Esri/calcite-design-system

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #2994 
The way the initial value and default were set would sometimes skip setting the internal color and mess up rendering if there was a custom value and format set by the user.
=> fix(color-picker): render current value when set initially with custom format

.github/ISSUE_TEMPLATE/bug.md, .github/need-info.yml, .github/workflows/need-info-close.yml, .github/workflows/need-info-verify.yml, CONTRIBUTING.md
**Related Issue:** #2962 
Repro samples and the full issue template format will now be required when logging bugs. 
- Updated the contributing doc and bug issue template to mention the new requirement
- Added a new [github action](https://github.com/benelan/need-info-action) to automatically request more info and close the issue if none are provided
- If an issue has a `need more info` label it will be closed in three days unless info is provided, so keep that in mind when adding the label manually
=> chore: new bugs require a repro sample

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #3035
Fixes an issue where the X/Y coordinates were sampled incorrectly while dragging the color field thumb when the component was placed within another shadow DOM root. 
**Note**: I'm looking at adding a specific test to catch this that doesn't involve an additional test suite run within shadow DOM.
=> fix(color-picker): fix mouse tracking logic when moved within another component's shadow DOM

src/components/calcite-action-bar/calcite-action-bar.e2e.ts, src/components/calcite-action-bar/calcite-action-bar.tsx, src/components/functional/CalciteExpandToggle.tsx
**Related Issue:** #3025
fix(action-bar): Better handling of overflow actions on smaller screens #3042
- Modifies the mutationObserver to listen to `subtree` changes.
- Calls resize on `connectedCallback`
- Checks resize for an actual height greater than 0 before continuing.
- Cleans up code for resizing based on the host element clientHeight.
- Cleans up code for a slot name.
=> fix(action-bar): Better handling of overflow actions on smaller screens

src/components/calcite-sortable-list/calcite-sortable-list.scss, src/components/calcite-sortable-list/calcite-sortable-list.tsx, src/components/calcite-sortable-list/readme.md, src/components/calcite-sortable-list/resources.ts
**Related Issue:** #2889
* Updates to use flex column layout 
* Adds `layout` property that defaults to "vertical"
=> fix(sortable-list): updated to use column layout

src/components/calcite-checkbox/calcite-checkbox.scss
**Related Issue:** #2880 
This fixes the `calcite-checbox` size shrink when it is unchecked & focusout and matches with size of checkbox when checked set to true
=> fix(checkbox): resize calcite-checkbox when unchecked & focusout

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2481
Fixes an issue where slider's maxValue thumb can't be moved via pointer if thumbs overlap at min edge. (Repro with [Storybook iframe url](https://esri.github.io/calcite-components/iframe.html?id=components-controls-slider--range&args=&knob-min=5&knob-min-label=Temperature,%20lower%20bound&knob-min-value=5&knob-max=100&knob-max-label=Temperature,%20upper%20bound&knob-max-value=5&knob-step=10&knob-ticks=10&knob-snap=true&knob-label-handles=true&knob-label-ticks=true&viewMode=story))
=> fix(slider): move maxValue thumb when thumbs overlap at min edge

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2480
Fixes an issue where a non-histogram range slider's minValue thumb is not placed correctly when both minValue and maxValue are `0`. ([Repro with Storybook iframe url](https://esri.github.io/calcite-components/iframe.html?id=components-controls-slider--range&knob-min=-100&knob-min-label=Temperature,%20lower%20bound&knob-min-value=0&knob-max=0&knob-max-label=Temperature,%20upper%20bound&knob-max-value=0&knob-step=1&knob-ticks=20&knob-label-ticks=true&knob-label-handles=false&viewMode=story))
=> fix(slider): align minValue thumb when both minValue/maxValue are zero

src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2881 
Slider was executing the emit change function on page load. Now it only executes the function on changes.
=> fix(slider): stop emitting change on page load

.github/workflows/teams-release-msg.yml
- When a github release is published this action will run
- It gets the release version using the tag
- Waits 30 min to make sure we have time to release to npm
- Sends the message to the CC teams channel
=> chore(action): automatically notify teams channel about releases

.lintstagedrc.json, package.json
Use prettier to format yml files the same way we do for other file types
=> chore: format yml files using prettier

.github/workflows/pr-bot.yml
**Related Issue:** #3077
The milestone action is failing on PRs by dependabot. This is by design for security reasons, as described [here](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).
I [changed](https://github.com/benelan/milestone-action/blob/main/src/main.ts#L13-L15) the action to skip PRs by dependabot for the time being until I think of a better solution.
=> chore(actions): fix milestone action to stop failing on dependabot prs

src/components/calcite-stepper-item/calcite-stepper-item.scss
**Related Issue:** #2715 
This  fix  removes the `margin-bottom` of container in `calcite-stepper-item ` and apply it to the `:host `element
=> fix(stepper-item): remove margin-bottom for calcite-stepper-item

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2480 (follow-on to pr #3083)
Fixes an issue where a histogram range slider's minValue thumb is not placed correctly when both minValue and maxValue are 0. ([Repro with Storybook iframe url](https://esri.github.io/calcite-components/iframe.html?id=components-controls-slider--histogram&args=&knob-min=-10&knob-min-value=0&knob-max=1&knob-max-value=0&knob-ticks=1&knob-label-handles=true&knob-label-ticks=true&viewMode=story))
(The highlighted histogram range will still need to be fixed in #2914.)
=> fix(slider): align histogram minValue thumb when both minValue/maxValue are zero

src/assets/styles/_type.scss, src/assets/styles/readme.md
**Related Issue:** #2728
Updated `--calcite-font-weight-bold` from `700` to `600` and updated styles README to reflect that change.
=> refactor (calcite-font-weight-bold): updated weight to 600

.github/workflows/assign-for-verification.yml, .github/workflows/need-info-close.yml
- Created two new github secrets:
- PRIMARY_CONTACT: a single username that will be the primary point of contact used in github actions. Right now the value is `benelan`
- SECONDARY_CONTACTS: A comma separated list of secondary contacts. It can be as many as needed. Right now the value is `jcfranco, julio8a`
- Changed all gh actions with hardcoded usernames to use the new gh secrets
- Changed the gh action that assigns verifiers for installed issues to randomly select a secondary contact if it is the primary contact's issue
=> chore: use github secrets for verifier usernames

CONTRIBUTING.md
- Cleaned up the existing contributing doc
- Added a section about issue management
=> docs(contributing): add issue management section

src/components/calcite-tree-item/calcite-tree-item.e2e.ts, src/components/calcite-tree-item/calcite-tree-item.tsx, src/demos/calcite-tree-scales.html
**Related Issue:** #2112
Fixes an issue where a tree-item with "ancestors" selection-mode would appear as selected, but its ancestor tree-items would not load with an `indeterminate` checkbox. Now ancestors will render with their indeterminate checkboxes on initial page load.
(The fix borrows the logic from calcite-tree's private [`updateAncestorTree`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tree/calcite-tree.tsx#L231-L236) method.)
=> fix(tree-item): update `indeterminate` on ancestor tree-items when `selected` on load

src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** #3071
fix(dropdown): Set scroller height to zero when not active. #3071
=> fix(dropdown): Set scroller height to zero when not active. #3071

support/deployNextFromTravis.ts
**Related Issue:** #3057 
Updates the `deployNextFromTravis.ts` to no longer fail the process when it handles an error. This would have a side-effect of failing the entire Travis build:
> If the script returns a nonzero status, deployment is considered a failure, and the build will be marked as “errored”.
☝🏼  from https://docs.travis-ci.com/user/deployment/script/
**Example errored build from https://app.travis-ci.com/github/Esri/calcite-components/builds/237925338**
```
Determining @next deployability 🔍
Building deployable candidate ⚙️
Deploying @next 🚧
- prepping package...
An error occurred during deployment ❌
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @esri/calcite-components@1.0.0-beta.65 util:deploy-next-from-travis: `ts-node --project ./tsconfig-node-scripts.json …
```
=> ci: avoid failing process for handled errors

src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.tsx
**Related Issue:** #2624 
Match `combobox` height when selection mode is `multi `or `ancestor` with single-selection mode.
=> feat(combobox): match combobox height with single selection mode

src/components/calcite-shell/calcite-shell.tsx
**Related Issue:** #3037 
changed the incorrect slot name/description in the jsdoc tag.
=> docs(shell): change incorrect slot name and description

FAQ.md, src/7-faq.stories.mdx
- Added a brief explanation about slots to the faq doc
- Added the faq page to storybook since I will continue adding stuff here
=> docs(faq): add section about slots

src/components/calcite-modal/readme.md, src/components/calcite-shell/calcite-shell.tsx
**Related Issue:** #1476 
Its a bit hacky but it fixes the doc issue. Tested locally
=> docs(modal): allow scrolling on storybook

.github/ISSUE_TEMPLATE/refactor.md
Added an issue template for refactors
=> chore: add refactor issue template

.github/workflows/pr-screener.yml
Maybe the screener check is showing the old one since I named it the same thing? So I changed the new one from `screener` to `screen` lets so if that gets rid of this weird bug
=> build(ci): try to fix screener github bug

src/components/calcite-input/calcite-input.tsx
**Related Issue:** #3383
Added `enterkeyhint` property to input which specifies which type of `enter` key should be provided on a mobile keyboard
=> feat(input): add enterkeyhint property to specify mobile enter key type

.github/dependabot.yml
**Related Issue:** #3360
The other issue above I logged for this is having that weird checks caching issue so I logged a GH support ticket and linked that PR. That one won't be merged it is just for them to look into. So I am creating this one to replace it.
cc @jcfranco @driskull
=> chore(ci): run dependabot weekly

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/new-component.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/refactor.md, .github/ISSUE_TEMPLATE/research.md, .github/ISSUE_TEMPLATE/tooling.md
Sometimes people forget to fill out the title which is possible since we already prefill some of it. If we remove the prefilled part and people don't add a title then the issue won't submit. All of the titles are duplicates of the labels that are added to the issue so having both is redundant anyway
=> chore: remove title from issue templates

.github/workflows/pr-screener.yml
Tweak API key approach based on some examples:
https://github.com/saucelabs/sauce_bindings/blob/99c9ea7c3928031b741d2f78fd6433a6013a1cd4/.github/workflows/dotnet.yml
https://github.com/microsoft/fluent-ui-react/blob/3fa9cbca5cde7a5da98b3c71bfc4bed7a56c743d/.github/workflows/screener.yml
https://github.com/microsoft/fluent-ui-react/blob/3fa9cbca5cde7a5da98b3c71bfc4bed7a56c743d/build/screener/screener.config.js
=> ci: use environment variable to set Screener API key

.github/workflows/pr-screener.yml
This sets up Screener to run against merges to master. This should help test our theory that Screener needs to run on the base branch to keep all visual states up to date.
=> ci: run screener on base branch merges

src/components/calcite-action/calcite-action.stories.ts
This pr adds a `Default` story for `calcite-action` so that it appears on the deployed Storybook website.
=> test(action): adding a default story so that it shows up in the deployed Storybook

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #3142
This PR adds an `e2e` test to verify if the max value of the` calcite-slider` is capped to the provided `max` prop value
=> test(slider): add e2e test to verify maxValue capped to max prop

.github/workflows/pr-screener.yml, screener.config.js
Add commit sha to the screener config as recommended by Loyal. Hopefully this gets the screener integration back
=> build(ci): add commit sha to screener run

src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #3349
Dropdown items now have consistent padding for RTL/LTR as well as links/non-links.
Focus and Hover states are now consistent for both RTL/LTR and links/non-links.
Observe the behavior on demo Codepen before:
https://codepen.io/ellupp/pen/YzxZaQz?editors=1000
Current
https://user-images.githubusercontent.com/19231036/140199954-25bb7354-5879-4839-be77-d837c4fe329e.mov
=> fix(dropdown-item): match padding for RTL vs LTR and links vs non-links, consistent focus and hover states for all

src/components/calcite-tile-select/calcite-tile-select.e2e.ts, src/utils/label.spec.ts, src/utils/label.ts
**Related Issue:** #3344 
This fixes an issue where components with nested labelable components (either in shadow DOM or slotted) could potentially be associated with the label instead of the owning component. For example, in the following snippet, the label gets associated with the slotted button.
```html
<calcite-label>
Labeled input (wrapped) ⛔
<calcite-input>
<calcite-button id="action-slot" slot="action">Go</calcite-button>
</calcite-input>
</calcite-label>
```
Note that this is not an issue with for-associated labels.
```html
<calcite-label for=input>
Labeled input (for) ✅
</calcite-label>
<calcite-input id=input>
<calcite-button id="action-slot" slot="action">Go</calcite-button>
</calcite-input>
```
The label lookup occurs in component's `connectedCallback`, which is not guaranteed …
=> fix(label): avoid associating labels to nested labelable components

src/components/calcite-filter/calcite-filter.e2e.ts, src/components/calcite-filter/calcite-filter.tsx, src/components/calcite-filter/resources.ts
**Related Issue:** #2208 
This PR makes some tweaks to the existing, internal, filter component for its premiere:
```ts
interface HTMLCalciteFilterElement {
data: T[]; // deprecated
items!: T[]; // ✨ new✨
filteredItems: T[]; // T = the item type ✨ new✨
}
```
* The event detail will be deprecated in favor of this new property.
* `items` will be doc'd as required, but enforced via types next release
* `data` is deprecated and will be removed in next release as it was not publicly doc'd
* Would renaming data => `items` and `filteredData` => `filteredItems` or `filtered` be a better fit? If so, for this release, we can add them and deprecate `data` and remove in the next sprint since the filter was never publicly doc'd
* Do we need a story + SDK entry for this? Filter is useful for a …
=> feat(filter): add filter component

src/components/calcite-select/calcite-select.e2e.ts
Removes duplicate [labelable test](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-select/calcite-select.e2e.ts#L42).
✨:broom:✨
=> test(select): drop redundant test

CHANGELOG.md
Reported in https://github.com/Esri/calcite-components/issues/3371#issuecomment-963662726.
=> docs(changelog): add missing switch entry from beta 67

src/components/calcite-action/calcite-action.stories.ts
**Related Issue:** #3415
This PR reverts #3415 after verifying @driskull's fix in #3421 in the production Storybook website.
=> revert(action): reverting #3415 after verifying deployed story correctly displays

support/deployNextFromCI.ts, support/prepReleaseCommit.ts
- Logging does not work in the `prepReleaseCommit` script so I moved it to the `deployNextFromCI` one.
- I am trying to get the workflow to fail if the commit or push does not happen.
=> chore(ci): move logging to help troubleshoot next script

support/deployNextFromCI.ts
Added user information to the next deploy script based on this error message from the previous run:
https://github.com/Esri/calcite-components/runs/4158364090?check_suite_focus=true#step:5:55
=> chore(ci): add user information to next deploy script and refactor conditionals

support/prepReleaseCommit.ts
Last run tried to publish on the current next release and we noticed that it was linting on the commit:
https://github.com/Esri/calcite-components/runs/4159041103?check_suite_focus=true#step:5:60
=> chore(ci): log tags and add noVerify to commit on next release script

.github/workflows/deploy-next.yml, support/deployNextFromCI.ts, support/prepReleaseCommit.ts
- Added a new `ADMIN_TOKEN` secret with a PAT I generated. An admin token is needed in order to push to a protected branch
- Made the push `atomic` so it either all works or all fails
=> chore(ci): fix github action push issue on protected branch

src/components/calcite-list-item/calcite-list-item.scss, src/components/calcite-list/calcite-list.stories.ts
**Related Issue:** #3362
Keeps list-item from being too small when there's only a label or description.
Accomplished by adding padding around `label` or `description` when they are `:only-child`.
=> feat(list-item): add padding when there is only a label or only a description

package.json
This updates the start script to make sure Stencil build arguments are passed through.
=> build: ensure build script arguments are passed through

.github/workflows/pr-merge.yml, support/deployNextFromCI.ts
Use the same github actions bot account for all of our ci stuff. Right now two of them are using a different `actions@github.com` account.
https://github.com/actions/checkout/discussions/479#discussioncomment-625461
=> chore(ci): use the same bot account for all actions

.github/workflows/pr-merge.yml
I had previously restricted the action to only allow a user to run the merge action on their own PRs. However this means no one could merge the PRs created by github actions, so I added a case for that
=> chore(ci): allow users to run merge action in prs created by bot

.github/workflows/update-deps.yml, .github/workflows/update-doc.yml
**Related Issue:** #3509
Some of the gh actions were hardcoded as node version 14. I changed them to `lts/*` which uses the latest LTS version, in this case v16
=> chore(ci): bump node versions to latest lts in gh actions

src/components/calcite-input/calcite-input.tsx, src/components/calcite-input/readme.md, src/components/calcite-input/usage/Native-events.md
**Related Issue:** #3474
This PR exposes the `calciteInputChange` event since the internal native `change` event can no longer be used after the changes introduced by #2570.  [There is already a test for this event in the code](https://github.com/Esri/calcite-components/blob/14ff2993e4e00dc885b0a5b3747c05d82b4f0bab/src/components/calcite-input/calcite-input.e2e.ts#L537-L574), so no need to add any additional ones for the purpose of this PR.
=> feat(input): add calciteInputChange event

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #782
Cursor behavior: 
The default behavior for input is to move the cursor to the beginning of the input when pressing Arrow Up. This results in cursor jumping back and forth as the value changes. The code now prevents this default behavior. 
Rate to match native input:
The input behavior now imitates the native HTML input type=“number”. The rate of increment/decrement is matched to be 100ms.
Now that the interval is shorter, pressing down too hard would result in incrementing/decrementing twice, which is why a local var is used as a flag to ignore the first interval call. It should start only if the user really intends to hold. 
e2e
This is followed with an update in count of emitted events in previous e2e tests.
=> fix(input): prevent default behavior of cursor jumping to the beginning of input, match rate of native input type=number (100ms)

src/components/calcite-input/calcite-input.e2e.ts
**Related Issue:** #3540
Skip the following unstable tests as these don't always provide a consistent value. 
correctly increments and decrements on long hold on mousedown and step is set to a decimal
should emit an event every 100ms on keyboard down ArrowUp/ArrowDown and stop on keyboard up
=> test(input): skip unstable input test

src/components/calcite-input-time-picker/calcite-input-time-picker.tsx
**Related Issue:** #2333
Specify that the `input-time-picker` step property is in seconds
=> docs(input-time-picker): specify step property is seconds

src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #3552 
This moves the color-picker's initialization logic to `componentWillLoad` to ensure initial properties/attributes are processed properly. 
* There is no automated test for this as it seems to be only reproducible with the `custom-elements` output target, which our E2E test setup does not use.
* We should audit all components to see if they suffer from the same issue
* Cloned [`calcite-components-examples`](https://github.com/Esri/calcite-components-examples/)
* Updated `rollup` example to follow  codesandbox from the issue description: https://codesandbox.io/s/calcite-components-color-picker-initial-value-setting-in-custom-elements-bundle-t3seb?file=/src/main.js
* Created a local calcite-components build with the fix and npm linked both
* Verified that the …
=> fix(color-picker): ensure props/attrs are initialized consistently

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #3109 
This fix make sure the corresponding thumb is focused on` click `and the closest thumb `:focus` is set to true when the user click on track.
=> fix(slider): focus respective thumb when click on track for range slider

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
This PR fixes a regression introduced by https://github.com/Esri/calcite-components/issues/3443 ([repro case](https://codepen.io/jcfranco/pen/MWvMQWM)). 
cc @benelan
=> fix(input): fix inconsistent value stepping

src/components/calcite-input/calcite-input.tsx
This refactors the value nudge interval to use a flag instead of keeping track of a counter.
=> refactor(input): simplify code for value nudging

src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** ##1688
When calciteDropdownItemSelect closes the dropdown, transitionEnd fires for each property transitioned.
this.calciteDropdownClose.emit() fires on the 'opacity' property when this.active changes to false, but opacity then is transitioned twice (I think for icon and popper repositioning). Changed it to a property 'visibility' that fires only once when closing.
=> fix(dropdown): stop calciteDropdownClose event from firing twice when closing the dropdown

.github/need-info.yml, .github/workflows/need-info-close.yml, .github/workflows/stale.yml
- A bunch of PRs closed as stale that I had to reopen. PRs shouldn't close as stale and delete the branch.
- I also gave people an extra couple of days to provide needed info before an issue closes
=> chore(ci): dont close prs and give more time to provide more info

src/components/calcite-shell-panel/calcite-shell-panel.tsx, src/utils/dom.ts
**Related Issue:** #2770
fix(shell-panel): Correct resizing of panels in RTL direction. #2770
- Fixes logic to handle resizing via mouse and keyboard when in RTL
- Deprecates `getElementDir`
- The problem with this utility method is that it only considers the dir attribute. Someone could set CSS `direction: rtl` and this wouldn't find it.
- The other reason for deprecating this is to make sure that components that use it evaluate if they actually need to. Many components can just use CSS logical properties instead.
- Adds `getElementStyleDir` which looks for the CSS direction value.
- This is only necessary when needing to know the direction to do something in JS.
cc @jcfranco
=> fix(shell-panel): Correct resizing of panels in RTL direction. #2770

src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** #1707
The error was occurring because icon is watching scale prop from modal, where “m” is set as a default. But the check for the scale on the icon was not accounting for medium scale, resulting in a large icon (and button) for a medium scale modal. Which made it shrink and expand when removing/adding the close button. The change in check now makes the modal scale reflect on icon for a corresponding scale.
https://user-images.githubusercontent.com/19231036/144491453-7321e9a1-e354-441f-8200-9d34a781c88d.mov
=> fix(modal): modal now doesn’t shrink when close button disabled

.husky/pre-push, package.json, support/checkSquashMergeableBranch.ts, support/matchConventionalCommit.ts
- You are allowed to push if there is at least one conventional commit on a branch
- pushes to master are exempt, but they still prompt to make sure its on purpose (version releases are non conventional commits)
=> chore(ci): prepush hook checks for a conventional commit on the branch

support/checkSquashMergeableBranch.ts
This fixes an issue when checking single-commit branch pushes:
```
@esri/calcite-components@1.0.0-next.314 util:check-squash-mergeable-branch
ts-node --project ./tsconfig-node-scripts.json support/checkSquashMergeableBranch.ts
/Users/juan6600/dev/projects/calcite-components/support/checkSquashMergeableBranch.ts:22
process.exitCode = commits.length === 1 ? (commits[0].test(conventionalCommitRegex) ? 0 : 1) : 0;
^
TypeError: commits[0].test is not a function
at runner (/Users/juan6600/dev/projects/calcite-components/support/checkSquashMergeableBranch.ts:22:57)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: failed to push some refs to 'github.com:Esri/calcite-components.git'
```
=> chore: fix squash-mergeable pattern check for single-commit branches

src/components/calcite-block-section/calcite-block-section.tsx, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-panel/calcite-panel.tsx, src/components/calcite-radio-button/calcite-radio-button.tsx, src/components/calcite-radio-group/calcite-radio-group.tsx, src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tip-manager/calcite-tip-manager.tsx, src/components/functional/CalciteExpandToggle.tsx
**Related Issue:** #2079
refactor: Use getElementStyleDir where applicable. #2079
- User getElementStyleDir where necessary. 
- This utility is used when direction is needed to perform a JS action such as keyboard events, icon swapping, etc.
- This utility shouldn't be used to set a class or styling. CSS logical properties should be used instead.
=> refactor: Use getElementStyleDir where applicable. #2079

src/components/calcite-radio-group-item/calcite-radio-group-item.e2e.ts, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-radio-group/calcite-radio-group.e2e.ts, src/components/calcite-radio-group/calcite-radio-group.tsx
**Related Issue:** #3120 
This fixes an issue where multiple  `calcite-radio-group` change events would fire from internal changes.
=> fix(radio-group): fix issue caused by radio group emitting change events from internal/programmatic changes

src/components/calcite-select/calcite-select.e2e.ts, src/components/calcite-select/calcite-select.tsx
**Related Issue:** #3239 #3241 
This improves `calcite-select` to update `selectedOption` as soon as there is an internal change to selection.
**Note:** this change causes `stencil The state/prop "value" changed during rendering. This can potentially lead to infinite-loops and other bugs.` warnings to display in the dev build when the component initializes, but it is expected as `value` and `selectedOption` (read-only) are technically not used for rendering.
=> fix(select): ensure selecting item programmatically is reflected in selectedOption

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #3381
This adjusts the approach taken for https://github.com/Esri/calcite-components/issues/2060 where value would support being cleared with `null`/`undefined`. `value` will now be a string to make it easier for end-users and align with expectations when compared to `<input>`.
=> fix(input): ensure input's value is an empty string when cleared or set to null/undefined

src/components/calcite-filter/calcite-filter.e2e.ts, src/components/calcite-filter/calcite-filter.tsx, src/components/calcite-pick-list/shared-list-render.tsx
This is a follow-up from https://github.com/Esri/calcite-components/issues/2208#issuecomment-963767923. Note that this depends on https://github.com/Esri/calcite-components/pull/3475 landing first.
=> refactor(filter): enforce items prop via type

src/components/calcite-popover/calcite-popover.scss
**Related Issue:** #2720 
I was unable to reproduce this issue locally or on a codepen so I'm not sure if this resolves the issue. @driskull how did you repro and find this solution?
=> fix(popover): close button no longer partially hidden

.github/workflows/pr-screener.yml
- Don't run screener when the PR is only markdown changes
- We pay per # runs so this might save us some money and definitely some time
Test Repo
- Skips on markdown only pr: https://github.com/benelan/test/pull/59
- Skips on markdown only push: https://github.com/benelan/test/runs/4414667007?check_suite_focus=true 
- Runs on non-markdown only prs: https://github.com/benelan/test/pull/60
- Runs on non-markdown only pushes: https://github.com/benelan/test/runs/4414736288?check_suite_focus=true
This PR
- [Successfully skipped screener when I changed `md` to `yml`](https://github.com/Esri/calcite-components/runs/4414152312?check_suite_focus=true)
- [Successfully ran screener when I changed it back to `md`](https://github.com/Esri/calcite-components/runs/4414250825?check_ …
=> ci(screener): skip screener when a pr is only markdown changes

src/components/calcite-tabs/calcite-tabs.stories.ts
**Related Issue:** #3395
I forgot to remove the commented out section for the story. There is already another story that is meant to replace the commented out story
=> refactor(tabs): remove commented out story that is replaced

src/components/calcite-button/calcite-button.e2e.ts, src/components/calcite-button/calcite-button.tsx
**Related Issue:** #3533 
This fixes the spaced occupied by `<div>` wrapper of `calcite-loader` in button when width is set to `half | full` and `alignment = space-between | icon-start-space-between | icon-end-space-between`
=> fix(button): no longer render loader when width set to half or full

src/components/calcite-option/calcite-option.e2e.ts, src/components/calcite-option/calcite-option.tsx
**Related Issue:** #3242 
This updates `calcite-option'`s observer to cover changes to character data, which is used by Ember and possibly other frameworks.
=> fix(option): update label and value when character data changes

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
**Related Issue:** #3597
Fix bug where inside calcite label the combobox would retain focus style after blur.
=> fix(combobox): fix focus behavior inside calcite label (#3597)

.github/workflows/pr-screener.yml
**Related Issue:** #3636
@driskull put in a hefty PR linked above and screener was skipped when it shouldn't have been. I immediately [reverted](#3673) the skipping part of the action. After some digging it looked like the script didn't fetch enough for larger PRs. Matt helped me test on his branch and confirmed that the fix in this PR (`fetch-depth: 0` instead of `--deepen=100`) works.
https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
=> ci(screener): fix fetch depth when skipping screener on markdown only prs

src/components/calcite-tip-manager/calcite-tip-manager.scss
**Related Issue:** #3081 
This will allow to use global css variable `--calcite-animation-timing` for customizing duration for animations/transitions.
=> feat(tip-manager): allow customizing animation/transition duration

src/components/calcite-dropdown-item/calcite-dropdown-item.scss
**Related Issue:** #3690
Align items with heading in selection-mode:none.
=> fix(dropdown-item): align items with heading in selection-mode: none

.github/workflows/stale.yml
**Related Issue:** #1475
Issues that are in development should not be marked as stale
=> ci(action): issues in development do not become stale

src/components/calcite-button/calcite-button.scss, src/components/calcite-link/calcite-link.scss
**Related Issue:** #3081 
This will allow to disable animations for `calcite-button` & `calcite-link` when `--calcite-animation-timing-factor` is set to 0 and customize the duration of  animation/transition timing
=> feat(button,link): allow disabling animation and customizing animation/transition duration

src/components/calcite-input/calcite-input.e2e.ts
**Related Issue:** #3716
Skipping unstable test
`calcite-input › number type › allows decimals when the supplied step is a whole number`
=> test(input): skip unstable decimal step test

src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.stories.ts, src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/resources.ts
**Related Issue:** #3529 
This fix removes the `margin` added to the `.content `class when  `calcite-button` is passed with empty `icon-start | icon-end` prop
Ex:
`<calcite-button icon-end>Button</calcite-button>`
=> fix(button): remove extra margin when icon is empty

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2538
- `calciteInputInput` wasn't firing when the last character was a decimal.
Edit:
With these changes the functionality will be
Type "1" -> event fires w/ "1"
Type "." -> event fires w/ "1"
Type "2" -> event fires w/ "1.2"
Delete "2" -> event fires w/ "1"
=> fix(input): input event fires when number ends with a decimal

src/components/calcite-label/calcite-label.stories.ts, src/components/calcite-switch/calcite-switch.scss
**Related Issue:** #3694 
Fixes `outline` of `calcite-switch` when toggled  with `calcite-label`  which currently is set to `black` by Chrome and edge browsers.
=> fix(switch): switch no longer has black outline when toggled with label

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html, src/utils/number.spec.ts, src/utils/number.ts
**Related Issue:** #3053
- Sanitize leading zeros, e.g. `000000` and extra dashes, e.g. `-22----4-` which were being emitted and used for the value.
- The zero example is now `0`, however it will still display all of the zeros in the input until a different number is entered. We are trying not to restrict the ability to type stuff (cc @eriklharper)
- The extra dashes example is now `-224`. Same idea, you can type them but they are sanitized out of the value. Then typing another number removes the extra dashes from the displayed number as well.
- Removed a skipped test which is no longer valid after these changes
- Added a test for the zeros and a test for the dashes
=> fix(input): sanitize extra dashes and leading zeros from number input value

support/prepReleaseCommit.ts
Right now the README is updated with `next` versions. From a product standpoint, the `next` versions should not be the recommended version in our project README. The people who need to use `next` will know how to do so, but the general public should use the `beta` versions.
=> ci(release): don't update cdn versions in readme on next releases

src/components/calcite-block/calcite-block.scss, src/components/calcite-block/calcite-block.tsx
**Related Issue:** #3684
Only render `.title` node is **heading** or **summary** is used.
Also adds some styles for some edge cases, e.g. for 
- collapsible but without heading and summary
- icon without heading and summary
=> fix(Block): only render title node when heading or summary is used

package.json
The last couple releases, the new tag was not pushed with the rest of the changes (package.json/readme/changelog). Adding `--atomic` to ensure the tag pushes, and if it doesn't it will give me a chance to troubleshoot.
=> ci(release): ensure tags are pushed when releasing

src/components/calcite-tree-item/calcite-tree-item.scss
**Related Issue:** #3081 
This will allow to disable animations for `calcite-tree-item` when `--calcite-animation-timing-factor` is set to `0` and customize the duration of animation/transition timing
=> feat(tree-item): allow disabling animation & customizing animation/transition duration

src/components/calcite-alert/calcite-alert.scss
**Related Issue:** #3081 
This will allow to disable animations for `calcite-alert` when `--calcite-animation-timing-factor` is set to 0 and customize the duration of animation timing
=> feat(alert): allow disabling animation and customizing animation/transition duration

.stylelintrc-postcss.json, package-lock.json, package.json, stencil.config.ts
This wires up postcss + stylelint + https://www.npmjs.com/package/stylelint-use-logical-spec to ensure the CSS output uses [logical props](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties). 
Note that this is using the default configuration and will transform all properties that have a logical equivalent. We can tweak this if we need to prevent some properties from being transformed.
=> build: use postcss to ensure CSS logical prop usage

.stylelintrc-postcss.json, package-lock.json, package.json, stencil.config.ts
This reverts commit 6dbcfaf9066aea16f6da9b9433050a2b0ffb9f94.
**Related Issue:** #3688 
Reverts 6dbcfaf9066aea16f6da9b9433050a2b0ffb9f94 since it introduced visual regressions. Will fix and resubmit in a separate PR.
=> revert: use postcss to ensure logical prop usage

.github/workflows/stale.yml
- When I stopped the stale action from closing PRs, I forgot to change the message.
=> ci(action): change misleading stale pr message

package-lock.json, package.json
This should fix build issues for projects bundling `calcite-components`. cc @ffaubry
=> build(deps): change form-request-submit-polyfill to be a dependency

.gitignore, .vscode/extensions.json, .vscode/settings.json
Set up vscode workspace settings to use stylelint.
**Note**: as [suggested in the `vscode-stylelint` plugin](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint#:~:text=for%20more%20details.-,Disable%20VS%20Code%27s%20Built%2DIn%20Linters%20(optional),-To%20prevent%20both), built-in style linting is disabled to have `stylelint` be the source of truth
=> chore: configure vscode workspace settings and extensions

.github/workflows/teams-release-msg.yml
- Removed unnecessary 30 min delay
- Changed the name of the GH secret. Since creating this, I added another teams notification for builds with the secret `TEAMS_WEBHOOK_URI_BUILD`. So I want to specify that this secret is for release for consistency
- Added `#changelog` to the link so you don't have to scroll to find the changes
- Hardcoded the action version just incase the owner pushes breaking changes to master
- https://github.com/marketplace/actions/ms-teams-action?version=v1.0.1
=> ci(action): cleanup teams release notification

src/components/calcite-switch/calcite-switch.scss
**Related Issue:** #3694 
- Fixes `outlines-offset` for `calcite-switch` on focus with pointer or keyboard .
- Outline appears when toggled by itself or using `calcite-label`
=> fix(switch): add back outline offset on focus

src/components/calcite-input/calcite-input.tsx, src/utils/number.spec.ts, src/utils/number.ts
**Related Issue:** #3627
- The PR linked above moved to use an empty string for the value instead of `null`. I made the same change for pasting invalid numbers.
=> fix(input): set value to empty string instead of null or undefined

src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-radio-button/calcite-radio-button.scss, src/components/calcite-radio-button/calcite-radio-button.tsx
**Related Issue:** #3783
This pr fixes checkbox and radio-button so that they no longer allow focusing when disabled.  Testing for this change will be covered with Screener visual snapshots in this PR: https://github.com/Esri/calcite-components/pull/3571
=> fix(checkbox,radio-button): prevents disabled checkboxes and radio-buttons from receiving keyboard or mouse focus

.github/workflows/update-deps.yml, package-lock.json, package.json
- Ran `npm audit fix`
- Added `npm audit fix` to the `deps:update` npm script.
- Tweaked the deps update gh action to try to get it to work again, based on [this suggestion](https://github.com/actions/runner/issues/241#issuecomment-924327172)
=> chore(deps): audit and fix non breaking vulnerabilities when updating deps

.github/need-info.yml, .github/workflows/need-info-close.yml
- Created a new label `incomplete issue report`
- Changed the bots that asks for more info and eventually close those issues to use the new label
- This frees up the `need more info` label for internal use
=> chore(action): change the label used for requesting more info

.github/workflows/deploy-next.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-screener.yml, .github/workflows/update-deps.yml, .github/workflows/update-doc.yml
- Start caching the npm packages when running the checks/actions to speed things up. 
- https://github.com/actions/setup-node#caching-packages-dependencies
=> ci: cache npm packages to speed up actions

.browserslistrc
This will better match the requirements defined in https://doc.arcgis.com/en/arcgis-online/reference/browsers.htm and https://developers.arcgis.com/javascript/latest/system-requirements/.
=> chore(browserslist): use last 2 major versions for Safari and iOS

src/utils/dom.spec.ts, src/utils/dom.ts
refactor(dom): Allow multiple slot names in getSlotted utility.
Allows usage of utility in `calcite-modal`...
```
this.hasFooter = !!this.el.querySelector(
`[slot=${SLOTS.back}], [slot=${SLOTS.secondary}], [slot=${SLOTS.primary}]`
);
```
=> refactor(dom): Allow multiple slot names in getSlotted utility.

src/components/calcite-action-bar/calcite-action-bar.scss, src/components/calcite-panel/calcite-panel.scss
**Related Issue:** #3699
Updates how header height is achieved in order to match the height to an Action when there's only a heading in the Panel's header.
Also updates border colors to match.
Of course, if there's a summary or long heading text, the alignment no longer happens.
=> fix(Panel): match header height and border color to Action

.vscode/extensions.json
Unrecommending deprecated extension  :grimacing:
=> chore: remove tslint from recommended extensions

src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-date-picker/calcite-date-picker.e2e.ts, src/components/calcite-inline-editable/calcite-inline-editable.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/tests/utils.ts
**Related Issue:** #1004
This PR eliminates the ambiguity of global timeout and interval methods. This is needed for to avoid mismatching types since `@types/node/globals.d.ts` is getting pulled in automatically from `jest` dependencies.
=> refactor: use window or global when calling global interval or timeout methods

src/components/calcite-value-list/calcite-value-list.e2e.ts, src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #3685
The value list was only emitting order change events when reordered with the mouse (via SortableJS). This PR adds the eventing logic when reordered via keyboard. 
Note that the event be emitted as each item is moved with the up/down keys.
=> fix(value-list): emit list order change event when value list items are reordered via the keyboard

src/components/calcite-value-list/calcite-value-list.e2e.ts, src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #3685 
This fixes a bug introduced by #3816 where the event payload when reordering items via the keyboard included the list elements instead of the ordered values.
cc @jmanke
=> fix(value-list): include ordered values in list order change event payload

src/components/calcite-pick-list/calcite-pick-list.tsx, src/components/calcite-pick-list/shared-list-logic.ts, src/components/calcite-value-list/calcite-value-list.tsx
Types the list change event payload for both pick and value lists. I had to use `any` for the shared implementation since it requires some advanced TS-fu. I'll create a follow-up issue for that.
=> refactor(pick-list, value-list): add proper types to list change event payload

.github/workflows/pr-merge.yml
Give the primary contact (me as of now) the ability to merge PR branches by commenting. If CI stuff ever gets messed up, I'll be able to merge the branches with a fix so someone doesn't accidently install with no checks (as an example).
=> chore(action): allow primary contact to merge pr branches

.github/workflows/pr-merge.yml
**Related Issue:** #3823
Reverting PR that broke the merge action.
=> revert: allow primary contact to merge pr branches

src/components/calcite-input-time-picker/calcite-input-time-picker.tsx, src/components/calcite-time-picker/calcite-time-picker.tsx
**Related Issue:** #2333
Cleanup doc
=> docs(input-time-picker, time-picker): synchronize value/step prop descriptions

src/components/calcite-color-picker-swatch/resources.ts
**Related Issue:** #3160
Double the alpha value on the border when theme is light to make it a bit more pronounced.
=> fix(color-picker-swatch): double the alpha value on the border when theme is light to make it a bit more pronounced

package-lock.json, package.json
Bumps `@esri/eslint-plugin-calcite-components` to the latest version, which includes a fix for the runtime linting error that shows up when committing.
=> build(deps): bump @esri/eslint-plugin-calcite-components

src/components/calcite-input/calcite-input.tsx
**Related Issue:** #3053
Restricts typing more than two hyphens, which is how native input does it.
=> fix(input): restrict typing more than two hyphens

src/components/calcite-input-date-picker/calcite-input-date-picker.e2e.ts, src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
Stems from https://github.com/Esri/calcite-components/issues/3659.
This introduces an `calciteInputDatePickerChange` event and deprecates the use of `calciteDatePickerChange` and `calciteDatePickerRangeChange` from that component since they should be considered internal.
=> feat(input-date-picker): add calciteInputDatePickerChange event

src/components/calcite-radio-button/calcite-radio-button.scss
**Related Issue:** #3875 
cherry picked the commit from the external PR linked above so that all of the CI runs correctly.
---
Produces following UI on browsers with OS in high contrast mode.
Firefox 95
Chrome 97
=> fix(radio-button): show selection in high contrast

.github/ISSUE_TEMPLATE/enhancement.yml
An unneeded `value` property was left in during my copy/paste rampage
=> chore(template): remove value from enhancement field

.github/need-info.yml
**Related Issue:** #3893
The new issue template format installed in the PR linked above can mark sections as required. Therefore we no longer need to check to see if all sections are included
=> chore(ci): remove obsolete check for valid new issues

src/components/calcite-input/calcite-input.e2e.ts
Testing for when both 'ArrowUp' and 'ArrowDown' are pressed at the same time most recently pressed key takes over.
=> test(input): skip unstable test 

src/components/calcite-link/calcite-link.e2e.ts, src/components/calcite-link/calcite-link.tsx, src/demos/calcite-link.html
**Related Issue:** #3758
feat(calcite-link): Add support for download attribute. #3758
=> feat(calcite-link): Add support for download attribute. #3758

screener.config.js
This PR updates the screener config to ignore the "Overview" stories.
=> ci(screener): ignore overview stories

src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion-item/calcite-accordion-item.tsx, src/components/calcite-accordion/calcite-accordion.scss, src/components/calcite-accordion/calcite-accordion.stories.ts, src/components/calcite-accordion/calcite-accordion.tsx
**Related Issue:** #1225 
This fix will set the `background-color` of the `calcite-accordion` to `transparent` in FireFox & Safari.
=> fix(accordion): no longer has white background when set to transparent

src/components/calcite-panel/calcite-panel.tsx, src/components/calcite-shell/calcite-shell.tsx, src/components/calcite-tree-item/calcite-tree-item.tsx
refactor(panel, shell, tree-item): Add keys to conditionally rendered slots.
=> refactor(panel, shell, tree-item): Add keys to conditionally rendered slots.

screener.config.js
This PR updates Screener's Chrome version to the latest at the time of authoring, which is 97.
=> ci(screener): updating to Chrome 97

screener.config.js
This pr increases the screen resolution as recommended by Sauce Labs support.  This is an experiment to see if this change will resolve mouse pointer out of bounds issues.
=> ci(screener): enlarging screen resolution

src/components/calcite-input/calcite-input.tsx
=> refactor(input): add types where they are any

src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #[1955](https://github.com/Esri/calcite-components/issues/1955)
All `EventListeners` added  will be removed once DOM it is disconnected via lifecycle method `disconnectedCallback( )`
=> refactor(slider): remove drag event listeners on component disconnected

src/components/calcite-input/calcite-input.e2e.ts
**Related Issue:** #3938
Simplify test to have a consistent result. 
Test error
FAIL src/components/calcite-input/calcite-input.e2e.ts (402.713 s)
● calcite-input › when both 'ArrowUp' and 'ArrowDown' are pressed at the same time most recently pressed key takes over
expect(received).toBe(expected) // Object.is equality
Expected: "1"
Received: "2"
695 |     await page.keyboard.down("ArrowUp");
696 |     await page.waitForChanges();
> 697 |     expect(await element.getProperty("value")).toBe("1");
|                                                ^
698 |     await page.keyboard.down("ArrowDown");
699 |     await page.waitForTimeout(delayFor2UpdatesInMs);
700 |     await page.keyboard.up("ArrowUp");
at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:697:48)
=> test(input): when both 'ArrowUp' and 'ArrowDown' are pressed at the same time most recently pressed key takes over

screener.config.js
=> ci(screener): restoring pre-Sauce integration settings

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/need-info.yml
- Provide context for the repro samples we provide in the issue templates
- Change the JSBin to use `next`, it was still at `beta.64` 
- Should it be `next` or `latest`? I think having it as `next` can help prevent unnecessary issues by having people test the unreleased changes.
=> docs(template): provide context for the repro samples

package.json
Pinning node16 / npm8 for volta users
=> chore: pin node 16 and npm 8 for volta

readme.md
Our sketch UI kit is super far behind the components, so I'm removing it from the README until it is updated. People will be really frustrated if they take the time to design something and it is completely different in the component library. 
We may want to add a disclaimer notice in the dev docs until figma/sketch gets caught up. Thoughts @macandcheese @jcfranco ?
=> docs(readme): remove sketch info until it is up to date

src/components/calcite-date-picker/utils.spec.ts, src/components/calcite-date-picker/utils.ts
**Related Issue:** #3965 
When a specific file cannot be found if a locale with regional code does not exist, then the date picker will seek for just the basic lang code instead.
For example: `pt-BR` -> `pt`
Before
After
=> fix(date-picker): update utils locale to get the lang code if regional code is not found

.github/workflows/pr-merge.yml
- Allows the users in the `PRIMARY_CONTACT` (a single user name) and `SECONDARY_CONTACTS` (comma separated usernames) github secrets to use the merge action on all PRs
- Important for situations like getting screener working on all the PRs again
=> ci: allow primary and secondary contacts to merge on all prs

src/components/calcite-date-picker/assets/calcite-date-picker/nls/pt-BR.json
Stemmed from https://github.com/Esri/calcite-components/issues/3925#issuecomment-1018028342. This PR adds `pt-BR.json` and updates some entries `pt-PT.json` per the CLDR locale dataset.
One thing I did notice was that `unitOrder` and `placeholder` from our files are different from the CLDR data. 
```json
{
"default-calendar": "gregorian",
"separator": "/",
"unitOrder": "DD/MM/YYYY",
"weekStart": 7,
"placeholder": "DD/MM/YYYY",
...
}
```
```json
{
"default-calendar": "gregorian",
"separator": "/",
"unitOrder": "dd/MM/yy",
"weekStart": 7,
"placeholder": "dd/MM/yy",
...
}
```
Worth noting that aside from Bulgaria (bg), all other locale files use the `MM`, `DD` and `YYYY` tokens. 
I kept the previous versions since that's what is being used by the input date picker …
=> fix(date-picker, input-date-picker): update pt-BR and pt-PT localization files

src/components/calcite-dropdown/calcite-dropdown.e2e.ts
**Related Issue:** #3936
This was flaking for 2 reasons:
- the event open/close fires after transition ends, so I needed to check for it in the right sequence and preceded with await page.waitForChanges();
- in the open position it fires calciteDropdownOpen, and in close: calciteDropdownClose; had to check for both
=> test(dropdown): correct logical errors in the test

src/components/calcite-tooltip/calcite-tooltip.tsx
Looks like these were copy and pasted from `popover` and the component name wasn't changed
=> docs(tooltip): use the correct component name

src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.stories.ts
**Related Issue:** #3891
Saw this while doing some mobile testing in another product. Using `flex-1` allows the element to scale down with no minimum, so it won't force a flex wrap.
=> fix(combobox): fix stacking icon on very narrow combobox (#3891)

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html
**Related Issue:** #3956
- `-123` was considered an invalid number in `ar` and `et` locales. 
- The issue started when adding the `componentShouldUpdate` lifecycle method in [this PR](https://github.com/Esri/calcite-components/pull/2036). 
- It looks like there was [no number sanitation at the time of that PR](https://github.com/Esri/calcite-components/blob/c0cc3ed5b6334282e5f7a4b415030331dae5f3c9/src/utils/number.ts). Can you think of any use cases where this method is needed @eriklharper? It seems like the new(ish) number sanitation covers it. 
- The existing tests passed locally and the functionality was the same in the demos. The test I added fails on master but passes on this branch.
=> fix(input): correct negative values in ar and et locales

src/components/calcite-switch/calcite-switch.scss
* Use canvasText system color to show selected state of switch control. This color matches the normal text color, outlines, and borders in high contrast mode
**Related Issue:** #3987
Fix provides a color to the switch track when the control is selected.
=> fix(switch): provide a selected color to track element (#3987)

.storybook/helpers.ts, src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx
**Related Issue:** #3234
fix(dropdown): Reposition floating menu correctly. #3234
- Makes sure that when a dropdown's placement is "top" but it doesn't have room to open that way, that it opens "bottom".
- Adds screenshot test via story
- Fixes story placement options
=> fix(dropdown): Reposition floating menu correctly.

.storybook/helpers.ts, src/components/combobox/combobox.stories.ts, src/components/combobox/combobox.tsx
**Related Issue:** #3868
fix(combobox): Align with dropdown logic and repositioning. #3868
- Makes sure when a combobox is placed at the bottom of a page that when it opens it opens "top".
- Adds screenshot test via story
- Refactors positioning and maxItems logic to be in sync with dropdown. (uses resizeObserver)
- Fixes issue where maxItem height was being applied when items where less than maxItems.
=> fix(combobox): Align with dropdown logic and repositioning

src/components/color-picker/color-picker.e2e.ts, src/components/color-picker/color-picker.tsx, src/components/fab/fab.e2e.ts, src/components/fab/fab.tsx, src/components/inline-editable/inline-editable.e2e.ts, src/components/inline-editable/inline-editable.tsx, src/components/split-button/split-button.e2e.ts, src/components/split-button/split-button.tsx
**Related Issue:** #4007
fix(fab, color-picker, inline-editable, split-button): Set calcite button type. #4007
- Make sure button types are "button" so forms don't submit.
=> fix(fab, color-picker, inline-editable, split-button): Set calcite button type

src/components/pick-list/readme.md, src/components/pick-list/usage/Sub-groups.md
=> docs(pick-list-item): change invalid heading property to label

src/components/input/input.e2e.ts, src/components/input/input.tsx, src/demos/input.html
**Related Issue:** #4063
Reverts #4020 which is a fix for `et` and `ar` locales. That fix created a regression which effects the `en` locale, which is most of our users, and therefore takes priority. I will reopen the other issue and find a solution that does not cause this regression.
=> revert(input): correct negative values in ar and et locales

src/components/panel/panel.tsx, src/components/shell-center-row/shell-center-row.tsx, src/components/shell-panel/shell-panel.tsx
**Related Issue:** https://community.esri.com/t5/calcite-design-system-questions/calcite-panel-heightscale-optional-or-not/td-p/1137264
- Fixes typo and sets heightScale to optional when for `panel` where there is no default
=> docs(panel, shell-panel-shell-center-row): fix heightScale typo

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml
- Remove the CDN vs NPM checkboxes as suggested by @jcfranco 
- Removed default values from some of the required fields and added placeholders so someone can't submit without entering something.
Bug template: https://github.com/benelan/test/issues/new?assignees=&labels=bug%2C0+-+new%2Cneeds+triage&template=bug.yml
A11y template: https://github.com/benelan/test/issues/new?assignees=&labels=a11y%2Cbug%2C0+-+new%2Cp+-+high%2Cneeds+triage&template=accessibility.yml
=> chore: reorganize a11y and bug issue templates

readme.md
**Related Issue:** #3681
Added a couple sentences to the readme. I'll also add it to the dev site getting started page here:
https://developers.arcgis.com/calcite-design-system/get-started/#ii-assets
=> docs(readme): the local assets directory must be named assets

src/components/popover-manager/popover-manager.e2e.ts, src/components/popover-manager/popover-manager.scss, src/components/tooltip-manager/tooltip-manager.e2e.ts, src/components/tooltip-manager/tooltip-manager.scss
**Related Issue:** #3900
fix(popover-manager, tooltip-manager): Misalignment of tooltips in FireFox #3900
Firefox needs manager components to be positioned relative. Tried positioning shadow dom container as relative but that didn't do anything.
=> fix(popover-manager, tooltip-manager): Misalignment of tooltips in FireFox #3900

src/components/input/input.e2e.ts, src/components/input/input.tsx
**Related Issue:** # none
After the changes in https://github.com/Esri/calcite-components/pull/3915, setting `element.value = ''` will no longer clear a `<calcite-input type="number">` that previously had a numerical value.  Setting `element.value = null` does clear the input, but that gives us TS errors since we build with `strictNullChecks: true`.
I added a failing test for this case, and then fixed it with a small change to the input component.
=> fix(input): Allow "" to clear a number input

src/components/functional/ExpandToggle.tsx
**Related Issue:** #3978
fix(action-bar, action-pad): Remove warning when when expanding with expand tooltip #3978
- This was setting referenceElement to `false` which isn incorrect.
=> fix(action-bar, action-pad): Remove warning when when expanding with expand tooltip #3978

src/assets/styles/_popper.scss, src/components/popover/popover.e2e.ts
fix(popover, tooltip, combobox, dropdown, input-date-picker): Hide popover that escapes reference element's boundary (and so it appears detached) or when the reference element is fully clipped and hidden from view.
- Hides popover that escapes reference element's boundary (and so it appears detached)
- Hides popover when the reference element is fully clipped and hidden from view.
- Demo: https://popper.js.org/docs/v2/modifiers/hide/#demo
https://popper.js.org/docs/v2/modifiers/hide/
data-popper-reference-hidden: This attribute gets applied to the popper when the reference element is fully clipped and hidden from view, which causes the popper to appear to be attached to nothing.
data-popper-escaped: This attribute gets applied when the popper escapes the reference …
=> fix(popover, tooltip, combobox, dropdown, input-date-picker): Hide popover when the reference element or popover is out of view.

src/components/date-picker/assets/date-picker/nls/bs.json, src/components/date-picker/assets/date-picker/nls/ca.json, src/components/date-picker/assets/date-picker/nls/cs.json, src/components/date-picker/assets/date-picker/nls/da.json, src/components/date-picker/assets/date-picker/nls/de.json, src/components/date-picker/assets/date-picker/nls/el.json, src/components/date-picker/assets/date-picker/nls/en-AU.json, src/components/date-picker/assets/date-picker/nls/es.json, src/components/date-picker/assets/date-picker/nls/et.json, src/components/date-picker/assets/date-picker/nls/fi.json, src/components/date-picker/assets/date-picker/nls/fr.json, src/components/date-picker/assets/date-picker/nls/hr.json, src/components/date-picker/assets/date-picker/nls/hu.json, src/components/date-picker/assets/date-picker/nls/it.json, src/components/date-picker/assets/date-picker/nls/lt.json, src/components/date-picker/assets/date-picker/nls/lv.json, src/components/date-picker/assets/date-picker/nls/mk.json, src/components/date-picker/assets/date-picker/nls/nb.json, src/components/date-picker/assets/date-picker/nls/nl.json, src/components/date-picker/assets/date-picker/nls/pl.json, src/components/date-picker/assets/date-picker/nls/ro.json, src/components/date-picker/assets/date-picker/nls/ru.json, src/components/date-picker/assets/date-picker/nls/sl.json, src/components/date-picker/assets/date-picker/nls/sr.json, src/components/date-picker/assets/date-picker/nls/sv.json, src/components/date-picker/assets/date-picker/nls/tr.json, src/components/date-picker/assets/date-picker/nls/uk.json, src/components/date-picker/assets/date-picker/nls/vi.json
**Related Issue:** #4075 
Sets the first day of the week according to https://olga8614.github.io/calendars/ for the following locales:
BS, CA, CS, DA, DE, EL, ES, ET, FI, FR, HR, HU, IT, LT, LV, NB, NL, PL, RO, SL, SR, SV, TR, UK, VI
MK (missing from issue) was updated following https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/weekData.json#L153
=> fix(date-picker): set correct first day of week for all locales

src/components/tree-item/tree-item.e2e.ts, src/components/tree-item/tree-item.tsx
**Related Issue:** #3123
This is a partial fix for #3123 that restores the correct right arrow key behavior.  The fix now focuses the first child in an expanded subtree.
=> fix(tree-item): Pressing right arrow key focuses first child when the tree-item contains an expanded subtree

src/components/button/button.tsx, src/components/link/link.tsx
**Related Issue:** #3284 
This will remove the existing `childElType` state in `button` & `link` components and determine the `type` in render method.
=> refactor(button,link): remove childElType as state

src/components/accordion/accordion.scss, src/components/accordion/accordion.tsx
**Related Issue:** #4120 
`transparent` and `minimal` appearance no longer has border in accordion
=> fix(accordion): transparent appearance no longer has border

src/components/slider/slider.stories.ts, src/components/slider/slider.tsx, src/demos/slider.html
**Related Issue:** #1156 
This fix will assign the `aria-role=slider` to appropriate element `div` and enable the screen readers to identify slider.
=> fix(slider): aria-role is assigned to appropriate element

src/components/pick-list/shared-list-logic.ts
this reverts commit 52f19d1
**Related Issue:** #4168
This code change was meant for pr branch #4177 so reverting it to put this code fix at it's proper pr branch
=> revert(pick-list): this change was in the wrong pr branch that got merged by accident

support/preact.ts
When all the files were renamed without the `calcite` prefix, it caused the generated preact types to be incorrect. This led to a lot of typescript errors where we're using a ref pointing to these types as preact was then thinking the CalciteInput was an Input.
=> fix: solve regression with preact type generation

package-lock.json, package.json
This drops `posthtml` as it's no longer used. 
Stems from https://github.com/Esri/calcite-components/pull/4189#issuecomment-1059575141
=> build(deps): drop unused posthtml

src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx, src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.tsx, src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-date-picker/input-date-picker.tsx, src/components/popover/popover.e2e.ts, src/components/popover/popover.tsx, src/components/tooltip/tooltip.e2e.ts, src/components/tooltip/tooltip.tsx, src/tests/commonTests.ts
**Related Issue:** #3727 
This PR updates all popper-owning components to toggle the `eventListeners` modifier based on the popper's visibility (as suggested [here](https://popper.js.org/docs/v2/tutorial/#performance)). 
This also cleans up some internals for combobox. It seemed to have multiple state props based on `active`.
=> fix(combobox, dropdown, input-date-picker, popover, tooltip): disable scroll event listeners for hidden poppers

tailwind.config.ts
This adds [content paths](https://tailwindcss.com/docs/content-configuration) per the following build warning:
```
warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
```
=> build(tailwind): add content paths

package-lock.json, package.json
Bumps Popper to the latest version, which includes improvements to positioning in shadow DOM (see https://github.com/floating-ui/floating-ui/releases/tag/v2.11.3).
=> build(deps): bump @popperjs/core from 2.11.2 to 2.11.4

src/assets/styles/_popper.scss, src/components/popover/popover.e2e.ts
**Related Issue:** #4197
This restores visibility for escaped poppers. Poppers with hidden reference elements will continue to be hidden.
=> fix(popover, tooltip, combobox, dropdown, input-date-picker): display escaped poppers

src/components/pick-list/shared-list-logic.ts, src/components/pick-list/shared-list-tests.ts
**Related Issue:** #4208 
This fixes an issue where grouped pick list items were removed regardless if they were slotted as a group's parent item or not.
=> fix(pick-list): only remove group if removable item is slotted as parent

src/components/dropdown-item/dropdown-item.tsx
**Related Issue:** #4215 
This fixes an issue that shows up in the custom-elements output target where a dropdown item is initialized before its ancestors are ready. I am not sure if it's possible to cover this in our automated test suite. I'll have to investigate.
I'll create a separate issue to go over our components to identify similar cases.
=> fix(dropdown-item): ensure dropdown items are initialized properly

src/components/action-bar/action-bar.e2e.ts, src/components/action-bar/action-bar.tsx, src/components/action-pad/action-pad.e2e.ts, src/components/action-pad/action-pad.tsx
**Related Issue:** #4169
fix(action-bar, action-pad): allow expanding via API when expandDisabled. #4169
Allows action-bar/action-pad to still change `expanded` state even when `expandDisabled` is true. `expandDisabled` only applies to showing the expand/collapse button at the bottom.
=> fix(action-bar, action-pad): allow expanding via API when expandDisabled. #4169

src/components/input-date-picker/input-date-picker.scss
cc @jcfranco
**Related Issue:** #2655 
This fixes a regression introduced by https://github.com/Esri/calcite-components/commit/083d283caf719eed91cb1f5bd71b4584864b5e61 (see https://github.com/Esri/calcite-components/commit/083d283caf719eed91cb1f5bd71b4584864b5e61#r68872701).
=> fix(input-date-picker): fix issue where clicking on the date picker would immediately close it

.github/workflows/pr-untruncated.yml
This adds an action to avoid truncated PR titles. When a commit title is too long, GitHub truncates it when a PR is created. This can lead to incomplete changelog entries ([example](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md?plain=1#L113)).
=> build(action): ensure PR title is not truncated

src/components/slider/slider.e2e.ts, src/components/slider/slider.tsx
**Related Issue:** #4174
fix(slider): Properly reset and submit form value when a range is used. #4174
- Changes `value` type to allow for an array.
- The change to value is to support form resetting but also form submission. Currently, form submission wouldn't submit values for range sliders.
- We might want to update clamping/stepping for range values later
=> fix(slider): Properly reset and submit form value when a range is used

src/components/tab-nav/tab-nav.tsx, src/components/tab-title/tab-title.tsx, src/components/tab/tab.tsx, src/components/tabs/tabs.tsx
This splits up refactor changes from https://github.com/Esri/calcite-components/pull/4250/.
=> refactor(tab-title, tab): clean up

.github/workflows/pr-e2e.yml, .github/workflows/pr-screener.yml
**Related Issue:** #4295
The storybook internal documentation pages use `mdx`. Right now e2e and screener is skipped for PRs that only contain markdown (`md`). This PR extends the skipping logic to `mdx` too.
=> ci: skip e2e and screener on md and mdx only PRs

.husky/pre-push
Kitty ran into an error pushing due to the prepush hook which ensures conventional commits. 
Relevant bit:
`Error: Command failed: git log --format=%B geospatialem/test --not master | tr '`
It looks like its an issue due to Windows. I disabled the hook so she can push and I'll work on making it OS agnostic.
=> ci: disable merge squash prepush due to windows error

package.json, stencil.config.ts
Appends the CC version number to the preamble so users can find out which version a product is using. I had to change the `release:prepare` npm script to build after bumping the version number rather than before.
For example, in the browser dev tools for Map Viewer you can't find a version:
This PR will display the version in the preamble comment like:
```js
/*!
* All material copyright ESRI, All Rights Reserved, unless otherwise specified.
* See https://github.com/Esri/calcite-components/blob/master/LICENSE.md for details.
* v1.0.0-beta.80
*/
```
If we are worried about character/line count, I can replace `master` with the version instead, like:
```js
/*!
* All material copyright ESRI, All Rights Reserved, unless otherwise specified.
* See …
```
=> build: add version to preamble

.husky/pre-push, support/checkSquashMergeableBranch.ts
**Related Issue:** #4307
Makes the squash-mergeable prepush script work on Windows (Kitty tested and confirmed). It also still works on Unix:
=> ci: squash mergeable script os agnostic

src/utils/label.spec.ts
https://github.com/ionic-team/stencil/blob/main/CHANGELOG.md#-2130-2022-01-24 added support for  `MockEvent#composedPath()`, so no need for our polyfill anymore.
=> test: remove unnecessary polyfill

.github/workflows/pr-e2e.yml, .github/workflows/pr-screener.yml
Mixed up my regex and glob pattern matching. It didn't break anything other than running screener/e2e on my markdown-only PR
=> ci: fix markdown PR check skipping logic

src/components/tab-nav/tab-nav.e2e.ts, src/components/tab-nav/tab-nav.tsx
**Related Issue:** #2885 
This modifies `tabs` to use a resize observer instead of relying on the window being resized to recompute the active tab underline. Previously, it would not update the active tab styling when initially hidden.
=> fix(tabs): update active tab styling on resize

.github/workflows/deploy-storybook.yml
Automatically deploy storybook at the beginning of the week.
I didn't test this in my test repo because it seems like more work than its worth. Its pretty simple and should work, but things won't explode if it doesn't. Worst case scenario it fails and I fix it.
=> ci: automatically deploy storybook once a week

src/components/tile/tile.scss, src/components/tile/tile.stories.ts
**Related Issue:** #4240 
Fixes padding space for `content-start` slotted items when `dir=rtl`
=> fix(tile): match content-start spacing when dir set to rtl

src/components/button/button.e2e.ts, src/components/button/button.tsx
**Related Issue:** #4117
fix(button)!: Change type property to be "button" by default. (#4117)
=> fix(button)!: Change type property to be "button" by default

src/components/list-item/list-item.scss, src/components/list-item/list-item.tsx, src/components/list-item/resources.ts, src/components/list/list.stories.ts, src/demos/list.html
**Related Issue:** #4336
When no center content is rendered, `content-end` and `content-start` slots occupy the available space in the container.
@benelan Not sure if I added the correct Milestone or not.
=> feat(ListItem): updates flex definitions on start and end content slots

.github/workflows/assign-for-verification.yml, .github/workflows/need-info-close.yml, .github/workflows/pr-merge.yml
I changed the names of some GitHub secrets. I also slightly changed the functionality of the issue verification action.
- The GH Secret for issue verifiers is now `ISSUE_VERIFIERS` (previously `PRIMARY_CONTACT` and `SECONDARY_CONTACTS`). 
- The secret still takes a comma separated list of usernames (currently me and @geospatialem). 
- It now assigns all verifications to everyone on the list, and they can verify any of them when they have the time. I can switch it back to randomly assigning again if people prefer, but I want to wait until Kitty has more practice verifying enhancements (which don't have repro samples).
- The GH Secret for merging anyone's PR with a comment is now `PRIMARY_MAINTAINERS`  (previously `PRIMARY_CONTACT` and `SECONDARY_CONTACTS`). 
- The …
=> ci: change the gh secrets with usernames for clarity

src/components/input/input.e2e.ts, src/components/input/input.tsx, src/utils/locale.ts, src/utils/number.ts
**Related Issue:** #4040 #3956
The negative character is different in some locales, and it was not being delocalized, which caused the number to be invalid.
=> fix(input): correctly de-localize negative numbers in ar and et

src/components/color-picker/color-picker.e2e.ts, src/components/color-picker/color-picker.tsx
**Related Issue:** #2033 
Fixes an issue where setting `value` more than once would emit. Specifically, it would emit on even `value` sets.
=> fix(color-picker): setting value programmatically twice or more in a row will no longer emit change/input events

.github/workflows/deploy-storybook.yml
For some reason, running `npm run release:docs` on my machine doesn't work. I have to run the commands separately. It looks like the action is having the same problem.
=> ci: fix storybook deployment action

src/components/input/input.e2e.ts, src/demos/input.html, src/utils/locale.spec.ts, src/utils/locale.ts
**Related Issue:** #3956 
It was adding a weird character which doesn't get logged in the dev tools console but does log in the codepen console.
https://codepen.io/benesri/pen/RwxYKWv?editors=0011
Is it Friday yet? lol
From [`formatToParts` on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts):
- To fix the issue I stripped everything except numbers, hyphens, and decimals. 
- I also added locale spec tests since we didn't have any. I removed the `et` negative/decimal e2e test because it is covered in the locale spec ones.
=> fix(input): negative numbers delocalize correctly in ar locale

src/utils/locale.spec.ts, src/utils/locale.ts
**Related Issue:** #3956
When adding the locale spec tests in the PR above, the group separators were not working properly for a lot of locales (33 failed tests if I remember correctly). I fixed and cleaned up the locale utils, so now everything is passing.
=> fix(input): correctly delocalize numbers with group separators

package.json, stencil.config.ts
https://github.com/Esri/calcite-components/pull/4381 bumped color to version 4.2.3, which [removed `numeric separators`](https://github.com/Qix-/color/releases/tag/4.2.3), so we can drop the `@babel/plugin-proposal-numeric-separator` rollup plugin (introduced in https://github.com/Esri/calcite-components/pull/2822/).
=> build: remove unnecessary numeric separator plugin

readme.md
=> docs(readme): change loader property from isActive to active

src/components/action-bar/action-bar.e2e.ts, src/components/action-bar/action-bar.tsx, src/components/action-pad/action-pad.e2e.ts, src/components/action-pad/action-pad.tsx
**Related Issue:** #2033 
This fix will make sure `calciteActionPadToggle` & `calciteActionBarToggle` events emit only on user interaction
=> fix(action-pad, action-bar): toggleChange event emit only on user interaction

CHANGELOG.md
This removes the breaking changes note since updates to https://github.com/Esri/calcite-components/pull/4423 made the change to no longer be breaking.
=> docs: remove invalid breaking changes entry

src/components/color-picker/color-picker.e2e.ts
=> test(color-picker): import getElementXY from util

conventions/Testing.md
Add a short section about commonTests and utils.
=> docs(internal): add section about test helpers and utilities

src/components/combobox/combobox.e2e.ts, src/components/filter/filter.tsx, src/utils/filter.ts
**Related Issue:** #4348
It was matching the `constant` attribute's `undefined` default value. 
```js
/u/.test(undefined) === true
```
Fixing it this way also works for `calcite-filter`, rather than only filtering based on `label` and `value` properties (relevant for #4425)
=> fix(combobox, filter): only test regex on string properties when filtering

.github/ISSUE_TEMPLATE/test.yml
Modify the unstable test template to fit all test cases including new, unstable tests, or Screener. 
- Renamed the template to "test.yml" for its new use
- All original content remains, but some fields are now optional
- An additional section was added to the top of the template indicating the type of test being requested
=> chore: modify test template

.github/workflows/pr-bot.yml, .github/workflows/pr-milestone.yml
Right now the current milestone is being added when the PR is opened. We need everything in a past-due milestone to be closed before we can close the milestone. Stale PRs are making it harder to close milestones. So it will be better to add PRs to milestones when they are merged, rather than opened.
=> ci: add current milestone when pr merged

src/components/filter/filter.e2e.ts, src/components/filter/filter.tsx, src/components/filter/resources.ts, src/components/input/input.e2e.ts, src/components/input/input.tsx, src/components/input/resources.ts
**Related Issue:** #4376 
This fixes a UI inconsistency with `calcite-filter` by refactoring it to use `calcite-input`'s `clearable` option. 
* Added `intlClear` prop
* Added default aria-label text for the clear button in case ☝️ is empty cc @geospatialem
=> fix(filter): fix inconsistent text-clearing UX

src/components/value-list-item/value-list-item.tsx, src/components/value-list/value-list.tsx
**Related Issue:** #4442
First of a series of updates across components to implement a style guide across our API references for consistency.
PR includes the following components API refs:
* value-list
* value-list-item
=> docs: consistent api refs for value-list and value-list-item

src/components/slider/slider.scss, src/components/slider/slider.stories.ts
**Related Issue:** #4126 
This PR sets `word-break` on the main container to prevent inheriting a value that could mess up the labels.
=> fix(slider): prevent parent word-break from breaking labels

.github/workflows/deploy-storybook.yml
Got a [new error](https://github.com/Esri/calcite-components/runs/6243148044?check_suite_focus=true#step:4:7696) for the storybook deployment action. Trying a solution found [here](https://github.com/storybookjs/storybook-deployer/issues/77#issuecomment-579745557)
=> ci: add ci flag and github actor to fix storybook deployment automation

src/utils/form.tsx
**Related Issue:** #4500
This PR adds a missing line to keep track of the bound reset method when a form control is added. This led to increased form reset event handlers being added and never removed.
=> fix(form): keep track of bound form reset event handlers to plug memory leak

src/components/date-picker-month/date-picker-month.tsx, src/components/date-picker/date-picker.stories.ts
**Related Issue:** #4283 
This fixes the wrong last dates of previous months displayed in locales such as `bg | sk`  in `date-picker` 
`locale=bg`
=> fix(date-picker): displays appropriate last date of previous month 

src/components/tab-title/tab-title.tsx
Let users know that setting the tab property affects what calciteTabsActivate emits.
=> docs(tab-title): calciteTabsActivate emits tab property or index position

src/demos/graph.html, src/demos/shell/popup-config-example.html, src/demos/theme/auto.html, src/index.html
**Related Issue:** #2622
1. Added remaining demos to the demo homepage, including:
*  graph
* input-date-picker
* theme
* animation
* handle
* shell
2. Updated demos with shell inclusion
* shell only spans the full window height
3. Theme switcher added to theme and shell example for the JSAPI
* map will also switch when theme switch is enabled (light vs. dark)
=> docs(demos): finalize demo homepage

src/components/graph/graph.scss, src/components/graph/graph.stories.ts, src/demos/graph.html
**Related Issue:** #4518
fix(graph): Set default height to 100%. (#4518)
The graph will now take up the available space of its parent.
Adds screener tests too.
=> fix(graph): Set default height to 100%

package.json
`support/prepReleaseCommit.ts` already adds and commits the relevant files. The extra `git add .` ends up staging all of the generated readmes which we don't want to manually commit. And then ammending the release commit with changelog fixes is slightly more annoying than if the readmes weren't staged 😅
=> ci: remove extra git add from release prepare

src/components/block/block.tsx
**Related Issue:** #4460
Add in the `@default` jsdoc tag to the `intlCollapse` and `intlExpand` props to display the values in our doc pages (compliments the resources.ts file contents).
=> docs(block): add default doc tag

src/components/list-item-group/list-item-group.tsx, src/components/list-item/list-item.tsx, src/components/list/list.tsx, src/components/loader/loader.scss, src/components/loader/loader.tsx
**Related Issue:** #4442 
API styling throughout all CC. This PR includes updates to list (and its children components) and loader.
1. related list components
- list
- list-item-group
- list-item
4. loader
- Includes styling docs
=> docs: consistent api styles

.eslintrc.json, package-lock.json, package.json
Added [`eslint-plugin-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc) with the recommended settings, except:
- Turned off [`require-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc#user-content-eslint-plugin-jsdoc-rules-require-jsdoc) which created empty jsdoc for every single function that wasn't doc'd. It could be worth setting it to `publicOnly` so that all of our exported functions are documented. Thoughts?
- Turned off [`check-tag-names`](https://www.npmjs.com/package/eslint-plugin-jsdoc#user-content-eslint-plugin-jsdoc-rules-check-tag-names) which threw warnings for our `slot` tags.
I have a separate `style` PR where I linted the code: #4551
With the current settings, if a function has a jsdoc (including something like `/** does XYZ */`) it …
=> build(deps): install jsdoc eslint plugin

src/components/list-item-group/list-item-group.tsx, src/components/list-item/list-item.tsx, src/components/list/list.tsx, src/components/tree-item/tree-item.tsx, src/components/tree/tree.tsx, src/components/value-list/value-list.tsx
**Related Issue:** #4442
Re-add backticks previously removed from:
* list
* list-item
* list-item-group
* tree
* tree-item
* value-list
=> docs: re-add backticks

src/tests/utils.ts
=> docs(internal): add jsdoc to test utils exported functions

src/components/stepper-item/stepper-item.scss
**Related Issue:** #4564 
* Removes the excessive outlines
* Adds an obvious selection indicator
* Make focus state obvious and work on different layouts
Changes produce this layout:
Colored states for non-active steps is not something that can be done in the high contrast mode. Additional text or visual clues will need to be used if a design is to work well in both normal and high contrast mode.
=> fix(stepper): Add high contrast specific styles to stepper

src/components/input-message/input-message.scss
**Related Issue:** #4291
The discrepancy between status active=false and status active=true font size was causing an odd scaling effect when transitioning all. There shouldn’t be any font size transitioning for message display, so the nonactive state shouldn’t have a size that is different from the active one. 
https://user-images.githubusercontent.com/19231036/168929796-b2e37cab-e249-4b8c-b38c-e3053767abd9.mov
=> fix(input-message): remove the scaling transition effect when displaying an input message

package.json, support/patchES5Helpers.ts
**Related Issue:** #4481 
This patches the `__spreadArray` tslib helper emitted from `buildEs5` to handle spreading of strings within arrays.
=> fix: patch __spreadArray helper to work around tslib bug (#4481)

package.json
`npm run start` was exiting with `1` because it appends flags to the build script, which was now appending it to the patch instead. I switched it to the prexisting `build:watch-dev` script, which is not getting patched. We don't need the es5 patch locally, it's just needed for releases.
Confirmed that the release is not failing with the patch: https://github.com/Esri/calcite-components/commit/120899649fb991a937c5c524304eff87f50ec084
@jcfranco can you confirm that the code is actually patched here:
https://unpkg.com/browse/@esri/calcite-components@1.0.0-next.473/dist/esm-es5/
=> ci: fix npm start script

src/components/input/input.scss
**Related Issue:** #4591
fix(input): Align type="time" correctly in Firefox. (#4591)
=> fix(input): Align type="time" correctly in Firefox

src/components/dropdown-group/dropdown-group.scss, src/components/dropdown-item/dropdown-item.scss, src/components/dropdown/dropdown.stories.ts
**Related Issue:** #4220
fix(dropdown-item, dropdown-group): text align to "start" by default.
=> fix(dropdown-item, dropdown-group): text align to "start" by default.

src/components/modal/modal.scss, src/components/modal/modal.tsx
**Related Issue:** #4442 
* Consistent API style guide references for `calcite-modal`.
* _Note_: Added a JSDoc `optional` tag for the `beforeClose` property instead of using the "Optionally" supporting text.
=> docs(modal): consistent api refs

src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts, src/components/tooltip/tooltip.tsx
**Related Issue:** #4399
feat(tooltip): Add property to close tooltip when referenceElement is clicked. (#4399)
=> feat(tooltip): Add property to close tooltip when referenceElement is clicked

src/components/panel/panel.scss
**Related Issue:** #4682
fix(panel): Add back z-index usage for internal component styles. (#4682)
This PR reverts the style changes in this one: https://github.com/Esri/calcite-components/pull/4182
The reasoning is here: https://github.com/Esri/calcite-components/issues/3724#issuecomment-1146461507
=> fix(panel): Add back z-index usage for internal component styles

src/components/tooltip/tooltip.scss
**Related Issue:** #4631
fix(tooltip): Remove internal flex display. (#4631)
The flex display is making `<span />` placed inside the tooltip act like a block element.
Demo can be seen here: https://codepen.io/afreitag/pen/KKQZmXP
=> fix(tooltip): Remove internal flex display. (#4631)

.github/workflows/change-milestone.yml
Created an action that moves issues from the previous, past due milestone to the current one. Only moves issues with one of these three labels:
- `0 - new`
- `1 - assigned`
- `2 - in development`
The action runs on Mondays. It won't do anything for the week between sprints since all of the movable issues were already moved. It automatically adds the `milestone adjusted` label to the issues it moves.
=> ci: add action to move issues to current milestone

src/components/tooltip/tooltip.tsx
**Related Issue:** #4442
API style guide consistency updates  for `calcite-tooltip`.
=> docs(tooltip): style guide api consistency

src/components/tooltip/TooltipManager.ts
It was preventing the `focusin` handler from being removed in `removeListeners()` because the `capture` flag was obscured when first adding the handler.
Looking to get this fix in quickly to unblock a Calcite upgrade to Field Maps ahead of the EA release next week. Is it worth a follow-on issue to add test coverage for this scenario?
=> fix(tooltip): Fix syntax typo in `TooltipManager`

src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx, src/demos/combobox.html, src/utils/filter.ts
**Related Issue:** #2115
enable` filter-disabled` prop support for `combobox-item` which is equivalent of `constant` prop.  deprecation of `constant` prop will follow.
=> refactor(combobox-item): enable filter-disabled prop support 

src/components/action/action.scss
**Related Issue:** #4702 
Adds a css variable to optionally set the indicator color on the action.
=> feat(action): Add css variable to override indicator color

src/components/accordion-item/accordion-item.scss, src/components/accordion-item/accordion-item.tsx, src/components/block/block.e2e.ts, src/components/block/block.scss, src/components/block/block.tsx, src/components/block/resources.ts, src/components/panel/panel.e2e.ts, src/components/panel/panel.scss, src/components/panel/panel.tsx, src/components/panel/resources.ts, src/components/stepper-item/stepper-item.scss, src/components/stepper-item/stepper-item.tsx
**Related Issue:** #4688 
- Deprecated `itemTitle` props in favor of `heading` in  `accordion-item` and `stepper-item` components
- Deprecated `itemSubtitle` , `summary` in favor of `description` in `accordion-item` , `stepper-item`,`block` & `panel` components
=> feat(accordion-item,stepper-item,block,panel): add heading & description prop 

src/components/modal/modal.e2e.ts
**Related Issue:** #4613
Removing the e2e test for the firstFocus property that was removed in #4671
=> test(modal): remove test for firstFocus property

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.e2e.ts, src/components/stepper/stepper.tsx
**Related Issue:** #4595
feat(stepper): Add calciteStepperItemChange event. (#4595)
- Adds new public event `calciteStepperItemChange`
- Added new internal event for handling only user interaction.
- Keeps other internal events needed for updating DOM. These could be removed during a refactor.
=> feat(stepper): Add calciteStepperItemChange event

src/components/accordion/accordion.tsx, src/components/action-bar/action-bar.tsx, src/components/action-pad/action-pad.tsx, src/components/action/action.tsx, src/components/button/button.tsx, src/components/color-picker/color-picker.tsx, src/components/dropdown-item/dropdown-item.tsx, src/components/handle/handle.tsx, src/components/input-time-picker/input-time-picker.tsx, src/components/rating/rating.tsx, src/components/slider/slider.tsx, src/components/stepper/stepper.tsx, src/components/tab-nav/tab-nav.tsx, src/components/tile-select/tile-select.tsx, src/components/tree-item/tree-item.tsx, src/components/value-list/value-list.tsx
**Related Issue:** #4731
fix: Make sure component setFocus methods do not throw error. (#4731)
When calling setFocus before the first render, an error may be thrown. This prevents that.
=> fix: Make sure component setFocus methods do not throw error

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.tsx
Updates typing of layout prop in stepper and stepper-item
**Related Issue:** #4766 
This extracts just the values that are relevant to Stepper from the shared Layout interface.
Note - we should probably move away from styling based on reflected props in a future update.
=> fix(stepper): remove invalid layout value (#4766)

src/components/tab-nav/tab-nav.scss, src/components/tab-title/tab-title.scss, src/components/tab-title/tab-title.tsx
**Related Issue:** https://github.com/Esri/calcite-components/issues/3682
Adjusts styling for long titles in bordered mode, and fix for cut off content in center alignment. 
- Long titles should now display properly in "bordered" mode.
- Center alignment should no longer cut off names 
- if the container is wide enough to display all items, it will appear center-aligned.
- if the container is not wide enough, the first tab will remain visible.
=> fix(tabs): update style for centered and bordered tab titles

.github/workflows/new-component-notify.yml
Adds automation  to notify CC design lead(s) when the `new component` label is added to an issue. 🤖
* The automation adds text to the issue's body `cc @<design-username>`  
* The design lead(s) are stored in a GH secret `CALCITE_DESIGNERS` 🔒 
* The entries in the secret will be entered as `<design-username>` or `<design-username1>, <design-username2>, ....` 
* The automation automatically adds in the `@` before the `<design-username>` text.
=> ci: notify leads of new component label

src/components/block/block.scss, src/components/block/block.stories.ts, src/components/block/block.tsx
**Related Issue:** #4116 
This will add a new prop `noPadding` which is defaulted to `false`. When `true`, it removes padding of the content slotted in `calcite-block`
=> feat(block): support noPadding property

src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.tsx, src/components/dropdown/resources.ts
Provide devs with more control of the components through additional hooks. For public events that are emitted after a transition finishes (in this case, opening/closing of the dropdown), we are now adding events that fire before the transition kicks off as well.
=> refactor(dropdown): added 'before' events for events that fire after transition

src/components/combobox/combobox.tsx
**Related Issue:** #4689 
Small follow-up: rename functions to be more explicit that it is a handler function as opposed to an event.
=> refactor(combobox): rename functions that emit open/close events

.github/workflows/stale.yml
**Related Issue:** #4598 #4599
Exempt stale epics from auto-closing
=> ci(stale): exempt epics from auto-closing

.github/workflows/deploy-next.yml, .github/workflows/deploy-storybook.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-screener.yml, .github/workflows/update-doc.yml
**Related Issue:** #4704 #4703
In the PRs above I had to change the GH Actions to use the `legacy-peer-deps` flag. For some reason I didn't think you could use that flag with `npm ci` but I was mistaken. Changing back to using `npm ci` since it is faster. Also adding the flag to the doc update which I missed last time.
=> ci: use npm ci to install deps

src/components/combobox/combobox.stories.ts, src/components/combobox/combobox.tsx
**Related Issue:** #4629 
- Adds support for `@Prop() placeholder-icon` which leads `placeholder` text in  `calcite-combobox `.
- This will fix the leading space added to the `placeholder` text in combobox when the `combobox-item` contains icon at start.
=> feat(combobox): add support for placeholder icon & no longer display leading space for placeholder text

src/components/input/input.e2e.ts, src/components/input/input.tsx
**Related Issue:** #3976
Add `selectText` method which calls the native input's `select` method.
=> feat(input): add selectText method

src/components/radio-group/radio-group.e2e.ts, src/components/radio-group/radio-group.tsx
**Related Issue:** #4662 
This fixes an issue where the radio group would not assign its default value properly.
=> fix(radio-group): fix form reset for radio groups with initial selected item

src/components/color-picker/color-picker.stories.ts, src/components/color-picker/color-picker.tsx
**Related Issue:** #4685 
This addresses an issue where the internal canvas (for color field and hue slider) would stay the same size as its initial scale.
=> fix(color-picker): resize color field/hue slider canvas on scale change

src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/date-picker-month-header/resources.ts, src/components/date-picker/assets/date-picker/nls/th.json, src/components/date-picker/date-picker.stories.ts, src/components/date-picker/utils.ts
**Related Issue:** #4571 
This PR updates the date picker to use the Buddhist calendar for the Thai locale. 
Additional locales may opt in simply by changing the default calendar in the locale metadata.
=> fix(date-picker): update Thai locale to use Buddhist calendar

src/components/input/input.tsx
**Related Issue:** #4172
Switches mouse events to pointer events to improve interactivity regardless of input type.
=> fix(input): update number stepper buttons to work with both mouse/touch inputs

src/components/color-picker/color-picker.e2e.ts, src/components/color-picker/color-picker.scss, src/components/color-picker/color-picker.tsx
**Related Issue:** #4171 
Switches mouse events to pointer events to improve interactivity regardless of input type.
=> fix(color-picker): update color-field and hue slider to work with both mouse/touch inputs

.github/workflows/create-milestone.yml
Adding an action that creates a new milestone twice a month (1st and 15th). I am also changing the sprint title to include the year to make sure they are all unique. Using ISO format to make sorting easier when we need to look back.
=> ci: automatically create new milestones

.github/workflows/create-milestone.yml
I used the label event to make sure the action worked on my test repo, and then forgot to move it here 😅
=> ci(create-milestone): remove label event used for testing

src/components/radio-group-item/radio-group-item.scss
* Adds highlight color to solid selected item
* Adds bold outline to outline selected item
* Modifies icon color on solid selected item for better contrast
**Related Issue:** #4873 
Modifies the radio group selections to look like this on High Contrast mode:
Unfortunately, the text *ALWAYS* has its own un-style-able background so it doesn't have the same background as the radio group "button".
=> fix: (radio group) - apply forced-colors styles

src/components/input/input.e2e.ts, src/components/input/input.scss, src/components/input/input.tsx
**Related Issue:** #4879, PR #4870
Added:
- `:disabled` pseudo-class to `.number-button-item`, set to `pointer-events-none` 
- a backup check for the `disabled` prop before the number value can be nudged
- test to make sure `disabled` stepper buttons should not be interactive/nudge the number
=> fix(Input): type number spinner buttons will no longer interact when disabled

src/components/tooltip/tooltip.tsx
**Related Issue:** #4864
fix(tooltip): Add aria-live="polite" for screen readers. (#4864)
=> fix(tooltip): Add aria-live="polite" for screen readers

src/components/input/input.stories.ts, src/utils/locale.ts
**Related Issue:** #3079
Sets the default numbering system for arab languages to latin. This is for browser consistency so that Firefox behaves like Chrome and Safari. According to the locale team, this is what our arab users want and it is the way other esri products do it, including the JSAPI team.
Users can still use the arab numbering system like:
```html
<calcite-input numbering-system="arab" type="number" value="5"></calcite-input>
```
=> fix(input): set the default numbering system for arab languages to latin

src/components/popover/popover.tsx
**Related Issue:** #4865
Fix enables `popover` to receive context for screen readers. 
Prior to the fix screen readers would only receive the popover content when using the down arrow key.
The [`aria-live="polite"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) will provide the popover content politely (once the screen reader reads through all the context)
=> fix(popover): Add aria-live="polite" for screen readers

src/components/radio-group-item/radio-group-item.tsx
**Related Issue:** #3431
Identified as part of the a11y audit in 2021.
When interacting with `radio-group-item` users must have an accompanying `aria-label` depicting the value. 
Added an `aria-label={value}` to the `<Host>` to ensure users are provided context when interacting with the `radio-group` and `radio-group-item`s.
=> fix(radio-group-item): Add aria-label providing context to users

.github/workflows/pr-milestone.yml
**Related Issue:** #4881
Today is the last day of the sprint and it should still be considered the current milestone. However PRs are adding the next milestone. This PR fixes that issue so the sprint ending today will be used.
[relevant code](https://github.com/benelan/milestone-action/commit/c68adeb50cd9b0da6549310a7d8287aa70e2ac5f#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR44)
=> ci(add-milestone): use milestone until the day after its due date

src/components/action-bar/action-bar.scss, src/components/action-pad/action-pad.scss
fix(action-bar, action-pad): Background color should be transparent on host.
`@extend %component-host;` sets a background color but these components shouldn't have one since they expand.
=> fix(action-bar, action-pad): Background color should be transparent on host.

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx, src/demos/input-time-picker.html
**Related Issue:** #1947
- added `readOnly prop` support
- modified the documentation to reflect the difference between `disabled` and `readOnly`:
> `readOnly` input is still focusable but won’t display the controls or allow for changing the value, whereas `disabled` controls can not receive focus and generally do not function as controls until they are enabled, refer to [MDN here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly#:~:text=The%20difference%20between%20disabled%20and%20readonly%20is%20that%20read%2Donly%20controls%20can%20still%20function%20and%20are%20still%20focusable%2C%20whereas%20disabled%20controls%20can%20not%20receive%20focus%20and%20are%20not%20submitted%20with%20the%20form%20and%20generally%20do%20not%20function%20as%20controls%20until%20they%20 …
=> feat(input-time-picker): add readOnly prop support

src/components/card/card.scss, src/components/card/card.stories.ts
**Related Issue:** #4895
fix(card): Prevent content from overflowing when corners are rounded. ([#4895](https://github.com/Esri/calcite-components/issues/4895))
=> fix(card): Prevent content from overflowing when corners are rounded

.github/workflows/assign-for-verification.yml
The verification action now also assigns designers to installed issues when the issue contains the `figma changes` label. The label should be added during triage when the issue involves:
- new components
- new properties
- changed property names/types/values
- new or changed css variables
- anything that registers as a change in screener
=> ci: assign designers to installed issues when figma changes are required

src/components/accordion-item/accordion-item.scss, src/components/combobox-item-group/combobox-item-group.scss, src/components/combobox-item/combobox-item.scss, src/components/combobox/combobox.scss, src/components/dropdown-item/dropdown-item.scss, src/components/dropdown/dropdown.scss, src/components/tree-item/tree-item.scss, src/components/tree/tree.scss
**Related Issue:** #4912 
Updates to the components' high contrast rendering
**Accordion**
**Combobox**
**Dropdown**
**Tree**
=> fix(accordion, combobox, dropdown, tree): remove excessive borders in high contrast mode

.storybook/manager-head.html
This blocks our internally-used Storybook from search engines to promote https://developers.arcgis.com/calcite-design-system/ as the source-of-truth doc site.
https://developers.google.com/search/docs/advanced/crawling/block-indexing
=> chore(storybook): block indexing from search engines

src/components/pick-list-item/pick-list-item.tsx
**Related Issue:** #3373
fix(pick-list-item): Make label property required. (https://github.com/Esri/calcite-components/issues/3373)
=> fix(pick-list-item): Make label property required. (#3373)

.prettierrc.json
Updates Prettier config according to https://prettier.io/docs/en/options.html#deprecated-jsx-brackets.
=> chore(linting): replace deprecated prop for same line bracket

src/components/alert/alert.tsx, src/components/combobox/combobox.tsx, src/components/dropdown/dropdown.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/modal/modal.tsx, src/components/popover/popover.tsx
**Related Issue:** #4902
fix(modal, alert, combobox, dropdown, input-date-picker, popover): Scope open and close events to component. (#4902)
Makes sure that transition events are only fired when they occur on the element they are supposed to.
=> fix(modal, alert, combobox, dropdown, input-date-picker, popover): Scope open and close events to component

src/assets/styles/includes.scss, src/components/stepper-item/stepper-item.scss
**Related Issue:** #4955 
The disabled style mixin was no longer applied to the host as the stepper item uses `display:contents`, which basically replaces the host container with its children. This extracts the host styles from that mixin to be applied individually in this case.
=> fix(stepper-item): restore disabled styling on horizontal layout stepper items

src/components/stepper-item/stepper-item.scss
**Related Issue:** #4956 
The vertical layout applies margin to item content. This is not needed when the stepper's layout is horizontal.
=> fix(stepper-item): remove bottom margin on content from horizontal layout

src/components/stepper-item/stepper-item.scss
**Related Issue:** #4954 
This fixes a mouse-cursor regression introduced by #4367.
Note: this has no accompanying screenshot test as Screener does not capture the mouse cursor
=> fix(stepper-item): avoid cursor-pointer on item content for horizontal layouts

support/patchES5Helpers.ts, support/prepReleaseCommit.ts
These got left out from https://github.com/Esri/calcite-components/pull/4890/.
=> build: add __dirname vars that are missing in ESM

src/components/alert/alert.tsx, src/components/combobox/combobox.tsx, src/components/dropdown/dropdown.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/modal/modal.tsx, src/components/popover/popover.tsx
**Related Issue:** #4963
JSDoc comments were replaced by regular block ones accidentally and this reverts the change.
=> docs(alert, combobox, dropdown, modal, input-date-picker, popover): restore JSDoc comments

src/components/combobox/combobox.tsx
**Related Issue:** #4918, #4917 
Adds support to `combobox` selection(s) and provides context to users of assistive technologies.
Includes:
1. When the `combobox` is in focus and has a value, or values selected, announces the selections via JAWS, NVDA, and VoiceOver
3. Adds an announcement to a `combobox-item` selection on-demand via JAWS, NVDA, and VoiceOver
_Of Note_: There were two eslint rules preventing commits from occurring in the component, including:  
- `require event emitter type` (line [285](https://github.com/Esri/calcite-components/compare/geospatialem/4918-fix-combobox-selection-a11y?expand=1#diff-8eb51d8ec5c3891740279618f20aa76593ead68fae27b701743289a341689bcfR285)), and  
- `react jsx no bind` (line [1020](https://github.com/Esri/calcite-components/compare/geospatialem/491 …
=> fix(combobox): Announce selection to assistive technologies in focus and on demand

support/prepReleaseCommit.ts
This got overlooked in https://github.com/Esri/calcite-components/pull/4890.
=> build: fix dynamic import in prepReleaseCommit

support/cleanOnProcessExit.ts, support/prepReleaseCommit.ts, support/releaseToGitHub.ts
Fixes additional imports from #4890.
=> build: fix dynamic ESM imports

src/components/action-bar/action-bar.scss, src/components/action-bar/action-bar.stories.ts, src/components/action-pad/action-pad.scss, src/components/action-pad/action-pad.stories.ts
**Related Issue:** #2380
fix(action-bar, action-pad): Allow users to define custom max-width with CSS
Users can use the new custom CSS properties to define max widths for action-bar and action-pad
=> fix(action-bar, action-pad): Allow users to define custom max-width with CSS

.github/workflows/deploy-next.yml, package.json, support/deployNextFromCI.ts, support/isNextDeployable.ts
The storybook deployment isn't happening because we set up concurrency to batch `next` release commits, which cancels the current run when a new push to master happens. Moving the storybook deployment before the `next` release will fix the issue.
Edits:
- Put the storybook deployment inside of the `deployNextFromCI` script so that storybook only deploys when there are deployable commits
- Make sure that `next` releases even if the storybook deployment fails
=> ci: deploy storybook before releasing next

support/cleanOnProcessExit.ts, support/prepReleaseCommit.ts
This fixes an issue in ESMified™ scripts where options were not parsed properly.
=> build: fix CLI option handling in ESM scripts

src/components/dropdown/dropdown.scss, src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx
This reverts commit 4392fb20658b5a0f0e25f16da20aaa14826697c9.
**Related Issue:** #4949 #5020
Revert "fix(dropdown): Fix navigating without a dropdown-group (#4949)"
Keep menu/group roles.
=> revert: Fix navigating without a dropdown-group 

src/components/date-picker/assets/date-picker/nls/pt-PT.json, src/components/date-picker/date-picker.stories.ts
**Related Issue:** #4776 
Adds short day entry from CLDR.
cc @annierm18
=> fix(date-picker): add short day names for pt-PT date picker

.github/workflows/deploy-next.yml
The next/storybook deployment is working! This just cleans it up so that the build on master doesn't fail if there are no deployable commits. See error:
https://github.com/Esri/calcite-components/runs/7529705317?check_suite_focus=true#step:5:25
=> ci(next): pass when next deployment is not required

src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.tsx, src/components/dropdown/interfaces.ts
**Related Issue:** #1967 
Adds the most recently selected item to `calciteDropdownSelect`'s payload. This will benefit users in knowing the item that triggered the event, especially when the item group's selection mode is `none`.
=> feat(dropdown): include selection-triggering item in select event payload

src/components/slider/slider.tsx
**Related Issue:** #4290
fix(slider): Focus active handle on pointerdown instead of click. (#4290)
=> fix(slider): Focus active handle on pointerdown instead of click

src/components/combobox/combobox.tsx, src/components/dropdown/dropdown.tsx
refactor(combobox, dropdown): Use pointerdown in favor of onclick for events.
=> refactor(combobox, dropdown): Use pointerdown in favor of onclick for events.

.stylelintrc.json
This enables the [`selector-max-specificity`](https://stylelint.io/user-guide/rules/list/selector-max-specificity) rule to suggest using dynamic classes in rendering to decrease selector complexity.
Stems from https://github.com/Esri/calcite-components/pull/4367#discussion_r921534454
cc @driskull 
-  ~define sensible value for max specificity~ -> starting w/ current one
-  ~update selectors wherever applicable (can be tackled separately)~ -> will tackle as we encounter them
=> chore(linting): suggest alternative CSS approach for high specificity selectors

src/components/combobox/combobox.scss, src/components/combobox/combobox.stories.ts, src/components/combobox/combobox.tsx
**Related Issue:** #3099 
This updates the combobox to avoid a situation where the option list will stretch to the combobox's parent width (see https://codepen.io/jcfranco/pen/BarmpJV?editors=1000).
This is part 1 of 2 fixes needed for #3099. 
@driskull I tried following the same approach as the dropdown. LMK if I need to make any adjustments. 🙇‍♂️
=> fix(combobox): set min width of combobox items to match its input

src/components/stepper/stepper.scss, src/components/stepper/stepper.stories.ts
**Related Issue:** #4883 
🦶🦶🦶🦶↔🤏
=> fix(stepper): allow overriding stepper width

src/components/dropdown-group/dropdown-group.tsx, src/components/dropdown/dropdown.tsx, src/components/dropdown/readme.md
**Related Issue:** #5020 https://github.com/ArcGIS/afd-calcite-documentation/pull/460
Specify that all dropdown-items must have a parent dropdown-group
=> docs(dropdown):  dropdown-items must have a parent dropdown-group

.github/workflows/close-milestone.yml
Close milestones once 100% of its issues/PRs are completed and the milestone is past due
=> ci: add action to close completed milestones

src/components/tree/tree.tsx
**Related Issue:** #4814 
Tree was using the document's `activeElement` instead of its root node for keyboard navigation. 
Automatically testing our components when wrapped in shadow DOM can get complex. I'll look into an approach with demo pages and possibly storybook to see if we can spot these earlier. It'd be a manual check, but at least something easy to test.
=> fix(tree): fix keyboard navigation when wrapped in shadow DOM

src/assets/styles/_floating-ui.scss, src/components/action/action.scss, src/components/alert/alert.scss, src/components/card/card.scss, src/components/color-picker-hex-input/color-picker-hex-input.scss, src/components/date-picker-day/date-picker-day.scss, src/components/date-picker-month-header/date-picker-month-header.scss, src/components/input-date-picker/input-date-picker.scss, src/components/input-number/input-number.scss, src/components/input-text/input-text.scss, src/components/input/input.scss, src/components/modal/modal.scss, src/components/panel/panel.scss, src/components/pick-list/pick-list.scss, src/components/progress/progress.scss, src/components/radio-group/radio-group.scss, src/components/scrim/scrim.scss, src/components/shell-panel/shell-panel.scss, src/components/shell/shell.scss, src/components/tile-select/tile-select.scss, src/components/tree-item/tree-item.scss, src/components/value-list/value-list.scss, tailwind.config.ts
**Related Issue:** #4372 #3099 #4682 #3724 #4781 
This fixes a couple of layering issues we had in our components by doing the following:
1. updated tailwind config to introduce contextual z-index layers
2. updated component styles to reference these
3. removed unnecessary z-indices (see 3 below)
1. I can break any of these items to separate PRs if deemed appropriate
2. Layers are based on https://www.duetds.com/tokens/#z-index and can be tweaked accordingly
3. Any removed `z-index` can be restored if we spot a regression. Removal was determined by:
* evaluating the need for a stacking context
* local testing
4. Repro cases from the referenced issues were tested and work as expected
5. Updated all z-indices to be applied as tailwind utils
6. Skipped adding CSS props for now until the …
=> fix: apply layered z-indices across components

src/components/tab/tab.tsx
**Related Issue:** #2124 
Adds screen reader support to access the `calcite-tab` content by moving the `role` and `tabindex` to a child element.
Prior to the fix when accessing the tab content, screen reader users were provided with the `tab-title`, but not the `tab` content in particular with JAWS and VoiceOver.
Additional reference: [4979 comment](https://github.com/Esri/calcite-components/pull/4979#discussion_r926069374)
Verified on:
=> fix(tab): Screen reader support to access tab content

src/components/radio-button-group/radio-button-group.tsx, src/components/radio-button/radio-button.tsx, src/components/radio-group-item/radio-group-item.tsx, src/components/radio-group/radio-group.tsx, src/components/rating/rating.scss, src/components/rating/rating.tsx
**Related Issue:** #4442
🧹 
Adds consistency to our API styling documentation for the radio components and rating, including:
- radio-button
- radio-button-group
- radio-group
- radio-group-item
- rating
=> docs: api styling consistency for radio components and rating

src/components/time-picker/time-picker.tsx
=> refactor(time-picker): drop obsolete Spacebar key value check

src/components/tab-nav/tab-nav.scss, src/components/tabs/tabs.stories.ts
**Related Issue:** #4971
Reverts regression that makes `tabs` ignore `layout="center"`. When `calcite-tabs` is passed a `layout="center"` attribute, the `calcite-tab-nav` component now centers again.
=> fix(tabs): reverts regression that makes tabs ignore layout center

.github/dependabot.yml
**Related Issue:** #4770
We were using the bump-deps action on Tuesdays, and I moved dependabot to Thursday as a backup incase the action failed. Now that the action isn't working anymore (linked issue), I'm changing dependabot back to Tuesdays
=> ci(dependabot): change back to tuesdays

src/components/checkbox/checkbox.tsx, src/components/radio-button/radio-button.tsx, src/components/switch/switch.tsx, src/utils/form.tsx
Not sure why it was irrationally bothersome, but I had to fix it
=> refactor: fix typo in form interface

src/components/action-menu/action-menu.tsx, src/components/combobox/combobox.tsx, src/components/dropdown/dropdown.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/pick-list-item/pick-list-item.tsx, src/components/popover/popover.tsx, src/components/rating/rating.tsx, src/components/split-button/split-button.tsx, src/components/tooltip/tooltip.tsx
**Related Issue:** #3815 #4355
Improves `overlayPositioning` description
=> docs:  improve overlayPositioning property description

src/components/handle/handle.tsx, src/components/pick-list-item/pick-list-item.tsx, src/components/rating/rating.tsx
**Related Issue:** #5124
Caught in the PR linked above when find/replacing. The one for handle actually shows up in the doc so it seemed worth the extra PR
=> docs(handle, pick-list-item, rating): remove repeat the in comments

package-lock.json, package.json
**Related Issue:** #5098 
PR to déBump stencil back to 2.16.1 since https://github.com/ionic-team/stencil/issues/3470 still hasn't been resolved. If we need to bump Stencil I can close this PR and write something up to inform our users before releasing. I assume many of them will not be able to use `beta.91` if that's the case though.
=> build(deps): downgrade stencil due to unresolved tree shaking bug

src/components/scrim/scrim.tsx, src/components/select/select.scss, src/components/select/select.tsx, src/components/shell-center-row/shell-center-row.tsx, src/components/shell-panel/shell-panel.tsx, src/components/shell/shell.scss, src/components/shell/shell.tsx, src/components/slider/slider.tsx, src/components/split-button/split-button.tsx, src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.tsx, src/components/switch/switch.tsx
**Related Issue:** #4442 
📖 Adds consistency to our API styling documentation for the s-named components, including:
- scrim
- select
- shell
- shell-center-row
- shell-panel
- slider
- split-button
- stepper
- stepper-item
- switch
=> docs: consistent api ref s-named components

package.json, support/patchESMResolution.ts
**Related Issue:** #5141
Patches an ES module resolution error caused by adding `type="module"` in our `package.json`. I confirmed it works using `npm link` w/ our webpack example.
=> fix: patch esm resolution issue causing webpack build error

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.e2e.ts
**Related Issue:** #5127 
When the stepper is in horizontal layout, the content is displaced from the item's selection hit area, so it needs to be ignored when clicked.
=> fix(stepper-item): avoid emitting change event when clicking content in horizontal layout

src/components/radio-button-group/radio-button-group.tsx
This fixes a type regression introduced by https://github.com/Esri/calcite-components/pull/5001/files#diff-1db34e36763c50cd41364b15a24af2d25c23a0d61dc2a53e31f570b061a9c17eR128 where `calciteRadioButtonGroupChange`'s payload was typed as `void` instead of `any`.
cc @AdelheidF @paulcpederson
=> fix(radio-button-group): fix incorrect event payload type

src/tests/commonTests.ts, src/tests/utils.ts
=> refactor: introduce test util to skip animations

src/components/tree-item/resources.ts, src/components/tree-item/tree-item.scss, src/components/tree-item/tree-item.tsx, src/components/tree/interfaces.ts, src/components/tree/tree.e2e.ts, src/components/tree/tree.stories.ts, src/components/tree/tree.tsx, src/demos/tree.html
**Related Issue:** #3121
This introduces a new `none` selection mode that will still allow tree navigation, but prevent an item from being selected. The `calciteTreeSelect` event will emit as well after an item is 'selected'.
=> feat(tree): add none selection mode

src/components/input-time-picker/input-time-picker.tsx, src/components/tab-nav/tab-nav.tsx
=> refactor(input-time-picker, tab-nav): remove duplicate stopPropagations

src/assets/styles/includes.scss, src/components/stepper/stepper.e2e.ts
**Related Issue:** #5137
Reverts change to `hidden` attribute that caused a transition regression on `scrim`.
=> fix(scrim): reverts change to hidden attribute that caused a transition regression on scrim

src/components/date-picker-month/date-picker-month.tsx, src/components/date-picker/date-picker.stories.ts
**Related Issue:** #5136 
Fixes misalignemnt of days with dates in `en-gb`,`en-au`,`nb`,`es`,`de` locales
Side bar:
`Math.abs` is not required to make sure if the indexed value of startofWeek is  greater than lastDay of the previous month we don't need to display any dates from previous in current month
Example : startOfWeek = 1 (Monday) and lastDay of previous month is 0 ( sunday)
=> fix(date-picker): no longer misalign dates with day in `en-gb`,`en-au`,`nb`,`es`,`de` locales

src/utils/globalScript.ts
**Related Issue:** #5104
@jcfranco noticed an error in the `demo-app-advanced-2-shell-header.html` and `demo-app-advanced.html` caused by trying to access `body`'s `classList` before it was available.
=> fix: wait for body to load before initializing theme change event

src/demos/shell/demo-app-advanced-2-shell-header.html, src/utils/globalScript.ts
**Related Issue:** #5180
The fix in the PR linked above could cause `calciteThemeChange` to not fire if the DOM content is loaded before globalScript invokes.
Edit:
Switched to `readystate==="interactive"` because `readystate==="complete"` comes after `DOMContentLoaded` so there would still be a small window of time where the theme event initialization won't happen. See:
https://codepen.io/benesri/pen/xxWmMBM?editors=0012
=> fix: initialize calciteThemeChange when DOM content is loaded before globalScript executes

src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx
**Related Issue:** #4880
fix(dropdown): Remove scrolling when max-items >= number of dropdown items. (#4880)
=> fix(dropdown): Remove scrolling when max-items >= number of dropdown items

src/components/color-picker-hex-input/color-picker-hex-input.tsx
**Related Issue:** #4072
This allows users to paste a formatted hex value (e.g., `#aaa` or `#aaaaaa`), which is a common use case.
I attempted to set up a test for this, but it seems this isn't possible due to [puppeteer having issues with this](https://github.com/puppeteer/puppeteer/issues/2147) and security mechanisms when I tried setting something up via synthetic events. I'll include the test here in case it's supported in the future:
```tsx
it("handles pasted hex values with #", async () => {
const page = await newE2EPage();
await page.setContent(html` <calcite-color-picker></calcite-color-picker>
<input id="source-hex" value="#abcdef" />
`);
const colorPicker = await page.find("calcite-color-picker");
const context = page.browserContext();
const origin = await page.evaluate(() => …
```
=> feat(color-picker): allow pasting hex values with # character

src/components/shell/shell.scss, src/components/shell/shell.stories.ts
**Related Issue:** #5177 
This fixes a regression from https://github.com/Esri/calcite-components/pull/5058 where the content-behind z-index was set to the same value as surrounding shell-panels and shell-center-rows.
=> fix(shell): fix z-index for content-behind mode

src/utils/floating-ui.ts
**Related Issue:** #5163
fix(dropdown): Fix placement typings. (#5163)
Allows deprecated placement values for menu dropdown components.
=> fix(dropdown): Fix placement typings

src/components/popover/PopoverManager.ts, src/components/popover/popover.e2e.ts
**Related Issue:** #5142
fix(popover): autoClose should work when clicking on another popover. (#5142)
=> fix(popover): autoClose should work when clicking on another popover reference element

src/assets/styles/_floating-ui.scss, src/components/dropdown/dropdown.tsx
**Related Issue:** #5102
fix(dropdown): Correct placement when opening. (#5102)
The dropdown group needs to remain visible so floating UI can calculate its height. Instead, we set the width/height on its container to be 0 when not opened. This prevents the dropdown group from taking up space when not opened.
cc @benelan
=> fix(dropdown): Correct placement when opening

conventions/Documentation.md
Adds documentation to the documentation ❗ convention file. 📝 
- Includes new section on documenting deprecation for our docs with a deprecated chip. 🐿️ 
- Provides usage guidance to display a deprecated chip on our SDK site for:
- JSDoc `@deprecated` tag 🏷️ for props, events, and methods 
- `[Deprecated]` text 📔  for slots and CSS props
=> docs: Include code documentation notes

src/components/modal/modal.e2e.ts, src/components/modal/modal.scss, src/components/modal/modal.tsx, src/components/modal/resources.ts
`calciteModalOpen` and `calciteModalBeforeOpen` would not emit on page load like the rest of the components and only when you close and reopen the modal. 
This change ensures that the open styles for the underlay get applied initially and the modal transition styles are applied once the component is fully hydrated.
=> fix(modal): calciteModalOpen and calciteModalBeforeOpen now emit on page load

support/prepReleaseCommit.ts
=> ci(release): fix Windows errors

src/components/radio-button/radio-button.e2e.ts
**Related Issue:** #4212
Update tests that cover behavior on element click to use the .callMethod("click") in addition to .click(). In the case of the `radio-button`, click triggers a boolean toggle on the checked prop.
=> test(radio-button): update to help test click behavior via HTMLElement.click()

src/components/switch/switch.e2e.ts
**Related Issue:** #4212
Update tests that cover behavior on element click to use the `.callMethod("click")` in addition to `.click()`. In the case of the `switch`, click triggers a boolean toggle on the `checked` prop.
=> test(switch): update to help test click behavior via HTMLElement.click()

package-lock.json, package.json, support/patchESMResolution.ts, support/patchTreeShaking.ts
**Related Issue:** https://github.com/ionic-team/stencil/issues/3470
It looks like Stencil wont fix the rollup tree shaking bug until v3 ([source](https://github.com/ionic-team/stencil/pull/3556)), so I'm adding another post-build patch until then. 
I looked through the [breaking PR](https://github.com/ionic-team/stencil/commit/ff0e8cc54e5e68631cd83302d59b19f2626d43cb#diff-474e24df74c0221a170d7c067c32acfa2501ed400f4694df986bd84ddd43b7ee), and it didn't look like any changes occured that would cause problems due to removing the component exports in `dist/components/index.js`. To be safe I tested with the [CC rollup example](https://github.com/Esri/calcite-components-examples/tree/master/rollup), `npm link`, and my [`build-sizes`](https://github.com/benelan/build-sizes) package. 
Using the …
=> build: patch rollup tree shaking stencil issue

src/components/time-picker/time-picker.e2e.ts, src/components/time-picker/time-picker.tsx
**Related Issue:** #4957 
Makes sure the meridiem location is determined on load.
=> fix(time-picker, input-time-picker): initialize meridiem at the start of the time for rtl locales

.github/workflows/pr-screener.yml
Unfortunately we need to temporarily disable screener to prevent insane overage fees. We are working on a short term solution to turn screener back on, and a mid-term solution to switch to Chromatic. Screener can still be run on a branch manually following these steps: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
For now, please try not to manually run screener unless absolutely necessary. We only have around 35 runs per month at our current snapshot count. We will be working to reduce the number of stories so we can reenable screener PR checks in the short term.
=> ci(screener): disable screener PR checks

.github/workflows/close-milestone.yml
We have a GitHub Action that closes a milestone when all of the issues are completed. Currently it is only triggered when an issue is closed. Sometimes an issue does not pass the QA verification and the issue needs to be moved to the current sprint or backburner. With this PR the milestone will properly close.
=> ci: close past due milestone when its last issue is moved

.github/workflows/close-milestone.yml
How did we ever live w/o optional chaining :'(
Error: https://github.com/Esri/calcite-components/runs/8052344919?check_suite_focus=true#step:2:44
=> ci(close-milestone): fix issue due to no optional chaining

src/components/list-item/list-item.scss
fix(list-item): Use margin instead of padding when slotting icons.
=> fix(list-item): Use margin instead of padding when slotting icons.

src/components/action/action.stories.ts, src/components/card/card.stories.ts, src/components/tooltip/tooltip.stories.ts
**Related Issue:** #5257
Some additional cleanup. I nuked a lot of the combinations but we can add some back once we are out of crisis mode
=> test(action, card, tooltip): cleanup screener snapshots

.github/workflows/pr-screener.yml
Allow screener to run manually w/o skipping due to strict conditionals
=> ci(screener): create job for manual screener runs

.github/workflows/pr-screener.yml
**Related Issue:** #5285
Fixes error that happens when running the screener action manually. Not sure why this is happening since its the same step code I use for all the other actions, but providing the path to the lock file should fix it.
Error:
https://github.com/Esri/calcite-components/runs/8257764671?check_suite_focus=true#step:2:13
> Dependencies lock file is not found in /home/runner/work/calcite-components/calcite-components. Supported file patterns: package-lock.json,yarn.lock
=> ci(screener): fix lock file error when running manually

src/components/tree-item/tree-item.scss, src/components/tree-item/tree-item.tsx, src/components/tree/tree.stories.ts, src/demos/tree.html
**Related Issue:** #5186
Preserve the alignment of the `tree-items` regardless of whether they have children: outdent the disclosure arrows.
=> fix(tree-item): preserve the alignment of tree-items with selection-mode: none regardless of whether they have children

src/components/accordion/accordion.stories.ts
This PR will remove the redundant code block in the `accordion` stories util method.
=> refactor: remove redundant code block

.eslintrc.json, src/utils/globalScript.ts
**Related Issue:** #5104
@dasa noticed this while we were looking into an unrelated JSAPI issue. He suggested I use the [`isBrowser` check the JSAPI copied from dojo](https://devtopia.esri.com/WebGIS/arcgis-js-api/blob/4master/esri/core/has.ts#L229-L235) and that I add the `no-eval`, `no-implied-eval`, and `no-new-func` ESLint rules, which the JSAPI uses, so we don't run into this problem in the future. 
[More info from MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions)
Edit:
I ran `npm run test:prerender` and there were no errors.
=> fix: remove unsafe-eval to support CSP script-src

.eslintrc.json
**Related Issue:** #5299
Move ESLint rule additions to separate PR from the one linked above
=> chore(eslint): add no-eval, no-implied-evail, and no-new-func rules

support/prepReleaseCommit.ts
**Related Issue:**
Cleanup from https://github.com/Esri/calcite-components/pull/5302#discussion_r969838912
=> ci(prepReleaseCommit): throw error when target release version not determined

src/components/input-number/input-number.tsx, src/components/input/input.tsx
**Related Issue:** #5287
Adds an `aria-hidden` prop to `input` when `type="number"` and `input-number` to hide the non-interactive up/down buttons.
Both buttons are not accessible via keyboard, and keyboard users can increment numbers using the arrow keys. This fix hides the buttons from the accessibility API to improve the experience for assistive technology users.
=> fix(input, input-number): hide non-interactive number up/down buttons from assistive technologies

src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts, src/demos/tooltip.html
**Related Issue:** #5318
refactor(tooltip): Use pointer events in favor of mouse events. (#5318)
pointer events will fire on disabled elements.
=> refactor(tooltip): Use pointer events in favor of mouse events

src/components/panel/panel.e2e.ts, src/components/panel/panel.tsx
feat(panel): Add `calcitePanelClose` event and deprecate `calcitePanelDismiss` event
=> feat(panel): Add `calcitePanelClose` event and deprecate `calcitePanelDismiss` event

src/components/flow-item/flow-item.e2e.ts, src/components/flow-item/flow-item.tsx
feat(flow-item): Add `calciteFlowItemBack` event and deprecate `calciteFlowItemBackClick` event
=> feat(flow-item): Add `calciteFlowItemBack` event and deprecate `calciteFlowItemBackClick` event

support/deployNextFromCI.ts
**Related Issue:**
Next hasn't actually deployed since 582. Looking at the error, it is failing a check to that makes sure the changes were pushed:
https://github.com/Esri/calcite-components/actions/runs/3050425472/jobs/4917508918#step:5:7366
However the following commit is the changes being pushed. According to the commit history we are on `next.590`. It seems like there is some lag happening between pushing and confirming that the push happened which is causing the deployment to fail right before publishing to NPM. So I'm removing that check. 
Hopefully it is an unnecessary check since we are using an atomic push which should provide a non-zero exit code of it doesn't work for any reason.
=> ci(next): stop checking if changes pushed before publishing to npm

src/components/color-picker/color-picker.tsx
Tidy up for color-picker's `value` doc.
This also works as a side-effect fix for a build error in Stencil v2.18. 🎉 cc @driskull
=> docs: update color-picker JSDoc link

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/workflows/add-esri-product-label.yml
Adds a required dropdown field for specifying an esri product team to the bug/a11y/enhancement issue templates. A github action will parse the field and add a label for filtering.
=> chore: specify esri product team when logging issues

package.json, support/deployNextFromCI.ts
**Related Issue:** #5062
Reorganize the `next` release NPM scripts so that they are in line with the normal release ones. The push should happen in the `util:publish-next` script so that we don't run into an issue where a version pushes but doesn't get published to NPM.
=> ci(next releases): check types before pushing tags

src/components/action-bar/action-bar.e2e.ts, src/components/input-number/input-number.e2e.ts, src/components/input-text/input-text.e2e.ts, src/components/modal/modal.e2e.ts, src/components/radio-button/radio-button.e2e.ts
**Related Issue:** I'll make one in a sec and add it here
Skipping unstable tests brought up in a Teams thread
=> test(action-bar, input-number, input-text, modal, radio-button): skip  unstable

package-lock.json, package.json
=> build(deps): bump calcite-ui-icons

src/components/modal/modal.scss
**Related Issue:** https://github.com/Esri/calcite-components/issues/5396
This fixes a regression from https://github.com/Esri/calcite-components/pull/5187 where we forgot to remove the use of the `calcite-hydrated` selector (see https://github.com/Esri/calcite-components/pull/5187/commits/fb5e58e62f2d8882b4af986efdd35b3545c27fc9). 
**Note**: I'm not sure how we can test within this repo since it depends on building Stencil components separately
cc @Elijbet
=> fix(modal): drop unnecessary calcite-hydrated selector for open/close eventing

conventions/README.md, src/components/date-picker-day/date-picker-day.tsx, src/components/date-picker-month/date-picker-month.tsx, src/components/dropdown/dropdown.tsx, src/components/radio-button/radio-button.tsx, src/components/rating/rating.tsx, src/components/tile-select/tile-select.tsx
Stems from https://github.com/Esri/calcite-components/pull/5320. This moves components to use pointer events for better device compatibility.
=> feat: use pointer events instead of mouse events to improve device compatibility

src/components/tile-select/tile-select.stories.ts, support/prepReleaseCommit.ts
Shockingly we don't have any sanity checks in `prepReleaseCommit` to make sure `master` is checked out and up to date, and that no uncommited changes make it into a release. I figured that out the hardway when a new story got commited with `beta.95` 😅 
I have a bash alias on my new work computer that checks out `master` and makes sure everything is up to date and clean, which is probably why this hasn't happened before. But as other people start to release we definitely want it as part of that script
=> ci(release): add checks to keep out uncommited code

src/components/flow-item/flow-item.tsx, src/components/panel/panel.tsx
Use the `example` jsdoc tag instead of fenced code, so the formatting isn't so goofy in the afd doc
=> docs(flow-item, panel): use @example jsdoc tag to fix formatting

.gitignore, stencil.config.ts
**Related Issue:** https://github.com/Esri/calcite-components/issues/3957
Removes an output target that we were [using](https://github.com/Esri/calcite-components/pull/781) [initially](https://github.com/Esri/calcite-components/pull/1499) to do what the `dist-custom-elements` output target does ([and better](https://github.com/Esri/calcite-components/pull/3224)). Our doc and examples use the supported output target, so this should not introduce breaking changes from that perspective.
=> build(output-target): drop undocumented and deprecated dist-custom-elements-bundle output target

.github/workflows/deploy-next.yml
**Related Issue:** #5398
The sanity checks I added in the PR linked above have been preventing `next` from deploying in our CI. Here is the error:
https://github.com/Esri/calcite-components/actions/runs/3230896841/jobs/5289848000#step:5:7451
My guess is it's failing because it's not on `master`. The other options would be uncomitted files or the local `master` branch not being in sync with `origin/master`, which don't seem as likely.
I thought it would be okay because we do checkout `master` in the action here:
https://github.com/Esri/calcite-components/blob/77e041e5b3d69dbad62c3c9b7f2d7acc446c0582/support/isNextDeployable.ts#L19
But maybe it is scoped and `master` is not staying checked out? I'm not sure. Hopefully this fixes it 🤞
=> ci(next): fix deployments by specifying master branch

src/components/alert/alert.tsx, src/components/input-number/input-number.e2e.ts, src/components/input-number/input-number.tsx, src/components/input/input.e2e.ts, src/components/input/input.tsx, src/components/pagination/pagination.tsx, src/components/slider/slider.tsx, src/utils/locale.spec.ts, src/utils/locale.ts, src/utils/number.spec.ts
**Related Issue:** #5301
Uses getter and setter methods in `NumberStringFormat` for safesies. Also caches the number formatter in `calcite-alert` by serializing and comparing the options object, and using the whole object for the `Intl.NumberFormat` options when there are changes.
=> refactor: use getters and setters in NumberStringFormat

src/components/block/block.tsx, src/components/block/resources.ts
=> refactor(block): move hardcoded classes to CSS object

src/components/input-number/input-number.scss, src/components/input-text/input-text.scss, src/components/input/input.scss
**Related Issue:** #5417
https://github.com/Esri/calcite-components/pull/5058 introduced a regression when it removed the z-indices for input icons as Chrome rendered fine during testing. This fixes it and adds a note regarding its use.
=> fix(input, input-number, input-text): fix input icons not displaying properly in Firefox

.github/workflows/deploy-next.yml, support/prepReleaseCommit.ts
**Related Issue:** #5460
PR linked above didn't fix next deployments 😞. It looks like it is failing because `npm run build-storybook` is running before the deployment, which builds to `./docs`. The check fails if there are uncomitted changes so removing the changes to ./docs should fix the issue.
=> ci(next): clean docs build before deployment

src/components/input-number/input-number.scss, src/components/input-text/input-text.scss
The resize icon is exclusively for `calcite-input`'s textarea styling, which is not supported by these inputs.
=> refactor(input-number, input-text): drop resize-icon selectors

src/components/block/block.scss, src/components/block/block.stories.ts, src/components/block/block.tsx, src/components/block/resources.ts
**Related Issue:** #5422 
This improves layout of block's content area.
=> fix(block): improve content layout

src/components/scrim/resources.ts, src/components/scrim/scrim.e2e.ts, src/components/scrim/scrim.tsx
**Related Issue:** #4961 
Wires up translations to the scrim component.
=> feat(scrim): add built-in translations

CHANGELOG.md
Adds missing breaking changes from #5411 and #5412.
=> docs(changelog): add missing breaking changes

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.stories.ts, src/components/stepper/stepper.tsx, src/demos/stepper.html
**Related Issue:** #4893
Adds `numberingSystem` property to `calcite-stepper`. A couple lines in `calcite-stepper-item` will need to be changed due to a refactor in #5466. The small change can go in which ever PR is merged last.
=> feat(stepper, stepper-item): add numberingSystem property

src/components/flow-item/flow-item.e2e.ts, src/components/flow-item/flow-item.tsx
**Related Issue:** #5414 
Fixes `flow-item#scrollContentTo` by storing missing reference.
cc @driskull
=> fix(flow-item): fix scrollContentTo

.github/workflows/deploy-next.yml
Forgot how weird GH Action's runner is. I don't think the cwd is the repo's root, but then somehow git/npm commands still work. Fun stuff.
https://github.com/Esri/calcite-components/actions/runs/3267954519/jobs/5373794675#step:5:7464
Also checking out `master` to be safe because I'm tired of submitting PRs for this. _I don't think_ `npx storybook-to-ghpages` changes the branch to gh-pages, but maybe it does?
=> ci(next): fix next releases take 3

src/components/flow-item/flow-item.stories.ts, src/components/panel/panel.tsx
**Related Issue:** #5428
https://github.com/Esri/calcite-components/pull/5129 refactored panel's content rendering function and it missed toggling some CSS classes on the parent node based on whether there was a fab or not (before: https://github.com/Esri/calcite-components/blob/6f6316c8532e1876aadc63f71c3e4095db2af3b6~/src/components/panel/panel.tsx#L533 + https://github.com/Esri/calcite-components/blob/6f6316c8532e1876aadc63f71c3e4095db2af3b6~/src/components/panel/panel.tsx#L523; after: https://github.com/Esri/calcite-components/blob/6f6316c8532e1876aadc63f71c3e4095db2af3b6/src/components/panel/panel.tsx#L629 ).
**Notable changes:**
- adds missing flow-item stories (to include in screenshot testing)
- removes unnecessary keys for nodes that are no longer conditionally rendered
cc …
=> fix(flow-item, panel): fix layout issue that would cause double scrollbars

src/components/tree/tree.e2e.ts
Removes leftover unused import from https://github.com/Esri/calcite-components/pull/5472.
✨ 🧹✨
=> chore: remove unused import

src/components/tree/tree.tsx
**Related Issue:** #5520
Some of the optional chaining `?` added to get rid of the typeError in cases when there is no `parentEl` (#5472) was redundant. In the context of events from child items, there is no need for the `?` operator as the event is processed after it bubbles, so we can assume there's an ancestor chain.
=> refactor(tree): drop the optional chaining operator ? from tree within the event handler

package-lock.json, package.json
**Related Issue:** #5481
Bumps `@esri/calcite-ui-icons`
=> build(deps): bump calcite icons

conventions/Documentation.md
Updates the style guide with the new double quote vs backtick guidelines.
=> docs(conventions): update style guide

src/components/slider/slider.e2e.ts, src/components/slider/slider.tsx
**Related Issue:** #5321 
This fixes a regression from https://github.com/Esri/calcite-components/commit/24a6b9548e8eaa2ab8b8c9faa05869c0c29d6136 where the thumb was being focused before the drag prop was set, causing an error to be thrown when clicking on the track, on opposite sides of the thumb.
* `activeProp` is no longer a state prop as it does not affect rendering (takes care of Stencil dev-time rendering warning)
* makes slider UX more consistent by focusing the single-thumb immediately on `pointerdown` (currently, this only happens with range slider)
=> fix(slider): fix slider (single-value) error when clicking range

.github/workflows/pr-screener.yml
When we scaled back our screener snapshot usage we decided to not run Screener on every push to `master`, which meant it would need to be ran manually whenever a screener change happened. Otherwise baseline gets out of sync and it causes problems. 
People haven't been remembering to tell me to run screener manually, so I'm re-enabling automatic screener runs on `master`. I tweaked it a bit so `dependabot` and `next` deployment pushes to `master` do not run screener. We have the screenshot bandwidth to re-enable this; I think trimming down some of the stories and not running screener on every single push to a PR branch made the biggest difference. 
Based on our snapshot count, we can also start adding the `pr ready for visual snapshots` label to all PRs before merging. …
=> ci(screener): reenable screener on pushes to master to update baseline

src/components/block-section/block-section.tsx, src/components/block/block.tsx, src/components/button/button.tsx, src/components/card/card.tsx, src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.tsx, src/components/chip/chip.tsx, src/components/color-picker-hex-input/color-picker-hex-input.tsx, src/components/color-picker-swatch/color-picker-swatch.tsx, src/components/color-picker/color-picker.tsx, src/components/combobox-item-group/combobox-item-group.tsx, src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.scss, src/components/combobox/combobox.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/input-time-picker/input-time-picker.tsx, src/components/popover/popover.tsx, src/components/tip/tip.tsx
**Related Issues:** #4442, https://github.com/Esri/calcite-components/pull/5450#discussion_r998534396 (for `calcite-card`s `thumbnailPosition` prop)
1. Adds documentation to `calcite-card`'s `thumbnailPosition` prop
2. Adds consistent doc styling to:
- block-section
- block
- button
- card
- checkbox
- chip
- color-picker
- combobox-item-group
- combobox-item
- combobox
3. Adds backticks to `true` values for:
- input-date-picker
- input-time-picker
- popover
- tip
=> docs: consistent api styling + define card thumbnailPosition

package-lock.json, package.json, src/utils/config.ts, src/utils/floating-ui.ts, src/utils/floating-ui/nonChromiumPlatformUtils.ts
**Related Issue:** #5429
This restores positioning logic that was reverted from [`@floating-ui/dom@1.0.2`](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fdom%401.0.2) due to the performance impact. The fix will only be applied to non-Chromium browsers (targeting Firefox and Safari specifically) by default and can be disabled by providing the following config flag:
```html
<script>
var calciteComponentsConfig = {
floatingUINonChromiumPositioningFix: false
}
</script>
```
* introduces a global config for components to allow users to opt-out of the fix in favor of performance
* bumps `@floating-ui/dom` to [1.0.3](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fdom%401.0.3)
* dynamically loads custom code for non-Chromium browsers for proper …
=> fix: add custom logic for floating-ui positioning across shadow DOM in non-Chromium browsers

src/components/input-message/input-message.e2e.ts, src/components/input-message/input-message.scss, src/components/input-message/input-message.tsx, src/components/loader/loader.e2e.ts, src/components/loader/loader.scss, src/components/loader/loader.tsx
**Related Issue:** #3821
Loader and Input-Message are small building blocks that an owning component should be able to display or hide.
This deprecates/removes the role of `active` prop in toggling visibility in favor of the global attribute `hidden`. Styles for hidden take precedence over active. 
The benefit is one less custom prop to manage, and it aligns with existing HTML conventions.
=> fix(calcite-loader, calcite-input-message): drop active in favor of hidden

src/components/flow-item/flow-item.e2e.ts, src/components/flow-item/flow-item.tsx
**Related Issue:** #5546
feat(flow-item): Add calciteFlowItemScroll event. (#5546)
=> feat(flow-item): Add calciteFlowItemScroll event

.github/need-info.yml
Adds in W3C URLs as a resource for issues to avoid the `needs info` label. 
W3C resources provide context for a11y audits, bugs, or enhancements, and are acceptable resources when filing a11y-related issues.
=> ci: adds w3c url for a11y issue filing

src/components/date-picker-month-header/date-picker-month-header.scss
**Related Issue:** #5532 
This PR will fix the format order issue in `calcite-date-picker` header for locales of order YYYY.MM.DD
=> fix(date-picker): display correct date format order in header for zh-CN locale.

src/components/stepper-item/stepper-item.tsx, src/demos/alert.html
**Related Issue:** #5467
Providing `numberingSystem` to the formatter isn't working correctly in the `effectiveLocale` watcher. ~~I'm changing it back to the render block so it works in this upcoming release. I'll get it working in a hook or lifecycle method after the release, when we aren't so crunched.~~
Looks like I just needed to add it to `componentWillLoad` as well, for the initial rendering on load. Thanks Franco!
=> fix(stepper-item): make sure numberingSystem is rendered on load

src/components/slider/slider.e2e.ts, src/components/slider/slider.tsx
**Related Issue:** #5449
updates the private setValue method to accept (n) props to update on the component.
updated dragUpdate to call setValue with minValue & maxValue on drag.
=> fix(slider): dragging range fires input event

src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #5538
fix(tooltip): Prevent opening when closeOnClick is true and referenceElement is clicked quickly. (#5538)
=> fix(tooltip): Prevent opening when closeOnClick is true and referenceElement is clicked quickly

package-lock.json, package.json
This fixes a regression caused by https://github.com/Esri/calcite-components/pull/5542 (bumped as a devdep vs dep 😅 #derp). cc @AdelheidF
=> fix(types): fix type issue caused by unintentionally moving @floating-ui/dom as a dev dependency

CHANGELOG.md
Adds more context to the revert changelog entry
=> docs(changelog): add context to revert requiring patch

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml, .github/workflows/add-esri-product-label.yml
If a team label does not exist, the user can edit it in after submitting the issue and the label will be automatically created. This also moves the `Calcite (dev)` and `Calcite (design)` options to the bottom of the list, since some people were selecting them w/o reading the prompt.
=> ci: automatically create product label when added after submission

.github/ISSUE_TEMPLATE/bug.yml
Allows users to input prioritization as it relates to the work to help us prioritize while triaging bugs 🐛 . 
The user input is optional and located at the bottom of the bug issue template, prior to selecting their team.
cc @brittneyzwolfer
=> ci: user impact field for bug issue prioritization

src/utils/floating-ui/nonChromiumPlatformUtils.ts
=> refactor: import types from @floating-ui/dom and not the package src

CHANGELOG.md
**Related Issue:** #5469
It looks like anything  manually added to the Unreleased section gets during release. Adding back.
=> docs(changelog): add back output target removal breaking change

src/components/dropdown/dropdown.e2e.ts, src/components/icon/icon.e2e.ts, src/components/modal/modal.e2e.ts, src/components/tab-title/tab-title.e2e.ts
Skips unstable tests:
- src/components/dropdown/dropdown.e2e.ts `dropdown should not overflow when wrapped inside a tab`
- src/components/icon/icon.e2e.ts `loads icon when it's close to viewport`
-  src/components/modal/modal.e2e.ts`opens and closes`
- src/components/tab-title/tab-title.e2e.ts `emits active event on user interaction only`
=> test(dropdown, icon, modal, tab-title): skip unstable tests

package.json
All those readmes that are generated on every build have been slowly driving me to madness. I've had it - NO MORE, I SAY!
The only time we actually need the readmes built is in the GH Action, which doesn't even use `npm run build`. 
It runs `npx stencil build --docs`, which will still generate the docs after this change. 
We also have a util script specifically for building docs, which will still do so: `npm run util:build-docs`.
We can free ourselves from the opressive reign of these markdown clad menaces! They may be many, but we are strong. Who will ~~ride with me~~ approve this PR?
=> ci: stop generating readmes on every build

src/components/dropdown-group/dropdown-group.scss
**Related Issue:** #5663 
This fixes a regression caused by #5399 where the floating-ui element is placed offscreen and its styles change the offsetParent in non-Chromium browsers.
=> fix(dropdown): fix calculation of max-items for non-Chromium browsers.

src/components/link/link.scss
**Related Issue:** #5262 
Link underline and link icon placement was wrong when used with calcite-fonts 2.x. The metrics of the new font files are taller in general, so links were displaying noticeably off vertical center.
I've tweaked the underline placement and icon positioning slightly to account for this change. I've checked this with the old and new versions of calcite fonts and it seems to work with both. 
@macandcheese I know you did a ton of work while creating this component to make sure it rendered in all these scenarios (ie. inline text in a paragraph, etc), so let me know if there is more to check than what's on the demo page.
=> fix(link): fix link underline and icon placement when used with calcite fonts 2.x

src/components/pick-list/shared-list-render.scss, src/components/value-list/value-list.e2e.ts, src/components/value-list/value-list.scss
**Related Issue:** #5690 
This PR will hide the screen reader only text when drag-enabled in `value-list` component.
=> fix(value-list): no longer display screen reader only text when drag-enabled

.github/workflows/pr-e2e.yml, .github/workflows/pr-screener.yml
Gets rid of `set-output` deprecation notices
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci(actions): remove deprecated set-output workflow commands

.github/workflows/pr-screener.yml
Fix indent and use GITHUB_OUTPUT instead of GITHUB_ENV
=> ci(screener): fix yaml syntax

.github/workflows/pr-e2e.yml
**Related Issue:** #5711
Forgot to change the e2e action as well
=> ci(e2e): use step output in github action

.github/workflows/deploy-next.yml, .gitignore
**Related Issue:** #5714
The error from the PR linked above is fixed, but it failed again:
https://github.com/Esri/calcite-components/actions/runs/3424220966/jobs/5703841849#step:5:8860
My guess is the [`git clean`](https://github.com/Esri/calcite-components/blob/114d47bc53a821b17e3da393ae60c41dbe798287/.github/workflows/deploy-next.yml#L42) removed the `components.d.ts` file which caused the [type check in `publish:next`](https://github.com/Esri/calcite-components/blob/f28b82f9a2ee23b864b73fccbc9d6fe0dcee7b1e/package.json#L61) to fail due to that stencil bug.
Not sure why this wasn't an issue before updating the GitHub Actions to the new node version. I gitignored `./docs` so I don't have to do a `git clean`, and that will prevent the type bug from occuring, if that's what is causing …
=> ci(next): fix potential type error due to the components.d.ts stencil bug

.github/workflows/deploy-next.yml
**Related Issue:** #5719
I just remembered that gitignored files aren't considered untracked, which means `git clean` won't remove them. So my last PR (linked above) probably won't fix the issue. I'm starting to run out of ideas, but maybe it is due to removing the default NPM registry url? Not sure why we would be required to specify the default registry, but serves me right for trying to tidy up, I guess.
If this isn't it, I'll revert back to the node12 runner until I have more time to troubleshoot.
=> ci(next): add back default npm registry url

package.json
**Related Issue:** https://github.com/ArcGIS/calcite-components-output-targets/pull/10
When releasing CCR, `stencil build` must be the last command  in CC's `build` script because [CCR appends the `--config` flag](https://github.com/ArcGIS/calcite-components-output-targets/blob/ae776a58efc3212802cd7a79192dcf09964f92b8/packages/calcite-components-output-target-generator/package.json#L15) to use a different config that generates the react output target.
I had been removing the patch because I thought something it changed in the CC build was breaking the CCR build. Moving the patch to `postbuild` will allow the patches to be applied to CCR as well.
=> ci(output targets): move patches to postbuild to include them in CCR

src/components/flow-item/flow-item.tsx
fix(flow-item): Position back tooltip above by default.
=> fix(flow-item): Position back tooltip above

.github/workflows/pr-bot.yml
**Related Issue:** #5704
I replaced an unmaintained 3rd party action, which still uses node12, with a [`github-script`](https://github.com/actions/github-script) workflow, but forgot to skip assignment for dependabot PRs
=> ci(pr-bot): skip assignment for dependabot PRs

package-lock.json, package.json
**Related Issue:** #5741
Screener broke itself
=> revert: bump semver-regex and screener-storybook (#5741)

src/components/inline-editable/inline-editable.stories.ts, src/components/input/input.scss
**Related Issue:** #5489
fix(inline-editable): Add text-ellipsis when not editing. (#5489)
=> fix(inline-editable): Add text-ellipsis when not editing

package.json
**Related Issue:** #5654
Turns out adding `--no-docs` to the build prevents the `docs-json` output target from being created. The reason I added it was the annoying readmes being generated for each component. The `git restore` I added to `postbuild` resolves that, while still generating `docs-json`.
=> build(docs): generate docs-json for afd usage

.github/workflows/pr-bot.yml, src/utils/locale.spec.ts
**Related Issue:** #5756
Dependabot labels itself and behaves differently than normal PRs, so we can just skip labelling it.
=> ci(pr-bot): don't label dependabot PRs

.github/workflows/add-esri-product-label.yml
**Related Issue:** #5687
Sorry, not sure how I missed this issue being logged. The script I am going to write to add the labels to issues logged before the action was created will do the failed ones too
=> ci(product-label): fix version syntax and use os agnostic newline char

CHANGELOG.md, CONTRIBUTING.md
I didn't realize that when adding a `BREAKING CHANGE` note to the summary block right before confirming a squash merge, we need to remove all the info except the `BREAKING CHANGE` note itself, or else everything ends up being added to the `changelog`. 
- Refactors `changelog` to remove the redundancy. 
- Adds a follow-up note regarding this to the contributing docs: https://github.com/Esri/calcite-components/blob/master/CONTRIBUTING.md#breaking-changes
=> refactor(changelog): remove redundant information from changelog and add a follow-up note to contributing docs

src/components/block/block.scss
**Related Issue:** #5776
This fixes a regression from https://github.com/Esri/calcite-components/pull/5314/ where the block loading icon would spin way too fast.
It uses the same speed as [`calcite-loader`](https://github.com/Esri/calcite-components/blob/master/src/components/loader/loader.scss#L23) for consistency.
Tested manually with the block demo page as animations are not supported by automated testing.
=> fix(block): slow down loading icon spin

CHANGELOG.md
Removing this manually after every next release until I fix the script. The I noted the rest of the changes that I need to make after the next beta release once it will stick, but this part needs to go now
=> docs(changelog): cleanup

CHANGELOG.md, support/prepReleaseCommit.ts
It turns out the default behavior of conventional-changelog is to generate the changelog items since the most recent tag. Whoever wrote the script was deleting all of the next tags and readding them so that the whole changelog would be regenerated. I ended up writing some helpers to combine the existing unreleased changelog items and the new ones.
=> ci: changelog modifications aren't overwritten after next releases

.storybook/resources.ts, src/components/action/action.scss, src/components/action/action.stories.ts, src/components/action/action.tsx, src/components/interfaces.ts, src/components/pick-list-item/pick-list-item.tsx
BREAKING CHANGE: Removed the `calciteActionClick` event and the `clear` value for the `appearance` property.
- Listen to the `click` event instead of `calciteActionClick.
- Use the value `transparent` instead of `clear` for the property `appearance`.
=> refactor(action)!: Removed deprecated properties and values

CONTRIBUTING.md
Designers are running into issues getting an environment set up to run the demos locally, so I'm clarifying a few things in the contributing guide.
=> docs(contributing): add additional info about environment setup

src/components/tree-item/tree-item.tsx, src/components/tree/tree.e2e.ts
**Related Issue:** #5735
fix(tree-item): Allow space and enter key events when selectionMode is "none". #5735
=> fix(tree-item): Allow space and enter key events when selectionMode is "none"

.github/workflows/chromatic.yml
I forgot to pass the diff threshold GH secret to the chromatic workflow's environment variables 😅
That explains why bumping up the value wasn't doing anything
=> ci(chromatic): use diffThreshold value saved in secrets

src/components/tip-manager/tip-manager.e2e.ts, src/components/tip-manager/tip-manager.tsx
BREAKING CHANGE: Removed the `calciteTipManagerToggle` event, use `calciteTipManagerClose` instead.
=> refactor(tip-manager)!: Remove deprecated `calciteTipManagerToggle` event.

.github/dependabot.yml, package.json
**Related Issue:** #5833
Prevent the whitespace storybook addon from getting bumped since it caused issues with chromatic:
https://github.com/Esri/calcite-components/actions/runs/3577241314/jobs/6016009432#step:6:207
=> ci(deps): exclude bumping @whitespace/storybook-addon-html due to chromatic errors

.storybook/preview.ts, src/components/date-picker/date-picker.stories.ts, src/components/slider/slider.stories.ts
Some more changes to stop text aliasing from triggering Chromatic diffs
=> ci: more tweaks to prevent chromatic diffs for text aliasing

.github/workflows/pr-bot.yml
There is a timing error, where if you sync a branch and change a label right afterwards, your change will be undone. This is because the `pr-bot` was adding the conventional commit type label to the existing ones, but when it started the run your change diudn't exist yet.
I found an API endpoint that just adds labels, without the potential to accidently remove existing ones.
=> ci(pr-bot): prevent from removing existing labels

src/05-custom-theme.stories.mdx
**Related Issue:** #5812
The image service we were using for the card's thumbnail in the custom theme story is/was down, which caused CI failures. For example:
https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6386b5d2e340d812b9c9a134
I switched it out to use our placeholderImage util.
=> test(custom-theme): use placeholderImage

CONTRIBUTING.md
Add contributing guidance for devs on time estimates pertaining to the `estimate-#` label. 
Adds estimates for: 
- 1
- 2
- 3
- 5
- 8
- 13
- 21, and
- 34
=> docs(contributing): estimate labels and guidance

src/components/tree-item/tree-item.tsx, src/components/tree/tree.tsx
BREAKING CHANGE: Removed the `inputEnabled` property.
- Removed the property `inputEnabled`, use `selectionMode="ancestors"` instead.
=> refactor(tree)!: Remove deprecated `inputEnabled` property

src/components/dropdown-item/dropdown-item.scss, src/components/dropdown-item/dropdown-item.tsx, src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx, src/components/dropdown/usage/Basic.md, src/components/dropdown/usage/Disabling-close-on-select.md, src/components/dropdown/usage/Groups.md, src/components/split-button/split-button.tsx
BREAKING CHANGE: Removed deprecated properties.
- Removed the property `active` on `calcite-dropdown-item`, use `selected` instead.
- Removed the property `active`, on `calcite-dropdown`, use `open` instead.
=> refactor(dropdown, dropdown-item)!: Remove deprecated properties

src/components/split-button/split-button.tsx
BREAKING CHANGE: Removed the `event.detail` payload from the events `calciteSplitButtonPrimaryClick` and `calciteSplitButtonSecondaryClick`. Use separate mouse event listeners to get information about `click` events.
=> refactor(split-button)!: Remove deprecated `event.detail` on events

src/components/radio-group-item/radio-group-item.e2e.ts, src/components/radio-group-item/radio-group-item.scss, src/components/radio-group-item/radio-group-item.tsx, src/components/radio-group/radio-group.stories.ts, src/demos/radio-group.html
BREAKING CHANGE: Removed deprecated properties.
- Removed the property `icon`, use either `iconStart` or `iconEnd` instead.
- Removed the property `iconPosition`, use either `iconStart` or `iconEnd` instead.
=> refactor(radio-group-item)!: Remove deprecated properties

CHANGELOG.md
=> docs(changelog): fix breaking change indent levels

.github/workflows/change-milestone.yml, .github/workflows/close-milestone.yml, .github/workflows/create-milestone.yml
I'm disabling some of the milestone automation for now. We recently changed the way we work with milestones, which is causing funky behavior.
The actions were created under the assumption that the only milestones with due dates would be for our 2 week sprints. I can change the actions if we are deciding to change how we use milestones, but we may want to wait for Brittney to return before making that decision, since that is her area of expertise.
=> ci: disable milestone automation due to process changes

.github/PULL_REQUEST_TEMPLATE.md
Removes the markdown comment from the PR template. We very rarely get outside PRs, and the comment is showing up in the squashed commit message after I changed it to use the PR description by default.
=> ci(pr-template): remove markdown comment

.github/workflows/update-browserslist-db.yml
**Related Issue:** #5512
The fix I did in the PR linked above is getting the workflow through the browserlist check. But now we are getting the stencil eslint plugin peer dep error on the uninstall. I'm not sure if the `--legacy-peer-deps` flag does anything for `npm uninstall`, but its worth a shot. 
Error: https://github.com/Esri/calcite-components/actions/runs/3610821906/jobs/6084842550#step:4:48
=> ci(browserlist): use legacy-peer-deps flag on uninstall

src/assets/styles/_floating-ui.scss, src/components/combobox/combobox.scss, src/components/dropdown/dropdown.scss, src/components/input-date-picker/input-date-picker.scss, src/components/modal/modal.stories.ts, src/components/popover/popover.e2e.ts, src/components/popover/popover.scss, src/components/tooltip/tooltip.e2e.ts, src/components/tooltip/tooltip.scss, tailwind.config.ts
**Related Issue:** #5388
fix(tooltip): Prevent tooltip from appearing above modal overlay. #5388
- Updates floating-ui to use tailwind configuration
- Sets default z-index to be that of a dropdown
- Adds ability for users to customize zindex of tooltips and popovers
- CSS vars `--calcite-tooltip-z-index` and `--calcite-popover-z-index`
```html
<calcite-tooltip style="--calcite-tooltip-z-index: 500;" label="Open modal" reference-element="button">
Open modal
</calcite-tooltip>
```
=> fix(tooltip): Prevent tooltip from appearing above modal overlay

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.e2e.ts, src/components/stepper/stepper.stories.ts, src/components/stepper/usage/Basic.md, src/demos/stepper.html
BREAKING CHANGE: Removed deprecated properties.
- Removed the property `active`, use `selected` instead.
- Removed the property `itemTitle`, use `heading` instead.
- Removed the property `itemSubtitle`, use `description` instead.
=> refactor(stepper-item)!: Remove deprecated properties

src/components/list-item/list-item.e2e.ts, src/components/list-item/list-item.scss, src/components/list-item/list-item.tsx, src/components/list-item/resources.ts, src/components/list/list.stories.ts
**Related Issue:** #3032
feat(list-item): Add slot for specialized content #3032
- Adds a new `content` slot to the `list-item` for customized content.
- `content` slot takes precedence over `label` and `description` properties.
=> feat(list-item): Add content slot for specialized content

src/components/input-number/input-number.tsx, src/demos/input-number.html
BREAKING CHANGE: remove deprecated property and event payload
- Removed `locale` property, use `lang` instead.
- Removed `calciteInputNumberInput` event payload properties, use the event's `target`/`currentTarget` instead.
=> refactor(input-number)!: remove deprecated property and event payload

package-lock.json, package.json
**Related Issue:** #5906
We are getting ECONNREFUSED puppeteer errors in our e2e PR check coming from Stencil:
https://github.com/Esri/calcite-components/actions/runs/3643107114/jobs/6150969791#step:6:5592
We just bumped our stencil version recently so I'm hoping this fixes it.  :crossed_fingers: 
Although there is an existing issue from before 2.20 came out, and I've been getting these same errors on my  Ubuntu-based distro forever now
https://github.com/ionic-team/stencil/issues/3853
=> build(deps): downgrade stencil due to e2e errors in ci

.github/workflows/deploy-next.yml, .github/workflows/pr-e2e.yml, package-lock.json, package.json
**Related Issue:** #5941
**Stencil Issue**: https://github.com/ionic-team/stencil/issues/3853
Downgrading Stencil didn't fix the ECONNREFUSED errors in the e2e test CI. After more investigating it turns out GitHub just recently bumped their action runner's  `ubuntu-latest` version from Ubuntu `v20.04` to `v22.04`. 
- Downgrades The runner's Ubuntu version back to `v20.04`. 
- Reupgrades Stencil to `v2.20`
- https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
- https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/
=> chore: bump stencil and downgrade e2e action runner

src/components/switch/switch.e2e.ts, src/components/switch/switch.tsx, src/demos/switch.html
BREAKING CHANGE: Removed deprecated `switched` property and `calciteSwitchChange` event payload.
- Removed the property `switched`, use `checked` instead.
- Removed the `event.detail` from `calciteSwitchChange`, use `event.target.checked` instead.
=> refactor(switch)!: Remove deprecated property and event payload.

src/components/color-picker/color-picker.tsx, src/components/tab-nav/readme.md, src/components/tab-nav/tab-nav.e2e.ts, src/components/tab-nav/tab-nav.scss, src/components/tab-nav/tab-nav.tsx, src/components/tab-nav/usage/Basic.md, src/components/tab-title/tab-title.e2e.ts, src/components/tab-title/tab-title.scss, src/components/tab-title/tab-title.tsx, src/components/tab/interfaces.ts, src/components/tab/tab.e2e.ts, src/components/tab/tab.tsx, src/components/tabs/interfaces.ts, src/components/tabs/readme.md, src/components/tabs/tabs.e2e.ts, src/components/tabs/tabs.scss, src/components/tabs/tabs.stories.ts, src/components/tabs/tabs.tsx, src/components/tabs/usage/Basic.md, src/components/tabs/usage/Bordered.md, src/demos/tabs.html
BREAKING CHANGE: Removed deprecated properties and values.
- Removed the property `active` from `calcite-tab-title`, use `selected` instead.
- Removed the property `active` from `calcite-tab`, use `selected` instead.
- Removed the `above` value from the `position` property on `calcite-tabs`, use `top` instead.
- Removed the `below` value from the `position` property on `calcite-tabs`, use `bottom` instead.
=> refactor(tabs, tab-nav, tab-title, tab)!: Remove deprecated properties and values.

src/utils/floating-ui.spec.ts
**Related Issue:** #5939
I kept getting type errors coming from `floating-ui.spec.ts` when trying to run the demos. After some quick maths I determined fixing them would be faster than restarting the dev server every 15 minutes
One of them was my fault from the PR linked above, I made the `placements` array a const so it could be used as a type but didn't check the spec tests. Not sure where the `referenceEl` error came from but renaming the param fixed it.
=> test(floating-ui): fix type errors

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx
BREAKING CHANGE: Removed the `active` property, use `open` instead.
=> refactor(input-time-picker)!: Remove deprecated active property

src/components/date-picker/date-picker.e2e.ts, src/components/date-picker/date-picker.stories.ts, src/components/date-picker/date-picker.tsx, src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-date-picker/input-date-picker.tsx
BREAKING CHANGE: Removed the `locale` property, use `lang` instead.
=> refactor(input-date-picker,date-picker)!: Removing deprecated locale properties

src/components/alert/alert.stories.ts, src/components/date-picker/date-picker.stories.ts, src/components/dropdown/dropdown.stories.ts, src/components/list/list.stories.ts, src/components/loader/loader.stories.ts, src/components/modal/modal.stories.ts, src/components/pagination/pagination.stories.ts, src/components/popover/popover.stories.ts, src/components/progress/progress.stories.ts, src/components/slider/slider.stories.ts
**Related Issue:** https://github.com/Esri/calcite-components/issues/4825#issuecomment-1335921930
Adds a chromatic snapshot delay to the components giving false positives. I also disabled animation for some of the floating-ui components, but only the NoTest ones so it doesn't effect the hosted stories. If the delay doesn't help I'll set the diffThreshold to `1` for the specific stories that fail, until I can do some additional digging.
=> test(chromatic): add delay and disable animation on some stories

src/utils/focusTrapComponent.ts
**Related Issue:** #5993
fix(popover, modal): deactivate focus trap on outside click.
https://github.com/focus-trap/focus-trap/blob/master/README.md
=> fix(popover, modal): deactivate focus trap on outside click

src/components/action-bar/action-bar.e2e.ts, src/components/action-bar/action-bar.tsx, src/components/action-group/action-group.tsx, src/components/action-menu/action-menu.e2e.ts, src/components/action-menu/action-menu.tsx, src/components/action-pad/action-pad.e2e.ts, src/components/action-pad/action-pad.tsx
BREAKING CHANGE: Removed event.
- Removed the event `calciteActionMenuOpenChange`, use `calciteActionMenuOpen` instead.
=> refactor(action-menu): remove event `calciteActionMenuOpenChange`

src/components/action-menu/action-menu.tsx
BREAKING CHANGE: Removed event.
- Removed the event `calciteActionMenuOpenChange`, use `calciteActionMenuOpen` instead.
=> refactor(action-menu)!: remove event `calciteActionMenuOpenChange`

src/components/date-picker/date-picker.tsx, src/components/date-picker/interfaces.d.ts, src/components/date-picker/interfaces.ts, src/components/input-date-picker/input-date-picker.tsx, src/demos/date-picker.html
- Removed the `event.detail` property on the event `calciteDatePickerChange`, use `event.target` instead.
- Removed the `event.detail` property on the event `calciteDatePickerRangeChange`, use `event.target` instead.
=> refactor(date-picker)!: remove `event.detail` payload from events

src/components/tip-manager/tip-manager.tsx, src/components/tip/readme.md, src/components/tip/tip.e2e.ts, src/components/tip/tip.stories.ts, src/components/tip/tip.tsx, src/components/tip/usage/Basic.md, src/demos/notice.html, src/demos/tip/basic.html
BREAKING CHANGE: Renamed property.
- Renamed the property `nonDismissible`, use `closeDisabled` instead.
=> refactor(tip)!: Rename property

src/components/chip/chip.e2e.ts, src/components/chip/chip.tsx, src/components/chip/readme.md, src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx, src/demos/chip.html
BREAKING CHANGE: Renamed event.
- Renamed the event `calciteChipDismiss`, use `calciteChipClose` instead.
=> refactor(chip)!: Rename event

src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx
BREAKING CHANGE: Removed `event.detail` payload from events and added properties `selectedItems` and `filteredItems`.
- Removed the `event.detail` property on the event `calciteComboboxChange`, use `event.target.selectedItems` instead.
- Removed the `event.detail` property on the event `calciteComboboxFilterChange`, use `event.target.filteredItems` or `event.target.value`   instead.
=> refactor(combobox)!: remove `event.detail` payload from events

src/components/rating/rating.e2e.ts, src/components/rating/rating.tsx
- Removed the `event.detail` property on the event `calciteRatingChange`, use `event.target` instead.
=> refactor(rating)!: remove `event.detail` payload from events

src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.tsx, src/components/dropdown/interfaces.ts
- Removed the `event.detail` property on the event `calciteDropdownSelect`, use `event.target` instead.
=> refactor(dropdown)!: remove `event.detail` payload from events

src/components/pagination/pagination.e2e.ts, src/components/pagination/pagination.tsx
- Removed the `event.detail` property on the event `calcitePaginationChange`, use `event.target` instead.
=> refactor(pagination)!: remove `event.detail` payload from events

src/components/tree/interfaces.ts, src/components/tree/tree.e2e.ts, src/components/tree/tree.tsx, src/demos/tree.html
BREAKING CHANGE: Removed `event.detail` payload from events and added `selectedItems` property.
- Added property `selectedItems`.
- Removed the `event.detail` property on the event `calciteTreeSelect`, use `event.target` instead.
=> refactor(tree)!: remove `event.detail` payload from events

src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/date-picker-month/date-picker-month.tsx, src/components/date-picker/date-picker.tsx
BREAKING CHANGE: Removed events.
- Removed the event `calciteDatePickerSelect` on `CalciteDatePickerMonthHeader`
- Removed the event `calciteDatePickerSelect` on `CalciteDatePickerMonth`
- Removed the event `calciteDatePickerActiveDateChange` on `CalciteDatePickerMonth`
=> refactor(date-picker-month, date-picker-month-header)!: Remove events.

src/components/radio-group/radio-group.e2e.ts, src/components/radio-group/radio-group.tsx
- Removed the `event.detail` property on the event `calciteRadioGroupChange`, use `event.target` instead.
=> refactor(radio-group)!: remove `event.detail` payload from events

src/components/accordion-item/accordion-item.tsx, src/components/accordion/accordion.e2e.ts, src/components/accordion/accordion.stories.ts, src/components/accordion/accordion.tsx, src/components/accordion/interfaces.ts, src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.stories.ts, src/components/combobox/combobox.tsx, src/components/combobox/interfaces.ts, src/components/combobox/usage/Multiple.md, src/components/dropdown-group/dropdown-group.tsx, src/components/dropdown-group/interfaces.ts, src/components/dropdown-item/dropdown-item.tsx, src/components/dropdown/dropdown.stories.ts, src/components/interfaces.ts, src/components/list-item/list-item.tsx, src/components/list/list.tsx, src/components/list/resources.ts, src/components/tree-item/tree-item.tsx, src/components/tree/interfaces.ts, src/components/tree/tree.stories.ts, src/components/tree/tree.tsx, src/demos/dropdown.html
BREAKING CHANGE: Removes `multi` value of `selection-mode`.
Removes the `multi` value for `selection-mode` property, use `multiple` instead.
=> refactor(accordion, combobox, dropdown, list, tree)!: Remove deprecated "multi" value

src/index.html
Truly the smallest PR for a busted scale value I introduced earlier - once you see it you can't unsee it:
=> chore(docs): Cleanup local index page

src/utils/locale.ts
All of the locale properties have been removed so this can be safely nuked 💣
=> refactor(locale): remove unused property from LocalizaedComponent

src/components/color-picker/color-picker.tsx, src/components/input/input.tsx, src/components/interfaces.ts
BREAKING CHANGE: remove deprecated event payload
- Removed the `nativeEvent` payload property which was being used internally.
=> refactor(input)!: remove deprecated event payload

src/components/interfaces.ts
Adds a missing value to SelectionMode type - no errors are thrown when you try to extract a value that doesn't exist in the type. Not sure if there's a way to validate the requested Extract values?
For example:   
`@Prop({ reflect: true }) selectionMode: Extract<"single" | "single-persist" | "multiple", SelectionMode> = "multiple";`
doesn't throw an error since the default `multiple` exists in the defined type, however:
`@Prop({ reflect: true }) selectionMode: Extract<"single" | "single-persist" | "multiple", SelectionMode> = "single-persist";`
would have thrown an error.
=> chore(types): Adds missing value to SelectionMode

CHANGELOG.md
Either this PR or #6109 will be incorporated in. The difference is the sorting/organization of the components (_see first bullet point below for organization details_).
**This is the recommended PR for merging (as long as developers agree) so those interpreting our change log can discern changes by component instead of having to sift through the entire 700+ line breaking changes between `beta.98` and `beta.99`.** 🚀 
- Adds major refactoring to the changelog so components show breaking changes more effectively.
- Components now have all breaking changes grouped under their name once
- Exceptions are grouped breaking changes where multiple components were listed (such as `list`, `list-item`, `list-group`) 
- Adds readability improvements to the changelog for the …
=> docs(changelog): resort and modify indent levels and styling

src/components/date-picker/date-picker.tsx, src/components/date-picker/interfaces.d.ts
chore(date-picker): Remove unused deprecated interface.
=> chore(date-picker): Remove unused deprecated interface.

CHANGELOG.md
**Related Issue:** #5902
Adds context to the newly created `calciteDropdownItemSelect` event used on the parent component.
Includes:
- Context to the `dropdown` breaking change, and
- Provides additional details to the `dropdown-item` feature summary
=> docs(changelog): context to `calciteDropdownItemSelect` event

src/components/radio-group-item/radio-group-item.scss, src/components/radio-group-item/radio-group-item.tsx, src/components/radio-group/radio-group.scss, src/components/radio-group/radio-group.stories.ts, src/components/radio-group/radio-group.tsx, src/demos/radio-group.html
Adds `outline-fill` value for `appearance` property
-- 
As shown in this comment, adds another appearance value to `radio-group` cc @SkyeSeitz @ashetland 
https://github.com/Esri/calcite-components/issues/6095#issuecomment-1357968324
=> feat(radio-group): Add appearance type

.github/workflows/chromatic.yml
Chromatic says in their [baseline doc](https://www.chromatic.com/docs/branching-and-baselines#squash-and-rebase-merging) that squash merging and rebasing should automatically accept baseline changes.
But I just found some more doc on their [CLI page](https://www.chromatic.com/docs/custom-ci-provider#squashrebase-merge-and-the-main-branch) that says it may not work lol.
So I'm explicitly accepting changes to `master` as baseline, since they will be approved in PRs before merging. I swear, if this fixes it...
=> ci(chromatic): explicitly auto-accept changes to master as baseline

src/components/stepper/stepper.e2e.ts, src/components/stepper/stepper.tsx
BREAKING CHANGE: Removed `event.detail` payload from event and added `selectedItem` property.
- Added property `selectedItem`.
- Removed the `event.detail` property on the event `calciteStepperItemChange`, use `event.target` and the property `selectedItem` instead.
=> refactor(stepper)!: remove event.detail payload from event and add property

src/components/radio-button-group/radio-button-group.e2e.ts, src/components/radio-button-group/radio-button-group.tsx
BREAKING CHANGE: Removed `event.detail` payload from event and added `selectedItem` property.
- Added property `selectedItem`.
- Removed the `event.detail` property on the event `calciteRadioButtonGroupChange`, use `event.target` and the property `selectedItem` instead.
=> refactor(radio-button-group)!: remove `event.detail` payload from event and add property

src/components/modal/modal.tsx, src/components/popover/popover.tsx, src/utils/focusTrapComponent.spec.ts, src/utils/focusTrapComponent.ts
**Related Issue:** #6140
feat(popover, modal): Add the ability to update focus trap elements after initialization.
- Adds `updateFocusTrapElements` method to each `FocusTrap` component.
- This method allows a user to update the focus trap elements after the focus trap has been initialized
```js
const modal = document.querySelector("calcite-modal");
const input = document.createElement("calcite-input");
content.appendChild(input);
await input.componentOnReady(); // To make sure the input has been rendered
await modal.updateFocusTrapElements(); // The new method to update focusable elements
requestAnimationFrame(() => input.setFocus()); // Wait for next frame to set focus
```
=> feat(popover, modal): Add the ability to update focus trap elements after initialization.

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
**Related Issue:** #6131
Adds a label in the issue templates for the ArcGIS Monitor team for:
- a11y issues 
- bugs 
- enhancements, and
- new components
=> chore: add esri monitor team label to issue templates

src/components/popover/PopoverManager.ts, src/components/popover/popover.tsx
BREAKING CHANGE: Removed the `toggle` method, use the `open` property instead.
=> refactor(popover)!: remove `toggle` method.

src/components/color-picker/assets/color-picker/t9n/messages_en.json
This PR will add missing message in `en` bundle of `calcite-color-picker`.
=> chore(color-picker): add missing message in `en` bundle

src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.e2e.ts
BREAKING CHANGE: Removed the `toggleSelected` method, use the `selected` property instead.
=> refactor(combobox-item)!: remove `toggleSelected` method.

package-lock.json, package.json
#6131 - Updates calcite ui icons to 3.20.7
=> build(deps): bump calcite-ui-icons from 3.20.5 to 3.20.7

src/components/flow-item/flow-item.tsx
**Related Issue:** #6178
Makes the showBackButton property used by the parent flow internal
=> docs(flow-item): make showBackButton internal

src/components/action-bar/action-bar.tsx, src/components/action-pad/action-pad.tsx, src/components/alert/alert.tsx, src/components/block-section/block-section.tsx, src/components/block/block.tsx, src/components/dropdown/dropdown.tsx, src/components/flow/flow.tsx, src/components/notice/notice.tsx, src/components/shell-panel/shell-panel.tsx, src/components/shell/shell.tsx, src/components/stepper/stepper.tsx, src/components/tab/tab.tsx, src/components/tile-select-group/tile-select-group.tsx, src/components/tree-item/tree-item.tsx, src/components/value-list-item/value-list-item.tsx
**Related Issue:** #3097  
Adds consistency to slot documentation across components. Particular focus on default slots to describe as "A slot for adding custom content". 
Also includes an in-depth review and update across all component slots.
=> docs: consistent slot messaging across components

CHANGELOG.md
There were many missing updates last week to the CHANGELOG, since the `beta.99` release which needed to be added in.^
Changes, including breaking changes, features, and bug fixes have been added between beta.99 to-date.
^ Note: It looks like changes to the CHANGLOG are being added in as of this week.
=> docs(changelog): update to incorporate missing changes since beta.99

src/components/scrim/scrim.tsx
Removes the extraneous `/**` from the docs. ❌
Looks like one line was missed with the [`intl` prop cleanup](https://github.com/Esri/calcite-components/commit/7dd5a387890709821c8059de8e8009feafb82a03#diff-1cbaac05a0c00caf59b9867d23256a9cc0e9cf8c9ad332d00ec914f943641396).
=> docs(scrim): remove extraneous line

src/components/modal/modal.scss
**Related Issue:** #1707
`padding-block` was changing the header height for me when toggling the back button. Removing it didn't seem to change the close button positioning in any way. `padding-inline` was added in #5210 for reference
=> fix(modal): close button does not change header height

src/components/modal/modal.tsx
**Related Issue:** #5856
Add context to the `modal`s `setFocus` method where the focus will be set on the component's "close" button.
=> docs(modal): provide context to setFocus method

src/components/input-number/input-number.e2e.ts, src/components/input-number/input-number.tsx, src/components/input/input.e2e.ts, src/components/input/input.tsx
**Related Issue:** #6201
Follows the native input's behavior by incrementing/decrementing to the `min`/`max` property when `value` is below/above
=> fix(input, input-number): increment/decrement to the min/max when value is below/above

.github/workflows/add-esri-product-label.yml
**Related Issue:** #5851
The Esri product team labeler was running into the same timing issue as another action linked above.
=> ci: fix timing issue in esri team labeler action

src/components/action-bar/action-bar.tsx, src/components/action-pad/action-pad.tsx, src/components/alert/alert.tsx, src/components/chip/chip.tsx, src/components/color-picker/color-picker.tsx, src/components/inline-editable/inline-editable.tsx, src/components/list/list.tsx, src/components/notice/notice.tsx, src/components/panel/panel.tsx, src/components/pick-list/pick-list.tsx, src/components/popover/popover.tsx, src/components/stepper-item/stepper-item.tsx, src/components/time-picker/time-picker.tsx, src/components/value-list/value-list.tsx
**Related Issue:** #6139
Adds context ~to the `panel` and `popover` docs~ **across our components** for the `setFocus` refactor. ~~Where when called will set focus on the component's first focusable element.~~ 
Where when called will either set focus on the component or its first focusable element. Some components first focusable element will be a close button.
Unchanged components with `setFocus` where focus is set on the component, such as `calcite-action`, and the context of "Set focus on the component" is still valid.
=> docs: update setFocus method across components

.github/workflows/add-esri-product-label.yml
**Related Issue:** #6192
Fixes the team labeler action toggling labels
=> ci: make sure action doesn't remove existing team label

src/components/alert/alert.tsx
**Related Issue:** #6222 
This should fix the problem described in the issue - it now handles multiple "hover on and off" events and, at least in local testing, seems to handle large queues that may be present pretty well. The events used were changed to fire less often, and there's an accrued timer of hover time that now is used to determine remaining duration before dismissal.
The watcher for changing the duration now resets it to the default, so unless a user interacts with the alert, it may display for a bit longer. Although, I can't think of a use case where this would be changed while an alert is open, we do use it in demos, and we could refactor this code to better support that if needed.
https://user-images.githubusercontent.com/4733155/210485461-c77e8948-af76-4c61-b965-306fc0a9d97 …
=> fix(alert): Correctly dismiss after hovering

src/components/list/list.tsx, src/components/pick-list/pick-list.tsx, src/components/value-list/value-list.tsx
Removes duplicate references to read only, where we can rely on the JSDoc tag for our docs site.
=> docs(list,pick-list,value-list): remove duplicate read only refs

src/components/tooltip/tooltip.stories.ts, src/components/tooltip/usage/Basic.md
**Related Issue:** #6211 
- Adds assistive technology (AT) support with the tooltip content reference in a `span` element.
- Removes the button's `title` attribute.
=> docs(tooltip): assistive technology story support

src/components/pick-list-group/pick-list-group.tsx, src/components/pick-list-item/pick-list-item.tsx, src/components/pick-list/pick-list.tsx, src/components/value-list-item/value-list-item.tsx, src/components/value-list/value-list.tsx
**Related Issue:** #6157
In addition to documentation page deprecation notices, adds a JSDoc `@deprecation` tag to the following components:
- `pick-list`
- `pick-list-group`
- `pick-list-item`
- `value-list`
- `value-list-item`
=> docs(pick-list,pick-list-group,pick-list-item,value-list,value-list-item): deprecate components

src/components/accordion-item/accordion-item.tsx, src/components/button/button.tsx, src/components/dropdown-item/dropdown-item.tsx, src/components/link/link.tsx, src/components/split-button/split-button.tsx, src/components/tab-title/tab-title.tsx
**Related Issue:** #5496 
Adds context to components that have the `iconFlipRtl` prop and multiple icons.
Where the prop is not a boolean (like the majority of the other components with the prop) and needs context pertaining to the values of `"start"`, `"end"`, and `"both"`.
Applies to the following components:
- accordion-item
- button
- dropdown-item
- link
- split-button
- tab-title
=> docs: add context to `iconFlipRtl` for components with the `FlipContext` interface

src/05-custom-theme.stories.mdx, src/components/card/card.scss, src/components/card/card.stories.ts, src/components/card/card.tsx, src/components/card/readme.md, src/components/card/resources.ts, src/demos/card.html, src/demos/chip.html, src/demos/modal.html
BREAKING CHANGE: rename footer-leading and footer-trailing slots to footer-start and footer-end
- Removed `footer-leading` and `footer-trailing` slots, use `footer-start` and `footer-end` instead
=> refactor(card)!: rename footer-leading and footer-trailing slots to footer-start and footer-end

src/components/panel/panel.scss
Adds a rule to make panel respect an explicitly set height of the parent container.
Before: 
After:
=> feat(panel): Allow Panel to fill height of parent

src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.stories.ts
**Related Issue:** #5698
Bumping the scale of the icon to M when the parent `combobox-item` is scale="l" for a visual distinction between larger and smaller components without affecting the height of the `combobox-item` when icon(s) are added or removed. Added a _testOnly snapshot.
=> fix(combobox-item): bumping the scale of icon to M when parent combobox is scale L

src/components/input-time-picker/input-time-picker.tsx, src/components/input-time-picker/readme.md
BREAKING CHANGE: Removed event payload information.
- Removed the event payload from `calciteInputTimePickerChange` event.
=> refactor(input-time-picker)!: remove string payload from event.

src/components/date-picker/date-picker.scss
- Updates Date Picker border color
--
cc @ashetland  @SkyeSeitz
=> feat(date-picker): Update border color

package-lock.json, package.json
**Related Issue:** https://github.com/Esri/calcite-components/pull/5639/files#r1067566974
Upgrades `calcite-colors` to `6.1.0`.
=> build: bump calcite-colors to latest

src/components/input-date-picker/input-date-picker.tsx, src/utils/date.spec.ts, src/utils/date.ts
**Related Issue:** https://github.com/Esri/calcite-components/pull/6289#pullrequestreview-1252734747
Adds a spec test for `dateToISO`.  Also updates the function to return a proper empty string value when any non-`Date` value is passed in.
=> test(date): add test for dateToISO utility function

src/components/combobox/combobox.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/input-number/input-number.tsx, src/components/input-text/input-text.tsx, src/components/input/input.tsx, src/components/radio-button/radio-button.tsx, src/components/rating/rating.tsx, src/components/segmented-control/segmented-control.tsx, src/components/select/select.tsx, src/components/slider/slider.tsx, src/components/switch/switch.tsx
**Related Issue:** #5284
1. Adds context to the `name` prop on components used for form submission.
2. Also, includes a missing backtick on a `value` prop for the `input` component.
=> docs: context to name prop for form submission

src/05-custom-theme.stories.mdx, src/components/pagination/pagination.e2e.ts, src/components/pagination/pagination.stories.ts, src/components/pagination/pagination.tsx, src/components/pagination/usage/Basic.md, src/demos/pagination.html
**Related Issue:** #6285 
BREAKING CHANGE: Rename properties.
- Removed the property `num`, use `pageSize` instead.
- Removed the property `total`, use `totalItems` instead.
- Removed the property `start`, use `startItem` instead.
=> refactor(pagination)!: rename properties.

src/components/tree-item/resources.ts, src/components/tree-item/tree-item.scss, src/components/tree-item/tree-item.tsx, src/utils/openCloseComponent.ts
**Related Issue:** #6284
This issue only occurs on the `custom-elements` and `dist` output builds, not the CDN. It is a timing issue where the item is expanded on initial load before the transition event listeners that handle styling are added. The fix uses a flag to make sure the transition start/end event listeners are added on initial load before the tree item expands.
=> fix(tree): expanded item renders correctly on initial load

src/components/select/select.stories.ts, src/components/select/select.tsx
**Related Issue:** #5698
Bumping the scale of the chevron to M when host is scale="l" for a visual distinction between larger and smaller components without affecting the height of the component when icon(s) are added or removed. Added a _testOnly snapshot.
=> fix(select): bumping scale of chevron icon to M when host is scale l

package.json
Adds an NPM script that removes all of the javascript files compiled by tsc when doing the type check before releases.
=> ci: add npm script to remove js files compiled by tsc

src/components/pagination/pagination.stories.ts, src/components/pagination/pagination.tsx
**Related Issue:** #5698
Bumping the `scale` of the `chevron` to M when host is `scale="l"` for a visual distinction between larger and smaller components without affecting the height of the component when icon(s) are added or removed. Added a _testOnly snapshot.
=> fix(pagination): bumping scale of chevron icon to M when host is scale L

src/components/progress/progress.tsx
**Related Issue:** #6345 
Clarifies the Progress' `value` prop to be reflected when `type` is `"determinate"`.
=> docs(progress): update value prop for determinate types

src/components/popover/popover.scss, src/components/popover/popover.stories.ts
**Related Issue:** #5803 
Fixes the x and y padding applied to the popover's heading (they were inverted).
**Note**: I included simple test stories for s, m and l scales. I can tweak these as needed based on our Chromatic setup.
=> fix(popover): fix heading padding for m and l scales

src/components/split-button/split-button.scss, src/components/split-button/split-button.stories.ts
**Related Issue:** #6332 
This PR will remove the divider background color when `appearance="transparent"` with `kind="color"`
Before the change:
After the change:
=> fix(split-button): no longer displays divider for transparent with inverse kind

src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #6198 
This PR restores the normal behavior of displaying the proper characters according to the specified numbering system in the input.
=> fix(input-date-picker): input renders numbers in the specified numbering system

src/components/alert/alert.scss, src/components/alert/alert.stories.ts, src/components/alert/alert.tsx
**Related Issue:** #6348
The bottom left corner radius was missing when the icon was present. Upon inspection, it was clear that slots added around content don't have the proper radius set and end up covering the radius on the host. For each occasion the slot is placed against either end of the host, I adjusted the relevant radius to match the host container. 
Because the close button is now always present, the cases addressed are the right side of the close button and the left side of the content (no icon) along with the left side of the icon (when placed in front of the content).
Added a screenshot for the radius with options where `icon` is present and absent.
=> fix(alert): ensure `border-radius` is consistent for prescribed `slots`

src/components/tree-item/tree-item.scss, src/components/tree/tree.stories.ts
**Related Issue:** #6367
Restores styles needed to properly contain expanded item line that removed in https://github.com/Esri/calcite-components/pull/6005.
=> fix(tree): prevent lines from expanded item from bleeding out of container

src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.e2e.ts, src/components/stepper/stepper.tsx
**Related Issue:** #6331 
This PR will fix the issue of `stepper` component's numbers being localized to the `numberingSystem` specified by neighboring `stepper` component rendered in same page.
=> fix(stepper-item): no longer refer numberingSystem from neighbor stepper component

.versionrc.json
**Related Issue:** #6355
I added markdown lint in the PR above but it isn't running during releases because we have `standard-version` set to `noVerify`. So this is manually linting the readme/changelog before committing.
=> ci(release): lint readme and changelog before committing

package-lock.json, package.json
Updates [calcite-ui-icons](https://www.npmjs.com/package/@esri/calcite-ui-icons) to `3.21.0` for the upcoming patch release, which includes [additional icons Esri teams are interested in](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.21.0).
=> build(deps): bump calcite-ui-icons from 3.20.7 to 3.21.0

src/components/date-picker-month/date-picker-month.tsx, src/components/date-picker/date-picker.tsx
**Related Issue:** #6194 
This PR fixes an issue where the days previous to the currently hovered day are highlighted incorrectly when no start or end value exists.  There should be no hover styles applied to any days other than the currently hovered day unless a start or an end date exists.
=> fix(date-picker): days previous to the currently hovered day when no range value exists display correctly with no hover styles

src/components/pick-list-group/pick-list-group.tsx, src/components/pick-list-item/pick-list-item.tsx, src/components/pick-list/pick-list.tsx, src/components/value-list-item/value-list-item.tsx, src/components/value-list/value-list.tsx
Mitigates slots populated in our docs for deprecated components.
Refer to [additional context](https://github.com/Esri/calcite-components/pull/6418#issuecomment-1416241405) from a PR closed earlier regarding formatting.
=> docs: fix slot creation for deprecated components

src/components/functional/Heading.spec.tsx
Passing a component is not necessary for this spec page test, so this cleans that up. This came up after some digging around where local test runs (w/ `--watchAll`) would fail after making changes to code:
> [ ERROR ]  Rollup: Parse Error
Unexpected token (Note that you need plugins to import files that are not JavaScript) 94: export {
CalciteValueList, defineCustomElement as defineCustomElementCalciteValueList } from
'CalciteValueList'; 95: export { CalciteValueListItem, defineCustomElement as
defineCustomElementCalciteValueListItem } from 'CalciteValueListItem'; 96: export { {DummyComponent
} from 'DummyComponent'; ^
=> test(heading): remove unnecessary dummy component for spec test

src/components/icon/utils.spec.ts, src/components/icon/utils.ts
**Related Issue:** #6272
This fixes an issue where our icon names weren't mapped correctly to some newly added icons (e.g., `1x`, `1-8x`).
=> fix(icon): fix icon normalization to handle x-times-named icons

src/components/tree-item/tree-item.scss
**Related Issue:** #6376
Reverses regression to bring back focus when navigating with the keyboard and a small cleanup on the existing code.
=> fix(tree-item): reverses regression to bring back focus when navigating with keyboard

src/components/segmented-control/segmented-control.tsx
**Related Issue:** #6427 
Adds context to the event description and removes the `event.detail` reference, where the payload is now set by `event.target`.
=> docs(segmented-control): update event description for calciteSegmentedControlChange

src/components/action-group/action-group.e2e.ts, src/components/action-group/action-group.tsx, src/components/date-picker/date-picker.e2e.ts, src/components/date-picker/date-picker.tsx, src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.tsx, src/components/pagination/pagination.e2e.ts, src/components/pagination/pagination.tsx, src/components/split-button/split-button.e2e.ts, src/components/split-button/split-button.tsx, src/tests/commonTests.ts
This reverts commit ceaf5320bd0f9fdeff4f4a7180e4a718c9743031.
The commit above will be reinstalled in the next few days after we release a patch.
=> revert: "feat(pagination, split-button, dropdown, date-picker) action-group): add setFocus method (#6405)"

stencil.config.ts
**Related Issue:** #6419
Resolves errors that occurs when lazy loading the components in Vite using the `dist` build.
https://stenciljs.com/docs/config-extras#experimentalimportinjection
The doc linked above mentions an increase in bundle size, here is the before and after using my `build-sizes` npm package.
```
-----------------------------
|> Application Build Sizes <|
-----------------------------
Build
--> file count: 9178
--> size: 12.07 MB
--> size on disk: 13.75 MB
-----------------------------
Main JS bundle
--> name: calcite-color-picker_3.cjs.entry.js
--> size: 100.12 KB
--> gzip size: 24.33 KB
--> brotli size: 21.01 KB
-----------------------------
```
```
-----------------------------
|> Application Build Sizes <|
-----------------------------
Build
--> file count: 9316
--> …
```
=> fix(vite): resolve lazying loading error in dist build

.versionrc.json
**Related Issue:** #6406
The commit messages for `next` releases are goofed. This removes our custom `{{currentTag}}` commit message and replaces it with the default: `chore(release): {{currentTag}}`.
It also removes `noVerify` so we can remove `npm run lint:md` because it will be done by `lint-staged`.
The commit message was fine before the PR linked above. No idea why this is happening but it's probably a `standard-version` bug
=> ci(next): fix commit message

package-lock.json, package.json
**Related Issue:** #6440
Updates [calcite-ui-icons](https://www.npmjs.com/package/@esri/calcite-ui-icons) to 3.21.2 for the upcoming patch release, which includes [additional icons Esri teams are interested in](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.21.2).
Verified the `analysis-overlay` icons are present for all sizes locally.
=> build(deps): bump calcite-ui-icons from 3.21.0 to 3.21.2

src/components/input-number/input-number.e2e.ts, src/components/input-number/input-number.tsx, src/components/input-text/input-text.e2e.ts, src/components/input-text/input-text.tsx, src/components/input/input.e2e.ts, src/components/input/input.tsx
**Related Issue:** #4232
Updates value-setting code to treat programmatically-set values as the last emitted one, which is used to determine whether to emit or not.
=> fix(input, input-number, input-text): emit change value when clearing programmatically-set value

src/components/modal/modal.e2e.ts, src/components/popover/popover.e2e.ts, src/utils/focusTrapComponent.spec.ts, src/utils/focusTrapComponent.ts
**Related Issue:** #6281 
This PR will fix `focusTrap` issue when user clicks inside the `modal`. When user clicks inside the modal, `focusTrap` behavior wont be affected.
=> fix(modal): no longer loses focus trap after clicking inside the component.

stencil.config.ts
**Related Issue:** #6419 
This fixes an issue with lazy-loading components when using Calcite Components in a Vite project with the `dist` Stencil output target.
Here's how I verified this fix locally:
1. Clone the [vite example from `calcite-components-examples`](https://github.com/Esri/calcite-components-examples/tree/master/vite)
2. Run `npm install`
3. Replace the source code in `main.js` with:
```
import { defineCustomElements } from "@esri/calcite-components/dist/loader";
defineCustomElements(window);
import "@esri/calcite-components/dist/calcite/calcite.css";
```
4. Checkout this branch In the local copy of calcite, run `npm run build` to generate the new `dist` build from the updated stencil configuration.
5. Then run `npm link` from within `calcite-components`
6. Back in the vite …
=> fix(vite): getting the dist build to work correctly with vite again

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml
Removes the placeholders for the repro/regression version fields since it looks like it was prefilled
=> ci: remove version placeholders from issue templates

src/components/modal/modal.e2e.ts, src/tests/utils.ts, src/utils/focusTrapComponent.spec.ts, src/utils/focusTrapComponent.ts
**Related Issue:** #6454 
This fixes an issue caused by setting the `tabindex` attribute on the host element instead of the property ([previous behavior](https://github.com/Esri/calcite-components/pull/6434)). 
* When `tabindex` was set, `focus-trap` seemed to move focus to the host as focus fallback even if focus was already set within the focus trap. We should look into only setting the host as focus fallback if there is no focusable content within the trap.
* The `tabindex` setting logic was removed instead of being rolled back because the [previous version](https://github.com/Esri/calcite-components/blob/059d6eee6a8dc0a0d74db6e113d30cafebac25bb/src/utils/focusTrapComponent.ts#L33-L35) was misleading and would never be invoked (`HTMLElement.tabIndex` [is always an …
=> fix(focus-trap): prevent host from receiving initial focus

.eslintrc.json
Change `@typescript-eslint/no-unused-vars` rule severity to `error` to prevent unused imports from being committed.
=> chore(linting): block commits if there are unused imports

package-lock.json, package.json
The latest version fixes the following [bug](https://github.com/Jordan-Hall/stylelint-use-logical-spec/issues/28):
```scss
padding: var(--calcite-modal-content-padding, var(--calcite-modal-padding-internal));
```
_⬇️ after autofix_
```scss
// invalid syntax
padding-block: var(--calcite-modal-content-padding, ; padding-inline: var(--calcite-modal-padding-internal)); 
```
=> chore(deps): bump stylelint-use-logical-spec

.lintstagedrc.json, package.json
Drops an obsolete filter since we no longer have JS files in the codebase.
=> chore(linting): drop filter for JS file linting

.github/ISSUE_TEMPLATE/bug.yml, .github/workflows/add-bug-priority-label.yml
1. Adds a dropdown to the bug issue template so users can select a priority impact from a dropdown menu, which includes:
- `p3 - not time sensitive`
- `p2 - want for current milestone`
- `p1 - need for current milestone`
- `p0 - emergency`
2. Adds an action that automatically adds a label (and will create a label if its not yet created) similar to the `add-esri-product-label.yml`
cc @brittneytewks
=> ci: add user-defined priority

src/components/value-list-item/interfaces.ts, src/components/value-list-item/value-list-item.tsx, src/components/value-list/value-list.e2e.ts, src/components/value-list/value-list.tsx
**Related Issue:** #6401 
This PR will add back instructions for screen reader when drag handle is activated via `Space` key. 
Sidebar: This will also cover #5739
=> fix(value-list): add back instructions for screen reader when drag handle is activated

src/components/tree-item/tree-item.scss, src/components/tree/tree.stories.ts
**Related Issue:** #6514 
This drops any clipping and also ensures the min-height of tree-items adheres to the design spec while still allowing items to grow if needed to accommodate their content.
cc @SkyeSeitz @ashetland
=> fix(tree): prevent tree-item content from being clipped

src/components/tree-item/tree-item.scss, src/components/tree/tree.stories.ts
**Related Issue:** #6512 
Updates styles to restore text wrapping. Thanks @nwhittaker for the fix suggestion!
=> fix(tree): restore wrapping in tree-item text content

src/components/filter/filter.e2e.ts, src/components/filter/filter.tsx, src/components/list/list.e2e.ts, src/components/list/list.tsx
**Related Issue:** #6523
This fixes initial filtering on consumers of `calcite-filter`. 
* `updateListItems` (private) is no longer debounced to allow updated values to be passed to the internal filter. This was also called whenever the items are modified (`MutationObserver`), so this could be revisited later if we see noticeable impact on performance
* Corrected assertion where filteredItems and filteredData were not matching (one reflects the other)
* Added new test
* Removed a duplicate `filter` call that would interfere with the initial one – (introduced [here](https://github.com/Esri/calcite-components/pull/5471), possibly an oversight)
* Restored skipped test
* Updated test to cover filtering with default filter text
=> fix(filter, list): filter properly on initialization
