src/components/tab-title/tab-title.e2e.ts, src/components/tab-title/tab-title.scss, src/components/tab-title/tab-title.tsx, src/components/tab/tab.tsx, src/components/tabs/tabs.e2e.ts
**Related Issue:** #2124
fix(tab, tab-title): Fix accessibility and keyboard navigation. (#2124)
=> fix(tab, tab-title): Fix accessibility and keyboard navigation

src/components/tab-title/tab-title.tsx
refactor(tab-title): Fix event variable name.
=> refactor(tab-title): Fix event variable name.

src/assets/styles/_header.scss, src/components/block/block.stories.ts, src/components/panel/panel.stories.ts, src/components/pick-list-group/pick-list-group.scss, src/components/pick-list/pick-list.stories.ts, src/components/tip-manager/tip-manager.scss, src/components/tip-manager/tip-manager.stories.ts, src/components/tip/tip.scss
**Related Issue:** #4768
fix(pick-list-group, tip, tip-manager, block, panel): headingLevel should not adjust styling. (#4768)
=> fix(pick-list-group, tip, tip-manager, block, panel): headingLevel should not adjust styling

src/components/color-picker/color-picker.e2e.ts, src/components/date-picker/date-picker.e2e.ts, src/components/dropdown/dropdown.e2e.ts, src/components/fab/fab.e2e.ts, src/components/inline-editable/inline-editable.e2e.ts, src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-number/input-number.e2e.ts, src/components/input/input.e2e.ts, src/components/panel/panel.e2e.ts, src/components/popover-manager/popover-manager.e2e.ts, src/components/split-button/split-button.e2e.ts, src/components/tabs/tabs.e2e.ts, src/components/tree/tree.e2e.ts
* Adds missing `await`s 
* Replaces `Array.forEach` with `for...of` loops to ensure `await` works within loops
=> test: fix async issues

src/components/combobox/combobox.scss, src/components/combobox/combobox.stories.ts, src/components/dropdown/dropdown.scss, src/components/dropdown/dropdown.stories.ts, tailwind.config.ts
**Related Issue:** #4772
fix(combobox, dropdown): Make sure menus do not take up more than half of available height. (#4772)
=> fix(combobox, dropdown): Make sure menus do not take up more than half of available height by default

src/components/alert/alert.e2e.ts, src/components/alert/alert.scss, src/components/alert/alert.stories.ts, src/components/alert/alert.tsx
**Related Issue:** #4688
Deprecates `active` prop on `alert` component and syncs with `open`.
=> feat(alert): deprecates active prop and syncs with open

src/components/action-menu/action-menu.tsx
**Related Issue:** #4771
fix(action-menu): Correctly close on touch devices. (#4771)
=> fix(action-menu): Correctly close on touch devices

.github/workflows/codeql-analysis.yml
=> ci(codeql): bump codeQL actions

src/components/action-menu/action-menu.e2e.ts, src/components/action-menu/action-menu.scss, src/components/action-menu/action-menu.stories.ts, src/components/action-menu/action-menu.tsx
**Related Issue:** #5082
fix(action-menu): Fix focus styling and opening behavior. (#5082)
=> fix(action-menu): Fix focus styling and opening behavior

src/components/accordion/accordion.tsx, src/components/color-picker-hex-input/color-picker-hex-input.tsx, src/components/color-picker/color-picker.tsx, src/components/date-picker-day/date-picker-day.tsx, src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/dropdown/dropdown.tsx, src/components/radio-button/radio-button.tsx, src/components/radio-group/radio-group.tsx, src/components/slider/slider.tsx, src/components/switch/switch.tsx, src/components/time-picker/time-picker.tsx
=> refactor: deconstruct event key

src/components/block-section/block-section.tsx, src/components/checkbox/checkbox.tsx, src/components/color-picker/color-picker.tsx, src/components/date-picker-day/date-picker-day.tsx, src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/popover/PopoverManager.ts, src/components/slider/slider.tsx, src/components/switch/switch.tsx
=> refactor: use activationKey util

src/components/combobox/combobox.e2e.ts
**Related Issue:** #5218 
This will add an E2E test to verify if the user is able to tab through the `Combobox` by the `tab` key once and able to type.
=> test(combobox): add test to verify user is able to tab through the component

src/demos/dropdown.html
**Related Issue:** #5190
revert dropdown demo modification)](chore: revert dropdown demo modification
=> chore: revert dropdown demo modification

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx
feat(input-time-picker): Add overlayPositioning property.
=> feat(input-time-picker): Add overlayPositioning property.

src/components/action/action.e2e.ts, src/components/action/action.tsx, src/components/action/resources.ts, src/components/action/usage/With-text-displayed.md, src/components/action/usage/With-tooltip.md, src/components/action/usage/Without-text-displayed.md, src/demos/action.html
**Related Issue:** #4414
feat(action): Add a slot for a calcite-tooltip. #4414
=> feat(action): Add a slot for a calcite-tooltip

src/components/action-bar/action-bar.e2e.ts
test(action-bar): Stabilize tests.
=> test(action-bar): Stabilize tests.

src/components/input-date-picker/input-date-picker.stories.ts
test(input-date-picker): Fix test to specific date.
=> test(input-date-picker): Fix test to specific date.

src/components/panel/panel.e2e.ts, src/components/panel/panel.tsx
**Related Issue:** #5329
fix(panel): Do not close non closable panel on ESC key. (#5329)
=> fix(panel): Do not close non closable panel on ESC key

src/components/avatar/avatar.tsx
=> refactor(avatar): rename state var to drop comment

src/components/progress/progress.scss, src/components/progress/progress.stories.ts, src/demos/progress.html
**Related Issue:** #4840
Sets the text style through a theme color variable declared in the global file, to enable theming to be applied and inherited throughout the component tree.
=> fix(progress): text now responds to light/dark theme mode change

src/components/tile-select-group/tile-select-group.stories.ts, src/components/tile-select/tile-select.stories.ts
**Related Issue:** #5253
chore(tile-select): Fix storybook stories.
https://github.com/Esri/calcite-components/pull/5257/files#r977949817
=> chore(tile-select): Fix storybook story knobs.

src/components/slider/slider.e2e.ts, src/components/slider/slider.stories.ts, src/components/slider/slider.tsx
**Related Issue:** #5382 
This will fix the thumb position to be on the slider track at min value.
After the fix :
=> fix(slider): thumb no longer appears above track at min

.github/workflows/deploy-next.yml, support/prepReleaseCommit.ts
There is no way the error will keep happening after these changes. And no, those aren't famous last words. THEY'RE UNKNOWN FIRST WORDS OKAAY!?
I also split up the error messages so people don't have to guess when they run into issues, like I did for the last 3 PRs
=> ci: fix next releases take 4

src/components/handle/handle.scss, src/components/value-list-item/value-list-item.scss
**Related Issue:** #5541
fix(value-list-item): Change drag handle color.
=> fix(value-list-item): Change drag handle color.

src/assets/styles/_floating-ui.scss, src/components/tooltip/tooltip.stories.ts
**Related Issue:** #5680
fix(tooltip, popover): Fix pointer when text-align is right. #5680
=> fix(tooltip, popover): Fix pointer when text-align is right

conventions/Testing.md
Documentation only update to provide context to developers on writing end-to-end vs unit tests for their code.
=> docs(tests): end-to-end vs unit

.github/workflows/pr-screener.yml
**Related Issue:** #5703 #5478
Fix merge conflict issue
=> ci: fix merge conflict issue

src/components/dropdown/dropdown.e2e.ts
test(dropdown): Temporary fix to have tests pass for dropdown.
=> test(dropdown): Temporary fix to have tests pass for dropdown.

src/components/value-list-item/value-list-item.tsx
**Related Issue:** #5701
fix(value-list-item): Prevent scrolling when space is pressed on drag button. #5701
=> fix(value-list-item): Prevent scrolling when space is pressed on drag button

src/components/popover/PopoverManager.ts, src/components/popover/popover.e2e.ts
**Related Issue:** Part of #2133
feat(popover): Escape key should close open popovers.
=> feat(popover): Escape key should close open popovers.

src/components/value-list/value-list.e2e.ts
test(value-list): Skip unstable test.
=> test(value-list): Skip unstable test.

src/components/tree/tree.e2e.ts
**Related Issue:** #5745
test(tree): Skip unstable test.
=> test(tree): Skip unstable test.

src/components/filter/filter.tsx, src/components/filter/resources.ts, src/components/pick-list/pick-list.tsx, src/components/pick-list/shared-list-logic.ts, src/components/pick-list/shared-list-render.tsx, src/components/pick-list/shared-list-tests.ts, src/components/value-list/value-list.tsx
**Related Issue:** #4333
feat(pick-list, value-list): Add calciteListFilter event, filteredItems prop, filterText prop and filteredData prop. (#4333)
=> feat(pick-list, value-list): Add calciteListFilter event, filteredItems prop, filterText prop and filteredData prop.

CHANGELOG.md
docs: update changelog's breaking changes.
=> docs: update changelog's breaking changes.

src/components/tooltip/tooltip.e2e.ts, src/components/tooltip/tooltip.tsx
**Related Issue:** #5734
feat(tooltip): Add tooltip open, close, beforeOpen, and beforeClose events. (#5734)
=> feat(tooltip): Add tooltip open, close, beforeOpen, and beforeClose events

src/components/list-item/list-item.tsx
refactor(list-item): Use DOM utility for checking if slot has assigned element.
=> refactor(list-item): Use DOM utility for checking if slot has assigned element.

src/components/list/list.stories.ts
docs(list): Fix storybook filtering for list.
=> docs(list): Fix storybook filtering for list.

src/components/tree-item/tree-item.tsx, src/components/tree/interfaces.ts, src/components/tree/tree.e2e.ts, src/components/tree/tree.tsx
docs(tree): Update interface for selectionMode.
cc @macandcheese
=> docs(tree): Update interface for selectionMode.

package-lock.json, package.json
Reverts Esri/calcite-components#5833
=> build: Revert bump @whitespace/storybook-addon-html from 5.0.0 to 5.0.3

src/components/list-item/list-item.scss
**Related Issue:** #5880
fix(list-item): Add hover styling
=> fix(list-item): Add hover styling

src/components/color-picker/assets/color-picker/t9n/messages.json
**Related Issue:** #2841
Adding the string from the PR linked above because we are about to freeze strings and the PR needs a bit more work
=> chore(color-picker): add opacity string

CHANGELOG.md
Add indent levels to the changelog for readability.
=> docs(changelog): fix breaking change indent levels

src/components/input-time-picker/input-time-picker.e2e.ts
=> test(input-time-picker): fix type errors

src/components/dropdown-item/dropdown-item.e2e.ts, src/components/dropdown-item/dropdown-item.tsx
**Related Issue:** #5940
feat(dropdown-item): Add `calciteDropdownItemSelect` event. #5940
=> feat(dropdown-item): Add `calciteDropdownItemSelect` event

FAQ.md, src/05-custom-theme.stories.mdx, src/components/card/card.stories.ts, src/components/dropdown/dropdown.e2e.ts, src/components/dropdown/dropdown.scss, src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx, src/components/dropdown/readme.md, src/components/dropdown/resources.ts, src/components/dropdown/usage/Basic.md, src/components/dropdown/usage/Disabling-close-on-select.md, src/components/dropdown/usage/Groups.md, src/components/split-button/split-button.tsx, src/demos/card.html, src/demos/date-picker.html, src/demos/dropdown.html
BREAKING CHANGE: Removed slot.
- Removed the slot `dropdown-trigger`, use `trigger` instead.
=> refactor(dropdown)!: removed slot `dropdown-trigger`.

CHANGELOG.md
Fixes breaking change indent levels and changes the format of some items for consistency
=> docs(changelog): fixing breaking change formatting

src/components/interfaces.ts, src/components/modal/modal.scss, src/components/modal/modal.stories.ts, src/components/modal/modal.tsx, src/demos/modal.html
BREAKING CHANGE: Renamed `color` property and updated values.
- Renamed the property `color`, use `kind` instead.
- Updated the accepted values of `kind` to `brand`, `danger`, `info`, `success`, and `warning`.
=> refactor(modal)!: Renamed property and updated values

src/components/switch/switch.tsx
docs(switch): Remove deprecated event detail doc
=> docs(switch): Remove deprecated event detail doc

src/components/action/usage/Transparent-appearance.md, src/components/interfaces.ts, src/demos/action.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/5929
This one was already done 😄, this just cleans up a couple of outdated "clear" references.
=> chore(action): Clean up action appearance references

src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx
**Related Issue:** #5109
fix(combobox): Fix error when typing a custom value and then trying to open the menu. #5109
=> fix(combobox): Fix error when typing a custom value

conventions/Accessibility.md, src/components/graph/graph.tsx, src/components/icon/icon.tsx, src/components/loader/loader.tsx
**Related Issue:** #5616
fix(icon, graphic, loader): Set aria-hidden on internal svg elements
=> fix(icon, graphic, loader): Set aria-hidden on internal svg elements

src/components/button/button.scss
Added `-internal` postfix to clarify intent of non-public css vars: https://github.com/Esri/calcite-components/issues/5958
=> chore(button): Update internal css var

src/components/radio-group-item/radio-group-item.scss, src/components/radio-group/radio-group.tsx
BREAKING CHANGE:
- Removed `minimal` appearance value, use `outline` instead.
=> refactor(radio-group)!: Update `appearance` value

src/components/modal/modal.e2e.ts, src/components/modal/modal.scss
Documents the `--calcite-modal-scrim-background` css variable.
=> chore(modal): Expose css var 

src/components/action-menu/action-menu.e2e.ts, src/components/date-picker-month-header/date-picker-month-header.e2e.ts, src/demos/card.html, src/demos/color-picker.html, src/demos/input.html, src/tests/commonTests.ts, src/utils/t9n.ts
This PR will remove unused util methods in t9n interface which are no longer used and removes any existing `intl` property reference across the repo.
=> chore: remove unused util methods & deprecated `intl*` property references.

src/components/input-date-picker/usage/Basic.md, src/components/rating/usage/Basic.md
This PR will remove deprecated properties from usage files in `rating` & `date-picker` components.
=> docs(rating,input-date-picker): remove deprecated properties from usage files

src/components/tabs/tabs.tsx
=> docs(tabs): Update tab slot.

.vscode/settings.json, stencil.config.ts
Adds VSCode completion and hover functionality for our components. Our users can enable it as well by adding this to their project:
```jsonc
// .vscode/settings.json
"html.customData": [
"./node_modules/@esri/calcite-components/dist/extras/vscode-data.json"
]
```
I don't even use VSCode, but happy holidays! 🎅 (Don't expect any more gifts)
- https://stenciljs.com/docs/docs-vscode
- https://github.com/microsoft/vscode-custom-data
=> build(vscode): add completion and hover support

CHANGELOG.md, src/components/tab-nav/tab-nav.tsx, src/components/tab-title/tab-title.tsx
feat(tab-nav): Add `selectedTitle` property. #6148
=> feat(tab-nav): Add `selectedTitle` property

src/components/modal/modal.tsx
Extracts only valid kind values from the interface.
=> chore(modal): Remove invalid kind values

.github/workflows/need-info-verify.yml, .github/workflows/pr-milestone.yml, .github/workflows/pr-semantic.yml
**Related Issue:** #5478
Continue working through updating the actions due to a deprecation, more info linked above. This leaves two unmaintained actions left that I'll figure out after v1
=> ci(actions): update additional actions using the deprecated node runner

.eslintrc.json, src/components/tree/tree.e2e.ts, src/demos/_assets/demo-dom-swapper.ts, src/demos/_assets/demo-form.ts, src/demos/_assets/demo-spacer.ts, src/demos/_assets/demo-template.ts, src/demos/_assets/head.ts, src/utils/form.spec.ts, tsconfig-eslint.json
Fixes a TS/ESLint error preventing @macandcheese from committing.
Also fixes a variety of type errors, mostly by adding null checks
=> ci: fix ts/eslint errors in demos

src/components/list-item/list-item.scss
**Related Issue:** #6123
Add pointer cursor on hover
=> fix(list-item): use pointer cursor when selection mode is none

src/components/segmented-control-item/segmented-control-item.tsx, src/components/segmented-control/segmented-control.e2e.ts, src/components/segmented-control/segmented-control.tsx, src/demos/button.html
BREAKING CHANGE:
- Updates `segmented-control` event to `calciteSegmentedControlChange`
=> refactor(segmented-control)!: Update event name

CHANGELOG.md
Modify the changelog indentation for readability with the unreleased breaking changes.
=> docs(changelog): modify indentation levels

CHANGELOG.md
Modify the changelogs final breaking changes indentation level for communication across teams.
=> docs(changelog): modify breaking changes indentation level

CHANGELOG.md
Prep for release on breaking changes, includes:
- Indentation and spacing fixes
- Reorganizes the breaking change list to be alphabetical
=> docs(changelog): reorganize and set indentation

src/components/tip/tip.scss, src/components/tip/tip.stories.ts, src/components/tip/tip.tsx, src/demos/tip-manager.html
BREAKING CHANGE : Rename `dismissed` prop to `closed.
=> refactor(tip)!: rename `dismissed` to `closed`

CHANGELOG.md
Updates the changelog organization (alphabetical order) and updates the indentation throughout. 🧹
=> docs(changelog): organize and indent breaking changes

src/components/combobox-item-group/combobox-item-group.scss, src/components/combobox-item/combobox-item.scss, src/components/combobox-item/combobox-item.tsx, src/components/combobox-item/resources.ts, src/components/combobox/combobox.stories.ts, src/components/combobox/utils.ts
**Related Issue:** #6287 
This PR will add selector indicator for `combobox-items` with icon.
=> fix(combobox-item):  adds selector indicator for item's with icon.

LICENSE.md, readme.md
Update CC copyright year to 2️⃣ 0️⃣ 2️⃣ 3️⃣ 🎉
=> docs: update license year

CONTRIBUTING.md
Added a couple sentences to the Contributing documentation about using Windows. I think making sure normal development works on Windows but using unix for maintainer-only workflows is a fair balance. But we should at least document it and provide recommendations
=> docs(contributing): mention windows environment considerations

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
Updates the list of Esri teams to match the data gathered by Yelena
=> ci: update esri team names

src/components/stepper-item/stepper-item.scss, src/components/stepper-item/stepper-item.tsx, src/components/stepper/stepper.stories.ts
**Related Issue:** #5227 
This PR will add bottom margin for text node in vertical layout.
=> fix(stepper): add margin bottom for text in vertical layout

CHANGELOG.md
Removes the feat update, which was removed prior to the upcoming 1.0.4 release.
=> docs(changelog): remove reverted feature

src/components/date-picker/date-picker.e2e.ts
=> chore: drop unused import

.github/workflows/sync_to_airtable.yml, src/components/popover/popover.e2e.ts
Allows faster, less expensive, and finer grained control of passing new or updated issues to Airtable
=> ci: Create sync_to_airtable.yml

src/components/modal/modal.e2e.ts, src/tests/utils.ts
Restores applicable tests fixed in 764609de7b8c96aa331e364ca790eefdb44dd1ab.
=> test(modal): restore fixed E2E tests

src/components/handle/assets/handle/t9n/messages.json, src/components/handle/assets/handle/t9n/messages_en.json, t9nmanifest.txt
**Related Issue:** #6248 
This PR will add message bundles required for translation build.
=> chore(handle): add message bundles for translation.

.lintstagedrc.json
Restores TS(X) file linting on commit.
=> chore(linting): restore pattern to lint TS and TSX files

src/components/action-pad/action-pad.stories.ts, src/components/card/card.stories.ts, src/components/checkbox/checkbox.stories.ts, src/components/flow-item/flow-item.e2e.ts, src/components/modal/modal.stories.ts, src/components/tabs/tabs.stories.ts
These came up from a different branch and prevented committing until fixed. Submitting separately to keep other PRs clean.
=> chore(linting): fix no-unused-var errors

.github/workflows/sync_to_airtable.yml
Tested in calcite-design-tokens. This commit removes the concurrency check that was causing annoying failure emails to be sent out. It also simplifies the updates being sent out, speeding up the workflow.
**Related Issue:** #6510
=> ci(sync_to_airtable): #6510 update workflow

.gitignore
**Related Issue:** #6491
Maintaining my sanity one gitignore at a time
=> chore: gitignore Dockerfile

.eslintrc.json, .github/workflows/chromatic.yml, .github/workflows/deploy-next.yml, .github/workflows/pr-e2e.yml, .github/workflows/update-browserslist-db.yml, .github/workflows/update-doc.yml, CONTRIBUTING.md, package-lock.json, package.json, src/utils/form.tsx
Updates dependencies that required `--legacy-peer-deps` for initial installs.
=> build: fix peer dependency resolution error

src/components/pagination/pagination.e2e.ts, src/components/pagination/pagination.tsx
**Related Issue:** #5590
Add `aria-current` to provide state information.
=> fix(pagination): add current page information for screen readers

src/components/date-picker-month/date-picker-month.scss, src/components/date-picker-month/date-picker-month.tsx
=> chore: fix CSS class typo

src/components/date-picker/date-picker.stories.ts
Sets fixed date on screenshot test that would show a diff every month.
=> test(date-picker): stabilize screenshot test

conventions/Internationalization.md
=> docs(conventions): update t9n conventions

src/components/input-message/input-message.tsx, src/components/input-number/input-number.tsx, src/components/input-text/input-text.tsx, src/components/input/input.tsx, src/demos/_assets/locales.ts, src/demos/input-time-picker.html
=> chore: fix linting errors

src/components/segmented-control/segmented-control.stories.ts
=> chore: fix missed renamed import

src/components/combobox-item-group/combobox-item-group.scss, src/components/combobox-item-group/combobox-item-group.tsx, src/components/combobox/combobox.stories.ts, src/components/combobox/utils.ts
**Related Issue:** #6384
Fix css for nesting group combobox items.
=> fix(combobox): Visually nest group items properly

src/tests/commonTests.ts
=> refactor: DRY up form-associated tests

CHANGELOG.md
Format the changelog to reflect the de-AT locale feature.
=> docs(changelog): format locale feature

src/demos/_assets/locales.ts, src/demos/date-picker.html
* drops unsupported locales from demo locales module
* updates demo page to use demo locales module vs hardcoding them
=> refactor: tidy up date-picker demo page

src/demos/_assets/demo-template.css, src/demos/_assets/demo-template.html, src/demos/_assets/demo-template.ts
Also increased header z-index to make sure its on top.
=> chore: Adds ability to remove demo page header via a close button.

src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/input-date-picker/input-date-picker.tsx
=> refactor(input-date-picker, date-picker-month-header): remove unused state prop

src/components/input-time-picker/assets/input-time-picker/t9n/messages.json, src/components/input-time-picker/assets/input-time-picker/t9n/messages_ar.json, src/components/input-time-picker/assets/input-time-picker/t9n/messages_en.json, src/components/input-time-picker/assets/input-time-picker/t9n/messages_fr.json, src/components/input-time-picker/assets/input-time-picker/t9n/messages_th.json, t9nmanifest.txt
**Related Issue:** #6835
Adds strings for translation process. 
**Note**: this also includes placeholders for E2E tests
=> chore(input-time-picker): add strings for translation

src/components/date-picker-day/date-picker-day.scss, src/components/date-picker-day/date-picker-day.tsx, src/components/date-picker-month/date-picker-month.tsx, src/components/date-picker/date-picker.stories.ts
This fixes a visual regression introduced by https://github.com/Esri/calcite-components/pull/6715.
=> fix(date-picker): fix range highlight style regression

src/components/list-item/list-item.tsx, src/components/list/list.e2e.ts, src/components/list/list.tsx, src/demos/list.html
**Related Issue:** #6382 
Adds `single-persist` mode to the List component.
=> feat(list): Add `single-persist` selection mode

src/components/shell-center-row/shell-center-row.tsx, src/components/shell/shell.stories.ts
**Related Issue:** Fix for #6890 
I missed this during review, it should only be applying this to Shell Panel. Adds test only Story to capture this state.
=> fix(shell-center-row): Correctly do not set Action Bar layout

package-lock.json, package.json
Bump floating-ui from 1.2.1  to 1.2.7
=> build(deps): Bump floating-ui from 1.2.1  to 1.2.7

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
Adds ArcGIS Knowledge team label for issue templates.
=> ci: add ArcGIS Knowledge team label

src/utils/dom.ts
chore: update doc for internal DOM utilities
=> chore: update doc for internal DOM utilities

src/components/color-picker/color-picker.e2e.ts
=> test(color-picker): split up some alpha tests to prevent timeouts

src/components/tooltip/tooltip.e2e.ts
=> test(tooltip): stabilize tests

src/components/menu-item/assets/menu-item/t9n/messages.json, src/components/menu-item/assets/menu-item/t9n/messages_en.json, t9nmanifest.txt
**Related Issue:** #6531 
This will add base message bundles to enable translations build process.
=> chore(menu-item): adds base message bundles.

src/components/navigation/navigation.scss, src/components/navigation/navigation.stories.ts, src/components/navigation/navigation.tsx, src/components/navigation/resources.ts, src/components/navigation/usage/Basic.md, src/demos/menu.html, src/demos/navigation.html
=> refactor(navigation): allow nesting secondary and tertiary navigation slots.

src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx, src/components/combobox/resources.ts
=> refactor(combobox, combobox-item): tidy up CSS object usage

CHANGELOG.md, src/components/popover/PopoverManager.ts
Reverts Esri/calcite-components#6977
=> fix(popover): change event listener to 'pointerup'

src/components/chip/chip.tsx, src/components/fab/fab.e2e.ts, src/components/inline-editable/inline-editable.e2e.ts, src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input/input.tsx, src/components/list-item-group/list-item-group.e2e.ts, src/components/stack/stack.e2e.ts, src/components/tree-item/tree-item.tsx
=> chore: tidy up imports

src/utils/locale.spec.ts
=> test(locale): add `getSupportedLocale` test coverage

src/components/button/button.e2e.ts, src/components/checkbox/checkbox.e2e.ts, src/components/combobox/combobox.e2e.ts, src/components/inline-editable/inline-editable.e2e.ts, src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-number/input-number.e2e.ts, src/components/input-text/input-text.e2e.ts, src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input/input.e2e.ts, src/components/radio-button/radio-button.e2e.ts, src/components/rating/rating.e2e.ts, src/components/segmented-control/segmented-control.e2e.ts, src/components/select/select.e2e.ts, src/components/slider/slider.e2e.ts, src/components/switch/switch.e2e.ts, src/components/text-area/text-area.e2e.ts, src/tests/commonTests.ts
Refactor `labelable` test helper to help mitigate timeouts.
The updated doc reflects how to use the helpers in E2E tests.
=> test: set up `labelable` helper to run a test per use case

src/components/modal/modal.tsx
=> chore: fix event handler casing

package-lock.json
**Related Issue:** #7128
Updates `package-lock.json`. The PR linked above was out of sync with `master` and a few deps were bumped this morning.
=> build(deps): update package-lock

packages/calcite-components/CHANGELOG.md
Updates commit message in changelog cc @benelan
=> docs(changelog): Update commit message for #7160

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
**Related Issue:** #7268
test(input-number, input-time-picker): Skip unstable tests
=> test(input-number, input-time-picker): Skip unstable tests

packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
**Related Issue:** #7268
test(input-time-picker): Skip another unstable test. #7268
=> test(input-time-picker): Skip another unstable test

packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, packages/calcite-components/src/utils/locale.ts
=> refactor: rename supported locale type

packages/calcite-components/src/components/combobox/combobox.tsx
=> refactor(combobox): fix method name casing

packages/calcite-components/src/components/chip/chip.tsx
=> fix(chip): disconnect mutation observer when component is disconnected from the DOM

packages/calcite-components/CHANGELOG.md
Updates the `1.5.0` changelog to provide more context for the two `text-area` enhancements.
=> docs(changelog): modify changelog for text-area description context

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
**Related Issue:** #7450
test(input-time-zone): Skip unstable test.
=> test(input-time-zone): Skip unstable test.

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/refactor.yml, .github/workflows/deploy-latest.yml, .husky/pre-push, packages/calcite-components/src/tests/utils.ts, packages/calcite-components/support/stencilDoubleBuildTypesWorkaround.sh, packages/eslint-plugin-calcite-components/rollup.config.ts
Missed a few instances because I forgot to use ripgrep's `--hidden` flag the first time around :sweat_smile:
=> chore: update additional instances of old branch and repo names

packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts
Updates story parameters so the time zone options are captured.
=> test(input-time-zone): ensure time zone options are captured in the screenshot

packages/calcite-components/src/components/accordion-item/accordion-item.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/pull/7466#discussion_r1286234883
✨📚✨
=> chore(accordion-item): add more info about accordion item sync

packages/calcite-components/src/components/modal/usage/Open.md
- update usage file with correct prop
=> docs(modal): update usage file with correct prop

packages/calcite-components/src/components/scrim/scrim.e2e.ts, packages/calcite-components/src/components/scrim/scrim.stories.ts, packages/calcite-components/src/components/scrim/scrim.tsx
**Related Issue:** #7032
- Use new dom utility to test for content
- Add stories
- Update tests
=> fix(scrim): render text content inside scrim

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/tests/commonTests.ts
=> test(input-time-zone): unskip test

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
=> test: skip unstable tests

packages/calcite-components/src/components/modal/modal.stories.ts, packages/calcite-components/src/components/shell/shell.stories.ts
Adds a delay to screenshot tests that have been recently differing.
=> test(modal, shell): add delay to recent unstable stories

packages/calcite-components/src/components/combobox/combobox.scss
=> fix(combobox): update combobox height to follow design spec

packages/calcite-components/src/components/table/usage/Basic.md
Fix for copy-paste in usage file.
=> docs(table): Update usage

packages/calcite-components/src/demos/flow.html
=> chore(demo): fix missed rename for custom-item-selectors attr

packages/calcite-components/src/components/pick-list-item/readme.md
=> docs(pick-list-item): drop reference to removed prop

packages/calcite-components/src/components/table/table.tsx
Improve slot documentation for Table component cc @geospatialem
=> docs(table): Improve slot documentation

packages/calcite-components/src/components/combobox/combobox.stories.ts
Add coverage for items picking up their parent's scale.
=> test(combobox): add open in all scales screenshot test

packages/calcite-components/src/utils/locale.ts
=> chore(locale): add extra info to default numbering system export

packages/calcite-components/src/components/sheet/sheet.e2e.ts, packages/calcite-components/src/components/sheet/sheet.tsx
**Related Issue:** #7681
- Depends on #7680
- Update sheet to emit correctly on scrim click
- Add test
- @jcfranco for risk consideration.
=> fix(sheet): calciteSheetClose should emit on scrim click

packages/calcite-components/src/components/action-group/action-group.scss, packages/calcite-components/src/components/action-group/action-group.stories.ts
**Related Issue:** #7687
- Add flex grow to container
=> fix(action-group): Honor flex-grow on slotted actions

packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.scss
=> chore: remove commented-out Tailwind directive

support/dictionaries/dict-calcite-design-system.txt
chore: add "xsmall" to custom spelling dictionary
=> chore: add "xsmall" to custom spelling dictionary

packages/calcite-components/src/components/alert/alert.e2e.ts
**Related Issue:** #7748
skip unstable test
=> test(alert): skip unstable accessible test

packages/calcite-components/.storybook/utils.tsx, packages/calcite-components/src/utils/responsive.ts
Adds helper to ease adding responsive layout screenshot tests.
=> chore: add util to generate breakpoint stories

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/refactor.yml
Adds issue template checkbox entry for `@esri/eslint-plugin-calcite-components` package.
=> chore: add @esri/eslint-plugin-calcite-components to issue templates

packages/calcite-components/conventions/README.md, packages/calcite-components/src/components/action-bar/action-bar.tsx, packages/calcite-components/src/components/table/readme.md, packages/calcite-components/src/components/tree-item/tree-item.tsx
**Related Issue:** #7621
Run `npm run lint` to prevent unrelated changes in the PR linked above.
=> style: run lint script

packages/calcite-components/src/components/modal/modal.stories.ts, packages/calcite-components/src/components/sheet/sheet.stories.ts, packages/calcite-components/src/components/shell/shell.stories.ts, packages/calcite-components/src/components/stepper/stepper.stories.ts, packages/calcite-components/src/components/tabs/tabs.stories.ts
test: increase screenshot test delays.
=> test: increase screenshot test delays.

packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts, packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx
**Related Issue:** #7707
- Correctly observes mutation changes and updates selectionMode on slotted children
- Adds test
=> fix(dropdown-group): set selectionMode on slotted dropdown-item children

packages/calcite-components/src/components/tab-nav/assets/tab-nav/t9n/messages.json, packages/calcite-components/src/components/tab-nav/assets/tab-nav/t9n/messages_en.json, t9nmanifest.txt
**Related Issue:** #6689
This will add base message bundles to enable the translations build process.
=> chore(tab-nav): adds base message bundles

packages/calcite-components/src/components/stepper-item/assets/stepper-item/t9n/messages.json, packages/calcite-components/src/components/stepper-item/assets/stepper-item/t9n/messages_en.json
**Related Issue:** #6694 
Adds messages to support built-in translations for responsive layout.
=> chore(stepper): add message bundles for responsive layout

packages/calcite-design-tokens/src/core.json
**Related Issue:** #7856
generates a new SCSS variable `$breakpoint-width-xxs: 320px;`
=> feat: add xxs breakpoint to tokens

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/refactor.yml
**Related Issue:** #7977
Adds issue template checkbox entry for `@esri/calcite-design-tokens` package.
=> chore: add @esri/calcite-design-tokens to issue templates

packages/calcite-components/src/components/icon/icon.scss, packages/calcite-components/src/components/icon/icon.stories.ts
**Related Issue:** #8006
- Use fixed pixel sizes for icons
=> fix(icon): use pixel sizes for icons

packages/calcite-components/src/components/stepper/stepper.tsx
Disconnects observer when component is disconnected from the DOM.
=> refactor(stepper): disconnects observer when component is disconnected

packages/calcite-components/src/components/block/block.e2e.ts, packages/calcite-components/src/components/block/block.scss, packages/calcite-components/src/components/block/block.stories.ts, packages/calcite-components/src/components/block/block.tsx
**Related Issue:** #4935 
Toggle icon is now always visible.
=> feat(block): ensure chevron is always displayed

packages/calcite-components/src/components/button/button.tsx, packages/calcite-components/src/components/scrim/scrim.tsx
=> refactor(button, scrim): ensure ref is set last so attrs/props are in sync

packages/calcite-components/src/components/block/block.stories.ts
=> test(block): Add screenshot test for long Block and Block Section props

packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json, packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages_en.json
=> fix(input-time-zone): fix Indian/Christmas time zone translation

packages/calcite-components/src/components/text-area/text-area.stories.ts
=> test(text-area): fix story markup

packages/calcite-components/src/tests/commonTests.ts
=> test(openClose): add missing awaits to openClose tests

packages/calcite-components-react/LICENSE.md, packages/calcite-components-react/README.md, packages/calcite-components/src/components/functional/FloatingArrow.tsx, packages/calcite-components/src/components/value-list-item/value-list-item.tsx, packages/eslint-plugin-calcite-components/LICENSE.md, packages/eslint-plugin-calcite-components/jest.config.ts, packages/eslint-plugin-calcite-components/src/configs/index.ts, packages/eslint-plugin-calcite-components/src/rules/ban-events.ts, packages/eslint-plugin-calcite-components/src/rules/ban-props-on-host.ts, packages/eslint-plugin-calcite-components/src/rules/require-event-emitter-type.ts, packages/eslint-plugin-calcite-components/src/rules/strict-boolean-attributes.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/ban-events/ban-events.spec.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/ban-props-on-host/ban-props-on-host.spec.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/require-event-emitter-type/require-event-emitter-type.spec.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/strict-boolean-attributes/strict-boolean-attributes.spec.ts, readme.md
Extracts linting fixes from https://github.com/Esri/calcite-design-system/pull/6958/files.
=> style: fix linting violations

packages/calcite-components/stencil.config.ts
=> build: use `enableImportInjection` extras config option instead of the deprecated `experimentalImportInjection`

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/refactor.yml
**Related Issue:** #7860
Adds the angular package to our issue templates for: a11y, bugs, enhancements, and refactors.
=> chore: add angular package to issue templates

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #7912
Fixes linting errors introduced by the PR linked above.
=> refactor(combobox): fix linting errors

package-lock.json, packages/calcite-components/package.json, packages/eslint-plugin-calcite-components/package.json
**Related Issue:** #8237
One more package needs downgrading
=> chore: downgrade eslint plugin after reverting breaking change

packages/calcite-components/src/components/button/button.e2e.ts, packages/calcite-components/src/components/button/button.tsx
**Related Issue:** #8140
- Sets aria-disabled instead of disabled on internal anchor element
- Adds test
=> fix(button): Sets aria-disabled instead of disabled on internal anchor element

packages/calcite-components/src/components/link/usage/Basic.md, packages/calcite-components/src/components/loader/usage/Compact.md, packages/calcite-components/src/components/modal/usage/Basic.md, packages/calcite-components/src/components/notice/usage/Basic.md, packages/calcite-components/src/components/panel/usage/With-action-bar.md, packages/calcite-components/src/components/panel/usage/With-fab.md, packages/calcite-components/src/components/select/usage/Basic.md, packages/calcite-components/src/components/select/usage/Content.md, packages/calcite-components/src/components/select/usage/Disable.md, packages/calcite-components/src/components/select/usage/Grouped.md, packages/calcite-components/src/components/select/usage/Side-by-side.md, packages/calcite-components/src/components/select/usage/Value.md
**Related Issue:** #6374 
Updates component usage examples for components listed in title
=> docs(link, loader, modal, notice, panel, select): update usage examples

packages/calcite-components/src/components/handle/handle.e2e.ts, packages/calcite-components/src/components/handle/handle.scss, packages/calcite-components/src/components/handle/handle.stories.ts, packages/calcite-components/src/components/handle/handle.tsx
**Related Issue:** #8282
- Adds disabled property to handle component
- Use interactive component on handle
- Adds e2e test
- Adds story screenshot test
=> feat(handle): Add disabled property

packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/input.tsx
Update `alignment` property type to use `Alignment` interface.
=> refactor(input,input-text,input-number): updates `alignmen`t property type

packages/calcite-components/src/utils/sortableComponent.ts
- Adds additional notes for implementing the SortableComponentItem interface.
=> chore: Add additional notes to sortableComponent.

packages/calcite-components/src/demos/dropdown.html
=> chore(dropdown): update demo page to use selected vs active (removed)

packages/calcite-components/src/components/tab-nav/tab-nav.e2e.ts
Waits for changes after interacting with the tab title to account for some internal eventing going on.
=> test(tab-nav): stabilize test

packages/calcite-components/src/demos/dropdown.html
=> chore(dropdown): update test page to set selection mode on groups

packages/calcite-components/src/components/list/usage/Advanced.md, packages/calcite-components/src/components/list/usage/DragEnabledNested.md, packages/calcite-components/src/components/list/usage/Nested.md
- Update list usage examples to include a nested list
- Remove drag icon from usage examples.
=> docs(list): update usage examples.

packages/calcite-components/src/demos/list.html
=> chore(list): fix demo code

packages/calcite-components/conventions/Accessibility/AccessibilityDeveloper.md, packages/calcite-components/src/components/dropdown/dropdown.stories.ts, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/tip/readme.md, packages/calcite-components/src/components/tree-item/tree-item.e2e.ts, packages/calcite-components/src/components/tree/tree.e2e.ts
chore: update links to use esri.com, update placeholder image reference.
=> chore: update links to use esri.com, update placeholder image reference.

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #8468
- Update selectedItems to not consider filteredItems
- Refactor filteredItems/openItems/focusableItems internally
- Add test
=> fix(list): correct selectedItems value when list is filtered

packages/calcite-components/src/components/list-item/list-item.tsx
- Refactor to remove unnecessary code
=> refactor(list-item): Remove unnecessary code for rendering open caret

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/combobox/interfaces.ts
=> refactor(combobox): remove unused interface

packages/calcite-components/src/demos/inline-editable.html
=> chore(inline-editable): add missing scale to slotted inputs in demo page

packages/calcite-components/src/components/radio-button/radio-button.tsx
The query works properly in its current state, so this is mainly for cleanup. ✨🧹✨
=> refactor(radio-button): fix query selector

packages/calcite-components/src/components/list-item/assets/list-item/t9n/messages.json, packages/calcite-components/src/components/list-item/assets/list-item/t9n/messages_en.json, packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #8613
- Adds tooltip for expand/collapse button.
=> feat(list-item): Add tooltip for expanding and collapsing

package-lock.json, packages/calcite-components/package.json
Removing `form-request-submit-polyfill` [again](https://github.com/Esri/calcite-design-system/pull/8155) as it snuck back via https://github.com/Esri/calcite-design-system/pull/8108.
=> chore(deps): drop unused `form-request-submit-polyfill`

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list/list.stories.ts
**Related Issue:** #8684
- Updates slotted styling for list elements.
- Adds screenshot test
=> fix(list-item): Fix slotted list border styling.

packages/calcite-components/src/components/scrim/scrim.scss, packages/calcite-components/src/components/scrim/scrim.stories.ts, packages/calcite-components/src/demos/scrim.html
`--calcite-scrim-background-color`: Specifies the background color of the component.
Adds a deprecated tag and fallback for the previous `--calcite-scrim-background` css property.
=> feat(scrim): Add component tokens

packages/calcite-components/.storybook/utils.tsx
=> chore: improve doc for createBreakpointStories helper

packages/calcite-components/src/components/input/common/input.spec.ts
=> refactor(input): tidy up input spec test

package-lock.json, packages/calcite-components/package.json
=> build(deps): update dependency @esri/calcite-ui-icons to v3.26.4

packages/calcite-components/src/components/chip/chip.scss
Updates the documentation for `--calcite-chip-shadow` css prop.
=> feat(chip): Update token documentation

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/fab/fab.scss
Refactors the Button and FAB components.
reduce component tokens
map FAB tokens to Button tokens
FAB
@prop --calcite-fab-background-color: defines the background color of the component.
@prop --calcite-fab-border-color: defines the border color of the component.
@prop --calcite-fab-corner-radius: defines the corner-radius of the component.
@prop --calcite-fab-icon-color: defines the icon color of the component.
@prop --calcite-fab-shadow: defines the shadow of the component.
Button
@prop --calcite-button-background-color: Specifies the background color of the component.
@prop --calcite-button-text-color: Specifies the text color of the component.
@prop --calcite-button-icon-color: Specifies the color of the component's start position icon.
@prop …
=> refactor(fab,button): update component tokens

packages/calcite-components/src/components/stepper-item/stepper-item.tsx, packages/calcite-components/src/components/stepper/stepper.tsx
Restores trailingComma removed in #8758
=> style(stepper,stepper-item): lint code

packages/calcite-components/src/components/graph/graph.scss
```scss
* --calcite-graph-background-color
* --calcite-graph-highlight-color
```
=> feat(graph): add component tokens

packages/calcite-components/src/components/shell-center-row/shell-center-row.e2e.ts
previous test selected the <style> tag
=> test(shell-center-row): fix test

packages/calcite-components/calcite-preset.ts
**Related Issue:** #8807
replaced `--calcite--color-brand` with `--calcite-color-brand`
=> fix(preset): calcite—color-brand to calcite-color-brand

packages/calcite-components/src/assets/styles/_floating-ui.scss, packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/dropdown/dropdown.scss, packages/calcite-components/src/components/flow-item/flow-item.scss, packages/calcite-components/src/components/flow/flow.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/panel/panel.scss, packages/calcite-components/src/components/popover/popover.scss, packages/calcite-components/src/components/tooltip/tooltip.scss
Update installed tokens for the components above to use fallback method.
=> refactor(flow, flow-item, panel, popover, tooltip): Use fallback method for css vars

packages/calcite-components/src/components/chip/chip.tsx
Removes now-deprecated coding patterns from Chip and replaces the functionality following current practices.
=> refactor(chip): Remove deprecated component patterns

packages/calcite-components/src/components/rating/rating.scss
=> refactor(rating): Update token pattern

packages/calcite-components/src/components/card-group/card-group.scss
=> refactor(card-group): Update token pattern

packages/calcite-components/src/components/pagination/pagination.scss
=> refactor(pagination): Update token pattern

packages/calcite-components/src/components/card/card.scss
=> refactor(card): Update token pattern

packages/calcite-components/src/components/action/resources.ts
=> fix(action): restore missing CSS lookup props

packages/calcite-components/src/components/action/action.scss
=> fix(action): add indicator fallback color

packages/calcite-components/src/components/scrim/scrim.scss
=> refactor(scrim): Update token pattern

packages/calcite-components/src/components/graph/graph.scss
=> refactor(graph): rename to use accent vs highlight

packages/calcite-components/src/components/meter/meter.scss
=> refactor(meter): Update token pattern

packages/calcite-components/src/components/chip/chip.scss
=> refactor(chip): Update token pattern

packages/calcite-components/src/components/tip/tip.scss, packages/calcite-components/src/components/tip/tip.stories.ts
Update component token pattern with fallbacks and add a story.
=> refactor(tip): update token pattern

packages/calcite-components/src/components/input/input.scss, packages/calcite-components/src/components/progress/progress.scss, packages/calcite-components/src/components/progress/progress.stories.ts
Update component tokens with fallbacks and add stories.
=> refactor(progress): update token pattern

packages/calcite-components/src/components/action-menu/action-menu.scss, packages/calcite-components/src/components/popover/popover.scss
Add mapped component tokens from parent to sub-component.
=> refactor(popover): update token pattern

packages/calcite-components/src/components/navigation-user/navigation-user.scss
Reverts [635e116](https://github.com/Esri/calcite-design-system/pull/8594/commits/635e116070de05ba92e4d6e0afb72bd70a845132) from `epic/7180-component-tokens`
=> revert: feat(navigation-user): add stateful component tokens

packages/calcite-components/src/components/select/select.scss
=> refactor(select): drop non-subcomponent-related state props

packages/calcite-components/src/components/tile/tile.scss
=> refactor(tile): update component CSS props to follow fallback pattern

package-lock.json, packages/calcite-components/package.json
=> build(deps): update @esri/calcite-ui-icons to v3.26.8

package-lock.json, package.json
=> chore(deps): bump Chromatic to v11.3.0

.github/scripts/addCalcitePackageLabel.js, .github/scripts/addEsriProductLabel.js, .github/scripts/addPriorityLabel.js, .github/scripts/assignForVerification.js, .github/scripts/notifyWhenReadyForDev.js, .github/scripts/notifyWhenSpikeComplete.js, .github/scripts/support/utils.js
=> chore(actions): fix label util not passing proper name argument

packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.scss, packages/calcite-components/src/components/date-picker/date-picker.e2e.ts, packages/calcite-components/src/components/date-picker/date-picker.scss
Update token names and add tests
=> fix(date-picker): update names and E2E tests

package-lock.json, package.json
✨📦➡️🤓✨
This was unintentionally added as a dependency in #9030.
=> build(deps): move `@storybook/test` to `devDependencies`

packages/calcite-components/src/components/filter/filter.e2e.ts
=> test(filter): add e2e tests

packages/calcite-components/src/components/flow-item/flow-item.e2e.ts
=> test(flow-item): add theme E2E tests

.github/scripts/support/utils.js
Fixes arguments passed to removeLabel issue API.
=> chore(actions): fix removeLabel util

packages/calcite-components/src/components/slider/slider.stories.ts, packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #1631
This ensures ranged sliders place the fill and style ticks within the range.
=> fix(slider): fix fill placement and tick styling when ranged

.github/ISSUE_TEMPLATE/test.yml, .github/scripts/addPriorityLabel.js
**Related Issue:** #9191 
Enables a priority option in the test issue template, which will add a priority label upon creation.
=> ci: adds support to test issue template priority status

packages/calcite-components/src/components/input/common/_mixins.scss, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.scss
Fix calcite-input mixin and base component. Adds docs for calcite-input
=> fix(input): update tokens and E2E tests

packages/calcite-components/.eslintrc.cjs, packages/calcite-components/src/components/block-section/block-section.tsx, packages/calcite-components/src/components/block/block.tsx, packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/inline-editable/inline-editable.tsx, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/rating/rating.tsx, packages/calcite-components/src/components/segmented-control/segmented-control.tsx, packages/calcite-components/src/components/shell/shell.tsx, packages/calcite-components/src/components/text-area/text-area.tsx, packages/calcite-components/src/components/time-picker/time-picker.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.tsx, packages/calcite-components/src/utils/focusTrapComponent.spec.ts, packages/calcite-components/src/utils/number.ts, packages/calcite-components/src/utils/openCloseComponent.ts
=> chore(linting): enable eslint recommended ruleset

packages/calcite-components/conventions/README.md
**Related Issue:** #9117
Docs CSS lookup pattern used across components and also includes dynamic class-generation update.
=> docs(conventions): doc CSS lookup pattern

package-lock.json, packages/calcite-components/package.json
Updates the `@esri/calcite-ui-icons` dependency to `3.28.2`.
=> build(deps): update dependency @esri/calcite-ui-icons to v3.28.2

packages/calcite-components/src/components/tree/tree.stories.ts
=> chore(tree): fix multiple selection-mode values set in slotted dropdown-groups

packages/calcite-components/src/components/navigation-logo/navigation-logo.e2e.ts
Add token test for `navigation-logo` component.
=> test(navigation-logo): add token theming tests

packages/calcite-components/src/components/pagination/pagination.e2e.ts
Adds token theming test for `pagination` component.
=> test(pagination): add token theming tests

packages/calcite-components/src/components/navigation-user/navigation-user.e2e.ts
Add token theming tests for `navigation-user` component.
=> test(navigation-user): add token theming tests

packages/calcite-components/src/components/navigation/navigation.e2e.ts, packages/calcite-components/src/components/navigation/navigation.scss
Add token theming tests for `navigation` component.
=> test(navigation): add token theming tests

packages/calcite-components/src/components/stepper-item/stepper-item.e2e.ts, packages/calcite-components/src/components/stepper-item/stepper-item.scss
Add token theming tests for `stepper-item`.
=> test(stepper-item): add token theming tests

packages/calcite-components/src/components/stepper/resources.ts, packages/calcite-components/src/components/stepper/stepper.e2e.ts
Add token theming tests for `stepper`.
=> test(stepper): add token theming tests

packages/calcite-components/src/components/action-group/action-group.e2e.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.e2e.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.scss, packages/calcite-components/src/components/handle/handle.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.scss
=> test(action-group, dropdown-item, handle, input-time-picker): fix themed test failures

packages/calcite-components/src/components/action/action.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.scss, packages/calcite-components/src/components/time-picker/time-picker.e2e.ts, packages/calcite-components/src/components/time-picker/time-picker.scss
Add token theming tests for `time-picker`.
=> test(time-picker, action, input-time-picker): add token theming tests and fix action, input-time-picker token theming tests

packages/calcite-components/src/components/color-picker/color-picker.tsx
=> refactor(color-picker): tidy up slider width logic

packages/calcite-components/src/components/block-section/block-section.scss
**Related Issue:** #6905
Adjust text hierarchy.
=> fix(block-section): adjust text hierarchy

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/progress/progress.e2e.ts, packages/calcite-components/src/components/progress/progress.tsx, packages/calcite-components/src/components/progress/resources.ts
=> test(progress): add component token E2E tests

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/chip/chip.e2e.ts, packages/calcite-components/src/components/chip/chip.scss
=> test(chip): add component token E2E tests

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/checkbox/checkbox.e2e.ts, packages/calcite-components/src/components/checkbox/checkbox.scss
=> test(checkbox): add component token E2E tests

packages/calcite-components/src/components/avatar/avatar.e2e.ts
=> test(avatar): add component token E2E tests

packages/calcite-components/src/components/segmented-control-item/segmented-control-item.e2e.ts, packages/calcite-components/src/components/segmented-control-item/segmented-control-item.scss, packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
=> test(segmented-control, segmented-control-item): add component token E2E tests

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/graph/graph.e2e.ts, packages/calcite-components/src/components/graph/graph.scss
=> test(graph): add component token E2E tests

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/switch/switch.e2e.ts, packages/calcite-components/src/components/switch/switch.scss
=> test(switch): add component token E2E tests

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/label/label.e2e.ts
=> test(label): add component token E2E tests

packages/calcite-components/src/components/card-group/card-group.e2e.ts, packages/calcite-components/src/components/card-group/card-group.tsx, packages/calcite-components/src/components/card-group/resources.ts, packages/calcite-components/src/components/card/card.e2e.ts, packages/calcite-components/src/components/card/card.scss
=> test(card, card-group): add component token E2E tests

package-lock.json
Resolve `package-lock.json` issue that is causing Chromatic failures on `dev`.
=> ci(chromatic): fix build errors from corrupted package-lock

packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx
The hotfixes for 2.8.5 and 2.8.6 never ended up on `dev` or `main`.
NOTE: this PR needs to be rebase-merged
=> chore: cherry-pick previous hotfixes

.github/workflows/deploy-latest.yml
=> ci(release-please): downgrade to v3

.github/workflows/deploy-latest.yml
Possibly related:
https://github.com/googleapis/release-please-action/issues/840
We are getting the "Not Found" error:
https://github.com/Esri/calcite-design-system/actions/runs/9672053091/job/26683703555#step:2:1719
=> ci(release-please): downgrade to v3.7.6

package-lock.json, packages/calcite-components-angular/projects/component-library/CHANGELOG.md, packages/calcite-components-angular/projects/component-library/package.json, packages/calcite-components-react/CHANGELOG.md, packages/calcite-components-react/package.json, packages/calcite-components/CHANGELOG.md, packages/calcite-components/package.json, packages/calcite-design-tokens/CHANGELOG.md, packages/calcite-design-tokens/package.json, packages/eslint-plugin-calcite-components/CHANGELOG.md, packages/eslint-plugin-calcite-components/package.json
Cherry-pick release commit for `2.10.0`.
=> chore: release main

packages/calcite-components/src/demos/_assets/head.ts
Add theme and spacer helpers to all pages
=> chore: update demo head

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/input-number/input-number.e2e.ts
=> test(action-menu, input-number): skip unstable tests

package.json
Fix a typo in the `cleanup` npm script.
=> chore: fix cleanup npm script

packages/calcite-components/src/components/combobox-item/combobox-item.e2e.ts, packages/calcite-components/src/components/combobox-item/combobox-item.tsx
=> test(combobox-item): add defaults and reflects tests

packages/calcite-components/src/components/value-list-item/value-list-item.tsx
**Related Issue:** #9295 
Add missing deprecation warning.
=> chore(value-list-item): add runtime deprecation warning

packages/calcite-components/src/components/combobox-item/combobox-item.scss
**Related Issue:** #9881
Applies heading color across all states.
=> feat(combobox-item): apply heading color according to updated spec

package.json, packages/calcite-design-tokens/package.json
=> build(deps): bump node version pinned by volta

package-lock.json, package.json
**Related Issue:** #9851
The PR I created for `actions/github-script` was merged.
=> build(deps): update github-script types

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, support/dictionaries/dict-calcite-design-system.txt
Fix a few low hanging fruit ESLint diagnostics.
=> chore(input-date-picker, input-time-picker): fix eslint warnings/hints

.gitignore
=> chore(.gitignore): drop redundant entry

packages/calcite-components/src/components/list-item/list-item.tsx
=> docs(list-item): add list as a type of element allowed in default slot.

packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #9017
Adds search icon to placeholder to provide context.
=> feat(input-time-zone): add search placeholder icon to provide hint

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/button/button.e2e.ts, packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/button/button.tsx
**Related Issue:** #8576
Drop loader fade in/out transition to align with other components that use an internal loader.
=> fix(button): drop loader fade-in/out animation

packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/combobox/resources.ts
**Related Issue:** #9935
This updates the placeholder's icon color to be consistent with other components.
=> fix(combobox): update placeholder-icon color

.github/workflows/chromatic.yml, .github/workflows/pr-semantic.yml
**Related Issue:** #10039
Ensure the `chromatic` and `semantic-pr` PR checks always run when they should.
=> ci: fix chromatic and pr-semantic check trigger events

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
Adds the Application Prototype Lab (APL) to the Esri team dropdown list across issue templates.
=> ci: updates esri team dropdown list

package-lock.json, package.json, packages/calcite-components/package.json
Revert the removal of `cheerio`, I missed its usage in the hidden directory when grepping.
This reverts commit b6baa087f6f6e57e51c667cc23dbb2eda4cbdb39.
=> revert: "build(deps): remove unused cheerio package (#10049)"

packages/calcite-components/src/components/color-picker/color-picker.tsx
=> refactor(color-picker): extract common canvas control pointer down logic

.github/workflows/pr-semantic.yml
The PR check didn't run on Ali's PR for some reason after they merged dev into the branch. This should force the check to refresh, even though the PR title couldn't have been changed.
=> ci(semantic): add synchronize trigger event

packages/calcite-components/stencil.config.ts
=> chore: use short sha-1 format for startup info message

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/dialog/dialog.e2e.ts, packages/calcite-components/src/components/dialog/dialog.stories.ts, packages/calcite-components/src/components/dialog/dialog.tsx
**Related Issue:** #9986
- add `outsideCloseDisabled` property. 
- add tests
=> feat(dialog): add outsideCloseDisabled property

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/dialog/dialog.e2e.ts, packages/calcite-components/src/components/dialog/dialog.stories.ts, packages/calcite-components/src/components/dialog/dialog.tsx
**Related Issue:** #10080
- add `escapeDisabled` property
- update storybook
- add e2e test
=> feat(dialog): add escapeDisabled property

packages/calcite-components/src/demos/dialog.html
=> test(dialog): fix demo page.

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts
=> test(color-picker): fix test covering hue scope keyboard nudging with shift

packages/calcite-components/src/components/alert/alert.e2e.ts
**Related Issue:** #7748
- unskip test
=> test(alert): unskip a11y test

packages/calcite-components/src/components/filter/filter.e2e.ts, packages/calcite-components/src/components/filter/filter.tsx
**Related Issue:** #10136
- fix setFocus method
- update test
=> fix(filter): fix setFocus method

packages/calcite-components/src/components/popover/popover.e2e.ts
=> test(popover): unskip focusable test

packages/calcite-components/src/components/action-group/action-group.stories.ts
Remove dangling HTML snippet found here https://github.com/Esri/calcite-design-system/pull/10058#discussion_r1733253670
=> test(action-group): remove extraneous template

packages/calcite-components/src/components/shell-panel/shell-panel.scss, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** #10176
- set container width/height to 100% (depending on layout)
- add story
=> fix(shell-panel): fill available space

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/checkbox/checkbox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/flow-item/flow-item.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/loader/loader.scss, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/components/panel/panel.e2e.ts, packages/calcite-components/src/components/panel/panel.tsx, packages/calcite-components/src/components/radio-button/radio-button.e2e.ts, packages/calcite-components/src/components/tile-select/tile-select.e2e.ts, packages/calcite-components/src/tests/commonTests/disabled.ts, packages/calcite-components/src/tests/commonTests/interfaces.ts
Cherry-pick the patch commits to `main`. 
> [!IMPORTANT]
> This needs to be rebase-merged
=> chore: cherry-pick patch commits to main

packages/calcite-components/stencil.config.ts
=> chore: use proper short sha-1 format for startup info message

packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
=> test(input-time-picker): skip unstable test.

packages/calcite-components/src/components/shell/shell.scss, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** #10222
-  fix z-index of panels
- add screenshot test
=> fix(shell): fix z-index of shell-panels

packages/calcite-components/src/components/accordion-item/accordion-item.tsx, packages/calcite-components/src/components/accordion/accordion.e2e.ts, packages/calcite-components/src/components/graph/graph.e2e.ts, packages/calcite-components/src/components/pagination/pagination.tsx
A few minor code changes for things I noticed while running the codemod
=> refactor: resolve minor issues

packages/calcite-components/.eslintrc.cjs, packages/calcite-components/src/components/action-group/action-group.tsx, packages/calcite-components/src/components/chip-group/chip-group.tsx, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.tsx, packages/calcite-components/src/components/date-picker/date-picker.e2e.ts, packages/calcite-components/src/components/graph/graph.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/meter/meter.tsx, packages/calcite-components/src/components/select/select.tsx, packages/calcite-components/src/components/slider/slider.stories.ts, packages/calcite-components/src/components/text-area/text-area.tsx, packages/calcite-components/src/components/tile-select/tile-select.tsx, packages/calcite-components/src/components/value-list-item/value-list-item.tsx, packages/calcite-components/src/tests/commonTests/themed.ts, packages/calcite-components/src/tests/utils.ts, packages/calcite-components/src/utils/date.ts, packages/calcite-components/src/utils/dom.ts, packages/calcite-components/src/utils/form.tsx, packages/calcite-design-tokens/.eslintrc.cjs, packages/calcite-design-tokens/support/token-transformer/styleDictionary/formatter/utils/formatExtraOutput.ts
Wires up https://typescript-eslint.io/rules/no-unnecessary-type-assertion/ to improve maintainability/readability.
Thanks for the suggestion, @maxpatiiuk!
=> chore(linting): enable `@typescript-eslint/no-unnecessary-type-assertion` assertion

packages/calcite-components/src/components/action-bar/action-bar.tsx, packages/calcite-components/src/components/action-pad/action-pad.tsx, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/components/tab-title/tab-title.tsx, packages/calcite-components/src/components/time-picker/time-picker.tsx, packages/calcite-components/src/components/tree-item/tree-item.tsx
=> refactor: remove unused class members

packages/calcite-components/src/components/dialog/dialog.e2e.ts, packages/calcite-components/src/components/dialog/dialog.scss, packages/calcite-components/src/components/panel/panel.e2e.ts, packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #10093 
Adds `--calcite-dialog-background-color` to Dialog
Adds `--calcite-panel-background-color` to Panel
Further token work may occur through related issues: #7180, #10380, etc.
=> feat(dialog, panel): Add css properties for background-color

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
Adds `ArcGIS Data Pipelines` to the issue templates Esri team dropdown.
=> chore(issue templates): add arcgis data pipelines to team dropdown

packages/calcite-components/src/components/checkbox/checkbox.tsx, packages/calcite-components/src/components/radio-button/radio-button.tsx
**Related Issue:** #9110
- deprecate guid properties
=> deprecate(checkbox, radio-button): deprecate 'guid' properties

packages/calcite-components/src/components/card-group/card-group.tsx
Extracted typo fix from https://github.com/Esri/calcite-design-system/pull/10443 to keep PR focused.
=> refactor(card-group): fix typo

packages/calcite-components/src/components/accordion-item/accordion-item.scss
=> docs(accordion-item): fix deprecation tag

packages/calcite-components/src/custom-theme/accordion.ts
=> chore: remove commented-out code

packages/calcite-components/src/custom-theme.stories.ts
This should help simplify updating component tokens a bit.
=> refactor: tidy up custom theme story

.husky/pre-push
Resolve an issue reading user input from the husky pre-push hook.
=> ci(husky): fix pre-push tty issue

packages/calcite-ui-icons/docs/keywords.json, packages/calcite-ui-icons/icons/drag-resize-horizontal-16.svg, packages/calcite-ui-icons/icons/drag-resize-horizontal-24.svg, packages/calcite-ui-icons/icons/drag-resize-horizontal-32.svg, packages/calcite-ui-icons/icons/drag-resize-vertical-16.svg, packages/calcite-ui-icons/icons/drag-resize-vertical-24.svg, packages/calcite-ui-icons/icons/drag-resize-vertical-32.svg
**added**
drag-resize-vertical-16
drag-resize-vertical-24
drag-resize-vertical-32
drag-resize-horizontal-16
drag-resize-horizontal-24
drag-resize-horizontal-32
=> feat: add drag resize vertical and drag resize horizontal

packages/calcite-components/src/components/sheet/interfaces.ts, packages/calcite-components/src/components/sheet/resources.ts, packages/calcite-components/src/components/sheet/sheet.e2e.ts, packages/calcite-components/src/components/sheet/sheet.scss, packages/calcite-components/src/components/sheet/sheet.tsx
=> sheet resizable separator role

packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
This should help stabilize some recent failing tests.
=> test(input-time-picker): wait for changes after typing value

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
=> chore(input-time-zone): rename t9n test for consistency

packages/eslint-plugin-calcite-components/docs/ban-events.md
=> docs(ban-events): fix typo

.vscode/settings.json
=> chore: update VSCode settings to ensure TS consistency

packages/calcite-components/src/components/table/table.e2e.ts
=> test(table): improve stability

packages/calcite-components/src/components/date-picker-day/date-picker-day.tsx, packages/calcite-components/src/components/list-item-group/list-item-group.tsx, packages/calcite-components/src/components/list/list.tsx
Add missing `@internal` tags to internal events
=> docs: add missing @internal to private events

examples/components/angular/README.md, examples/components/angular/src/app/app.component.spec.ts, examples/components/angular/src/app/app.component.ts, examples/components/angular/src/main.ts, examples/components/vite/README.md
Clean up the Angular and Vite component integration examples.
=> docs(angular, vite): cleanup setup instructions for component examples

packages/calcite-components/src/utils/dom.spec.ts, packages/calcite-components/src/utils/dom.ts
**Related Issue:** #10472
- enhance utility to support auto mode
- add spec test
=> fix(utils/dom): fix getModeName function to support auto mode

packages/calcite-components/src/components/loader/loader.stories.ts, packages/calcite-components/src/components/tabs/tabs.stories.ts
**Related Issue:** #5779 
Cleans up the remaining playground stories as a follow-up to https://github.com/Esri/calcite-design-system/issues/9084.
=> refactor: ensure consistent playground stories

packages/calcite-components/src/components/flow/interfaces.ts, packages/calcite-components/src/demos/flow.html
=> docs(flow): Add FlowItemLike interface documentation.

packages/calcite-components/src/components/combobox-item/combobox-item.tsx
=> docs(combobox-item): update description property

packages/calcite-components/src/components/inline-editable/inline-editable.e2e.ts, packages/calcite-components/src/components/inline-editable/inline-editable.tsx
=> test(inline-editable): stabilize test

packages/calcite-components/index.html
Updates the demo page's reference link to the updated internal Storybook site url.
=> docs(demos): update storybook link

packages/calcite-components/src/components/dialog/dialog.tsx
**Related Issue:** #10860
- fix error when dialog is opened initially.
=> fix(dialog): fix error when initially opened

package-lock.json, package.json, packages/calcite-components/package.json
Updates to the latest `4.32.0-next.29`, which should address the Stencil type mismatches from internal teams.
=> build(deps): update arcgis to v4.32.0-next.29

package-lock.json, package.json
Removes the following unused dependencies:
* [`@storybook/addon-webpack5-compiler-babel`](https://www.npmjs.com/package/@storybook/addon-webpack5-compiler-babel)
* [`quicktype-core`](https://www.npmjs.com/package/quicktype-core)
* [`workbox-build`](https://www.npmjs.com/package/workbox-build)
=> build(deps): drop unused deps

packages/calcite-design-tokens/.eslintrc.cjs
Removes removed rule missed in https://github.com/Esri/calcite-design-system/pull/10909.
=> chore(linting): remove obsolete rule

.renovaterc.json, packages/calcite-components/src/components/slider/slider.scss, packages/calcite-design-tokens/support/token-transformer/styleDictionary/parser/utils/resolveRelevance.ts
=> chore(linting): fix errors

.renovaterc.json
Groups `stylelint` deps for smoother updates (see #9640).
=> ci(renovate): add group for `stylelint` deps

packages/calcite-design-tokens/package.json
Adds utility NPM script to update test snapshots per [Jest's doc](https://jestjs.io/docs/snapshot-testing#updating-snapshots).
=> chore(tokens): add test updating script

packages/calcite-components/src/components/list/list.tsx
remove unused private property. 🧹
=> refactor(list): remove unused private property.

.github/workflows/pr-e2e.yml
Exclude the examples from the list of testable changes.
=> ci(e2e): skip tests for changes to examples

package-lock.json, package.json, packages/calcite-components/package.json
=> build(deps): update arcgis to v4.32.0-next.35

packages/calcite-components/src/components/list-item/list-item.e2e.ts, packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list-item/utils.ts, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #10949
- set displayMode on slotted list
- cleanup 🧹 
- e2e test
=> refactor(list-item): set displayMode on slotted list

packages/calcite-components/src/components/input/input.scss
Fixes invalid selector that was introduced in https://github.com/Esri/calcite-design-system/pull/8160/files#diff-dedd929af14b005ccb0ca87cf19b8bf0f0d1569b619621536f7f14c232ae81acR482.
=> fix(input): fix broken selector

packages/calcite-components/src/components/dropdown/dropdown.scss
=> refactor(dropdown): tidy up styles

packages/calcite-components/src/components/tab-title/tab-title.e2e.ts
=> test(tab-title): unskip test

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
=> test(dropdown): unskip tests

packages/calcite-components/src/components/accordion/accordion.e2e.ts, packages/calcite-components/src/components/action-bar/action-bar.e2e.ts, packages/calcite-components/src/components/action-pad/action-pad.e2e.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/stepper/stepper.e2e.ts, packages/calcite-components/src/tests/commonTests/labelable.ts
=> test: avoid hanging async code

packages/calcite-components/src/components/sheet/resources.ts, packages/calcite-components/src/components/sheet/sheet.scss, packages/calcite-components/src/components/sheet/sheet.stories.ts, packages/calcite-components/src/components/sheet/sheet.tsx
- add a new content container to hide overflowed slotted content
- add story screenshot test
=> fix(sheet): fix rounded corners when `displayMode="float"`

CONTRIBUTING.md
=> docs(contributing): update commit message format section

packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
=> refactor(input-date-picker): fix typo

packages/calcite-components/src/components/sheet/sheet.scss
=> fix(sheet): remove some margin

packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #10981 
✨🧪🧹😅✨
=> fix(input-time-zone): remove debugging log messages

packages/calcite-components/src/components/accordion-item/accordion-item.scss
**Related Issue:** #10894
Update `accordion-item`'s description for consistency with our documentation style guide.
=> docs(accordion-item): update icon token descriptions

packages/calcite-components/tsconfig.json
=> chore: drop outdated/non-applicable lit migration notes

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/combobox/interfaces.ts, packages/calcite-components/src/components/list/list.e2e.ts
**Related Issue:** #8043 
This provides more flexibility for filtering combobox items and groups.
=> feat(combobox): add `filterProps`

packages/calcite-components/src/assets/styles/includes.scss, packages/calcite-components/src/components/autocomplete-item/autocomplete-item.scss, packages/calcite-components/src/components/combobox-item/combobox-item.scss, packages/calcite-components/src/utils/text.tsx
**Related Issue:** #11173 
This also introduces a mixin for shared text highlighting styles.
=> feat(combobox, input-time-zone): highlight text matches consistently

packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, packages/calcite-components/src/components/time-picker/time-picker.e2e.ts, packages/calcite-components/src/components/time-picker/time-picker.tsx
**Related Issue:** #10102 
Exposes previously internal event.
=> feat(time-picker): expose `calciteTimePickerChange` event

CONTRIBUTING.md
Update style lint integrations link so it resolves.
=> docs(contributing): update style lint link

.renovaterc.json
=> ci(renovate): group dep-bump PRs for @floating-ui packages

.renovaterc.json
=> ci(renovate): group dep-bump PRs for @cspell packages

packages/calcite-components/src/components/action/action.e2e.ts, packages/calcite-components/src/components/menu-item/menu-item.e2e.ts
=> refactor: tidy up theme tests

package-lock.json, package.json, packages/calcite-components/src/utils/config.spec.ts, packages/calcite-components/src/utils/config.ts, packages/calcite-components/vite-env.d.ts, packages/calcite-components/vite.config.ts
**Related Issue:** #10731  
Simplifies version placeholder replacement by using vite's built-in [`define` feature](https://vite.dev/config/shared-options.html#define).
=> build: simplify version placeholder replacement

packages/calcite-components/src/components/combobox/combobox.e2e.ts
=> test(combobox): skip unstable test

packages/calcite-components/src/components/list-item/list-item.e2e.ts, packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #11322
- reflect property
- add test
=> fix(list-item): reflect the sortHandleOpen property

packages/calcite-ui-icons/docs/keywords.json, packages/calcite-ui-icons/icons/crosshair-16.svg, packages/calcite-ui-icons/icons/crosshair-24.svg, packages/calcite-ui-icons/icons/crosshair-32.svg
**added**
crosshair-16
crosshair-24
crosshair-32
=> feat: add crosshair

packages/calcite-components/src/components/table/table.tsx
=> chore(table): move workaround comment back to its usage

.github/ISSUE_TEMPLATE/enhancement.yml
**Related Issue:** #9922
Adds the icons package to the enhancement issue template.
=> chore: add ui icons package to enhancement template

packages/calcite-components/src/components/action-pad/action-pad.scss
- restores rounded styling for action-pad
- existing screenshot test is updated
=> refactor(action-pad): restore rounded styling

packages/calcite-components/vite.config.ts
=> refactor: address ts-strict-ignore comment

packages/calcite-components/src/tests/commonTests/utils.ts
=> chore(test-utils): add more context to getTag error message

packages/calcite-components/src/components/carousel/carousel.scss
**Related Issue:** #11426
Adjusts colors for the navigation controls in Carousel component.
| Before    | After |
| -------- | ------- |
| ![Screenshot 2025-02-03 at 3 42 42 PM](https://github.com/user-attachments/assets/50ae51df-76e7-44f9-83ae-917797bdbbb2) |  ![Screenshot 2025-02-03 at 3 42 35 PM](https://github.com/user-attachments/assets/f38046fe-4591-46dd-9881-eacbb829148b) |
=> fix(carousel): Improve Carousel navigation display

packages/calcite-components/src/components/dropdown-group/dropdown-group.scss, packages/calcite-components/src/components/dropdown-item/dropdown-item.scss, packages/calcite-components/src/components/dropdown/dropdown.scss
Updates `dropdown`, `dropdown-group` and `dropdown-item` CSS variable descriptions in alignment with documentation standards.
=> docs(dropdown, dropdown-group, dropdown-item): update component token descriptions

packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
=> chore(input-date-picker): drop an unnecessary comment

readme.md
Link to the READMEs of the packages in the monorepo's root README.
=> docs: link to package readmes from root readme

package-lock.json, package.json, packages/calcite-components/package.json
**Related Issue:** #11536
Update the `arcgis` scoped packages to `v4.33.0-next.13`.
=> build(deps): update arcgis to ^4.33.0-next.13

.github/workflows/contributors.yml, examples/components/angular/README.md, examples/components/angular/src/app/app.component.ts, examples/components/react/README.md, examples/components/react/src/App.tsx, package-lock.json, package.json, packages/calcite-components/package.json, packages/calcite-components/src/components/action/action.tsx, packages/calcite-components/src/components/block-group/block-group.e2e.ts, packages/calcite-components/src/components/block-group/block-group.tsx, packages/calcite-components/src/components/dialog/dialog.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/loader/loader.scss, packages/calcite-components/src/components/loader/loader.tsx, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/components/sheet/sheet.tsx, packages/calcite-components/src/controllers/useFocusTrap.ts, readme.md
Cherry-pick the [3.0.0 Patch - 2025-02-13] commits from `dev` to `main`.
> [!IMPORTANT]
> This PR **must** be [rebase-merged]
[3.0.0 Patch - 2025-02-13]: https://github.com/Esri/calcite-design-system/issues?q=-is%3Aissue%20milestone%3A%223.0.0%20Patch%20-%202025-02-13%22%20
[rebase-merged]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits
=> chore: cherry-pick patch commits

package-lock.json, package.json, packages/calcite-components/package.json
This reverts commit 18e72fb4cc8697d105ccd23e3aac20a21ecf807b.
=> revert: build(deps): update arcgis to ^4.33.0-next.13 (#11539)

packages/calcite-components/src/components/block-group/block-group.tsx
Matches documentation from the list component
https://github.com/Esri/calcite-design-system/blob/3470a989073ba61dca514f1c62bb18413b17ce8f/packages/calcite-components/src/components/list/list.tsx#L194
=> docs(block-group): update documentation for canPull

packages/calcite-components/src/components/rating/rating.tsx, packages/calcite-components/src/components/segmented-control/segmented-control.tsx
=> chore(rating, segmented-control): improve event handler types

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.stories.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #7224 
Adds offset properties for dropdown menu placement.
=> feat(dropdown): add `offsetDistance` and `offsetSkidding` properties

packages/calcite-components/src/components/chip/chip.e2e.ts
=> test(chip): tidy up tests

packages/calcite-design-tokens/package.json, packages/calcite-design-tokens/vitest.config.ts
This improves the test workflow by running the build and tests after changes are made to either the test or source code.
=> chore: improve dev workflow (build watch mode + test reruns)

packages/calcite-ui-icons/README.md
redirecting scale vector icons read me link
=> fix: Update README.md

packages/calcite-ui-icons/docs/keywords.json, packages/calcite-ui-icons/icons/check-16.svg, packages/calcite-ui-icons/icons/check-24.svg, packages/calcite-ui-icons/icons/check-32.svg
**added** 
check-16
check-24
check-32
=> feat: add check

.gitignore
Ignores IntelliJ IDEA [module files](https://www.jetbrains.com/help/idea/creating-and-managing-modules.html#modules-idea-java).
=> chore: ignore iml files

packages/calcite-components/src/components/action-menu/action-menu.tsx
=> docs(action-menu): fix minor grammar error

packages/calcite-design-tokens/src/build/format/index-file.ts, packages/calcite-design-tokens/src/build/transforms/value/merge-value.ts
=> perf: build theme dictionaries in parallel

packages/calcite-components/src/components/combobox-item/combobox-item.scss, packages/calcite-components/src/components/combobox/combobox.scss
Rename `internal` tokens in combobox & combobox-item.
=> refactor(combobox, combobox-item): rename internal tokens

packages/calcite-components/src/components/block-group/block-group.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/text-area/text-area.e2e.ts, packages/calcite-components/src/tests/commonTests/disabled.ts, packages/calcite-components/src/tests/commonTests/floatingUI.ts, packages/calcite-components/src/tests/commonTests/focusable.ts, packages/calcite-components/src/tests/commonTests/formAssociated.ts, packages/calcite-components/src/tests/commonTests/labelable.ts, packages/calcite-components/src/tests/commonTests/openClose.ts, packages/calcite-components/src/tests/commonTests/slots.ts, packages/calcite-components/src/tests/commonTests/t9n.ts, packages/calcite-components/src/tests/commonTests/themed.ts
Ignores additional files for incremental strict-mode updates (see #11177).
=> chore: update @ts-strict-ignore comments

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
Adds the Workflow Manager team to the Esri team dropdown across our issue templates, including: accessibility, bug, enhancement and new component issue requests.
=> chore: add workflow manager to team issue templates

.github/workflows/schedule-updates.yml
Stems from https://github.com/Esri/calcite-design-system/pull/11947#issuecomment-2813498710.
=> ci: only include THIRD-PARTY-LICENSES.md in update PRs

packages/calcite-design-tokens/src/build/filter/global-js.ts, packages/calcite-design-tokens/src/build/overrides/index.ts, packages/calcite-design-tokens/src/config/index.ts
=> refactor: remove obsolete customization

packages/calcite-components/src/components/sheet/sheet.scss, packages/calcite-components/src/components/sheet/sheet.stories.ts, packages/calcite-components/src/components/shell-panel/shell-panel.scss, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** #12042
- Adjust z-index of resize handle
- add screenshot tests
=> fix(shell-panel, sheet): Resize handle overlaps dropdown within panel

packages/calcite-components/src/components/shell-panel/shell-panel.scss, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** #12057
Fixes regression where content isn't overflowing correctly with the newly added internal `content-container` element.
- fix regression overflowing content
- add screenshot test
=> fix(shell-panel): handle overflow scrolling

CONTRIBUTING.md
Updates our contributing labels and guidelines to reflect the `dev` branch and describe the installation and verified process in more depth.
=> docs(contributing): update lifecycle label descriptions

support/dictionaries/dict-calcite-design-system.txt
* Updates dictionary to address recent warnings
* Tidy up NPM-package entry group
=> chore(dictionary): update custom dictionary

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/utils/number.ts
**Related Issue:** #8640
Strip all invalid characters during sanitization.
=> fix(input-number): prevent entry of invalid characters

packages/calcite-components/src/components/fab/fab.scss
**Related Issue:** [#10004](https://github.com/Esri/calcite-design-system/issues/10004)
- Remove shadow change on `:hover`.
- Remove shadow change on `:active`.
=> feat(fab): enhance component's interactivity states

packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts, packages/calcite-components/src/components/autocomplete/autocomplete.tsx, packages/calcite-components/src/demos/autocomplete.html
**Related Issue:** #12096
- opens the component when input is typed
- adds test
=> fix(autocomplete): should open on key input and close when key input is cleared

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list-item/utils.ts, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #12074
- correctly set the drag order and set size on filtered items
- add tests
=> fix(list): correctly set the drag order and set size on filtered items

packages/calcite-components/src/components/action-pad/action-pad.tsx
**Related Issue:** #7507
- Corrects deprecation message
=> docs(action-pad): fix deprecation message

packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/demos/list.html
**Related Issue:** #11650
- removes auto expanding on drag
- improve demos
=> fix(list): remove auto expanding behavior when dragging

packages/calcite-components/src/components/radio-button/radio-button.scss
**Related Issue:** [#10021](https://github.com/Esri/calcite-design-system/issues/10021)
- Update radio to `--calcite-color-brand-hover` on `:hover`.
- Update radio to `--calcite-color-brand-press` on `:press`.
=> feat(radio-button): enhance component's interactivity states

packages/calcite-components/conventions/Internationalization.md
Update t9n implementation specifications in conventions.
=> docs(conventions): update t9n spec

packages/calcite-components/src/components/sheet/sheet.scss, packages/calcite-components/src/components/sheet/sheet.stories.ts, packages/calcite-components/src/components/shell-panel/shell-panel.scss, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** #12196
- fix styling for resize handle in RTL
- add screenshot tests
=> fix(sheet, shell): fix resize handle in RTL direction

packages/calcite-components/src/components/checkbox/checkbox.e2e.ts, packages/calcite-components/src/components/checkbox/checkbox.scss, packages/calcite-components/src/custom-theme/checkbox.ts
**Related Issue:** [#10020](https://github.com/Esri/calcite-design-system/issues/10020)
- Update checkbox to brand.hover on hover.
- Update checkbox to brand.press on press.
- Add `--calcite-checkbox-border-color-press` css token.
=> feat(checkbox): enhance component's interactivity states

packages/calcite-components/src/components/combobox-item/combobox-item.scss, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.scss
**Related Issue:** #12226
Add `--calcite-combobox-divider-color`.
deprecate(combobox): remove `--calcite-combobox-item-border-color`
=> feat(combobox): add `--calcite-combobox-divider-color` 

packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, packages/calcite-components/src/controllers/useTime.ts
=> refactor: rename and move time controller for consistency

packages/calcite-components/src/components/sort-handle/assets/t9n/messages.de.json
Updated translation using Jenkins. Please review and merge @anveshmekala @jcfranco @benelan @geospatialem 
CC: @michi6571 @masa6674
=> chore(localization): update translation

packages/calcite-design-tokens/src/tokens/semantic/corner.json, packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
=> refactor(semantic-tokens): update description for `--calcite-corner-radius-sharp`

packages/calcite-components/src/components/accordion-item/accordion-item.e2e.ts, packages/calcite-components/src/components/accordion-item/accordion-item.scss, packages/calcite-components/src/components/accordion-item/accordion-item.tsx, packages/calcite-components/src/components/accordion/accordion.stories.ts
**Related Issue:** #10705
- fix font sizing for consistency with the headingLevel property
- add screenshot test to catch any regression
=> fix(accordion-item): fix font size for headingLevel property

packages/calcite-components/src/demos/sortable-list.html
Remove unsupported `intl` properties from demo file.
=> refactor(sortable-list): remove unsupported properties from demo

packages/calcite-components/src/components/input-date-picker/assets/t9n/messages.en.json, packages/calcite-components/src/components/input-date-picker/assets/t9n/messages.json
**Related Issue:** #12238
Add message strings.
=> chore(input-date-picker): add message strings

.github/scripts/assignPullRequestReviewer.js, .github/scripts/support/resources.js, .github/workflows/pr-t9n.yml
Action to assign reviewers for translation PR's.
=> chore: add action to assign reviewers for translation PR

packages/calcite-ui-icons/docs/keywords.json, packages/calcite-ui-icons/fantasticonrc.json, packages/calcite-ui-icons/icons/content-side-by-side-right-16.svg, packages/calcite-ui-icons/icons/content-side-by-side-right-24.svg, packages/calcite-ui-icons/icons/content-side-by-side-right-32.svg
**added**
content-side-by-side-right-16
content-side-by-side-right-24
content-side-by-side-right-32
=> feat: add content side by side right

packages/calcite-components/src/components/autocomplete/autocomplete.tsx
=> refactor(autocomplete): merge `willUpdate` repositioning logic

packages/calcite-ui-icons/docs/keywords.json
=> chore(icons): remove surrounding space from keywords metadata

.markdownlint-cli2.jsonc, .prettierignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, packages/calcite-components/conventions/Styling.md, packages/calcite-components/conventions/Testing.md, packages/calcite-components/eslint.config.mjs, packages/calcite-components/package.json, packages/calcite-components/src/components/radio-button/radio-button.scss, packages/calcite-design-tokens/package.json, packages/calcite-tailwind-preset/package.json, packages/calcite-ui-icons/README.md, packages/calcite-ui-icons/eslint.config.mjs, packages/calcite-ui-icons/package.json, support/syncLinkedPackageVersions.ts
Minor cleanup and standardization of our linting setup:
* applies consistent linting calls
* corrects patterns in consolidated `.prettierignore`
* fixes linting issues
* simplifies markdownlint  configuration
=> chore(linting): update linting setup

packages/calcite-components/src/components/accordion/accordion.stories.ts
=> chore: drop commented-out import

packages/calcite-components/src/components/combobox/assets/t9n/messages.en.json, packages/calcite-components/src/components/combobox/assets/t9n/messages.json
**Related Issue:** #10409, #12525
Add message strings.
=> chore(combobox): add message strings

packages/calcite-components/src/components/date-picker/utils.ts
Updates locale data missing error message to be semantic.
chore: omit from CHANGELOG
=> refactor(date-picker): update error message

.husky/pre-commit
Improves DX by auto-committing t9n manifest updates.
=> chore: ensure t9n manifest updates are committed by precommit hook

packages/calcite-components/src/components/input-message/input-message.e2e.ts, packages/calcite-components/src/components/input-message/input-message.scss, packages/calcite-components/src/components/input-message/input-message.stories.ts, packages/calcite-components/src/components/input/input.tsx, packages/calcite-components/src/custom-theme.stories.ts, packages/calcite-components/src/custom-theme/input-message.ts
**Related Issue:** #11759
Improved theming tests with a fix to e2e and added screenshot coverage. 
Removed an invalid `[status="warning"]` rule set.
=> test(input-message): improve theming tests

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.scss, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/dropdown/resources.ts
=> refactor(dropdown): drop component name from CSS classes

packages/calcite-components/src/components/accordion-item/assets/t9n/messages.en.json, packages/calcite-components/src/components/accordion-item/assets/t9n/messages.json, t9nmanifest.txt
**Related Issue:** #12232 
Adding t9n strings for expand and collapse tooltips.
=> chore(accordion-item): add message strings

packages/calcite-components/src/components/date-picker/date-picker.e2e.ts
✨🧪🧹✨
* removes waiting on transition timeouts
* renames some event spies to better match name
* use local date utils
* remove unnecessary `E2EPage.waitForChanges`
=> test(date-picker): tidy up

package.json, support/check-volta.ts
Ensures proper volta install on repo initialization.
=> chore: check for volta install at root level

.github/scripts/addUnblockedComment.js
**Related Issue:** #12667 
Updates action to account for full URLs as well so folks can just copy and paste full issue links. 
Tested and working on separate repo with the following comment in the description:
=> ci(actions): update unblocked issues action to take full URLs

packages/calcite-components/src/components/tree-item/tree-item.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.tsx
**Related Issue:** #10978
Add `calciteTreeItemSelect` event.
=> feat(tree-item): add `calciteTreeItemSelect` event

packages/calcite-components/src/components/list-item-group/list-item-group.scss
**Related Issue:** [#10764](https://github.com/Esri/calcite-design-system/issues/10764)
Update font weight to `--calcite-font-weight-bold`.
Update color to `--calcite-color-text-1`.
=> feat(list-item-group): update design for 4.0

.github/scripts/support/monday.js
=> chore: update `peopleMap` used by Monday.com support script

package-lock.json, packages/calcite-components/package.json
=> build(deps): bump `focus-trap`

package-lock.json, package.json, packages/calcite-components-react/package.json, packages/calcite-components/package.json
=> build(deps): bump `@arcgis` deps to latest
