src/components/slider/slider.scss
**Related Issue:** #4290
Replicated the issue on a PC tablet (Dell Precision 5560 per use case) and noticed that the slider was being blocked by the browser swipe gesture. Happened on several browsers tested on this device (Chrome 110.0.5481, MicrosoftEdge 11.0.1587).
https://user-images.githubusercontent.com/19231036/222330979-31a80b8e-4ab8-41d1-aaa5-812248e6e838.mp4
Solved by disabling browser swipe navigation to next/previous page to prevent interference with the slide thumb intended functionality to follow touch gesture. The fix will apply to all touch-enabled devices, including iOS and and tablets running other operating systems. 
Can't see a way to automatically test it in our setup, maybe we could add a wiki or confluence page for the slider behavior on other devices (any slider …
=> fix(slider): range slider thumb on all touch-enabled devices now follows touch gesture

package.json
This fixes `npm run docs:preview` by including the `util:generate-t9n-types` script.
=> build: ensure required files are available for doc preview build

src/components/action/action.scss, src/components/action/action.stories.ts
**Related Issue:** #5375 
Updates layout to include space for indicator when `text-enabled` is set.
=> fix(action): ensure consistent width to accommodate indicator when displaying text

src/components/modal/modal.scss, src/components/modal/modal.tsx, src/components/modal/resources.ts
**Related Issue:** #5067 
Moves an internal open state class to the topmost container so all transitions are in sync.
=> fix(modal): ensure modal transitions are in sync

src/components/avatar/avatar.scss, src/components/avatar/avatar.stories.ts
**Related Issue:** #6203
The color of the name initials for light and dark modes are not far apart enough to create interesting background colors that would pass contrast. 
To make light letters lighter and dark letters darker, we’re swapping `ui-text-3` with `ui-text-2`. 
Adding a visual test as well.
=> fix(avatar): passes color contrast after adjusting text color

src/components/accordion-item/accordion-item.scss, src/components/accordion/accordion.stories.ts
**Related Issue:** #5683
The `accordion-item header` longer `title`/`description` no longer extends outside the container instead of wrapping.
Note: Tailwind's `break-words` implements the `overflow-wrap: break-word` CSS property, but it seems to have no impact for me in Chrome. Used  our `word-break() mixin` instead to achieve the desired effect.
Provided a `_TestOnly` screenshot that simulates long words with underscores.
=> fix(accordion, accordion-item): now wraps long words in header (title & description)

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml, .github/workflows/add-priority-label.yml
We received some feedback after Dev Office Hours asking for an additional option for priority, specifically around an upcoming milestone (e.g. one of our next "major" releases).
1. Updates the priority dropdown to include a new option for folks:
- **_Proposed change_** - `p4 - not time sensitive`
- **_New change_** - `p3 - want for upcoming milestone`
- `p2 - want for current milestone`
- `p1 - need for current milestone`
- `p0 - emergency`
3. Also adds the priority dropdown to the following requests:
- accessibility bugs
- enhancements (no `p0 - emergency` option)
- new components (no `p0 - emergency` option)
**Note: will update the labels once approved, and prior to merging.**
Original PR for context: https://github.com/Esri/calcite-components/pull/6513
=> ci: update user-defined priority

src/components/modal/modal.tsx
**Related Issue:** #6617
1. Updates `content-top` and `content-bottom` to kabob case
2. Adds additional context to the `content-top` and `content-bottom` slot descriptions
=> docs(modal): kebab-case slot names and sticky context

src/components/input-number/input-number.tsx, src/components/input-text/input-text.tsx, src/components/input/input.tsx
Document API consistency across components, in particular while working through the new component, `textarea`. cc: https://github.com/Esri/calcite-components/pull/5644
Update includes consistency with `input`, `input-number`, and `input-text` (in alignment with `textarea`) for the following:
1. `autofocus` prop:
> When `true`, the component is focused on page load. Only one element can contain `autofocus`. If multiple elements have `autofocus`, the first element will receive focus.
2. `selectText()` method:
> Selects the text of the component's `value`.
=> docs(input, input-number, input-text): api consistency across components

src/components/tile/tile.scss
**Related Issue:** #5608
`Tile` with `Link` used coloring of the icon to indicate that the tile contains a link, which isn't sufficient differentiation 
for users with color blindness. The PR adds styling to the link `heading` as well, making it both colored and underlined.
=> fix(tile): adds styling to `tile` where `link` is present for additional distinction

src/components/tile-select/tile-select.tsx
**Related Issue:** #6185 
Renames event handlers to prevent click listener not firing when the tile-select area was clicked in the `dist-custom-elements` output target. This seems like a Stencil bug caused when an event handler is identical to its listened event name (needs further investigation to confirm cc @benelan).
=> fix(tile-select): fix click not firing in custom-elements build

src/utils/dom.ts
**Related Issue:** #6188
This is a workaround for modal throwing an error in the `dist-custom-elements` build when setting focus on the first focusable item after the component initially renders. Fortunately for modal, focus is set properly after the open animation.
The problem seems to be the focus-trap's element `ref` not being called on `componentDidLoad`, not even after using `requestAnimationFrame` as used in [this Ionic util](https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/helpers.ts#L72-L79), nor `setTimeout` as suggested [here](https://github.com/ionic-team/stencil/issues/3246#issuecomment-1048802446). We'll investigate and open an issue if this is indeed a lifecycle bug.
=> fix(modal): prevent error when calling setFocus on a recently rendered and opened modal (`dist-custom-elements`)

src/components/button/button.tsx, src/components/checkbox/checkbox.tsx, src/components/combobox/combobox.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/input-number/input-number.tsx, src/components/input-text/input-text.tsx, src/components/input-time-picker/input-time-picker.tsx, src/components/input/input.tsx, src/components/radio-button/radio-button.tsx, src/components/rating/rating.tsx, src/components/segmented-control/segmented-control.tsx, src/components/select/select.tsx, src/components/slider/slider.tsx, src/components/switch/switch.tsx, src/components/text-area/text-area.tsx, src/tests/commonTests.ts, src/utils/form.spec.ts, src/utils/form.tsx
**Related Issue:** #5164 
This allows developers to associate form components by providing the form ID. 
* the form must be available in the DOM before the component is attached to the DOM
* components will not look up ancestors for form if the ID is invalid or if the form is not found
I'll DRY up some duplication in the `commonTests#formAssociated` test helper in a separate PR. I went this route to expedite testing.
=> feat: support setting form ID on form components

src/components/text-area/text-area.tsx
**Related Issue:** #5644
Component methods need to be private if they are using a 3rd party package like lodash. Otherwise the package's types are included in dist and we would need to move the package's types from devDeps to deps.
=> ci: fix next releases due to failing type test

src/utils/locale.spec.ts, src/utils/locale.ts, src/utils/time.ts
**Related Issue:** #4148 
Adds util to reuse `Intl.DateTimeFormat` instances.
This came up while working on https://github.com/Esri/calcite-components/issues/5570 and decided to submit separately to link to #4148.
* caching will be tied to single locale, once it changes, the cache will be cleared
* this removes error handling in `time.ts` when creating a `Intl.DateTimeFormat` as specifying an unsupported locale would be a user error.
=> refactor(time): add util to create and cache date time formats

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx, src/components/time-picker/time-picker.e2e.ts, src/components/time-picker/time-picker.tsx
**Related Issue:** #6039 
The `step` property toggles the display of the seconds in the UI. This adds some watchers to trigger rendering when the prop is updated.
=> fix(input-time-picker, time-picker): render when input-time-picker or time-picker's step property changes

src/components/button/button.tsx, src/components/checkbox/checkbox.tsx, src/components/combobox/combobox.tsx, src/components/input-date-picker/input-date-picker.tsx, src/components/input-number/input-number.tsx, src/components/input-text/input-text.tsx, src/components/input-time-picker/input-time-picker.tsx, src/components/input/input.tsx, src/components/radio-button/radio-button.tsx, src/components/rating/rating.tsx, src/components/segmented-control/segmented-control.tsx, src/components/select/select.tsx, src/components/slider/slider.tsx, src/components/switch/switch.tsx, src/components/text-area/text-area.tsx, src/utils/form.tsx
Reformats the form references across components to reside outside of `<code>` in the docs, which were trying to add a `<form>` info the doc site. 
Change includes:
> `<form>` to form
=> docs: format form refs across components

package.json, readme.md, support/prepReleaseCommit.ts
Based on jsdelivr's [about page](https://www.jsdelivr.com/about), [unpkg comparison page](https://www.jsdelivr.com/unpkg) and also recent experiences, jsdelivr seems to be a more reliable, fast and secure option than unpkg.
=> chore: switch unpkg CDN to jsdelivr

src/components/action-bar/action-bar.e2e.ts, src/components/action-bar/action-bar.stories.ts, src/components/action-bar/action-bar.tsx, src/components/action-group/action-group.e2e.ts, src/components/action-group/action-group.tsx, src/components/action-pad/action-pad.e2e.ts, src/components/action-pad/action-pad.tsx, src/components/shell/shell.stories.ts, src/demos/action.html
**Related Issue:** #6390
Deprecates the layout property on the `action-group` element. The parent component of the child `action-group` elements will set the `layout` property.
=> feat(action-bar, action-pad): Set layout property on child action-group elements.

src/components/action-bar/action-bar.tsx, src/components/shell-center-row/shell-center-row.tsx, src/components/shell-panel/shell-panel.tsx
**Related Issue:** #6739
`shell-panel`, and `shell-center-row` components will set the `layout` property for slotted `action-bar` components.
=> refactor(shell-panel, shell-center-row): Set layout property on slotted action-bar components.

package-lock.json, package.json
I noticed the UI Icon versions were again not being published, so I have made the npm versions up to date with the github releases. I then checked and Calcite Components was pretty far behind so updating y'all to the latest so all the new icons are available to teams through CC.
=> build(deps): update calcite-ui-icons from 3.21.2 to 3.21.9

src/utils/observers.ts
Updates typings to only allow init options for `IntersectionObserver`. Other types do not support options.
=> refactor: remove invalid option from observers util

src/index.ts
**Related Issue:** #6696 
Adds workaround to force Stencil build to export `getAssetPath` for developers to check if the asset path has been set.
=> feat: make getAssetPath available in output targets

src/components/dropdown/dropdown.scss, src/components/dropdown/dropdown.stories.ts
**Related Issue:** #5903
Applies css word break to the container of the trigger slotted element. If it overflows its bounds, words will be broken.
=> fix(dropdown): trigger should break words when overflowing container.

package.json
Using `--quiet` to reduce noise in storybook build logs. Note that this isn't an issue in the CLI, which clears status messages as the build progresses.
=> chore(storybook): use quiet flag to reduce noise from storybook build step

support/deployNextFromCI.ts
Next releases are failing due to exceding the maxBuffer size of stdout/stderr. Here is the error message:
https://github.com/Esri/calcite-components/actions/runs/4671369609/jobs/8272269667#step:5:247
This increases the maxBuffer which should resolve the issue.
=> ci: fix next releases by increasing maxBuffer

conventions/README.md
Fixing a typo in our conventions readme.  Should be `assetsDirs` not `assetsDir`.
=> docs(conventions): fix typo for assetsDirs and add link to Stencil docs

src/components/color-picker-swatch/readme.md
Observed by Esri staff where the component name was listed as "my component"
Adds context to our internal `color-picker-switch` component page.
=> docs: add color-picker-swatch name

src/components/date-picker/assets/date-picker/nls/de-AT.json, src/utils/locale.ts
**Related Issue:** #6737 
The change in this PR is to add support for the German - Austria (de-AT) locale in the date-picker component. It was requested by an international distributor. The change entails adding a new json file for the de-AT locale with locale-specific data.
=> feat: add json for de-AT locale with locale-specific data

src/components/tree-item/tree-item.e2e.ts, src/components/tree-item/tree-item.tsx
**Related Issue:** #5867 
This updates the initial tree-item initialization logic to consider each tier of selected items in the tree hierarchy.
=> fix(tree-item): ensure tree-item properly reflect ancestor-mode selection on initialization

src/components/menu-item/interfaces.ts, src/components/menu-item/menu-item.tsx, src/components/menu/menu.tsx
**Related Issue:** #6531 
Refactors keyboard navigation and cleanup
=> refactor(menu-item,menu): keyboard interaction

src/components/stepper/stepper.e2e.ts
**Related Issue:** #5979 
Add a test to verify stepper-item re-renders when numbering system is changed on parent stepper.
=> test(stepper): adds test to verify stepper-item re-render when numbering-system changes on parent

src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input/input.tsx
Wires up `accessible` test helper for input-date-picker suite. 
**Note**: this rolls back overriding `role` on `calcite-input`'s internal input (see https://github.com/Esri/calcite-components/pull/6805/). This ended up causing invalid markup as some roles require matching aria roles, which refs cannot be resolved between shadow/light DOM:
```
● calcite-input-date-picker › is accessible
expect(received).toHaveNoViolations(expected)
Expected the HTML found at $('calcite-input-date-picker,calcite-input,input[aria-label=""]') to have no violations:
<input aria-label="" class="" inputmode="text" placeholder="MM/DD/YYYY" type="text" role="combobox">
Received:
"Required ARIA attributes must be provided (aria-required-attr)"
Fix any of the following:
Required ARIA …
```
=> test(input-date-picker): add accessible test for input-date-picker

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.scss, src/components/input-time-picker/input-time-picker.tsx, src/components/input-time-picker/resources.ts
**Related Issue**: #6830
This enhances the `input-time-picker` to allow it to be toggled via mouse and keyboard vs initial focus.
This also updates input to allow overriding `role` to accommodate other a11y structures.
=> feat(input-time-picker): allow toggling time picker by clicking the input or entering the down/escape key

calcite-preset.ts, src/assets/styles/global.scss
**Related Issue:** #6857 
This fixes an issue where `--calcite-ui-focus-color`'s default was resolved at `:root` and would not allow it to inherit `--calcite-ui-brand` further down the DOM tree.
=> fix: fix inheritance of default focus-color value

src/components/chip/chip.tsx
Handles the case where a parent Chip Group of `selection-mode="none"` caused the Chip to incorrectly have role of "radio" set. 
cc @geospatialem
=> fix(chip): Uses correct aria role in a selection-mode:none Chip Group

src/components/checkbox/checkbox.e2e.ts, src/components/combobox/combobox.e2e.ts, src/components/input-date-picker/input-date-picker.e2e.ts, src/components/input-number/input-number.e2e.ts, src/components/input-text/input-text.e2e.ts, src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input/input.e2e.ts, src/components/radio-button/radio-button.e2e.ts, src/components/rating/rating.e2e.ts, src/components/segmented-control/segmented-control.e2e.ts, src/components/select/select.e2e.ts, src/components/slider/slider.e2e.ts, src/components/switch/switch.e2e.ts, src/components/text-area/text-area.e2e.ts, src/tests/commonTests.ts
This should help mitigate timeouts caused by additional test coverage added to the `formAssociated` test helper.
This also changes the way we have to use the helpers in E2E tests. I've updated the helper doc to reflect this as well.
=> test: split up form-associated test helper to run a test per use case

.github/ISSUE_TEMPLATE/config.yml
**Related Issue:** #6629 
Adds two links to our [issue template chooser](https://github.com/Esri/calcite-components/issues/new/choose) using `contact_links` for:
- Esri Support
- Esri Community
Learn more on [template chooser and `contact_links`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).
Experience will be similar to [JS's next feedback repo](https://github.com/Esri/feedback-js-api-next/issues/new/choose):
=> ci: adds support and community to issue template chooser

CONTRIBUTING.md
**Related Issue:** #6629 
Updates contributing docs:
- Adds Support and Community guidance 
- Adds context to the `design-complete` label
=> docs(contributing): community and support guidance

src/components/block/block.scss, src/components/block/block.stories.ts, src/demos/block.html
**Related Issue:** #6627 
Adjust slotted icon container css to better align the icon container. Small misalignments due to icon may still occur but this should be better than before. Adds a handful of test-only stories to capture more Block states, and fixes some instance of an outdated prop used in demo pages.
cc @ashetland @SkyeSeitz - I think this was already correct in Figma, but FYI as this will likely require Chromatic approval.
cc @asangma @mitc7862 - FYI
Before:
After:
=> fix(block): Corrects alignment of slotted icon

src/components/flow-item/flow-item.stories.ts, src/components/flow-item/flow-item.tsx, src/components/flow-item/resources.ts
**Related Issue:** #6886
- Adds action-bar slot to flow item so it can be passed to the panel internally.
=> feat(flow-item): Add action bar slot

src/components/action-bar/action-bar.scss, src/demos/panel.html
**Related Issue:** #6758 
Adds a css case to prevent the border at the edge of horizontal action bar bottom-actions.
Before:
After:
=> feat(action-bar): Improve border display in horizontal layout

src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #6278 #6615 #6785
- Only clears the hovering timeout for toggling a tooltip when:
- An active tooltip is being hovered.
- An active tooltip exists and a tooltip reference element is not being hovered.
- This means a newly hovered tooltip can be opened without having to stop moving the mouse.
- Had to make some adjustments for clicked tooltips when `closeOnClick` is true.
- Cleanup some code 
- Adds test
=> fix(tooltip): Open hovered tooltip while pointer is moving

src/components/color-picker/color-picker.tsx
**Related Issue:** #6864
Updates the  `color-picker` component's `allowEmpty` prop, supplying the correct supporting context and behavior for the `true` and `false` values.
=> docs(color-picker): update allowEmpty prop description

src/components/flow-item/flow-item.scss, src/components/flow-item/flow-item.stories.ts, src/components/flow-item/flow-item.tsx, src/components/flow/readme.md, src/components/flow/usage/Menu-actions-and-footer-actions.md, src/components/panel/panel.scss, src/components/panel/panel.stories.ts, src/components/panel/panel.tsx, src/components/shell/shell.stories.ts, src/demos/flow.html, src/demos/shell/block-configurations.html, src/demos/shell/demo-app-advanced-2-shell-header.html, src/demos/shell/demo-app-advanced-center-row-async.html, src/demos/shell/demo-app-advanced-center-row.html, src/demos/shell/demo-app-full-window-reversed.html, src/demos/shell/demo-app-full-window.html, src/demos/shell/demo-app-rtl.html, src/demos/shell/demo-app.html, src/demos/shell/nesting-testing-flow.html, src/demos/shell/nesting-testing.html
**Related Issue:** #6892
- Panel
- Adds `--calcite-panel-footer-padding` to specify the padding of the component's footer.
- Deprecates the `footer-actions` slot, use the `footer` slot instead.
- FlowItem 
- Adds `--calcite-flow-item-footer-padding` to specify the padding of the component's footer.
- Deprecates the `footer-actions` slot, use the `footer` slot instead.
=> feat(panel, flow-item): Add CSS custom property to define footer padding and deprecate "footer-actions" slot.

src/components/list/list.e2e.ts
Skip unstable test for filtering initially. Requires a refactor to filter to be able to get filterData after change of filterText.
=> test(list): skip unstable filter test

src/components/list/list.e2e.ts
Skips unstable list test.
The filter component needs to be refactored to be able to access its data after changing the filterText since its debounced.
=> test(list): skip unstable test

src/components/action-bar/action-bar.scss, src/components/panel/panel.stories.ts
**Related Issue:** #6865
- Removes `transparent` bg color on action-bar.
- Adds screenshot test.
=> fix(action-bar): Set background color on action-bar

package-lock.json, package.json
Updates calcite-ui-icons to the latest published version.
=> build(deps): bump calcite-icons to v3.22.2

src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #6785
- Closes tooltip when pointer is not moving on the tooltip or its reference element.
- Adds test
=> fix(tooltip): close tooltip when pointer is moving

src/components/avatar/avatar.stories.ts, src/components/avatar/avatar.tsx, src/demos/avatar.html
**Related Issue:** #5564 
This PR will add a `label` property in `calcite-avatar` which is used to provide context for Assistive Technology users.
=> feat(avatar): add label prop for alternative text & aria-label

src/components/tooltip/tooltip.e2e.ts, src/components/tree-item/tree-item.tsx, src/components/tree/tree.e2e.ts, src/components/tree/tree.tsx, src/demos/tree.html
**Related Issue:** #6912, #6444, #6509
Updates the interaction model of trees to adhere to the [new design](https://www.figma.com/file/R0B6ljDBIyKPtEa5GXjSjx/Tree-%5Bparent%2Fchildren-selection%5D-%5B6912%5D?node-id=1-76826&t=GOElQQiBF6PkKrgN-0). The key changes to the interaction model are:
1. Tree items will expand when they are clicked (#6444)
2. Child selection modes will not automatically display all children of a selected item as selected (#6912)
3. Clicking a slotted action inside a tree item will not select the tree item (#6509)
Note: this pr does not address the hover states in that design. We are coming down to the wire and I want to give time for code review. I can help address the styling/focus/hover/accessibility aspects of the tree next release.
=> fix(tree): allow selection of parent category w/out selecting children

src/assets/styles/_animation.scss, src/demos/animation/animation.html, src/tests/globalStyles.e2e.ts
Adding additional "left" and "right" animation classes, to support https://github.com/Esri/calcite-components/pull/6919 and other future needs.
- Adds `calcite-animate__in-left` and `calcite-animate__in-right` classes.
- Updates demo page with new classes, and updates demo page "Reset" button functionality.
- Q - I am imagining for now components will set the correct animation where needed based on `rtl`. Not sure if there's a better way to make these rtl / ltr supportive with the classes themselves.
=> feat(styles): Add additional animation classes

package-lock.json, package.json
**Related Issue:** https://github.com/Esri/calcite-components/issues/6925
Adds in the latest Calcite UI icons to support an ArcGIS Online workflow in the upcoming R02 release.
=> build(deps): bump calcite-ui-icons to 3.22.4

.github/workflows/chromatic.yml
Adds a `skip visual snapshots` label which can be used for PRs that don't need to run chromatic.
=> ci: add label to skip visual snapshots

src/components/list/list.e2e.ts, src/components/tooltip/TooltipManager.ts, src/components/tooltip/tooltip.e2e.ts, src/utils/dom.spec.ts, src/utils/dom.ts
**Related Issue:** #6893
- When a tooltip's reference element is inside a shadowRoot, the `focusin` and `focusout` handlers are not activating
- This is because the event handlers are on the document and wont' work inside a shadowRoot
- This PR sets up these focus handlers on each shadowRoot necessary
- Only sets up the focus listeners once per shadowRoot by keeping a count of referenceElements with the same shadowRoot.
- Adds `getShadowRootNode` dom utility to get an elements rootNode if the rootNode is a shadowRoot element.
=> fix(tooltip): fix focusing tooltip when a referenceElement is within a shadowDOM

src/components/chip-group/chip-group.tsx, src/components/chip/chip.tsx
**Related Issue:** #6945
- Provides additional context to the `scale` inheritance of `chip-group` in relation to `chip`.
- Adds backticks to "`true`" values in `chip` and `chip-group`
=> docs(chip, chip-group): provide context to parent scale inheritance

.stylelintrc.json, src/components/stepper/stepper.scss
https://caniuse.com/mdn-css_selectors_host-context
Stems from https://github.com/Esri/calcite-components/pull/6959.
=> chore(linting): ban use of `:host-context` until all browsers support it

src/components/date-picker-month-header/date-picker-month-header.tsx, src/components/date-picker-month-header/resources.ts, src/components/input-date-picker/input-date-picker.e2e.ts, src/utils/date.spec.ts, src/utils/date.ts
**Related Issue:** #6636
This updates `input-date-picker` to follow `date-picker`'s logic and map between the internal and displayed date values for Buddhist calendars.
=> fix(input-date-picker): update input-date-picker to properly handle Buddhist calendar changes

package-lock.json, package.json
**Related Issue:** #6579
Bump focus-trap from 7.4.1 to 7.4.2
=> build(deps): Bump focus-trap from 7.4.1 to 7.4.2

src/components/flow-item/flow-item.e2e.ts, src/components/flow-item/flow-item.tsx
If you have already clicked the back button close the tooltip.
=> fix(flow-item): Close back button tooltip on click

src/components/combobox/combobox.e2e.ts, src/components/combobox/combobox.tsx
This should help users recall the most recent selection when opening the combobox. Previously, this was not ideal if there is a large list of items since the active item index would start from the top when opened. This is especially noticeable in single-selection mode where the input showing the selected value is cleared on open.
Stems from https://github.com/Esri/calcite-components/pull/6947.
=> fix(combobox): ensure most recent selected item is active when combobox is opened

src/components/popover/PopoverManager.ts
**Related Issue:** #6455
- Changes `PopoverManager` event listener to be 'pointerup' instead of `pointerdown` to allow elements to become focused first. (seems like safari was the only browser with an issue)
- `focus-trap` listens for `pointerdown` to get the element to return focus to.
- If these elements become focused first then their focus is returned correctly.
=> fix(popover): change event listener to 'pointerup'

src/components/time-picker/time-picker.e2e.ts, src/components/time-picker/time-picker.tsx
**Related Issue:** #6851 
This ensures the hour, minute and second inputs are the only focusable elements within the component. Previously, focus would land on the hour-increment stepper (due to `tabIndex=1` on steppers and the component using `delegatesFocus: true`), which doesn't listen to up/down keys.
=> fix(time-picker): prevent time-picker part steppers from being focusable

package-lock.json, package.json
Adds in the latest Calcite UI icons, `3.22.6` for this week's `1.4.0` release.
=> build(deps): bump calcite-ui-icons to 3.22.6

src/components/tab-title/tab-title.tsx, src/components/tabs/tabs.e2e.ts
**Related Issue:** #6299
This updates public tab selection events to emit in the next frame to allow internal eventing and state to be set beforehand.
=> fix(tab-nav): ensure selected title is set when tab change event is emitted

CHANGELOG.md
Adds a [few feats and fix](https://github.com/Esri/calcite-components/commit/91c66b4181b16f38b1b384312657b5be8b5b1bf1) that didn't make the last `next` runs:
- 1 fix for `tab-nav`
- 2 feats (`tab-nav` and `navigation, navigation logo, navigation-user`)
Organizes content alphabetically in the log for release.
cc @benelan
=> docs(changelog): organize for release

package-lock.json, package.json
Adds in the latest Calcite UI icons, `3.22.7` for an upcoming `1.4.1` patch.
=> build(deps): bump calcite-ui-icons to 3.22.7

src/utils/t9n.ts
**Related Issue:** #7001
This skips message bundle loading when prerendering.
=> fix(hydrate): fix errors caused by message bundle fetch attempts during prerendering

src/components/menu-item/menu-item.tsx, src/components/navigation/navigation.tsx
**Related Issue:** #7006 
Reallocates the slots outside of the `@component` decorator for JSDoc.
=> docs(navigation, menu-item): reallocate slots for jsdoc generation

src/components/color-picker/color-picker.e2e.ts, src/components/color-picker/color-picker.stories.ts, src/components/color-picker/color-picker.tsx
**Related Issue:** #7004
Restores the fix from https://github.com/Esri/calcite-components/pull/4734, which got unintentionally removed in #2841.
=> fix(color-picker): prevent hue slider thumb from wrapping when dragged near/past the edge

src/components/navigation-logo/navigation-logo.scss, src/components/navigation-logo/navigation-logo.stories.ts, src/components/navigation-logo/navigation-logo.tsx, src/components/navigation-logo/resources.ts, src/components/navigation-user/navigation-user.scss, src/components/navigation-user/navigation-user.stories.ts, src/components/navigation-user/navigation-user.tsx, src/components/navigation-user/resources.ts, src/components/navigation/navigation.stories.ts
**Related Issue:** #7010 
This more explicitly sets the line height within our components, adds class name where we were targeting elements previously, and does a bit of clean up of related css.
Before (with css from JSAPI `4.27` - this wasn't an issue with `4.26` or prior):
After:
=> fix(navigation-logo, navigation-user): Prevent inheriting line-height

.eslintrc.json
**Related Issue:** https://github.com/Esri/calcite-components/pull/7007#issuecomment-1560276591
Add a blank line before the first jsdoc tag, after the description.
=> ci(lint): add blank line before first jsdoc tag

src/components/menu-item/menu-item.scss, src/components/menu-item/menu-item.tsx
**Related Issue:** #7027 
Fixes a css typo and adds a condition to ensure the "href icon" shows as expected.
Before:
After:
=> fix(menu-item): Ensure icon displays when `href` is populated

src/tests/commonTests.ts, src/utils/interactive.ts
**Related Issue:** #7022
This updates `interactive.ts` to prevent blocking of mouse/pointer events unnecessarily. This is needed if mouse/pointer events happen right after toggling `disabled` on an interactive component.
=> fix: ensure mouse events are blocked only when components are disabled

src/components/color-picker-hex-input/color-picker-hex-input.tsx
**Related Issue:** #4072 
This ensures pasted values with `#` are committed on blur since the event is canceled to intercept and modify the text value.  
**Note**: there is no corresponding E2E test due to the puppeteer limitations outlined [here](https://github.com/Esri/calcite-components/pull/5189#issue-1344620750).
=> fix(color-picker): fix pasting hex with leading # character

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #7036 
This fixes an issue where passing in `en-us` instead of `en-US` (or inheriting the lang from the HTML tag) was blocking rendering and throwing a console error.
=> fix(input-time-picker): allow en-us and other supported lowercase locale codes

src/components/combobox-item/combobox-item.tsx, src/components/combobox/combobox.e2e.ts
**Related Issue:** #4738, #3074
This reverts the fix for #4738 to prevent breaking existing user workflows that rely on clicking an item to deselect.
=> fix(combobox): restore toggling of single-select combobox items

src/components/input-time-picker/input-time-picker.e2e.ts, src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #7040
This fixes an issue where setting `lang` to a locale code with an unsupported region (e.g. `nl-nl`) failed to fall back to the base language and didn't render the component.
=> fix(input-time-picker): only load valid dayjs locale files and fallback to base lang when region code is unsupported

src/components/tab-nav/tab-nav.scss, src/components/tab-title/tab-title.scss, src/components/tabs/tabs.stories.ts
**Related Issue:** #7025 
Follow-up to fix to #7026.
Centered `tabs` should spread the `tab-titles` evenly to extend across the entire width of `tab-nav`, as opposed to `inline tab-titles` that only justify against the start of `tab-nav` width.
Added coverage for both `centeredTabsAreEvenlyJustifiedAcrossNavWidth` and `inlineTabsJustifyAgainstTheStartOfTheNavWidth`.
=> fix(tab-nav): justify centered `tab-titles` evenly to extend across the width of `tab-nav`

src/components/list-item/list-item.e2e.ts, src/components/list-item/list-item.tsx
**Related Issue:** https://github.com/Esri/calcite-components/issues/7059
- Always emit calciteListItemSelect on activation
=> fix(list-item): always emit calciteListItemSelect on activation

support/generateT9nTypes.ts
This addresses an issue where manual sorting of `t9nmanifest.txt` entries would not match the automated sorting.
=> chore: ensure t9nmanifest file is sorted consistently

src/components/menu-item/menu-item.stories.ts, src/components/menu-item/menu-item.tsx, src/demos/menu.html
**Related Issue:** #7097 
Updates the rendered order of icons, updates local demo, adds screenshot test.
=> fix(menu-item): Ensure correct order of rendered icons

src/components/flow-item/flow-item.tsx, src/components/panel/panel.tsx, src/components/shell-panel/shell-panel.scss, src/components/shell/shell.tsx
**Related Issue:** #7101 
Adds context to the deprecations of the following slots:
1. Flow item's `"footer-actions"` slot -> use `"footer"`
2. Panel's `"footer-actions"` slot -> use `"footer"`
3. Shell `"center-row"` slot -> provide context to slot name
And the deprecated CSS vars:
1. Reformat Shell Panel to display in the docs and `--calcite-shell-panel-detached-max-height` -> use `heightScale` property.
=> docs: provide context to slot and css var deprecations

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/popover/popover.e2e.ts, packages/calcite-components/src/components/tooltip/tooltip.e2e.ts, packages/calcite-components/src/tests/commonTests.ts
Refactor `floatingUIOwner` test helper to help mitigate timeouts.
Splitting up our common test helpers into individual tests helps mitigate timeouts that occurred when a helper's coverage ended up taking longer than the default test timeout.
The updated doc reflects how to use the helpers in E2E tests.
=> test: set up floatingUIOwner helper to run a test per use case

.github/workflows/remove-next-changelog-entries.yml, package.json
**Related Issue:** #6988
Fixes a couple release CI issues:
1. We were going to rename `master` to `main` but not sure what happened to that so I changed the branch names back before installing the monorepo PR. However I missed a few in `package.json`. I think it is still going to happen but I want to wait for Franco to get back before pulling the trigger. cc @alisonailea 
2. Looks like the Action gets out of sync in a real dev environment rather than my isolated testing. I need to pull before pushing the changelog cleaning. Error: https://github.com/Esri/calcite-components/actions/runs/5191460111/jobs/9359307809#step:5:35
=> ci: fix a couple release ci issues

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list/list.scss
**Related Issue:** https://github.com/Esri/calcite-components/issues/6373
Fixes the "border gap" caused by the table rendered within List.
=> fix(list): Improve border styling

packages/calcite-components/CHANGELOG.md, release-please-config.json
**Related Issue:** #6988
This PR changes the `release-please` PR title to `chore: release latest`. The default is `chore: release master`. 
It also makes sure a `v` isn't added before the version in git tags. Their schema doc says it doesn't by default, 
but I'm not convinced (see links below) so I want to hardcode the config value. The `v` being in the tag wouldn't break anything in our CI, but Lerna doesn't add a `v` and we should make sure our tag format is consistent for our consumer's CI.
https://github.com/googleapis/release-please/blob/bdd9b0158ce79d958da01ebf54cb6b07925bc125/schemas/config.json#L77-L79
https://github.com/googleapis/release-please/blob/bdd9b0158ce79d958da01ebf54cb6b07925bc125/src/strategies/base.ts#L139
=> ci(release-please): change PR title and ensure git tag consistency

packages/calcite-components/src/utils/locale.ts
**Related Issue:** #7130 
This PR will allow users to type `latn` decimal separator for `arabic` lang in  Firefox & safari for `calcite-input` and `calcite-input-number`.
=> fix(input,input-number): allow typing decimal separator in firefox for arabic locale

packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #6378
- Updates internal input's value when the value on the input-date-picker is changed.
- Adds a test
=> fix(input-date-picker): Fix showing the placeholder when resetting the value

packages/calcite-components/src/components/scrim/resources.ts, packages/calcite-components/src/components/scrim/scrim.e2e.ts, packages/calcite-components/src/components/scrim/scrim.tsx
**Related Issue:** #7147
- Updates the scrim to set the scale of the internal loading spinner based on the scrim size.
- Scrim is now responsive with a resize observer.
- Breakpoints added based on design. These could maybe go into some kind of component token in the future.
- Breakpoint is based on the minimum value of width or height.
- Adds test
=> fix(scrim): Responsively set the scale of the loading spinner

packages/calcite-components/conventions/README.md, packages/calcite-components/src/components/alert/alert.e2e.ts, packages/calcite-components/src/components/alert/alert.tsx
**Related Issue:** #6363
fix(alert): Sets autoCloseDuration to "medium" by default. #6363
@jcfranco ~~can we have linting to prevent having any conditional defaults? If not, we should maybe update conventions to say not to do this~~ Lets discuss how we can properly document and test this pattern.
=> fix(alert): Sets autoCloseDuration to "medium" by default

packages/calcite-components/support/generateT9nTypes.ts
This will correct the misspelled file name constant.
=> chore(t9n): corrects name of the path constant

packages/calcite-components/support/generateT9nTypes.ts, t9nmanifest.txt
Fixes `t9nmanifest.txt` entry sorting by changing where it looks for the component name in the t9n dir. This broke when the paths were updated to the new monorepo structure.
=> chore: fix sorting logic for t9nmanifest entries

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #7202
- Updates `selectedItems` when an item's selection is toggled.
- Fixes current logic which depends on value being `true`.
- Adds test coverage
=> fix(list): update selectedItems property on all item selection changes

.github/workflows/design-complete.yml
Updates the design complete workflow for conditions, in the event labels are not present.
In this case, will continue to run if the `design` and/or `1 - assigned` label(s) are not included in the issue. 🤖
=> ci: set design complete label conditionals

packages/calcite-components/stencil.config.ts
Currently our `npm run test:watch` script watches files in `node_modules`, `dist`, and other build outputs, which doesn't make sense unless you're monkey patching stuff. I've been getting an error due to watching too many files since we transitioned to a monorepo:
```log
[ ERROR ]  runJest: Error: EMFILE: too many open files, watch
'/app/packages/calcite-components'
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @esri/calcite-components@1.5.0-next.4
npm ERR!   at location: /app/packages/calcite-components
```
Ignoring `node_modules` and the build outputs resolved the issue for me (ref: https://github.com/jestjs/jest/issues/8088#issuecomment-473101715).
If anyone still experiences this error, installing watchman is another option …
=> build: ignore node_modules and build outputs when watching for changes during stencil tests

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #6854 
This PR will support French AZERTY keyboard layout in `calcite-input` & `calcite-input-number`
=> fix(input, input-number): allows numeric characters.

.github/workflows/deploy-latest.yml
The release-please action randomly started failing 3 days ago with this [unhelpful error](https://github.com/Esri/calcite-components/actions/runs/5360304923/jobs/9725004712#step:2:234). It looks like they [released 3 days ago](https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.10), so I'm pinning the version to the one before that and hoping it will fix it. 
I also added the [`workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) trigger so we can run the action manually.
=> ci(release-please): pin action version and allow manually running action

packages/calcite-components/src/components/tree-item/tree-item.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.scss, packages/calcite-components/src/components/tree-item/tree-item.tsx
**Related Issue:** #6575 
This updates the styling on tree items to ensure they are rendered regardless of its expand/collapse transition.
**Note:** 7209f9bc9fa5aaad361532409bc129400643f459 removes `OpenCloseComponent` implementation since the hooks no longer did anything. We can reapply it once we add corresponding events to tree items.
Release-As: 1.4.3
=> fix(tree-item): ensure expanded tree-item is displayed when expanded and made visible

package-lock.json, packages/calcite-components-react/package.json, packages/calcite-components/package.json, release-please-config.json
**Related Issue:** #7222
Pinning the `release-please` Github Action version in the PR above fixed the error, so their release must have broken something for us. `release-please` is trying to release `v1.5.0` instead of `v1.4.3` because we installed a feat and subsequently reverted it, but our current version is still `1.5.0-next.5`. 
[The logs](https://github.com/Esri/calcite-components/actions/runs/5383995298/jobs/9771404018#step:2:102) say it's skipping the conventional commit versioning strategy and forcing `1.5.0`. I'm hoping I can force `1.4.3` instead, as described in their [manifest doc](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile). If this doesn't work I may need to change the package.json versions back to `1.4.3-next.7`.
=> ci: hardcode release version due to reverting feat

package-lock.json, packages/calcite-components-react/package.json, packages/calcite-components/package.json
A feat accidently snuck into our patch release, which we reverted. This PR changes the versions in `package.json` back to the highest `next` release so the CI doesn't get confused.
=> build: bump package versions back to 1.5.0-next.5

packages/calcite-components/package.json, packages/calcite-components/support/stencilDoubleBuildTypesWorkaround.sh
Add a `prepublishOnly` npm script hook to calcite-components, which builds and makes sure the types aren't broken. In addition to the Stencil bug, Calcite Components also needs to be built after versioning so that the preamble is correct. It has been [a version behind in `next` releases](https://unpkg.com/browse/@esri/calcite-components@1.5.0-next.5/dist/calcite/calcite.esm.js). 
ref: https://github.com/lerna/lerna/tree/main/libs/commands/publish#lifecycle-scripts
=> ci: double build cc when publishing to workaround stencil types bug

packages/calcite-components/src/tests/commonTests.ts
Restores [assertions for tab/mouse focusing on disabled components](https://github.com/Esri/calcite-components/blame/6777b06c5dbad5441ed651d676cd9562d79e6986/packages/calcite-components/src/tests/commonTests.ts#L1044-L1064) removed in the [`disabled` test helper refactor](https://github.com/Esri/calcite-components/pull/7089).
=> test(commonTests): restore disabled focus target testing for non-"none" focus targets

packages/calcite-components/src/components/date-picker/date-picker.tsx, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/tests/commonTests.ts, packages/calcite-components/src/tests/utils.ts
**Related Issue:** #6495 
This ensures the active date is reset properly after a `calcite-input-date-picker`'s date picker is closed (either by blurring or selecting a date).
* This adds an internal `reset` method that can be made public in the future if needed. 
* There was an existing `reset` method prior to these changes that seems to clear the active date when the date picker is blurred or when `Escape` is pressed. We should revisit this behavior since it was [added when the input and date picker were a single component](https://github.com/Esri/calcite-components/blob/v1.0.0-beta.22/src/components/calcite-date/calcite-date.tsx#L263-L270) and it does seem odd to have the date-picker reset in these scenarios. cc @macandcheese @SkyeSeitz @ashetland 
* Utility test methods to interact …
=> fix(input-date-picker): reset active date picker date after closing

packages/calcite-components/.eslintrc.json, packages/calcite-components/src/tests/commonTests.ts
Prevents `unicorn/avoid-abbreviations` from flagging `e2ePage`.
=> chore(linting): allow e2ePage variable naming

packages/calcite-components/src/components/input/input.e2e.ts
This will replace  any instance of `calcite-input-number` used in `calcite-input` E2E tests.
=> test(input): replaces input-number with input component

packages/calcite-components/src/components/tooltip/tooltip.e2e.ts, packages/calcite-components/src/components/tooltip/tooltip.stories.ts, packages/calcite-components/src/components/tooltip/tooltip.tsx, packages/calcite-components/src/demos/tooltip.html
**Related Issue:** #6329
- Deprecates the `label` property.
- The already provided `aria-describedby` attribute is sufficient for accessibility.
- Setting aria attributes on the component is not recommended.
- Can still be set by user so no breaking changes.
- Set to optional by default so its no longer required.
- Update tests
- Update Storybook
- Update HTML
=> fix(tooltip): deprecate the label property due to the description coming from the component's content

packages/calcite-components/src/utils/browser.ts, packages/calcite-components/src/utils/config.ts, packages/calcite-components/src/utils/floating-ui.spec.ts, packages/calcite-components/src/utils/floating-ui.ts
We no longer need to check for Chromium 109+ before applying `getOffsetParent` ponyfill since our supported Chrome versions are now 113 & 114.
**Note**: this also removes internal config flag to bypass the custom logic to handle positioning across shadow DOM (no longer an issue as the ponyfill does not impact performance).
=> refactor(floating-ui): apply composed getOffsetParent consistently

packages/calcite-components/src/components/tab-title/tab-title.scss
Effect is only noticable in high-contrast mode. Issue #6994
**Related Issue:** #6994
Adds a simple z-index to show the high contrast focus outline over the tab title outline.
=> fix(tab-title): add full focus outline to closable tab button in high contrast mode

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/modal/modal.e2e.ts
**Related Issue:** #7254
- Emits internal event when `closed` or `disabled` changes on a list item.
- This internal event triggers the parent list to update its navigable items.
- Adds test for keyboard navigation
=> fix(list): fix keyboard navigation after a listItem's disabled or closed property changes

packages/calcite-components/src/components/popover/popover.tsx
- renames private method from `handlefocusTrapDisabled` to `handleFocusTrapDisabled`
=> refactor(popover): renames private method

packages/calcite-components/src/tests/utils.ts
Refactor to add implementation example to `visualizeMouseCursor` util doc.
=> docs: Add implementation example to `visualizeMouseCursor` util

packages/calcite-components/src/tests/utils.ts
Refactor to add implementation example to `skipAnimations` util doc.
=> docs: Add implementation example to `skipAnimations` util

packages/calcite-components/src/components/color-picker-hex-input/color-picker-hex-input.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/filter/filter.e2e.ts, packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-text/input-text.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/link/link.e2e.ts, packages/calcite-components/src/components/list/list.e2e.ts
Adds more `page.waitForChanges()` after `setFocus` calls. This is needed after https://github.com/Esri/calcite-design-system/pull/7277.
=> test: stabilize tests using setFocus

packages/calcite-components/src/components/dropdown-item/dropdown-item.tsx
**Related Issue:** #6921 
This PR provides accessible label for `calcite-dropdown-item` irrespective of `href` property value.
=> fix(dropdown-item): provides accessible label when href is not parsed

packages/calcite-components/src/components/input-date-picker/assets/input-date-picker/t9n/messages.json, packages/calcite-components/src/components/input-date-picker/assets/input-date-picker/t9n/messages_en.json, packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-date-picker/resources.ts
**Related Issue:** #5581 
This fix will provide placeholder text context for Assistive Technology users in `calcite-input-date-picker`.
=> fix(input-date-picker): provides placeholder text context for AT users

.editorconfig, .prettierrc.json
Adds [`.editorconfig`](https://editorconfig.org/#file-format-details) to ensure people's editors have the same settings as prettier. Prettier will get settings from editorconfig if there is one found. This PR also switches to the new Prettier 3x default of adding trailing commas. 
I linted and nothing else changed except for a few cleanups that also changed w/o the editorconfig. I'll make a separate PR for that.
ref: https://prettier.io/docs/en/configuration.html#editorconfig
options: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
=> chore: add editorconfig

.github/workflows/ready-for-dev.yml
Modifies the `design-complete` workflow to accommodate an iterative design process where:
- Designers can provide a `ready-for-dev` label once initial design efforts have been conducted,
-  The `design` label remains on the issue, and
- If additional iterations or conversations are needed the workflow suggests design comments are open/available as part of the issue
- Naming throughout to `ready-for-dev`
- Label name change from `design-complete` → `ready-for-dev` (_will be implemented once this PR is merged in_)
- Keeps the `design` label on the issue for context
cc @ashetland @SkyeSeitz @brittneytewks
=> ci: modifies design complete workflow to ready for dev

packages/calcite-components/src/components/block/block.stories.ts
**Related Issue:** noticed the failing snapshots in #7327
For example: https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=64b6d984dc6b56c885b8872f
Sets the duration factor to 0 in chromatic snapshots to prevent failures due to loader animation
=> test(block): disable loader animation in chromatic snapshots

packages/calcite-components/.storybook/main.ts
This displays a notice for anyone that might still be looking at the storybook link, which has now been deprecated (as component doc) in favor of the official documentation site.
**Note**: this won't be displayed for Chromatic Storybook builds
=> docs: add warning notice to internal storybook

packages/calcite-components/calcite-preset.ts
**Related Issue:** #7344 
This updates the tooltip z-index layer to use the corresponding design token CSS var.
=> fix(tooltip): ensure --calcite-app-z-index-tooltip is applied

packages/calcite-components/src/components/link/link.scss
**Related Issue:** #6588 
This PR will add back the `2px` outline-offset for `calcite-link`.
=> fix(link): adds outline-offset to avoid overlapping with text.

packages/calcite-components/.storybook/main.ts, packages/calcite-components/src/components/alert/alert.stories.ts, packages/calcite-components/src/components/block/block.stories.ts, packages/calcite-components/src/components/dropdown/dropdown.stories.ts, packages/calcite-components/src/components/loader/loader.stories.ts, packages/calcite-components/src/components/popover/popover.stories.ts, packages/calcite-components/src/components/progress/progress.stories.ts, packages/calcite-components/src/components/shell/shell.stories.ts
**Related Issue:** https://github.com/Esri/calcite-design-system/pull/7337#discussion_r1267378922
Uses `--calcite-duration-factor` to disable animations for all snapshots when running in Chromatic.
=> ci(chromatic): disable animations globally to prevent false positive visual diffs

packages/calcite-components/src/components/alert/alert.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #6018
Use the new `onToggleOpenCloseComponent` pattern to replace both `connectOpenCloseComponent` and `disconnectOpenCloseComponent` on `alert` and `dropdown`. This new pattern is intended to simplify the overall eventing logic.
=> refactor(alert, dropdown): `onToggleOpenCloseComponent` replaces connect logic

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #6018
Use the new `onToggleOpenCloseComponent` pattern to replace both `connectOpenCloseComponent` and `disconnectOpenCloseComponent` on `combobox`. This new pattern is intended to simplify the overall eventing logic.
=> refactor(combobox): `onToggleOpenCloseComponent` replaces connect logic

packages/calcite-components/src/components/action-group/action-group.e2e.ts, packages/calcite-components/src/components/action-group/action-group.tsx
- Adds overlayPositioning property
- Allows a user to set the  `overlayPositioning` on the internal `calcite-action-menu`
=> feat(action-group): Adds overlayPositioning property.

packages/calcite-components/src/assets/styles/global.scss, packages/calcite-components/src/components/modal/modal.e2e.ts, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/components/modal/resources.ts
**Related Issue:** #7325
- refactor(modal): use inline style to set overflow instead of a class
- We don't want to expose css utility classes this way.
=> refactor(modal): use inline style to set overflow instead of a class

packages/calcite-components/src/assets/styles/_animation.scss, packages/calcite-components/src/assets/styles/_floating-ui.scss, packages/calcite-components/src/assets/styles/global.scss
**Related Issue:** #7325
- Reduces root selector amount.
- Only a single root selector now
- animation and floating-ui CSS were spitting out their own root selectors just for CSS vars
- Moves animation helper classes into a mixin
- Moves reduced motion CSS into a mixin
=> refactor: clean up global stylesheets

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #6736
- Updates keyboard navigable items to account for filtered items.
- Updates setFocus method to account for filter being enabled.
- Updates keyboard to account for filter navigation.
- Fixes test
- Adds test
=> fix(list): fix keyboard navigation when filterEnabled is true

packages/calcite-components/src/components/action-bar/action-bar.tsx, packages/calcite-components/src/components/action-pad/action-pad.tsx, packages/calcite-components/src/components/functional/ExpandToggle.tsx
Cleans up some remaining, internal `intlX` props.
=> refactor: rename remaining intl props from interface

packages/calcite-components/src/components/menu-item/menu-item.scss, packages/calcite-components/src/components/menu/menu.stories.ts
**Related Issue:** #7386
Adds css rule to prevent duplicate border in certain nested cases when the last item itself is a parent of other Menu Item components.
Before:
After:
=> fix(menu-item): Prevent duplicate border in nested vertical menu-items

packages/calcite-components/src/components/switch/switch.scss, packages/calcite-components/src/components/switch/switch.stories.ts
**Related Issue:** #4633 
This PR will replace the block focus outline of `calcite-switch` with a rounded one.
Before the change:
After the change:
=> feat(switch): updates focus outline to be rounded

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.tsx
**Related Issue:** #7394 
This fixes opacity thumb keyboard interaction.
=> fix(color-picker): fix opacity slider keyboard nudging

packages/calcite-components/src/components/switch/switch.scss, packages/calcite-components/src/components/switch/switch.stories.ts
**Related Issue:** #7402 
Fix for focus issue where container was getting the focus outline. With this change, the component is still taking up 100% width of the Label, but the focus outline is limited to the visual area. We could look at adjusting the click area in a separate update if needed.
Before:
After:
=> fix(switch): Fix for focus outline style in certain cases

packages/calcite-components/.storybook/helpers.ts, packages/calcite-components/.storybook/main.ts, packages/calcite-components/package.json
**Related Issue:** #7338
Creates a `STORYBOOK_SNAPSHOT_LOCAL_BUILD` environment variable and automatically sets it in the `docs:preview` npm script. When the environment variable is truthy, the storybook build:
- Hides the warning banner
- Displays both TestOnly and NoTest stories
=> chore(storybook): hide warning and show TestOnly stories in local builds

packages/calcite-components/src/components/tooltip/TooltipManager.ts, packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #7396
Updates `TooltipManager` logic to avoid toggling hovered tooltips if they are the active ones.
=> fix(tooltip): avoid extra before open/close event emitting

packages/calcite-components/src/components/slider/resources.ts, packages/calcite-components/src/components/slider/slider.stories.ts, packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #7242
This caps the amount of ticks that get rendered at a time (max 250).
**Note**: The current max was determined heuristically to strike a balance between amount of ticks displayed and avoiding cluttering.
=> fix(slider): prevent excessive tick rendering

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.tsx, packages/calcite-components/src/components/color-picker/resources.ts, packages/calcite-components/src/utils/math.spec.ts, packages/calcite-components/src/utils/math.ts
**Related Issue:** #7005
This addresses slider thumbs appearing cut off.
This also ensures the max hue slider value doesn't overlap with 0 and adds a util to map a value between ranges.
=> fix(color-picker): draw slider thumbs within bounds

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input/input.e2e.ts
=> test(input, input-number): await on missed `page.waitForChanges` calls

packages/calcite-components/src/components/panel/panel.tsx
fix(panel): Add native tooltip to close button.
- Modal uses a native tooltip for its close button
- Using a calcite-tooltip would be too much visual noise
=> fix(panel): Add native tooltip to close button.

packages/calcite-components/src/components/flow-item/flow-item.e2e.ts, packages/calcite-components/src/components/flow-item/flow-item.tsx
**Related Issue:** #7436 #7433
- Use a native tooltip for the back button. #7436
- This is the only component that uses a tooltip by default so it seems like we shouldn't do this
- A native tooltip probably makes more sense as the back icon is pretty recognizable
=> fix(flow-item): Use a native tooltip for the back button

packages/calcite-components/src/components/functional/ExpandToggle.tsx
**Related Issue:** #7451
- Add native tooltip to expand action when no tooltip is slotted.
=> fix(action-bar, action-pad): Add native tooltip to expand action

packages/calcite-components/src/tests/commonTests.ts
This should help identify the exact prop that fails the test.
```bash
● calcite-input-time-zone › reflects › reflects
expect(received).toBeTruthy()
Received: null
```
```bash
● calcite-input-time-zone › reflects › "disabled"
expect(received).toBeTruthy()
Received: null
```
=> chore: improve test failure messaging for defaults and reflects helpers

packages/calcite-components/src/utils/browser.ts
**Related Issue:** #7459 
This checks the build context to make sure `navigator` is available. The prerendering test wasn't catching this because Stencil will mock it.
=> fix: fix SSR build error caused by browser-sniffing util

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/panel/panel.scss, packages/calcite-components/src/components/panel/panel.stories.ts, packages/calcite-components/src/components/panel/panel.tsx, packages/calcite-components/src/components/panel/resources.ts
**Related Issue:** #7453
- Combine wrapper and container nodes/classes to simplify implementation.
- Fixes full height content for children of panel
- It seems that the `<section>` isn't necessary.
- Add stories
=> fix(panel): Allow panel content to take full height.

release-please-config.json
`release-please` was having problems finding it's own pull requests, which was causing issues with the post-merge deployments. The [logs say the problem is with the custom pull request title](https://github.com/Esri/calcite-design-system/actions/runs/5756030451/job/15604709660#step:2:28). Reverting the configuration to the default title seemed to fix the issues in my test repo.
=> ci(release-please): use default pull request title

packages/calcite-components/src/components/accordion-item/accordion-item.tsx, packages/calcite-components/src/components/accordion/accordion.tsx
**Related Issue:** #7448 
This updates accordion to sync its children's properties across shadow boundaries via events.
=> fix(accordion): restore accordion-items working with accordion across shadow DOM

packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #7475
- Makes sure `value` is defined before trying to get its length.
=> fix(input): fix clearable from throwing an error when value is undefined

.github/workflows/deploy-latest.yml, packages/calcite-components/support/stencilDoubleBuildTypesWorkaround.sh
**Related Issue:** #7397 
The vscode-data Stencil output is not being generated if one already exists. It works on `next` because the components get built 3 times, once for tests, once for storybook deployment, and then a third time for the stencil types workaround. I'll try to find a way to remove one of those builds for `next` deployments.
=> ci: ensure vscode-data is generated during every build

packages/calcite-components/src/components/scrim/scrim.e2e.ts, packages/calcite-components/src/components/scrim/scrim.tsx
**Related Issue:** #7032
- Support adding slotted content after initial render
- Uses `onSlotChange` to detect slotted elements
- Hides content container via the hidden attribute
- Updates test
=> fix(scrim): handle slotted children correctly

packages/calcite-components/src/components/chip-group/chip-group.tsx
Running into some error using Chip Group / Chip in React environment with programmatically populated Chips...
Adds check for existence of unfound element.
=> fix(chip-group): Add existence checks

.github/workflows/deploy-latest.yml
The `deploy-latest` action is [throwing an error](https://github.com/Esri/calcite-design-system/actions/runs/5814180775/job/15763323592#step:4:9) saying it can't find the Node version from Volta in `package.json`. 
Interestingly, the `deploy-next` action [checks for the node version](https://github.com/Esri/calcite-design-system/blob/main/.github/workflows/deploy-next.yml#L20) in the exact same way and its run [succeeds](https://github.com/Esri/calcite-design-system/actions/runs/5814180776/job/15763326002#step:3:11) on the same commit.
`¯\_(ツ)_/¯`
=> ci(deploy-latest): hardcode node version to prevent errors

packages/calcite-components/src/components/list/list.stories.ts
- Adds `dragEnabled` to the `list` knobs
- Modifies the stories with the `"drag"` icon to a different icon, in the event testing is conducted with `dragEnabled`
=> docs(storybook): add list dragEnabled knob and modify stories

packages/calcite-components/src/components/block/block.tsx
**Related Issue:** #6484 
Defaults the scale of status icon to `s`
=> fix(block): defaults the status icon to `scale=s`

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #6387 
This prevents `Space` key navigating combobox list when opened.
=> fix(combobox): prevents navigation list with Space key

packages/calcite-components/src/components/tree/tree.e2e.ts, packages/calcite-components/src/components/tree/tree.tsx
**Related Issue:** #7104 
Selects all the child `calcite-tree-item` elements when the root element is selected with `selection-mode="ancestors"`
=> fix(tree): selects all child items when selection-mode is set to ancestors

packages/calcite-components-react/package.json, packages/calcite-components-react/src/auto-define.ts, packages/calcite-components-react/support/patchSSR.ts
**Related Issue:** #7486
Enabling Stencil's [`includeImportCustomElements`](https://stenciljs.com/docs/react#includeimportcustomelements) option prevented SSR and vitetest users from being able to explicitly define the custom elements on the client. This patches the Stencil build to ensure the custom elements aren't defined while on the server.
=> fix: prevent vitetest/ssr errors due to defining components on the server

packages/calcite-components/src/components/shell-panel/shell-panel.tsx
- Remove usage of getSlotted utility
=> refactor(shell-panel): Remove usage of getSlotted utility. #6059

packages/calcite-components/src/components/action-bar/action-bar.e2e.ts, packages/calcite-components/src/components/action-bar/action-bar.stories.ts, packages/calcite-components/src/components/action-bar/action-bar.tsx, packages/calcite-components/src/components/action-bar/resources.ts
**Related Issue:** #7534
- Fix incorrect resources slot value
- Separate state from different slots so they aren't' competing with each other.
- Add tests
=> fix(action-bar): restore "bottom-actions" slot functionality.

packages/calcite-components/package.json
This allows `npm repo @esri/calcite-components` to open directly to https://github.com/Esri/calcite-design-system/tree/main/packages/calcite-components
Reference: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository
Example: https://github.com/rollup/plugins/blob/a01a075364901c416db7485164613806187f6243/packages/commonjs/package.json#L11
=> chore: add `directory` to package.json `repository` property

packages/calcite-components/.eslintrc.cjs, packages/calcite-components/src/components/color-picker/utils.ts
Enables [`one-var`](https://eslint.org/docs/latest/rules/one-var) to prevent consecutive variable declarations. This should make it easier to vertically scan (both the variable and type).
`one-var` to rule them all,
&nbsp;&nbsp;&nbsp;`one-var` to find them,
`one-var` to bring them all
&nbsp;&nbsp;&nbsp;and in the darkness bind them.
=> chore(linting): enable one-var rule

packages/calcite-components/src/utils/openCloseComponent.ts
This updates how `onToggleOpenCloseComponent` determines the duration for the `openTransitionProp` to be more robust to work consistently across browsers.
The previous approach relied on the computed `transition` property having all associated transition values laid out per prop, which didn't work in Safari since it won't include all values if shared.
This change should be covered by existing tests.
cc @Elijbet
=> fix: fix open/close event emitting in Safari

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.tsx
**Related Issue:** #7205 
This updates the color picker to update its state properly when `alphaChannel` is toggled.
=> fix(color-picker): update value when alphaChannel is toggled

packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #7540
- Fixes parent and nested lists from competing with each other and setting dragEnabled on children
- Only closest parent will now set the dragEnabled property on its direct children
- The furthest parent will control setting `selectionMode` and `selectionAppearance` on all child items.
=> fix(list): fixes dragging nested list items

packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.stories.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #6899 
Updates `input-date-picker` and `input-time-picker` to follow read-only design spec.
=> fix(input-date-picker, input-time-picker): do not show dropdown affordance when read-only

packages/calcite-components/src/components/date-picker/assets/date-picker/nls/zh-CN.json
**Related Issue:** #7382
Updates the `date-picker` first day of the week in the `zh-CN` locale to Monday (`周一`), previously set as Sunday (`周日`).
=> fix(date-picker): set start of week to monday in zh-CN

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/button/button.stories.ts, packages/calcite-components/src/components/split-button/split-button.scss, packages/calcite-components/src/components/split-button/split-button.stories.ts
**Related Issue:** #6364 
✨💅✨
**Note**: this also applies `border-1` to `calcite-button` with `appearance="outline-fill"`.
=> fix(split-button): update divider and borders to follow design spec

packages/calcite-components/src/components/combobox-item/combobox-item.tsx
Dropping lingering, unused variable.
=> refactor(combobox-item): drop unused variable

packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts, packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx, packages/calcite-components/src/components/dropdown-group/resources.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.tsx, packages/calcite-components/src/components/dropdown-item/resources.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #6038
`getElementProp` is refactored out across child components as an outdated pattern in favor of inheritable props set directly on the parent.
The logic for setting these props thus moves to the parent, getting rid of the `getElementProp` altogether. The parent component gets a `mutationObserver` to do this as well as `watchers` for when it needs to modify the children.
Inherited props addressed:
=> refactor(dropdown, dropdown-item-group, dropdown-item): `getElementProp` is refactored out in favor of inheritable props set directly on parent

packages/calcite-components/src/components/loader/loader.scss, packages/calcite-components/src/demos/loader.html
**Related Issue:** #6383 
This revisits how the loader animates its different segments to play nicely across all browsers. It seems like the percentages calculated [here](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/loader/loader.scss#L179-L181) are causing Safari to interrupt the animation before resetting (there are some [existing](https://bugs.webkit.org/show_bug.cgi?id=258897) [issues](https://bugs.webkit.org/show_bug.cgi?id=249307) on this behavior). It comes close to the original, but it's not identical, so I'm open to suggestions on how to improve this. cc @driskull @macandcheese @paulcpederson 
Also, the `loader-clockwise` (rotating) animation is now applied to the SVG container to avoid it being overwritten by the …
=> fix(loader): tweak loading animations to work in Safari

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #7574
- use dragAndDrop util for more tests.
=> test(list): Use the dragAndDrop utility for mouse tests

packages/calcite-components/src/components/flow/flow.e2e.ts, packages/calcite-components/src/components/flow/flow.tsx
- catch error when beforeBack promise is rejected
=> fix(flow): catch error when beforeBack promise is rejected

packages/calcite-components/src/components/modal/modal.e2e.ts, packages/calcite-components/src/components/modal/modal.tsx
**Related Issue:** #6381
- catch error when beforeClose promise is rejected
=> fix(modal): catch error when beforeClose promise is rejected

packages/calcite-components/src/components/combobox-item/combobox-item.tsx, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/combobox/utils.ts, packages/calcite-components/src/demos/combobox.html
**Related Issue:** #4738 
Adds `single-persist` mode to `calcite-combobox` to allow users to opt-in to this change in selection behavior (vs making it a breaking change on the current `single` selection mode). 
`clearDisabled` would behave the same way unless we want to make an exception to this mode.
=> feat(combobox): add single-persist selection mode

packages/calcite-components/src/components/tree-item/tree-item.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.tsx, packages/calcite-components/src/components/tree/tree.e2e.ts, packages/calcite-components/src/components/tree/tree.tsx, packages/calcite-components/src/components/tree/utils.ts
**Related Issue:** #6861 
Improves tree's keyboard navigation to move across all items and users can now tab to the next focusable element without having to traverse all items.
* items are now programmatically-focusable only (e.g., `tabindex="-1"`) since the tree moves focus
* keyboard navigation based on https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/#kbd_label
* consolidated tree tests and improved coverage
* moved all navigation logic to the tree-level
* refactored item traversal logic to cover all cases
* moved tree `keyDownHandler` to use VDOM event.
=> fix(tree): improve keyboard navigation

packages/calcite-components/src/components/accordion-item/readme.md
**Related Issue:** #6312 
- Adds context to VS Code for the `accordion-item` component
- Tests our maintenance limitation when additional labels are present
=> docs(accordion-item): update component description for vscode

packages/calcite-components-react/package.json, packages/calcite-components/package.json
**Related Issue:** #7625 
Adds the [project homepage](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#homepage) to our `calcite-components` and `calcite-components-react` packages.
Similar to the `@arcgis/core`'s page:
```json
"name": "@arcgis/core",
"version": "4.27.6",
"homepage": "https://js.arcgis.com",
"description": "ArcGIS Maps SDK for JavaScript: A complete 2D and 3D mapping and data visualization API",
```
=> docs: add homepage to npm packages

packages/calcite-components/src/components/shell/shell.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/7154
Doc copyediting for the `shell`'s new `"sheets"` slot.
=> docs(shell): update sheets slot position

packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-date-picker/util.spec.ts, packages/calcite-components/src/components/input-date-picker/utils.ts, packages/calcite-components/src/utils/date.spec.ts, packages/calcite-components/src/utils/date.ts
**Related Issue:** #7588
Normalizes year to current century. 
Ex: If the user types `01/01/20` the `value` will be corrected to `01/01/2020`
=> feat(input-date-picker): normalize year to current century

package-lock.json, packages/calcite-components/package.json
Updates `calcite-ui-icons` to `3.24.1`, released yesterday, 8/30, for the upcoming CC `1.7.0` release.
=> chore(deps): update calcite-ui-icons to 3.24.1

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #7627
- calciteListChange shouldn't be emitting when an item is disabled or closed.
=> fix(list): Stop emitting calciteListChange when a list-item is disabled or closed.

packages/calcite-components-react/src/auto-define.ts
**Related Issue:** #7575
CodeSandbox exposes `process`, which makes it look like NodeJS. The only way to determine it should be treated as the browser is the non-standard value they use for `process.platform`.
ref: https://nodejs.org/api/process.html#processplatform
=> fix: make sure components are defined in environments like in codesandbox

packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #7588 
This will normalize two digit year typed by user to current century. 
Ex: If the user types `01/01/20` the value will be corrected to `01/01/2020` when user focus out of the input field or press a `Enter` key.
=> feat(input-date-picker): normalize year to current century for user typed values only

CONTRIBUTING.md
This updates the URL to Stencil's contributing doc, which was moved to the root.
=> docs(contributing): update the commit message format example URL

packages/calcite-components/src/components/accordion-item/accordion-item.e2e.ts, packages/calcite-components/src/components/accordion-item/accordion-item.tsx, packages/calcite-components/src/components/accordion-item/resources.ts
**Related Issue:** #5553 
Updated HTML to improve a11y.
=> fix(accordion, accordion-item): improve a11y

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx
**Related Issue:** #6706
Add an `integer` property to `calcite-input-number` which prevents decimals and exponential notation.
=> feat(input-number): add integer property

packages/calcite-components/conventions/README.md, packages/calcite-components/src/components/flow/flow.e2e.ts, packages/calcite-components/src/components/flow/flow.tsx, packages/calcite-components/src/components/flow/interfaces.ts, packages/calcite-components/src/demos/flow.html
**Related Issue:** #6237 
This enables `flow` to work with custom components using shadow DOM wrapping `flow-item`. 
Custom components will have to implement the [`FlowItemLike`](https://github.com/Esri/calcite-design-system/pull/7608/files#diff-82c222ab365cde13a1f1288d936611519dfd9bee1e283164b260ca554c04a191R3-R7) interface and set the new `custom-item-selectors`/`customItemSelectors` attr/prop to target custom components (see [E2E test](https://github.com/Esri/calcite-design-system/pull/7608/files#diff-9b86e64de24dfca441533c63ae0f6834bff10bffbde23fd8bb3989a2259e356cR315-R387) for vanilla JS example).
**Note**: `customItemSelectors` is intentionally marked internal since we don't have any documentation yet on developing custom components, which this is meant to support. We could …
=> feat(flow): add support for custom flow-item elements

packages/calcite-components/src/utils/number.spec.ts, packages/calcite-components/src/utils/number.ts
Prevent error when pasting a string like `123test` into `calcite-input-number` and `calcite-input type="number`. The error was due to our sanitization logic, which splits on `e` for exponential notation and sanitizes each part. In the `123test` example, the rest of the letters after the `e` are sanitized causing a `reduce()` on nothing. On the other hand, `123fine` works fine because the `e` is at the end of the string so the falsy check kicks in before the `reduce()`. The fix uses `join()`, which doesn't throw errors on empty strings.
Sample: https://developers.arcgis.com/calcite-design-system/components/input-number/#sample
Steps:
1. Open the sample and paste `123test` into the input
2. Notice `test` isn't sanitized
3. Open the console and you'll see the following …
=> fix(input, input-number): correctly sanitize numbers when pasting string with 'e'

packages/calcite-components/src/assets/styles/_sortable.scss, packages/calcite-components/src/assets/styles/global.scss, packages/calcite-components/src/assets/styles/includes.scss, packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #7645
- Add styles for drag state classes
- This is a stop-gap style for the time being until a thorough design is complete
=> fix: add drag styles for improved UX

packages/calcite-components/src/components/block-section/block-section.e2e.ts, packages/calcite-components/src/components/block-section/block-section.scss, packages/calcite-components/src/components/block-section/block-section.tsx, packages/calcite-components/src/components/block-section/resources.ts, packages/calcite-components/src/components/block/block.e2e.ts, packages/calcite-components/src/components/block/block.tsx, packages/calcite-components/src/components/block/resources.ts
**Related Issue:** #5565 
Updated HTML to improve a11y.
**Note**: this removes references to outdated `TEXT` constants, which were used before translations were built-in.
=> fix(block, block-section): improve a11y

packages/calcite-components/src/components/block/block.tsx, packages/calcite-components/src/components/block/resources.ts
**Related Issue:** #5565
Prior to this proposed fix, NVDA and JAWS were only receiving context that the `block` was expanded or collapsed due to the `title` prop. 
Updates include:
- Adds an `aria-describedby` to provide context of the collapse/expansion in addition to the header (handled via the `id`)
- Adds the `"header"` `id` to the block's `resources.ts`
=> fix(block): provide textual name on collapse and expansion to AT

.github/scripts/limitPullRequestsForMaintenanceReleases.js
**Related Issue:** #7531
The action correctly determined that it was a maintenance milestone and [set the error message](https://github.com/Esri/calcite-design-system/actions/runs/5988880275/job/16244580547#step:3:39). However, it looks like [`core.setFailed()`](https://github.com/actions/toolkit/tree/main/packages/core#exit-codes) sets the exit code but doesn't actually exit. And then the else block with `process.exit(0)` overrode the exit code in the next iteration. Explicitly exiting will fix the issue.
=> ci: make sure to exit on maitenance milestone failure

packages/calcite-components/src/components/sheet/sheet.scss
Fixes shadow set on incorrect container in Sheet while in `display-mode="float"`, and updates to use the same shadow variable as Modal. Was only noticed when the scrim color was overridden to a lighter color. cc @driskull cc @SkyeSeitz 
Before:
After:
=> fix(sheet): Update shadow style in display-mode="float"

packages/calcite-components/src/components/table-cell/table-cell.scss, packages/calcite-components/src/components/table-header/table-header.scss, packages/calcite-components/src/components/table/table.stories.ts
Adds styles to allow long text in header or table cell to wrap. Adds story.
=> fix(table): Allow wrapping text in table-header and table-cell

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #7530
Leverages `combobox`'s new `single-persist` mode to avoid an error caused by deselecting an item.
=> fix(input-time-zone): prevent items from being deselected

packages/calcite-components/conventions/README.md, packages/calcite-components/src/components/flow/interfaces.ts
**Related Issue:** #7608 
Splits up interfaces for custom flow item class and elements. 
This also updates the conventions doc with info on interface usage.
=> feat(flow): split up custom flow item interfaces

packages/calcite-components/src/components/list-item/list-item.e2e.ts, packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #7676
- Enter key on any of the actions containers will not do anything
- So enter key will no longer be prevented
- Adds test
=> fix(list-item): Do not call preventDefault on enter key within slotted actions

packages/calcite-components/src/components/modal/modal.e2e.ts, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/demos/modal.html, packages/calcite-components/src/utils/openCloseComponent.ts
**Related Issue:** #7655
- Updates openCloseComponent helper to consider `opened` property for components that have it
- Update modal to emit correctly on close click
- Add test
- @jcfranco for risk consideration.
=> fix(modal): calciteModalClose should emit on close button click

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list/list.scss
**Related Issue:** #7599
- removes z-index on a container within the list component
=> fix(list): remove unnecessary z-index

packages/calcite-components/src/assets/styles/includes.scss
- Gives a component SCSS access to headless token vars.
- This is required to access breakpoint vars (`$breakpoint-width-xs`)
Example:
```scss
@container pagination (max-width: #{$breakpoint-width-xs}) {
// some styling here
}
```
=> chore: adds headless sass vars in includes for component usage.

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/tests/utils.ts, packages/calcite-components/src/utils/responsive.spec.ts, packages/calcite-components/src/utils/responsive.ts
**Related Issue:** #6670 
Adds support module for component responsiveness. 
* Spec test is skipped until the following JSDOM issues are addressed:
* https://github.com/jsdom/jsdom/issues/3563
* https://github.com/jsdom/jsdom/issues/2160.
* Moves existing custom matchers from the color-picker E2E test to the test utils module for reuse.
=> chore: add responsive module

packages/calcite-components/src/components/combobox-item-group/combobox-item-group.scss, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #6814 
This fixes an issue with the logic matching items to the internal filtered data. Filtered data corresponds to items, so both `label` and `value` need to match vs one or the other.
Also, hidden groups are visually hidden now. They were being displayed because the host was missing the base `hidden` styles.
=> fix(combobox): fix filtering to avoid showing unrelated items

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #2162 
Clears the user entered input on `blur` when `allowCustomValues` is set to `false`
=> fix(combobox): clears input value on blur

packages/calcite-components/.storybook/main.ts
chore: add spaces around link inside storybook notice
=> chore: add spaces around link inside storybook notice

packages/calcite-components/.eslintrc.cjs
Disables ESlint rule ["jsdoc/require-returns-type"](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-returns-type.md#readme) since we rely on TypeScript.
This builds upon https://github.com/Esri/calcite-design-system/pull/7326.
=> chore: disable eslint rule "jsdoc/require-returns-type"

packages/calcite-components/src/components/action-pad/usage/Tooltip.md, packages/calcite-components/src/components/action/action.tsx
**Related Issue:** #6374
Includes a doc cleanup 🧹  for our a-named components, which include:
- `action`: discovered the use for a `tooltip` slot, which wasn't documented, should it be? ❓ 
- `action-pad`: updates the tooltip use sample to the `"expand-tooltip"` slot
=> docs(action, action-pad): update usage and action's `tooltip` slot 

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #5689
- Fix keydown handler event to support dispatching events from any elements within the trigger slot
- Add test 
- Note: the codepen needs the slot changed from `dropdown-trigger` to `trigger`
- Note: the codepen needs the dispatched event to bubble.
=> fix(dropdown): support dispatching enter key event on dropdown trigger

packages/calcite-components/.eslintrc.cjs
**Related Issue:** #7747, #7326
Disable [`jsdoc/require-property-type`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-property-type.md) in favor of using Typescript.
=> ci(eslint): disable jsdoc/require-property-type

packages/calcite-components/src/components/block/usage/Always-open.md, packages/calcite-components/src/components/block/usage/Collapsible.md, packages/calcite-components/src/components/block/usage/Header-with-control.md, packages/calcite-components/src/components/block/usage/Header-with-icon.md, packages/calcite-components/src/components/button/usage/Within-form.md, packages/calcite-components/src/components/checkbox/usage/Hovered-with-calcite-label.md, packages/calcite-components/src/components/checkbox/usage/Indeterminate-with-native-label.md, packages/calcite-components/src/components/chip-group/usage/Basic.md, packages/calcite-components/src/components/chip-group/usage/SinglePersist.md, packages/calcite-components/src/components/combobox/usage/SinglePersist.md
**Related Issue:** #6374
Audits the b-named and c-named component usages.
Changes included:
- `block`: spelling change
- `button`: adds `type` to submit example
- `checkbox`: 
- remove hover use
- add `calcite-label` to use example
- `combobox`
- add `"single-persist"` `selectionMode`
=> docs(block, button, checkbox, combobox): update component use

packages/calcite-components/src/components/tab-nav/tab-nav.tsx, packages/calcite-components/src/components/tabs/tabs.stories.ts
**Related Issue:** #6821
- Updates offset position when tab icon is added
=> fix(tab-nav): update indicator position when tab icon changes

packages/calcite-components/src/components/action-group/action-group.scss, packages/calcite-components/src/components/action-group/action-group.stories.ts
**Related Issue:** #7380
- Adds `--calcite-action-group-gap` CSS variable to set the gap (gutters) between rows and columns when the `layout` property is `"grid"`.
- Adds `--calcite-action-group-padding` CSS variable to set the padding when the `layout` property is `"grid"`.
=> feat(action-group): add css custom properties to define gap and padding when layout is "grid"

packages/calcite-components/src/components/option/option.e2e.ts, packages/calcite-components/src/components/option/option.tsx, packages/calcite-components/src/components/select/select.e2e.ts
**Related Issue:** #4032
This fixes an issue where an empty string value was treated as value not set and would therefore fall back to the label as the value.
=> fix(select): allow setting an option value to an empty string

packages/calcite-components/src/components/date-picker/usage/Range.md, packages/calcite-components/src/components/dropdown/usage/Basic.md, packages/calcite-components/src/components/dropdown/usage/Disabling-close-on-select.md, packages/calcite-components/src/components/dropdown/usage/Groups.md, packages/calcite-components/src/components/fab/usage/Loading-and-disabled.md, packages/calcite-components/src/components/fab/usage/Styling.md, packages/calcite-components/src/components/fab/usage/With-text.md, packages/calcite-components/src/components/flow/usage/Basic.md, packages/calcite-components/src/components/flow/usage/Menu-actions-and-footer-actions.md, packages/calcite-components/src/components/icon/usage/Custom-icon-color.md, packages/calcite-components/src/components/inline-editable/usage/Basic.md, packages/calcite-components/src/components/inline-editable/usage/With-label.md, packages/calcite-components/src/components/inline-editable/usage/With-save-and-cancel-controls.md, packages/calcite-components/src/components/input-date-picker/usage/Basic.md, packages/calcite-components/src/components/input-date-picker/usage/Range.md, packages/calcite-components/src/components/input-message/usage/Basic.md, packages/calcite-components/src/components/input-number/usage/Basic.md, packages/calcite-components/src/components/input-number/usage/Integer.md, packages/calcite-components/src/components/input-text/usage/Basic.md, packages/calcite-components/src/components/input/usage/Basic.md, packages/calcite-components/src/components/input/usage/Clearable.md, packages/calcite-components/src/components/input/usage/Native-events.md, packages/calcite-components/src/components/input/usage/With-message.md
**Related Issue:** #6374 
Updates component usage examples for the following `d` through `i` named components:
- `date-picker`: 
- Showcase `range` types with the JS `value` prop.
- `dropdown`: 
- Update `selectionMode` value from `"multi"` to `"multiple"`
- Consistent usage samples
- `fab`: 
- Add description
- Adds new styling sample 
- `flow`
- Updates to doc site samples for more robust usage examples
- `icon`
- Showcase css var
- `inline-editable`
- Consistent usage samples
- `input`
- Various improvements across samples
- `input-date-picker`
- Update basic example for clarity
- Adds `range` example
- `input-message`
- Updates to doc site sample for a more robust usage example
- `input-number`
- Adds new samples including `integer` example
- `input-text`
- Adds new sample
=> docs: updates d thru i component usage examples

CONTRIBUTING.md
Updates our contributing doc in prep of Hacktoberfest 🎃🦇👻  
- Includes link to `good first issue` labels
- Updates context of design issues with the `ready for dev` label
- Adds context to "Stalled" milestone (removing "Backburner")
- Includes breaking change context, which should be communicated and coordinated in advance prior to submitting PRs
- Refactor and organize Visual snapshot section
- Adds Low risk issues and Maintenance releases section
cc @jcfranco @brittneytewks
=> docs(contributing): add context to prep for hacktoberfest contributions

packages/calcite-components/src/components/flow-item/flow-item.tsx, packages/calcite-components/src/components/flow/flow.e2e.ts, packages/calcite-components/src/components/flow/flow.tsx
**Related Issue:**#7869
- Supports the cancelling of the `calciteFlowItemBack` event via `preventDefault()`
- Changes event to be cancellable
- Adds test
=> feat(flow, flow-item): Allow calciteFlowItemBack event to be cancelled

package.json
Node v16 died on 9/11 (no that's not a distasteful joke): https://nodejs.dev/en/about/releases/
A variety of packages are dropping support, including ESLint. Bumping Volta's pinned version to v18 (the current LTS).
=> build: bump node to v18

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.scss, packages/calcite-components/src/components/action-menu/action-menu.stories.ts, packages/calcite-components/src/components/action-menu/action-menu.tsx
- Adds `appearance` property to `calcite-action-menu`.
- Allows menu to configure the default action's appearance
- Adds test
- Adds screenshot tests
=> feat(action-menu): Add appearance property to configure trigger appearance

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #7875
- Add more useful event details to `calciteListOrderChange` event
- Adds `oldIndex` and `newIndex` properties to the event detail
- Adds test
=> feat(list): add newIndex and oldIndex event details to calciteListOrderChange event

.renovaterc.json, package-lock.json, package.json
**Related Issue:** #7695
- Pin the Node types to v18.x.x so we don't get incorrect info
- Prevents Renovate from trying to update the Node types
- Bump NPM to the version that ships with Node v18
=> build(node): bump npm version and pin node types to v18

packages/calcite-components/src/components/tree-item/interfaces.ts, packages/calcite-components/src/components/tree-item/tree-item.scss, packages/calcite-components/src/components/tree-item/tree-item.tsx, packages/calcite-components/src/components/tree/tree.e2e.ts, packages/calcite-components/src/components/tree/tree.stories.ts, packages/calcite-components/src/components/tree/tree.tsx
**Related Issue:** #6971 
* toggle non-selectable parents when clicked w/o affecting selection (`multiple`, `none`, `single`, `single-persist`)
* update selection color & text weight (`children`, `multichildren`)
=> fix(tree): update tree selection per design spec

packages/calcite-components/src/components/tree-item/tree-item.tsx, packages/calcite-components/src/components/tree/tree.e2e.ts
**Related Issue:** #7898 
Fixes issue where selecting a child with the keyboard would collapse its parent and lose focus and mess up keyboard navigation.
=> fix(tree): fix tree keyboard selection issue

packages/calcite-components/src/components/tree/tree.e2e.ts, packages/calcite-components/src/components/tree/tree.tsx
**Related Issue:** #7909
`selectedItems` should no longer be updated when selection mode is `none`.
=> fix(tree): avoid modifying selected items for "none" selection-mode

.github/scripts/limitPullRequestsForMaintenanceReleases.js, .github/workflows/limit-prs-for-maintenance-releases.yml
Ensure the PR check that blocks installs if the current milestone is for maintenance doesn't think the milestone changed until after the release.
=> ci: the current milestone ends after release day

packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-number/input-number.stories.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.stories.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
**Related Issues:** #5723, #4276
Add `status` property to `calcite-input-date-picker` and `calcite-input-time-picker`. Validation messages will be added in a second pass to ensure consistency with the messages displayed for components with invalid values on form submission.
=> feat(input-date-picker, input-time-picker): add status property

packages/calcite-components/package.json
Adds a `util:clean-readmes` npm script for restoring the auto-generated component readmes. They are updated by some of our other NPM scripts like `docs:preview`. Unfortunately, they can't be easily restored automatically after npm scripts that are closed with CTRL-C because it ends the process. This adds an easy way for people to restore the component readmes until I have time to add a more automated option.
=> chore: add npm script for restoring changes to component readmes

package-lock.json, packages/calcite-components/package.json
v0.6.0 improves browser compatibility by targeting ES2020.
=> build(deps): bump timezone-groups

.github/ISSUE_TEMPLATE/research.yml, .github/ISSUE_TEMPLATE/test.yml
- Updates the test issue template to include the `needs milestone` label
- Replaces the `spike` issue in the research template (previously `research`)
cc @brittneytewks
=> chore: update issue template labels to support workflows

packages/calcite-components/src/components/panel/panel.tsx, packages/calcite-components/src/components/panel/resources.ts
**Related Issue:** #7930
- invert expand/collapse title attribute value.
- reverse icon direction.
=> fix(panel): fix collapse action title and reverse icon direction

package-lock.json, packages/calcite-components/package.json
Updates calcite-ui-icons to `3.24.7`, released yesterday, for the upcoming CC release.
=> chore(deps): update calcite-ui-icons to 3.24.7

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #7934 
Updates the component to consistently bail on blur handling logic if the input is blurred, but focus is still within the component.
* the regression was introduced by https://github.com/Esri/calcite-design-system/pull/7721/
* due to time constraints, testing will be tackled in a follow-up issue as it's not easy to reproduce in an E2E test.
=> fix(combobox): fix issue causing value to be cleared when selecting an item (Windows + trackpad)

packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #7944
This updates the component to remove cityless time zone entries in the `offset` mode and for unknown entries (either from browser differences or updated values) their city part will be displayed as is.
**Note**: due to time constraints, testing will be tackled in #7951.
=> fix(input-time-zone): fix handling of unknown and cityless time zones from offset display mode

packages/calcite-components/src/components/flow-item/flow-item.e2e.ts, packages/calcite-components/src/components/flow-item/flow-item.tsx
**Related Issue:** #7959
- Updates collapsed property when `calcitePanelToggle` event is fired.
- Add test
=> fix(flow-item): update collapsed property when collapse button is clicked

package-lock.json, packages/calcite-components/package.json
v0.7.0 fixes an issue causing certain time zones to be grouped incorrectly.
=> build: bump timezone-groups

packages/calcite-components/src/components/table/table.scss
**Related Issue:** #7892 
Updates the css rule to only display scrollbars in Windows when scrolling is occurring.
| Before | After  |
| ------------- | ------------- |
| <img width="600" alt="Screenshot 2023-10-09 at 10 06 40 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/867f58cd-c892-4e71-8364-36a253921f9b">| <img width="600" alt="Screenshot 2023-10-09 at 10 06 51 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/ed2eb94c-5721-4a61-9815-febbbc80b1e2"> |
Tested / screenshots taken through Windows VM.
=> fix(table): Improve scrollbar display

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #7944
Addresses an issue caused by time zone label index adjustment (from time zone group filtering) ended up as -1 and cause an error when using it as a lookup index.
This also adds missing tests from https://github.com/Esri/calcite-design-system/pull/7947/.
=> fix(input-time-zone): fix error caused by time zone group filtering

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/tests/commonTests.ts
**Related Issue:** #7951 
✨🧪✨
This also updates test helpers to accept additional test setup options.
=> test(input-time-zone): restore common tests

support/syncLinkedPackageVersions.ts
We don't want the design tokens version to be in sync with the CC version, that is just for the component wrapper packages.
=> ci: don't link design-token version to CC version

packages/calcite-components/src/components/stepper/stepper.e2e.ts, packages/calcite-components/src/components/stepper/stepper.stories.ts, packages/calcite-components/src/components/stepper/stepper.tsx
**Related Issue:** #7953 
Selects next enabled `calcite-stepper-item` when the first one is disabled.
=> fix(stepper): selects next enabled stepper-item when first one is disabled

packages/calcite-components/src/components/pagination/pagination.e2e.ts, packages/calcite-components/src/components/pagination/pagination.tsx
**Related Issue:** #2093 
Prevents console error messages when `page-size` is set to `0` via attribute or programmatically.
=> fix(pagination): prevents console error when page-size is set to zero

packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.scss, packages/calcite-components/src/components/input-time-picker/input-time-picker.stories.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #6889
Uses `getIconScale` to apply corresponding scale to internal chevron icon.
=> fix(input-date-picker, input-time-picker): adjust chevron scale accordingly

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/button/button.stories.ts, packages/calcite-components/src/components/fab/fab.stories.ts, packages/calcite-components/src/components/inline-editable/inline-editable.stories.ts, packages/calcite-components/src/components/split-button/split-button.stories.ts
=> fix(button, fab, inline-editable, split-button): prevent redundant opacity when button is both loading and disabled

packages/calcite-components/src/components/combobox/combobox.e2e.ts
**Related Issue:** #7955 
Adds missing test from #7934.
=> test(combobox): add test for filter being cleared if there's a delay between pointer down and up

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/utils/interactive.ts
**Related Issue:** #7335 
Drop "managed" as the `hostIsTabbable ` argument since the parent does not control its tabbability (`tabindex`).
This also adds info to `updateHostInteraction`'s doc.
=> fix(list-item): restore tabbability when an item's disabled prop is toggled

package-lock.json, package.json, packages/calcite-design-tokens/package.json, packages/calcite-design-tokens/support/token-transformer/format/javascript.ts, packages/calcite-design-tokens/support/token-transformer/sd-run.ts
**Related Issue:** #7986
Adds two new platforms and four formats to design-token exports.
The "js" platform creates a javascript object of the design-tokens and a typescript types declaration file representing that object. This format is necessary for documentation.
```js
export default {
core: {
breakpoint: {
width: {
xxs: {
value: "320px",
type: "sizing",
description: "Small handheld devices and mini-windows",
filePath: "src/core.json",
isSource: true,
original: {
value: "320px",
type: "sizing",
description: "Small handheld devices and mini-windows",
},
name: "xxs",
attributes: {},
path: ["core", "breakpoint", "width", "xxs"],
},
xs: {
```
```typescript
declare const root: RootObject
export default root
interface RootObject {
core: Core;
semantic: Semantic;
}
interface Core {
font: …
```
=> feat: add js platform formats to calcite-design-tokens

CONTRIBUTING.md, package.json, packages/calcite-components/package.json
Trying to build the Calcite Design System packages with node 16 fails. It requires at least node 18.
=> chore: align expected node engine with volta

packages/calcite-design-tokens/src/core.json
Different platforms need to target breakpoints in different ways. It might be easier to be explicit about min vs max breakpoint sizes. This is not a breaking change as it retains the existing “breakpoint-width-“ tokens for the time being but does mark them for deprecation.
=> feat: reorganize breakpoints 

packages/calcite-components/src/utils/responsive.spec.ts, packages/calcite-components/src/utils/responsive.ts, support/dictionaries/dict-calcite-design-system.txt
**Related Issue:** #7856
Updates `breakpoints` lookup object to include `xxs` (added in https://github.com/Esri/calcite-design-system/pull/7992).
=> chore(responsive): add xxs breakpoint prop

packages/calcite-components/src/components/navigation-logo/navigation-logo.scss, packages/calcite-components/src/components/navigation-logo/navigation-logo.stories.ts, packages/calcite-components/src/components/navigation-logo/navigation-logo.tsx, packages/calcite-components/src/components/navigation-logo/resources.ts, packages/calcite-components/src/demos/navigation.html
**Related Issue:** #7124 
Adds `icon` and `iconFlipRtl` properties to `calcite-navigation-logo`. Because `calcite-navigation` and related components are offered in one scale, this unique `icon` case will use `scale="l"` due to the prominence and usage of the component, and to ensure `icon` adjacent to `thumbnail` are presented at equal sizes:
=> feat(navigation-logo): Adds `icon` and `iconFlipRtl` properties

packages/calcite-components/src/components/functional/XButton.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/7765
Finalizes up the above issue by tackling the `XButton.tsx` (functional component) discussed in https://github.com/Esri/calcite-design-system/issues/7765#issuecomment-1779672451 and https://github.com/Esri/calcite-design-system/issues/7765#issuecomment-1779748973.
cc: @jcfranco and related PR #7973
=> refactor(xbutton): extract icon scale from utility function

CONTRIBUTING.md
Adds new design estimate label context to our `contributing.md` for the following labels:
- `estimate - design - sm`
- `estimate - design - md`
- `estimate - design - lg`
Also includes the following updates:
- Groups development labels into its own section (Development estimates), and
- Updates the word "work" to "effort"
cc @brittneytewks
=> docs(contributing): add design estimates

packages/calcite-components/src/components/combobox-item/combobox-item.tsx, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #2162 
Clears input value on `blur` if the value has no matching `combobox-item` when `allowCustomValue` property is set to `false`
=> fix(combobox): clear custom input value on blur

packages/calcite-components/src/components/filter/filter.tsx
**Related Issue:** #5626
- Correctly set the label for the filter component
=> fix(filter): corrects the accessible label

packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/combobox/combobox.stories.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8067
Uses `getIconScale` util to set proper scale for placeholder and chevron icons.
=> fix(combobox): ensure icon scales are consistent

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
Fails on unrelated PR: #7605 
Looks like it's DST-related, as London is used in E2E tests and it had a DST adjustment on 10/2 per @jcfranco
🫤 🤔 🤨 🧐
=> test: skip unstable tests

packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts
**Related Issue:** #8086 
✨📸🧪🔨✨
=> test(input-time-zone): update screenshot tests to use time zones unaffected by DST

CONTRIBUTING.md
- Refactors section on how contributors can help, as a few items have surfaced during Hacktoberfest 🎃👻🦇 contributions 
- Issues
- Dev work
- Resources 
- Adds more context on why contributors should comment on issues (so we can assign issues to them)
- Updates the jsbin url to reflect the latest versions (linked the same in our bug issue template)
- Small copyedits
- Adds conventional commit example and link to our recent commits for additional examples for folks to reference
=> docs(contributing): add supporting context for new contributors

.github/scripts/notifyWhenSpikeComplete.js, .github/workflows/spike-complete.yml
Adds automation when developers complete research spikes associated with the `spike` label.
How it works:
1. The developer adds the `spike complete` label
2. The script runs, and:
- The `spike` label is removed
- If present, the `1 - assigned` label is removed
- Adds the `0 - new` and `needs milestone` labels
- All assignees are removed and the milestone is cleared
- Calcite PMs are notified (currently set to @brittneytewks and myself) to add to an upcoming milestone
- Also discoverable via the `needs milestone` label
=> ci: automate research spike issue completion

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts
**Related Issue:** #8086
Updates skipped test to use time zones that are unaffected by DST.
✨🧪🔨✨
=> test(input-time-zone): restore skipped tests

packages/calcite-components/src/components/combobox-item/combobox-item.tsx
cc @BrunoCaimar
---
**Related Issue:** #7719 
Do not show the icon if the combobox-item is disabled.
=> fix(combobox-item): hide disabled item icon

.renovaterc.json
**Related Issue:** #8102
We don't want to pin peer deps, because our users should be allowed to update the version of packages they use in their app w/o throwing errors due to calcite. Also, increasing the frequency of renovate updates to ensure we don't fall behind.
=> ci(renovate): run on weekdays and don't pin peerDeps

packages/calcite-components/src/components/block-section/block-section.scss, packages/calcite-components/src/components/block-section/block-section.tsx, packages/calcite-components/src/components/block/block.stories.ts
**Related Issue:** #7698 
Wraps long text to a new line when `toggle-display='switch'`
=> fix(block-section): wraps long text over to a new line when toggle switch is displayed

packages/calcite-components/src/components/card/assets/card/t9n/messages.json, packages/calcite-components/src/components/card/assets/card/t9n/messages_en.json, packages/calcite-components/support/generateT9nDocsJSON.ts
**Related Issue:** #6660
BREAKING CHANGE: Removed the `deselect` message property – this property was deprecated in #6657 as it is no longer being rendered.
=> refactor(card)!: remove deprecated `deselected` message

.github/scripts/notifyWhenSpikeComplete.js
Tries to remove the `2 - in development` lifecycle label, if present on the issue when completing a spike to properly clear all the labels. cc: @jcfranco 
Refer to https://github.com/Esri/calcite-design-system/issues/7692#issuecomment-1797088523 and https://github.com/Esri/calcite-design-system/issues/7692#issuecomment-1797802671 for additional context.
=> ci: update spike complete automation to try removing dev lifecycle label

packages/calcite-components/src/components/split-button/resources.ts, packages/calcite-components/src/components/split-button/split-button.e2e.ts, packages/calcite-components/src/components/split-button/split-button.scss, packages/calcite-components/src/components/split-button/split-button.stories.ts, packages/calcite-components/src/components/split-button/split-button.tsx
**Related Issue:** #7692
This fixes an issue where styles related to `width` were being applied internally and had no impact on the component.
=> fix(split-button): fix width layout

packages/eslint-plugin-calcite-components/README.md, packages/eslint-plugin-calcite-components/docs/enforce-ref-last-prop.md, packages/eslint-plugin-calcite-components/src/rules/enforce-ref-last-prop.ts
**Related Issue:** #7669, #7659
Refactor to improve on `enforce-ref-last-prop` ESLint rule docs.
=> refactor: improve on enforce-ref-last-prop ESLint rule docs

package-lock.json, packages/calcite-components-angular/projects/component-library/package.json
**Related Issue:** #7860
Angular has an unusual workflow where you need to `cd` into the library's `dist` directory and run `npm publish` from there. I found related Lerna issues that culminated in the ability to publish a particular package from a different directory. This is the doc I found for the config option:
https://github.com/lerna/lerna/tree/main/libs/commands/publish#publishconfigdirectory
Unfortunately, it didn't end up working, so `v1.10.1-next.3` of the angular wrapper is broken. I'm not aware of a way to test the results of `lerna publish` without actually publishing.
I ended up copying the config from the `arcgis-web-components` repo's angular wrapper once I remembered they use Lerna.
=> fix(angular): publish from the dist directory

package-lock.json, packages/calcite-components/package.json, packages/calcite-components/src/utils/form.tsx
=> chore: drop form-request-submit-polyfill as Safari 16 supports it

packages/calcite-components/src/components/alert/alert.tsx, packages/calcite-components/src/components/pagination/pagination.tsx, packages/calcite-components/src/utils/responsive.spec.ts, packages/calcite-components/src/utils/responsive.ts, packages/calcite-components/stencil.config.ts
Stems from https://github.com/Esri/calcite-design-system/pull/8041#discussion_r1370773208. 
This changes how breakpoints are built and used (`responsive` module):
* uses design tokens JS output target to reference breakpoint values
* prevents possible disconnect between stylesheet and conditional rendering breakpoint values (only the latter could be overridden via CSS props)
* the breakpoints lookup object no longer needs to be obtained asynchronously
This also updates and unskips the `responsive` spec test.
**Note**: this includes an update to the testing Jest config to apply Stencil's transformer to the design token's headless ESM file as the default one was not transforming properly and leading to `Jest encountered an unexpected token` errors when running the …
=> refactor(responsive): use JS module to create breakpoints lookup object

packages/calcite-components/src/components/flow-item/flow-item.scss, packages/calcite-components/src/components/panel/panel.scss, packages/calcite-components/src/demos/flow-and-panel-action-menu-overflow.html
**Related Issue:** #8028
Attempt to fix the clipping of action-menu in Panel and FlowItem.
This draft adds a test demo to approximate one of the use cases where the issue is appearing.
I could use some help testing if this update breaks other stuff.
cc @geospatialem
=> fix(panel, flow-item): remove overflow rule

package-lock.json, packages/calcite-components-angular/projects/component-library/README.md, packages/calcite-components-angular/projects/component-library/ng-package.json, packages/calcite-components-angular/projects/component-library/package.json
Changes calcite-components to a dependency of the angular wrapper, versus a peerDep and devDep. 
Stencil has it as a peerDep because it is required for the user. arcgis-web-components and us added it as a devDep so the monorepo dependency tree would catch it.
Putting it as a dep resolves both of the above, and it prevents the user from needing to install it on their end. It seems like lerna doesn't bump the peerDep when versioning local packages so it falls behind, which causes issues.
Note: we did the same thing for the react wrapper for convenience, even before we moved it to the monorepo
=> build(angular): chage calcite-components to a dep from peerDep/devDep

.github/workflows/deploy-next.yml
We have consistent timeout test failures on `main`, which is preventing `next` deployments. Strangely, the tests are passing on the PR check and locally. I'm not sure what's going on and it's hard to troubleshoot because it only occurs in the CI. 
I'm adding a "supposedly" redundant build to the next deployment workflow to align with the passing e2e PR check:
https://github.com/Esri/calcite-design-system/blob/01288a3575e1388c49f0fe6b66d863306b3f8c06/.github/workflows/pr-e2e.yml#L32
I must have forgotten to remove the extra build in the PR check when I set up the monorepo. It shouldn't be required because we have turbo set up to build before testing:
https://github.com/Esri/calcite-design-system/blob/01288a3575e1388c49f0fe6b66d863306b3f8c06/turbo.json#L13-L15
This shouldn't add additional …
=> ci(next): attempt to fix tests by copying steps in passing pr check

packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts
**Related Issue:** #6678
This removes unnecessary sizing applied to the date-picker's wrapper which displayed an artifact when configuring the `input-date-picker` with `scale=l` and `range`.
=> fix(input-date-picker): fix date-picker wrapper displaying beyond its bounds

packages/calcite-components/src/components/checkbox/checkbox.tsx
Related issue: #8182
The `label` property was unintentionally marked as internal.
=> fix(checkbox): make label property public

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list/list.stories.ts, packages/calcite-components/src/components/stack/stack.scss, packages/calcite-components/src/components/stack/stack.stories.ts
**Related Issue:** #8187
- Adds css to stack and list-item to treat an action-menu the same as an action
- This makes the action take up the full height of the list-item/stack
- Previously, the action-menu would stop at 32x32 pixels.
=> fix(list-item, stack): stretch action-menu and handle when placed inside a list-item or stack.

packages/calcite-components/src/components/action/action.scss, packages/calcite-components/src/components/action/action.stories.ts, packages/calcite-components/src/components/action/action.tsx, packages/calcite-components/src/components/action/resources.ts, packages/calcite-components/src/demos/action.html
**Related Issue:** #6879 
Ensures extra space is not added to an action. 
This is solved by:
When an icon is present, the indicator will always be appended to the bottom right. This ensures it remains in the same place whether a parent Action Bar is expanded, or not. The indicator moved a couple of px away - in the future I think we can improve this with a border or clipped ring around the indicator to prevent overlap. 
Also resolves https://github.com/Esri/calcite-design-system/issues/5860, for icon-only uses.
When an icon is not present, the indicator will be positioned adjacent to the text container.
| Before  | After |
| ------------- | ------------- |
| <img width="500" alt="Screenshot 2023-11-15 at 5 00 35 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/ae4d202b …
=> fix(action): Ensure action content is correctly spaced

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list-item/resources.ts, packages/calcite-components/src/components/list/list.stories.ts
**Related Issue:** #8173
- This is a good starting point. We just need input from design. cc @macandcheese 
- Adds a new slot `content-bottom`. Could also be called `content-block-end`?
- `content-bottom` is indented the same as the item.
- screenshot tests
=> feat(list-item): Add content-bottom slot for placing content below the label and description of the component

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list/list.stories.ts, packages/calcite-components/src/components/stack/stack.scss, packages/calcite-components/src/components/stack/stack.stories.ts
**Related Issue:** #8185
- stretch dropdown component in list-item and stack
=> fix(list-item, stack): stretch dropdown when placed inside a list-item or stack

packages/calcite-components/calcite-preset.ts, packages/calcite-components/src/components/list-item-group/list-item-group.scss, packages/calcite-components/src/components/list/list.scss, packages/calcite-components/src/components/list/list.stories.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #7546 
Adds border to the `calcite-list-item` excluding the first `calcite-list-item` in the `calcite-list-item-group` or the `calcite-list`.
=> fix(list-item): adds border between grouped and ungrouped list-items

.github/workflows/pr-e2e.yml, packages/calcite-components/stencil.config.ts, turbo.json
**Related Issue:** #8179
Fixes a few test run failures on `rc`:
- a module import issue, see #8201 (thanks  @jcfranco :rocket:)
- remove the `build` prerequisite from turbo's `test` pipeline, which was causing concurrency issues
=> chore(jest, turbo): resolve test run failures

packages/calcite-components/conventions/README.md
Old URL is leading to a 404 page.
I found the new URL for the same page.
=> docs: update outdated Web Component conventions link

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx
**Related Issue:** #7188 
Prevents increasing/decreasing the value in `calcite-input-number` on `blur` via keyboard or mouse
=> fix(input-number): prevents mutating value on blur

packages/calcite-components/src/components/list-item/list-item.tsx
@jcfranco I'm running into an issue where once I drag a list-item that has children, the caret icon disappears.
I can't reproduce it with just calcite. Do you think this might fix it?
=> fix(list-item): fix rendering of open icon.

package-lock.json, packages/calcite-components-angular/projects/component-library/package.json, packages/calcite-components-react/package.json, packages/calcite-components/package.json
**Related Issue:** #8232
Downgrade the versions in `package.json` files to ensure the release goes out as 1x
=> chore: downgrade packages after reverting 2.0.0-next.0 change

packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #8243 
Prevents increasing/decreasing the value in `<calcite-input type="number" />` on `blur` using `Tab`
=> fix(input): prevents mutating value on `blur` when `type="number"`

packages/calcite-components/src/assets/styles/_sortable.scss, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx, packages/calcite-components/src/utils/floating-ui.spec.ts, packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #8214 #7979
- Update some component `open` handlers to call reposition before open and after open
- Previously, they were just calling when open was set to true.
- Update `floating-ui` utility
- Handle device pixel ratio: https://floating-ui.com/docs/misc#subpixel-and-accelerated-positioning 
- Only set `top`, `left`, and `transform` when the component is open.
- This makes it so that the positioned container is never going to "fly in" from anywhere. 
- Update sortable styles to hide any overflow on dragged elements.
=> fix: dragging floating ui components

packages/calcite-components/src/components/color-picker/color-picker.tsx, packages/calcite-components/src/components/popover/PopoverManager.ts, packages/calcite-components/src/components/shell-panel/shell-panel.tsx, packages/calcite-components/src/components/slider/slider.tsx, packages/calcite-components/src/components/tooltip/TooltipManager.ts
**Related Issue:** #8156
- Sets up global event listeners on the window instead of the document.
- This is because the events should continue to work beyond the document in cases where an iframe is being used.
- We want to continue to listen to these events for the entire window.
=> fix(color-picker, popover, shell-panel, slider, tooltip): Register events on the window instead of the document

packages/calcite-components/src/components/modal/modal.scss, packages/calcite-components/src/components/modal/modal.stories.ts, packages/calcite-components/src/components/modal/modal.tsx, packages/calcite-components/src/demos/modal.html
**Related Issue:** #8250 
BREAKING CHANGE: For consistency, renames `width` property to `widthScale`.
=> refactor(modal)!: rename `width` property to `widthScale`

packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.scss, packages/calcite-components/src/components/dropdown/dropdown.stories.ts
**Related Issue:** #5903
BREAKING CHANGE: Dropdown's default `display` was changed from `inline-flex` to `inline-block` to make it easier to prompt truncation in trigger button text with minimal impact to layout (by setting an explicit width **or** setting `width: 100%` or `display: block` on the dropdown of a width-constrained parent).
=> fix(dropdown)!: change display to inline-block to ease truncation setup

packages/calcite-components/src/components/list/list.scss, packages/calcite-components/src/components/list/list.stories.ts
**Related Issue:** #7546 
Adds border between last `calcite-list-item` in a `calcite-list-item-group` and next slotted `calcite-list-item`.
=> fix(list-item): adds border between last item in a group and slotted item

packages/calcite-components/src/components/alert/alert.scss
Removes responsiveness-related declaration no longer necessary after https://github.com/Esri/calcite-design-system/pull/8195/.
=> refactor(alert): remove unnecessary CSS declaration

packages/calcite-components/src/components/action-menu/action-menu.scss, packages/calcite-components/src/components/action-menu/action-menu.stories.ts
**Related Issue:** #8274
- Sets max-height on action-menu and applies overflow if necessary
- Adds screenshot test
=> feat(action-menu): set max height of the action menu

packages/calcite-components/src/components/stepper/stepper.scss
Cherry pick fix from https://github.com/Esri/calcite-design-system/pull/8254.
=> fix(stepper): typo in CSS variable for step bar's fill

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/button/button.tsx, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/pick-list/pick-list.e2e.ts, packages/calcite-components/src/components/pick-list/shared-list-render.tsx, packages/calcite-components/src/components/pick-list/shared-list-tests.ts, packages/calcite-components/src/components/value-list/value-list.e2e.ts
**Related Issue:** #7590
This updates some components to avoid setting `disabled` on internal, supporting components when `loading` was set to true.
BREAKING CHANGE: Setting `loading` prop to true no longer prevents interaction nor applies disabled styles. If you'd like to block interaction when loading, please set `disabled` along with `loading`.
=> fix(button, list, pick-list, value-list)!: prevent loading prop from affecting interactivity

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/utils/dom.ts
**Related Issue:** #7974
- Focuses on the first tabbable element inside the grid cell when using arrow keys.
- Excludes hidden cells from the arrow key logic
- Adds dom utility `getFirstTabbable` to get first focusable element from within an element.
=> fix(list-item): focus on the first focusable element within the component when using arrow keys

packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx
**Related Issue:** #6121
- When a component is moved (via drag and drop or whatever), we need to reconnect floating UI (connectFloatingUI).
- This is needed because it sets up autoUpdating of the reference element so that the reference element is tracked and positioned properly
- Currently, when an a component is moved, this tracking is lost because we were only calling `connectFloatingUI` when the reference element and floating element were created.
- This PR makes sure that we reestablish the floating UI autoUpdate when the component itself is moved.
=> fix(combobox, dropdown, input-date-picker, popover, tooltip): fix positioning of component when component is moved

packages/calcite-components/src/utils/focusTrapComponent.spec.ts, packages/calcite-components/src/utils/globalAttributes.spec.ts
Resolves some JSDOM type errors that were causing issues with `npm start`. I wouldn't normally use `any`, but it's to fix types for a hack in spec tests. Here are the error messages that appeared in `npm start`:
```
[ ERROR ]  TypeScript: ./src/utils/focusTrapComponent.spec.ts:71:7
Type 'DOMWindow' is not assignable to type 'Window & typeof globalThis'.
L70:  const { window: win } = new JSDOM();
L71:  window = win; // make window references use JSDOM
L72:  globalThis.MutationObserver = window.MutationObserver; // needed for focus-trap
[ ERROR ]  TypeScript: ./src/utils/globalAttributes.spec.ts:16:5
Type 'DOMWindow' is not assignable to type 'Window & typeof globalThis'.Type 'DOMWindow' is not assignable
to type 'Window'.Types of property 'self' are incompatible.Type 'DOMWindow' is not …
```
=> test(spec): resolve jsdom type errors

packages/calcite-components/src/components/shell-panel/shell-panel.tsx
**Related Issue:** #8286 
Updated the description of the `heightScale` property for `Shell Panel` to correctly reflect the actual behavior.
=> docs(shell-panel): remove incorrect information from heightScale prop

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #8007
This addresses an issue where `input-time-zone` was recreating time zone groups when related props were modified, but these were not affecting state, so the items would remain unchanged.
=> fix(input-time-zone): update time zone items when item-dependent props change

packages/calcite-components/src/components/checkbox/checkbox.scss, packages/calcite-components/src/components/checkbox/checkbox.stories.ts, packages/calcite-components/src/components/checkbox/checkbox.tsx, packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/combobox/combobox.stories.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/input-text/input-text.stories.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx, packages/calcite-components/src/components/select/select.scss, packages/calcite-components/src/components/select/select.stories.ts, packages/calcite-components/src/components/select/select.tsx, packages/calcite-components/src/components/text-area/text-area.scss, packages/calcite-components/src/components/text-area/text-area.stories.ts, packages/calcite-components/src/components/text-area/text-area.tsx, packages/calcite-components/src/demos/checkbox.html
**Related Issue:** #8057 #3406
Add the `status` property to additional form components in preparation of adding internal input messages for validation. I split these changes out from #8305, which is where the new stories are.
=> feat(combobox, checkbox, input-time-zone, select, text-area): add status property

packages/calcite-components/src/components/modal/modal.tsx
**Related Issue:** #8250
Updates the `modal`'s `fullscreen` prop context to the updated `widthScale` prop (previously named `scale`).
=> docs(modal): update fullscreen context to updated widthScale prop

packages/calcite-design-tokens/src/$config.ts, packages/calcite-design-tokens/support/token-transformer/registerCalciteTransformers.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/formatter/docs.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/formatter/utils.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/formatter/utils/formatExtraOutput.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/attributes/attributePlatformName.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/name/nameSet.spec.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/name/nameSet.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/utils.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/utils/setTokenNameByPlatform.ts, packages/calcite-design-tokens/support/types/fileExtensions.ts, packages/calcite-design-tokens/support/types/platform.ts
**Related Issue:** #8287
This changes the new format "json" to "docs" to better capture where this platform output should be used. This replaces the folder "json" with "docs".
=> feat: update json shape for docs

packages/calcite-components/src/components/label/label.tsx, packages/calcite-components/src/tests/commonTests.ts, packages/calcite-components/src/utils/component.spec.ts, packages/calcite-components/src/utils/component.ts, packages/calcite-components/src/utils/label.ts
**Related Issue:** #7364 
This allows `label` to find its corresponding labelable when `for` is dynamically set after the label and labelable have gone through the label matching process that happens when they are connected to the DOM.
=> fix(label): associate label to component when `for` prop is set after initialization

.github/workflows/deploy-latest.yml
Update the deploy-latest workflow to use the Node version pinned by volta to prevent build errors:
https://github.com/Esri/calcite-design-system/actions/runs/7067688502/job/19241371459#step:5:691
Pushing this through so I can release, cc @jcfranco
=> ci(deploy-latest): use volta's pinned node version

.github/workflows/deploy-latest.yml
We got a [new error](https://github.com/Esri/calcite-design-system/actions/runs/7067782508/job/19241570336#step:4:9) in the `deploy-latest` workflow. Not sure why it can't find `package.json`, considering I copied that directly from `deploy-next`:
https://github.com/Esri/calcite-design-system/blob/acd95305cd4143580f695f11036e91f47174efa6/.github/workflows/deploy-next.yml#L18-L23
Hardcoding the version for now so we can release. Pushing this one through too, cc @jcfranco
=> ci(deploy-latest): hardcode node v18

packages/calcite-components/src/components/dropdown-item/dropdown-item.e2e.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.scss, packages/calcite-components/src/components/dropdown-item/dropdown-item.tsx, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.stories.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #6667
This allows disabling dropdown items.
=> feat(dropdown-item): add disabled support

package-lock.json, package.json, packages/calcite-design-tokens/support/tests/__snapshots__/index.spec.ts.snap, packages/calcite-design-tokens/support/token-transformer/registerCalciteTransformers.ts, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/value/valueCheckEvaluateMath.ts
**Related Issue:** #8146
Resolves issues with https://github.com/Esri/calcite-design-system/pull/8146
- sd-transformer changed the default comment style for es6 output
- sd-transformer added a new line at the end of es6 output tokens
=> chore: update token transformer to align with sd-transforms@0.12.1

packages/calcite-components/src/demos/_assets/demos.css, packages/calcite-components/src/demos/list.html
Rename outdated CSS Variables that we missed during the token renames. I used my handy, new [`@ben-elan/calcite-codemod`](https://www.npmjs.com/package/@ben-elan/calcite-codemod) package :rocket:
=> chore(demos): update outdated CSS variable names after token breaking changes

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.tsx
**Related Issue:** #7445
- Set autoClose on internal popover
- Remove event listener on window
- Listen for popover close to set `open` property to false.
- Updates existing test. (Already a test to ensure closure of menu when clicking outside)
=> fix(action-menu):  fix closing action menu after a drag occurs

packages/calcite-components/src/components/dropdown/dropdown.tsx
Cleans up some code that relies on a custom `dropdown-item` attribute (`islink`) that was removed in https://github.com/Esri/calcite-design-system/pull/2106/files#diff-a41ea470fa36ce6cabf5f622a56904c6bbd308964030313c2962a0afe6c19517L172.
=> refactor(dropdown): remove obsolete logic

packages/calcite-design-tokens/support/token-transformer/styleDictionary/formatter/utils/formatExtraOutput.ts
**Related Issue:** #8343
Resolves bug where the @media query, which applied light and dark color-context tokens on prefers-color-scheme in CSS, was applied at `:root` instead of `.calcite-mode-auto`
=> fix(color-context tokens): only apply when `.calcite-mode-auto` is applied

packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #7218 
`calcite-input-date-picker` no longer emits `calciteInputDatePickerChange` event twice when `valueAsDate` is parsed and user changes the date.
=> fix(input-date-picker): no longer emits redundant change event

.github/workflows/deploy-next.yml
**Related Issue:** #8325
Resolves [an error](https://github.com/Esri/calcite-design-system/actions/runs/7132693857/job/19423776955#step:4:39) in the `next` deployment CI, which was trying to use `ts-node` before it was installed.
The issue was introduced in the PR linked above, which was fixing a [different error](https://github.com/Esri/calcite-design-system/actions/runs/7119908955/job/19386029658#step:5:545) in the `next` deployment CI.
=> ci(next): install deps before running npm scripts

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/sortable-list/sortable-list.tsx, packages/calcite-components/src/components/value-list/value-list.tsx, packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #8367
- Adds event `calciteListDragEnd` to `list`
- Adds event `calciteListDragStart` to `list`
- Refactors global drag event name in `SortableComponent`.
- Adds test
=> feat(list): Add `calciteListDragStart` and `calciteListDragEnd` events for when a drag starts and ends.

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.tsx
**Related Issue:** #7445
- Keep open property in sync with open property of internal popover
- Update menu button element when connectedCallback occurs.
- Add test
=> fix(action-menu): keep internal popover open property in sync

packages/calcite-components/src/components/tab/tab.scss, packages/calcite-components/src/components/tabs/tabs.stories.ts
**Related Issue:** #8139 
This PR fixes an issue where applying a fixed CSS height on the `calcite-tabs` element or using tabs inside a shell panel caused child `tab`s to sometimes show a vertical scrollbar.
=> fix(tab): prevent vertical scrollbar on content pane when the height of outer elements are specified

packages/calcite-components/src/components/dropdown-item/dropdown-item.scss
**Related Issue:** #6667
This addresses pseudo-element selectors kicking in due to the `disabled` component style mixin not affecting `pointer-events` on the host (by design).
* Screenshot tests were not updated as our current setup does not allow us to test for pseudo-elements. Something like https://storybook.js.org/addons/storybook-addon-pseudo-states or https://www.chromatic.com/docs/interactions/ might help with this in the future.
* Related styles using `:before` were removed as they do not appear to be in use (will submit a follow-up clean up PR afterwards).
=> fix(dropdown-item): avoid hover/active styling when disabled

packages/calcite-components/src/components/dropdown-item/dropdown-item.scss
Existing selectors using `::before` are not targeting pseudo-elements due to missing `content`.
=> chore(dropdown-item): remove non-applicable selectors due to lack of visual `::before` pseudo-element

packages/calcite-components/src/assets/styles/_sortable.scss, packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx, packages/calcite-components/src/tests/commonTests.ts, packages/calcite-components/src/utils/floating-ui.spec.ts, packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #7979 #8214 #8386 #8419 #5697
- reverts #8001
- Keeps doc updates 
- reverts partially #8230
- Keeps drag classes that are setting `overflow:hidden` when a drag is occurring.
- Keeps roundByDPR floating-ui fix. https://floating-ui.com/docs/misc#subpixel-and-accelerated-positioning
- Hides overflow for `calcite-sortable--chosen` class
- Only sets `top` and `left` on floating element once positioned. **This fixes native drag and drop issue**
=> fix(floating-ui): improve floating element performance

packages/calcite-components/package.json
**Related Issue:** #8421 
Ensure the build used for `next` releases includes patches. This fixes a regression caused by #8325, where we removed the extra build on prepublish. The extra build was fixing some issues caused by `npm run test:prerender`, where a build occurred that didn't run pre/post build scripts, including the ESM resolution patch added in #5145.
=> build: ensure patches run after prerender test build

packages/calcite-components/src/components/avatar/avatar.e2e.ts
- removes references to placekitten in tests
- replaces with svg local image
=> test(avatar): Fix placeholder image url.

packages/calcite-components/src/components/stepper/stepper.e2e.ts, packages/calcite-components/src/components/stepper/stepper.tsx
**Related Issue:** #8397 
Emits `calciteStepperItemChange` event when switched to the first enabled step in single view layout.
=> fix(stepper): emits `calciteStepperItemChange` event when switched to first step

packages/calcite-components/src/components/list/usage/Advanced.md, packages/calcite-components/src/components/stack/readme.md, packages/calcite-components/src/components/stack/usage/Basic.md, packages/calcite-components/src/components/stack/usage/Disabled.md, packages/calcite-components/src/components/tabs/usage/Basic.md, packages/calcite-components/src/components/tabs/usage/Bordered.md, packages/calcite-components/src/components/tip-manager/usage/Basic.md, packages/calcite-components/src/components/tip/usage/Basic.md
- removes references to placekitten in markdown files.
=> docs: use example image instead of live url.

packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-date-picker/resources.ts
**Related Issue:** #6501 
This fixes an issue where the start/end picker would not update after being toggled and displayed on the toggled side.
=> fix(input-date-picker): ensure range input toggling is consistent

packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #8437
- Adds drag event details to `calciteListDragStart` and `calciteListDragEnd` events.
- Adds test
=> feat(list): Add drag event details to `calciteListDragStart` and `calciteListDragEnd` events

packages/calcite-components/src/components/table-cell/table-cell.scss, packages/calcite-components/src/components/table/table.stories.ts
**Related Issue:** #8380 
Fixes a typo that caused this variable not to work, and removes an unused border variable from the initial Table PR that snuck through.
=> fix(table-cell): Fix background css variable

packages/calcite-components/src/components/table/interfaces.ts, packages/calcite-components/src/components/table/resources.ts, packages/calcite-components/src/components/table/table.e2e.ts, packages/calcite-components/src/components/table/table.scss, packages/calcite-components/src/components/table/table.stories.ts, packages/calcite-components/src/components/table/table.tsx, packages/calcite-components/src/demos/table.html
**Related Issue:** #7906 
Updates nomenclature for this Table property, and adds Chromatic test for the deprecated property. Also removes a related, but unused type definition.
=> refactor(table): Add `striped` property, deprecate `zebra` property

packages/calcite-components/src/components/date-picker/date-picker.tsx
**Related Issue:** #8436
- Quick fix to remove console error
- Ideally, I think a user should be able to select the end date first and the whole hover range experience should work. I tried getting that working quickly but wasn't successful. I think we'll need a followup issue.
=> fix(date-picker): prevent console error when selecting just an end date for input date picker

documentation/monorepo.md, documentation/releasing.md
Moves the two maintained wiki pages to the monorepo before we disable the wiki.
=> docs: move maintained wiki pages into the monorepo

packages/calcite-components/src/components/filter/filter.tsx
**Related Issue:** #8457
- Removes console warning from being displayed to end users
=> fix(filter): prevent console warning from displaying to end users

package-lock.json, package.json
Resolve [Storybook build errors](https://github.com/Esri/calcite-design-system/actions/runs/7343318422/job/19993741956?pr=8509#step:6:234) that were caused by conflicting Webpack versions.
We should probably bump to Storybook 7 soon to get Webpack 4 out of our dependency tree, among other things.
=> build(storybook): resolve error due to webpack dependency conflicts

packages/calcite-components/src/components/table/table.stories.ts, packages/calcite-components/src/components/table/table.tsx, packages/calcite-components/src/demos/table.html
**Related Issue:** #8508
Adds a conditional class to Table Rows slotted in `table-footer` slot to prevent double border. We were doing this for body rows, but not footer rows. Adds screenshot tests to verify and updates some local samples to show this combination of props / slotted content.
| Before  | After |
| ------------- | ------------ | 
| <img width="997" alt="Screenshot 2023-12-27 at 4 46 36 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/ac65ab72-6455-4c05-bcb2-480af2ae65f4"> | <img width="997" alt="Screenshot 2023-12-27 at 4 46 01 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/fac52ec6-9695-4f07-bb2b-35c5f7bac373"> |
=> fix(table): Fix double border on `bordered` Table Rows in `table-footer`

packages/calcite-components/src/components/tab-nav/tab-nav.tsx, packages/calcite-components/src/components/table/table.tsx, packages/calcite-components/src/components/tabs/tabs.tsx, packages/calcite-components/src/components/tile-select/tile-select.tsx, packages/calcite-components/src/components/tree/tree.tsx, packages/calcite-components/src/components/value-list/value-list.tsx
**Related Issue:** #7071
Updates doc consistency across t and v-named components defined in the above issue for props, events, methods, and css vars, including:
- `tab-nav`
- `table`
- `tabs`
- `tile-select`
- `tree`
- `value-list`
=> docs(tab-nav, table, tabs, tile-select, tree, value-list): consistent api description refs

.github/workflows/update-doc.yml
Resolves an error in the GitHub Action that updates the component readmes, which was due to not building the design tokens before building the components.
error: https://github.com/Esri/calcite-design-system/actions/runs/7381163545/job/20079386682#step:4:178
=> ci(update-doc): build design tokens to prevent errors

packages/calcite-components/src/components/button/button.e2e.ts, packages/calcite-components/src/components/button/button.tsx
**Related Issue:** #8417
In my application I set `title` attribute on the `<calcite-button>`, but it wasn't being displayed because the shadow DOM's `<button>` had an empty title attribute (`title=""`) which was overwriting the title set on the calcite-button.
Reproduction:
1. [Codepen example](https://codepen.io/maxpatiiuk/pen/KKJEaER?editors=1000)
2. Hover over the button - no tooltip is shown
3. Remove the "title" attribute from the `<button>`, and tooltip is visible
Video reproduction:
https://github.com/Esri/calcite-design-system/assets/40512816/d338be3e-667d-45ab-a29f-bc79d84df353
=> fix(button): don't needlessly overwrite title

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #7965
This fixes an issue that caused the start date picker to be toggled when the end date icon was clicked.
=> fix(input-date-picker): ensure range icon toggles open corresponding date-picker

packages/calcite-components/src/utils/interactive.tsx
[Stencil 4.8.0](https://github.com/ionic-team/stencil/blob/main/CHANGELOG.md#-480-2023-11-27) added `inert` to the JSX types, so this is no longer needed.
=> refactor: remove @ts-ignore needed for Stencil missing  in JSX types

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/list-item-group/list-item-group.e2e.ts, packages/calcite-components/src/components/list-item-group/list-item-group.scss, packages/calcite-components/src/components/list-item-group/list-item-group.tsx, packages/calcite-components/src/components/list-item/list-item.e2e.ts, packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.stories.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #8539
- Adds internal `filterHidden` property to `list-item` and `list-item-group`
- This property is used to hide an item when it is filtered out instead of the native `hidden` attribute
- This allows the `hidden` attribute to be set by an end user
- Renames internal vars
- Adds screenshot tests
- Add e2e tests
- Added a developer discussion topic to consider not modifying global `hidden` attribute on host elements.
=> fix(list, list-item, list-item-group): honor hidden attribute on list-item and list-item-group

packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.e2e.ts, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/common/tests.ts, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx, packages/calcite-components/src/utils/form.tsx
**Related Issue:** #8072
This fixes an issue in form-submitting contexts where input focus would move and stay on a hidden input.
**Note:** this also introduces a module for sharing input tests.
=> fix(input, input-number, input-text): restore focus on input after browser validation error is displayed and user continues typing

packages/calcite-components/src/components/action/action.scss
**Related Issue:** #8519
Action token was mislabeled as a button token and was missed in the design token refactor. This adds the token back to the action component
=> fix(action): update component tokens to support transparent

documentation/monorepo.md
Clarify that you need to edit the body of the pull request for the changelog entry you want to modify.
=> docs(monorepo): clarify which PR to edit when modifying changelog entry

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.stories.ts, packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/list/resources.ts, packages/calcite-components/src/demos/list.html
**Related Issue:** #8564
- Adds slot `"filter-no-results"`.
- When filter is enabled, a filter text is present and there are no items being shown, this slot will be displayed
- The slot is for showing any warning information that there are no items displayed
- Allows a user to customize any messaging for no results shown.
- Adds screenshot test
- Adds e2e test
=> feat(list): Add "filter-no-results" slot to display content when no filtered items are shown

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.tsx
**Related Issue:** #7351
When color channels are nudged, the value is modified and set directly on input. This worked fine when using up/down arrows as change events are emitted by default, but for the modified nudging behavior (shift key), the modified input value logic was suppressing the change event.
=> fix(color-picker): emit color change when nudging color channels by using the shift key

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.tsx
- Refactor logic to rely on focus out instead of tab key
- Update test
=> feat(action-menu): Close menu on blur instead of on tab key.

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.e2e.ts, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx, packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx, packages/calcite-components/src/components/select/select.e2e.ts, packages/calcite-components/src/components/select/select.tsx, packages/calcite-components/src/components/text-area/text-area.e2e.ts, packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #8057
- Reflect the `validationIcon` - brought up in https://github.com/Esri/calcite-design-system/pull/8561#issuecomment-1884074225
- Add `validationIcon`, `validationMessage`, and `status` properties to the reflects and defaults common tests - brought up in https://github.com/Esri/calcite-design-system/pull/8561#issuecomment-1879355882
=> feat: reflect validationIcon property

packages/calcite-components/src/assets/styles/includes.scss, packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-message/input-message.scss
**Related Issue:** https://github.com/Esri/calcite-design-system/pull/8561#issuecomment-1887992460
- Resolve CSS specificity issue that prevented `--calcite-input-message-spacing-value` from having any effect.
- Add missing margin top to the small scale to align with the Figma design, where the margin is the same for all scales.
=> fix(input-message): add missing margin to scale="s", spacing CSS variable has effect

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/modal/modal.e2e.ts, packages/calcite-components/src/components/modal/modal.tsx
**Related Issue:** #8340 
This fixes an issue caused by the internal `opened` watcher being invoked and not having the [`transitionEl` ref available](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/modal/modal.tsx#L519-L523), which would bypass the open/close component hooks and not [activate the focus trap](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/modal/modal.tsx#L489).
=> fix(modal): ensure focus trapping in dynamically created, subsequently opened modals

packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/input.tsx, packages/calcite-components/src/components/radio-button-group/radio-button-group.tsx, packages/calcite-components/src/components/radio-button/radio-button.tsx, packages/calcite-components/src/components/tile-select/tile-select.tsx, packages/calcite-components/src/components/tile/tile.tsx
**Related Issue:** #5548  
This removes `hidden` props since it's available on `HTMLElement` (base class for custom elements).
=> refactor: drop `hidden` prop since it is a global attribute

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/list-item/list-item.e2e.ts, packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #6700
It was decided that the majority of cases use the layer list to perform some kind of action so the default should be to have hover and pointer styling by default. In the future, we may add another selectionMode to provide a better UX for "non interactive" lists.
Further information: https://github.com/Esri/calcite-design-system/issues/6123#issuecomment-1361770131
- Always has the hover and pointer styling on a list item regardless of selectionMode
- Add e2e test
=> fix(list-item): always show hover and pointer styling

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.tsx
**Related Issue:** #8577 #8628
- This reverts commit ccfbd0c69f3f83149808f16dfaa389dc463c2442.
- Adds test
=> fix(action-menu): clicking an action menu item should call click event.

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/demos/button.html
Add the following component tokens to the button component:
`--calcite-button-background-color`: Specifies the background color of the component.
`--calcite-button-background-color-hover`: Specifies the background color of the component when in hover state.
`--calcite-button-background-color-focus`: Specifies the background color of the component when in focus state.
`--calcite-button-background-color-active`: Specifies the background color of the component when in active state.
`--calcite-button-text-color`: Specifies the text color of the component.
`--calcite-button-text-color-hover`: Specifies the text color of the component when in hover state.
`--calcite-button-text-color-focus`: Specifies the text color of the component when in focus state. …
=> feat(button): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/action-bar/action-bar.e2e.ts, packages/calcite-components/src/components/action-bar/action-bar.tsx, packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-pad/action-pad.e2e.ts, packages/calcite-components/src/components/action-pad/action-pad.tsx, packages/calcite-components/src/components/block/block.e2e.ts, packages/calcite-components/src/components/block/block.tsx, packages/calcite-components/src/components/flow-item/flow-item.e2e.ts, packages/calcite-components/src/components/flow-item/flow-item.tsx, packages/calcite-components/src/components/panel/panel.e2e.ts, packages/calcite-components/src/components/panel/panel.tsx, packages/calcite-components/src/tests/commonTests.ts
**Related Issue:** #8620
This allows users to specify `overlayPositioning` to help escape scrolling containers for underlying menus.
**Note**: this adds a new helper (`delegatesToFloatingUiOwningComponent`) to shallowly test if a component has a floating-ui-owning component wired up.
=> feat(action-bar, action-pad, block, flow-item, panel): add `overlayPositioning` prop for built-in menus

packages/calcite-components/src/components/tab/tab.e2e.ts, packages/calcite-components/src/components/tab/tab.scss, packages/calcite-components/src/components/tabs/tabs.stories.ts
**Related Issue:** #8413
Introduces a CSS custom property `--calcite-tab-content-block-padding` to align with other components that have built-in padding. 
Currently, the Tab component has a built-in `block-padding` that cannot be overridden in a supported way, leading to a bug with scrollbars when tabs are housed inside a panel. 
The introduction of the custom property allows for more flexibility in the component, as users can achieve their desired layout and padding by adding it to their slotted content. (https://github.com/Esri/calcite-design-system/issues/8139#issuecomment-1830397218)
=> feat(tab): add `--calcite-tab-content-block-padding` to override built-in block-padding

packages/calcite-components/src/components/tile-select/tile-select.tsx
**Related Issue:** #8495 
This fixes an issue that prevented the Stencil build from including supporting components from being auto-defined in the `components` output target.
=> fix(tile-select): ensure supporting components are auto-defined

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8495 
This fixes an issue that prevented the Stencil build from including supporting components from being auto-defined in the components output target. 
This probably wasn't noticeable since in `combobox` and `combobox-item`s are expected to be used together.
=> fix(combobox): ensure supporting components are auto-defined

packages/calcite-components/.eslintrc.cjs, packages/eslint-plugin-calcite-components/docs/no-dynamic-createelement.md, packages/eslint-plugin-calcite-components/src/configs/base.ts, packages/eslint-plugin-calcite-components/src/rules/index.ts, packages/eslint-plugin-calcite-components/src/rules/no-dynamic-createelement.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/no-dynamic-createelement/no-dynamic-createelement.good.tsx, packages/eslint-plugin-calcite-components/tests/lib/rules/no-dynamic-createelement/no-dynamic-createelement.spec.ts, packages/eslint-plugin-calcite-components/tests/lib/rules/no-dynamic-createelement/no-dynamic-createelement.wrong.tsx
**Related Issue:** #8651
This adds a custom ESLint rule to ensure Stencil bundles and auto-defines child components created via `document.createElement`.
=> feat: add `no-dynamic-createelement` rule

packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts
**Related Issue:** #8664
- Fixes tabbing through slotted elements within the list-item.
- When focusin occurs, do not focus the element, instead just save the cell index.
=> fix(list-item): Do not focus on item cells on focusIn

packages/calcite-components/src/components/chip/chip.e2e.ts, packages/calcite-components/src/components/chip/chip.tsx
**Related Issue:**#8674
- Prevents rendering the internal calcite-icon if no selection icon is specified
- Causes screenshot tests in the Maps SDK to fail because its expecting/waiting for an icon to load and it will never load since no icon is specified
- Maybe we should make the icon property required on `calcite-icon`?
=> fix(chip): Prevent rendering internal icon if not necessary.

packages/calcite-components/package.json
Lint the component readmes after they are generated by the storybook build to reduce the diffs. The readmes are linted in the action that updates them:
https://github.com/Esri/calcite-design-system/blob/2d111761f756689942775174fdc8b1217aca16c1/.github/workflows/update-doc.yml#L19-L20
=> build(storybook): lint component readmes after building docs

.renovaterc.json
Removes the limit on the number of renovate pull requests than can be open concurrently. This came up on a Teams thread because the Calcite UI icons did not get updated in a timely manner.
=> ci(renovate): remove rate limiting on esri and stencil deps

packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8396 
This fixes a spacing regression introduced in https://github.com/Esri/calcite-design-system/pull/7912/.
=> fix(combobox): avoid inline-start padding on combobox label when icon is displayed

packages/calcite-components/calcite-preset.ts
**Related Issue:** #8548
Resolves issue with missing `--calcite-ui-focus-color`
=> fix(preset): add back legacy token for calcite-ui-focus-color

packages/calcite-components/src/components/combobox/combobox.tsx
Fixes a test failure caused by conditional rendering of nodes. 
**Note**: the `grid` key can be removed once we bump Stencil to v4.12.0 or greater as it introduced [automatic `key` insertion](https://github.com/ionic-team/stencil/releases/tag/v4.12.0).
=> test(combobox): fix form-associated test

packages/calcite-components/src/components/panel/panel.scss, packages/calcite-components/src/components/panel/panel.stories.ts
- Adds screenshot theming test
* `--calcite-panel-background-color`: Specifies the background color of the component.
* `--calcite-panel-border-color`: Specifies the border color of the component.
* `--calcite-panel-description-text-color`: Specifies the color of the component's description.
* `--calcite-panel-footer-background-color`: Specifies the background color of the component's footer.
* `--calcite-panel-footer-space`: Specifies the spacing of the component's footer.
* `--calcite-panel-header-background-color`: Specifies the component header's background color.
* `--calcite-panel-heading-text-color`: Specifies the component header's  color.
* `--calcite-panel-header-z-index`: Specifies the component header's z-index.
* `--calcite-panel-fab-z-index`: …
=> feat(panel): Add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.e2e.ts, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/common/input.spec.ts, packages/calcite-components/src/components/input/common/input.ts, packages/calcite-components/src/components/input/common/tests.ts, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx, packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #8647 
This ensures `pattern`, `minlength`, `maxlength`, `min`, `max`, `step` are set on the internal form input based on the matching type.
**Note**: `minlength` and `maxlength` won't trigger constraint validation unless a user interacts with the input (see [`minlength` spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#setting-minimum-input-length-requirements:-the-minlength-attribute:~:text=Constraint%20validation%3A%20If%20an%20element%20has%20a%20minimum,element%20is%20suffering%20from%20being%20too%20short.) and [`maxlength` spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#setting-minimum-input-length-requirements:-the-minlength-attribute:~:text=Constraint%20validation%3A%20If%20an%20element%20has%20a%20maximu …
=> fix(input, input-number, input-text, text-area): ensure all applicable props are considered in form validation

packages/calcite-components/src/components/flow-item/flow-item.scss, packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #8028 #8611
- Reverts previous pull request which removes `overflow:hidden` on the host of the `panel` and `flow-item` components.
=> revert: fix(panel, flow-item): remove overflow rule

packages/calcite-components/src/assets/styles/_sortable.scss, packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #8728
- Fixes fallback ghost element styling to not overflow its container.
- adds fallback class for sortable items.
=> fix: fix styling when dragging items on a mobile device

packages/calcite-components/src/components/icon/icon.scss
Add new component tokens
```
--calcite-icon-color: defines the color of the component. Defaults to `currentColor`.
--calcite-icon-size: defines the size of the component.
```
=> feat(icon): add component tokens

packages/calcite-components/src/utils/interactive.spec.ts, packages/calcite-components/src/utils/interactive.tsx
**Related Issue:** #8729 
This updates the interactive util to track disabled component parents (needed for Firefox workaround) as the component is disabled and enabled.
**Note**: test environment is Chromium-based, so no tests were updated.
=> fix: prevent interaction when component is disabled after initialization (Firefox)

packages/calcite-components/src/components/flow-item/flow-item.scss, packages/calcite-components/src/components/flow-item/flow-item.stories.ts, packages/calcite-components/src/components/panel/panel.scss
- Add component tokens for `calcite-flow-item`
- Add story
Adds the following component tokens:
* @prop --calcite-flow-item-background-color: Specifies the background color of the component.
* @prop --calcite-flow-item-border-color: Specifies the border color of the component.
* @prop --calcite-flow-item-description-text-color: Specifies the text color of the component's description.
* @prop --calcite-flow-item-fab-z-index: Specifies the component fab's z-index.
* @prop --calcite-flow-item-footer-background-color: Specifies the background color of the component's footer.
* @prop --calcite-flow-item-footer-padding: [Deprecated] Use `--calcite-flow-item-footer-space` instead. Specifies the padding of the component's footer.
* @prop --calcite-flow-item-footer-space: …
=> feat(flow-item): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/stepper-item/stepper-item.scss, packages/calcite-components/src/components/stepper-item/stepper-item.tsx, packages/calcite-components/src/components/stepper/resources.ts, packages/calcite-components/src/components/stepper/stepper.tsx
**Related Issue:**  #8461
When `layout="horizontal"`, allows `stepper-item's` to shrink with container width.
=> fix(stepper): no longer adds default `min-width` for items when `layout='horizontal'`

release-please-config.json
This updates the `release-please` config to use [`groupName`](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#linked-versions) vs [`group-name`](https://github.com/Esri/calcite-design-system/blob/main/release-please-config.json#L32) to fix synced version changelog entries (notice `undefined` below):
> ## [2.2.0](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-components-react@2.1.0...@esri/calcite-components-react@2.2.0) (2024-01-17)
> 
> ### Miscellaneous Chores
> 
> - **@esri/calcite-components-react:** Synchronize undefined versions
=> build(changelog): fix synced version group name

packages/calcite-components-angular/projects/component-library/CHANGELOG.md, packages/calcite-components-react/CHANGELOG.md
**Related Issue:** #8763
#8762 fixed the synced version group name in the latest release-please pull request. This updates the group name in the changelogs for previous versions.
=> docs(changelog): specify components group name

package-lock.json, package.json, packages/calcite-components/package.json
Cleans up package-patching scripts (introduced in https://github.com/Esri/calcite-design-system/pull/8751) to prevent them from running on `calcite-components` installs.
=> fix: prevent package patching on install

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/meter/meter.scss, packages/calcite-components/src/components/rating/rating.scss, packages/calcite-components/src/components/rating/rating.stories.ts, packages/calcite-components/src/demos/rating.html
Adds the following component tokens:
`--calcite-rating-spacing-unit`: The amount spacing between rating items.
`--calcite-rating-outline-color`: Specifies the outline color for a rating item.
`--calcite-rating-outline-color-hover`: Specifies the outline color for a rating item while hovered.
`--calcite-rating-value-fill-color`: Specifies the fill color for a rating item with value.
`--calcite-rating-average-fill-color`: Specifies the fill color for a rating item with average.
`--calcite-rating-chip-background-color`: Specifies the background color of the component's `show-chip` display.
`--calcite-rating-chip-border-color`: Specifies the border color of the component's `show-chip` display.
`--calcite-rating-chip-shadow`: Specifies the box shadow of the …
=> feat(rating): Add component tokens

packages/calcite-components/src/assets/styles/_floating-ui.scss, packages/calcite-components/src/assets/styles/global.scss, packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/dropdown/dropdown.scss, packages/calcite-components/src/components/input-date-picker/input-date-picker.scss, packages/calcite-components/src/components/popover/popover.scss, packages/calcite-components/src/components/popover/popover.stories.ts, packages/calcite-components/src/components/tooltip/tooltip.scss, packages/calcite-components/src/components/tooltip/tooltip.stories.ts
* @prop --calcite-tooltip-background-color: Specifies the background color of the component.
* @prop --calcite-tooltip-border-color: The border color of the component.
* @prop --calcite-tooltip-corner-radius: The corner radius of the component.
* @prop --calcite-tooltip-shadow: The shadow of the component.
* @prop --calcite-tooltip-text-color: The text color of the component.
=> feat(tooltip): add component tokens.

packages/calcite-components/src/components/table-cell/table-cell.tsx, packages/calcite-components/src/components/table-header/table-header.tsx, packages/calcite-components/src/components/table/table.stories.ts, packages/calcite-components/src/demos/table.html
**Related Issue:** #8778 
- Resolves missing border issue by conditionally applying the `lastCell` class only when applicable - ensuring the border is displayed when the Cell is the "last in row" but visually not presented that way due to `rowSpan`
- Adds more complex demo and screenshot test to illustrate the issue / fix.
Before:
After:
=> fix(table): Ensure border are correctly applied with complex rowSpan

packages/calcite-components/src/components/inline-editable/inline-editable.scss
* `--calcite-inline-editable-background-color`: Specifies the background color of the component.
* `--calcite-inline-editable-border-color`: Specifies the border color of the component.
**Note**: border color applied to `.cancel-editing-button-wrapper` was removed since it was not applied (border style not assigned).
=> feat(inline-editable): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-number/input-number.tsx
Deprecates `minLength`/`maxLength` since they have no effect on numeric inputs. We can remove them at a future breaking change release.
This stems from https://github.com/Esri/calcite-design-system/pull/8655#discussion_r1468938091.
=> docs(input-number): deprecate `minLength`/`maxLength` props as they have no effect

packages/calcite-components/src/components/switch/switch.scss
* `--calcite-switch-handle-background-color`
* `--calcite-switch-handle-border-color`
* `--calcite-switch-track-background-color`
* `--calcite-switch-track-border-color`
* `--calcite-switch-corner-radius`
* `--calcite-switch-shadow`
=> feat(switch): add component tokens

packages/calcite-components/src/components/shell-center-row/shell-center-row.e2e.ts
This selects the correct component within the shadow dom. The previous selector included the components <style> tag.
=> test(shell-center-row): fix test

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/option-group/option-group.e2e.ts
The previous selector included the component’s style tag. This allows the test to pass.
=> test(option-group): fix

packages/calcite-components/src/components/combobox/combobox.e2e.ts
I don’t know why but adding three items always resulted in an overflow on my machine. I don’t think this change alters the actual intent of the test but it does allow it to pass locally.
=> test(combobox): update test to reduce complexity

.github/workflows/pr-e2e.yml, packages/calcite-components/src/components/input/input.e2e.ts
Manually install Chrome using an action to prevent errors with Puppeteer trying to install Chrome from a broken URL.
```
npm ERR! code 1
npm ERR! path /home/runner/work/calcite-design-system/calcite-design-system/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip
npm ERR!     at file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:74:31
npm ERR!     at ClientRequest.requestCallback …
```
=> ci(e2e): manually setup chrome to fix puppeteer errrors

.github/workflows/pr-e2e.yml
Allows anyone with GH Actions permission on the repo to manually go to https://github.com/Esri/calcite-design-system/actions/workflows/pr-e2e.yml and select their current branch, even if it's base is not `main` or `rc` and trigger an `npm run build && npm run test`
=> chore(pr-e2e): add workflow_dispatch option for e2e tests

packages/calcite-components/src/components/navigation-logo/navigation-logo.scss, packages/calcite-components/src/components/navigation-logo/navigation-logo.stories.ts
**Related Issue:** #8482 
Fixes change of icon color in `navigation-logo` when `href` attribute is parsed.
=> fix(navigation-logo): no longer changes icon color when `href` is parsed

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/tile/tile.tsx
**Related Issues:** #6662 #8351
Tile Select no longer uses Tile, and thus its internal `embed` property, so this PR marks it as deprecated.
=> docs(tile): deprecate embed property

packages/calcite-components/src/components/action-group/action-group.scss, packages/calcite-components/src/components/action-menu/action-menu.e2e.ts, packages/calcite-components/src/components/action-menu/action-menu.scss, packages/calcite-components/src/components/block/block.scss, packages/calcite-components/src/components/menu-item/menu-item.scss, packages/calcite-components/src/components/panel/panel.scss
Adds Action-Menu component tokens and sub-component tokens to Calcite Components
--calcite-action-group-action-menu-border-color: The border color of the sub-component.
--calcite-action-group-action-menu-text-color: The text color of the sub-component.
--calcite-action-menu-border-color: The border color of the component.
--calcite-action-menu-text-color: The text color of the component.
--calcite-block-action-menu-border-color: The border color of the sub-component.
--calcite-block-action-menu-text-color: The text color of the sub-component.
--calcite-menu-item-action-menu-border-color: The border color of the sub-component.
--calcite-menu-item-action-menu-text-color: The text color of the sub-component.
--calcite-panel-action-menu-border-color: The border color …
=> feat(action menu): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/card-group/card-group.tsx
Removes this unused property that made it through review. 
Initially there was a plan to add scale to Card, but that change was removed and this property was not cleaned up. Should be safe to remove as it had no effect.
=> refactor(card-group): Remove unused `scale` property

packages/calcite-components/src/components/tab-nav/tab-nav.scss
* `--calcite-tab-nav-indicator-color`
* `--calcite-tab-nav-button-background-color`
* `--calcite-tab-nav-button-background-color-active`
* `--calcite-tab-nav-button-background-color-focus`
* `--calcite-tab-nav-button-background-color-hover`
* `--calcite-tab-nav-button-border-color`
* `--calcite-tab-nav-button-border-color-active`
* `--calcite-tab-nav-button-border-color-focus`
* `--calcite-tab-nav-button-border-color-hover`
* `--calcite-tab-nav-button-icon-color`
* `--calcite-tab-nav-button-icon-color-active`
* `--calcite-tab-nav-button-icon-color-focus`
* `--calcite-tab-nav-button-icon-color-hover`
**Note:** scroll button prop assignment is depends on button refactor.
=> feat(tab-nav): add component tokens

packages/calcite-components/src/components/tab/tab.scss
* `--calcite-tab-content-space-y`
Deprecates the following:
* `--calcite-tab-content-block-padding`
=> feat(tab): add component tokens

packages/calcite-components/src/components/select/select.e2e.ts
Uses character-matching behavior for select to ensure the component's value changes. The context-menu is not accessible through Puppeteer.
=> test(select): fix form-associated E2E test

packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #8892
Adds the `filter-no-results` slot to the `list` component's doc.
=> docs(list): add filter-no-results slot

packages/calcite-components/src/components/navigation-user/navigation-user.scss
Adds following tokens for `calcite-navigation-user`
``` 
--calcite-navigation-user-avatar-corner-radius: Specifies the corner radius of avatar of the component.
--calcite-navigation-user-avatar-text-color: Specifies the text color of avatar of the component.
--calcite-navigation-user-background-color: Specifies the background color of the component.
--calcite-navigation-user-border-color: Specifies the border color of the component.
--calcite-navigation-user-full-name-text-color: Specifies the text color of full name of the component.
--calcite-navigation-user-name-text-color: Specifies the text color of user name of the component.
--calcite-navigation-user-text-color: Specifies the text color of the component.
=> feat(navigation-user): adds component tokens

packages/calcite-components/src/components/navigation/navigation.scss
Adds following tokens for `calcite-navigation` component and deprecates `calcite-navigation-background-color` token.
``` 
--calcite-navigation-action-background-color-active: defines the background color of an action sub-component when active.
--calcite-navigation-action-background-color-hover: defines the background color of an action sub-component when hovered or focused.
--calcite-navigation-action-background-color: defines the background color of an action sub-component inside the component.
--calcite-navigation-background-color: Specifies the background color of the component.
--calcite-navigation-background: [Deprecated] in favor of `--calcite-navigaton-background-color`. Specifies the background color of the component.
--calcite-navigation-border-color: …
```
=> feat(navigation): adds component tokens

packages/calcite-components/src/components/input-time-picker/input-time-picker.scss, packages/calcite-components/src/components/time-picker/time-picker.scss, packages/calcite-components/src/demos/input-time-picker.html
Add the following component tokens to the time-picker component:
`--calcite-time-picker-text-color`: Specifies the text color of the component.
`--calcite-time-picker-background-color`: Specifies the background color of the component.
`--calcite-time-picker-background-color-hover`: Specifies the background color of the component when in hovered.
`--calcite-time-picker-background-color-active`: Specifies the background color of the component when in active.
`--calcite-time-picker-icon-color`: Specifies the color of the component's icons.
`--calcite-time-picker-input-box-shadow`: Specifies the box shadow around the numbers inside the open component.
`--calcite-time-picker-input-box-shadow-focus`: Specifies the box shadow around the numbers inside the open component …
=> feat(time-picker): add component tokens to time picker

packages/calcite-components/src/components/navigation-user/navigation-user.scss, packages/calcite-components/src/components/navigation-user/navigation-user.stories.ts
Allows theming with tokens and removes `--calcite-navigation-user-text-color` token from `navigation-user`.
=> fix(navigation-user): allows theming with tokens

packages/calcite-components/src/components/action/action.scss, packages/calcite-components/src/components/block/block.scss, packages/calcite-components/src/components/card/card.scss, packages/calcite-components/src/components/loader/loader.scss, packages/calcite-components/src/components/scrim/scrim.scss
--calcite-loader-color-end: defines the color of a loader. Applies to --calcite-loader-color between 66% - 99% of the animation.
--calcite-loader-color-middle: defines the color of a loader. Applies to --calcite-loader-color between 33% - 66% of the animation.
--calcite-loader-color-start: defines the starting color of a loader. Applies to --calcite-loader-color between 0% - 33% of the animation.
=> fix(loader): update names

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8919
Prevent combobox from allowing to select and deselect the "last focused item" with the Enter key when it's closed.
=> fix(combobox): prevent toggling items when combobox is closed

packages/calcite-components/src/components/button/button.scss, packages/calcite-components/src/components/color-picker/color-picker.scss, packages/calcite-components/src/components/fab/fab.scss, packages/calcite-components/src/components/inline-editable/inline-editable.scss, packages/calcite-components/src/components/tab-nav/tab-nav.scss, packages/calcite-components/src/components/table/table.scss
--calcite-button-background-color: defines the component's background color.
--calcite-button-border-color: defines the component's border color.
--calcite-button-corner-radius: defines the component's corner radius.
--calcite-button-loader-color: defines the component's loader color.
--calcite-button-shadow: defines the component's shadow.
--calcite-button-text-color: defines the component's text color.
--calcite-button-icon-color: defines the color of an icon in the component.
--calcite-fab-background-color: defines the component's background color.
--calcite-fab-border-color: defines the component's border color.
--calcite-fab-corner-radius: defines the component's corner radius.
--calcite-fab-loader-color: defines the component's loader color. …
=> feat(button, fab): add component tokens

.github/workflows/pr-semantic.yml
Per the action's documentation (https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#legacy-configuration-for-validating-single-commits) and our latest squash merging settings (use PR title + description), validating on single commits is no longer necessary.
=> ci(pr-semantic): remove no longer needed validateSingleCommit

packages/calcite-components/src/components/block-section/block-section.scss
Adds the following subcomponent tokens (CSS props):
* `--calcite-block-section-switch-corner-radius`
* `--calcite-block-section-switch-handle-background-color`
* `--calcite-block-section-switch-handle-border-color-hover`
* `--calcite-block-section-switch-handle-border-color`
* `--calcite-block-section-switch-handle-shadow-hover`
* `--calcite-block-section-switch-handle-shadow`
* `--calcite-block-section-switch-track-background-color-checked`
* `--calcite-block-section-switch-track-background-color`
* `--calcite-block-section-switch-track-border-color-checked`
* `--calcite-block-section-switch-track-border-color`
* internal label does not require customization.
* icon-related CSS props will be added by https://github.com/Esri/calcite-design-system/pull/8868/.
=> feat(block-section): add subcomponent CSS props

packages/calcite-components/src/components/switch/switch.scss
Updates component tokens to the following (CSS props):
* `--calcite-switch-corner-radius`
* `--calcite-switch-handle-background-color`
* `--calcite-switch-handle-border-color`
* `--calcite-switch-handle-shadow`
* `--calcite-switch-shadow-hover`
* `--calcite-switch-track-background-color`
* `--calcite-switch-track-border-color`
=> feat(switch): add stateful component tokens

packages/calcite-components/src/components/notice/notice.scss
Fix for incorrect fallback.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2024-03-14 at 9 38 00 AM](https://github.com/Esri/calcite-design-system/assets/4733155/e923fd70-7005-4fcc-9ba4-09dd4ae5edb0)  |   ![Screenshot 2024-03-14 at 9 37 21 AM](https://github.com/Esri/calcite-design-system/assets/4733155/7fc2962d-0923-4f24-89d4-a21d86906881) |
=> fix(notice): Fix close button focus outline color

packages/calcite-components/src/components/alert/alert.scss
* `--calcite-alert-accent-color`
* `--calcite-alert-background-color`
* `--calcite-alert-border-color`
* `--calcite-alert-chip-background-color`
* `--calcite-alert-chip-border-color`
* `--calcite-alert-chip-corner-radius`
* `--calcite-alert-chip-text-color`
* `--calcite-alert-close-background-color-active`
* `--calcite-alert-close-background-color-focus`
* `--calcite-alert-close-background-color-hover`
* `--calcite-alert-close-background-color`
* `--calcite-alert-close-icon-color-active`
* `--calcite-alert-close-icon-color-focus`
* `--calcite-alert-close-icon-color-hover`
* `--calcite-alert-close-icon-color`
* `--calcite-alert-corner-radius`
* `--calcite-alert-shadow`
**Note**: `--calcite-alert-min-height` was …
=> feat(alert): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/pagination/pagination.scss, packages/calcite-components/src/components/pagination/pagination.stories.ts, packages/calcite-components/src/demos/pagination.html
Updates nomenclature of Pagination design tokens to be more specific / accurate. Previously, the naming made it seem like the tokens applied to the parent container - in practice, they apply to the internally rendered items. It also follows the structure of `pagination-arrow-x`.
=> feat(pagination): Update component tokens

packages/calcite-components/src/components/date-picker-day/date-picker-day.scss, packages/calcite-components/src/components/date-picker-month/date-picker-month.scss, packages/calcite-components/src/components/date-picker/date-picker.scss
Changes in `calcite-date-picker` tokens:
- Removes `--calcite-date-picker-day-font-size` & `--calcite-date-picker-week-headers-border-color ` tokens.
- Renames  `--calcite-date-picker-border-radius` to `--calcite-date-picker-corner-radius`.
=> refactor(date-picker): removes font token and update naming.

packages/calcite-components/src/components/stepper/stepper.e2e.ts, packages/calcite-components/src/components/stepper/stepper.tsx
**Related Issue:** #8931 
Fixes an issue that caused step labels to overlap when dynamically switching to `horizontal-single` layout mode.
=> fix(stepper): fix layout when switching modes dynamically to `horizontal-single`

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/table-cell/table-cell.scss, packages/calcite-components/src/components/table-header/table-header.scss, packages/calcite-components/src/components/table-header/table-header.tsx, packages/calcite-components/src/components/table-row/table-row.scss, packages/calcite-components/src/components/table/resources.ts, packages/calcite-components/src/components/table/table.scss, packages/calcite-components/src/components/table/table.stories.ts, packages/calcite-components/src/components/table/table.tsx, packages/calcite-components/src/demos/table.html
=> feat(table): Add component tokens

packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.scss, packages/calcite-components/src/components/date-picker/date-picker.scss, packages/calcite-components/src/components/date-picker/date-picker.stories.ts
Adds following corresponding tokens in `calcite-date-picker` component :
```
--calcite-date-picker-header-background-color: Specifies the background color of month header.
--calcite-date-picker-header-navigation-button-background-color-active: Specifies the background color of navigation button of month header when active.
--calcite-date-picker-header-navigation-button-background-color-hover: Specifies the background color of navigation button of month header when hovered.
--calcite-date-picker-header-navigation-button-background-color: Specifies the background color of navigation button of month header.
--calcite-date-picker-header-navigation-button-text-color-hover: Specifies the text color of navigation button of month header when hovered. …
```
=> feat(date-picker, date-picker-month-header): add component tokens

packages/calcite-components/src/components/modal/modal.scss
* `--calcite-modal-accent-color`
* `--calcite-modal-background-color`
* `--calcite-modal-border-color`
* `--calcite-modal-close-button-background-color-hover`
* `--calcite-modal-close-button-background-color`
* `--calcite-modal-close-button-icon-color`
* `--calcite-modal-content-background-color`
* `--calcite-modal-content-space`
* `--calcite-modal-corner-radius`
* `--calcite-modal-scrim-background-color`
* `--calcite-modal-shadow`
* `--calcite-modal-text-color`
Deprecates the following:
* `--calcite-modal-content-background`
* `--calcite-modal-content-padding`
* `--calcite-modal-scrim-background`
This additionally updates naming on internal props.
=> feat(modal): add component tokens

packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #8928
- Moves sticky class to the table header from the table row
=> fix(list): fix filter box when scrolling in Safari

packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #8954
- Sortablejs by default calls `event.preventDefault()` because the option `preventOnFilter` is true by default.
- This affects any elements slotted within the `drag-disabled` list item.
- In order to fix this, we move the `filter` selector to just the `calcite-handle` instead of the whole `list-item`.
```js
filter: ".ignore-elements",  // Selectors that do not lead to dragging (String or Function)
preventOnFilter: true, // Call `event.preventDefault()` when triggered `filter`
```
=> fix(list, list-item): calcite-select becomes unresponsive in a list-item if drag-disabled is true

packages/calcite-components/src/components/block-section/block-section.scss, packages/calcite-components/src/components/switch/switch.scss
Drops shadow CSS prop in favor of border for thumb border effect.
Removes the following component tokens (CSS props):
* `--calcite-switch-handle-shadow`
* `--calcite-block-section-switch-handle-shadow`
* `--calcite-block-section-switch-handle-shadow-hover`
Stems from https://github.com/Esri/calcite-design-system/pull/8899#discussion_r1526867384.
=> refactor(switch): simplify switch CSS props

packages/calcite-components/src/components/color-picker/color-picker.scss
* `--calcite-color-picker-background-color`
* `--calcite-color-picker-input-background-color`
* `--calcite-color-picker-input-border-color`
* `--calcite-color-picker-input-corner-radius`
* `--calcite-color-picker-input-prefix-background-color`
* `--calcite-color-picker-input-text-color`
* `--calcite-color-picker-tab-nav-indicator-color`
* `--calcite-color-picker-tab-title-background-color`
* `--calcite-color-picker-tab-title-text-color`
* `--calcite-color-picker-text-color`
=> feat(color-picker): add component tokens

packages/calcite-components/src/components/stepper-item/stepper-item.scss, packages/calcite-components/src/components/stepper/functional/step-bar.tsx, packages/calcite-components/src/components/stepper/stepper.scss, packages/calcite-components/src/components/stepper/stepper.stories.ts, packages/calcite-components/src/components/stepper/stepper.tsx
Adds tokens for `stepper` and `stepper-item` components.
`calcite-stepper-item` tokens:
```  
--calcite-stepper-item-description-text-color: Specifies text color of description of component.
--calcite-stepper-item-heading-text-color: Specifies text color of heading of component.
--calcite-stepper-item-icon-color: Specifies color of icon of component.
--calcite-stepper-item-number-text-color: Specifies text color of number of component.
--calcite-stepper-item-text-color: Specifies text color of component.
```
`calcite-stepper` tokens:
``` 
--calcite-stepper-action-background-color: defines the background color of an action sub-component inside the component.
--calcite-stepper-action-background-color-hover: defines the background color of an action sub-component …
```
=> feat(stepper, stepper-item): add component tokens

packages/calcite-design-tokens/support/tests/__snapshots__/index.spec.ts.snap, packages/calcite-design-tokens/support/token-transformer/styleDictionary/transformer/value/valueFontFamilyFallbacks.ts
**Related Issue:** #8963 
Generated font-stack values are now comma-delimited according to the [`font-family` spec](https://drafts.csswg.org/css-fonts/#font-family-prop):
> Component values are a comma-separated list indicating alternatives.
=> fix: fix invalid font stacks

packages/calcite-components/src/components/tab/tab.scss
**Related Issue:** #8799 
Applies focus outline styling to `tab`'s content container.
=> fix(tab): style focus outline of tab content

packages/calcite-components/src/components/tree-item/tree-item.scss
* `--calcite-tree-item-line-color`
* `--calcite-tree-item-text-color`
=> feat(tree-item): add component tokens

packages/calcite-components/src/components/slider/slider.scss
* `--calcite-slider-fill-color`
* `--calcite-slider-histogram-accent-color`
* `--calcite-slider-histogram-background-color`
* `--calcite-slider-handle-border-color-hover`
* `--calcite-slider-handle-border-color`
* `--calcite-slider-handle-color-active`
* `--calcite-slider-handle-color-hover`
* `--calcite-slider-handle-color`
* `--calcite-slider-precise-handle-color-hover`
* `--calcite-slider-precise-handle-color`
* `--calcite-slider-handle-shadow-hover`
* `--calcite-slider-handle-shadow`
* `--calcite-slider-text-color`
* `--calcite-slider-text-size`
* `--calcite-slider-tick-border-color`
* `--calcite-slider-tick-color`
* `--calcite-slider-track-color`
=> feat(slider): add component tokens

packages/calcite-components/src/components/split-button/split-button.scss
--calcite-split-button-background-color-active: Specifies the component's background color when the button is active.
--calcite-split-button-background-color-focus: Specifies the component's background color when the button is focused.
--calcite-split-button-background-color-hover: Specifies the component's background color when the button is hovered.
--calcite-split-button-background-color: Specifies the component's background color.
--calcite-split-button-border-color-active: Specifies the component's border color when the button is active. 
--calcite-split-button-border-color-focus: Specifies the component's border color when the button is focused. 
--calcite-split-button-border-color-hover: Specifies the component's border color when the button is hovered. …
=> refactor(split-button): add component tokens

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx, packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #8685
- Connect floatingUI elements once a component has loaded to correctly setup auto update events
- Automatically call `reposition` inside `connectFloatingUI` for consistency
=> fix(dropdown): correct positioning behavior when inside a scrollable container

packages/calcite-components/src/components/color-picker-hex-input/color-picker-hex-input.scss, packages/calcite-components/src/components/color-picker/color-picker.scss
* `--calcite-color-picker-input-prefix-text-color`
* `--calcite-color-picker-input-suffix-background-color`
* `--calcite-color-picker-input-suffix-text-color`
* `--calcite-color-picker-hex-input-background-color`
* `--calcite-color-picker-hex-input-border-color`
* `--calcite-color-picker-hex-input-corner-radius`
* `--calcite-color-picker-hex-input-prefix-background-color`
* `--calcite-color-picker-hex-input-prefix-text-color`
* `--calcite-color-picker-hex-input-suffix-background-color`
* `--calcite-color-picker-hex-input-suffix-text-color`
* `--calcite-color-picker-hex-input-text-color`
Removes the following (either unused or name does not match component):
* `--calcite-filter-input-prefix-background-color`
* …
=> refactor(color-picker, color-picker-hex-input): update component tokens

packages/calcite-components/src/components/action-bar/action-bar.scss, packages/calcite-components/src/components/action-group/action-group.scss, packages/calcite-components/src/components/action-menu/action-menu.scss, packages/calcite-components/src/components/action-pad/action-pad.scss, packages/calcite-components/src/components/action/action.scss, packages/calcite-components/src/components/action/action.tsx, packages/calcite-components/src/components/action/resources.ts, packages/calcite-components/src/components/popover/popover.scss
--calcite-action-shadow: Specifies the shadow of the component.
--calcite-action-icon-color: Specifies the color of the component's icon.
--calcite-action-indicator-color: Specifies the color of the component's indicator.
--calcite-action-loader-color: Specifies the color of the component's loader.
--calcite-action-pad-background-color: Specifies the background color of the component.
--calcite-action-pad-border-color: Specifies the border color of the component.
--calcite-action-pad-corner-radius: Specifies the corner radius of the component.
--calcite-action-pad-expanded-max-width: When `layout` is `"vertical"`, specifies the expanded max width of the component.
--calcite-action-pad-popover-background-color: Specifies the background color of the popover in the …
=> refactor(action, action-pad, action-bar, action-group, action-menu, popover): component tokens

packages/calcite-components/src/components/action-menu/action-menu.tsx, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/popover/PopoverManager.ts, packages/calcite-components/src/components/tooltip/TooltipManager.ts
**Related Issue:** #7732
This updates event handling to use `click` vs `pointerdown` + checking the pointer type wherever clicks are expected. Both events have different semantics and trigger order. Simplified code is also an added bonus.
=> fix(action-menu, combobox, dropdown, popover, tooltip): use click instead of pointerdown for click contexts

packages/calcite-components/src/components/popover/PopoverManager.ts, packages/calcite-components/src/components/popover/popover.e2e.ts, packages/calcite-components/src/utils/dom.spec.ts, packages/calcite-components/src/utils/dom.ts
**Related Issue:** #7732 
This changes `PopoverManager` to no longer rely on the capture phase for toggling popovers, so clicks from disabled elements are ignored properly.
**Note**: this also introduces a new DOM util to help determine if a click event was triggered via keyboard or not.
=> fix(popover): prevent disabled reference elements from toggling popover

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #6777
Prevent spacebar from opening the menu when focused on chip's `close` button.
Fixes a regression introduced in https://github.com/Esri/calcite-design-system/pull/8909.
=> fix(combobox): prevent spacebar from opening the menu when focused on chip's close button

packages/calcite-components/src/components/input-time-picker/input-time-picker.scss
**Related Issue:** #7713 
Updates toggle icon color in `calcite-input-time-picker`.
=> fix(input-time-picker): update toggle icon color

packages/calcite-components/src/components/action-menu/action-menu.e2e.ts
**Related Issue:** #9000
```
Summary of all failing tests
@esri/calcite-components:test: FAIL src/components/action-menu/action-menu.e2e.ts (19.748 s)
@esri/calcite-components:test:   ● calcite-action-menu › Keyboard navigation › should click the active action when clicked and close the menu
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toBe(expected) // Object.is equality
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: false
@esri/calcite-components:test:     Received: true
@esri/calcite-components:test: 
@esri/calcite-components:test:       523 |       await page.$eval("calcite-action", (el: HTMLCalciteActionElement) => el.click());
@esri/calcite-components:test:       524 |
@esri/calcite-components:test:     > 525 | …
```
=> test(action-menu): skip unstable tests

packages/calcite-components/src/components.d.ts
The [release failed](https://github.com/Esri/calcite-design-system/actions/runs/8445236842/job/23132122216) due to the `components.d.ts` file being outdated, with the following error:
```sh
lerna notice cli v7.4.2
lerna info versioning independent
lerna info ci enabled
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/calcite-components/src/components.d.ts
Error: Process completed with exit code 1.
```
I will add an actual fix to the CI in a subsequent PR.
=> build(components.d.ts): update types for release

packages/calcite-components/src/components/tab-nav/tab-nav.tsx
**Related Issue:** #9010 
Class members are defined on the component host in the `components` output build, so we need to avoid using names of  `HTMLElement` members (`dir` in this case).
**Note**: no additional tests were added since our testing setup uses the `dist` output target.
=> fix(tab-nav): fix custom element creation error in `components` build output

.github/workflows/deploy-latest.yml
**Related Issue:** #9008
Commit changes to `components.d.ts` after building for release to
prevent lerna/npm publishing errors due to an unclean working tree. The
commit will be discarded once the workflow run's container is destroyed.
The `components.d.ts` file is tracked as a temporary workaround for
https://github.com/ionic-team/stencil/issues/3239
To keep the types updated, `components.d.ts` is added to the index in a
pre-commit hook.
https://github.com/Esri/calcite-design-system/blob/2bb1ee24bb317c95e2bef8165c75583fe98ad714/.husky/pre-commit#L7-L13
However, the file can still be outdated if people make changes and don't
rebuild before creating another commit. This is mostly an issue with
small doc updates, like the PR linked above. If that happens, the
release will fail due to an …
=> ci: prevent outdated types from blocking release

packages/calcite-components/src/components/tab-title/tab-title.scss, packages/calcite-components/src/components/tabs/tabs.scss
🔳✨🔨
**Note**: this also fixes a regression from https://github.com/Esri/calcite-design-system/pull/8783 where non-bordered tabs displayed a border.
=> fix(tabs): use border prop for bordered styling

packages/calcite-design-tokens/support/token-transformer/sd-run.ts
This adds a workaround for https://github.com/amzn/style-dictionary/issues/1144. 
**Note**: the workaround is only applied when the design token build runs in Windows
Props to @josercarcamo for catching this and testing the workaround. ✨💪✨
=> build: fix design-tokens build in Windows

.renovaterc.json
This reverts commit d01461d3896bd9791783341999207fb2fa0244e4.
**Related Issue:** #8693
The reverted commit appears to have broken dependency updates for stencil and esri packages. I'll do some additional testing in a separate repo to find a working solution for prioritizing specific packages.
=> revert: ci(renovate): remove rate limiting on esri and stencil deps (#8693)

packages/calcite-components/src/components/list-item/list-item.scss, packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.scss, packages/calcite-components/src/components/list/list.stories.ts
**Related Issue:** #9005
- closed list-items should not leave behind extra space
- Sets internal elements hidden instead of hiding on the host
- updates slotted styles to not apply when closed or filtered out.
=> fix(list): closed list-items no longer render extra space

packages/calcite-components/src/components/block/block.tsx, packages/calcite-components/src/components/date-picker/date-picker.tsx, packages/calcite-components/src/components/flow-item/flow-item.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/panel/panel.tsx, packages/calcite-components/src/components/pick-list-group/pick-list-group.tsx, packages/calcite-components/src/components/pick-list/pick-list.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tip-manager/tip-manager.tsx, packages/calcite-components/src/components/tip/tip.tsx
**Related Issue:** #9044 
Updating the description of `headingLevel` prop to eliminate confusion on what it's purpose is.
=> docs: fix the description of headingLevel property

packages/calcite-components/src/components/panel/panel.e2e.ts, packages/calcite-components/src/components/panel/panel.tsx
**Related Issue:** #9070
- Moves keydown handler to the host so it can be properly cancelled
- Add e2e test
=> fix(panel): support cancelling the esc key event to prevent closing a panel

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8460
- Move combobox role from container wrapper to the input element
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role#examples
=> fix(combobox): fix aria-role for proper voiceover support

packages/calcite-components/src/components/handle/handle.e2e.ts, packages/calcite-components/src/components/handle/handle.tsx
**Related Issue:** #7426
- support keyboard sorting in screen readers by setting internal role to radio
- add e2e test.
- https://stackoverflow.com/questions/52261977/why-javascript-if-keycode-enter-key-or-spacebar-key-does-not-work-with-nvda
=> fix(list, list-item): support keyboard sorting in screen readers

packages/calcite-components/.eslintrc.cjs
Enables [`import/order`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) to help take care of any newlines left between imports after updating modules.
=> chore(linting): enable `import/order` rule to collapse newlines between imports

packages/calcite-components/src/tests/commonTests.ts, packages/calcite-components/src/tests/utils.ts
Our chromium tests do a good job of ensuring the component token updates to styles do not break the existing UI but custom style application of tokens should be considered a data change, not a style change and therefor should be tested with Unit tests. These E2E tests are faster, less resource heavy, and less prone to human error.
However, E2E token tests are harder to set up. To facilitate ease-of-use for other developers this PR introduces a new commonTest utility called themed. This utility expects a calcite-component followed by an object of component token names as keys and each value being an object with a selector, shadowSelector, targetProp, and optional state. The state key will accept a string or an object for more selector specificity which is required …
=> test(common): add prop theme utility for E2E

.renovaterc.json
Enable Renovate's GitHub Action version manager.
ref: https://docs.renovatebot.com/modules/manager/github-actions/
=> ci(renovate): enable github action version management

packages/calcite-components/package.json
Calcite Component's `test:watch` npm script was using the `test` one, which has the `--no-build` flag.
=> test:  ensure 'test:watch' npm script rebuilds after code changes

packages/calcite-components/src/components/action/action.scss, packages/calcite-components/src/components/action/action.stories.ts, packages/calcite-components/src/components/action/action.tsx, packages/calcite-components/src/components/navigation/navigation.e2e.ts
**Related Issue:** #8900
- Maintain equal height when text is not enabled in a small scale
=> fix(action): maintain equal height when text is not enabled in a small scale

packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx, packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #8272 
This updates `input-time-zone` to also check for an item's label when updating state to properly reflect user selection.
=> fix(input-time-zone): ensure selected item is properly displayed when there are other items with the same offset

.github/workflows/pr-e2e.yml
**Related Issue:** #8819
Switch back to using the Chrome executable downloaded with Puppeteer.
Chrome was manually installed via a GitHub Action due to a broken URL,
which has since been fixed.
=> ci(e2e): use chrome included with puppeteer again

packages/calcite-components/.eslintrc.cjs
=> chore(linting): restore disabling of ESLint rules that warn on common, useful patterns

packages/calcite-components/src/components/date-picker/date-picker.e2e.ts, packages/calcite-components/src/components/date-picker/date-picker.tsx
**Related Issue:** #6223
Updates date-picker's `proximitySelectionDisabled` behavior to properly reset a range once a selection occurs after a range's start and end date have been committed.
=> fix(date-picker): ensure `proximitySelectionDisabled` resets range on post-range-commit selection

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/slider/slider.e2e.ts, packages/calcite-components/src/components/slider/slider.stories.ts, packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #4004
Adds `labelFormatter` prop to allow customization of handle and tick labels.
```ts
interface CalciteSlider {
/** 
* Formatter for custom handle/ticks labels.
* 
* If the returned value is a string, it will get used in the label, 
* and if it is `undefined`, it will use the default, formatted label.
*/
labelFormatter(
// the associated label value
value: number, 
// the label type
type: "min" | "max" | "value" | "tick" 
// the default formatter (configured with corresponding locale, numbering system and group separator
defaultFormatter: (value: number): string;
): string | undefined;
}
```
=> feat(slider): add support for custom label formatting

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json, packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages_en.json, packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts, packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx, packages/calcite-components/src/components/input-time-zone/utils.ts, packages/calcite-components/src/demos/input-time-zone.html
**Related Issue:** #9020
Adds `clearable` property to allow `input-time-zone` to be cleared via the UI or programmatically via `””` or `null`.
=> feat(input-time-zone): allow clearing value

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/slider/slider.e2e.ts, packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #1631
Renames the property according to thread in #9170.
=> fix(slider): rename `highlightPlacement` to `fillPlacement`

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/slider/slider.e2e.ts, packages/calcite-components/src/components/slider/slider.stories.ts, packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #1631
This fixes an issue where ticks outside of the active fill were highlighted.
**Note**: this depends on #9195
=> fix(slider): style ticks according to the fill placement

packages/calcite-components/package.json
Restores build step unintentionally removed in https://github.com/Esri/calcite-design-system/pull/9030.
=> chore: restore Stencil build step prior `screenshot-tests:preview`

packages/calcite-components/conventions/README.md
add convention for property values
=> docs: add convention for property values

packages/calcite-components/src/components/combobox/combobox.scss
**Related Issue:** [#7711](https://github.com/Esri/calcite-design-system/issues/7711)
This updates `combobox` chevron colors to be --calcite-color-text-3 when idle or focused, and `--calcite-color-text-1` when hovered.
=> fix(combobox): update the focused chevron icon color

packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
Enable the form validation test utils for `segmented-control`.
=> test(segmented-control): enable form validation tests

packages/calcite-components/src/utils/conditionalSlot.ts
**Related Issue:** #9177
Fixes an issue caused by `conditionalSlot` implementing `unobserve` on top of `ExtendedMutationObserver`, which already implements it.
=> fix: fix memory leak affecting components using conditionally-rendered slots

packages/calcite-components/src/components/handle/handle.e2e.ts, packages/calcite-components/src/tests/commonTests.ts
=> fix(handle): update for e2e theme test

packages/calcite-components/src/components/radio-button/radio-button.e2e.ts, packages/calcite-components/src/demos/validation.html, packages/calcite-components/src/index.html, packages/calcite-components/src/tests/commonTests/formAssociated.ts, packages/calcite-components/src/utils/form.tsx
**Related Issue:** #9220
Fix validation messages not displaying on `calcite-radio-button-group` during form submission.
Note: `calcite-radio-button`s need to be in a group, or else they will not display validation messages based on the `required` constraint.
The formAssociated common test needs to be updated to support a parent component wrapping the form associated element. Currently it assumes the first element it finds will be the form associated component to test. I will do this in a follow up PR, likely after the release.
=> fix(radio-button): display validation message in parent group

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.scss, packages/calcite-components/src/components/combobox/combobox.stories.ts, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/input-time-zone/input-time-zone.stories.ts
**Related Issue:** #7853 #8666
Improves read-only behavior in combobox and applies proper styling.
=> fix(combobox, input-time-zone): improve readOnly behavior and styling

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/list-item/list-item.tsx, packages/calcite-components/src/components/list/list.e2e.ts, packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #9248
- Use internal event on list-item to emit whenever `open` property changes
- Listen for internal event on the list to update bordering.
=> fix(list): border items when an item is programmatically opened.

packages/calcite-components/src/components/card-group/card-group.e2e.ts, packages/calcite-components/src/components/chip-group/chip-group.e2e.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts, packages/calcite-components/src/components/table/table.e2e.ts, packages/calcite-components/src/components/tile-group/tile-group.e2e.ts, packages/calcite-components/src/tests/utils.ts
Adds new `createSelectedItemAsserter` util to help with selection assertions on selectable components.
=> refactor(tests): extract selected item assertion util

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-number/input-number.e2e.ts, packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.e2e.ts, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/common/tests.ts, packages/calcite-components/src/components/input/input.e2e.ts, packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #9235
This fixes the following issues introduced by #9123 when component props that shadowed global attributes were removed:
* the kebab-cased attribute names of those props would no longer work (namely, `enter-key-mode`, `input-mode`)
* `autofocus` was missing from component types as Stencil does not include it in the base `HTMLAttribute` type (see https://github.com/ionic-team/stencil/issues/5726).
=> fix(input, input-number, input-text): restore `autofocus`, `enter-key-mode` and `input-mode` attributes

.renovaterc.json
**Related Issue:** #4678
Removing `cheerio` and `storybook-addon-html` from Renovate's ignore list as we are using recent versions of these dependencies.
=> chore(renovate): update ignore list

packages/calcite-components/src/components/icon/icon.tsx, packages/calcite-components/src/components/icon/utils.ts
Improves icon rendering by:
* avoiding visibility checks on connect if icon is already visible 
* making icon path data assignment sync when cached
* drop fetching on `componentWillLoad` since icon data fetching will occur when the component is visible
=> perf(icon): render icon sooner if already visible or loaded

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/tile-group/tile-group.stories.ts, packages/calcite-components/src/components/tile-group/tile-group.tsx, packages/calcite-components/src/components/tile/resources.ts, packages/calcite-components/src/components/tile/tile.scss, packages/calcite-components/src/components/tile/tile.tsx, packages/calcite-components/src/demos/tile-group.html
**Related Issue:** #9252
This PR fixes Tile's `alignment="center"` option to only horizontally center the primary icon, heading and description.
=> fix(tile): apply center alignment only to x-axis

packages/calcite-components/src/components/tip-group/tip-group.tsx, packages/calcite-components/src/components/tip-manager/tip-manager.tsx, packages/calcite-components/src/components/tip/tip.tsx
**Related Issue:** #9228
Deprecates the `tip`, `tip-group` and `tip-manager` components with the following:
- Tip and Tip Manager: `carousel` and `carousel-item`
- Tip: `card`, `notice`, `panel`, or `tile`
=> docs(tip, tip-group, tip-manager): deprecate components

packages/calcite-components/src/components/select/select.e2e.ts, packages/calcite-components/src/components/select/select.tsx
**Related Issue:** #4461
This fixes an issue where the initial `value` would not match any `option`.
=> fix(select): fix option selection via initial `value`

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/block/block.scss
**Related Issue:** #9323
Update `block`'s padding.
=> fix(block): update text hierarchy and spacing

package-lock.json, package.json, packages/calcite-components/package.json
**Related Issue:** #9307
Add `type-fest` to the dependencies of `@esri/calcite-components` to prevent build errors. `type-fest` can also be used to simplify/remove the [preact type generator](https://github.com/Esri/calcite-design-system/blob/27a82dcaf8b091c609b3bf765d8c8617c447d8e7/packages/calcite-components/support/preact.ts#L8) in the future.
=> fix: add type-fest as dependency due to build error

package-lock.json, packages/calcite-components/package.json
Manually updates the `@esri/calcite-ui-icons` dependency to [`3.28.1`](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.28.1).
=> build(deps): update dependency @esri/calcite-ui-icons to v3.28.1

.github/workflows/remove-prerelease-changelog-entries.yml, documentation/monorepo.md, package.json, support/removePrereleaseChangelogEntries.ts
Ensure all pre-release changelog sections are removed before a `latest` release-please pull request is installed into the `main` or `hotfix` branches.
=> ci: ensure all pre-release changelog sections are removed

packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #9235
Exposes `autofocus` property to ensure the prop/attr is available on the `HTMLElement` type.
This should no longer be necessary once https://github.com/ionic-team/stencil/issues/5726 is fixed and available in Stencil.
=> fix(input, input-number, input-text): ensure autofocus is available on HTMLElement

packages/calcite-components/src/components/input-number/input-number.tsx, packages/calcite-components/src/components/input-text/input-text.tsx, packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #9235
Exposes `autofocus` property to ensure the prop/attr is available on the `HTMLElement` type.
This should no longer be necessary once https://github.com/ionic-team/stencil/issues/5726 is fixed and available in Stencil.
=> fix(input, input-number, input-text): ensure autofocus is available on HTMLElement (#9343)

packages/calcite-components/src/components/flow-item/flow-item.scss, packages/calcite-components/src/components/flow-item/flow-item.stories.ts, packages/calcite-components/src/components/flow-item/flow-item.tsx, packages/calcite-components/src/components/flow-item/resources.ts, packages/calcite-components/src/demos/flow.html
**Related Issue:** #8979
Add a new `content-bottom` slot to the `flow-item` component.
=> feat(flow-item): add content-bottom slot

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/dropdown-item/dropdown-item.scss, packages/calcite-components/src/components/dropdown-item/dropdown-item.tsx, packages/calcite-components/src/components/dropdown-item/resources.ts, packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
Removes unused CSS classes.
_Note_: Suggested to install after https://github.com/Esri/calcite-design-system/pull/9330
=> refactor(dropdown-item):  remove unused css classes

packages/calcite-components/src/utils/component.spec.ts, packages/calcite-components/src/utils/component.ts, packages/calcite-components/src/utils/loadable.ts
Adds a replacement `componentFocusable` util that does not depend on implementing `LoadableComponent`.
=> refactor: add simpler componentFocusable util (deprecates LoadableComponent)

packages/calcite-components/src/tests/commonTests/t9n.ts, packages/calcite-components/src/utils/t9n.ts
**Related Issue:** #9240
This updates the `t9n` module to use a noop function (instead of undefined) for the injected watcher callback when disconnected. This change addresses an issue where a component invokes watchers during disconnection.
=> fix(t9n): fix error caused by disconnecting components during the setting of initial message overrides

packages/calcite-components/src/components/text-area/text-area.scss
**Related Issue:** #8374
Removes bespoke disabled styling applied in addition to the common disabled style mixin.
=> fix(text-area): remove double transparency applied when disabled

packages/calcite-components/src/components/switch/resources.ts, packages/calcite-components/src/components/switch/switch.scss, packages/calcite-components/src/components/switch/switch.tsx
**Related Issue:** #7723
Prevents interaction states on switch when disabled.
=> fix(switch): prevent hover state change when disabled

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/accordion-item/accordion-item.e2e.ts, packages/calcite-components/src/components/accordion-item/accordion-item.tsx
**Related Issue:** #7211
Add `setFocus` method.
=> feat(accordion-item): add setFocus

.github/ISSUE_TEMPLATE/tooling.yml
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/9258
Adds a priority option to the tooling issue template, which will add a priority label upon creation. Sets the default priority to `p - low`.
=> chore: adds priority context to tooling issue template

packages/calcite-components/src/components/shell/shell.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/9275
Updates the `shell` slots to reflect `shell-panel` placement, as we move towards deprecation of the `shell-center-row`, anticipated for June/July 2024.
Also, includes a minor doc consistency improvement for the `"modals"`, `"alerts"`, and `"sheets"` slots to reflect `calcite-shell`.
=> docs(shell): modify panel-named slots to reflect shell-panel

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9321
This fixes an issue where references to internal elements were undefined in the window-level click handler. This would happen because the window click handler was added when the component was connected, but before its internals were rendered.
=> fix(combobox): fix error that occurs when a click is emitted when the component is appended to the DOM

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new-component.yml
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/9133
Updates the user impact dropdown selections to make the labels more clear using `"impact"`:
- `impact - p3 - not time sensitive`
- `impact - p2 - want for an upcoming milestone`
- `impact - p1 - need for current milestone`
- `impact - p0 - emergency`
Once approved and the PR has been merged, will modify the existing labels to reflect the above.
=> chore: refactor user defined priority selection

packages/calcite-components/src/components/dropdown-group/dropdown-group.scss, packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx, packages/calcite-components/src/components/dropdown/dropdown.stories.ts, packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #9350
`calcite-dropdown-group` title font-size scales with dropdown scale.
=> fix(dropdown-group): title scale with dropdown scale

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/stepper-item/stepper-item.e2e.ts, packages/calcite-components/src/components/stepper-item/stepper-item.tsx, packages/calcite-components/src/components/stepper/stepper.e2e.ts, packages/calcite-components/src/components/stepper/stepper.tsx
**Related Issue:** #2094 
Adds the following events:
* `calciteStepperChange` on `calcite-stepper`
* `calciteStepperItemChange` on `calcite-stepper-item`
Deprecates `calciteStepperItemChange` on `calcite-stepper`.
=> feat(stepper, stepper-item): add separate change events to stepper and items (deprecates `calciteStepperItemChange` on the parent)

packages/calcite-components/src/components/stepper-item/stepper-item.scss
Removes transitions per https://github.com/Esri/calcite-design-system/pull/8996#issuecomment-2027823945.
=> refactor(stepper-item): drop unnecessary transitions

packages/calcite-components/src/components/link/link.e2e.ts
Add token theming tests for `link`.
=> test(link): add token theming tests

.github/workflows/deploy-latest.yml, .github/workflows/deploy-next.yml
Enable npm provenance statements to improve supply-chain security for our users.
ref: https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools
=> ci: enable npm provenance statements

.github/workflows/deploy-latest.yml, package.json, packages/calcite-components-angular/projects/component-library/package.json, support/uploadReleaseAssets.ts
Upload dist files to the GitHub Releases after publishing to npm. I'm not sure why I thought release-please was already doing this. I tested locally with the following script, which correctly uploaded the dists, e.g. for release [`@esri/calcite-components: v2.8.0`](https://github.com/Esri/calcite-design-system/releases/tag/%40esri%2Fcalcite-components%402.8.0).
```sh
#!/usr/bin/env bash
mv support/uploadReleaseAssets.ts /tmp
git clean -fdx && git reset --hard
git checkout @esri/calcite-components@2.8.0
npm install
npm run build
mv /tmp/uploadReleaseAssets.ts support/
npx tsx support/uploadReleaseAssets.ts '["packages/calcite-components","packages/calcite-components-react","packages/calcite-components-angular/projects/component-library"]'
```
It might be time to recreate a VM so I can …
=> ci: upload dist to github releases

packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9321
This updates the combobox window-click listener to use an internal state property for its text instead of getting the value of the internal input. 
The `componentOnReady` util helps normalize waiting for a component to be ready in both output targets (based on [Ionic's helper](https://github.com/ionic-team/ionic-framework/blob/5cdfa1aaf47a6160cd1bd2be434dcfa8390b56e1/core/src/utils/helpers.ts#L60-L79)). This is sufficient for most scenarios, but for this particular case, it was running earlier than `connectedCallback` due to the emitted click as the component is appended and initialized, so the component is not yet rendered by the time the util resolves.
**Note**: there are no accompanying tests as this is not reproducible in the test environment, which uses the …
=> fix(combobox): fix error that occurs in dist-custom-elements (components) output when a click is emitted when the component is appended to the DOM

packages/calcite-components/package.json, packages/calcite-components/support/cleanupDistFiles.sh
Remove unnecessary files that somehow ended up in `dist` before publishing to NPM.
=> build: remove unnecessary dist files before publishing

.renovaterc.json
Set [`prBodyTemplate`](https://docs.renovatebot.com/configuration-options/#prbodytemplate) to remove the noisy sections, which end up in the commit message when merging.
=> ci(renovate): remove noisy sections from the PR body

.release-please-manifest.json, packages/calcite-components-angular/projects/component-library/CHANGELOG.md, packages/calcite-components-react/CHANGELOG.md, packages/calcite-components/CHANGELOG.md, packages/calcite-components/readme.md, packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx, packages/calcite-components/src/utils/floating-ui.spec.ts, packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #9438
Sync changes from the `2.8.4` hotfix release to `main`.
=> chore: sync hotfix to main

.github/workflows/deploy-latest.yml, .github/workflows/deploy-next.yml
**Related Issue:** #9429
Update the deployment GitHub Actions according to steps in the [npm provenance doc](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions), which I missed because I was looking at the 3rd party section below it.
The [GitHub provenance doc](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) doesn't mention permissions, so it might not be required.
We had originally hardcoded an older version of Ubuntu in #5942 due to errors, but it was resolved in Stencil v4.
=> ci(provenance): add missing options from setup doc

packages/calcite-components-react/package.json, packages/eslint-plugin-calcite-components/package.json
- Add repository URL to package.json files that were missing the field, which is [required for provenance](https://github.com/Esri/calcite-design-system/actions/runs/9279905717/job/25533608990#step:4:16776).
- Sort the package.json files with `npx sort-package-json`.
This is the last missing configuration for provenance; Calcite components and the angular wrapper already published successfully:
https://www.npmjs.com/package/@esri/calcite-components/v/2.9.0-next.24#provenance
=> ci: add repo url to package.json files for provenance

packages/calcite-components/src/components/navigation-logo/navigation-logo.e2e.ts
Updates theming test to use sub-component token as targetProp in `navigation-logo` component.
=> test(navigation-logo): use sub-component token for theming test

.github/workflows/deploy-latest.yml
**Related Issue:** #9428
The new [script](https://github.com/Esri/calcite-design-system/blob/main/support/uploadReleaseAssets.ts) for uploading release assets failed after `2.9.0` was deployed:
```sh
> calcite-design-system@0.0.0 util:upload-release-assets
﻿2024-05-29T06:43:20.4633461Z > tsx support/uploadReleaseAssets.ts [packages/calcite-components,packages/calcite-components-react,packages/calcite-components-angular/projects/component-library]
SyntaxError: Unexpected token 'p', "[packages/c"... is not valid JSON
at JSON.parse (<anonymous>)
at <anonymous> (/home/runner/work/calcite-design-system/calcite-design-system/support/uploadReleaseAssets.ts:10:35)
```
The quotes were removed from the [`paths_released`](https://github.com/googleapis/release-please-action#outputs) value, which …
=> ci(assets): stringify list of paths for released packages

packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
Add token theming tests for `tooltip` component.
=> test(tooltip): add token theming tests

packages/calcite-components/src/components/popover/popover.e2e.ts
Add token theming tests for `popover` component.
=> test(popover): add token theming tests

packages/calcite-components/src/components/panel/panel.e2e.ts, packages/calcite-components/src/components/panel/panel.scss
Add token theming tests for `panel` component.
=> test(panel): add token theming tests

packages/calcite-components/src/components/modal/modal.e2e.ts
Add token theming tests for `modal`.
=> test(modal): add token theming tests

packages/calcite-components/src/components/combobox/combobox.tsx, packages/calcite-components/src/components/dropdown/dropdown.tsx, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/popover/popover.tsx, packages/calcite-components/src/components/tooltip/tooltip.tsx
**Related Issue:** #9468
https://github.com/Esri/calcite-design-system/pull/9443 introduced a regression caused by using the `componentOnLoad` util to consolidate initialization logic shared between `connectedCallback` and `componentDidLoad`. The util appears to resolve at a different time in the `components` output target, which messed up with initialization of certain components.
**Note**: there are no accompanying tests as this is not reproducible in the test environment, which uses the lazy-loaded output.
=> fix(combobox, dropdown, input-date-picker, popover, tooltip): fix initialization logic in components output target

packages/calcite-components/src/components/pagination/pagination.e2e.ts, packages/calcite-components/src/components/pagination/pagination.scss, packages/calcite-components/src/components/pagination/pagination.tsx, packages/calcite-components/src/components/pagination/resources.ts, packages/calcite-components/src/components/table/table.e2e.ts
**Related Issue:** #7804
- render a list and list items internally
- add test to ensure future compliance
=> fix(pagination): use semantic internal elements

packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #8028
- do not cut off menu actions
- `position:relative` on the container class within the panel seems to fix the safari issue. Not sure how we can test this without manual testing or getting different browser screenshots setup.
@geospatialem @DitwanP could one of you help test this fix?
=> fix(panel): prevent menu actions from being clipped in Safari

packages/calcite-components/src/components/popover/popover.tsx
**Related Issue:** #9504
This fixes an issue where any clicks when the popover is connected to the DOM would cause it to be immediately closed.
This would happen because `PopoverManager`'s window `click` handler was being added and invoked during `connectedCallback` and not after the component was initialized (somewhat similar to https://github.com/Esri/calcite-design-system/pull/9373).
**Note**: there are no accompanying tests as this is not reproducible in the test environment, which uses the lazy-loaded output.
=> fix(popover): prevent closing when component is connected to the DOM via a click

packages/calcite-components/src/components/block-section/block-section.e2e.ts, packages/calcite-components/src/components/block-section/block-section.scss, packages/calcite-components/src/components/block-section/block-section.tsx, packages/calcite-components/src/components/block-section/resources.ts
**Related Issue:** #9454
Fixes toggling issue caused by moving switch outside toggle container.
This regression was introduced by #9194.
=> fix(block-section): restore block toggling when clicking on the header switch

packages/calcite-components/src/components/block/block.tsx
**Related Issue:** #8037
- Add aria-labelledby to internal control container for enhanced accessibility.
=> fix(block): add accessible label for slotted controls

packages/calcite-components/src/components/tooltip/tooltip.stories.ts
**Related Issue:** [#9537](https://github.com/Esri/calcite-design-system/issues/9537)
Refactors the interface within [`tooltip.stories.ts`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/tooltip/tooltip.stories.ts) to use props from the component's class.
=> refactor(storybook): refactor tooltip simple story interface

packages/calcite-components/.stylelintrc.json
Enables [`selector-pseudo-element-colon-notation`](https://stylelint.io/user-guide/rules/selector-pseudo-element-colon-notation/) for consistent pseudoelement syntax (CSS3).
=> chore(linting): enable selector-pseudo-element-colon-notation rule

.github/workflows/deploy-prerelease.yml
Use an absolute path to the pre-release publishing script, because I'm not sure where relative paths start from.
=> ci(prerelease): use absolute path to publish script

packages/calcite-components/src/components/split-button/split-button.e2e.ts, packages/calcite-components/src/components/split-button/split-button.stories.ts, packages/calcite-components/src/components/split-button/split-button.tsx
**Related Issue:** #9542
- add placement and flipPlacements property
- add tests
- add story
=> feat(split-button): add placement and flipPlacements property

packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9401
- Toggles the combobox's open property when typing within the input
- If the value.length > 0, the combobox is opened otherwise its closed
- adds test
=> fix(combobox): open the component when typing within it

packages/calcite-components/src/components/date-picker/date-picker.e2e.ts
**Related Issue:** #9422 
This PR removes a skipped test change and a `describe.only` test.
=> test(date-picker): removing describe.only and skipped test missed in PR for #9422

package-lock.json, package.json, packages/calcite-components/src/utils/config.spec.ts, packages/calcite-components/src/utils/config.ts, packages/calcite-components/src/utils/globalScript.ts, packages/calcite-components/stencil.config.ts
**Related Issue:** #8848
This updates the globalScript to stamp the version onto an existing global calciteConfig var and will create one if not defined.
=> feat: include version in global config

packages/calcite-components/src/components/color-picker/color-picker.e2e.ts, packages/calcite-components/src/components/color-picker/color-picker.scss, packages/calcite-components/src/components/color-picker/color-picker.stories.ts, packages/calcite-components/src/components/color-picker/color-picker.tsx, packages/calcite-components/src/components/color-picker/resources.ts, packages/calcite-components/src/components/color-picker/utils.ts
**Related Issue:** #9412
This decreases the size of thumbs and uses the component's scale for the color preview when alpha channel is not displayed.
=> feat(color-picker): adjust thumb and color preview sizes to follow updated spec

packages/calcite-components/src/components/tile/tile.tsx
**Related Issue:** #9582
This PR exposes `calcite-tile`'s `selected` property so that it won't throw typescript errors when compiled.  This was made internal unintentionally as other components like `calcite-chip` expose this property.
=> fix(tile): expose selected property

packages/calcite-components/src/components/action/action.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.e2e.ts, packages/calcite-components/src/components/tree-item/tree-item.scss
Updates tree-item tokens and adds themed e2e tests
=> fix(tree-item): update tokens and tests

packages/calcite-components/src/components/date-picker-month/date-picker-month.scss
**Related Issue:** #7180 #9524
Date-picker-month .week-header should use --calcite-font-weight-bold
=> fix(date-picker-month): use font-weight bold

packages/calcite-components/src/components/list/list.tsx, packages/calcite-components/src/components/sortable-list/sortable-list.tsx, packages/calcite-components/src/components/value-list/value-list.tsx, packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #9521
- Makes sure that `connectSortableComponent` isn't called during an active drag of a sortable item.
- Previously, mutation observers were calling `connectSortableComponent` during a drag
- This caused the existing implementation to be destroyed and a new one created which left the user in a frozen state.
- This only occurred on mobile devices because mobile devices do not use native drag and drop with Sortable.js
- The fix makes sure that `connectSortableComponent` and `disconnectSortableComponent` do nothing during an active drag.
=> fix(list): fix mobile device dragging with nested lists

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/combobox/combobox.e2e.ts, packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #6776
- When a chip is focused, the activeChipIndex is updated
- Only allow tabindex on one chip or the input.
- Adds tests
=> fix(combobox): fix navigating initially when multiple items are selected

packages/calcite-components/src/components.d.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts, packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx, packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.stories.ts, packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/9491
Focuses input element on `setFocus` method.
=> fix(input-date-picker, input-time-picker): focus input element on `setFocus`

packages/calcite-components/src/components/carousel/carousel.e2e.ts, packages/calcite-components/src/components/carousel/carousel.tsx
**Related Issue:** #9620 
Adds a check for `autoplay` in our keyboard interaction handler. Adds a test to confirm behavior.
=> fix(carousel): Prevent unexpected keyboard `autoplay` activation

.github/ISSUE_TEMPLATE/accessibility.yml, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/refactor.yml, .github/workflows/chromatic.yml, .github/workflows/pr-e2e.yml, .github/workflows/schedule-updates.yml, documentation/monorepo.md, packages/calcite-components-angular/projects/component-library/README.md, packages/calcite-components/conventions/Accessibility/AccessibilityDeveloper.md, packages/calcite-components/conventions/Internationalization.md, packages/calcite-components/conventions/README.md, packages/calcite-components/conventions/Testing.md, packages/calcite-components/src/components/color-picker/color-picker.tsx, packages/calcite-components/src/components/functional/FloatingArrow.tsx, packages/calcite-components/src/components/pick-list-item/pick-list-item.tsx, packages/calcite-components/src/components/slider/slider.tsx, packages/calcite-components/src/components/tab-title/tab-title.tsx, packages/calcite-components/src/components/value-list-item/value-list-item.tsx, packages/calcite-components/src/utils/floating-ui.ts, packages/calcite-components/stencil.config.ts
- Remove Chromatic from `main`, since it will already have ran on `dev`.
- Fix the scheduled update jobs, which where still creating PRs targeting
`main`. Thankfully I left the 6 approvals rule because I definitely tried to
merge those with `gh` :sweat_smile:
- Change the branch of code URLs from `main` to `dev`. Side note: maybe we
could use the rollup plugin from #9536 to pin the version tag in the API
reference code links. That way docs-json will point to the actual version's
code instead of whatever is currently on `dev` or `main`.
=> chore: change additional instances of main to dev
