Esri/calcite-design-system

- package-lock.json
- package.json
Doesn't seem like I can re-open that PR because of the GH organization move... here's another one....
Updates core, sass, state-tunnel to latest versions
> Bumps stencil version

- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-alert/calcite-alert.tsx
- src/components/calcite-alerts/calcite-alerts.tsx
Adds dark theme color values
Updates internal id name -> alertId
Adds delay to initial animation to be more reliable
> Updates to alerts

- package-lock.json
- package.json
- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-checkbox/calcite-checkbox.scss
- src/components/calcite-loader/calcite-loader.scss
- src/components/calcite-progress/calcite-progress.scss
- src/components/calcite-radio-group/calcite-radio-group.scss
- src/components/calcite-slider/calcite-slider.scss
- src/components/calcite-switch/calcite-switch.scss
- src/components/calcite-tabs/calcite-tabs.scss
Updated all SCSS color variables to the new set from [calcite-colors](https://github.com/Esri/calcite-colors/blob/master/colors.scss#L464). Both light and dark theme.
> Color ui variables

- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- package-lock.json
- package.json
- src/components/calcite-alert/readme.md
- src/components/calcite-alerts/readme.md
- src/components/calcite-button/readme.md
- src/components/calcite-loader/readme.md
- src/components/calcite-radio-group/readme.md
- stencil.config.ts
- support/release.sh
This preps for the beta 1 release. Which I will run as soon as this gets merged and I have admin privileges on this repo.
> Prep for beta 1 release

- src/components/calcite-button/calcite-button.scss
- removes outline:none on all but inline link items
- flips animation of inline link item in rtl
- uses new calcite color variables
- updates focus style
> Buttons update

- package-lock.json
- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-alert/calcite-alert.tsx
- src/components/calcite-alerts/calcite-alerts.tsx
- fixes typos in doc comments
- adds css variables and cleans up styles
- sets element dir and adds associated styles
> Alerts update - Fixes typos, adds css vars, sets element dir

- readme.md
we can remove some of the "in progress" warnings now that we are starting to publish to npm.
> update readme, remove link to docs (#80)

- src/components/calcite-button/calcite-button.scss
- src/components/calcite-button/calcite-button.tsx
- src/index.html
Moves position of icon in inline links to trailing position, improves styling of icons in inline links
Improves design of loading state, prevents clicking loading state buttons
> Updates buttons

- CHANGELOG.md
- src/components/calcite-slider/calcite-slider.scss
- src/components/calcite-slider/calcite-slider.tsx
- src/index.html
- bug where dragging the slider handle had wacky behavior inside parent elements with new offset coordinates
- update formatting for slider comments
- change blue color of slider for dark theme
> fix incorrect drag behavior in calcite-slider, add dark theme

- CHANGELOG.md
- src/components/calcite-radio-group-item/calcite-radio-group-item.scss
- src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
- src/components/calcite-radio-group/calcite-radio-group.scss
- src/components/calcite-radio-group/calcite-radio-group.tsx
- src/index.html
- Updates styles a bit to match those from recent designs.
- Adds scale prop (s/m/l)
- Adds prop validation for theme, scale
- Prettifies files
- Updates preview bg color of index.html
> Adds scale prop to radio group, updates style

- src/components/calcite-button/calcite-button.scss
Fix for https://github.com/Esri/calcite-components/issues/146
> Adjusts styling of buttons to render :host full height

- package-lock.json
- package.json
- src/assets/styles/includes.scss
- src/components/calcite-popover/calcite-popover.e2e.ts
- src/components/calcite-popover/calcite-popover.scss
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-popover/readme.md
- src/components/calcite-popover/resources.ts
- src/index.html
- src/tests/commonTests.ts
- src/tests/setup.js
- stencil.config.ts
@julio8a this is what a port to calcite-components would look like.
> CalcitePopover component

- src/components/calcite-popover/calcite-popover.tsx
Popover: separate reposition method a bit
> Popover: separate reposition method a bit

- src/components/calcite-button/calcite-button.scss
- src/components/calcite-button/calcite-button.tsx
- src/index.html
Creates proxy element for button associated with form
Adds disabled style to rendered span child element
Adds example
Logic from ionic button, but adds ability to use button with named associated form outside of form itself - https://github.com/ionic-team/ionic/blob/bf2953cf85c078b0fd567e51208eacd5dc9b87cd/core/src/components/button/button.tsx#L150
> Add ability to submit buttons in forms

- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-popover/resources.ts
- src/index.html
Popover: Make placement options consistent with Tooltip
Allows for more advanced placement of popovers.
> Popover: Make placement options consistent with Tooltip

- CONTRIBUTING.md
- readme.md
Also adds reminder to bump example version number :)
> Bumps example version number

- src/components/calcite-dropdown-group/calcite-dropdown-group.scss
- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-dropdown/calcite-dropdown.scss
- added 2px border radius
- updated border color
- added new calcite-color variables
- updated text colors
> dropdown styling updates

- package-lock.json
- src/components/calcite-button/calcite-button.scss
- src/index.html
From the conversation we had Friday I:
- updated solid dark (light and dark theme)
- removed border from solid buttons
> updated solid dark button and removed borders on primary buttons

- CHANGELOG.md
- src/assets/styles/_mixins.scss
- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
multiple bug fixes for the modal component, works in Edge now!
> Modal fixes

- src/components/calcite-button/calcite-button.tsx
- src/index.html
Check for target form onsubmit,  and call that if present.
Added example of combinations of button types, onclick, onsubmit examples
Is this too simple a check? In React will onSubmit need to be accounted for (etc)? Would anything more custom best be implemented by a consumer on a `type="button"` onClick?
cc @kevindoshier
> Use supplied onsubmit function, if present, for button submit

- src/components/calcite-modal/calcite-modal.scss
- src/index.html
- fix for Safari header / footer sizing issues affecting small viewport sizes
- fix for "back" button slot not rendering full width on small viewport sizes
- fix for space not being added to buttons in Edge on small viewport sizes
- updates styles based on requested changes in https://github.com/Esri/calcite-components/issues/191
- Some variable updates
> Modal styling updates / fixes

- CHANGELOG.md
- src/components/calcite-accordion-item/calcite-accordion-item.e2e.ts
- src/components/calcite-accordion-item/calcite-accordion-item.scss
- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-accordion-item/readme.md
- src/components/calcite-accordion/calcite-accordion.e2e.ts
- src/components/calcite-accordion/calcite-accordion.scss
- src/components/calcite-accordion/calcite-accordion.stories.js
- src/components/calcite-accordion/calcite-accordion.tsx
- src/components/calcite-accordion/readme.md
- src/index.html
- stencil.config.ts
- adds new component - accordion
- adds storybook entry
- adds basic tests
- updates changelog, fixes changelog typo
I think this is a good candidate for a better focus style - currently the "focus / hover / active" combinations are a bit too subtle IMO cc @bstifle
> Adds accordion component

- src/components/calcite-popover/calcite-popover.scss
#218
Border radius.
@macandcheese I made it 3px. Eh?
> style(popover): added border-radius

- CHANGELOG.md
- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.stories.js
- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-modal/readme.md
Had a situation where I needed to use the modal with a fullscreen element, and the padding around the edges of the modal content caused issues.
> add no-padding prop to modal, prettier modal ✨ 

- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-accordion/calcite-accordion.stories.js
- src/index.html
Adds check to make sure click is not on a child item
Updates demos to have a focusable element in the item
> Fix for keyboard event on child items closing dropdown item

- CHANGELOG.md
- src/components/calcite-dropdown/calcite-dropdown.stories.js
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-dropdown/readme.md
- src/index.html
- Adds type prop/attribute with "hover" and "click" as options - defaults to "click" (previous functionality)
- Updates example on demo index page and Storybook
> Adds hover type to dropdown

- src/components/calcite-button/calcite-button.scss
Updates to variable names to fix styling issues.
> Update scss vars

- CONTRIBUTING.md
- readme.md
Update for https://github.com/Esri/calcite-components/issues/258
cc @noahmulfinger - can't add you as reviewer for some reason...
> Update docs for including global stylesheet, update contributing docs

- CHANGELOG.md
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-button/readme.md
- src/components/calcite-modal/readme.md
- src/components/calcite-notice/calcite-notice.tsx
- src/components/calcite-notice/readme.md
- src/index.html
- src/utils/dom.ts
Follow up from Teams convo: https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1576262145551?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1576262145551&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1576262145551
Adds method to focus a `calcite-button`, a little prop and doc cleanup.
> Adds focusCalciteButton method

- CHANGELOG.md
- src/components/calcite-notice/calcite-notice.scss
- src/components/calcite-notice/calcite-notice.tsx
- src/index.html
- update style of notice to use new shadow level
- update sizing of scale variants
- setFocus() on a notice element will now focus a slotted calcite-button in the notice-link slot
- add example of focus functionality
> Update notice style and focus handling

- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-notice/calcite-notice.scss
- ensure only icon color gets set based on attribute, not text content
> Updates alert and notice style

- src/components/calcite-button/calcite-button.scss
- src/index.html
Fix for https://github.com/Esri/calcite-components/issues/284 
cc @dhrumil83
> Fixes misaligned full width button when icon present

- src/components/calcite-date/calcite-date-picker.scss
- src/components/calcite-pagination/calcite-pagination.scss
- src/components/calcite-popover/calcite-popover.scss
- src/components/calcite-radio-group/calcite-radio-group.scss
- src/components/calcite-tooltip/calcite-tooltip.scss
- src/demos/calcite-modal.html
- src/index.html
- updated the border radius display on: tooltip, popover & date
- added calcite-date page to homepage list
> Design (BR) bug fixes

- src/components/calcite-popover/calcite-popover.e2e.ts
- src/components/calcite-popover/calcite-popover.tsx
Calcite-popover: Event call back on close of a popover. #290
> Calcite-popover: Event call back on close of a popover. #290

- src/components/calcite-button/calcite-button.stories.js
Adds some examples to the button storybook..
Side note - anyone have a configuration in vs code that can format these files? No combination of language / formatter seems to do anything with storybook files :(
> Update button storybook examples

- CHANGELOG.md
- package-lock.json
- package.json
- readme.md
The release process wouldn't allow me to update this directly, so I'm submitting this PR in the meantime.
> v1.0.0-beta.18 content

- stencil.config.ts
Adds https://github.com/Esri/calcite-components/issues/323
Also adds a couple of missing bundles, and alphabetizes bundle list
> Add appendChildSlotFix, Add missing bundles, organize bundles

- package-lock.json
- package.json
Adds NPM script to make dependency updating easier.
Uses https://www.npmjs.com/package/updtr to update all dependencies (runs tests on each one and only updates the passing ones) and commits on success.
> build(deps): add dependency updating script

- CHANGELOG.md
- src/components/calcite-accordion-item/calcite-accordion-item.scss
- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-notice/calcite-notice.scss
Fixes for https://github.com/Esri/calcite-components/issues/329
Accordion:
- fix incorrect alignment of text content in accordion item headers in RTL
Alert:
- fix icon spacing inconsistencies between LTR / RTL
Notice:
- fix icon spacing inconsistencies between LTR / RTL
- fix the border of the notice appearing on the wrong side in RTL
Updates changelog
> Fix RTL style issues for accordion, alert, notice

- src/components/calcite-accordion-item/calcite-accordion-item.scss
- src/components/calcite-accordion/calcite-accordion.scss
- src/components/calcite-accordion/calcite-accordion.tsx
- src/demos/calcite-accordion.html
Removes border from beneath title of active accordion item
Removes tabindex from accordion container to allow tabbing through accordions
Add example of nested accordion to dev demo
> Updates accordion style and tabindex

- src/components/calcite-popover/calcite-popover.tsx
#342 add setFocus method to popover to focus on the close button.
> Add setFocus method to popover to focus on the close button.

- src/assets/demo/createAlert.js
- src/components/calcite-alert/calcite-alert.stories.js
This adds example of adding / removing alerts from the alert queue (as well as open and close functionality)
> Add example of queued alerts to Storybook

- .storybook/helpers.js
- src/components/calcite-button/calcite-button.stories.js
- src/components/calcite-icon/calcite-icon.stories.js
Related issue: #336 
This also restores the icon selection in the _simple_ icon story.
> refactor(storybook): extract iconNames constant

- src/components/calcite-slider/calcite-slider.scss
- src/components/calcite-slider/calcite-slider.tsx
- moved the theming to using the `calcite-ui-` variables from the theme
- stoped using css vars to do dynamic left/right positioning
- fixed ticks
- everything works in ie
> #375 🐞 fix calcite-slider in ie11, ✨ cleanup

- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
mostly came down to differences in defaults/behavior for flexbox layouts.
> 🐞 Fix modals in ie11

- src/components/calcite-progress/calcite-progress.scss
- src/components/calcite-progress/calcite-progress.tsx
Another one that was broken due to dynamic updating of css variables.
[#373]
> 🐞 fix progress bar in ie11

- src/components/calcite-loader/calcite-loader.scss
@bstifle this took me basically all day
> determinate loader should start at top

- src/components/calcite-card/calcite-card.e2e.ts
- src/components/calcite-card/calcite-card.scss
- src/components/calcite-card/calcite-card.tsx
- src/components/calcite-card/resources.ts
- src/demos/calcite-card.html
Fix for https://github.com/Esri/calcite-components/issues/367
Just some picky flexbox and positioning stuff mostly. Also added back looking up the dir and explicitly adding it to the component (removes :host-context).
> Fix card ie11 styling and tests

- CHANGELOG.md
> Updates changelog for new dropdown attribute / prop

- src/components/calcite-accordion-item/calcite-accordion-item.tsx
Cleans up typo in click handler naming
> Fix naming of click handler in accordion item

- readme.md
add a browser support table and current npm version badge to readme
> add browser support and npm version to readme

- src/components/calcite-stepper-item/calcite-stepper-item.scss
- src/components/calcite-stepper-item/calcite-stepper-item.tsx
- src/components/calcite-stepper/calcite-stepper.tsx
Fixes issue in Edge where stepper content would not display for active item in horizontal alignment
Fixes issue in IE where icon would get squished depending on size of container
Another update to fix display in IE upcoming....
> Edge - fixes stepper content not displaying in horizontal layout

- package-lock.json
- package.json
> chore: Bump popper dep

- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
- src/utils/popper.ts
fix(popper): typings for newer Popper.js version
> fix(popper): typings

- CHANGELOG.md
- src/components/calcite-date/calcite-date.e2e.ts
- src/components/calcite-icon/readme.md
- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.scss
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-input/readme.md
- src/components/calcite-radio-group/readme.md
- src/demos/calcite-input.html
Fixes incrementing number type input with appended buttons
Removes custom textarea resize handle in ie11
Fixes display of custom textarea resize handle in Firefox
Updates style of incrementing number buttons
Fixes tests for input
> Small updates for input component, text fixes

- src/components/calcite-tree/readme.md
end tags were formatted incorrectly
> Update readme.md for calcite-tree

- CHANGELOG.md
- src/components/calcite-pagination/calcite-pagination.scss
- src/components/calcite-pagination/calcite-pagination.stories.js
- src/components/calcite-pagination/calcite-pagination.tsx
- src/components/calcite-pagination/readme.md
- src/demos/calcite-pagination.html
Style updates for https://github.com/Esri/calcite-components/issues/502, using explicit values until a space / font size scale is decided upon after next week's meeting.
> Update pagination style

- CHANGELOG.md
- src/components/calcite-accordion-item/calcite-accordion-item.scss
- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-accordion-item/readme.md
- src/components/calcite-accordion/calcite-accordion.e2e.ts
- src/components/calcite-accordion/calcite-accordion.stories.js
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-stepper-item/calcite-stepper-item.scss
- src/demos/calcite-accordion.html
Adds prop for icon in calcite-accordion-item
Updates title of calcite-accordion-item and calcite-stepper-item to be 500 weight at all times
Updates accordion test, dev demo, storybook, changelog
Various formatting updates from auto-generated readme
Adds https://github.com/Esri/calcite-components/issues/508 cc @bpatterson88
> Adds support for icons in calcite-accordion-item

- src/components/calcite-date-day/calcite-date-day.scss
- src/components/calcite-date-day/calcite-date-day.tsx
- src/components/calcite-date-month-header/calcite-date-month-header.scss
- src/components/calcite-date-month-header/calcite-date-month-header.tsx
- src/components/calcite-date-month/calcite-date-month.scss
- src/components/calcite-date/calcite-date.scss
- src/components/calcite-date/calcite-date.tsx
- hide next/prev buttons if out of range 🤸‍♂️ 
- fix baseline alignment of month + year in header 📏 
- make sure paddles are square 🚣
- optically center number in date circle  👁️
- remove shadow on always open calendar 👐
> Small updates to date style from feedback #446

- CHANGELOG.md
- src/components/calcite-chip/calcite-chip.e2e.ts
- src/components/calcite-chip/calcite-chip.scss
- src/components/calcite-chip/calcite-chip.stories.js
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-chip/readme.md
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-notice/calcite-notice.tsx
- src/components/calcite-notice/readme.md
- src/demos/calcite-chip.html
resolves #490 
I think I got everything (storybook, tests, etc), but please take a close look as this is my first PR to this repo.
> calcite-chip - don't show X unless new dismissible property is true

- CHANGELOG.md
- src/components/calcite-icon/readme.md
- src/components/calcite-radio-group-item/calcite-radio-group-item.e2e.ts
- src/components/calcite-radio-group-item/calcite-radio-group-item.scss
- src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
- src/components/calcite-radio-group-item/readme.md
- src/components/calcite-radio-group/calcite-radio-group.stories.js
- src/demos/calcite-radio-group.html
Users can now add icon and icon-position props to radio group items
Adds dev demo, storybook, tests
Updates changelog
Addresses #550
>  Add support for icons in radio group items

- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
Popover/Tooltip: Use @Listener for events. 
Refactor code to use Stencil listeners instead of doing it the manual way.
> Popover/Tooltip: Use @Listener for events. 

- src/components/calcite-slider/readme.md
Use attribute instead of props in code sample
Remove `label` as it's currently not a defined prop / attribute
Finders fee ➡️@jgibson02
> Update slider docs

- src/components/calcite-loader/readme.md
- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-scrim/calcite-scrim.e2e.ts
- src/components/calcite-scrim/calcite-scrim.scss
- src/components/calcite-scrim/calcite-scrim.stories.js
- src/components/calcite-scrim/calcite-scrim.tsx
- src/components/calcite-scrim/readme.md
- src/components/calcite-scrim/resources.ts
- src/components/calcite-scrim/usage/basic.md
- src/demos/calcite-scrim.html
- src/index.html
- stencil.config.ts
New Component: Calcite-scrim #252
We want a more widespread component for loading and disabled states. Gonna make our calcite-app functional component into a calcite "component component" that can be used in this repo and brought into arcgis-components (for Dhrumil).
Maybe related to loading / skeleton states? #163
> feat(scrim): New calcite-scrim component

- src/components/calcite-popover-manager/calcite-popover-manager.e2e.ts
- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-popover-manager/readme.md
- src/components/calcite-popover/calcite-popover.tsx
Popover enhancement request #509
> Popover: Add `auto-close` property to handle closing all open popovers

- CHANGELOG.md
- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-dropdown-item/calcite-dropdown-item.tsx
- src/components/calcite-dropdown/calcite-dropdown.scss
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/demos/calcite-dropdown.html
Fix for nested children of "dropdown-trigger" slot not causing dropdown to open - Fixes #543 and Fixes #528
Fix inconsistency in open / close animation in center aligned dropdown - Fixes #526
> Various fixes for calcite-dropdown

- CHANGELOG.md
- src/components/calcite-modal/readme.md
- src/components/calcite-popover/readme.md
- src/components/calcite-scrim/readme.md
- src/components/calcite-split-button/calcite-split-button.stories.js
- src/components/calcite-split-button/calcite-split-button.tsx
- src/components/calcite-split-button/readme.md
- src/demos/calcite-split-button.html
> Adds ellipsis icon option for split-button dropdown trigger

- CHANGELOG.md
- src/components/calcite-chip/calcite-chip.e2e.ts
- src/components/calcite-chip/calcite-chip.scss
- src/components/calcite-chip/calcite-chip.stories.js
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-chip/readme.md
- src/components/calcite-combobox-item/calcite-combobox-item.tsx
- src/components/calcite-combobox/calcite-combobox.scss
- src/components/calcite-combobox/calcite-combobox.stories.js
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-combobox/readme.md
- src/demos/calcite-chip.html
- src/demos/calcite-combobox.html
Contains various requested chip updates cc @bstifle @julio8a
BREAKING - removes XS and XL scale from chip
BREAKING - removes XS and XL scale from combobox
Adds "color" prop to chip
Adds "appearance" prop to chip
Updates chip style and dimensions
Adds a set of tests to calcite-chip to test for props and dismissible
Resolves #462, Resolves #461, Resolves #536
> BREAKING: Various Chip / Combobox updates and enhancements

- CHANGELOG.md
- src/components/calcite-input/calcite-input.scss
- src/components/calcite-input/calcite-input.tsx
- src/demos/calcite-input.html
Update dev demo
Update changelog
Fix style of scale large icon
Fixes #597 cc @jcfranco
> Fix display of icon when prefix-text is set

- CHANGELOG.md
- src/components/calcite-alert/calcite-alert.scss
Fixes #604  cc @cosbyr 
- Update style to fix RTL display issues
- Ensure alerts with close button or icon are sized the same as those without - there were some small px differences due to padding
- Small css changes to better animate progress bar
- Update changelog
Choppy gif demo:
> [calcite-alert] Fix alert auto dismiss progress direction in RTL

- CHANGELOG.md
- src/components/calcite-radio-group/calcite-radio-group.e2e.ts
- src/components/calcite-radio-group/calcite-radio-group.scss
- src/components/calcite-radio-group/calcite-radio-group.stories.js
- src/components/calcite-radio-group/calcite-radio-group.tsx
- src/components/calcite-radio-group/readme.md
- src/demos/calcite-radio-group.html
re #615
* Added `width` prop to RadioGroup
* Added related styles to RadioGroup
* Added related styles for RadioGroupItem
* e2e
* readme
> RadioGroup - add width prop

- src/components/calcite-accordion/readme.md
- src/components/calcite-progress/calcite-progress.tsx
- src/components/calcite-progress/readme.md
> Update progress value prop description

- src/components/calcite-accordion/readme.md
- src/components/calcite-progress/calcite-progress.scss
- src/components/calcite-progress/calcite-progress.stories.js
- src/components/calcite-progress/calcite-progress.tsx
- src/components/calcite-progress/readme.md
- src/demos/calcite-progress.html
> Fix progress `reversed` behavior

- src/components/calcite-progress/calcite-progress.scss
> Center align progress text and align size with loader

- CHANGELOG.md
- src/components/calcite-popover/calcite-popover.scss
- src/demos/calcite-popover.html
re #636 
* Removed max-width
* Updated CHANGELOG
* Tweak to demo-app
> feat(popover): remove max-width

- CHANGELOG.md
Moves changelog entry from the past to the future 🧙🔮
> Updates changelog entry

- src/components/calcite-button/calcite-button.scss
- src/components/calcite-button/calcite-button.tsx
Resolves https://github.com/Esri/calcite-components/issues/578 cc @driskull cc @paulcpederson
> Prevent events on disabled buttons

- src/components/calcite-slider/calcite-slider.scss
- src/components/calcite-slider/calcite-slider.tsx
Fixes https://github.com/Esri/calcite-components/issues/664
> Moving transformed slider handle results in hyphenation display issues

- src/components/calcite-slider/calcite-slider.scss
> feat(slider): update disabled style 

- conventions/README.md
> 📜 Add note about using existing DOM events to conventions doc

- src/components/calcite-link/calcite-link.scss
- src/components/calcite-link/calcite-link.tsx
> Update disabled calcite-link handling

- src/components/calcite-popover-manager/calcite-popover-manager.e2e.ts
- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
- src/components/calcite-tooltip/calcite-tooltip.e2e.ts
- src/utils/dom.ts
> Fix for issue 692

- src/components/calcite-card/calcite-card.tsx
@macandcheese could use some guidance on the event detail type part.
> chore(card): rename select event and remove el from event detail

- CHANGELOG.md
- src/components/calcite-card/readme.md
- src/components/calcite-tab-nav/calcite-tab-nav.tsx
- src/components/calcite-tab-title/calcite-tab-title.scss
- src/components/calcite-tab-title/calcite-tab-title.tsx
- src/components/calcite-tab-title/readme.md
- src/components/calcite-tab/calcite-tab.scss
- src/components/calcite-tab/calcite-tab.tsx
- src/components/calcite-tab/readme.md
- src/components/calcite-tabs/calcite-tabs.e2e.ts
- src/components/calcite-tabs/calcite-tabs.stories.js
- src/demos/calcite-tabs.html
Resolves #475 👍 
BREAKING CHANGES:
- 🚨 - `calcite-tab` - `isActive` prop is now `active` to be consistent with other components
- 🚨 - `calcite-tab-title` - `isActive` prop is now `active` to be consistent with other components
Also some formatting updates and commits some readme updates from prior PR that had not made it in.
> [1.0 Cleanup] Tabs

- src/components/calcite-pagination/calcite-pagination.scss
> chore(pagination): remove background style

- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
- src/utils/dom.ts
chore: cleanup dom util for popover/tooltip
> chore: cleanup dom util for popover/tooltip

- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-popover/calcite-popover.tsx
> import VNode consistently

- package-lock.json
- src/components/calcite-modal/calcite-modal.tsx
- src/demos/calcite-modal.html
**Related Issue:** #768 
* Created a function for rendering the footer.
* Test of any slots for the footer are used.
* If no slot used then don't render the footer structure
> fix: fix styling for modal when no footer buttons

- .travis.yml
> ci: enable Travis CI

- src/components/calcite-color/calcite-color.e2e.ts
Fixes `calcite-color` test that failed on Travis-CI.
> test(color): update color test

- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-tile-select/calcite-tile-select.tsx
- src/components/calcite-tile/calcite-tile.tsx
Fix linting errors.
cc @eriklharper
> style: fix linting errors

- src/components/calcite-panel/calcite-panel.e2e.ts
feat(panel): Add tooling to test onscroll event for FlowItem and Panel
> feat(panel): Add tooling to test onscroll event for FlowItem and Panel

- TRAVIS_WEBHOOK_README.md
docs(travis): Add travis webhook documentation readme
> docs: Add travis webhook readme

- src/components/calcite-color/calcite-color.e2e.ts
Adds extra assertion to test the warning message when an invalid color is provided. This also helps keep the test log clean.
> test(color): add assertion for unsupported value console warning

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-flow/calcite-flow.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-sortable-list/calcite-sortable-list.tsx
- src/components/calcite-tab-title/calcite-tab-title.tsx
- src/components/calcite-tab/calcite-tab.tsx
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
refactor: replace componentDidUnload with disconnectedCallback
> chore: replace componentDidUnload with disconnectedCallback

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.scss
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/demos/calcite-checkbox.html
> feat(calcite-checkbox): label support

- src/components/calcite-radio-button/calcite-radio-button.scss
- src/components/calcite-radio-button/calcite-radio-button.tsx
> fix(calcite-radio-button): removing css class on host element

- src/components/calcite-radio-group-item/calcite-radio-group-item.scss
**Related Issue:** Resolves #853 cc @bstifle 
Updates hover text color to requested value
> style(radio-group): update hover styling

- src/components/calcite-input/calcite-input.scss
- src/components/calcite-input/calcite-input.tsx
**Related Issue:** Resolves #839 
Fixes icon scale issue with number button icons
> style(icon): update number button icon scale

- src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #877
feat(tooltip): Dismiss calcite-tooltip via ESC key #877
> feat(tooltip): Dismiss calcite-tooltip via ESC key #877

- src/components/calcite-color/calcite-color.tsx
Throttles canvas rendering to avoid unnecessary rendering.
> refactor(color): throttle canvas rendering to 60fps

- src/tests/setup.ts
> chore(tests): drop obsolete setup file

- src/components/calcite-tip-group/calcite-tip-group.scss
- src/components/calcite-tip-manager/calcite-tip-manager.scss
- src/components/calcite-tip/calcite-tip.scss
- src/components/calcite-tip/calcite-tip.tsx
**Related Issue:** #902
UI alignment with Notice.
> chore(tip, tip-group, tip-manager): ui alignment

- src/components/calcite-color/calcite-color.e2e.ts
- src/components/calcite-color/calcite-color.tsx
> fix(color): ensure color object values are rounded

- .eslintrc.json
- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-alert/calcite-alert.tsx
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-card/calcite-card.tsx
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-date/calcite-date.tsx
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-input-message/calcite-input-message.tsx
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-notice/calcite-notice.tsx
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-radio-button-group/calcite-radio-button-group.tsx
- src/components/calcite-radio-button/calcite-radio-button.tsx
- src/components/calcite-scrim/calcite-scrim.tsx
- src/components/calcite-slider/calcite-slider.tsx
- src/components/calcite-tile-select-group/calcite-tile-select-group.tsx
- src/components/calcite-tile-select/calcite-tile-select.tsx
- src/components/calcite-tile/calcite-tile.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
- src/components/calcite-tree-item/calcite-tree-item.tsx
- src/components/calcite-tree/calcite-tree.tsx
Keeping things simple and consistent by enforcing self-closing tags (auto-fixable! 🔨 ).
>  chore(linting): enable self-closing tags

- src/components/calcite-shell-panel/calcite-shell-panel.scss
> fix(shell-panel): fixes height styling for panel and flow in undetached shell-panel

- src/components/calcite-date-month-header/calcite-date-month-header.scss
- src/components/calcite-date-month-header/calcite-date-month-header.tsx
**Related Issue:** #907
In certain languages, it's common practice to add the character meaning "year" after the actual year number.
> fix(date): fix display of year in languages with year unit - ja,ko,ch (#907)

- src/components/calcite-date-month-header/calcite-date-month-header.scss
- src/components/calcite-date-month-header/calcite-date-month-header.tsx
> feat(date): respect order of year and month in date-header (#908)

- src/components/calcite-radio-button-group/calcite-radio-button-group.e2e.ts
- src/components/calcite-radio-button-group/calcite-radio-button-group.tsx
- src/components/calcite-radio-button/calcite-radio-button.e2e.ts
- src/components/calcite-radio-button/calcite-radio-button.tsx
> feat(calcite-radio-button-group): calciteRadioButtonGroup change event

- src/components/calcite-panel/calcite-panel.tsx
> docs(panel): adds doc for new slots

- src/6-custom-theme.stories.mdx
- src/custom-theme.md
**Related Issue:** #10 
Added a story with some very basic documentation and an interactive canvas where all the theme colors are knobs:
> docs(theme): add story for custom theme #1097

- .storybook/preview.ts
Simplify story sorting config.
> chore(storybook): simplify story sorting

- CONTRIBUTING.md
Reading through the contributing file, certain sections were out of date with changes made to our build commands/documentation structure.
> docs(CONTRIBUTING): fix out of date npm commands

- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-panel/calcite-panel.tsx
- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/components/calcite-shell-panel/calcite-shell-panel.tsx
- src/demos/shell/demo-app-advanced-2.html
**Related Issue:** #1107
- Panel: adds default width-scale
- ShellPanel: adds width-scale and associated styles
cc @kevindoshier @AdelheidF
> feat(panel, shell-panel): adds width-scale default to panel. adds width-scale property and styles to shell-panel

- .storybook/preview.ts
chore: Auto run a11y on storybook
> chore: Auto run a11y on storybook

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-popover-manager/calcite-popover-manager.e2e.ts
- src/components/calcite-popover/calcite-popover.e2e.ts
- src/components/calcite-progress/calcite-progress.e2e.ts
- src/components/calcite-radio-button/calcite-radio-button.tsx
- src/components/calcite-scrim/calcite-scrim.e2e.ts
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts
- src/components/calcite-tooltip/calcite-tooltip.e2e.ts
**Related Issue:** Tests: Add accessible tests #1159
Tests: Add accessible tests #1159
> Tests: Add accessible tests #1159

- src/components/calcite-button/calcite-button.e2e.ts
**Related Issue:** #1159
tests(button): add accessible tests
> test(button): add accessible tests

- src/components/calcite-graph/calcite-graph.e2e.ts
- src/tests/commonTests.ts
**Related Issue:** Tests: Add accessible tests #1159
Tests: Add accessible tests #1159
> test(graph): add accessible tests

- src/components/calcite-tree-item/calcite-tree-item.e2e.ts
- src/components/calcite-tree-item/calcite-tree-item.tsx
- src/components/calcite-tree/calcite-tree.e2e.ts
**Related Issue:** Tests: Add accessible tests #1159
test(tree, tree-item): add accessible tests.
> test(tree, tree-item): add accessible tests.

- src/components/calcite-switch/calcite-switch.e2e.ts
**Related Issue:** Tests: Add accessible tests #1159
test(switch): add accessible tests
> test(switch): add accessible tests

- src/components/calcite-select/readme.md
- src/components/calcite-select/usage/basic.md
**Related Issue:** #1240 
Adds brief description and usage snippets that will be pulled into `readme.md` in the next docs build.
cc @AdelheidF
> docs(select): add description and usage examples

- src/components/calcite-flow/calcite-flow.e2e.ts
- src/components/calcite-modal/calcite-modal.e2e.ts
> test(modal, flow): improve exposed fn types

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-label/calcite-label.e2e.ts
- src/components/calcite-label/calcite-label.tsx
- src/demos/calcite-checkbox.html
- src/demos/calcite-label.html
> fix: fixing click issues when using calcite-label with calcite-checkbox and enabling interoperability with native labels and inputs

- src/components/calcite-input/calcite-input.stories.ts
> docs(calcite-input): fixing storybook freeze

- .github/workflows/stale.yml
chore: filter stale issues with new or assigned labels
> chore: filter stale issues with new or assigned labels

- src/components/calcite-button/calcite-button.scss
- src/components/calcite-button/calcite-button.stories.ts
- src/components/calcite-date/calcite-date.scss
- src/components/calcite-date/calcite-date.tsx
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-label/calcite-label.tsx
**Related Issue:** #1168
feat(date): Use popper.js for Date component. #1168
>  feat(date): Use popper.js for Date component. #1168

- src/components/calcite-alert/calcite-alert.e2e.ts
**Related Issues:** #1159 
Adds tests for accessibility.
> test(alert): Update tests

- src/components/calcite-button/calcite-button.scss
- src/components/calcite-button/calcite-button.stories.ts
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-fab/calcite-fab.scss
- src/components/calcite-fab/calcite-fab.stories.ts
- src/index.html
- stencil.config.ts
**Related Issue:** #1167
fix(button)!: Remove floating property from calcite-button in favor of clcite-fab component.  #1167
> fix(button)!: Remove floating property from calcite-button

- package-lock.json
- package.json
> build(deps): bump versions

- src/components/calcite-pagination/calcite-pagination.tsx
- src/demos/calcite-pagination.html
**Related Issue:** #1341 
Makes pagination arrows correctly respond in rtl.
> fix(pagination): point arrows the correct direction in RTL #1341

- src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** Addresses #1289 cc @MikeTschudi
> docs(dropdown): Clarify max-item intent

- .github/workflows/stale.yml
chore: Update stale issues/prs configuration #1348
- Changes stale from 30 to 60 days.
- Changes closed from 7 to 14 days.
> chore: Update stale issues/prs configuration #1348

- .github/workflows/codeql-analysis.yml
build: Add code scanning
Sets up Code scanning alerts from here: https://github.com/Esri/calcite-components/security
> build: Add code scanning

- package.json
- src/components/calcite-color/calcite-color.e2e.ts
- src/tests/setupTests.ts
> chore: cleanup tests

- src/components/calcite-color/calcite-color.e2e.ts
- src/components/calcite-tab-title/calcite-tab-title.tsx
- src/components/calcite-tab/calcite-tab.tsx
- src/components/calcite-tabs/calcite-tabs.tsx
- src/tests/setupTests.ts
fix(tab, tab-title, tabs): Emit unregister events on the document.
> fix(tab, tab-title, tabs): Emit unregister events on the document.

- src/assets/styles/_popper.scss
**Related Issue:** #1381
fix(dropdown): Dropdown on RTL page causes long horizontal scroll #1381
> fix(dropdown): Dropdown on RTL page causes long horizontal scroll #1381

- src/components/calcite-modal/calcite-modal.tsx
- src/utils/dom.ts
**Related Issue:** #1375
fix(modal): Allow modal to focus on calcite components.
> fix(modal): Allow modal to focus on calcite components.

- src/components/calcite-color-swatch/calcite-color-swatch.e2e.ts
- src/components/calcite-inline-editable/calcite-inline-editable.e2e.ts
- src/components/calcite-link/calcite-link.e2e.ts
- src/components/calcite-panel/calcite-panel.e2e.ts
- src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts
- src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
- src/components/calcite-popover/calcite-popover.e2e.ts
- src/components/calcite-radio-button-group/calcite-radio-button-group.e2e.ts
- src/components/calcite-rating/calcite-rating.e2e.ts
- src/components/calcite-select/calcite-select.e2e.ts
- src/components/calcite-tooltip/calcite-tooltip.e2e.ts
- src/components/calcite-value-list-item/calcite-value-list-item.e2e.ts
This stabilizes tests by adding missing `await`s and switching parallel `accessible` tests to run sequentially (workers were not cleaned up properly in some cases).
cc @MikeTschudi
> test: stabilize async execution

- src/components/calcite-avatar/calcite-avatar.e2e.ts
This moves away from running a11y tests in parallel, which can cause workers to not shutdown properly.
> test(avatar): clean up a11y test

- src/components/calcite-flow/calcite-flow.stories.ts
- src/components/calcite-panel/calcite-panel.stories.ts
docs(flow, panel): fix calcite-flow and calcite-panel stories referencing outdated slots #1425
> docs(flow, panel): fix calcite-flow and calcite-panel stories referencing outdated slots #1425

- src/components/calcite-graph/calcite-graph.e2e.ts
- src/components/calcite-icon/calcite-icon.e2e.ts
- src/components/calcite-radio-button-group/calcite-radio-button-group.e2e.ts
- src/components/calcite-radio-button/calcite-radio-button.e2e.ts
- src/components/calcite-radio-group-item/calcite-radio-group-item.e2e.ts
- src/components/calcite-radio-group/calcite-radio-group.e2e.ts
- src/components/calcite-rating/calcite-rating.e2e.ts
> chore(tests): remove unnecessary await for sync methods

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
> test(dropdown): type promise

- src/components/calcite-dropdown/calcite-dropdown.tsx
This caused an error when the component was within another shadow DOM.
> fix(dropdown): use handler event argument

- CHANGELOG.md
chore: update changelog with breaking change to interface
> chore: update changelog with breaking change to interface

- conventions/README.md
> docs: correcting grammar in event details section of conventions

- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/demos/calcite-checkbox.html
> fix(calcite-checkbox): hidden input can no longer be forced to display with external css

- .storybook/main.ts
Updates story glob according to https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs.
> chore(storybook): migrate to latest supported story glob pattern

- src/components/calcite-button/calcite-button.stories.ts
docs: remove floating prop on button
> docs: remove floating prop on button

- CONTRIBUTING.md
>  docs(CONTRIBUTING): tailwind editor config

- src/components/calcite-action/calcite-action.tsx
**Related Issue:** #967 / https://github.com/Esri/calcite-app-components/issues/981
Removed confusing wording
> docs: update description for calcite-action's label prop  

- PROJECT_GUIDELINES.md
docs: update project guidelines for advanced CSS selectors
> docs: update project guidelines for advanced CSS selectors

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.scss
- src/components/calcite-checkbox/calcite-checkbox.tsx
> fix(calcite-checkbox): removing unnecessary aria attributes

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-combobox/calcite-combobox.e2e.ts
- src/components/calcite-date-picker/calcite-date-picker.tsx
- src/components/calcite-inline-editable/calcite-inline-editable.tsx
- src/components/calcite-input-message/calcite-input-message.tsx
- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-option/calcite-option.tsx
- src/components/calcite-pagination/calcite-pagination.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
- src/components/calcite-radio-group/calcite-radio-group.tsx
- src/components/calcite-rating/calcite-rating.tsx
- src/components/calcite-select/calcite-select.tsx
- src/components/calcite-stepper/calcite-stepper.tsx
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-tree-item/calcite-tree-item.tsx
- src/components/calcite-tree/calcite-tree.tsx
> chore: fix build warnings

- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-dropdown-item/calcite-dropdown-item.tsx
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-label/calcite-label.tsx
- src/components/calcite-link/calcite-link.tsx
- src/utils/dom.ts
**Related Issue:** #1538
chore: getAttributes() utility helper to spread attributes
@macandcheese could we change from a blockList to allowList on the attributes to pass down?
> chore: getAttributes() utility helper to spread attributes 

- conventions/README.md
docs: Update convention stubbing console.warn
> docs: Update convention stubbing console.warn

- src/components/calcite-color-hex-input/calcite-color-hex-input.e2e.ts
- src/components/calcite-color/calcite-color.e2e.ts
- src/components/calcite-inline-editable/calcite-inline-editable.e2e.ts
- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.tsx
- src/demos/calcite-input.html
**Related Issue:** #1507
fix(input): Support default value to reset an input
> fix(input): Support default value to reset an input

- src/assets/styles/_popper.scss
- src/components/calcite-popover/calcite-popover.e2e.ts
- src/components/calcite-tooltip/calcite-tooltip.e2e.ts
- src/components/calcite-tooltip/calcite-tooltip.scss
**Related Issue:** #552
fix(tooltip): Tooltip should appear in front of a popover.
> fix(tooltip): Tooltip should appear in front of a popover.

- src/components/calcite-fab/calcite-fab.tsx
**Related Issue:** #1524
A11y: Remove "Clear" prop from FAB #1524
> fix(FAB)!: Remove clear option from appearance property.

- src/components/calcite-modal/calcite-modal.e2e.ts
- src/components/calcite-modal/calcite-modal.stories.ts
**Related Issue:** #1477
docs(modal): Simple modal HTML shows obsolete property #1477
> docs(modal): Simple modal HTML shows obsolete property #1477

- src/components/calcite-alert/calcite-alert.e2e.ts
- src/components/calcite-combobox/calcite-combobox.e2e.ts
- src/components/calcite-input-date-picker/calcite-input-date-picker.e2e.ts
Skips additional alert a11y test. Will be fixed by #1608
> test: stabilize tests

- .github/workflows/stale.yml
chore: Update stale issue and PR configuration
> chore: Update stale issue and PR configuration

- src/components/calcite-action/usage/basic.md
**Related Issue:** #1623
docs(Action): Update usage for clarity on text property.
> docs(Action): Update usage for clarity on text property.

- conventions/README.md
- src/components/calcite-action-menu/calcite-action-menu.tsx
- src/components/calcite-alert/calcite-alert.tsx
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-inline-editable/calcite-inline-editable.tsx
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
- src/components/calcite-modal/calcite-modal.tsx
refactor(action-menu, alert, dropdown, inline-editable, input-date-picker, modal): clear timeouts
> refactor: clear timeouts on components

- src/components/calcite-rating/calcite-rating.scss
Updates rating widget to leverage more tailwind apply rules.
> refactor(rating): use tailwind in rating 

- src/components/calcite-handle/calcite-handle.scss
> refactor(handle): tailwindify

- src/components/calcite-pagination/calcite-pagination.scss
Supports #1646 #1500
Borders seem to be a continual issue. Had the same on notice. 
I have some `FIXME:` to note and get feedback on. Thx!
From the screener changes, the main change is the brand border bottom. It was 3px, but 3px is not in on scale, so bumped down to 2px, same as alerts and other items that have a brand line on them.
> refactor(Pagination): tailwindify

- src/components/calcite-fab/calcite-fab.scss
supports #1654 #1500
This already had @apply for most, just added it for bg trasparent. 
Not sure if I need to do something with the @extend
> refactor(FAB): tailwindify

- src/components/calcite-radio-button-group/calcite-radio-button-group.scss
> refactor(radio-button-group): tailwindify

- src/components/calcite-popover/calcite-popover.scss
> refactor(popover): tailwindify

- src/components/calcite-pick-list-group/calcite-pick-list-group.scss
> refactor(calcite-pick-list-group): tailwindify

- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
> refactor(calcite-pick-list-item): tailwindify

- src/components/calcite-panel/calcite-panel.scss
> refactor(panel): tailwindify

- src/components/calcite-panel/calcite-panel.scss
In MV, this is causing issues as a visual change to the type heiarchy. We can tackle this post dev conf.
cc'ing @asangma @bstifle @paulcpederson
> fix(panel): reverting weight as it's causing visual braking changes

- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
> feat(pick-list-item): removes top margin on description

- src/components/calcite-filter/calcite-filter.e2e.ts
- src/utils/filter.ts
fix(filter): Escape filter value
> fix(filter): Escape filter value

- src/components/calcite-combobox/calcite-combobox.tsx
refactor(combobox): Match dismissed chip by combobox item
> refactor(combobox): Match dismissed chip by combobox item

- src/components/calcite-progress/calcite-progress.scss
> refactor(progress): tailwindify

- src/components/calcite-pick-list/calcite-pick-list.scss
> refactor(calcite-pick-list): tailwindify

- src/components/calcite-tree/calcite-tree.scss
> refactor(tree): tailwindify

- src/components/calcite-shell/calcite-shell.e2e.ts
- src/components/calcite-shell/calcite-shell.tsx
Adds unique keys to the content node.
Adds related tests.
> fix(shell): adds unique keys for content node. adds related e2e tests

- src/components/calcite-rating/calcite-rating.scss
fix(rating): Fix wrapper display.
> fix(rating): Fix wrapper display.

- src/components/calcite-value-list/calcite-value-list.scss
> refactor(value-list): tailwindify

- src/components/calcite-date-picker/calcite-date-picker.tsx
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
- src/demos/calcite-date-picker.html
- src/demos/calcite-input-date-picker.html
feat(date-picker, input-date-picker): Add 'minAsDate' and 'maxAsDate' props
> feat(date-picker, input-date-picker): Add 'minAsDate' and 'maxAsDate' props

- src/components/calcite-shell-panel/calcite-shell-panel.scss
> refactor(shell-panel): tailwindify

- src/components/calcite-label/calcite-label.scss
Supports #1652 #1500
This one had some previous work in it with `@apply`
> refactor(label): tailwindify

- src/components/calcite-shell-center-row/calcite-shell-center-row.scss
> refactor(shell-center-row): tailwindify

- src/components/calcite-value-list-item/calcite-value-list-item.scss
> refactor(value-list-item): tailwindify

- src/components/calcite-scrim/calcite-scrim.scss
> refactor(scrim): tailwindify

- src/components/calcite-stepper/calcite-stepper.scss
> refactor(stepper): tailwindify

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
- src/components/calcite-dropdown/calcite-dropdown.stories.ts
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-dropdown/interfaces.ts
- src/components/calcite-dropdown/resources.ts
- src/components/calcite-popover/calcite-popover.stories.ts
- src/components/calcite-split-button/calcite-split-button.tsx
- src/demos/calcite-dropdown.html
- src/utils/popper.spec.ts
- src/utils/popper.ts
**Related Issue:** #1758
- feat(dropdown)!: Replace alignment property with position property.
- feat(popover, tooltip, action-menu): Add additional placement values for switching start and end in RTL.
> feat(dropdown)!: Replace alignment property with position property.

- src/components/calcite-tooltip/calcite-tooltip.scss
> refactor(tooltip): tailwindify

- src/components/calcite-radio-button/calcite-radio-button.e2e.ts
- src/components/calcite-radio-button/calcite-radio-button.tsx
**Related Issue:** #1775
This is PR #1776 here's an image to commemorate it!
> fix(radio-button): hidden input position no longer interferes with document flow

- src/components/calcite-tip/calcite-tip.scss
> refactor(tip): tailwindify

- src/6-custom-theme.stories.mdx
- src/components/calcite-action-bar/calcite-action-bar.stories.ts
- src/components/calcite-action-pad/calcite-action-pad.stories.ts
- src/components/calcite-action/calcite-action.stories.ts
- src/components/calcite-block/calcite-block.stories.ts
- src/components/calcite-fab/calcite-fab.stories.ts
- src/components/calcite-flow/calcite-flow.stories.ts
- src/components/calcite-panel/calcite-panel.stories.ts
- src/components/calcite-pick-list/calcite-pick-list.stories.ts
- src/components/calcite-shell/calcite-shell.stories.ts
- src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
- src/components/calcite-tip/calcite-tip.stories.ts
- src/components/calcite-value-list/calcite-value-list.stories.ts
docs: Update storybook to remove 'app' section, add 'theming' section and organize stories.
> docs: Update storybook to remove 'app' section, add 'theming' section and organize stories.

- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-pick-list/shared-list-logic.ts
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-popover/resources.ts
- src/components/calcite-value-list/calcite-value-list.tsx
refactor: FocusId types were clashing
> refactor: FocusId types were clashing

- src/components/calcite-tip-manager/calcite-tip-manager.scss
> refactor(tip-manager): tailwindify

- src/components/calcite-combobox-item/calcite-combobox-item.scss
> refactor(combobox-item): tailwindify

- src/components/calcite-date-picker/calcite-date-picker.scss
> refactor(date-picker): tailwindify

- src/components/calcite-tile-select-group/calcite-tile-select-group.scss
> refactor(tile-select-group): tailwindify

- src/components/calcite-select/calcite-select.scss
> refactor(select): tailwindify

- src/components/calcite-checkbox/calcite-checkbox.scss
> refactor(checkbox): tailwindify

- src/components/calcite-shell/calcite-shell.scss
> fix(shell): adds missed style

- src/components/calcite-combobox/resources.ts
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
**Related Issue:** #1826
feat(combobox, input-date-picker): Use new placements that flip in RTL.
> feat(combobox, input-date-picker): Use new placements that flip in RTL.

- src/components/calcite-action-pad/calcite-action-pad.scss
Supports #1500
Just removed the @extend that wasn't used. Everthing else looked good.
> refactor(action-pad): tailwindify

- CONTRIBUTING.md
> docs: correcting misspelling

- src/components/calcite-dropdown-group/calcite-dropdown-group.scss
- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-dropdown/calcite-dropdown.scss
> refactor(dropdown, dropdown-group, dropdown-item): tailwindify

- src/components/calcite-fab/calcite-fab.e2e.ts
- src/components/calcite-fab/calcite-fab.tsx
**Related Issue:** #1842
fix(fab): Fix native tooltip display. #1842
> fix(fab): Fix native tooltip display.

- src/components/calcite-action-group/calcite-action-group.tsx
- src/components/calcite-action-group/resources.ts
fix(action-group)!: Replace 'intlOptions' property with 'intlMore'.
> fix(action-group)!: Replace 'intlOptions' property with 'intlMore'.

- src/components/calcite-combobox/calcite-combobox.e2e.ts
**Related Issue:** #1876
test(combobox): skip unstable combobox test.
https://api.travis-ci.com/v3/job/495338469/log.txt
https://travis-ci.com/github/Esri/calcite-components/builds/221840214
> test(combobox): skip unstable combobox test.

- src/components/calcite-radio-group-item/calcite-radio-group-item.scss
- src/components/calcite-radio-group/calcite-radio-group.scss
- src/demos/calcite-radio-group.html
> refactor(radio-group-item): tailwindify

- src/components/calcite-action-menu/calcite-action-menu.tsx
fix(action-menu): Show pointer on menu.
> fix(action-menu): Show pointer on menu.

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
feat(action-menu): Add 'calciteActionMenuOpenChange' event.
> feat(action-menu): Add 'calciteActionMenuOpenChange' event.

- src/components/calcite-action-bar/calcite-action-bar.tsx
fix(action-bar): Overflow actions on initial render of component.
> fix(action-bar): Overflow actions on initial render of component.

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
fix(action-menu)!: Remove 'offsetDistance' property.
> fix(action-menu)!: Remove 'offsetDistance' property.

- src/components/calcite-switch/calcite-switch.tsx
- src/components/calcite-switch/readme.md
- src/components/calcite-switch/usage/framework-integration.md
- src/demos/calcite-switch.html
> docs(calcite-switch): removing proxy input support information

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
**Related Issue:** #1897
feat(action-menu): Auto close action menu when clicked outside.
> feat(action-menu): Auto close action menu when clicked outside.

- src/components/calcite-label/calcite-label.tsx
> fix(calcite-label): label no longer modifies slotted children attributes

- src/components/calcite-action-bar/calcite-action-bar.tsx
fix(action-bar): Overflow actions at load time.
> fix(action-bar): Overflow actions at load time.

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
**Related Issue:** #1896
feat(action-menu): Adds setFocus method and focus on first action when open or menu button when closed.
> feat(action-menu): Adds setFocus method and focus on first action when open or menu button when closed.

- src/components/calcite-action-group/calcite-action-group.tsx
- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
- src/components/calcite-action/calcite-action.tsx
**Related Issue:** #1896
fix(action-menu): When opening menu set focus on first action #1896
> fix(action-menu): When opening menu set focus on first action #1896

- src/components/calcite-date-picker-day/calcite-date-picker-day.scss
- src/components/calcite-date-picker/calcite-date-picker.stories.ts
Fixing the broken out of range day styling. Also updated the date-picker story to include out of range days so that screener will verify future updates.
> fix(date-picker-day): restore out-of-range day styling

- package-lock.json
- package.json
> chore: bump calcite icons

- src/components/calcite-tree-item/calcite-tree-item.e2e.ts
- src/components/calcite-tree-item/calcite-tree-item.tsx
- src/demos/calcite-tree.html
**Related Issue:** #1809
Tree items should be able to start expanded.
> fix(tree-item): allow trree to begin expanded #1809

- src/components/calcite-action-bar/utils.ts
- src/demos/shell/demo-app-advanced-3.html
**Related Issue:** #1942
fix(action-bar): Improve overflow logic for certain device heights
> fix(action-bar): Improve overflow logic for certain device heights

- src/components/calcite-action-bar/usage/tooltip.md
**Related Issue:** #1925
docs(action-bar): Update usage for expand action tooltip. #1925
> docs(action-bar): Update usage for expand action tooltip. #1925

- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
- src/demos/shell/demo-app-advanced.html
- src/utils/dom.ts
**Related Issue:** #1930
fix(tooltip, tooltip-manager, popover, popover-manager): Work correctly within shadowRoot elements.
> fix(tooltip, tooltip-manager, popover, popover-manager): Work correctly within shadowRoot elements.

- src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
**Related Issue:** #1116
fix(pick-list-item): Clicking on icon should trigger a click. #1116
> fix(pick-list-item): Clicking on icon should trigger a click. #1116

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
**Related Issue:** #1939
feat(action-menu): Add 'scale' property to calcite-action-menu #1939
> feat(action-menu): Add 'scale' property to calcite-action-menu #1939

- src/components/calcite-accordion-item/calcite-accordion-item.scss
- src/components/calcite-accordion-item/calcite-accordion-item.tsx
fix(accordion-item): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(accordion-item): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-avatar/calcite-avatar.tsx
fix(avatar): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(avatar): Remove setting 'dir' attribute in light DOM elements. #1831 

- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.tsx
> fix(calcite-input): localized number value now correctly updates when value is set programmatically

- package-lock.json
- package.json
fix(button): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(button): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-dropdown-group/calcite-dropdown-group.tsx
fix(dropdown-group): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(dropdown-group): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
fix(input-date-picker): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(input-date-picker): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-input-message/calcite-input-message.scss
- src/components/calcite-input-message/calcite-input-message.tsx
fix(input-message): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(input-message): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-link/calcite-link.e2e.ts
test(link): Remove "requestFailed" console error.
> test(link): Remove "requestFailed" console error.

- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
fix(pick-list-item): Use 'calciteActionClick' event for removing item.
> refactor(pick-list-item): Use 'calciteActionClick' event for removing item.

- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
docs(popover-manager, tooltip-manager): Improve documentation.
> docs(popover-manager, tooltip-manager): Improve documentation.

- src/utils/locale.ts
> fix(calcite-input): number input localization no longer restricted to static list of locales

- src/components/calcite-dropdown/calcite-dropdown.scss
- src/components/calcite-dropdown/calcite-dropdown.tsx
fix(dropdown): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(dropdown): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-label/calcite-label.e2e.ts
- src/components/calcite-label/calcite-label.scss
- src/components/calcite-label/calcite-label.tsx
fix(label): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(label): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-card/calcite-card.scss
- src/components/calcite-card/calcite-card.tsx
fix(card): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(card): Remove setting 'dir' attribute in light DOM elements. #1831

- .github/ISSUE_TEMPLATE/bug.md
Updates GH issue template with additional info to help users fill out and to get more structure in place.
> chore: update bug issue template

- src/components/calcite-rating/calcite-rating.scss
- src/components/calcite-rating/calcite-rating.tsx
fix(rating): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(rating): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
docs(popover-manager, tooltip-manager): Document the default slot.
> docs(popover-manager, tooltip-manager): Document the default slot.

- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.tsx
- src/demos/calcite-input-number.html
> fix(calcite-input): setting value of number inputs restricted to valid numbers or no value

- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
fix(value-list-item): Remove undocumented properties from the Host element. #2059
> fix(value-list-item): Remove undocumented properties from the Host element. #2059

- src/components/calcite-radio-button/calcite-radio-button.scss
- src/components/calcite-radio-button/calcite-radio-button.tsx
fix(radio-button): Remove undocumented property/attribute from the Host element. #2059
> fix(radio-button): Remove undocumented property/attribute from the Host element. #2059

- conventions/README.md
- package.json
> chore(custom-elements): rename scripts that modify custom-elements output target to convey relation

- readme.md
**Related Issue:** #1986 
Removes overlooked references to the previously-removed nomodules script.
> docs(readme): update installation section

- src/components/calcite-chip/calcite-chip.scss
- src/components/calcite-chip/calcite-chip.tsx
fix(chip): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(chip): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
fix(modal): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(modal): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-input/calcite-input.scss
- src/components/calcite-input/calcite-input.tsx
fix(input): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(input): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-date-picker-day/calcite-date-picker-day.scss
- src/components/calcite-date-picker-day/calcite-date-picker-day.tsx
fix(date-picker-day): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(date-picker-day): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-alert/calcite-alert.scss
- src/components/calcite-alert/calcite-alert.tsx
fix(alert): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(alert): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-radio-group-item/calcite-radio-group-item.scss
- src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
- src/components/calcite-radio-group/calcite-radio-group.e2e.ts
fix(radio-group-item): Remove undocumented properties from the Host element. #2059
> fix(radio-group-item): Remove undocumented properties from the Host element. #2059

- src/components/calcite-slider/calcite-slider.scss
- src/components/calcite-slider/calcite-slider.tsx
fix(slider): Remove undocumented properties from the Host element. #2059
> fix(slider): Remove undocumented properties from the Host element. #2059

- src/components/calcite-tab-title/calcite-tab-title.scss
- src/components/calcite-tab-title/calcite-tab-title.tsx
fix(tab-title): Remove undocumented properties from the Host element. #2059
> fix(tab-title): Remove undocumented properties from the Host element. #2059

- src/components/calcite-stepper-item/calcite-stepper-item.scss
- src/components/calcite-stepper-item/calcite-stepper-item.tsx
fix(stepper-item): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(stepper-item): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-dropdown-item/calcite-dropdown-item.tsx
- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
fix(dropdown-item): Remove setting 'dir' attribute in light DOM elements. #1831
> fix(dropdown-item): Remove setting 'dir' attribute in light DOM elements. #1831

- src/components/calcite-modal/calcite-modal.tsx
fix(modal): Remove setting 'dir' attribute in light DOM elements.
> fix(modal): Remove setting 'dir' attribute in light DOM elements.

- src/components/calcite-notice/calcite-notice.tsx
fix(notice): Remove undocumented properties from the Host element. #2059
> fix(notice): Remove undocumented properties from the Host element. #2059

- src/components/calcite-modal/calcite-modal.e2e.ts
- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
fix(modal): Remove undocumented properties from the Host element. #2059
> fix(modal): Remove undocumented properties from the Host element. #2059

- src/components/calcite-tooltip/readme.md
docs(tooltip): Update example to include required property.
> docs(tooltip): Update example to include required property.

- src/components/calcite-combobox-item/calcite-combobox-item.tsx
- src/components/calcite-combobox/calcite-combobox.e2e.ts
- src/components/calcite-combobox/calcite-combobox.tsx
**Related Issue:** #2102
fix(combobox, combobox-item): Toggling 'selected' on combobox-item should update the combobox parent. #2102
> fix(combobox, combobox-item): Toggling 'selected' on combobox-item should update the combobox parent. #2102

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.scss
- src/components/calcite-checkbox/calcite-checkbox.stories.ts
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-label/calcite-label.e2e.ts
- src/demos/calcite-checkbox.html
- src/demos/calcite-label.html
> fix(calcite-checkbox)!: removing internal label

- src/components/calcite-label/calcite-label.e2e.ts
- src/components/calcite-label/calcite-label.tsx
- src/demos/calcite-label.html
> fix(calcite-label): label for clicks work properly inside shadowRoots

- src/components/calcite-slider/calcite-slider.e2e.ts
- src/components/calcite-slider/calcite-slider.tsx
> fix(calcite-slider): slider handle position changes on mousedown instead of click/mouseup

- src/components/calcite-tree-item/calcite-tree-item.tsx
- src/components/calcite-tree/calcite-tree.tsx
**Related Issue:** #2164
refactor: invert internal CalciteTree root property to conform w/ strict-boolean-attributes rule #2164
> refactor: invert internal CalciteTree root property to conform w/ strict-boolean-attributes rule

- src/components/calcite-radio-button/calcite-radio-button.e2e.ts
> test: Fix radio-button test.

- src/components/calcite-checkbox/calcite-checkbox.scss
- src/components/calcite-checkbox/calcite-checkbox.tsx
- Updated large to 16px
- Updated icon svg code for minus and check
https://github.com/Esri/calcite-components/projects/14#card-60668119
> refactor(checkbox): Large size and icon updates

- src/components/calcite-modal/calcite-modal.scss
- src/components/calcite-modal/calcite-modal.tsx
- src/demos/calcite-modal.html
- Updated header text for s, m, l
- Updated all spacing to match Figma
https://github.com/Esri/calcite-components/projects/14#card-60668030
> refactor(modal): updated headers and spacing

- src/components/calcite-label/calcite-label.scss
**Related Issue:** #1500 and #2041 
- Large label text size down to 16px
> refactor(label): L size text size down to 16px

- src/components/calcite-chip/calcite-chip.scss
- src/components/calcite-chip/calcite-chip.tsx
- src/demos/calcite-chip.html
**Related Issue:** #2041
- Changed font sizes to 12px for S, 14px for M, and 16px for L
> fix(calcite-chip): updated scale to match figma

- conventions/README.md
> docs(conventions): fix typo

- src/components/calcite-action-menu/calcite-action-menu.scss
- src/components/calcite-action-menu/calcite-action-menu.tsx
- src/demos/shell/popup-config-example.html
**Related Issue:** #1906
@driskull would you mind updating the keyboard handlers on this one? I took a whack at it, but realized I don't know what I'm doing.
> feat(action-menu): update styling and keyboard behavior

- conventions/README.md
- src/demos/_assets/toggles.ts
- src/demos/calcite-inline-editable.html
**Related Issue:** #2262
docs: Update documentation for theming components and fix demo toggling theme. #2262
> docs: Update documentation for theming components and fix demo toggling theme. #2262

- src/components/calcite-action-menu/calcite-action-menu.e2e.ts
- src/components/calcite-action-menu/calcite-action-menu.tsx
**Related Issue:** #2273
feat(action-menu): Close action-menu when an action is clicked. #2273
> feat(action-menu): Close action-menu when an action is clicked. #2273

- src/components/calcite-tile/calcite-tile.e2e.ts
- src/components/calcite-tile/calcite-tile.scss
- src/components/calcite-tile/calcite-tile.stories.ts
- src/components/calcite-tile/calcite-tile.tsx
**Related Issue:** #2142 
Adds `disabled` prop to prevent user interaction.
> feat(tile): add disabled property

- src/demos/shell/popup-config-example.html
> chore(shell): update outdated slot names from demo page

- src/components/calcite-block-section/calcite-block-section.e2e.ts
- src/components/calcite-block-section/calcite-block-section.scss
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block-section/resources.ts
- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-block/readme.md
- src/components/calcite-block/resources.ts
- src/components/interfaces.ts
- src/demos/shell/block-configurations.html
**Related Issue:** #2261
This adds status to Block and BlockSection.
> feat(block, block-section): adds status and relate UI 

- src/components/calcite-pagination/calcite-pagination.scss
- src/components/calcite-pagination/calcite-pagination.tsx
**Related Issue:** #1500 #2041
- Large updates: 16px font and 16px icons
- Ellipse as text, not icon, follow text size from scale
- Height: Large 44px, Medium 32px, Small 24px
My first time touching TSX files will need review. 
Project card: https://github.com/Esri/calcite-components/projects/14#card-60668015
> refactor(pagination): Tailwindify and follow Figma

- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.tsx
- src/utils/locale.ts
- src/utils/number.ts
> fix(calcite-input): preventing number input from allowing more than one zero

- src/components/calcite-block-section/calcite-block-section.e2e.ts
- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-pagination/calcite-pagination.tsx
- src/demos/calcite-combobox.html
- src/demos/calcite-tabs.html
- src/demos/shell/block-configurations.html
chore: Run prettier and skip unstable test
> chore: Run prettier and skip unstable test

- src/components/calcite-notice/calcite-notice.tsx
- src/demos/calcite-notice.html
- Utilize tailwind
- Match figma designs
Project card: **Related Issue:** #1500
- Added all sizes to the demo page
- First pass at matching Figma
Project card: https://github.com/Esri/calcite-components/projects/14#card-60667723
> refactor(notice): Tailwind and Figma match

- src/components/calcite-checkbox/calcite-checkbox.e2e.ts
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-radio-button/calcite-radio-button.e2e.ts
- src/components/calcite-radio-button/calcite-radio-button.tsx
- src/components/calcite-tile-select/calcite-tile-select.e2e.ts
- src/components/calcite-tile-select/calcite-tile-select.tsx
**Related Issue:** #2259
fix(tile-select): Add aria-label for the form element used. #2259
Also adds guid for the input's id.
> fix(tile-select): Add aria-label for the form element used

- tsconfig-base.json
chore: updates typescript config to allow resolving JSON modules. #2367
> chore: updates typescript config to allow resolving JSON modules.

- src/components/calcite-color-picker/calcite-color-picker.e2e.ts
- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.tsx
- src/demos/calcite-input-number.html
- src/utils/locale.ts
- src/utils/number.ts
> fix(calcite-input): initially setting value to empty string results in value being "" instead of null

- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
**Related Issue:** #2258
Updates description font and size.
Updates title font color.
Adds a bit of spacing between title and description.
Adjusts spacing a bit.
> feat(value-list-item, pick-list-item): change description font to sans

- src/components/calcite-value-list/calcite-value-list.tsx
docs(value-list): Update group property description.
> docs(value-list): Update group property description.

- src/components/calcite-select/calcite-select.scss
- src/demos/calcite-select.html
- First pass at matching Figma
Project card: https://github.com/Esri/calcite-components/projects/14#card-60667918
> refactor(select): Match Figma and Tainwindify

- src/components/calcite-graph/calcite-graph.e2e.ts
- src/components/calcite-graph/calcite-graph.tsx
- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #1317
refactor(graph, popover-manager, tooltip-manager): Make components shadowed.
> refactor(graph, popover-manager, tooltip-manager): Make components shadowed.

- src/components/calcite-action-menu/calcite-action-menu.tsx
chore: remove menuButtonEl state
> refactor: remove menuButtonEl state

- CHANGELOG.md
> docs(changelog): add more detail about button breaking changes

- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
**Related Issue:** #2446
docs(popover, tooltip): Update referenceElement usage guidelines.  #2446
> docs(popover, tooltip): Update referenceElement usage guidelines.  #2446

- src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx
- src/components/calcite-color-picker/calcite-color-picker.tsx
- src/components/calcite-input/calcite-input.e2e.ts
- src/components/calcite-input/calcite-input.scss
- src/components/calcite-input/calcite-input.tsx
> fix(calcite-input): stop spreading attributes

- src/components/calcite-input/calcite-input.scss
- src/components/calcite-modal/calcite-modal.scss
**Related Issue:** #2216
- Modal X is not ui-text-3 on idle
- Input close X and other controls (spinners, chevrons, etc) are not ui-text-3 on idle
CC @bstifle
> refactor(components-x): components need consistent `x` idle, hover, etc

- src/demos/calcite-switch.html
**Related issue**: #2365
**Summary**:
- matched the current calcite-switch demo page according to the Figma design
> test(switch): update demo html to match Figma

- src/components/calcite-dropdown/calcite-dropdown.scss
- src/components/calcite-dropdown/calcite-dropdown.stories.ts
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-split-button/calcite-split-button.stories.ts
- src/components/calcite-split-button/calcite-split-button.tsx
fix(dropdown): Fix dropdown display issues.
> fix(dropdown): Fix dropdown display issues.

- package-lock.json
- src/components/calcite-list-item/calcite-list-item.scss
- src/components/calcite-list/calcite-list.scss
- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
- src/demos/list/basic.html
- src/demos/shell/block-configurations.html
**Related Issue:** #2541 
A few small style tweaks to match existing lists (value and pick).
Also includes some demo tweaks for the halps.
cc @AdelheidF
> fix(list, list-item): UI tweaks to better match other lists

- src/demos/calcite-chip.html
**Related Issue:** #2549 
- match the current calcite-chip demo page according to the Figma design
- all chips variants are included
> test(chip): updated demo html page

- src/components/calcite-input/calcite-input.scss
**Related Issue:** #2216
`x` on input and inline editible hover state updated to ui-text-1
> fix(x-close input and inline): x hover ui-text-1

- stencil.config.ts
**Related Issue:** #2600
build: Drop legacy code support #2600
> build: remove build options for legacy browser support

- src/components/calcite-pick-list/calcite-pick-list.e2e.ts
- src/components/calcite-value-list/calcite-value-list.e2e.ts
- src/tests/setupTests.ts
Fixes reported `eslint-plugin-jest` issues.
> test: fix linting issues

- src/demos/calcite-loader.html
**Related Issue:** #2633 
- updated loader demo page
> test(loader): loader demo updated

- src/demos/calcite-progress.html
**Related Issue:** #2636 
- updated progress demo page
> test(progress): updated demo page

- src/demos/calcite-popover.html
**Related Issue:** #2635 
- updated popover demo page
> test(popover): updated popover demo page

- src/demos/calcite-date-picker.html
**Related Issue:** #2580 
- updated calcite-date-picker encompassing the Figma design
- this version includes _small_, _medium_, and _large_ scale, which the previous version failed to include
> test(date-picker): updated date-picker demo according to Figma

- src/demos/calcite-notice.html
**Related Issue:** #2611 
- updated demo page
- _small_, _medium_, and _large_ variants included
> test(notice): updated demo page

- .browserslistrc
**Related Issue:** #2600 
Remove IE11 from browserslist config.
> build: update browserslist

- src/demos/calcite-tooltip.html
**Related Issue:** #2642 
- updated tooltip demo page
> test(tooltip): updated tooltip demo page

- src/demos/calcite-pagination.html
**Related Issue:** #2634 
- updated pagination demo page
> test(pagination): updated pagination demo page

- src/components/calcite-select/calcite-select.scss
- src/components/calcite-select/calcite-select.stories.ts
**Related Issue:** #2714
fix(select): truncate long labels. #2714
> fix(select): truncate long labels. #2714

- src/demos/list/basic.html
**Related Issue:** #2703 
- updated _calcite-list_ demo
> test(list): updated list demo

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-bar/utils.ts
refactor(action-bar): Overflow actions based on browser calculated size of action.
Also changes action-group buffer size since padding on the group has been removed since refactor.
> refactor(action-bar): Overflow actions based on browser calculated size of action.

- src/components/calcite-input-message/calcite-input-message.tsx
- src/components/calcite-input/calcite-input.scss
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/demos/calcite-checkbox.html
- src/demos/calcite-input.html
- src/demos/calcite-loader.html
- src/demos/calcite-popover.html
- src/demos/calcite-tooltip.html
> chore: run prettier

- src/tests/commonTests.ts
**Related Issue:** #2710
test(commonTests): Revert accidental merge changes from #2710
> test(commonTests): Revert accidental merge changes from #2710

- src/demos/calcite-select.html
**Related Issue:** #2637 
- updated select demo page
> test(select): updated demo page

- .storybook/preview-head.html
- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
- src/demos/calcite-select.html
> style: fix linting issues

- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
**Related Issue:** #2446 #2831
fix(popover, tooltip): Reposition open popover and tooltip on initial load. #2446
cc @caripizza
> fix(popover, tooltip): Reposition open popover and tooltip on initial load. #2446

- src/components/calcite-combobox/calcite-combobox.scss
**Related Issue:** #2515
fix(combobox): Set focus style correctly. #2515
> fix(combobox): Set focus style correctly

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
- src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** #2761
fix(dropdown): Stops closing after selection even with disableCloseOnSelect. #2761
> fix(dropdown): Stops closing after selection even with disableCloseOnSelect

- src/components/calcite-date-picker/calcite-date-picker.e2e.ts
- src/components/calcite-tree/calcite-tree.e2e.ts
- src/components/calcite-tree/calcite-tree.tsx
**Related Issue:** #2440
fix(tree): Tree with nested tree elements should fire only one event. #2440
> fix(tree): Tree with nested tree elements should fire only one event

- .github/auto_assign.yml
- .github/workflows/pr-bot.yml
Added an action that automatically assigns PRs to their author. Tested here: https://github.com/benelan/test-actions/pull/8
> chore: add action to auto assign prs

- CHANGELOG.md
> docs(changelog): remove irrelevant revert entry

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-date-picker/calcite-date-picker.tsx
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
- src/components/calcite-input-time-picker/calcite-input-time-picker.tsx
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-label/calcite-label.tsx
- src/components/calcite-link/calcite-link.tsx
- src/components/calcite-loader/calcite-loader.tsx
- src/components/calcite-modal/calcite-modal.tsx
- src/components/calcite-notice/calcite-notice.tsx
- src/components/calcite-popover-manager/calcite-popover-manager.e2e.ts
- src/components/calcite-popover-manager/calcite-popover-manager.tsx
- src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
- src/components/calcite-radio-group/calcite-radio-group.tsx
- src/components/calcite-radio/calcite-radio.tsx
- src/components/calcite-shell/calcite-shell.tsx
- src/components/calcite-slider/calcite-slider.tsx
- src/components/calcite-split-button/calcite-split-button.tsx
- src/components/calcite-switch/calcite-switch.tsx
- src/components/calcite-tab-nav/calcite-tab-nav.tsx
- src/components/calcite-tab-title/calcite-tab-title.tsx
- src/components/calcite-tabs/calcite-tabs.tsx
- src/components/calcite-tile/calcite-tile.tsx
- src/components/calcite-tip/calcite-tip.tsx
fix: default boolean properties to be false instead of undefined.
> fix: default boolean properties to be false instead of undefined.

- src/components/calcite-date-picker-month/calcite-date-picker-month.tsx
- src/components/calcite-date-picker/calcite-date-picker.tsx
- src/components/calcite-input-date-picker/calcite-input-date-picker.e2e.ts
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
- src/utils/date.ts
**Related Issue:** #2955
fix(input-date-picker): Set value, start, and end properties via input or date-picker. #2955
> fix(input-date-picker): Set value, start, and end properties via input or date-picker. #2955

- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-date-picker-day/calcite-date-picker-day.tsx
- src/components/calcite-date-picker-month/calcite-date-picker-month.tsx
- src/components/calcite-date-picker/calcite-date-picker.tsx
- src/components/calcite-dropdown-item/calcite-dropdown-item.tsx
- src/components/calcite-dropdown/calcite-dropdown.tsx
- src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
- src/components/calcite-input-message/calcite-input-message.tsx
- src/components/calcite-list-item/calcite-list-item.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-radio-button-group/calcite-radio-button-group.tsx
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-tooltip/calcite-tooltip.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
- src/utils/date.ts
**Related Issue:** #2701
docs: Add documentation for undocumented properties, methods, and events. #2701
> docs: Add documentation for undocumented properties, methods, and events

- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-action-menu/calcite-action-menu.tsx
- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-alert/calcite-alert.tsx
- src/components/calcite-button/calcite-button.tsx
- src/components/calcite-checkbox/calcite-checkbox.tsx
- src/components/calcite-chip/calcite-chip.tsx
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-dropdown-item/calcite-dropdown-item.tsx
- src/components/calcite-fab/calcite-fab.tsx
- src/components/calcite-filter/calcite-filter.tsx
- src/components/calcite-handle/calcite-handle.tsx
- src/components/calcite-input-time-picker/calcite-input-time-picker.tsx
- src/components/calcite-input/calcite-input.tsx
- src/components/calcite-link/calcite-link.tsx
- src/components/calcite-notice/calcite-notice.tsx
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-radio-button/calcite-radio-button.tsx
- src/components/calcite-radio-group/calcite-radio-group.tsx
- src/components/calcite-rating/calcite-rating.tsx
- src/components/calcite-select/calcite-select.tsx
- src/components/calcite-slider/calcite-slider.tsx
- src/components/calcite-switch/calcite-switch.tsx
- src/components/calcite-tile-select/calcite-tile-select.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
**Related Issue:** #2701
docs: document  the setFocus method on components
> docs: document  the setFocus method on components

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/calcite-panel/calcite-panel.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-popover/calcite-popover.tsx
- src/components/calcite-time-picker/calcite-time-picker.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #2701
docs: document the setFocus method on components #2701
> docs: document the setFocus method on components #2701

- src/components/calcite-pagination/calcite-pagination.tsx
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2517
docs(pagination, pick-list-item, slider): Add additional information for label properties. #2517
> docs(pagination, pick-list-item, slider): Add additional information for label properties

- screener.config.js
- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-date-picker/utils.ts
- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-input-time-picker/calcite-input-time-picker.tsx
- src/components/calcite-slider/calcite-slider.tsx
- src/components/calcite-tab-nav/calcite-tab-nav.tsx
- src/components/calcite-time-picker/calcite-time-picker.tsx
- src/demos/tip/basic.html
- tailwind.config.js
> style: lint codebase

- src/assets/styles/_header.scss
- src/components/calcite-tip-manager/calcite-tip-manager.scss
**Related Issue:** #2961
* Address bug in mentioned issue.
* Refactors _header partial
> refactor(header): apply tailwind to _header include

- .github/auto_assign.yml
- .github/workflows/pr-bot.yml
* Use a cleaner assign action
* Don't target the master branch for the label action in case of breaking changes
* Bump milestone action
> chore(actions): update prbot workflow

- CONTRIBUTING.md
Added the jsapi to one of the bug sample repro templates
> docs: setup the jsapi in a template repro sample

- package-lock.json
- package.json
> build(deps): bump calcite-ui-icons version

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
tests(action-bar): Skip unstable test related to resize observer.
> test(action-bar): Skip unstable test related to resize observer.

- .github/ISSUE_TEMPLATE/bug.md
- .github/need-info.yml
- .github/workflows/need-info-verify.yml
* added the template repro samples to the bug issue template in markdown comments
* updated the gh action to provide the option to not check markdown comments for required content
> chore: add template samples to bug issue template

- src/components/calcite-input-date-picker/readme.md
- src/components/calcite-input-date-picker/usage/Basic.md
@caripizza [found an issue](https://github.com/Esri/calcite-components/pull/3061/files/70d93d4d9c3c41b468643f16d6fcbe59ae043269#r711277667) with a usage example.
> docs: remove native label from usage example

- .github/need-info.yml
- .github/workflows/assign-for-verification.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/need-info-verify.yml
- .github/workflows/update-deps.yml
- .github/workflows/update-doc.yml
- setting the `3 - installed` label on an issue automatically removes all currently assigned users and assigns me
> chore: auto assign installed issues  for verification

- src/components/calcite-combobox/calcite-combobox.scss
**Related Issue:** #3059
fix(combobox): Correct display issues with single select and long strings. #3059
> fix(combobox): Correct display issues with single select and long strings. #3059

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-bar/utils.ts
**Related Issue:** #3119
test: Fix calcite-action-bar skipped test. #3119
> test: Fix calcite-action-bar skipped test. #3119

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
test(action-bar): Fix action-bar skipped test.
> test(action-bar): Fix action-bar skipped test.

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
**Related Issue:** #3119
test(action-bar): skip menuOpen test. #3119
> test(action-bar): skip menuOpen test. #3119

- src/components/calcite-filter/calcite-filter.e2e.ts
- src/components/calcite-filter/calcite-filter.tsx
**Related Issue:** #3138
refactor(filter): Add value property to set a filter.
> refactor(filter): Add value property to set a filter.

- src/assets/styles/_type.scss
**Related Issue:** #3438
Cherry-picked commit from external pr #3480
> fix: remove quotes from generic font families

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-pad/calcite-action-pad.e2e.ts
- src/components/calcite-radio-button-group/calcite-radio-button-group.e2e.ts
- src/components/calcite-value-list-item/calcite-value-list-item.e2e.ts
**Related Issue:** #2697
Worked on a windows virtual machine to troubleshoot this issue. The original windows issue (tailwind/sass error) seems to be fine now, not sure if an upgrade fixed that. This pr updates a couple files so the build on windows goes all the way through. There were a few (valid) linter errors being thrown, but after this it seems to work great!
> fix: fix build on windows (#2697)

- package-lock.json
- package.json
> build(deps): bump calcite-ui-icons

- src/components/calcite-alert/calcite-alert.e2e.ts
- src/components/calcite-alert/calcite-alert.tsx
**Related Issue:** #3366
Additional minor revisions from previously merged pr feedback #3525
> refactor(alert): add html helper for automated prettier

- .github/workflows/pr-semantic.yml
- New versions fix merge commit bug we ran into
- https://github.com/amannn/action-semantic-pull-request/blob/master/CHANGELOG.md#changelog
> ci(action): bump semantic pr version to fix merge commit bug

- src/utils/dom.ts
- src/utils/popper.spec.ts
**Related Issue:**  #2079
refactor: Refactor getElementDir dom utility.
> refactor: Refactor getElementDir dom utility.

- src/components/calcite-dropdown-item/calcite-dropdown-item.scss
- src/components/calcite-tab/calcite-tab.scss
**Related Issue:** #3437
Remove host color style.
> fix(tab): remove content text color from host

- src/components/calcite-link/calcite-link.e2e.ts
- src/components/calcite-link/calcite-link.scss
**Related Issue:** #3675
fix(link): Set host display to inline. #3675
> fix(link): Set host display to inline. #3675

- src/components/calcite-dropdown-group/calcite-dropdown-group.e2e.ts
- src/components/calcite-dropdown-group/calcite-dropdown-group.scss
**Related Issue:** #3427
fix(dropdown-group): Set display as block. #3427
> fix(dropdown-group): Set display as block. #3427

- src/components/calcite-accordion-item/calcite-accordion-item.tsx
- src/components/calcite-accordion/calcite-accordion.tsx
Question came up on the Teams channel, so adding doc for clarity
> docs(accordion): nest accordion-items not accordions

- package-lock.json
- package.json
**Related Issue:** #3822 
`@esri/eslint-plugin-calcite-components` got updated, so I thought I would bump this sooner.
> build(deps): bump @esri/eslint-plugin-calcite-components

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
> test: fix dropdown test.

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
test(dropdown): Fix another tests HTML. :)
> test(dropdown): Fix another tests HTML. :)

- src/components/calcite-combobox/calcite-combobox.e2e.ts
- src/components/calcite-combobox/calcite-combobox.tsx
- src/components/calcite-combobox/resources.ts
Stems from https://github.com/Esri/calcite-components/pull/3919#discussion_r783346858
feat(combobox): Add 'intlRemoveTag' property to override the remove tag text.
> feat(combobox): Add 'intlRemoveTag' property to override the remove tag text.

- src/components/calcite-combobox/calcite-combobox.e2e.ts
- src/components/calcite-combobox/calcite-combobox.tsx
**Related Issue:** #3754
fix(combobox): Properly set internal identifiers. #3754
> fix(combobox): Properly set internal identifiers. #3754

- src/components/calcite-alert/calcite-alert.e2e.ts
- src/components/calcite-alert/calcite-alert.tsx
- src/demos/calcite-alert.html
**Related Issue:** #3760
fix(alert): Emit calciteAlertClose/calciteAlertOpen after animation. #3760
> fix(alert): Emit calciteAlertClose/calciteAlertOpen after animation. #3760

- src/components/calcite-dropdown/calcite-dropdown.e2e.ts
Skip 2 tests for checking if the dropdown opens when dropdown-trigger is an action or a button.
> test(dropdown): skip dropdown opens when dropdown-trigger is an action or a button

- src/components/calcite-panel/calcite-panel.e2e.ts
- src/components/calcite-panel/calcite-panel.tsx
- src/demos/calcite-panel.html
**Related Issue:** #3924
feat(panel): Add method to scroll content. #3924
> feat(panel): Add method to scroll content. #3924

- src/demos/calcite-date-picker.html
- src/demos/calcite-graph.html
- src/demos/calcite-loader.html
- src/demos/calcite-switch.html
- src/demos/calcite-tree.html
- src/demos/form.html
- src/demos/shell/demo-app-advanced-2-shell-header.html
- src/demos/shell/demo-app-advanced-2.html
- src/demos/shell/demo-app-advanced-3.html
- src/demos/shell/demo-app-advanced.html
- src/demos/theme/auto.html
> refactor(demos): change var to const

- src/components/calcite-action/calcite-action.scss
**Related Issue:** #3955
Adds specific font declaration.
> fix(Action): updates font-family declaration

- src/components/radio-button/radio-button.tsx
> refactor(radio-button): fix selector typo

- src/components/input-message/input-message.scss
**Related Issue:** #4082
All credit to @paulcpederson via https://codepen.io/paulcp/pen/WNXjQxe
> fix(input-message): contained links work

- src/components/date-picker/date-picker.e2e.ts
> test(date-picker): unskip test

- src/components/dropdown/dropdown.tsx
**Related Issue:**  #4066 #3880
fix(dropdown): trigger keydown handler should only work for trigger element.
> fix(dropdown): trigger keydown handler should only work for trigger element

- src/components/tip-manager/tip-manager.tsx
**Related Issue:** #4106 
Update the `closed` property description for tip manager.
> docs: update tip manager prop desc

- src/utils/dom.ts
**Related Issue:** #4279
fix(tooltip): Removes console error when querying the tooltip (#4279)
> fix(tooltip): Removes console error when querying the tooltip

- src/components/switch/switch.e2e.ts
- src/components/switch/switch.tsx
**Related Issue:** #4211
fix(switch): Calling click() on switch should toggle checked. (#4211)
> fix(switch): Calling click() on switch should toggle checked

- src/components/filter/filter.e2e.ts
- src/components/filter/filter.tsx
- src/components/filter/resources.ts
**Related Issue:** #4284
fix(filter): emit events only on user interaction #4284
> fix(filter): emit events only on user interaction

- src/utils/label.ts
cc @timmorey 
--- 
**Related Issue:** # none
When updating from `next.413` to `next.414` (see diffs https://github.com/Esri/calcite-components/compare/v1.0.0-next.413...v1.0.0-next.414), we observed a significant slowdown in the field-maps test suite.  This appears to be caused by an accumulation of event listeners on the `document` that never get properly removed.
To address this, I followed a similar pattern to how we were managing the `calciteInternalLabelClick` event handlers.  When adding a listener, we store it in a `WeakMap`, so that we'll have the exact listener reference on hand when it comes time to remove it.
We have validated these changes in field-maps, and it appears to restore the performance of our test suite without regression.
> fix(label): avoid accumulation of event listeners

- src/demos/_assets/demos.css
- src/demos/input-time-picker.html
- src/demos/shell-panel/basic.html
- src/demos/sortable-list.html
- src/demos/tip/basic.html
- src/index.html
**Related Issue:** #2622 
* Update demos in the `index.html` page. 
* Maintain consistent naming and styling throughout individual demo pages.
> docs(demos): update demos and styling

- src/components/popover/popover.stories.ts
docs(popover): Remove manager readme from popover story.
> docs(popover): Remove manager readme from popover story.

- src/components/tile/tile.e2e.ts
- src/components/tile/tile.scss
- src/components/tile/tile.stories.ts
**Related Issue:** #4390
fix(tile): Prevent description from overflowing. (#4390)
> fix(tile): Prevent description from overflowing

- src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #4364
feat(input-time-picker): Add reposition method. (#4364)
> feat(input-time-picker): Add reposition method

- src/tests/commonTests.ts
refactor(commonTests): Cleanup formatting.
> refactor(commonTests): Cleanup formatting.

- src/components/action-menu/action-menu.tsx
refactor(action-menu): Store tooltip using assignedElements on slotChange
> refactor(action-menu): Store tooltip using assignedElements on slotChange

- src/utils/label.ts
**Related Issue:** #4495
This updates the label util to:
* remove mapped entries for bound label-connect/disconnect listeners for when a labelable component is removed (no need to track these anymore) 
* reuse bound label-connect listeners for when a label is disconnected
> fix(label): fix memory leak from label util

- src/components/shell-panel/shell-panel.scss
- src/components/shell/shell.stories.ts
**Related Issue:** #4489
fix(shell-panel): Remove border on slotted panels that are dismissed.  (#4489)
> fix(shell-panel): Remove border on slotted panels that are dismissed

- src/components/stepper/stepper.tsx
**Related Issue:** #4315
refactor(stepper): Fix direction setting.
> refactor(stepper): Fix direction setting.

- src/components/color-picker/color-picker.e2e.ts
test(color-picker): Fix build error.
> test(color-picker): Fix build error.

- src/components/stepper/stepper.e2e.ts
- src/components/stepper/stepper.tsx
**Related Issue:** #4490
refactor(stepper): Cleanup code from review.
> refactor(stepper): Cleanup code from review.

- src/components/action-bar/action-bar.e2e.ts
- src/components/action-bar/action-bar.tsx
**Related Issue:** #3119
test(action-bar): Fixes skipped test. (#3119)
> test(action-bar): Fix skipped test

- src/components/action-bar/action-bar.e2e.ts
test(action-bar): Stabilize menuOpen test.
> test(action-bar): Stabilize menuOpen test.

- src/components/action-bar/action-bar.e2e.ts
test(action-bar): Stabilize test.
> test(action-bar): Stabilize test.

- src/components/action-bar/action-bar.e2e.ts
test(action-bar): Fix stability of test
> test(action-bar): Fix stability of test.

- src/components/action/action.scss
- src/components/chip/chip.scss
- src/components/date-picker-day/date-picker-day.scss
- src/components/filter/filter.scss
- src/components/input-date-picker/input-date-picker.scss
- src/components/label/label.scss
- src/components/list-item-group/list-item-group.scss
- src/components/list-item/list-item.scss
- src/components/pagination/pagination.scss
- src/components/tab-title/tab-title.scss
- src/components/tile-select-group/tile-select-group.scss
fix: Ensure components are using logical css properties for margin and padding.
> fix: Ensure components are using logical css properties for margin and padding.

- src/components/tooltip-manager/tooltip-manager.e2e.ts
chore: Cleanup unused import in test.
> chore: Cleanup unused import in test.

- src/components/action-menu/action-menu.e2e.ts
- src/components/action-menu/action-menu.tsx
- src/components/functional/ExpandToggle.tsx
**Related Issue:** #4609
fix(action-menu): Hide tooltip when open. (#4609)
> fix(action-menu): Hide tooltip when open. (#4609)

- src/components/modal/modal.tsx
**Related Issue:** #4613
fix(modal): Remove unused 'firstFocus' property. (#4613)
> fix(modal): Remove unused 'firstFocus' property. (#4613)

- src/components/flow/flow.e2e.ts
- src/components/flow/flow.tsx
**Related Issue:** #4667
fix(flow): Only slotted panels should be managed. (#4667)
> fix(flow): Only slotted panels should be managed. (#4667)

- conventions/README.md
Documented the globalAttributes util
> docs(internal): globalAttributes util usage

- .github/workflows/deploy-next.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/update-deps.yml
**Related Issue:** #4703
Missed a couple
> ci: fix additional dep conflicts

- src/components/popover/popover.e2e.ts
- src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #3196
test(tooltip, popover): Add tests for virtual reference elements. (#3196)
> test(tooltip, popover): Add tests for virtual reference elements

- src/components/tab-nav/tab-nav.scss
- src/components/tab-nav/tab-nav.tsx
- src/components/tab-title/tab-title.e2e.ts
- src/components/tab-title/tab-title.scss
- src/components/tabs/interfaces.ts
- src/components/tabs/tabs.e2e.ts
- src/components/tabs/tabs.scss
- src/components/tabs/tabs.tsx
**Related Issue:** #4688 
This will enable `top`, `bottom` values for `@Prop( ) position` in `tabs`,`tab-nav` & `tab-title` component. current values `above , below` will be deprecated.
> feat(tabs,tab-nav,tab-title): add top,bottom values for position prop

- src/utils/dom.ts
refactor: Update toAriaBoolean DOM utility to use Boolean function.
> refactor: Update toAriaBoolean DOM utility to use Boolean function.

- package-lock.json
- package.json
build(deps): Revert cheerio to 1.0.0-rc.10 to fix storybook
@benelan  maybe we need to block cheerio from updating automatically. It was crashing storybook local build.
> build(deps): Revert cheerio to 1.0.0-rc.10 to fix storybook

- src/components/dropdown/dropdown.scss
- src/components/dropdown/dropdown.stories.ts
**Related Issue:** #404
fix(dropdown): Restore trigger container to flex-auto. (#404)
> fix(dropdown): Restore trigger container to flex-auto

- src/components/accordion-item/accordion-item.tsx
**Related Issue:** #4691
fix(accordion-item): Indicate whether accordion is expanded to screen readers.
> fix(accordion-item): Indicate whether accordion is expanded to screen readers.

- src/components/combobox/combobox.tsx
**Related Issue:** #4773
fix(combobox): Correctly honor max-items. (#4773)
> fix(combobox): Correctly honor max-items

- src/components/flow/flow.stories.ts
docs(flow): Update story to use description instead of summary property.
> docs(flow): Update story to use description instead of summary property.

- src/components/combobox/combobox.tsx
**Related Issue:** #4388
fix(combobox): Correctly read back items in voiceover. (#4388)
> fix(combobox): Correctly read back items in voiceover

- src/components/input-date-picker/input-date-picker.e2e.ts
- src/components/input-date-picker/input-date-picker.tsx
Input-date-picker implements OpenCloseComponent interface.
> refactor(input-date-picker): to implement OpenCloseComponent interface

- src/components/combobox/combobox.tsx
Cleanup related to OpenCloseComponent interface implementation.
> refactor(combobox): replace transitionrun with transitionstart and cleanup

- src/components/popover/popover.e2e.ts
- src/components/popover/popover.tsx
Popover implements OpenCloseComponent interface.
> refactor(popover): implements OpenCloseComponent interface

- src/components/combobox/combobox.e2e.ts
- src/components/combobox/combobox.scss
fix(combobox): Remove popper remnants.
> fix(combobox): Remove popper remnants.

- src/components/notice/notice.e2e.ts
- src/components/notice/notice.scss
- src/components/notice/notice.stories.ts
- src/components/notice/notice.tsx
- src/demos/notice.html
**Related Issue:** #4688 
This will deprecate `active` prop in favor of `open`.
> feat(notice): deprecate active prop and add support for open prop

- src/components/dropdown-group/dropdown-group.tsx
- src/components/dropdown/dropdown.e2e.ts
- src/components/dropdown/dropdown.tsx
**Related Issue:** #4944
fix(dropdown): Fix navigating without a dropdown-group. (#4944)
Also updates aria roles for a11y.
> fix(dropdown): Fix navigating without a dropdown-group

- src/components/filter/filter.tsx
- src/components/pick-list/shared-list-tests.ts
**Related Issue:** #4851 
In addition to fixing the error, this refactors the components to reuse the same filter util.
> fix(pick-list, value-list): fix error when typing special regex chars
