Esri/calcite-design-system

package-lock.json, package.json
Removes calcite-fonts as a dep of calcite-components. 
Once the newest version of calcite-fonts makes it to the CDN, I'll add a link to the CDN for our local dev site, but we shouldn't have the repo listed as an actual dep.
=> #86 - remove calcite-fonts

package-lock.json, package.json, src/components/calcite-button/calcite-button.scss, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-progress/calcite-progress.scss, src/components/calcite-radio-group/calcite-radio-group.scss, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-tabs/calcite-tabs.scss, src/index.html
- use calcite-base from newly published npm module
- update all remaining pre 1.0.0 colors
- add fonts via new CDN css reference
=> Use calcite-base from npm, finish updating variables to new color format

src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/index.html
Adds theme prop to buttons - light / dark, defaults to light. Adds css vars to support the theme prop.
Note this only changes styling for red / blue buttons - light / dark are unaffected... consumers should just swap color prop vs. theme prop for those cases... the idea of a theme="dark" / color="light" button being dark seems... wrong. 
Note, these "dark theme" color variables will be updated in `calcite-colors` soon, this just sets up theme prop on buttons, and adds the css vars so when those are updated, it applies to buttons.
=> Adds dark theme to buttons

src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-radio-group/calcite-radio-group.scss
Fixes the following Edge issues:
1. In the `External inputs` case (from demo), the label obtained from the proxied input wasn't being rendered. ~~I think this may be a Stencil bug although I haven't been able to create an isolated test case. I'll have to dig a little deeper.~~ Created Stencil issue: https://github.com/ionic-team/stencil/issues/1811
2. Layout was broken in Edge (items were aligned vertically).
=> Issue #100: Fix <calcite-radio-group> Edge issues.

conventions/README.md
Renames `reflectToAttr` to `reflect`
Changes wording around `<calcite-button>` now that we do, in fact, have a `<calcite-button>` component ;)
=> Updates conventions

src/components/calcite-dropdown-group/calcite-dropdown-group.e2e.ts, src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-group/readme.md, src/components/calcite-dropdown-item/calcite-dropdown-item.e2e.ts, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-dropdown/readme.md, src/index.html, src/interfaces/DropdownInterface.tsx, src/utils/dom.ts, stencil.config.ts
This for the most part follows the API discussed in https://github.com/Esri/calcite-components/issues/6
At its simplest:
```
<calcite-dropdown alignment="right">
<calcite-button slot="dropdown-trigger">Open Dropdown</calcite-button>
<calcite-dropdown-group grouptitle="View">
<calcite-dropdown-item active>List</calcite-dropdown-item>
<calcite-dropdown-item>Grid</calcite-dropdown-item>
<calcite-dropdown-item>Table</calcite-dropdown-item>
</calcite-dropdown-group>
</calcite-dropdown>
```
Each `calcite-dropdown-item` registers itself in a `calcite-dropdown-group`, which handles sorting of items within itself. Similarly, `calcite-dropdown-group` registers itself in the containing `calcite-dropdown`, which handles sorting of groups - needed for dropdowns that contain multiple …
=> Initial Dropdown Commit

src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.scss, src/index.html
Mostly some subtle style changes to bring this inline with some of our other designs. Also, it seemed like you could "tab" through collapsed items in scale(0) so just made display:none/block.
- Changes styling of “hidden” items to just display:none - previously you were able to tab through closed items that had scale(0)
- Adjusts spacing and alignment
- Updates caret icon and sizing
- Adds transition to all hover effects
- Hovering over a child item will now add a hover state to all parent lines
- Adds distinct styles for “open” vs” open and selected” for parent level items
- Uses char symbol for active dot, vs. icon, to match dropdown 
- Updates hover style to gray dot to match dropdown 
- Adds “hover / active width” to lines to better match that of tabs component
- Updates small scale …
=> Style updates - focus fix for hidden items

CHANGELOG.md, src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/index.html
- Adds "transparent" button style
- Makes "outline" buttons have a dark bg in dark theme
- adds "iconposition" prop to position icon, you can now define iconposition=start/end (defaults to start)
- cleans up some styles
I'd still like to refactor how we allow icons - once we have an "icon component", we can refactor a bit to better scale icons based on button size, and think about letting consumers pass a "calcite ui icon name" as a prop instead of path data, which is pretty messy.
=> Updates button styles

src/assets/styles/includes.scss, src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.scss, src/components/calcite-tree/calcite-tree.tsx, src/index.html
This PR makes 3 fixes for `<calcite-tree>`:
1. When pre-rendering/hydrating CSS for the expanded tree items no longer extends to all children.
2. Links in tree nav are now black even if other styles are applied.
3. The tab order fixes from @macandcheese in https://github.com/Esri/calcite-components/pull/111 are maintained.
@macandcheese one thing I did notice is that selected/open parent items don't have a distinct focus state, not sure if you want to follow up on that today.
=> Tree fixes

src/index.html
There was a problem with the files in calcite-fonts 1.3.0 for medium weight.
=> bump fonts link to fix medium weight avenir

CHANGELOG.md, src/components/calcite-modal/calcite-modal.scss
Medium and Large modals would become very narrow when narrow content was passed in. That behavior is now only preserved in the small modal, the rest will size to the max-width immediately.
=> fix width of medium/large modals with narrow contents

src/components/calcite-radio-group/calcite-radio-group.e2e.ts
Adds tests for:
- Rendering of requested scale/theme props
- Validation of incorrect scale/theme props
- Rendering of default scale/theme props
- Rendering of requested scale prop on child radio group items
- Validation of incorrect scale prop on child radio group items
- Rendering of default scale prop on child radio group items
Let me know if I should add tests for anything else.
**Note** The "when multiple items are checked, last one wins" test still fails occasionally - related to https://github.com/Esri/calcite-components/issues/104,
Sometimes it passes because it returns the correct item (item 3), sometimes it fails as it returns item 1/item2... but this was already happening pre-these-updates. I had similar "ordering" issues with calcite-dropdown-items/calcite-dropdown-groups and …
=> Adds test for prop validation on radio groups

CHANGELOG.md, package.json, src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.tsx, src/components/calcite-modal/readme.md, src/index.html
The code here is hopefully self-explanatory.
I have a use-case where the user can do a bunch of work inside of the modal, and accidentally hitting "escape" would dismiss all of that work without a prompt, which I've already found is very frustrating.
Even with this option, the modal ought to remain accessible because the user can still tab to the "X" button and hit enter.
=> add `closeOnEscape` option to calcite-modal

CHANGELOG.md, src/components/calcite-modal/calcite-modal.scss, src/index.html
Small update to modal scrolling behavior. Only the content will scroll now, rather than the entire modal.
Also updated the links in the `CHANGELOG` so that they pointed to `Esri/calcite-components`  and made sure we had them all accounted for.
@macandcheese you already reviewed this, but adding you again anyways.
=> scroll modal content rather than full modal

src/assets/styles/includes.scss, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-alerts/calcite-alerts.scss, src/components/calcite-alerts/calcite-alerts.tsx, src/components/calcite-button/calcite-button.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-tabs/calcite-tabs.scss
Restores function for alerts and dropdowns
Fixes styling for alerts, dropdowns, and buttons
Syntax changes due to Edge's incompatibility with shadowRoot / ::slotted styling
Adjusts active color for tabs
Having to use  
`if (e.target.outerHTML.includes('slot="dropdown-trigger"')) { ... }`
instead of 
` if (e.target.slot === "dropdown-trigger") { ... } `
_feels wrong_, so if there is a better pattern that lets you target slots in Edge, I'm all ears and happy to update.
=> Edge fixes for alerts, dropdowns, buttons

src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/index.html
Sets tabindex for all rendered child items to ensure focusability
Sets explicit width on parent for width half / full (fix for recent change to button structure)
=> Fix for inline with no href, and button width props

CHANGELOG.md, package-lock.json, package.json, support/release.sh
This should fix the release process for people who have 2 factor auth on their GitHub accounts (i.e. everyone) by using `origin` (which should be SSH) bypassing 2FA.
=> Fix release origin

src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/readme.md, src/components/calcite-radio-group/readme.md, src/index.html
Popover: Accept id string for reference element as a convenience.
---
This will allow a user to set the id string of the reference element instead of having to go through the DOM.
=> Popover: Accept id string for reference element as a convenience.

src/components/calcite-tree/calcite-tree.scss
The indicator start values were defaulting to `0`, which was setting `right:0`making the default size max-width. Changed to be `auto` so now the default size is the inline width.
=> fix: indicator-start values

src/components/calcite-button/calcite-button.tsx
We can improve this later to adjust the blacklist / make it a whitelist / etc., but this should fix the immediate issue of duplicate id on parent and in rendered child in shadowDom
=> Adds id to attribute blacklist

src/components/calcite-popover/calcite-popover.tsx
#182
- Fixes the offsets for x/y when the placement is top or bottom.
- If the placement is "auto" then x-offset/y-offset will not be respected.
=> Popover: Reverse x-offset/y-offset when top/bottom placement

src/assets/styles/_popper.scss, src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/resources.ts, src/components/calcite-tooltip/calcite-tooltip.scss, src/components/calcite-tooltip/calcite-tooltip.tsx, src/components/calcite-tooltip/resources.ts
- Move shadow to its own node so it doesn't show on host always even if not displayed.
- Only apply margin if caret is used and to the appropriate side.
- Add a property to disable the caret on the Popover
Issue: https://github.com/Esri/calcite-app-components/issues/449
=> Popover/Tooltip enhancements for shadow/caret

src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/readme.md, src/index.html
- Improves handling of button actions associated with forms
-- prevents type reset or button from submitting
-- explicitly handle validate, submit, and reset of associated forms
- Check and set button types if needed
- Keep track of button child element type internally
- General component and doc cleanup
- Add examples to index page
Fix for https://github.com/Esri/calcite-components/issues/193 - I had originally used the proxy button from Ionic's button, but updated that function a bit. Can you take a look @driskull @kevindoshier
=> Fix for unintended button submission in form, improve button/form handling

package-lock.json, package.json, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip/calcite-tooltip.tsx
- Updates popper.js to 1.16.
- Adds a property to disable flipping. Popover will maintain placement as defined. Would be useful when you want a popover to always position in a specific direction.
- Adds a property to flow inside of the referenceElement instead of outside. Would be useful for a popover that should cover the element.
- Define `preventOverflow` first according to docs.
calcite-popover placement issues when popover is too high #190
calcite-popover going offscreen #195
=> Popover modifier enhancements

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-dropdown/calcite-dropdown.tsx
Provides an update for https://github.com/Esri/calcite-components/issues/181
Only opening a dropdown via key on the `dropdown-trigger` slot will cause the first item to be focused now, and will not occur when opening with mouse.
If keyboard and mouse are used in combination, clear keyboard focus and assign focus to the hovered item. 
This also does some general component cleanup.
This should prevent most of the styling oddities in the original issue - our general focus styles need a pass which should help further down the line.
=> Updates to dropdown focus, general clean up

CHANGELOG.md, src/components/calcite-modal/calcite-modal.tsx, src/components/calcite-modal/readme.md, src/components/calcite-radio-group/readme.md
Needed a way to make the content of a modal scroll back to the top. As the scrollable element is in the shadow dom, you don't have access as a consuming dev to set `scrollTop` values.
=> add scrollContent method to calcite-modal

CHANGELOG.md, src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.stories.js, src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/readme.md, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-group/readme.md, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.stories.js, src/index.html
Fix for https://github.com/Esri/calcite-components/issues/179 cc @adelheidF
- breaking: calcite-button "iconposition" attribute updated to "icon-position"
- breaking: calcite-dropdown-group "grouptitle" attribute updated to "group-title"
- breaking: calcite-dropdown-item "linktitle" attribute updated to "link-title"
- updates docs and storybook examples
=> Breaking - update property / attribute names

package-lock.json, src/assets/styles/_colors.scss, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-button/calcite-button.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-progress/calcite-progress.scss, src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-radio-group/calcite-radio-group.scss, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-tooltip/calcite-tooltip.scss, src/index.html
global css variables:
- fixed a bug that was breaking dark theme
Bryan and I sat down and synched up the Sketch values with the calcite-component values: colors, weights, sizes, etc.
Went through most of the components and sourced the global css variables from https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_colors.scss:
- Made sure text colors were using ui text 1, 2, 3, blue, or red.
- Added foreground colors to containers or close button. 
- sourced main ui colors 
minor UI changes
- some UI updates to sliders to match Sketch lib
- updated solid light button hover and pressed state for dark theme
=> Components source global CSS variables

src/components/calcite-button/calcite-button.scss
Didn't catch this when reviewing https://github.com/Esri/calcite-components/pull/227 : the underline for red and blue "inline" buttons was updated to a css var that doesn't exist. 
Might be worth going over all touched components to give one more check over @julio8a, but I couldn't find anything else
=> Fix for missing button inline underline after css updates

src/components/calcite-button/calcite-button.scss
#237 
I've updated the text color and border color on these buttons (blue and red):
- clear
- transparent
- outline (for consistency, these always have ffffff bg)
- inline
Not sure if this is the best way to do it, open to some other ideas @paulcpederson and @macandcheese
=> blue and red accessibility fix

src/assets/styles/_popper.scss, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-tooltip/calcite-tooltip.scss
fix: Popover caret showing again
@asangma the `overflow:hidden` here broke it. https://github.com/Esri/calcite-components/commit/76ece13e7fa166c75a48fe010a85f11c45c62de0#diff-f6732f8c161075a349f5bb173ef35c31
=> fix: Popover caret showing again

package.json
Updated Stencil version. 
1.8.0 is when Stencil got up to TS 1.7 🎉
(I have some chaining in my branch that's breaking the build)
=> upgrade to stencil 1.8.1

src/assets/styles/readme.md
From a meeting with @asangma and @macandcheese. Here's the first pass at a readme that gives the most common usage and points to the foundation styles for building calcite(-app)-components.
The story behind this is...
As a developer not familiar with calcite-components, I want to find variables and styles so that I can quickly build components and keep them consistent with what's been built so far.
Open to feedback and suggestions.
=> Added initial round of global styles readme

CHANGELOG.md, src/components/calcite-modal/calcite-modal.tsx
creates a `focusElement` method which allows devs to restore focus to a modal.
=> add focusElement method to calcite modal

src/components/calcite-accordion-item/calcite-accordion-item.tsx, src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-switch/calcite-switch.tsx, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tab/calcite-tab.tsx, src/components/calcite-tree-item/calcite-tree-item.tsx
This fixes some [issues caught by axe](https://travis-ci.com/Esri/calcite-app-components/builds/137847375) where it would complain about `aria-some-boolean-attribute=""` being invalid.
=> Use text values for boolean ARIA attributes.

CHANGELOG.md, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-alert/readme.md, src/components/calcite-icon/readme.md, src/components/calcite-notice/readme.md, src/index.html
- Updates component to use new calcite-icon component
- Adds setFocus() method to focus either a slotted alert-link or a close button, if present (same functionality as for notice)
- Styling updates to match those to calcite-notice
- Update some generated docs, changelog
=> Adds setFocus() method to alert, use calcite-icon, update styles

src/components/calcite-switch/calcite-switch.tsx
This fixes a regression caused by https://github.com/Esri/calcite-components/pull/259.
=> fix(a11y): fix calcite-switch semantics

CHANGELOG.md, src/components/calcite-progress/calcite-progress.tsx, src/components/calcite-progress/readme.md, src/index.html
Addresses https://github.com/Esri/calcite-components/issues/246
- Conditionally display calcite-progress--text only if text attribute is present (removes unwanted padding)
- Removes slot from component - previously it was used as a wrapping component around content, now it can be used as a standalone item that can be positioned by the consumer
- Update readme and docs
@driskull I think you originally wrote this - thoughts on changing from a "wrapping" component to one that can be positioned by the consumer?
=> Update to progress - remove slotted children, don't display text container if not requested

src/components/calcite-icon/readme.md, src/index.html
Follow up to issue: https://github.com/Esri/calcite-components/issues/276
Adds super simple example of custom icon fill color and quick docs.
cc @rslibed
=> Add docs and example for custom icon fill

src/components/calcite-dropdown/calcite-dropdown.scss
When hovering over the dropdown-trigger, there were a few pixels that would cause the animation to stutter as the transition occurred - this should fix that.
=> Fix for dropdown hover animation

src/components/calcite-icon/calcite-icon.e2e.ts
Adding waitForChanges after icon is injected pauses and waits for the path data to load asynchronously so its consistently present when the code tries to read the path attribute.
=> fix: calcite-icon failing tests

src/components/calcite-dropdown/calcite-dropdown.e2e.ts
This fixes the test failure that began occurring in calcite-dropdown.
The tests now explicitly open the dropdown before "clicking" each option.
Edit, figured it out.... this was due to `pointer-events: none;` being added to closed dropdowns, previously the test was able to "click" a closed item, after the change it no longer could. it just coincided with the Stencil version bump ;)
=> Fixes for dropdown test

src/components/calcite-loader/calcite-loader.scss, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree/calcite-tree.scss
- switch
- loader
- tree
- I'm not sure about the changes to the switch, seems odd, but it works out at the end as the correct values render on the page. Open to feedback or changes if needed. 
- @paulcpederson, I noticed `spot-light` and `spot-dark` were using `v-xx-xxx` values. I just changed them to the main blue for light and dark theme. Not sure if we still need both regular `loader-spot` and `loader-spot-light`.
=> Use global CSS vars

src/components/calcite-button/calcite-button.scss, src/demos/calcite-button.html
Maintains full height when flexed
Preserves icon width when adjacent to long text strings
Adds example to doc
addresses https://github.com/Esri/calcite-components/issues/299, further improvements can be made here: https://github.com/Esri/calcite-components/issues/297
cc @AdelheidF 👀 
It will still overflow if there's a very long string so perhaps a `scale="s/xs"` could be justified if it's still running over.
=> Updates button style

src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree/calcite-tree.scss
- reverted `--calcite-tree-indicator-active' and '--calcite-tree-line-active' (they reference `--calcite-ui-blue`)
- kept `--calcite-tree-chevron-active` out, since it's not being used.
#310 
@oknoway
=> updates to tree css vars

src/components/calcite-icon/calcite-icon.tsx
The current icon visibility code assumes that only one IntersectionObserverEntry would exist when the callback is invoked. This leads to an edge case where an icon would not load correctly if the second, or subsequent, entry is the one confirming its visibility. This PR addresses this by checking all possible entries to determine if the icon is visible or not.
=> fix(icon): include all observed intersection entries to determine icon visibility

src/components/calcite-tree-item/calcite-tree-item.scss
Currently long strings inside `calcite-tree-item` will overflow from `calcite-tree`. This makes them not do that.
=> Tree: Force long strings to wrap

src/components/calcite-switch/calcite-switch.e2e.ts, src/components/calcite-switch/calcite-switch.tsx
Currently, it's not possible to set `tabindex` on the switch because it's hardcoded. This PR allows overriding it by using a [pattern from Ionic's `tab-button` component](https://github.com/ionic-team/ionic/blob/94159291b27ddf1a859c8f3f87a0d6e54a8b5f13/core/src/components/tab-button/tab-button.tsx#L110-L120
).
Side note, I can remove the test if deemed redundant. Just wanted to have an automated way to test the behavior.
=> fix(switch): honor user-set tab index

src/components/calcite-slider/calcite-slider.tsx
Noticed this while I was testing labels wrapping sliders 😄
=> Updates slider guid name

src/assets/styles/_popper.scss
Popper: Allow pointer events for poppers that have escaped their container
=> Popper: Allow pointer events for poppers that have escaped their container

src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.scss
Moves css vars from children items to parent. 
Removes unused theme declarations.
No change for users.
=> Clean up dropdown css, tsx

src/components/calcite-notice/calcite-notice.scss
Z-index was erroneously set on calcite-notice. They don't float above anything so they shouldn't have a z-index set at all.
=> Removes z-index from calcite-notice

CHANGELOG.md, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-dropdown/calcite-dropdown.stories.js, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-dropdown/readme.md, src/components/calcite-radio-group/readme.md, src/demos/calcite-dropdown.html
Follow up PR from conversations, also includes a couple other cleanup items: @TheBlueDog @driskull @kstinson14
**BREAKING:** renames "left/right" alignment to logical property "start/end" nomenclature
**BREAKING:** removes link-title attribute from calcite-dropdown-item
**UPDATE:** now spreads attributes on calcite-dropdown-item to rendered child link if href attribute is present
**FIXES:** "center" alignment when the dropdown-trigger is narrower than the width of the dropdown should now be correctly positioned
**DESIGN:** Removes dot and horizontal padding in "none" selection-mode
**DESIGN:** Now uses check icons instead of dots in "multi" selection-mode
**MISC:** Updates tests, storybook, dev demo page
=> BREAKING - Dropdown updates

src/components/calcite-alert/calcite-alert.stories.js, src/components/calcite-alert/calcite-alert.tsx, src/demos/calcite-alert.html, stencil.config.ts
Addresses https://github.com/Esri/calcite-components/issues/354
No change for users, it was unexpected to have to use an `id` in the first place so this is just an enhancement.
- If a user doesn't provide an id, fallback to a generated private GUID used for queuing.
- Also fixes a duplicate entry for `calcite-icon` in stencil config.
CC @cosbyr
=> Use GUID to manage alert queue if ID is not provided in DOM

src/components/calcite-radio-group/calcite-radio-group.e2e.ts, src/components/calcite-radio-group/calcite-radio-group.tsx
Related issue: #74 
Adds `CalciteRadioGroup#setFocus()` 👁👓:camera:  📸
=> feat(radio-group): add setFocus method

src/components/calcite-tab/calcite-tab.scss, src/components/calcite-tabs/calcite-tabs.scss, src/components/calcite-tabs/calcite-tabs.tsx
We're making use of the `calcite-tabs` component and ran into a bit of an issue with styling.  Basically, we're giving the `calcite-tabs` component a defined height.  And we want each `calcite-tab` component within it to take up the full height (minus the height of the tab nav) even if the tab's content doesn't fill that space completely (this is useful for something like a vertically-centered empty state).  This seems like a fairly common use case.  Unfortunately, it seems like we're only able get each tab to take up as much vertical space as its content does.  
Example of behavior:
- `calcite-tabs` component given a height of `500px`, represented in blue.
- `calcite-tab` component given height of `100%`, represented in green.
There doesn't seem to be a good way to get the tab content to …
=> Allow calcite-tab to take up full height of calcite-tabs component

src/components/calcite-loader/calcite-loader.scss, src/components/calcite-loader/calcite-loader.tsx, src/components/calcite-loader/readme.md, src/demos/calcite-loader.html
1. Converted to circle
2. Works in edge
3. Works in ie11
4. Determinate loader has new fade-out on completion
5. No more `requestAnimationFrame` js stuff for edge 
In IE and Old Edge the segments are rotated, but in more modern browsers the dash-array is animated. The dash-array animation is slightly sharper, so for machines that can handle it I've left it.
@julio8a @bstifle I've also added a [series of variables](https://github.com/Esri/calcite-components/pull/384/files#diff-a3b65abeb0b9258c91de75281e64c75bR17-R25) that act as knobs letting you easily tweak the animation if you want to run this locally and change numbers until it looks right.
@macandcheese I think we can close the other loader pr that is currently open after this? IDK let me know
=> ✨ Loader improvements

package-lock.json, package.json, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-date-month-header/calcite-date-month-header.scss, src/components/calcite-date-month-header/calcite-date-month-header.tsx, src/components/calcite-date-month-header/readme.md, src/components/calcite-date/calcite-date-picker.scss, src/components/calcite-date/calcite-date-picker.tsx, src/components/calcite-date/readme.md, src/components/calcite-dropdown/readme.md, src/components/calcite-icon/calcite-icon.scss, src/components/calcite-icon/calcite-icon.tsx, src/components/calcite-icon/readme.md, src/components/calcite-icon/utils.ts, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-modal/calcite-modal.stories.js, src/components/calcite-modal/calcite-modal.tsx, src/components/calcite-modal/readme.md, src/components/calcite-notice/calcite-notice.scss, src/components/calcite-notice/calcite-notice.tsx, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/readme.md, src/components/calcite-popover/usage/addClickHandle.md, src/components/calcite-radio-group/readme.md, src/demos/calcite-alert.html, src/demos/calcite-modal.html, src/demos/calcite-popover.html
- bump calcite-ui-icons to `v3.0.0-beta.5`
- convert all existing icons to `calcite-icon` component
- update incorrect `icon=` uses on buttons in demos and docs
- update some references to icons that no longer exist in a post-3.0.0 world (lightbulb-filled, etc)
- change sizes of most of the `x` icons. They really changed the size of the x inside the bounding box so the 16x16 x was now reaaaally tiny
- fix `calcite-icon` in ie11 (now fetching the icon as JSON rather than with JS module syntax)
=> ✨ Icon update

src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-radio-group/calcite-radio-group.scss
Multiple problems with this one:
1. using locally declared css vars from a parent in a child component
2. Using default slot content (it always showed up in ie11)
3. Using `toggleAttribute` method 
[#374]
=> 🐞  fix radio-group in ie11

src/components/calcite-button/calcite-button.scss, src/demos/calcite-button.html
- demo page: dark theme bg color sample was wrong. Updated to 2b2b2b.
- outline buttons use calcite-ui-foreground(-dark) as background
- adjusted outline light/dark solid buttons (they no longer blend
with background on hover)
- updates to dark buttons border outline/clear: borders no longer blend
with background on hover
=> Outline and Clear button style updates

src/assets/styles/includes.scss, src/components/calcite-tree-item/calcite-tree-item.scss
Forgot this part, this fixes the colors for dark theme in ie11
=> fix dark theme in calcite-tree in ie11

src/components/calcite-switch/calcite-switch.tsx, src/demos/calcite-switch.html
Fix for https://github.com/Esri/calcite-components/issues/385 - had to explicitly emit the change event. cc @rslibed
@vcolavin can you give this a sanity check - should we "re-emit" native events like this (sorry, can't add as a reviewer)? 
There have been a few issues opened now around `calcite-switch`(https://github.com/Esri/calcite-components/issues/283) and I wonder how much has to do with the proxy / wrapped input stuff we are doing. 
@patrickarlt I know initially we were doing this to handle some specific Angular requirements - is this still a good methodology? Would we be able to simplify these components to disallow the wrapping of custom inputs, while we work towards a more holistic solution like seeing if https://github.com/ionic-team/stencil-ds-plugins works, or taking a stance …
=> Explicitly emit change event on keypress

src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-slider/calcite-slider.tsx, src/components/calcite-tab-nav/calcite-tab-nav.scss, src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/components/calcite-tab-title/calcite-tab-title.scss, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tab/calcite-tab.tsx, src/components/calcite-tabs/calcite-tabs.scss, src/components/calcite-tabs/calcite-tabs.tsx, src/demos/calcite-tabs.html
#377 - updates tabs so that they work on ie11. 
Basically the strategy of setting a whole bunch of vars on a parent component is a non-starter for ie11. What I've been doing is using `.closest` to find the anscestor with the set attribute and then cloning that to the child host pre-render. I've been making these un-documented (`@internal`) props so they don't show up in storybook or anything.
=> 🐞Fix tabs in ie11

src/components/calcite-card/calcite-card.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.e2e.ts, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-dropdown/calcite-dropdown.tsx, src/demos/calcite-dropdown.html, src/utils/dom.ts
Related issue: #396 
This adds the following enhancements to the dropdown: 
* Focuses the first active item or first one if there's none.
* Enables scrolling for long list of items.
* Fixes item focusing (it wasn't working before).
* Adds utility to help focus components or native elements.
* Fixes some tests and typings.
* Minor cleanup.
cc @dhrumil83
=> feat(dropdown): focus on active item when opened

src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.scss
Fixes for IE11 dropdown... preferring the duplication of CSS vars in each nested child file to setting the scale and dir and theme explicitly on the component host in the .tsx file... Neither is really nice
=> IE 11 Dropdown style fixes

src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion-item/calcite-accordion-item.tsx
Similar to https://github.com/Esri/calcite-components/pull/423 - fixes IE11 by doubling up on variables with host-context and explicitly re-including the theme variables for nested child component. Re-adds Dir to `host` as well.
=> IE 11 Accordion style fixes

src/components/calcite-icon/calcite-icon.e2e.ts, src/components/calcite-icon/calcite-icon.tsx, src/components/calcite-icon/utils.ts
This addresses unnecessary shifts in layout caused by not rendering the SVG element until the path data is available.
Reverts c601720bb8756f848de03fc02d8274621bc2a94f
#432
=> fix(icon): always render in the target scale to avoid shifts in layout

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.stories.js, src/components/calcite-dropdown/calcite-dropdown.tsx, src/demos/calcite-dropdown.html, src/interfaces/Dropdown.ts
#431 
This adds a new `calcite-dropdown` prop (`maxItems`) to allow users to specify the number of items to display before the scroller shows up. **Note**: group titles don't count as items. For example, if you have a two groups of 5 items each and set the max to 7, you will see the following:
See the demo for more details on ☝️.
This also types some of the registration events and caught a bug ([`requestedDropdownItem`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-dropdown-group/calcite-dropdown-group.tsx#L101) isn't in the register item event payload).
I'm open to suggestions on the prop name. 😄 
@dhrumil83
=> feat(dropdown): specify max items to display before scrolling is enabled

src/components/calcite-button/calcite-button.tsx
This is an attempted fix for https://github.com/Esri/calcite-components/issues/434
Without a reproduction case I don't know if this will solve it, but, because this change was added in the last release it seems... likely? 
@kstinson14 I  * believe * this will accomplish what you were looking for with the mutationObserver, determining if "hasText" is true if the component updates. Please let me know if this doesn't work!
=> Remove mutationObserver in button for hasText prop

CHANGELOG.md, package.json, src/components/calcite-icon/calcite-icon.tsx, src/components/calcite-icon/utils.ts, src/components/calcite-stepper-item/calcite-stepper-item.tsx, src/demos/calcite-icon.html
We won't be able to merge this until the corresponding pr is merged into the icons repository and we cut a new release over there.
Essentially they removed most of the filled icons a couple releases ago, making our `filled` prop virtually useless. 
Some select icons still have a filled variant, but now that is handled via a different icon name. This pr updates our icon component to reflect those changes.
=> 🚨 remove filled prop on calcite-icon

src/components/calcite-button/calcite-button.tsx
This restores `MutationObserver` logic to update button's state:
> When the issue occurs, the element's textContent gets set after initial lifecycle methods and when that happens it does not trigger a re-render, so hasText isn't recalculated. Restoring MutationObserver fixes this in my testing.
☝️ from #434 
Revert "Remove mutationObserver in button for hasText prop (#436)"
This reverts commit eec7a7a1f74e611ffbd8e5fc4c12ee9663aa2486.
=> fix(button): update hasText when textContent is set after initial render

CHANGELOG.md, src/components/calcite-pagination/calcite-pagination.e2e.ts, src/components/calcite-pagination/calcite-pagination.scss, src/components/calcite-pagination/calcite-pagination.stories.js, src/components/calcite-pagination/calcite-pagination.tsx, src/components/calcite-pagination/readme.md, src/demos/calcite-pagination.html
I'm not sure how I didn't catch this in the initial code review for pagination, but basically the props were not what we were intending them to mean. I think the initial dev on this just misunderstood the intent or hadn't used ArcGIS REST services before. 
The idea was for devs to have the ability to pass props straight from a JSON response from our search API's directly into the component. Previously, the component was expecting you to pass in _page_ count/values. So the dev would have to compute these prior to setting the properties. They were also confusingly named exactly what is sent back. This pr updates the API so that it works in tandem with the APIs it's meant to support. 
Other improvements:
- using `button` elements instead of anchors with no href and a tabindex. This allows …
=> Updates to pagination component API

src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx
fix: calcite-tooltip-manager only working once (when used with Maquette?) #483
=> Popover/Tooltip: Keep guid consistent

CHANGELOG.md, src/components/calcite-date-day/calcite-date-day.scss, src/components/calcite-date-day/calcite-date-day.tsx, src/components/calcite-date-day/readme.md, src/components/calcite-date-month-header/calcite-date-month-header.scss, src/components/calcite-date-month-header/calcite-date-month-header.tsx, src/components/calcite-date-month-header/readme.md, src/components/calcite-date-month/calcite-date-month.scss, src/components/calcite-date-month/calcite-date-month.tsx, src/components/calcite-date-month/readme.md, src/components/calcite-date/calcite-date.scss, src/components/calcite-date/calcite-date.stories.js, src/components/calcite-date/calcite-date.tsx, src/components/calcite-date/readme.md, src/components/calcite-input/calcite-input.tsx, src/components/calcite-progress/calcite-progress.scss, src/components/calcite-progress/calcite-progress.tsx, src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-slider/calcite-slider.tsx, src/demos/calcite-date.html, src/interfaces/Date.ts, src/utils/locale.ts
Sorry, other branch was deleted after I rebased, so reopening this pr. Several fixes, plus a bundle of `calcite-date` updates. This pr builds on top of the `key` work in #479 so that pr should probably be merged prior to this one.
- 🐞 fix hidden progress text (#452)
- 🧹 remove BEM syntax from slider css classes
- 🐞 don't allow entering 0 for month or day (#307)
- 🐞 fix z-index collision between date and slider (#307)
- 🐞 size date dropdown to input width, fix 1px open movement (#308)
- ✨ use `calcite-input` in `calcite-date`
- ✨ add scale prop to date (#463)
- 🎨 clean up date styles (#446)
- 🚨 `show-calendar` now `active` in calcite date, 
- 🧹 v1 calcite date cleanup, better typing for events, more consistent props (#463)
=> Date updates, fixes

CHANGELOG.md, src/components/calcite-icon/utils.spec.ts, src/components/calcite-icon/utils.ts, src/demos/calcite-icon.html
Fixes #494 
Basically I only handled the `circleF` format and not `circle-f`. Added some tests for this as well.
=> 🐞 fix fetching filled calcite icons with kebab case

src/components/calcite-accordion/calcite-accordion.stories.js, src/components/calcite-combobox/calcite-combobox.stories.js, src/components/calcite-dropdown/calcite-dropdown.stories.js, src/components/calcite-radio-group/calcite-radio-group.stories.js, src/components/calcite-stepper/calcite-stepper.stories.js, src/components/calcite-stepper/readme.md
Updates based on https://github.com/Esri/calcite-components/issues/498
Updates calcite-stepper docs to match initial state of example in Storybook
Adds child component docs to top-level stories for accordion, dropdown, stepper, combobox, radio-group
Various auto-generated readme spacing updates
cc @gavinr
In the future we could improve this by adding tabs for each child component's docs, adding a helper to handle the concatenation of readmes, or... see what lies in store for us in Storybook 6 which supposedly has a lot of QoL improvements (global state for RTL, Theme, Scale, etc., that will help us generally clean up Stories)
=> Add child component docs to storybook

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.stories.js, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html
Handles cases where min or max are set to 0
Adds dev demo example
Adds min, max, step knobs to Storybook
Adds more tests around number buttons for number type input
Fixes margin only being applied to a certain input type
-- This will eventually get added to the label wrapping an input and not the input itself re: https://github.com/Esri/calcite-components/issues/480 but for now, it fixes an inconsistency where it was only being added to number type button vertical
cc @kellyhutchins
=> Fix increment and decrement of number type input when min/max is 0

CHANGELOG.md, src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-radio-group/calcite-radio-group.e2e.ts, src/components/calcite-radio-group/calcite-radio-group.scss, src/components/calcite-radio-group/calcite-radio-group.stories.js, src/components/calcite-radio-group/calcite-radio-group.tsx, src/components/calcite-radio-group/readme.md, src/demos/calcite-radio-group.html
Feature add re: https://github.com/Esri/calcite-components/issues/501 cc @jwasilgeo
- Adds style for vertical layout
- Width of containing `calcite-radio-group` will expand to the widest child when in `layout=vertical`
- Doesn't try to handle overflow or max-height, users can set that on a wrapping container if desired
- Adds test, story, changelog for vertical layout
=> Adds vertical layout option to radio group

src/components/calcite-notice/calcite-notice.scss, src/demos/calcite-notice.html
Fixes #533 cc @MikeTschudi
The following markup
```
<calcite-notice width="full" dir="rtl" active>
<div slot="notice-title">Welcome to your new website</div>
<div slot="notice-message">
<div>
That thing you wanted to do worked pretty well
</div>
<ul>
<li>LI item</li>
<li>LI item</li>
</ul>
<div>
A second slotted div
</div>
</div>
</calcite-notice>
```
(or when `dir="rtl"` is set on a parent container)
results in :
=> Fix Notice RTL padding

CHANGELOG.md, src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-card/calcite-card.tsx, src/components/calcite-checkbox/calcite-checkbox.scss, src/components/calcite-checkbox/calcite-checkbox.stories.js, src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-checkbox/readme.md, src/components/calcite-input-message/calcite-input-message.scss, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-tooltip/calcite-tooltip.scss, src/demos/calcite-checkbox.html
BREAKING: calcite-checkbox "size" prop is now "scale"
Tooltip: dark background needs to use level-2 (Fix #521)
Switch: hover state border increase to 3px (Fix #520)
Input-message: text centering (Fix #517)
Checkbox: styling fixes (Fix #515)
Card: checkbox spacing, Dark theme checkbox (Fix #514)
Alert: remove autodismiss bar border radius (Fix #513)
Accordion: caret color hover (Fix #512)
=> BREAKING - checkbox prop change, various style updates

.lintstagedrc.json
I forgot to include TS files in the auto-linting PR (https://github.com/Esri/calcite-components/pull/426). :sweat_smile:
=> chore(linting): include TS files

src/components/calcite-dropdown/calcite-dropdown.scss
Ensures RTL is adhered to in Safari / Firefox now that it's explicitly defined on component.
=> Removes :host-context from dropdown

src/components/calcite-accordion/calcite-accordion.scss, src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/readme.md, src/components/calcite-card/calcite-card.scss, src/components/calcite-chip/calcite-chip.scss, src/components/calcite-combobox-item/calcite-combobox-item.scss, src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-date/calcite-date.scss, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-input/calcite-input.tsx, src/components/calcite-label/calcite-label.tsx, src/components/calcite-label/readme.md, src/components/calcite-link/calcite-link.tsx, src/components/calcite-link/readme.md, src/components/calcite-notice/calcite-notice.scss, src/components/calcite-pagination/calcite-pagination.scss, src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-split-button/calcite-split-button.tsx, src/components/calcite-split-button/readme.md, src/components/calcite-stepper/calcite-stepper.tsx, src/components/calcite-stepper/readme.md, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-switch/calcite-switch.tsx, src/components/calcite-switch/readme.md, src/components/calcite-tabs/calcite-tabs.scss, src/components/calcite-tree/calcite-tree.tsx, src/index.html
Mainly trying to make components easier to theme as per #507 . Basically, by setting the `theme` attribute on all the components we were making it hard to override the css vars. This stops setting theme if the prop isn't passed in, and allows components to inherit their theme. 
Getting this to work in ie required adding the dark theme variables to all components, not just nested ones. When IE11 support is dropped we will be able to remove these. 
Also started moving some of the remaining components that use their own configurable theming variables over to the normal global ones. This covers most of #546 , but not the dark button. Some of the dark button colors are not available in our global css vars.
In order to make it easier for me to test/troubleshoot theming I've added a "sticker …
=> Don't set default theme attributes

CHANGELOG.md, src/assets/styles/global.scss, src/components/calcite-date/calcite-date.scss, src/components/calcite-input/calcite-input.scss
Two very small bug fixes plus some additional properties to help text rendering. 
```css
text-rendering: optimizeLegibility;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```
To my eyes, this makes the text in the browser feel a lot closer to the text in the designs (ie. weight is closer to what it looks like in sketch). Interested to get @bstifle  and @julio8a 's opinion on if this is better?
| Before | After |
| ------ | ----- |
| <img width="289" alt="Screen Shot 2020-05-06 at 2 52 42 PM" src="https://user-images.githubusercontent.com/1031758/81232475-dab8a380-8fa9-11ea-9ed0-411c3d69df86.png"> | <img width="291" alt="Screen Shot 2020-05-06 at 2 56 53 PM" src="https://user-images.githubusercontent.com/1031758/81232473-d9877680-8fa9-11ea-9039-f765e63abd8f.png"> …
=> Text rendering

src/components/calcite-input-message/calcite-input-message.scss, src/components/calcite-label/calcite-label.scss, src/components/calcite-radio-button/calcite-radio-button.scss
Small style updates based on feedback from @asangma / Mitch (can never tag him)...
@eriklharper - I removed the overrides from radio-group as the labels now display at that size by default.
Update font-weight and size of calcite-label
Removes explicitly defined label size from calcite-radio-button as it's no longer needed
Calcite-input-message no longer has font-size set, so it should display at same scale as container.
Resolves #582
=> Update label styling

src/components/calcite-scrim/calcite-scrim.scss
scrim: set pointer events to none by default
=> scrim: set pointer events to none by default

CHANGELOG.md, src/components/calcite-switch/calcite-switch.stories.js, src/components/calcite-switch/calcite-switch.tsx, src/demos/calcite-switch.html
Fixes #602  cc @MikeTschudi
- Adds lookup for RTL
- Updates story, dev demo, changelog
We weren't looking up for a wrapping RTL, should be fixed now:
=> [calcite-switch] Fix RTL display

CHANGELOG.md, src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion/calcite-accordion.scss
Fixes #289 cc @TheBlueDog @bstifle 
- Updates rotation of icon-position=end icons for chevron and caret values (does not affect plus-minus)
- Updates some rotation values to more consistently animate in LTR and RTL
- Update changelog
Example:
=> [calcite-accordion] Update display of icon-position=end icons

conventions/README.md
The conventions write up was pretty out of date. Lots of advice we no longer use, links were broken, the only examples were tabs, etc. 
I've added new content about class names, rewritten the theming section, and given everything a general once over for spelling/accuracy. You can read through a non-diff version here: https://github.com/Esri/calcite-components/tree/conventions/conventions
=> 📜 update the conventions document

CHANGELOG.md, src/components/calcite-tree-item/calcite-tree-item.scss
Fixes #605 cc @MikeTschudi
I don't think this will cause unexpected changes for anyone?
- Add `word-break: break-word` to slotted children to prevent overflow of long, unbroken strings
- Updates changelog
| Before  | After |
| ------------- | ------------- |
| <img width="189" alt="Screen Shot 2020-05-20 at 11 17 12 AM" src="https://user-images.githubusercontent.com/4733155/82482767-2da35800-9a8c-11ea-9a1b-98ec9c1163c9.png"> | <img width="189" alt="Screen Shot 2020-05-20 at 11 17 24 AM" src="https://user-images.githubusercontent.com/4733155/82482787-3562fc80-9a8c-11ea-82cd-452a7cc42968.png"> |
=> [calcite-tree] Add break-word for long wrapping tree items

CHANGELOG.md, src/assets/demo/validateInput.js, src/components/calcite-date/calcite-date.tsx, src/components/calcite-input-message/calcite-input-message.e2e.ts, src/components/calcite-input-message/calcite-input-message.scss, src/components/calcite-input-message/calcite-input-message.tsx, src/components/calcite-input-message/readme.md, src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.stories.js, src/components/calcite-input/calcite-input.tsx, src/components/calcite-input/readme.md, src/components/calcite-label/calcite-label.scss
Some various input / input-message updates
Resolves #614 cc @noahmulfinger
Resolves #617 cc @noahmulfinger
Resolves #595 cc @jcfranco 
- BREAKING: `calciteInputChange` event renamed to the more accurate `calciteInputInput`
- Fix for calcite-input-message cursor being visible when inactive
- Inputs now control their own icon fill color (for instances when used outside calcite-label and inherited css is not available)
- "valid" inputs will now color their icon green, if present cc @noahmulfinger
- Removes unused "appearance" prop on calcite-input-message
- Update calcite-date to use new calcite-input event name cc @paulcpederson 
- Cleanup storybook
- Update readme
=> BREAKING: Input and Input Message cleanup

CHANGELOG.md, src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion-item/calcite-accordion-item.tsx, src/components/calcite-accordion-item/readme.md, src/components/calcite-accordion/calcite-accordion.scss, src/components/calcite-accordion/calcite-accordion.tsx, src/components/calcite-accordion/readme.md
Resolves #457 
- BREAKING Updates various event names and typings
- Now uses typed element references to determine active items rather than generated GUID
- Fixes incorrect keyboard navigation behavior in instances of nested accordions within other accordions
- Keyboard navigation with home/end/up/down will now cycle between items in the currently focused nested accordion, rather than incorrectly jump between items between all accordions in the child / parent tree
- Users can tab between nested instances of calcite-accordion
- Removes host-context and explicitly sets icon-position on child items
- this fixes instances where nested accordions could not adhere to their requested icon-position because they were incorrectly inheriting from a parent
=> BREAKING: Cleanup/accordion

package-lock.json, package.json
Published calcite-ui-icons to npm and bumped the dependency.
=> 🧹bump calcite-ui-icons to latest 📦 v3.2.0

src/components/calcite-switch/calcite-switch.scss
Fixes #624 cc @cosbyr 
- Remove unintended switch handle movement on hover in RTL
This used to be a hover animation we had for both RTL and LTR - looks like the RTL style never got removed.
=> Remove unintended switch handle movement on hover in RTL

CHANGELOG.md, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-group/readme.md, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.tsx, src/interfaces/Dropdown.ts
This tackles the event renaming part of #464. 
BREAKING CHANGE: The following calcite-dropdown events have been renamed:
* calciteDropdownItemHasChanged => calciteDropdownItemChange
* registerCalciteDropdownGroup => calciteDropdownGroupRegister
* calciteDropdownItemSelected => calciteDropdownItemSelect
* closeCalciteDropdown => calciteDropdownClose
* registerCalciteDropdownItem => calciteDropdownItemRegister
=> refactor(calcite-dropdown)!: rename events and stop propagation of internal ones

CHANGELOG.md, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown-item/readme.md, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-dropdown/readme.md, src/demos/calcite-date.html
Related issue #464 
This adds a 'read-only' `selectedItems` convenience property to the dropdown (akin to `HTMLSelectElement#selectedOptions`). 
Additionally, `calciteDropdownSelect` is now is emitted when an item is selected/deselected.
cc @kstinson14 
* This leverages the existing `calciteDropdownItemChange` event, which fires when items are selected. This event is now internal.
* The property isn't a true read-only prop and can be overridden by users. 
* There is no corresponding attribute for this.
* Moves item registration logic to `componentWillLoad` to avoid re-rendering warnings from build.
* Groups no longer process item selection when `selectionMode === "none"`.
* `selectedItem` updates could be optimized in the future once the internal dropdown `items` property stays fixed (it …
=> feat(dropdown)!: add selectedItems property and calciteDropdownSelect event

src/components/calcite-alert/calcite-alert.scss, src/components/calcite-notice/calcite-notice.scss
Addresses part of https://github.com/Esri/calcite-components/issues/645 cc @FelFly 
We were only styling slotted `div` elements - this ensures any slotted element will have consistent styling.
=> Ensure consistent styling of any slotted element in alert and notice

src/components/calcite-stepper/calcite-stepper.tsx
=> Fixing `__spreadArrays` error in ES5 builds

readme.md, src/components/calcite-date/calcite-date.tsx, src/components/calcite-split-button/calcite-split-button.tsx, stencil.config.ts, support/preact.ts
While setting up CC with a preact project that used TypeScript I ran into a lot of problems. First, you get the "Property 'insert-calcite-tag-name' does not exist on type 'JSX.IntrinsicElements':
- https://github.com/ionic-team/stencil/issues/1090
- https://github.com/ionic-team/stencil/issues/1636
So you have to augment the intrinsic elements types with the custom tag names from calcite components. After you do that, then you realize that the event names don't work in preact if you use the events from the provided types. Ie `onDropdownClose` will never fire, you have to use `ondropdownClose`:
- https://github.com/preactjs/preact/issues/2592
This is a temporary fix that uses a custom output target to generate an additional typescript file for preact. If we get the ds framework bindings up …
=> create types for using calcite components with preact + typescript

CHANGELOG.md, src/components/calcite-button/calcite-button.e2e.ts, src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.stories.js, src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/readme.md, src/components/calcite-card/calcite-card.stories.js, src/components/calcite-link/calcite-link.e2e.ts, src/components/calcite-link/calcite-link.scss, src/components/calcite-link/calcite-link.stories.js, src/components/calcite-link/calcite-link.tsx, src/components/calcite-link/readme.md, src/components/calcite-split-button/calcite-split-button.e2e.ts, src/components/calcite-split-button/calcite-split-button.stories.js, src/components/calcite-split-button/calcite-split-button.tsx, src/components/calcite-split-button/readme.md, src/demos/calcite-button.html, src/demos/calcite-card.html, src/demos/calcite-link.html, src/demos/calcite-split-button.html
Resolves #665 
Breaking change to allow up to two icons in start / end positions on icons - should solve for some previously unaccounted for use cases - includes styling updates and handles two icons positioned together without text. Applies to `calcite-button`, `calcite-link`, `calcite-split-button` (with some slight syntactical differences to match the existing API in split-button).
Also adds an additional `dropdown-icon-type` value of `overflow` to `calcite-split-button`.
- 🚨 **BREAKING** - `calcite-button` - `icon-position` and `icon` props have been removed - you can now use `icon-start` and `icon-end` props to position up to two icons.
- 🚨 **BREAKING** - `calcite-link` - `icon-position` and `icon` props have been removed - you can now use `icon-start` and `icon-end` props to …
=> Add explicit start/end icons to button

src/components/calcite-tabs/readme.md, src/demos/calcite-tabs.html, src/index.html
I missed a few instances of "is-active" in the dev demos, this updates these to "active"
=> Docs cleanup for tabs

src/components/calcite-button/calcite-button.e2e.ts, src/components/calcite-loader/readme.md
- 🧪 - Updates button tests to check for `calcite-hydrated` attribute instead of `hydrated` class
- 📝 - Commits readme update for loader that didn't make it into prior PR
=> Fixes button tests for new calcite-hydrated attribute

CHANGELOG.md, src/components/calcite-button/calcite-button.tsx, src/components/calcite-card/calcite-card.tsx, src/components/calcite-loader/calcite-loader.e2e.ts, src/components/calcite-loader/calcite-loader.scss, src/components/calcite-loader/calcite-loader.stories.js, src/components/calcite-loader/readme.md, src/components/calcite-scrim/calcite-scrim.tsx, src/demos/calcite-loader.html, src/index.html
Follow up / some clean up for https://github.com/Esri/calcite-components/pull/709
- 🚨 - Adds changelog entry for breaking property change from `isActive` to `active`
- ♻️ - Updates instances of loader used in other components to new `active` prop
- 🧪 - Updates tests with new `active` property
- 📝 - Updates dev demo page with better spacing for inline loader
- 📚 - Updates storybook with better spacing for inline loader and knobs for configuration options
- ✨ - Formatting / Prettier changes
cc @asangma
=> [Loader] Cleanup for isActive  -> active prop change

src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-example/calcite-example.e2e.ts, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-stepper-item/calcite-stepper-item.tsx, src/components/calcite-switch/calcite-switch.tsx, src/components/calcite-tree-item/calcite-tree-item.e2e.ts, src/tests/utils.ts, src/utils/date.spec.ts, src/utils/date.ts
- Fixed dropdown without a group failing
- Fixed group-item warning for rendering
- Skipped the example component
- Removed conflicting event name
- ~~Skipped failing tree test // Not sure how to fix this one. @macandcheese?~~ Fixed it.
- Changed date util to throw error instead of console.error
- Updated pageSetup to not allow `console.error` for passing tests
- Fixed pre-rendering bugs with combobox and stepper-item
=> chore: fix tests for components

CHANGELOG.md, src/components/calcite-switch/calcite-switch.e2e.ts, src/components/calcite-switch/calcite-switch.tsx
#474 also asks to remove `change`, but I am not seeing it in der.
=> chore(switch): add switched to event detail

CHANGELOG.md, src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-modal/calcite-modal.stories.js, src/components/calcite-modal/calcite-modal.tsx, src/components/calcite-modal/readme.md, src/demos/calcite-modal.html
- **Open and close modal via an `active` prop rather than imperative methods.** This makes it much easier to use the modal in frameworks with unidirectional data flow.
- **Add `scale` prop to alter the size/padding.** This makes modal consistent with other scalable components.
- **Change `size` prop to `width`**. Also align the sizes with the syntax we use for scale (`"s" | "m" | "l"`)
- **Add ability to set custom modal widths.** Now `width` can also be passed a number. This allows devs to set a custom width for in-between modal sizes.
- **Move `fullscreen` to its own prop.**
- **Stop setting class on host.** This was the last instance of setting a class on the host element, so I've also removed it (#700)
I went down a lot of different roads trying to do custom sizes in a more eloquent …
=> Modal Cleanup

CONTRIBUTING.md, support/release.sh
Going through the release script step by step manually, I noticed that when I checked out a new temporary branch, the dist folder was actually missing a whole bunch of stuff. So I've removed the build that happens prior to prerelease and added both a full clean and rebuild in the temporary branch to the release script. 
I also added notes about the branch requirements for the release script to work.
=> fix release script

CHANGELOG.md, src/assets/demo/createAlert.js, src/components/calcite-accordion/readme.md, src/components/calcite-alert/calcite-alert.e2e.ts, src/components/calcite-alert/calcite-alert.resources.ts, src/components/calcite-alert/calcite-alert.scss, src/components/calcite-alert/calcite-alert.stories.js, src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-alert/readme.md, src/components/calcite-dropdown/readme.md, src/components/calcite-modal/readme.md, src/components/calcite-popover/readme.md, src/components/calcite-stepper/readme.md, src/demos/calcite-alert.html
Resolves https://github.com/Esri/calcite-components/issues/570 - cc @jwasilgeo - can you give this a look over? It should work as desired, while still maintaining a queue if multiple are added to DOM with active present.
Resolves https://github.com/Esri/calcite-components/issues/456
**BREAKING**
- 🚨 - removes `open` and `close` methods in favor of `active` prop
- 🚨 - removes public `currentAlert`, `alertQueue`, and `alertQueueLength` props (queue and opened / closed element available as event details)
**ADDED**
- 🆕 - adds `intlClose` prop for translating button close label
**CHANGES**
- ♻️ - No longer assigns GUID or relies on internal alertId string for queue and active state management
- ♻️ - Updates tests, dev demos, Storybook
- ♻️ - Some generated `readme` updates.
=> Alert updates

.storybook/helpers.js, src/components/calcite-alert/readme.md, src/components/calcite-button/calcite-button.stories.js, src/components/calcite-card/calcite-card.stories.js, src/components/calcite-checkbox/calcite-checkbox.stories.js, src/components/calcite-chip/calcite-chip.stories.js, src/components/calcite-dropdown/calcite-dropdown.stories.js, src/components/calcite-icon/calcite-icon.stories.js, src/components/calcite-input/calcite-input.stories.js, src/components/calcite-label/calcite-label.stories.js, src/components/calcite-link/calcite-link.stories.js, src/components/calcite-loader/calcite-loader.stories.js, src/components/calcite-modal/calcite-modal.stories.js, src/components/calcite-notice/calcite-notice.stories.js, src/components/calcite-popover/calcite-popover.stories.js, src/components/calcite-popover/readme.md, src/components/calcite-radio-button-group/calcite-radio-button-group.stories.js, src/components/calcite-radio-button/calcite-radio-button.stories.js, src/components/calcite-scrim/calcite-scrim.stories.js, src/components/calcite-slider/calcite-slider.stories.js, src/components/calcite-split-button/calcite-split-button.stories.js, src/components/calcite-stepper/calcite-stepper.stories.js, src/components/calcite-switch/calcite-switch.stories.js, src/components/calcite-tooltip/calcite-tooltip.stories.js, src/components/calcite-tree/calcite-tree.stories.js
This fixes a lot of the different stories. Essentially a storybook update broke some of our stories where components were using the `boolean` knob. This knob has never really functioned how we want it to (ie it renders `attr=false` rather than just not being there...). 
I've created a storybook helper which starts up a boolean knob and returns the correct prop so rather than getting `attr="true" | attr="false` you'll get `attr` or nothing.
=> 📚 create new boolean helper

src/components/calcite-tab/calcite-tab.tsx, src/components/calcite-tabs/calcite-tabs.e2e.ts
Updated the attribute to [`aria-labelledby`](https://www.w3.org/TR/wai-aria/#aria-labelledby). This came up from the color picker a11y tests.
=> fix(tabs): fix invalid aria attribute

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx
This changes how the color sampling takes place and uses the color/slider field's x/y instead of offsetting from layout.
=> test(color): remove border dependency from color sampling test

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/new-component.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/research.md, .github/ISSUE_TEMPLATE/tooling.md, .github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml
Adds issue/PR templates to help keep contributions consistent.
Labels from templates may need tweaking after installing since I'm not sure if they'll match as is. Another option is to get rid of emojis in labels to make it easier to keep these in sync.
=> chore: add GitHub issue/PR templates

.github/PULL_REQUEST_TEMPLATE.md
This adds info on the commit conventions we want to follow in PRs for future contributions, as well as extra details on a minor issue that may be confusing with the [`semantic-pull-requests`](https://github.com/zeke/semantic-pull-requests/) check.
=> chore: add info about conventional commits to PR template

package-lock.json, package.json
v1.0.0-beta.34 will cause a build issue in a consuming Stencil project unless `@types/color` is installed locally.
=> build(deps): move @types/color as a dependency so the public types resolve properly

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.scss, src/components/calcite-color/calcite-color.tsx, src/components/calcite-color/resources.ts
**Related Issue:** #750 
Adds `appearance` prop for color component. The value can be `default` (border) or `minimal` (borderless).
=> feat(color): add appearance property to support embedded use cases

src/components/calcite-label/calcite-label.scss
Fix for label misalignment in `calcite-radio-group` caused by removing an optional css var in `calcite-label` cc @eriklharper
=> fix(radio-group): Fix for label alignment

package-lock.json, package.json, stencil.config.ts
chore: update @stencil/core to v1.17.2
**Related Issue:** #485
I've been working on how to use calcite-components in rollup, and I think I've got a solution. To make it work, this pr uses the `dist-custom-elements-bundle` output target to generate a tree-shakable bundle of our components. This can then be imported into a rollup file and only the components that are used will be bundled into your app. Once this is published on npm I'll open an pr onto [calcite-components-examples](https://github.com/arcgis/calcite-components-examples/) with a working rollup example. 
For some reason, rollup will choke on the custom elements bundle (thinking it's not ESM and trying to wrap it) unless it's file extension is `.mjs`. This is a problem we may want to request stencil update. For now I've added a …
=> feat: add custom element bundle for tree-shaking

stencil.config.ts
**Related Issue:** #781
For some reason bumping `@stencil/core` exposed this bad link to the prerender config. Updating the path so it matches the actual prerender config file name fixes the issue.
=> test: update path to prerender config

src/components/calcite-popover/readme.md, src/components/calcite-stepper/calcite-stepper.stories.ts
**Related Issue:** # None
The storybook for stepper had some wrongly placed closing tags.
This also commits an update to generated readme.
=> fix(storybook): fix stepper storybook

src/components/calcite-popover/readme.md, src/components/calcite-split-button/calcite-split-button.stories.ts
The storybook for split button had a wrongly placed closing tag.
=> fix(storybook): fix split button storybook

src/components/calcite-button/readme.md, src/components/calcite-button/usage/internals.md
This PR adds documentation that extra attributes passed to `<calcite-button>` are passed to the internal `<a>` or `<button>`. I had an entire PR ready to add support for `target` until I ran the tests and found out that it already does it.
=> Document that you can pass additional attributes like target and type to <calcite-button>

src/components/calcite-panel/calcite-panel.scss, src/components/calcite-panel/calcite-panel.tsx, src/components/calcite-panel/resources.ts
Summary
Should fix #797
Should not cause this again:
https://github.com/Esri/calcite-app-components/issues/1000
Should not cause this again:
https://github.com/Esri/calcite-app-components/issues/1044
=> fix(panel): remove slot-container and associated styles

CHANGELOG.md, src/components/calcite-button/readme.md, src/components/calcite-checkbox/readme.md, src/components/calcite-color/readme.md, src/components/calcite-icon/readme.md, src/components/calcite-link/readme.md, src/components/calcite-tab-title/calcite-tab-title.e2e.ts, src/components/calcite-tab-title/calcite-tab-title.scss, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tab-title/readme.md, src/components/calcite-tabs/calcite-tabs.stories.ts, src/demos/calcite-tabs.html
**Related Issue:** Resolves #672 
Adds icon-start and icon-end props to tab-title component
Adds hasText watcher to tab-title component to properly space icons in tabs when no text is present
Update dev demo, storybook, tests, changelog
=> feat(tabs): Add support for icons in tab-title

src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts, src/components/calcite-shell-panel/calcite-shell-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.tsx, src/components/calcite-shell-panel/readme.md, src/components/calcite-shell/calcite-shell.stories.ts, src/components/calcite-shell/readme.md, src/components/calcite-shell/usage/advanced.md, src/demos/shell/block-configurations.html, src/demos/shell/demo-app-advanced-center-row.html, src/demos/shell/demo-app-advanced.html, src/demos/shell/demo-app-center-row-action-bar.html, src/demos/shell/demo-app-full-window-reversed.html
**Related Issue:** #815
Add a property to set the dynamic width of a ShellPanel's content area.
Should we also rename the `detached-scale` property to be explicitly about height?
=> feat(shell-panel)!: add width-scale property

package-lock.json, package.json, src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/components/calcite-tabs/calcite-tabs.e2e.ts
**Related Issue:** #831
This updates the tag used within the tabs container to be presentational to conform to the expected child tab roles.
Also, this bumps axe-core to v4.x and adds a basic a11y test to `calcite-tabs`.
=> fix(tabs): ensure proper ARIA roles

CHANGELOG.md, src/components/calcite-pagination/calcite-pagination.e2e.ts, src/components/calcite-pagination/calcite-pagination.tsx, src/demos/calcite-pagination.html
Current logic rendered page 1 link twice for single-page sets:
This fixes this edge case (and adds a test for it).
=> fix(pagination): prevent page one rendering twice when total is smaller than num

src/components/calcite-date/calcite-date.e2e.ts, src/components/calcite-input/calcite-input.tsx
https://github.com/Esri/calcite-components/issues/829
Removed  emission of calciteInputInput event on componentWillUpdate
=> fix(input): Removed calciteInputInput event on componentWillUpdate

.storybook/utils.ts
This updates the component HTML util to handle boolean attributes correctly.
**Note**: this is a port of https://github.com/Esri/calcite-app-components/pull/1053
=> docs: fix boolean attribute generation in story util

src/components/calcite-icon/calcite-icon.stories.ts
It is confusing that the knob name for the icon `scale` property is `size`.
=> docs: correct knob name to match property name

CHANGELOG.md, src/components/calcite-tab-title/calcite-tab-title.scss, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tabs/calcite-tabs.scss, src/components/calcite-tabs/calcite-tabs.stories.ts, src/components/calcite-tabs/calcite-tabs.tsx, src/components/calcite-tabs/readme.md, src/demos/calcite-tabs.html
**Related Issue:** Resolves #399 cc @jwasilgeo
Adds a position prop to allow content to be positioned above or below the tab nav
Update dev demo, storybook, changelog
=> feat(tabs): Add support for content positioning

src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html
**Related Issue:** Resolves #864 cc @gpbmike 
Updates the default icon for inputs of `type=email` from `send` to `email-address`
Note: input types that display a default icon with the `icon` attribute can still accept overrides by passing a Calcite UI Icon name to the attribute: `icon=banana`
=> feat(input): Update default icon of input type email

src/components/calcite-card/readme.md, src/components/calcite-checkbox/readme.md, src/components/calcite-label/readme.md, src/components/calcite-switch/calcite-switch.e2e.ts, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-switch/calcite-switch.stories.ts, src/components/calcite-switch/calcite-switch.tsx, src/components/calcite-switch/readme.md, src/demos/calcite-switch.html
**Related Issue:** Resolves #851  cc @rslibed
Adds `disabled` prop to `calcite-switch`
=> feat(switch): add disabled prop

src/components/calcite-scrim/readme.md
The example is a loading scrim. The text should reflect that.
=> docs(scrim): Correct text to match example for loading state

.storybook/main.ts
This fixes the following issue when running the storybook preview:
```
info => Loading custom manager config.
WARN Unable to close preview build!
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.entry should not contain the item '/.../calcite-components/node_modules/@storybook/addon-knobs/dist/register.js' twice.
ERR!    -> A non-empty array of non-empty strings
ERR!     at webpack (/.../calcite-components/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at /.../calcite-components/node_modules/@storybook/core/dist/server/dev-server.js:69:48
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration …
```
=> docs: fix storybook config

CHANGELOG.md, src/components/calcite-loader/calcite-loader.e2e.ts, src/components/calcite-loader/calcite-loader.tsx
**Related Issue:** #811
Fixed this prior to seeing the issue as I was using loader, but it solves the issue 811 describes
=> fix(loader): ensure fallback id for loaders is generated properly

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx, src/components/calcite-color/utils.ts
**Related Issue:** #822 
This fixes an issue that prevented events firing when the color was modified by a user interacting with the controls. 
Also, restores an unintentionally skipped color test.
=> fix(color): ensure color change event is emitted when color is modified via API or interaction

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #886 
Added `CalciteInputInput` event on up and down click on number input.
=> fix(input): emit calcite input input on up and down click on number input #886

src/components/calcite-split-button/calcite-split-button.tsx, src/demos/calcite-split-button.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/652
Extends access to a click handler on the secondary button/dropdown trigger in a `calcite-split-button`. It seems like nesting components like this one does introduce a number of challenges when trying to interface with children from elsewhere in an app. Since the primary click handler was already in place, I figured it made sense to follow that pattern, but I'm open to hearing other suggestions for how to go about achieving this behavior.
=> feat(split-button): add secondary click event

src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/components/calcite-tab-title/calcite-tab-title.scss, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tabs/calcite-tabs.e2e.ts, src/components/calcite-tabs/calcite-tabs.stories.ts, src/demos/calcite-tabs.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/640
This adds a `disabled` state to `<calcite-tab-title>`, following `link`'s pattern of using a `<span>` element. In order to remove focus state on a non-actionable tab title, I had to move the focus styles off of `:host` and into the child anchor element.
=> feat(tabs): add tab-title disabled state

src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html
**Related Issue:** Resolves #892 cc @kevindoshier
Clearable had been enabled by default within the `calcite-input` component for types `date`, `time`, and `search`... This PR removes that setting by default for `date` and `time`, since it is not consistently present across browers in native input elements. I opted to leave it on by default for `search`, since this is consistent across browsers.
For `date` and `time`, users can now just request the `clearable` prop to re-enable this previously default behavior.
=> fix(input): No longer set clearable by default on type date or time

src/components/calcite-sortable-list/calcite-sortable-list.e2e.ts, src/components/calcite-value-list/calcite-value-list.e2e.ts, src/components/calcite-value-list/calcite-value-list.tsx, src/demos/value-list/advanced.html, src/demos/value-list/basic.html, src/tests/utils.ts
Ports over changes from https://github.com/Esri/calcite-app-components/issues/1056.
This also adds a e2e utility to help test DnD interactions and unskips previous DnD tests. 🛠️
=> chore(value-list): port dragging between same-group value lists

src/components/calcite-block/calcite-block.scss, src/components/calcite-block/calcite-block.tsx
**Related Issue:** #902
* Aligns Block UI to be more like Accordion
* Simplifies some of the styles by leveraging _header styles
=> chore(block): aligning with accordion and simplifying styles

src/components/calcite-tree/calcite-tree.tsx
=> fix(tree): change tabindex to 0 to prevent forced first tab stop on page

src/components/calcite-input/calcite-input.tsx, src/components/calcite-label/calcite-label.scss, src/components/calcite-label/calcite-label.tsx, src/components/calcite-radio-group/calcite-radio-group.scss, src/components/calcite-radio-group/calcite-radio-group.stories.ts, src/components/calcite-radio-group/calcite-radio-group.tsx, src/demos/calcite-input.html, src/demos/calcite-radio-group.html
- Adds disabled prop to label
- Adds disabled prop to radio-group
- Updates demos and storybook
- Any calcite-* components contained within a disabled input will have disabled applied
- Handles "opacity stacking" of wrapped disabled inputs by setting contained elements opacity to 1 and only setting one level of opacity on the wrapping disabled label
**Related Issue:** Resolves #760 cc @joeyHarig
=> feat(label): Adds disabled prop to label, radio-group

src/components/calcite-label/calcite-label.scss, src/components/calcite-label/calcite-label.tsx
**Related Issue:** #916
* Adds no-margin property
* Updates label-text spacing.
=> feat(calcite-label): adds no-margin property. also updates label-text spacing

src/components/calcite-color/calcite-color.e2e.ts
Skips the 'color inputs' test suite since they are timing out sporadically. https://github.com/Esri/calcite-components/issues/928 will explore rewriting these tests to avoid using a custom timeout.
=> test(color): skip color input tests until they no longer time out

stencil.config.ts
**Related Issue:** #935 
Adds missing extras to restore legacy polyfills (see https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#opt-in-for-ie11-edge-16-18-and-safari-10-builds).
=> build: restore legacy polyfills

src/assets/styles/_popper.scss, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/resources.ts, src/components/calcite-tooltip/calcite-tooltip.scss, src/components/calcite-tooltip/calcite-tooltip.tsx, src/components/calcite-tooltip/resources.ts, src/utils/popper.ts
**Related Issue:** #651
Update calcite-dropdown to use Popper.js
@macandcheese this kills the animation of dropdown so we need to come up with another solution for animating.
Currently, animation is based off of the height of the menu changing. However, Popper needs to know the height before positioning so animating the height isn't a good idea. 
Is there something else we can animate?
=> refactor(dropdown): update calcite-dropdown to use Popper.js

package.json
Updates `next` release tag to avoid updating the beta one.
`@next` versions will be labeled as `1.0.0-next.<num>`. After we're officially on 1.0.0, we'll have better labels following the semver based on the current changelog: `<upcoming-semver>-next.<num>`
=> ci: tweak next release tag

.versionrc.json, support/ensureNonPrereleaseChangelog.ts
Updates a changelog generation helper to work with the latest [@next deployment changes](https://github.com/Esri/calcite-components/pull/985). 
This also updates the release commit message to skip builds for (pre)release commits.
=> chore: update changelog scripts

src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.e2e.ts
**Related Issue:** #992 
This updates the logic that determines whether a dropdown item has been selected or not. The main issue is that when the dropdown is in the shadow DOM, the event target will be the wrapping component and not the dropdown, which breaks the current logic.
=> fix(dropdown): fix item selection when dropdown is in a shadow DOM context

src/components/calcite-checkbox/calcite-checkbox.scss, src/components/calcite-checkbox/calcite-checkbox.tsx
=>  fix(calcite-checkbox): visibility of hidden input controlled by inline styles to prevent outside CSS from affecting its display

src/components/calcite-popover-manager/calcite-popover-manager.tsx, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts, src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx, src/components/calcite-tooltip/resources.ts, src/utils/dom.ts
**Related Issue:** #938
- Delays the closing/opening of a tooltip to allow a user to hover the tooltip with their mouse and keep it open. Defaults to 500ms and can't be changed for now.
- Once the tooltip is hovered, the timeout is cleared and started again on mouseout.
- Closes both hovered or focused tooltips on ESC key press (moved to document)
- Focus/Hover tooltips are opened/closed independent of each other
- Cleans up some linting on related files.
- Updates tests
- What should the default timeout be for opening/closing a tooltip? 
https://codepen.io/smhigley/pen/KjoerX?editors=0010
https://www.digitala11y.com/tooltip-role/
=> fix(tooltip): Add a11y improvements for hovering over a tooltip

src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #938
fix(tooltip): Keep tooltip visible if focus occurs after hover #938
=> fix(tooltip): Keep tooltip visible if focus occurs after hover #938

src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts, src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #1006
chore(tooltip): Add unit test for triggering tooltip from combinations of hover/focus #1006
- Also fixes minor issue when pressing escape while having a reference element hovered and focused the tooltip remains open.
=> test(tooltip): Add unit test for triggering tooltip from combinations of hover/focus #1006

.versionrc.json, package-lock.json, package.json, support/ensureNonPrereleaseChangelog.ts, support/prepareVersionUpdate.ts
This fixes an issue where `next` and `beta` versions would reset back to 0 when you mixed release types (this seems to be an issue w/ `standard-version`). 
* Added a new wrapper script for `standard-version` calls that keeps track of versions.
* ☝ is now used instead of `npm version`
=> chore: update release scripts to keep track of beta and next versions

src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-radio-button/calcite-radio-button.tsx, src/components/calcite-tile-select/calcite-tile-select.tsx
**Related Issue:** #977
I tested this on a local running instance of `arcgis-webviewer-app` without the workarounds that @kevindoshier was using as a temporary fix and I could not reproduce the bug, which consisted of unrendered input tags that correspond to each radio the second (and all subsequent) time(s) that the Map properties time slider options panel was opened.
Kevin wasn't able to verify these fixes on his local copy, but despite that these fixes make sense to commit anyway because it makes radio and checkbox more consistent with how all other calcite components create input elements.  We'll see once this makes it into a release and the webviewer can update calcite to see if this truly fixes the problem.
=> fix(calcite-radio-button): fixing issue where input isn't properly initialized in some cases

src/components/calcite-dropdown/calcite-dropdown.scss, src/demos/calcite-dropdown.html
**Related Issue:** Resolves https://github.com/Esri/calcite-components/issues/1012
This should restore the functionality that was in the example in the linked issue above in v38. @asangma can you confirm this doesn't break anything layout-wise?
=> fix(dropdown): Adjust display of slotted full width buttons

package.json
This updates the storybook deployer call to reuse the existing `docs` directory and not run its own build.
=> chore(docs): update storybook deployer to use existing docs build

src/components/calcite-checkbox/calcite-checkbox.e2e.ts, src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.tsx, src/components/calcite-switch/calcite-switch.e2e.ts
**Related Issue:** #975 
This change updates the custom change event behavior to match that of similar components like `calcite-switch` where the custom change event is only emitted when the component is "clicked" either programmatically (with `element.click()`) or actual user clicks from the mouse or keyboard.  When the `checked` attribute is controlled directly, this custom change event no longer fires because it was causing infinite loop issues.
=> fix(calcite-radio-button, calcite-checkbox): no longer fires custom change event when the checked attribute is controlled

.github/workflows/main.yml
This adds a custom workflow for updating issues/PRs after a release. It references a custom action (see https://github.com/jcfranco/actions-milestone-sync) that will:
1. create a new beta milestone
2. update all open PRs/issues to ☝
3. close the milestone associated with the release
**Note**: all milestones were renamed from `🔨 v1-beta.<x>`/`📦 v1-beta.<x>` to `v1.0.0-beta.<x>` to make labels easier to work with in Scriptland (the scriptiest place on Earth™).
=> ci(github): enable milestone-updating GitHub action

src/components/calcite-modal/calcite-modal.e2e.ts
`beforeClose` is exposed on `window` and not the test (context of `this`).
=> test(modal): fix context type for exposed function

CHANGELOG.md, support/ensureNonPrereleaseChangelog.ts
**Related Issue:** #1026 
This changes the strategy to ignore `@next` tags when generating the changelog. The changelog-generating script now ensures there are no `@next` tags when generating the changelog while staying on the same branch (`master`).
This also corrects invalid commit references in the changelog.
=> chore(changelog): ensure changelog script does not generate invalid commits

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx
The current initialization logic for `calcite-color` ignores the initial color value when set as a property. This is very noticeable whenever the component is initialized by a VDOM library that relies on props and not attributes (e.g., Stencil, maquette).
=> fix(color): initial user-defined value (prop) gets set properly

src/components/calcite-pagination/calcite-pagination.e2e.ts, src/components/calcite-pagination/calcite-pagination.tsx, src/demos/calcite-pagination.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/833
When `calcite-pagination`'s `num` attribute was set to `1`, the logic was off:
- for rendering the current page (showed `2` when `start=1`)
- which left the "previous" button visibly enabled but non-functional,
- and rendered one more page than necessary
This PR fixes that by specifically accounting for `num === 1`, and adds tests and demos. Let me know what I missed!
=> fix(pagination): prev/next disabled, page 1 shown

src/components/calcite-date/calcite-date.e2e.ts, src/components/calcite-date/calcite-date.tsx
**Related Issue:** #905
Due to peculiarities in how the `new Date()` function works, two digit dates are turned into four digits with `19` preceding the date you entered. This caused issues where you'd start typing a year and the input would change what you were typing to `1920`. To get around this, we were only allowing years with 4 digits. 
I've found a better way to ensure the year is correct and not converted to 19XX, so I'm removing the 4 digit requirement.
=> fix(date): allow 3 digit years in input #905

src/components/calcite-date-month-header/calcite-date-month-header.tsx, src/components/calcite-date/calcite-date.e2e.ts, src/components/calcite-date/calcite-date.tsx
**Related Issue:** #1017
Firing calcite date change event when year and month left/right buttons are interacted with. Also allowing shorter years now as we're handling them elsewhere.
=> fix(date): fire date change on interactions with calcite-date-month-header element

src/components/calcite-date/calcite-date.e2e.ts, src/components/calcite-date/calcite-date.tsx, src/demos/calcite-date.html, src/utils/date.ts
**Related Issue:** #722
When updating the value of the `calcite-date` element, we were always firing the `calciteDateChange` event. This led to devs having to handle infinite loops of `event => app state => value => event`.
=> fix(date): don't fire event on outside value update (#722)

src/components/calcite-color/calcite-color.e2e.ts
**Related Issue:** #928 
A [recent change](https://github.com/Esri/calcite-components/pull/1054) to the CI environment (thanks @paulcpederson!) stabilizes e2e tests and the color input ones are now running smoothly. 🧈
=> test(color): restore skipped color input tests

src/components/calcite-date/calcite-date.e2e.ts
Seems like there may be a problem in travis using the shadow-piercing selector to get an interactive element.
=> test(date): attempt to make date tests more consistent on travis

.github/workflows/main.yml
This updates the milestone-mover GH action with the latest, which fixes an issue where dependencies weren't bundled (as https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-and-push-your-action-to-github indicates).
=> ci(github): update actions-milestone-sync

src/components/calcite-tile-select-group/calcite-tile-select-group.e2e.ts, src/components/calcite-tile-select-group/calcite-tile-select-group.scss, src/components/calcite-tile-select-group/calcite-tile-select-group.tsx, src/demos/calcite-tile-select.html
**Related Issue:** #1020
Saw issue #1020 about documenting this behavior, but I don't think it was actually possible. I've also added a test suite for the group component as it now has a prop.
=> feat(tile-select-group): add layout prop for vertical tile select

src/components/calcite-tile-select/calcite-tile-select.e2e.ts, src/components/calcite-tile-select/calcite-tile-select.scss, src/components/calcite-tile-select/calcite-tile-select.tsx, src/demos/calcite-tile-select.html
**Related Issue:** #1021
We're seeing UI designs with full width tile select UI's quite frequently across the platform. One is referenced in #1021 .
I've added a `width` property (which we've used on other components). Default is `auto` (current behavior of tiles), with new option `full` which will set the tile to fill its parent. This should allow us to keep these UI's consistent with tiles as currently they're implemented as their own special components in all the apps themselves.
=> feat(tile-select): add width prop to tiles for full width option

src/components/calcite-shell-panel/calcite-shell-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.tsx, src/demos/shell/block-configurations.html
**Related Issue:** #1029 
Adds `detached-height-scale` to ShellPanel.
cc @jcfranco
=> feat(calcite-shell-panel): adds detached-height-scale property

src/components/calcite-block-section/calcite-block-section.tsx
**Related Issue:** #1074
This uses `intlExpand`/`intlCollapse` for native tooltips on a block section. These were previously only used to set `aria-label`.
I don't know if there's a way to test for this without screenshots, which is still pending (https://github.com/Esri/calcite-components/issues/577).
=> fix(block-section): use expand/collapse tooltips as a section's native tooltip

src/components/calcite-date-month-header/calcite-date-month-header.scss, src/components/calcite-date-month-header/calcite-date-month-header.tsx
**Related Issue:** #1069
When you click a button in safari, they helpfully move the focus to the `body` rather than the button you just clicked. This triggers the blur event and closes the date picker. The simplest workaround seems to be using an anchor with a `tabindex`. Setting `role=button` and handling keyboard interaction so it is accessible like a button would be.
=> fix(date): stop date from closing on month next/previous buttons in safari #1069

src/components/calcite-loader/calcite-loader.stories.ts
**Related Issue:** #1086
Updating the vars so the color knobs in the story book for custom loader colors work again.
=> docs(loader): fix custom theme css vars in storybook (#1086)

src/components/calcite-label/calcite-label.scss, src/demos/calcite-input.html
**Related Issue:** #1050
Input message inside a disabled label was always showing (not respecting `active` prop)
=> fix(label): prevent calcite-input-message from always showing in disabled label

.storybook/manager.ts
Per today's sync-up, this fixes the Storybook knob panel to the right.
=> chore(storybook): fix knob panel to the right

src/components/calcite-action-bar/calcite-action-bar.stories.ts, src/components/calcite-action-pad/calcite-action-pad.stories.ts, src/components/calcite-action/calcite-action.stories.ts, src/components/calcite-block/calcite-block.stories.ts, src/components/calcite-fab/calcite-fab.stories.ts, src/components/calcite-flow/calcite-flow.stories.ts, src/components/calcite-panel/calcite-panel.stories.ts, src/components/calcite-pick-list/calcite-pick-list.stories.ts, src/components/calcite-shell/calcite-shell.stories.ts, src/components/calcite-tip-manager/calcite-tip-manager.stories.ts, src/components/calcite-tip/calcite-tip.stories.ts, src/components/calcite-value-list/calcite-value-list.stories.ts
Consistent story titles FTW! 🏆
=> chore(storybook): rename app component story titles for consistency

.travis.yml, src/components/calcite-date/calcite-date.e2e.ts
Tests _sometimes_ fail with missing element when you query for an element inside a shadow dom boundary. This only happens on travis. All other environments work fine. For now, I'm just tabbing to the input and executing keyboard commands on the page instead.
=> test(date): work around missing shadow piercing element in e2e test

CONTRIBUTING.md
The doc-updating script was missing since it was disconnected from the `release:publish` script.
=> docs(contributing): add note on doc-updating script

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
Emits calciteInputInput on clear
Adds tests for clearing on key and clear button press
**Related Issue:**  Resolves #1065 cc @noahmulfinger
=> fix(input): Emit calciteInputInput on clear

src/components/calcite-card/calcite-card.scss, src/demos/calcite-card.html
When cards get put in a container using flexbox to make them all the same height, the actions on the bottom won't line up if cards have different content heights:
This pr places the footers at the bottom of the card:
This shouldn't impact any of the current card styles, and will only apply if the card has already been stretched vertically.
=> style(card): make card footers align for multiple cards in flex box row

src/components/calcite-popover/calcite-popover.scss
Post refactor, Panel and Flow in Popover were not doing scrolling correctly.
This fixes that.
=> feat(popover): adds flex-direction and slotted styles for panel and flow

src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-combobox-item/calcite-combobox-item.tsx, src/components/calcite-date-day/calcite-date-day.tsx, src/components/calcite-date-month/calcite-date-month.tsx
=> docs(calcite-alert, calcite-combobox-item, calcite-date-day, calcite-date-month): fix invalid JSDoc

src/components/calcite-label/calcite-label.e2e.ts, src/components/calcite-label/calcite-label.tsx, src/demos/calcite-label.html
Exclude id from attributes spread to child label
Add demo
Adds test
**Related Issue:** Resolves #1106 cc @jcfranco
=> fix(label): only render id on parent calcite-label

src/components/calcite-date-month-header/calcite-date-month-header.tsx, src/components/calcite-date/calcite-date.e2e.ts, src/components/calcite-date/calcite-date.stories.ts, src/components/calcite-date/calcite-date.tsx
**Related Issue:** #1122 
We were always using the "next month" string for both next and previous aria labels. This fixes that and also updates the storybook example to use the correct props as well.
=> fix(date): use correct props for next/previous month labels (#1122)

src/assets/styles/_header.scss, src/components/calcite-action/calcite-action.scss, src/components/calcite-block-section/calcite-block-section.e2e.ts, src/components/calcite-block-section/calcite-block-section.scss, src/components/calcite-block-section/calcite-block-section.tsx, src/components/calcite-block-section/resources.ts, src/components/calcite-block/calcite-block.scss, src/components/calcite-panel/calcite-panel.scss, src/components/calcite-panel/calcite-panel.tsx
**Related Issue:**  (#1131)
Fixes incorrect font sizes for
- Panel heading
- Block heading
- Block summary
Sorry...I messed up the commit history on the previous branch.
This one is cleaner.
Note: the use of Tailwind themes in component stylesheets will be refactored in an upcoming PR.
=> fix(panel, block, block-section): updates font-sizes

src/components/calcite-button/calcite-button.tsx, src/components/calcite-chip/calcite-chip.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-input/calcite-input.tsx, src/components/calcite-link/calcite-link.tsx, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-tab-title/calcite-tab-title.tsx
The pass through props weren't adhering to RTL set on the components, so this passes that down to the icon to correctly use `flip-rtl` at the `calcite-icon` level
=> fix(icon): Explicitly set dir on components with pass-through flip-rtl

src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** #918 cc @noahmulfinger
There was a discrepancy between how the modal functioned when clicking close vs. closing via Escape key. This adds a watcher to the "active" prop to sync it with the "is-active" state.
=> fix(modal): Allow re-opening of modal when close button is clicked

src/components/calcite-checkbox/calcite-checkbox.e2e.ts, src/components/calcite-checkbox/calcite-checkbox.tsx, src/demos/calcite-checkbox.html
=> fix(calcite-checkbox): resets to initial checked state when form reset event is triggered

src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/components/calcite-split-button/calcite-split-button.e2e.ts, src/components/calcite-split-button/calcite-split-button.scss, src/components/calcite-split-button/calcite-split-button.stories.ts, src/components/calcite-split-button/calcite-split-button.tsx, src/demos/calcite-split-button.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/796
Adds a passthrough `appearance` attribute to the `calcite-split-button` that lands on both the primary and secondary button elements, as well as a new `split-child` attribute on the `calcite-button` component to allow for styling specific to when they're inside split buttons!
=> feat(split-button): Add support for appearance

src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.tsx, src/demos/calcite-radio-button-group-rtl.html, src/demos/calcite-radio-button-group.html, src/demos/calcite-radio-button-rtl.html, src/demos/calcite-radio-button.html, src/demos/calcite-tile-select.html
=> fix(calcite-radio-button): last checked wins

src/components/calcite-pagination/calcite-pagination.e2e.ts, src/components/calcite-pagination/calcite-pagination.tsx
**Related Issue:** #1180
next button was disabled in cases where the last page had only 1 result.
=> fix(pagination): fix next button when last page has 1 element (#1180)

src/components/calcite-avatar/calcite-avatar.e2e.ts, src/components/calcite-avatar/calcite-avatar.scss, src/components/calcite-avatar/calcite-avatar.tsx, src/components/calcite-chip/calcite-chip.scss, src/components/calcite-chip/calcite-chip.stories.ts, src/demos/calcite-chip.html
This allows passing an avatar to a chip as per discussion yesterday. 
```html
<calcite-chip>
<calcite-avatar slot="chip-image" user-id="a81470986eaeee1833b74b7d8abcd5b2" username="cw" />
Carol Whitten
</calcite-chip>
```
@bstifle on the gray of the chip, the backgrounds were really hard to distinguish, so I lowered the lightness a bit. Had to tweak the initials font sizes a little as well so they wouldn't get cramped in this slightly smaller container. Take a 👀  and we can tweak as needed.
=> feat(chip): allow passing avatar as chip image

src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.tsx, src/demos/calcite-radio-button.html
=> fix(calcite-radio-button): all children text nodes render inside a single calcite-label

src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion/calcite-accordion.scss, src/components/calcite-button/calcite-button.scss, src/components/calcite-checkbox/calcite-checkbox.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-input/calcite-input.scss, src/components/calcite-label/calcite-label.scss, src/components/calcite-radio-button/calcite-radio-button.scss, src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-select/calcite-select.scss, src/demos/calcite-dropdown.html
**Related Issue:** #1186 #1137
This is an interim update to font sizes.
Note: this uses the `theme` utility, and that will be refactored with `@apply` in a future PR.
This is aimed at UI alignment with newly ported components.
This does not include any new line-height patterns.
The few line-height changes are intended to approximate previously defined line-heights relative to the new font-sizes..
=> feat: updates a shortlist of components with new font-sizes for each scale

src/components/calcite-inline-editable/calcite-inline-editable.e2e.ts, src/components/calcite-inline-editable/calcite-inline-editable.scss, src/components/calcite-inline-editable/calcite-inline-editable.stories.ts, src/components/calcite-inline-editable/calcite-inline-editable.tsx, src/components/calcite-inline-editable/readme.md, src/components/calcite-inline-editable/resources.ts, src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-inline-editable.html, src/index.html
`textarea`s will be handled in a separate PR.
**Related Issue:** #819 
Provides inline editing capabilities for calcite-inputs via compositional/wrapping component. 
```
<calcite-inline-editable>
<calcite-input placeholder="Hooray"/>
</calcite-inline-editable>
```
=> feat(inline editable inputs): support inline editable text inputs.

src/components/calcite-select/calcite-select.e2e.ts, src/components/calcite-select/calcite-select.tsx
**Related Issue:** #1226 
This fixes an issue where updating the option/option-group children caused duplicate items to be added. 
cc @priya4991
=> fix(select): keep internal native elements in sync with calcite option and option groups

src/components/calcite-tile-select/calcite-tile-select.scss, src/components/calcite-tile/calcite-tile.scss, src/demos/calcite-tile-select.html
Resolves #1063 cc @noahmulfinger 
Resolves #1098 cc @eriklharper @bstifle 
Adds disabled styling:
While adding the disabled styling, I ran into the issues described in #1098, so I tried to alleviate that as much as possible by simplifying the styling. I tried the "outset" focus as @bstifle suggested but it was ultimately unreliable with similar weirdness.
For tile-select items that SHOW a radio or checkbox, the focus state is applied to that input within the tile. Hover state for these configurations is a darker border.
For tile-select items that DO NOT SHOW a radio or checkbox, we apply an inset focus style. Hover state for these configurations is a blue border.
Additionally I've lightened the text for header and description by one step when a wrapped calcite-tile is …
=> feat(tile-select): Add disabled styling for tile select, updates hover and focus style

src/components/calcite-shell-panel/calcite-shell-panel.scss
Minor tweak to make shell-panel content height dynamic when detached.
@driskull @macandcheese  Would like to get this into a release.
=> fix(shell-panel): adds auto bottom margin to make height dynamic.

src/components/calcite-date-month-header/calcite-date-month-header.e2e.ts, src/components/calcite-date-month-header/calcite-date-month-header.scss, src/components/calcite-date/calcite-date.e2e.ts
[This line](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-date-month-header/calcite-date-month-header.scss#L70) would always hide and prevent mouse interaction with date's next/prev month buttons.
cc @zaramatheson
*Note*: added simple `calcite-date` test to verify that calendar is displayed when clicked.
=> fix(date): fix prev/next month buttons not rendering

src/components/calcite-color-hex-input/calcite-color-hex-input.e2e.ts, src/components/calcite-color-swatch/calcite-color-swatch.e2e.ts, src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts, src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts, src/components/calcite-pick-list/calcite-pick-list.e2e.ts, src/components/calcite-pick-list/shared-list-tests.ts, src/components/calcite-value-list/calcite-value-list.e2e.ts
**Related Issue:** #1159 
This adds a11y tests to the following components:
* `calcite-color-hex-input`
* `calcite-color-swatch`
* `calcite-pick-list-group`
* `calcite-pick-list-item`
* `calcite-pick-list`
* `calcite-value-list`
=> test: add more a11y tests

src/components/calcite-notice/calcite-notice.scss
While using notice in Online, we found that in IE11 the text spilled outside the notice. This is apparently a problem in using an auto `flex-basis`: https://github.com/philipwalton/flexbugs/issues/170
=> fix(notice): prevent text overflow in smaller notices on ie11

src/components/calcite-button/calcite-button.scss, src/demos/calcite-button.html
Fixes "loading" loader not appearing when using "transparent" appearance type cc @TheBlueDog
Also adds example to dev demo:
=> fix(button): Fix loading style in transparent button

src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.scss
**Related Issue:** Resolves #1241 cc @noahmulfinger 
This removes instances of host-context based styles that don't apply in FF or Safari.
@asangma can you verify the styles are still as intended after the last few PR? Thanks!
=> fix(dropdown): Fix styles in Firefox and Safari

src/components/calcite-checkbox/readme.md
=> docs(calcite-checkbox): removing usage instructions for deprecated child input feature

src/components/calcite-select/calcite-select.scss, src/components/calcite-select/calcite-select.tsx, src/demos/calcite-select.html
**Related Issue:** Resolves #1238 cc @AdelheidF 
Updates styling a bit to prevent text overlaps by adding padding to the select div.
@jcfranco I moved styling to a dir tag on host instead of css utility, let me know if that was set up in that way for a reason I didn't catch.
=> fix(select): Fix overlapping text with long options

package-lock.json, package.json, src/components/calcite-modal/calcite-modal.tsx
This moves dependencies that get bundled into the distributable to dev dependencies. `@popperjs/core` is still kept as a dep for the types referenced in the component types.
This also changes `@a11y/focus-trap` to point to the NPM package instead of a personal fork. Additionally, this decreases modal's bundle size because the utils are tree-shaken.
=> build: move non-dependencies to devDependencies

src/components/calcite-rating/calcite-rating-resources.ts, src/components/calcite-rating/calcite-rating.e2e.ts, src/components/calcite-rating/calcite-rating.scss, src/components/calcite-rating/calcite-rating.stories.ts, src/components/calcite-rating/calcite-rating.tsx
- Adds two additional props for configuring screen reader labels for the rating component. 
- Structures the rating like a radio-input group (left/right to change selection, etc)
- Updates styles to use tailwind
@macandcheese can you look at these styles and make sure it visually looks like it used to?
=> fix(rating): add props for accessible labels, structure as radio button

src/components/calcite-rating/calcite-rating.scss
Not 100% why, but rating stars display vertically now due to some weird interaction with `fieldset` and `display: flex`. Seems like `inline-block` solves it...
=> fix(rating): fix ratings appearing vertically in certain sites

src/components/calcite-switch/calcite-switch.e2e.ts, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-switch/calcite-switch.stories.ts, src/components/calcite-switch/calcite-switch.tsx, src/components/calcite-switch/readme.md, src/demos/calcite-switch.html
**Related Issue:** https://github.com/Esri/calcite-components/issues/1220
Beginning to remove instances of offering "red" versions of colors and associated color props. Link, Button, soon to come.
Users can STILL ACHIEVE these designs if absolutely necessary by overriding css vars for the particular component instance. But we want to remove them from the "off the shelf" options.
Also updates stories a bit to have examples without labels, and then an explicit story with a calcite-label.
=> feat(switch)!: Remove red variant and color prop

src/components/calcite-select/calcite-select.e2e.ts, src/components/calcite-select/calcite-select.tsx
**Related Issue:** #1262 
This updates `calcite-select` to emit its change event after children have been updated in the DOM. This is needed to ensure correct results when querying the DOM for the selected option after the event.
=> fix(select): ensure select change event fires after render update

src/components/calcite-tree-item/calcite-tree-item.scss, src/demos/calcite-tree.html
**Related Issue:** Resolves #522 cc @capeoples @cosbyr 
This limits the appearance of indicators.. If a tree has "lines" enabled - the active indicator is a blue border. If a tree doesn't, it's just the dot.
This pr does NOT add the checkmarks for multiple-select options, I will open a new issue for that, but this was needed by Online ASAP.
Doing that down the road may necessitate an "indicator-type" prop, but for now this seems like a simple non-breaking-change solution.
=> feat(tree): Update indicator styling

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/new-component.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/research.md, .github/ISSUE_TEMPLATE/tooling.md
Label emoji have been dropped, so this updates our GH issue templates to match.
=> chore: update issue template labels

src/components/calcite-checkbox/calcite-checkbox.tsx
**Related Issue:** #1290 
The fix for this just removes the keydown handler which isn't needed anymore and was just causing a double trigger to occur.
=> fix(calcite-checkbox): space key works again on Firefox

src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-panel/calcite-panel.tsx
**Related Issue:** #1277
feat(panel): setFocus to back button on calcite-panel. #1277
=> feat(panel): setFocus to back button on calcite-panel. #1277

CHANGELOG.md
didn't revert a commit from a failed release step, updating changelog by hand
=> chore(changelog): remove duplicate beta.42 entry

src/components/calcite-color-hex-input/calcite-color-hex-input.e2e.ts, src/components/calcite-color-hex-input/calcite-color-hex-input.tsx, src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx, src/demos/calcite-color-hex-input.html
**Related Issue:** #866 
This enhances `calcite-color` and `calcite-color-hex-input` to allow nudging values when using the arrow keys. Values are nudged by 1 or by 10 if the shift key is pressed alongside an arrow key.
Note that for the hex input, each channel value will be nudged. This is follows how Figma's hex input works, which is referenced in the related issue.
=> feat(color): allow color input nudging by using ⬆ ⬇ (+shift) keys

src/components/calcite-button/calcite-button.e2e.ts
Fixes naming issues in the button test introduced in https://github.com/Esri/calcite-components/pull/1271
=> test(button): Fixes button tests

src/utils/dom.spec.ts
Fixed `setRequestedIcon` test block nesting.
🐦 :egg: 🌲
=> test(dom): fix nesting

.storybook/preview-head.html, src/components/calcite-accordion-item/calcite-accordion-item.e2e.ts, src/components/calcite-accordion/calcite-accordion.e2e.ts, src/components/calcite-accordion/calcite-accordion.stories.ts
**Related Issues:** #1114 #1159 
Adds tests for accessibility and updates the story.
=> chore(accordion): Update tests and stories

package.json
This new command is useful for debugging calcite in say the WebViewer App when using `npm link` to symlink the calcite repo.  `npm start` works for the initial build, but fails to update after changes are made, but this new watch script, which just calls `stencil build --watch` works much more consistently.
After merging this, will update https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/wiki/How-to-live-debug-calcite-components-and-arcgis-components-in-arcgis-webviewer-app to use this new `npm run build:watch` command instead of `npm start`.
=> build: adding a build watch command for debugging with npm link in external apps

src/components/calcite-card/calcite-card.e2e.ts, src/components/calcite-card/calcite-card.tsx, src/components/calcite-card/resources.ts, src/demos/calcite-card.html
**Related Issue:** #1159 
Caught one! While adding accessible tests to cards, I found that our rendered checkbox in the "selectable" card was not accessible. This PR adds two `intl-*` strings to the card component with English fallbacks to "Select" and "Deselect", updates the wrapping element around the checkbox to be a label, and sets aria-label and title. 
I opted to use title to display the "Select" and "Deselect" promps, I suppose this could also be a tooltip... 
Thoughts there on UI - tooltip is certainly nicer looking than a title but may not always be wanted... @mitc7862 @bstifle @asangma ?
Thoughts on UX of chosen text strings @capeoples - they could always be overridden with another English word as well if Select and Deselect are not desired by an app for whatever reason. …
=> feat(card): Adds checkbox label props for selectable cards

src/components/calcite-value-list-item/calcite-value-list-item.e2e.ts
This adds a test suite (based on calcite-pick-list-item) since it was never added. 😱
=> test(value-list-item): add e2e suite

src/components/calcite-value-list-item/calcite-value-list-item.e2e.ts, src/components/calcite-value-list-item/calcite-value-list-item.tsx
**Related Issue:** #1306
This adds an event emitter to `calcite-value-list-item` to have the event listener show up in the types. The `calciteListItemRemove` event is emitted by the wrapped `calcite-pick-list-item` component.
cc @pemberdom
~Note that this adds a test suite (based on `calcite-pick-list-item`) since it was never added. 😱~ moved over to #1313
=> feat(value-list-item): add event emitter to value-list-item

screener.config.js
This setting change will prevent Travis from failing (when the rest of the build succeeds) when Screener detects visual regressions.  Merging continues to be blocked while Screener regressions are resolved.  Once Screener regressions are resolved, the Github PR's Screener status will update and greenlight the PR properly without having to re-run the Travis build again.
See setup steps here for more information: https://screener.io/v2/docs/github
=> build: setting Screener's failureExitCode to 0 so that it doesn't break successful Travis builds

src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** Resolves #1003 cc @joeyHarig 
Ensures the close event is fired when a user clicks on a dropdown-trigger of an open dropdown.
Also adds a check to prevent the close function from running when "shift tabbing" backwards through triggers with closed dropdowns.
=> fix(dropdown): Emit close event on trigger click

src/components/calcite-notice/calcite-notice.e2e.ts
**Related Issues:** #1159 
Adds tests for accessibility.
=> test(notice): Update tests

src/components/calcite-alert/calcite-alert.stories.ts
Uses the boolean helper to allow auto-dismiss to be false by default - this is a better "default" story and will also prevent Screener from taking snapshots at different dismiss progression percentages. 
=> docs(alert): Update Storybook

src/components/calcite-action-bar/calcite-action-bar.e2e.ts, src/components/calcite-action-bar/calcite-action-bar.tsx, src/components/calcite-action-pad/calcite-action-pad.e2e.ts, src/components/calcite-dropdown-item/calcite-dropdown-item.e2e.ts, src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-radio-group/calcite-radio-group.e2e.ts, src/tests/commonTests.ts
Stems from https://github.com/Esri/calcite-components/pull/1309#discussion_r534349890
This adds the following improvements to the `focusable` test helper:
* `focusId` can now be specified to be passed into `setFocus()` (if the component supports focusing different parts)
* uses a selector to match focused element instead of an element's tag
* can specify a selector to match the focusable element on the light and shadow DOM. The shadow DOM use case is used to assert the actual elements focused inside a component's shadow tree.
=> refactor: enhance focusable test helper to support more use cases

src/components/calcite-date-month-header/calcite-date-month-header.tsx, src/components/calcite-date/calcite-date.scss, src/components/calcite-date/calcite-date.tsx, src/components/calcite-date/readme.md, src/demos/calcite-date.html, src/utils/date.ts
BREAKING CHANGE: date component no longer supports setting in input proxy
**Related Issue:** #1111
Date component in certain timezone (basically anything past the international dateline) was getting stuck in a render loop. Delving into it there were actually quite a few multiple renders being fired. To solve, I've had to remove the proxy input support for the date component. I've also reworked some updates so that it's more efficient in how it renders.
Other than the removal of proxy, the API/UX should remain the same.
=> fix(date): solve rerender issues in some timezones (#1111)

package.json, src/components/calcite-popover-manager/calcite-popover-manager.tsx, src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/resources.ts, src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx, src/components/calcite-tooltip/resources.ts, src/demos/calcite-popover.html, src/utils/dom.ts
**Related Issue:** #548
fix(popover, tooltip): Allow both tooltip and popover to share the same referenceElement.
- Uses data-attribute for referenceElement ID instead of aria-describedby.
- Adds aria-expanded and aria-controls to popover for added a11y.
- No longer sets aria-describedby on popover referenceElement.
- Cleanup.
=> feat(tooltip, popover): Make Tooltip ❤️  Popover

.github/workflows/milestone-mover.yml
Renamed and updated GH action to latest.
=> chore(github): update actions-milestone-sync

src/components/calcite-stepper/calcite-stepper.resources.ts
chore: remove unnecessary code from stepper resources
---
Replacing a substring with itself has no effect and usually indicates a mistake, such as misspelling a backslash escape.
=> chore: remove unnecessary code from stepper resources

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.stories.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-combobox/readme.md, src/demos/calcite-combobox.html, src/index.html
This is the first of several prs updating the combobox. Adds `max-items` property which behaves in exactly the same way the prop does on the dropdown component. Essentially, cap the height of the popover content to a particular number of items. 
Added a link to the combobox demo from the index as well.
=> feat(combobox): add max-items prop for combobox

PROJECT_GUIDELINES.md
Adds a bit about naming conventions for branches cc @caripizza 
Open to content suggestions but wanted to get something in there.
=> docs(guidelines): Add guidelines around branch naming

package.json
Discovered that by adding the `--dev` option along with `--watch` you can get source maps enabled when debugging the build inside of `arcgis-webviewer-app` and the code is easier to read as well for debugging and breakpoints.
=> build: adding build:watch-dev command to enable source maps and useful dev features while debugging calcite in external apps

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-input-message/calcite-input-message.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/tests/commonTests.ts
* Removes overlooked `only` set on color test suite and fixes failing tests by splitting up tests and updating test values.
* Fixes issue with `reflects` helper (boolean attributes appear to not be removed in Puppeteer, but rather set to `""`).
* Update `calcite-input-message` rendering test to not assert visibility.
=> test(color, input-message, radio-button): stabilize tests

src/assets/styles/global.scss, src/components/calcite-alert/calcite-alert.tsx, src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx, src/components/calcite-tree-item/calcite-tree-item.e2e.ts, src/components/calcite-tree-item/calcite-tree-item.tsx
**Related Issue:** #1374 
This introduces a special attribute (`calcite-hydrated-hidden`) to hide hydrated components. This support boolean attribute would help prevent the default styling applied by `calcite-hydrated`, which makes any host component visible. This is undesired for a few components (`calcite-alert`, `calcite-popover`, `calcite-tooltip` and `calcite-tree-item`).
=> refactor: use different selector to hide components that should not be visible on first render

src/components/calcite-split-button/calcite-split-button.e2e.ts
**Related Issue:** #1159
Add some a11y tests for the split-button component
(Redo of #1370)
Sorry for the duplicate PR here! My travis build for the last PR was failing due to attempting the PR from a fork, so I needed to make another attempt from a direct clone of the repo.
=> test(split-button): Add some a11y tests

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.tsx
**Related Issue:** #675
Added changes from [macandcheese](https://github.com/macandcheese/calcite-components/commit/77ae6f2ab1d56c95c8393125db966ce0f4bc7e6d#diff-8f6e4c214e58e59f3253d9f369db62edcd3ae99a530d26a19e42f5802c96f77bR81) to fix a11y attributes
=> fix(calcite-dropdown): calcite-dropdown-item uses unsupported ARIA attribute

src/components/calcite-tab-nav/calcite-tab-nav.e2e.ts, src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/components/calcite-tab-title/calcite-tab-title.tsx, src/demos/calcite-tabs.html
**Related Issue:** #1356
Fixes the active tab highlight not being positioned correctly in RTL. While I was working on this, I noticed the icon margins for tabs in RTL were also messed up, so I fixed that as well. Sorry @caripizza if you were working on this one, I saw you were assigned to the issue. We ran into this bug in our RC testing, so I wanted to get a fix in as soon as I could.
(Redo of #1383)
Sorry for the duplicate PR here! My travis build for the last PR was failing due to attempting the PR from a fork, so I needed to make another attempt from a direct clone of the repo.
=> fix(tab-nav, tab-title): fix tab icons and active tab highlight in rtl

src/components/calcite-select/calcite-select.e2e.ts, src/components/calcite-select/calcite-select.tsx
**Related Issue:** #1250
This enhances `calcite-select`'s API with a convenience prop for the currently selected option. 
Note that the prop technically be read-only, but at least it will be doc'd as such.
=> feat(select): add selectedOption convenience prop

src/components/calcite-input/calcite-input.resources.ts, src/components/calcite-input/calcite-input.tsx
Renamed input const to include word separators.
=> refactor(input): rename resource const

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #1389
fix(input): Prevent error when changing the 'step', 'min', or 'max' properties.
=> fix(input): Prevent error when changing the 'step', 'min', or 'max'

src/components/calcite-tab-nav/calcite-tab-nav.tsx, src/demos/calcite-tabs.html
**Related Issue:** none
Sort of a follow-on to #1385.  While I was installing the fix introduced in that PR in my app, it didn't totally fix the problem I was seeing.  
It seems like the way we were calculating the tab indicator offset in RTL worked for our simple demo examples, but not for more complex, nested layouts.  I added an example on the tabs demo page to show the problem:
The first "RTL tabs" example shows the current implementation of the offset calculation working correctly.  This is just a `calcite-tabs` element at the top level of the document.
The second "Scrollable RTL Tabs in Container" example shows where the calculation breaks down.  It's a `calcite-tabs` element contained within two wrapping divs, an outer of 100% width and an inner of 500px width.  Its tab indicator …
=> fix(tab-nav): change rtl tab indicator position to fix nested layouts

src/components/calcite-accordion/calcite-accordion.stories.ts, src/components/calcite-action-bar/calcite-action-bar.e2e.ts, src/components/calcite-action-bar/calcite-action-bar.stories.ts, src/components/calcite-action-pad/calcite-action-pad.e2e.ts, src/components/calcite-action-pad/calcite-action-pad.stories.ts, src/components/calcite-block/calcite-block.stories.ts, src/components/calcite-flow/calcite-flow.stories.ts, src/components/calcite-panel/calcite-panel.stories.ts, src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts, src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts, src/components/calcite-pick-list/calcite-pick-list.e2e.ts, src/components/calcite-pick-list/calcite-pick-list.stories.ts, src/components/calcite-pick-list/shared-list-tests.ts, src/components/calcite-radio-group/calcite-radio-group.e2e.ts, src/components/calcite-select/calcite-select.e2e.ts, src/components/calcite-select/calcite-select.stories.ts, src/components/calcite-shell/calcite-shell.stories.ts, src/components/calcite-tip-manager/calcite-tip-manager.stories.ts, src/components/calcite-value-list-item/calcite-value-list-item.e2e.ts, src/components/calcite-value-list/calcite-value-list.e2e.ts, src/components/calcite-value-list/calcite-value-list.stories.ts, src/demos/_assets/head.ts, src/demos/flow/adding-items.html, src/tests/utils.ts, stencil.config.ts
Stems from https://github.com/Esri/calcite-components/pull/1386#discussion_r538893225. 
> Prettier runs on each commit, but it doesn't format embedded content if it can't recognize it. [Looking at the docs](https://prettier.io/docs/en/options.html#embedded-language-formatting), I think we could have this work automatically wrapping `dedent` in a tagged template called `html`, which Prettier will pick up. Then we would only need to do something similar to get automatic formatting:
> 
> ```ts
> const page = await newE2EPage({
>   html: html`
>       ...some markup
>   `
> });
> ```
> 
> I'll submit a PR for this. Thanks for the idea! 🎉 
This adds a utility tagged template named `html`, which will give Prettier a hint to format wherever we have embedded HTML (e.g., …
=> chore: add helper to enable auto-formatting of HTML template strings

src/assets/styles/_popper.scss, src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-date/calcite-date.scss, src/components/calcite-dropdown/calcite-dropdown.scss
**Related Issue:** #1381
fix(dropdown): Set dropdown scale to 0 when inactive. #1381
Sets the transform scale to zero instead of positioning offscreen which causes scrolling issues. This way, the menu is not taking up any space when invisible but still lets popper calculate the height it needs in order to correctly position the element. Using `display:none` would not allow that and would also kill the animation.
=> fix(dropdown): Set dropdown scale to 0 when inactive. #1381

src/components/calcite-chip/calcite-chip.tsx, src/components/calcite-combobox-item/calcite-combobox-item.scss, src/components/calcite-combobox-item/calcite-combobox-item.tsx, src/components/calcite-combobox-item/resources.ts, src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.stories.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/demos/calcite-combobox.html, src/utils/key.ts
Prior to updating the tests for this component, I wanted to get everybody's feedback/design review on this new interaction model for the combobox. This is not a breaking change as it doesn't actually change the API at all, just the internal implementation. 
Main change:
- selected chips appear inside text box rather than above
- don't have to focus through every chip, focus is managed entirely by component. This model is valid per the combobox spec:
> If the popup element supports `aria-activedescendant`, in lieu of moving focus, such keyboard mechanisms can control the value of `aria-activedescendant` on the textbox element. When a descendant of the popup element is active, authors MAY set `aria-activedescendant` on the textbox to a value that refers to the active element within the …
=> feat(combobox): improved interaction, a11y support

src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** Fixes #1394 cc @patrickarlt 
Removes the overflow class from the document on `disconnectedCallback()`
Would like to add some tests to this but having trouble accessing the document classList in the e2e test... open to suggestions there.
=> fix(modal): Remove overflow class when modal is removed from DOM

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.stories.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/demos/calcite-combobox.html
**Related Issue:** #558
New prop `custom-values` allows users to enter values in the combobox that don't appear in the known items list. This is useful for tags where new option entry is allowed.
=> feat(combobox): add custom-values prop that allows free entry of new tags

src/assets/styles/global.scss, src/components/calcite-button/calcite-button.scss, src/components/calcite-checkbox/calcite-checkbox.scss, src/components/calcite-date-day/calcite-date-day.scss, src/components/calcite-dropdown/calcite-dropdown.scss, src/components/calcite-input/calcite-input.scss, src/components/calcite-label/calcite-label.scss, src/components/calcite-link/calcite-link.scss, src/components/calcite-pagination/calcite-pagination.scss, src/components/calcite-radio-group/calcite-radio-group.scss, src/components/calcite-radio/calcite-radio.scss, src/components/calcite-select/calcite-select.scss, src/components/calcite-select/calcite-select.tsx, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-split-button/calcite-split-button.scss, src/components/calcite-stepper-item/calcite-stepper-item.scss, src/components/calcite-switch/calcite-switch.scss, src/components/calcite-tab-title/calcite-tab-title.scss, src/demos/calcite-select.html
**Related Issue:** Fixes #1416 cc @nwhittaker 
- Prevents pointer events on a disabled select
- Overrides browser-supplied disabled select styling
- Applies styling to disabled select
- Updates dev demo with examples of disabled select
Also:
- Updates value of disabled opacity css variable, updates across components
-- This was previously set to 0.3 -> this updates to 0.5 across the board and updates a few instances that weren't using the css var (that were set at 0.4). cc @bstifle cc @asangma 
- Select now inherits theme from a parent if set. cc @jcfranco
-- Updates dev demo with examples of inheriting theme from wrapping calcite-label
=> Updates disabled select styling, updates disabled opacity value across components

src/components/calcite-date/calcite-date-nls/sk.json, src/components/calcite-date/calcite-date.e2e.ts
**Related Issue:** #1355
When calendar locale is set to Slovak, the week now starts on Monday ("Pondelok").
=> fix(date): start Slovak calendar week on Monday, not Sunday

src/components/calcite-input/calcite-input.stories.ts, src/components/calcite-label/calcite-label.e2e.ts, src/components/calcite-label/calcite-label.scss, src/components/calcite-label/calcite-label.tsx
**Related Issue:** #1296 
When contained in a center-aligned container, labels are now left (or right in rtl) aligned. Also adds the ability to center-align the label text using the new prop.
=> fix(label): enforce directionality with new alignment prop

src/components/calcite-rating/calcite-rating.e2e.ts, src/components/calcite-rating/calcite-rating.tsx
**Related Issue:** #1294 
When a rating exists, clicking on a wrapping calcite-label will focus the last selected rating item, otherwise it will focus the first rating item.
=> fix(rating): clicking on a wrapping calcite-label focuses a rating item

src/components/calcite-fab/calcite-fab.e2e.ts, src/components/calcite-fab/calcite-fab.tsx
fix(fab)!: default scale property to medium (m). #1427
=> fix(fab)!: default scale property to medium (m). #1427

src/components/calcite-select/calcite-select.tsx
**Related Issue:** #1409 
This fixes an incorrect assumption made by the code where the mutation observer callback that updates the internal select would always fire **after** initial render and the ref to the internal select is set. This seems to happen when the component is used inside another VDOM engine (Ember, React, maquette).
I wasn't sure how to repro this error purely w/ the Stencil test tooling, so I created the following codepen that shows the issue: https://codepen.io/jcfranco-the-scripter/pen/poEVyxj?editors=0010. It uses maquette and you can see an exception in the console shortly after it loads and renders.
=> fix(select): handle case where mutation observer fires before internal select is stored

src/components/calcite-radio-button/calcite-radio-button.tsx
I've been running into occasional errors when using the calcite-radio-button in React using beta.47. The internal input sometimes has been removed from the page before the formResetHandler runs, causing an error trying to call `setAttribute` on a non-existent input.
This is a defensive fix and may not be the best way to address it, but its easy and shouldn't introduce any other issues.
=> fix(radio-button): Add check for existing input before setting attribute

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx, src/components/calcite-color/utils.ts
Stems from https://github.com/Esri/calcite-components/issues/917#issuecomment-749238586. 
This will allow users to explicitly set the color format used by `value`. This is automatically inferred from `value` by default and preserved during color updates until a new value w/ different format is provided.
cc @pemberdom
```ts
interface CalciteColor {
format: "auto" | "hex" | "rgb-css" | "hsl-css" | "rgb" | "hsl" | "hsv";
}
```
Are the following format names OK? They are currently the previously internal values. Is there an official name to distinguish a color object vs CSS value (e.g., RGB object vs RGB CSS string)?
* `hex`(string)
* `rgb-css`(string)
* `hsl-css`(string)
* `rgb`(object)
* `hsl`(object)
* `hsv`(object)
=> feat(color): allow setting color value format

.storybook/main.ts, package-lock.json, package.json
Sets up https://www.npmjs.com/package/@whitespace/storybook-addon-html to include an HTML-preview tab (next to `Knobs` and `Accessibility`). This would allow users to copy/paste component markup after customizing a story.
=> docs(storybook): add html preview tab

src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** #1412
The fix here is to avoid `flex: inherit` as mobile safari apparently can't handle that. 
I've also updated all the styles to use tailwind as I think the rule is "if you're in there, convert it"
=> fix(modal): fix styling on mobile safari (#1412), use tailwind

package-lock.json, package.json
Per [Stencil documentation](https://stenciljs.com/docs/custom-elements#distributing-custom-elements#:~:text=@stencil/core), this moves `@stencil/core` as a dependency for the `dist-custom-elements-bundle` output target. This will be useful for consumers that want to use a tree-shakeable bundle.
=> build: move @stencil/core as a dependency for custom-elements output

src/components/calcite-input-message/calcite-input-message.e2e.ts, src/components/calcite-input-message/calcite-input-message.tsx, src/components/calcite-input-message/interfaces.ts, src/components/calcite-input/calcite-input.stories.ts, src/demos/calcite-input.html
**Related Issue:** #1330 
Allows a custom icon to be passed, in addition to the status-based defaults.
=> feat(input-message): allow custom icons

src/components/calcite-combobox-item/calcite-combobox-item.scss, src/components/calcite-combobox-item/calcite-combobox-item.tsx, src/components/calcite-combobox-item/resources.ts, src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.stories.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-combobox/interfaces.ts, src/demos/calcite-combobox.html
Adds the ability to select only one item in a combobox at a time. This allows creating nested, single-select workflows from a hierarchy or a flat list:
It's a common use case whenever there is a 1to1 relationship (ex. what family/genus/species/ is this animal in? what region/department  is this employee in? etc). This could also be used in lieu of a datalist (#1143) as it provides a search field with filtered options. Possibly could be used in the use case from #925 as well (known list, with search, allow selection).
Specific need from team is for a folder-selection UI. So I've included examples for that as well.
=> feat(combobox): single select mode

src/components/calcite-rating/calcite-rating.e2e.ts, src/components/calcite-rating/calcite-rating.stories.ts, src/components/calcite-rating/calcite-rating.tsx, src/components/calcite-rating/readme.md, src/demos/calcite-rating.html
We need the ability to hide the value of the count/average numbers. I went to add a prop for this and realized it was already there, we just weren't using it 🤦🏻 .
This updates the ratings component to pay attention to the existing `display-value` prop and adds tests, docs, jsdoc for it as well.
=> fix(rating)!: display-value => show-chip, also works now

src/components/calcite-date-picker-day/calcite-date-picker-day.scss, src/components/calcite-date-picker/calcite-date-picker.scss, src/demos/calcite-input-date-picker.html
Several style issues from the date refactor. The demos were all `active` on page load which was causing issues, so removed that as well.
Also replaced a CSS variable that's no longer there (I think it was removed after the style/tailwind refactor?). We will need a more permanent solution as this color will not automatically change if a dev uses a custom theme color for `brand`. We can do that in a follow up pr. This at least gets it working again.
=> fix(date-picker, input-date-picker): fix missing range color, update demos

package-lock.json, package.json
**Related Issue:** #1479
This moves runtime deps installed as devDependencies as dependencies. This would cause other Stencil builds to fail as they couldn't resolve the dependencies and would force users to install these themselves.
cc @subgan82
=> fix(deps): move runtime deps to dependencies

src/components/calcite-date-picker/calcite-date-picker.e2e.ts, src/components/calcite-date-picker/calcite-date-picker.tsx, src/demos/calcite-date-picker.html
**Related Issue:** #1484
We were emitting an a range change event in the date anytime the start or end changed. On the surface this makes sense, but in react/preact/vue this can cause really unpredictable bugs. Consider the following fake react code:
```jsx
<calcite-date-picker range start={state.start} end={state.end} onCalciteDateRangeChange={this.setStartEnd} />
```
When the component is controlled like this, you could cause a render loop because:
```txt
your event handler updates state 
⇗                                ⇘
prop change fires event handler           ⟸            state updates props
```
Events should only be fired on changes that happen from user interaction, not prop changes ("props down events up").
=> fix(date-picker): Don't emit range change events on outside prop edits (#1484)

src/components/calcite-shell/calcite-shell.scss
**Related Issue:** #1502
Remove padding in the calcite-shell footer slot
=> fix(calcite-shell): Remove padding in the calcite-shell footer slot

src/components/calcite-radio-button/calcite-radio-button.e2e.ts
This test was erring out locally for me. I believe this is just do to the selector being incorrect. Adding an additional piercing selector seems to make the tests happy enough. We'll see how travis feels about it.
=> test(radio-button): fix shadow root test selector

conventions/README.md, src/components/calcite-pagination/calcite-pagination.e2e.ts, src/components/calcite-pagination/calcite-pagination.tsx, src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #1145
For consistency, this deprecates `<*Update>` events in favor of `<*Change>` ones.
=> chore(input, slider): add change events and deprecate update ones

conventions/README.md, src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** #1145
Adds `setFocus` method on modal for consistency:
```ts
interface CalciteModal {
setFocus(focusId?: "close-button"): Promise<void>;
}
```
Additionally, deprecates `focusElement(el?: HTMLElement): Promise<void>`.
=> feat(modal): add setFocus method and deprecate focusElement

package-lock.json, package.json, src/components/calcite-tile-select/calcite-tile-select.stories.ts, src/components/calcite-tile/calcite-tile.stories.ts
We were five versions behind on the icons library.
=> chore: bump calcite-ui-icons to latest

src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
While the events for date change were firing (due to propagation from the underlying date-picker component, they were not included in the generated doc or generated preact types. Adding them to the input so that they are documented.
=> fix(input-date-picker): document events emitted by input date picker

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
When using the combobox inside a shadow dom, clicking the element to open it was bubbling up, causing the `setInactiveIfNotContained` method to run and immediately close it. 
I'm not entirely sure why this problem exists only in shadow dom (maybe document is different, or `el.contains` no longer functions correctly). The fix is to just stop that event from bubbling up to the document (it should have been like this anyways, more efficient). 
I've heard this happens on select menus as well, so I'll look into it next.
@eriklharper thanks for the shadow root test you wrote for radio button, it really helped me know how to test this!
=> fix(combobox): solve issue with using combobox inside shadow DOM

src/components/calcite-avatar/calcite-avatar.tsx, src/components/calcite-label/calcite-label.tsx
**Related Issue:** #637
https://github.com/Esri/calcite-components/pull/954 removed all prop validation checks. This takes care of some remaining ones.
=> chore(avatar, label): drop lingering prop validation checks

src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.tsx, src/components/calcite-date-picker/calcite-date-picker.e2e.ts
**Related Issue:** #1546
next/prev were flipped for some reason (maybe after refactor?)
=> fix(date-picker): correct swapped next/prev in header (#1546)

src/components/calcite-shell-panel/calcite-shell-panel.tsx, src/components/calcite-shell-panel/resources.ts
**Related Issue:** #1540 
This simply adds a named slot for anything at the top of the content area: `<slot name="header" />`
The named slot is not added if it's empty.
cc @kevindoshier 
The dark thing at the top there is using its own "hand-rolled" styles.
For content in the default slot, scrolling appears to be unaffected by content in the `header` slot.
Also, a flow in the default slot will operate as normal.
@driskull I think we should make a Header component or something that can be reused.
There are some pretty similar blocks of code in Block and Panel, and a Header component would work nicely in this slot.
=> feat(shell-panel): adds slot for header content

src/assets/styles/global.scss
Currently the global CSS file has an `@apply` rule in it. Stencil is _supposed_ to run your global css through the same plugins as your component css, but for some reason it's leaving it. This is causing problems for people who are using the CSS file over the wire (causing errors as `@apply` is not natively supported). 
For now I'm removing it. Until we work with the stencil devs to fix this we should avoid using `@apply` in the global section.
=> fix: stop @apply rule from getting into dist CSS

src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.tsx, src/demos/calcite-radio-button.html
=> fix(calcite-radio-button): document-level "!important" style overrides applied to hidden input no longer take effect

src/components/calcite-button/calcite-button.scss
**Related Issue:** #1562 
Especially when using `icon-start-space-between` or `icon-end-space-between`, wrapped text would reveal itself to be centered causing weird looking layout.
This fixes that.
Before
After
=> fix(button): fixes missing text-alignment for alignment prop.

src/components/calcite-shell-center-row/calcite-shell-center-row.scss
**Related Issue:** #1554
Removes CSS transition for height.
While it's nice to have, the transition can cause rendering issues with the "micro apps" it contains.
=> feat(shell-center-row): remove CSS transition for height

.github/PULL_REQUEST_TEMPLATE.md, src/components/calcite-input/calcite-input.tsx
Allow `maxlength` property to be set on a `calcite-input` item
=> feat: add maxlength property to calcite-input

src/components/calcite-color/calcite-color.e2e.ts
This hides the many (expected) 'invalid color' messages shown during a local test run.
=> chore: hide invalid color warnings shown during test

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.tsx
Inside a container with scroll, the hidden list items are actually taking up room and forcing a scroll of the container even when closed. This sets the items to display none when the combobox is closed so no overscroll is forced
.
Example code to repro:
```html
<div style="overflow: auto">
<calcite-combobox>
...items, etc
</calcite-combobox>
</div>
```
=> fix(combobox): prevent hidden options from causing scroll

support/deployNextFromTravisBuild.sh
This updates the `@next` deployment script to bail if there is a newer commit that will end up being deployed. This should mitigate a scenario where `@next` releases would halt when multiple deployable PRs are installed consecutively. Basically, the builds from later PRs would be missing commits installed by the `@next` deployment scripts of earlier Travis runs.
cc @subgan82 @asangma
=> ci: prevent deployment if outdated

src/components/calcite-checkbox/calcite-checkbox.e2e.ts, src/components/calcite-checkbox/calcite-checkbox.tsx, src/components/calcite-radio-button/calcite-radio-button.e2e.ts, src/components/calcite-radio-button/calcite-radio-button.tsx
**Related Issue:** #808
Adds `setFocus` to checkbox and radio button components.
=> feat(checkbox, radio-button): add setFocus()

src/components/calcite-avatar/calcite-avatar.stories.ts, src/components/calcite-block/calcite-block.stories.ts, src/components/calcite-card/calcite-card.stories.ts, src/components/calcite-chip/calcite-chip.stories.ts, src/components/calcite-shell/calcite-shell.stories.ts, src/components/calcite-tip-manager/calcite-tip-manager.stories.ts, src/components/calcite-tip/calcite-tip.stories.ts
**Related Issue:** #1584 
This pr replaces network calls to fetch images in avatar, block, card, chip, shell, and tip-manager stories with the new svg placeholder utility.
=> chore(avatar, block, card, chip, shell, tip-manager): use svg placeholder in stories

support/deployNextFromTravisBuild.sh
https://github.com/Esri/calcite-components/pull/1593/ made some updates to prevent deploying an outdated build. This fixes a bug where the current commit was not excluded from the outdated deployable check. 
This also deletes a local test file that snuck in from ☝️ .
=> ci: check for latest deployable installs after current commit

src/components/calcite-input/calcite-input.tsx
Did not open issue - can make one if needed
Setting the properties in the title in componentDidLoad() can cause the attributes not to be applied to the input in the shadow dom at initial render. Looks like this:
In the screen shot, step, min, and max are missing. When the value of the input is changed, the attributes then show up because the component re-renders.
Moving these assignments to componentWillLoad() guarantees they will be assigned at render time.
Also saw a typo in the watch method, it should keep the stepString and step properties in sync, not assign max again. If there is a specific reason for that, let me know 😄 
cc: @driskull @macandcheese
=> refactor(input): move assigning stepString, minString, maxString props to before component is rendered

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx
**Related Issue:** #1468 
This fixes an issue where the default value would get rejected and not converted to the initial format.
**Note**: this will not emit an event as it's considered the initial value and therefore not changed.
=> fix(color): convert default value based on initial format

src/components/calcite-checkbox/calcite-checkbox.stories.ts, src/components/calcite-checkbox/calcite-checkbox.tsx
=> fix(calcite-checkbox): fixing focus outline styling weirdness on Safari

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
**Related Issue:** #1585
New `calciteComboboxFilterChange` event when user filters the combobox list. Detail passed to the event will have the following type:
```ts
{
visibleItems: HTMLCalciteComboboxItemElement[];
text: string;
}
```
=> feat(combobox): fire event when combobox list is filtered (#1585)

src/components/calcite-alert/calcite-alert.e2e.ts
Created issue to restore when the test is stable: https://github.com/Esri/calcite-components/issues/1608
=> test(alert): skip unstable test

src/components/calcite-color/calcite-color.e2e.ts, src/components/calcite-color/calcite-color.tsx
**Related Issue:** #1474 
This fixes an issue where the hue slider would not work if the selected color would produce the same RGB value after modifying the hue.
=> fix(color): ensure hue slider always updates internal color regardless of value being equal

.github/ISSUE_TEMPLATE/unstable-test.md, .github/PULL_REQUEST_TEMPLATE.md, conventions/README.md
Adds convention to help track and fix unstable tests.
=> chore(tests): add convention for skipping unstable tests with issue template

src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.e2e.ts, src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx, src/components/calcite-color-picker-hex-input/readme.md, src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx, src/components/calcite-color-picker/readme.md
**Related Issue:** #1437 
This renames the following events that were missing from https://github.com/Esri/calcite-components/pull/1613:
* `calciteColorChange` -> `calciteColorPickerChange`
* `calciteColorHexInputChange` -> `calciteColorPickerHexInputChange` (internal)
=> refactor(color)!: rename color to color-picker

src/components/calcite-modal/calcite-modal.e2e.ts
https://travis-ci.org/github/Esri/calcite-components/builds/760523989
```
FAIL src/components/calcite-modal/calcite-modal.e2e.ts (32.825 s)
● calcite-modal accessibility checks › setFocus › can focus close button directly
expect(received).toBe(expected) // Object.is equality
Expected: true
Received: false
165 |   }
166 | 
> 167 |   expect(await page.evaluate((selector) => document.activeElement.matches(selector), focusTargetSelector)).toBe(true);
|                                                                                                            ^
168 | }
169 | 
at Object.focusable (src/tests/commonTests.ts:167:108)
at runMicrotasks (<anonymous>)
```
=> test(modal): skip unstable test

.github/ISSUE_TEMPLATE/unstable-test.md, .github/PULL_REQUEST_TEMPLATE.md
Minor tweaks to the unstable test templates. Mainly drops the Travis build URL since it may point to a successful one if the build is run again and is successful.
=> chore(tests): update unstable-test templates

src/components/calcite-notice/calcite-notice.tsx
**Related Issue:** #744
Showing/hiding the notice is now controlled exclusively via the `active` prop. This brings the component closer to how other components like modal work.
=> fix(notice)!: remove open and close methods

tailwind.config.js
Supports #1500 
This changeset adds a set of convenience utilities for text that wraps.  These utilities combine `text-*` + `leading-*` e.g. `text-2-snug` is equivalent to `text-2 leading-snug`.**
=> feat(tailwind): add percentage based text utils for "text that wraps"

src/components/calcite-loader/calcite-loader.scss, src/components/calcite-modal/calcite-modal.scss
Use more tailwind for modal and loader.
Modal was pretty well converted already. There are some awkward moments with border, something we should figure out. 
The largest change in loader was that the medium scale loader didn't fall on the spacing scale. It was previously (and in figma) `54px`. This is between spacing `12` (48px)  and spacing `16` (64px). I've adjusted the medium scale to be spacing 12 as this makes the sizes `8 => 12 => 20` which seems very rational.
=> refactor(loader, modal): use tailwind on loader and modal

tailwind.config.js
**Related Issue:** #1500, https://github.com/Esri/calcite-components/pull/1640
Renames the existing `-snug` and `-tight` text size utils as `-wrap`. This should help remove some guess work in the naming.
=> refactor(tailwind): rename text-N-wrap utils

src/components/calcite-radio-group/calcite-radio-group.scss
#supports #1701 #1500 
@bstifle, I used the border input color for these, figma didn't have them, but we want to match inputs?
Please advice, I can always revert.
=> refactor(radio-group): tailwindify

src/components/calcite-shell-center-row/calcite-shell-center-row.scss, src/components/calcite-shell/calcite-shell.e2e.ts, src/components/calcite-shell/calcite-shell.scss, src/components/calcite-shell/calcite-shell.tsx, src/components/calcite-shell/readme.md
**Related Issue:** (#1637)
Updates Shell and CenterRow to fix layout bug when Shell did not have `content-behind`.
@driskull Let me know if the conditionals on the node layout is overly complex.
=> fix(shell): content layout when not content-behind

src/components/calcite-combobox-item/calcite-combobox-item.tsx, src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.stories.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-combobox/interfaces.ts, src/components/calcite-combobox/utils.ts, src/demos/calcite-combobox.html
**Related Issue:** #1590
This adds a new selection mode for selecting in a hierarchical set where selection of a child infers selection of a parent. We need this to cover the content categories UI. I've used `selectionMode` to retain consistency with Tree which is the most obviously similar component in our system. 
Selected elements in this mode show their hierarchy in the chip as well:
=> feat(combobox): add ancestor selection mode (#1590)

src/components/calcite-tab/calcite-tab.scss
Refactors calcite-tab to use the Tailwind config.
=> refactor(tab): use tailwind

src/components/calcite-block/calcite-block.e2e.ts, src/components/calcite-block/calcite-block.tsx, src/components/calcite-block/resources.ts, src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.tsx, src/components/calcite-date-picker/calcite-date-picker.e2e.ts, src/components/calcite-date-picker/calcite-date-picker.tsx, src/components/calcite-date-picker/resources.ts, src/components/calcite-input-date-picker/calcite-input-date-picker.tsx, src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-panel/calcite-panel.tsx, src/components/calcite-panel/resources.ts, src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts, src/components/calcite-pick-list-group/calcite-pick-list-group.tsx, src/components/calcite-pick-list-group/resources.ts, src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts, src/components/calcite-tip-manager/calcite-tip-manager.tsx, src/components/calcite-tip-manager/resources.ts, src/components/calcite-tip/calcite-tip.e2e.ts, src/components/calcite-tip/calcite-tip.tsx, src/components/calcite-tip/resources.ts, src/components/functional/CalciteHeading.spec.tsx, src/components/functional/CalciteHeading.tsx, src/components/functional/HeadingWizard.tsx
**Related Issue:** https://github.com/Esri/calcite-components/issues/1531
feat(block, panel, pick-list-group, tip, tip-manager): Add 'headingLevel' property to specify a number at which section headings should start for the component.
- Adds a `headingLevel` prop to any components that use a `h1`-`h6`.
- Uses `headingLevel` prop and a functional component to return the correct heading level
- Allows a user to change the level for headings within a component for accessibility and semantics.
- ~~@asangma we will need to set sizing for all the heading classes so that changing the level does not change the size of the heading.~~ We can tackle these as the arise or we can create an issue.
- ~~If naming is approved, I will create tests.~~ done
=>  feat(block, panel, pick-list-group, tip, tip-manager): Add 'headingLevel' property

src/components/calcite-input-date-picker/calcite-input-date-picker.scss
**Related Issue:** #1689 
Removes max-widths.
=> fix(input-date-picker): removes max-widths

src/components/calcite-filter/calcite-filter.e2e.ts, src/components/calcite-filter/calcite-filter.tsx, src/components/calcite-pick-list/shared-list-logic.ts, src/components/calcite-pick-list/shared-list-tests.ts
**Related Issue:** #1527 
Fixes an issue where items after filtering would not be keyboard-navigable (unless result includes selected item).
cc @AdelheidF
=> fix(pick-list, value-list): fix keyboard navigation after filtering

src/components/calcite-tabs/calcite-tabs.scss
Refactor calcite-tabs to use the Tailwind config - Depends on pr #1669 for border-side-style utilities.
=> refactor(tabs): use tailwind

src/components/calcite-radio/calcite-radio.scss
Supports #1694 #1500
Medium: code and design have 14px, however, tailwind doesn't have this vlaue. Tailwind 2.0 does have it, maybe a reason to update? @jrowlingson 
Large: code has 20px, design has 18px (which is not a tailwind value). Used 20px for now.
^^ @bstifle
=> refactor(radio): tailwindify

src/components/calcite-input/calcite-input.tsx, src/components/calcite-label/calcite-label.tsx, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx
fix(input, label): Removing disabled prop should also updated slotted elements.
- If you add a disabled prop to an input or label, it adds disabled to the slotted input.
- However, if you then remove that disabled prop, it does nothing.
- I think it should update it.
=> fix(input, label): Removing disabled prop should also updated slotted elements.

src/components/calcite-shell/calcite-shell.tsx, src/demos/shell/demo-app-advanced-center-row-async.html
Also adds async test demo
* Simpler render
* removes conditional render of center-row slot
cc @kevindoshier
=> fix(shell): simplifies content render removes center-row conditional

src/components/calcite-filter/calcite-filter.e2e.ts, src/components/calcite-filter/calcite-filter.tsx
Allows the filter text term to be cleared by pressing the Escape key.
=> feat(filter): clear text on Escape

CODEOWNERS
Updates codeowners file to use reviewer group as catch-all.
Do we want to also set up granular ownership? Something like this would work:
```
calcite-block/                    @jcfranco
calcite-block-section/            @jcfranco
calcite-color-picker/             @jcfranco
calcite-color-picker-hex-input/   @jcfranco
calcite-color-picker-swatch/      @jcfranco
calcite-icon/                     @jcfranco
calcite-option/                   @jcfranco
calcite-option-group/             @jcfranco
calcite-pick-list/                @jcfranco
calcite-select/                   @jcfranco
calcite-value-list/               @jcfranco
```
Anything not specified above would be owned by the reviewers group (see [codeowners syntax](https://docs.github.com/en/github/creating-cloning-and- …
=> chore: fine-tune codeowners

.storybook/manager.ts, package-lock.json, package.json
This sets up an 'addon extension' to https://www.npmjs.com/package/@whitespace/storybook-addon-html to intercept our storybook HTML preview content and hide global, internal attributes that may affect component rendering when copying/pasting code.
=> docs(storybook): prevent internal attributes from being rendered in HTML preview

src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.e2e.ts, src/components/calcite-tree/calcite-tree.stories.ts, src/components/calcite-tree/calcite-tree.tsx, src/components/calcite-tree/interfaces.ts, src/demos/calcite-tree.html
We have several UI's which are hierarchical structures where every level can be selected. Here are some examples:
I've added this functionality as a mode to the Tree component. `selection-mode="ancestors"` will select all children  of an object when select, and deselect all children when deselected. This selection mode is very similar to the `ancestors` selection mode that is now available in `combobox`.
I've also added a `checkboxes` prop. This works much like `lines`. It's a more form-like way to render tree options for selecting, rather than just navigating. When you have checkboxes and you're in ancestors selection mode, the tree will manage setting indeterminate states for you as well.
I've added a tests for the selection mode. I didn't convert `tree` to tailwind or write tests for …
=> feat(tree): add ancestor selection mode, input-enabled prop for selectable trees

src/components/calcite-combobox-item/calcite-combobox-item.tsx, src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/demos/calcite-combobox.html, src/utils/filter.ts
This allows devs to keep certain combobox items visible even when filtering. The use case here is some sort of "new" option:
However, this could also be used to put together an async combobox UI. Imagine you want to have a selection UI for members, but you have to hit a paginated API. You could use the filter event from the box, hit the API, and render the results. If you use this prop on all of them, you'll be able to show them even though text is entered. Basically it allows devs to take care of list filtering themselves if they want to as an opt-in.
I haven't added a storybook entry for this. The combobox storybook needs a rewrite to work more like accordions where there are multiple pages of knobs that are grouped for combobox, combobox-item.
=> feat(combobox): add constant prop to combobox item

src/components/calcite-shell-panel/calcite-shell-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.tsx, src/components/calcite-shell-panel/resources.ts, src/demos/shell/block-configurations.html
**Related Issue:** # (#1750)
This PR lets a component in ShellPanel's default slot more accurately get the height of its container.
The issues from #1750 appear to be happening because a component in ShellPanel's default slot will read the height of the entire `.content` div. So if there's a header, the calculated value on `height: 100%` is no longer any good.
Note that unless a Flow or Panel is placed directly into the default slot, e.g. anything else like a div or an outside component, it will still need to set `height: 100%` on itself and probably any Panel inside it.
cc @AdelheidF @kevindoshier
=> fix(shell-panel): adds divs to provide accurate height calculations for slotted content

src/components/calcite-panel/calcite-panel.scss, src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-popover/readme.md, src/demos/shell/block-configurations.html
**Related Issue:** #1752
Includes some clean-up on Popover as discussed previously with @julio8a .
Also updates demo app for better demo apping.
=> fix(popover, panel)!: image slot removed and sizing styles updated

src/components/calcite-color-picker-swatch/calcite-color-picker-swatch.scss
Supports #1500 
The large size changed from what originally used. use to be 28px jumped to 32px from the spacing scale. 
before:
S = 20px
M = 24px
L = 28px
Now:
S = 20px (5)
M = 24px (6)
L = 32px (8)
=> refactor(color-picker-swatch): tailwindify

src/components/calcite-select/calcite-select.scss, src/components/calcite-shell-panel/calcite-shell-panel.scss, src/components/calcite-tabs/calcite-tabs.scss, tailwind.config.js
Removes the 3px border width and border-side-style utility additions introduced in pr #1669 from our Tailwind config. Also removes usage of the border-side-style utility in calcite-tabs and calcite-shell-panel .scss files.
Why?
We don't want to provide 3px border widths in the theme (some border widths - like calcite-notice and calcite-tab-title -  decreased from 3px to 2px in the refactor work, and that's intended).
Additionally, when tailwind base is incorporated down the road, @jrowlingson let me know that the border-side-style utility won't be needed. (As a note, when I looked at this last Friday with Jack, my refactor of calcite-tab-title needed the border-side-style explicitly set for its gray hover effect, which was the reason I had added the utility. …
=> refactor(tailwind, tabs, shell-panel): reverts 3px border width, border-side-style utility, usage

src/components/calcite-tab-nav/calcite-tab-nav.scss
Refactors tab-nav styles to use the tailwind config. Changes the 3px active tab indicator height to 2px (to match new calcite-tab-title 2px border width).
** I'm thinking this one should be merged right after pr #1745 - Screener tests are going to fail on this one until the new calcite-tab-title styles are accepted.
=> refactor(tab-nav): use tailwind

src/components/calcite-tab-title/calcite-tab-title.scss
Refactors tab-title styles to use the tailwind config. Changes 3px border widths to 2px (match calcite-notice).
=> refactor(tab-title): use tailwind

src/components/calcite-shell-center-row/calcite-shell-center-row.scss
=> fix(center-row): update style to use updated tailwind reference

src/components/calcite-panel/calcite-panel.scss, src/components/calcite-panel/calcite-panel.tsx
**Related Issue:** (#1822)
Alternatively, I could add conditional styles for there not being a header, but this seemed cleaner.
=> fix(panel): retain header node even without content to retain action position

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input.html
**Related Issue:** #936
Fixes bug in input where decimal precision got all wonky if you clicked the input a whole bunch of times. I think this bug is due to javascript being... bad at math. Setting a fixed decimal length which is the same as the current value solves the issue.
=> fix(input): solve bug with decimal precision in number input (#936)

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
This adds `minLength`/`maxLength` props to `<calcite-input>` and deprecates `minlength` because it does not follow prop casing.
=> feat(input): add minLength/maxLength props

src/components/calcite-modal/calcite-modal.stories.ts
Uses attribute value to unset the color attribute. Stories use attributes instead of props, so `null` would get stringified when rendered:
```html
<calcite-modal
active=""
color="null"
background-color="white"
scale="m"
width="s"
intl-close="Close"
>/*...*/</calcite-modal>
```
=> docs(modal): fix 'none' option values for modal color attribute

src/components/calcite-panel/calcite-panel.scss
**Related Issue:** #1822
Updates styles to actually fix the layout issue.
Actions should all be in the right place whether or not header-content is rendered.
cc @subgan82
=> fix(panel): header-actions--end layout fix when header-content is not rendered

src/components/calcite-tip/calcite-tip.e2e.ts, src/components/calcite-tip/calcite-tip.scss, src/components/calcite-tip/calcite-tip.tsx
fix(tip): Hide tip when dismissed.
Currently, closing the tip still shows the close button and border.
https://esri.github.io/calcite-components/?path=/story/components-app-tip--basic
=> fix(tip): Hide tip when dismissed.

src/components/calcite-action/calcite-action.scss
Resets line-height back to pre-refactor.
Update was causing descenders to get clipped.
cc @driskull 
Fixes this.
=> fix(action): reset line-height

src/components/calcite-filter/calcite-filter.e2e.ts, src/components/calcite-filter/calcite-filter.tsx
**Related Issue:** #1527
This addresses lost focus for anyone clearing the filter text by clicking the clear button.
cc @AdelheidF
=> fix(filter): keep focus on filter after clearing text via mouse

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
This brings `<calcite-input>` closer to `<input>` by only emitting events on user interaction. 
This also helps w/ VDOM integrations where value comes from a state model and is set on the input and not from interaction, so no need to emit in that case. Otherwise, you get two events fired.
cc @AdelheidF
=> fix(input): only emit input event on user interaction

src/components/calcite-tile-select-group/calcite-tile-select-group.stories.ts
**Related Issue:** # n/a
I noticed Storybook's showing a blank page for tile-select-group's docs, so I've added it in here.
=> chore(tile-select-group): update story to make sure docs visible

src/assets/styles/global.scss, src/components/calcite-panel/calcite-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.scss
**Related Issue:** #1849
This adds a base width unit at the :root level that is then used when calculating the width, min-width, and max-width for Panel and ShellPanel at each scale.
It should not affect the UI or any existing usages of Shell and ShellPanel.
The `width-scale` property should still behave as it has been on both components.
=> feat(panel, shell-panel): add width base unit at root level

src/components/calcite-select/calcite-select.tsx
**Related Issue:** #1836
Updates `calcite-select` to use `innerText` for its internal `<option>`s to display properly in mobile (see https://stackoverflow.com/questions/35021620/ios-safari-not-showing-all-options-for-select-menu/41749701).
Note that there are no accompanying tests since I'm not sure how we can automatically test for this in our E2E setup.
=> fix(select): fix rendering of options for mobile

src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.e2e.ts, src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx, src/components/calcite-color-picker/utils.ts
This tweaks up the input processing logic to prevent users from entering invalid characters when the the input has a selection.
=> fix(color-picker): prevent invalid chars from being entered when hex input text is selected

src/components/calcite-option/calcite-option.e2e.ts, src/components/calcite-option/calcite-option.tsx
**Related Issue:** #1409 
This tweaks the mutation observer options to actually track when its text content changes. `characterData` was not working because of the node being observed was not a text node. Dropped `subtree` since option is not expected to have a subtree as content.
=> fix(option): fix mutation observer options used to track content changes

src/assets/styles/global.scss, src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-panel/calcite-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts, src/components/calcite-shell-panel/calcite-shell-panel.scss
Remove "ui" from var name.
cc @kevindoshier
=> refactor(panel, shell-panel): rename CSS var to remove -ui- and add testing

src/utils/dom.ts
Updates dom util getElementDir to go beyond shadow dom.
**Related Issue:** #1826
fix(input-date-picker): Menu position should change depending on dir.
Updates dom util getElementDir to go beyond shadow dom.
=> fix(input-date-picker): Menu position should change depending on dir.

src/components/calcite-combobox/calcite-combobox.tsx
fix(combobox): Update scrollable menu height for 'maxItems' when maxItems or active changes.
=> fix(combobox): Update scrollable menu height for 'maxItems' 

src/assets/styles/_popper.scss, src/components/calcite-card/calcite-card.stories.ts, src/components/calcite-popover/calcite-popover.scss, src/components/calcite-tooltip/calcite-tooltip.scss, src/demos/_assets/toggleBodyTheme.ts, src/demos/calcite-card.html, src/demos/calcite-link.html, src/demos/calcite-popover.html, src/demos/calcite-tooltip.html
This pr aims to fix a few style issues with `calcite-tooltip`'s Tailwind refactors (pr #1738, pr #1765).
The goal here is to a). ensure the tooltip tail doesn't appear **over** the content area, and b). ensure the tooltip's new border styles are visible.
I also noticed the tooltip wasn't working in a few places (card stories, card/link demo html), so I tried to fix those as well.
=> fix(tooltip): improve tooltip border, tooltip usage in card story, card/link demo html

conventions/README.md
docs: Update conventions for RTL support.
Updates text to say we can set `dir` attribute on shadowed elements but not light dom or host.
Using a utility class is preferred if possible.
=> docs: Update conventions for RTL support.

src/components/calcite-action-bar/calcite-action-bar.e2e.ts, src/components/calcite-action-bar/calcite-action-bar.tsx, src/components/calcite-action-group/calcite-action-group.tsx
fix(action-bar): Only allow one overflow menu open at a time.
=> fix(action-bar): Only allow one overflow menu open at a time.

src/components/calcite-color-picker-swatch/calcite-color-picker-swatch.tsx, src/components/calcite-color-picker-swatch/resources.ts
**Related Issue:** #1886 
Updates swatch borders to be spec-compliant.
**light theme**
**dark theme**
cc @julio8a
=> fix(color-picker): update color swatch border to follow spec

src/components/calcite-radio-group/calcite-radio-group.scss, src/demos/calcite-radio-group.html
**Related Issue:** n/a - relates to Tailwind refactor from pr #1711, issue #1500
cc @julio8a @bstifle 
Ensures the gray outline around `calcite-radio-group` stays inside the new total heights for each scale. Also freshens up its demo html a bit.
=> fix(radio-group): ensure group's outline is included in new total heights

src/components/calcite-action-group/resources.ts, src/components/calcite-card/calcite-card.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.scss, src/components/calcite-color-picker/calcite-color-picker.tsx, src/components/calcite-color-picker/resources.ts
**Related Issue:** #1406
I kept getting issues assigned to me about lacking keyboard support in this component, so thought I'd just take a crack at it. I've chosen to model this as multiple `slider` components in terms of accessibility. Because multi-axis sliders are not supported via the `slider` role, when you are moving in the vertical direction, we treat this as a 0-100 value slider, while when you're moving horizontally we treat it as a 0-100 saturation slider.
=> fix(color-picker): add keyboard support to color field and hue slider

src/components/calcite-select/calcite-select.scss
Fixes RTL styles (probably a regression from tailwindification™).
**before**
**after**
=> fix(select): fix RTL styling

src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-panel/calcite-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.scss
**Related Issue:** (#1914)
Adds explicit flex grow, shrink, and basis definitions to make Safari play nice.
cc @AdelheidF 
Also added to Panel at the :host level to ease integration.
=> fix(panel, shell-panel): flex grow, shrink, basis definitions 

src/components/calcite-flow/calcite-flow.scss, src/components/calcite-panel/calcite-panel.scss, src/components/calcite-shell-panel/calcite-shell-panel.scss
… Safari (#1914)
**Related Issue:** #1914 
Adds additional styles to play nice with Safari.
Custom elements, i.e. other components inside Panel and Flow will still need these styles applied to them:
```
display: flex;
flex: 1 1 auto;
overflow: hidden;
```
cc @AdelheidF @kevindoshier @dhrumil83 @subgan82
If you know Ganesh and Dhrumil's handles, please mention them here.
=> fix(panel, shell-panel, flow): fixes height and scrolling issues with Safari

src/components/calcite-block/calcite-block.e2e.ts, src/components/calcite-block/calcite-block.tsx
**Related Issue:** #1917
Moves aria attribute to the proper toggling element.
=> fix(block): place aria-expanded on block toggle button

src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.e2e.ts, src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx, src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
The color picker was recently updated to use the previous value when there is none and either the hue or saturation/value thumbs are modified via keyboard. This updates the color picker inputs to be consistent with this behavior. 👍🏼 👍🏼
=> feat(color-picker): restore previous value when there is no color and input is nudged

src/components/calcite-action-bar/calcite-action-bar.tsx
…y from working correctly.
**Related Issue:** #1938 #1937
<!--
fix(action-bar): Fix bug preventing 'overflowActionsDisabled' property from working correctly.
=> fix(action-bar): Fix bug preventing 'overflowActionsDisabled' property from working correctly.

src/components/calcite-combobox/calcite-combobox.scss, src/components/calcite-combobox/calcite-combobox.tsx
We were running into issues where at first, a combobox would _always_ open down. Any scrolling or recalculation would make it move to the top (correct), but initially it was wrong. 
Digging in, this is because we were setting the height to `0` as part of https://github.com/Esri/calcite-components/pull/1577
So this pr, we first show the items (giving the menu height), then reposition before showing the menu itself. Also removed the `dir` prop on the host component as I think we're getting rid of those.
=> fix(combobox): open combobox in the correct direction

.storybook/preview-head.html
This PR aims to keep the existing shortcuts outside of component previews by blocking keydown events coming from users interacting with a component.
=> docs(storybook): prevent component story key presses from activating storybook shortcuts

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
This fixes an issue saturation/value cannot be nudged if it would produce the same RGB value. This is reproducible by setting the color picker to 000 and then trying to modify saturation/value with the keyboard.
=> fix(color-picker): fix color field thumb nudging when saturation change does not change the color's RGB value

src/components/calcite-block/calcite-block.e2e.ts, src/components/calcite-block/calcite-block.tsx, src/components/calcite-date-picker/calcite-date-picker.e2e.ts, src/components/calcite-date-picker/calcite-date-picker.tsx, src/components/calcite-panel/calcite-panel.e2e.ts, src/components/calcite-panel/calcite-panel.tsx, src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts, src/components/calcite-pick-list-group/calcite-pick-list-group.tsx, src/components/calcite-pick-list/calcite-pick-list.e2e.ts, src/components/calcite-pick-list/calcite-pick-list.tsx, src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts, src/components/calcite-tip-manager/calcite-tip-manager.tsx, src/components/calcite-tip/calcite-tip.e2e.ts, src/components/calcite-tip/calcite-tip.tsx, src/components/functional/CalciteHeading.spec.tsx, src/components/functional/CalciteHeading.tsx
**Related Issue:** #1710
fix(block, date, panel, pick-list, pick-list-group, tip, tip-manager)!: Remove default 'headingLevel' value. 
Removes the default headingLevel value and child elements will calculate the value relative to their parent components.
=> fix(block, date, panel, pick-list, pick-list-group, tip, tip-manager)!: Remove default 'headingLevel' value.  #1710

src/utils/form.ts
=> fix: fix transform value typo from form style util

src/components/calcite-tile-select-group/calcite-tile-select-group.stories.ts, src/components/calcite-tile-select/calcite-tile-select.scss, src/demos/calcite-tile-select.html
**Related Issue:** #1020
There was a CSS issue when you used `width=full` without an icon and with inputs enabled. Example of broken state:
Notice how in the non-icon example the input alignment is incorrect (should be start) and in the icon example `width=full` is not applying correctly. 
This pr makes the example render correctly. I also added a knob for `width` to satisfy https://github.com/Esri/calcite-components/issues/1020 so devs even know this kind of layout is possible.
@julio8a I can help you update your tile select tailwind pr if this goes in before yours.
=> fix(tile-select): fix full width tile selects with icons, inputs

src/components/calcite-color-picker/calcite-color-picker.tsx, src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input-number.html
**Related Issue:** #1810
This changes `localeFormat` prop to be off by default.
=> refactor(calcite-input): making locale-format false by default

conventions/README.md, stencil.config.ts, support/output-targets/custom-elements/createBundles.ts, tsconfig-node-scripts.json
`createBundles.ts` uses `collection-manifest.json` to generate the util bundles for the custom-elements output target (https://github.com/Esri/calcite-components/pull/1499). This would work for most cases except if a bundle in `stencil.config.ts` had component names where sorting them alphabetically moved the 1st item (the Stencil build sorts them when generating the manifest file).
For example, the following would work fine since the root component will remain first after sorting.
```ts
{
components: [
"calcite-action",
"calcite-action-group",
"calcite-action-menu",
"calcite-action-bar",
"calcite-action-pad"
]
},
```
By contrast, the following would generate a bundle for `calcite-option` and not `calcite-select` (root) after sorting.
```ts
{
components: [ …
```
=> fix(custom-elements): ensure root components get a util bundle generated

src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input-number.html
**Related Issue:** #1983 
@driskull This also fixes console.warn messages from appearing in tests and in the browser when entering number values ending in a decimal.  Numbers in the input that end with a decimal are allowed to be typed, but the stored value doesn't update until another number is typed.  The `calciteInputInput` event also won't emit the value if it ends in a decimal, it waits to emit until a number is added to the right of the decimal.
=> fix(calcite-input): inputInput event now correctly broadcasts the target element's value (event.target.value) to match event.detail.value

src/components/calcite-input/calcite-input.tsx
=>  fix(calcite-input): allowing ctrl+v (and other modifier keys) for pasting numbers on windows machines

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/utils/locale.ts, src/utils/number.spec.ts, src/utils/number.ts
=> fix(calcite-input): setting initial value for number input to "undefined" doesn't display in the input

.travis.yml, support/deployNextFromTravis.sh
**Related Issue:** #1994 
This tweaks the deployment script used by Travis to do a production build instead of reusing a test one, which will lack any configured output targets and extras. 
**Note**: this change will slightly increase the time for a next deployment after tests pass (by ~1 min).
=> ci: ensure next builds are the same as production

src/components/calcite-modal/calcite-modal.e2e.ts, src/components/calcite-modal/calcite-modal.scss, src/components/calcite-modal/calcite-modal.tsx
Working on a design right now where there are actions in the footer in some steps and not in others. The current implementation is not "live". So if you have slotted buttons the footer shows, but when you remove them it still shows the empty footer with border, etc:
This pr adds a `MutationObserver` which checks if you have slotted content in the footer when your dom changes. That way you can flip back and forth between having a footer and not having a footer.
=> fix(modal): render correctly with no footer slots

package.json, support/cleanOnProcessExit.ts, tsconfig.json
**Related Issue:** #2024
This PR will prevent unnecessary files from getting picked up into the dist folder.
=> build: exclude irrelevant dist files

src/components/calcite-modal/calcite-modal.tsx
In production builds, stencil uses `new CSSStyleSheet()` with `shadowRoot.adoptedStyleSheets` to style components usign shadow dom when browsers support it. This actually overrides the `<style>` tag we have in the render function. To get around this I've used the `!important` sledgehammer. I tried to construct a stylesheet and add it to adoptedStyleSheets but there is very little visibility into the stencil build process and the normal host styles were still winning. This at least will consistently solve the issue.
=> fix(modal): solve issue with custom widths in prod builds

src/components/calcite-modal/calcite-modal.tsx
Earlier pr today incorrectly removed slotted content from the footer of modals. This restores it and corrects the footer display with no slotted content. 
I'm not totally sure why screener didn't pick the regression up? Seems like out modal visual testing is probably not very good...
=> fix(modal): restore footer slotted content

src/components/calcite-modal/calcite-modal.scss
=> fix(modal): aleft align back button with title/content of modal

src/components/calcite-action-menu/calcite-action-menu.e2e.ts, src/components/calcite-action-menu/calcite-action-menu.tsx, src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-input-date-picker/calcite-input-date-picker.e2e.ts, src/components/calcite-input-date-picker/calcite-input-date-picker.tsx, src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx, src/utils/popper.ts
**Related Issue:** #2069 #1913
feat(action-menu, combobox, dropdown, input-date-picker, popover, tooltip): Add 'overlayPositioning' property. #2069
Describes the type of positioning to use for the overlaid content. If your element is in a fixed container, use the 'fixed' value.
=> feat(action-menu, combobox, dropdown, input-date-picker, popover, tooltip): Add 'overlayPositioning' property. #2069

src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2071
I couldn't reproduce this locally, but this fix is still something we want to do not just with the `name` attribute, but with all others that we're currently spreading onto the internal input.
=> fix(calcite-input): setting name explicitly on internal input

GETTING_STARTED.md, readme.md
**Related Issue:** #1986
Based on our current [browser support](https://github.com/Esri/calcite-components#browser-support), we should no longer include the `nomodule` script in the doc. 
We can still keep it in our test pages until we no longer need to support it (end of 2021?).
cc @julio8a
=> docs(readme): drop nomodule script snippets

src/components/calcite-select/calcite-select.scss, src/components/calcite-select/calcite-select.tsx, src/utils/dom.ts
fix(select): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(select): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-split-button/calcite-split-button.tsx
fix(split-button): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(split-button): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-stepper/calcite-stepper.tsx
fix(stepper): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(stepper): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-tab-title/calcite-tab-title.tsx
fix(tab-title): Remove setting 'dir' attribute in light DOM elements #1831
=> fix(tab-title): Remove setting 'dir' attribute in light DOM elements #1831

src/components/calcite-tile-select/calcite-tile-select.scss, src/components/calcite-tile-select/calcite-tile-select.tsx
fix(tile-select): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(tile-select): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-pagination/calcite-pagination.tsx
fix(pagination): Remove setting 'dir' attribute in light DOM elements #1831
=> fix(pagination): Remove setting 'dir' attribute in light DOM elements #1831

src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.tsx
fix(date-picker-month-header): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(date-picker-month-header): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-combobox-item/calcite-combobox-item.scss, src/components/calcite-combobox-item/calcite-combobox-item.tsx
fix(combobox-item): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(combobox-item): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-date-picker/calcite-date-picker.tsx
fix(date-picker): Remove setting 'dir' attribute in light DOM elements. #1831
=> fix(date-picker): Remove setting 'dir' attribute in light DOM elements. #1831

src/components/calcite-action/calcite-action.scss, src/components/calcite-block-section/calcite-block-section.scss, src/components/calcite-block-section/calcite-block-section.tsx, src/components/calcite-block-section/resources.ts, src/components/calcite-block/calcite-block.scss, src/components/calcite-block/calcite-block.tsx, src/components/calcite-block/resources.ts, src/components/calcite-handle/calcite-handle.scss, src/components/calcite-panel/calcite-panel.scss, src/demos/shell/popup-config-example.html, tailwind.config.js
**Related Issue:** #1542 
Adds an icon that indicates opened or closed status of the Block.
Only adds the icon if the Block is collapsible.
Also updates the UI of other components to both increase alignment and distinguish functionality.
@mitc7862 @bstifle Could use your UI review as well.
View demos/shell/block-configurations.html to see permutations of the Block header and how it relates to Panel's back button and BlockSection.
cc @AdelheidF
=> feat: adds opened and closed status icon to Block and updates UI of related components

src/components/calcite-filter/calcite-filter.scss
**Related Issue:** #1850
fix(filter): Dark theme colors. #1850
Current:
Fixed:
=> fix(filter): Dark theme colors. #1850

src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-group/resources.ts
fix(dropdown-group): Remove undocumented properties from the Host element. #2059
=> fix(dropdown-group): Remove undocumented properties from the Host element. #2059

.eslintrc.json, src/components/calcite-slider/calcite-slider.tsx, src/components/calcite-tree/calcite-tree.tsx, src/utils/number.ts
Enables https://eslint.org/docs/rules/no-unneeded-ternary (auto-fixable) to simplify code.
=> chore(linting): enable no-unneeded-ternary rule

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/utils/key.ts
=> fix(calcite-input): disallowing typing any key with shift modifier down inside a number input

src/components/calcite-switch/calcite-switch.scss
**Related Issue:** (#1747)
Removes extraneous margin in RTL.
=> fix(switch): removed unneeded RTL margin 

src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:** #2098
Styles internal "handle" element to match CalciteHandle.
Refactoring ValueListItem to use Handle would be cool.
We are going to have a general ListItem, and when ValueListItem is refactored to use that component, we can take care of this then.
=> fix(value-list-item): updates handle colors to match CalciteHandle

src/utils/dom.e2e.ts, src/utils/dom.ts
**Related Issue:** #2103
fix(dom): Query whole shadowRoot of elements rootNode instead of just inside of the host.
=> fix(dom): Query whole shadowRoot of elements rootNode instead of just inside of the host.

src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:** (#2098)
Updated handle idle color.
cc @bstifle @julio8a
=> fix(value-list-item): updated handle color 

src/components/calcite-input-message/calcite-input-message.e2e.ts
Passes locally fine but seems brittle in Travis CI, so skipping. (All these tests may go away anyways, due to #2172)
Here are few Travis build failures showing the issue:
[Travis fail 1](https://travis-ci.com/github/Esri/calcite-components/builds/226248957):
```
FAIL src/components/calcite-input-message/calcite-input-message.e2e.ts (28.516 s)
● calcite-input-message › CSS properties for light/dark themes › should allow the CSS custom property to be overridden
expect(received).toEqual(expected) // deep equality
Expected: "rgba(0, 0, 0, 0.4)"
Received: "rgba(0, 0, 0, 0.094)"
217 |       inputMessage = await page.find("calcite-input-message");
218 |       inputMessageStyles = await inputMessage.getComputedStyle();
> 219 |       expect(await …
```
=> test(input-message): skip unstable test

src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts, src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #2171
fix(tooltip-manager): Don't show tooltip on click of referenceElement. #2171
=> fix(tooltip-manager): Don't show tooltip on click of referenceElement

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx, src/utils/math.spec.ts, src/utils/math.ts
**Related Issue:** #2122 
Updates the color picker to keep tracking mouse movements when a thumb is being dragged and the mouse moves outside the canvas.
**Notable changes**
* adds `math` util
* fixes thumb hover/idle rendering
* separates mousemove event handlers to cover
* thumb state rendering 
* tracking mouse movement for updating the color
=> feat(color-picker): improve thumb drag interaction

src/components/calcite-pick-list/calcite-pick-list.tsx, src/components/calcite-pick-list/shared-list-logic.ts, src/components/calcite-pick-list/shared-list-tests.ts
**Related Issue:** #1734 
This tweaks pick list's keyboard interaction to allow an item to be selected with the spacebar and allow items to be navigated via up/down arrows (before it would alter the selection when navigating through items).
This makes it consistent to when the pick list has the `multiple` mode enabled.
=> feat(pick-list, value-list): improve keyboard interaction for single-item selection

src/components/calcite-card/calcite-card.scss
Updated spacing between header and subtitle to match Figma.
https://github.com/Esri/calcite-components/projects/14#card-60668124
=> refactor(card): spacing between header and subtitle

src/components/calcite-panel/calcite-panel.scss
Updated the heading and sub heading to use `h` and not `wrap` for text. Per feedback from Bryan on Figma/Tailwind refactor project (below).
https://github.com/Esri/calcite-components/projects/14#card-60668063
=> refactor(flow): change text from wrap to heading

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/new-component.md, .github/ISSUE_TEMPLATE/research.md, .github/ISSUE_TEMPLATE/tooling.md
Adds 'needs triage' label to most issue templates likely to need triaging.
=> chore: add 'needs triage' label to issue templates

src/5-licensing.stories.mdx
**Related Issue:** https://github.com/Esri/calcite-components/pull/2207
Fixes broken Storybook import.
=> docs(storybook): fix broken import

src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion-item/calcite-accordion-item.tsx, src/components/calcite-accordion/calcite-accordion.scss, src/demos/calcite-accordion.html
**Related Issue:** #2041
- Updated large accordion header font size to 0 (16px)
- Removed logic for decorative header icon sizing so that all accordion sizes use small icons
=> fix(calcite-accordion): updated large accordion to match figma

.github/workflows/update-doc.yml
Fixes a step in the update-doc action.
=> chore: fix auto-doc action step

src/components/calcite-progress/calcite-progress.scss
- Changed text to use heading `h`
- Medium font-weight
Card for this PR: https://github.com/Esri/calcite-components/projects/14#card-60667949
=> refactor(progress): text heading and medium

src/components/calcite-rating/calcite-rating.scss
- unselected star: updated to use ui-border-input
- This has an action item to use chip at 16px font and 44px height, but this should be done at the chip component, not star. 
Card for this PR: https://github.com/Esri/calcite-components/projects/14#card-60667925
=> refactor(rating): Unselected star ui-border-input

src/components/calcite-tile/calcite-tile.scss
**Related Issue:** #2123
Removes max width rule.
=> fix(tile): remove max-width

src/components/calcite-radio-group-item/calcite-radio-group-item.scss, src/components/calcite-radio-group/calcite-radio-group.scss
- Large updates:
- Updated height of large to 44
- font is 16px
- icon is 16px
Radio group (and radio group item) for this PR: https://github.com/Esri/calcite-components/projects/14#card-60667936
=> refactor(radio-group): updated height of large (icon and font)

src/components/calcite-modal/calcite-modal.tsx, src/utils/dom.spec.ts, src/utils/dom.ts, src/utils/guid.spec.ts
**Related Issue:** #1756 
Updates `calcite-modal` to use ARIA roles for title and content.
**Note**: This adds a DOM util to ensure elements have a unique ID associated (`ensureId`).
Tested with:
**Safari + VoiceOver**
**FireFox/Edge + NVDA**
=> fix(modal): improve modal a11y

.github/workflows/update-doc.yml
Fixes invalid prop name caught by GitHub: https://github.com/Esri/calcite-components/actions/runs/883011168/workflow
=> chore: fix wrong auto-doc action config prop name

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
We had people typing into a custom values combobox and tabbing away. Because they didn't "enter" the text (and create a chip) their value was thrown away, which was the source of a lot of confusion. One user said "that's weird it's not styled like a tag" and tabbed away anyways.
This change essentially adds a chip for them if they've entered text when they tab away.
=> feat(combobox): apply entered text on tab for custom values combobox

package.json, src/components/calcite-button/calcite-button.stories.ts, src/components/calcite-card/calcite-card.stories.ts, src/components/calcite-checkbox/calcite-checkbox.stories.ts, src/components/calcite-date-picker/calcite-date-picker.stories.ts, src/components/calcite-input-date-picker/calcite-input-date-picker.stories.ts, src/components/calcite-input/calcite-input.stories.ts, src/components/calcite-label/calcite-label.stories.ts, src/components/calcite-link/calcite-link.stories.ts, src/components/calcite-modal/calcite-modal.stories.ts, src/components/calcite-pagination/calcite-pagination.stories.ts, src/components/calcite-radio-button-group/calcite-radio-button-group.stories.ts, src/components/calcite-radio-button/calcite-radio-button.stories.ts, src/components/calcite-radio-group/calcite-radio-group.stories.ts, src/components/calcite-select/calcite-select.stories.ts, src/components/calcite-tabs/calcite-tabs.stories.ts
**Related Issue:** #2108 
This adds RTL stories (based on existing ones) for the following components:
- `calcite-button`
- `calcite-card`
- `calcite-checkbox`
- `calcite-date-picker`
- `calcite-input`
- `calcite-input-date-picker`
- `calcite-label`
- `calcite-link`
- `calcite-modal`
- `calcite-pagination`
- `calcite-radio-button`
- `calcite-radio-button-group`
- `calcite-radio-group`
- `calcite-select`
- `calcite-tabs`
This will help Screener detect visual differences in RTL.
cc @caripizza
=> docs: add RTL stories

.github/workflows/update-doc.yml
The Stencil build step in this action fails because the setup-node action was installing Node v10 (instead of v12+). This updates it to use v14.
=> chore: use node 14 for update-doc action

src/components/calcite-rating/calcite-rating.scss
A bug caused by the refactor. This brings back the focus animation.
=> fix(rating): focus typo fix - outset

src/components/calcite-combobox/calcite-combobox.tsx
Related to the pr I opened the other day: #2239
Previously we used a tab key event to enter the text, this moves to using a blur event so that the text appears correctly if the user clicks away as well.
=> fix(combobox):  treat entered text as chip in custom-value comboboxes on blur

src/components/calcite-popover/calcite-popover.tsx
**Related Issue:** #2130
Fixes setFocus method of Popover.
=> fix(popover): add forceUpdate to ensure Action is available for setFocus

src/components/calcite-modal/calcite-modal.tsx
**Related Issue:** #2178 
Updates modal to restore mutation observing when appended. 
**Note**: I'll submit a separate PR for consistent setup of observers.
=> fix(modal): update footer when modal is connected to the DOM

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #2230 
Tweaks fallback logic for positioning the hue slider scopes.
=> fix(color-picker): handle hue scope when color is 000.

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
Fixing an issue with the combobox when you're using custom values, enter text, then select an item from the tags list. Also updated the test to behave more like an actual blur and used text that matches an existing option to cover this better.
=> fix(combobox): fix custom chip selection on blur

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
Combobox wasn't firing any event when custom values were added.
=> fix(combobox): emit lookup change when custom tag is added

src/components/calcite-action-group/calcite-action-group.scss, src/components/calcite-action-menu/calcite-action-menu.tsx
fix(action-menu): Set offsetDistance to zero.
**Related Issue:** #2295
Sets offsetDistance to zero since the pointer has been removed from ActionMenu.
<!--
Please make sure the PR title and/or commit message adheres to the https://www.conventionalcommits.org/en/v1.0.0/ specification.
Note: If your PR only has one commit and it is NOT semantic, you will need to either
a. add another commit and wait for the check to update
b. proceed to squash merge, but make sure the commit message is the same as the title.
This is because of the way GitHub handles single-commit squash merges (see https://github.com/zeke/semantic-pull-requests/issues/17)
If this is component-related, please verify that:
=> fix(action-menu): Set offsetDistance to zero.

src/components/calcite-action-menu/calcite-action-menu.e2e.ts, src/components/calcite-action-menu/calcite-action-menu.tsx
fix(action-menu): Focus on the menu's trigger when a slotted action is clicked and the menu is closed.
When an action in the `calcite-action-menu` is clicked, the menu is closed but now nothing is focused. This restores focus to the button that opened the menu when an action has been clicked and the menu is now closed.
=> fix(action-menu): Focus on the menu's trigger when a slotted action is clicked and the menu is closed

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
OK, last pr for this I swear. Was improving this test to cover both tab and click away blur and it revealed a bug where using tab key no longer entered the chip so I've addressed it here. 
FYI @driskull you were correct when you asked "Does this need a test?" in https://github.com/Esri/calcite-components/pull/2263 as the test only covered one of the two ways to tab away form the component.
Related prs: #2263 #2283
=> fix(combobox): in-progress custom values should get commited on blur or tab

src/components/calcite-tooltip-manager/calcite-tooltip-manager.e2e.ts, src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx, src/components/calcite-tooltip/resources.ts, src/demos/calcite-tooltip.html
**Related Issue:** #2310
fix(tooltip-manager): Prevents closing prematurely for non-leaf nodes #2310
=> fix(tooltip-manager): Prevents closing prematurely for non-leaf nodes

src/components/calcite-input/calcite-input.e2e.ts
**Related Issue:** #2323
Skips the tests per the issue. (Since it's testing programmatically I just added the problematic locales to be filtered out.)
=> test(input): skip unstable locale tests

src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx
**Related Issue:** #2318
fix(tooltip-manager): Mousing over non-reference elements keeps tooltip open #2318
=> fix(tooltip-manager): Mousing over non-reference elements keeps tooltip open #2318

.lintstagedrc.json
Wires up HTML files to be auto-fixed on commit.
=> chore(linting): lint HTML on commit

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/components/calcite-dropdown/calcite-dropdown.e2e.ts, src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-dropdown/interfaces.ts
**Related Issue:** #2268 #2026
This refactors how items and groups are processed by the dropdown. It previously relied on events to register these elements, but these shouldn't be necessary because of [Stencil's lifecycle hierarchy](https://stenciljs.com/docs/component-lifecycle#lifecycle-hierarchy). 
The tests pass after refactoring and I also tested with the test case provided in #2026 (no more console error).
=> fix(dropdown): fix processing of groups and items

src/components/calcite-split-button/calcite-split-button.e2e.ts, src/components/calcite-split-button/calcite-split-button.scss, src/components/calcite-split-button/calcite-split-button.tsx, src/components/calcite-split-button/readme.md, src/components/calcite-split-button/resources.ts
**Related Issue:** (#921)
Adds a width property. Behavior and style match Button's width property.
=> feat(split-button): add width property, related styles, and doc 

src/components/calcite-combobox/calcite-combobox.e2e.ts, src/components/calcite-combobox/calcite-combobox.tsx
This solves a problem with the height being incorrect on the combobox in a couple different scenarios:
1. When items are nested in a particular way the amount of items shown was always one less than the prop
2. After entering a custom value, only two items where shown, regardless of maxItems setting
=> fix(combobox): fix maxItems after selection, fix maxItems calculation when nested

src/components/calcite-split-button/calcite-split-button.stories.ts
**Related Issue:** #921
Adds `width` property to the story.
Adds a width style to a container div to make it easier to see what `width` does.
Spaced adding this in #2347.
=> docs(split-button): adds width to story

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2316 
This fixes an issue where pressing the Enter/Space key would fire a click event on the button element used for the thumb and would set the value to 0.
=> fix(slider): prevent Enter/Space from setting value to 0

src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2150
Fixes doc for input's action slot.
=> docs(input): use correct action slot name

src/components/calcite-notice/calcite-notice.e2e.ts, src/components/calcite-notice/calcite-notice.resources.ts, src/components/calcite-notice/calcite-notice.scss, src/components/calcite-notice/calcite-notice.stories.ts, src/components/calcite-notice/calcite-notice.tsx, src/demos/calcite-notice.html
**Related Issue:** #2144 
This adds a new slot (`action-end`) for a calcite-action.
The end action can be used alongside `dismissible` as well:
=> feat(notice): allow slotting action

src/components/calcite-alert/usage/basic.md, src/demos/_assets/createAlert.ts
**Related Issue:** # n/a
Updates outdated slot names for alert in its usage example and demo util.
=> docs(alert): use correct slot names in usage ex, demo util

src/components/calcite-notice/calcite-notice.e2e.ts, src/components/calcite-notice/calcite-notice.tsx
This came up during #2144 and fixes a bug that would prevent `setFocus` from working.
=> fix(notice): fix setFocus

src/components/calcite-panel/usage/basic.md
**Related Issue:** #2284
Fixes outdated slot names used in panel usage examples.
=> docs(panel): use proper slot names for leading/trailing actions

src/demos/shell/popup-config-example.html
**Related Issue:** #2150
Fixes outdated input action slot names used in a shell demo.
=> chore(shell): use proper slot name for action

src/components/calcite-time-picker/calcite-time-picker.tsx, src/components/calcite-tree-item/calcite-tree-item.tsx, src/utils/key.ts
This came up from working on #2290. This drops `isSpacebarKey` since `getKey` util is used to normalize key values.
=> refactor(keys): tidy up keys util

src/components/calcite-pick-list/calcite-pick-list.stories.ts, src/components/calcite-pick-list/calcite-pick-list.tsx, src/components/calcite-pick-list/shared-list-logic.ts, src/components/calcite-pick-list/shared-list-render.tsx, src/components/calcite-pick-list/shared-list-tests.ts, src/components/calcite-value-list/calcite-value-list.stories.ts, src/components/calcite-value-list/calcite-value-list.tsx, src/demos/pick-list/basic.html, src/demos/value-list/basic.html
**Related Issue:** #2344 
This adds a `selectionFollowsFocus` (default false) prop to both pick and value lists to allow users to change the selected item as they navigate items with the ⬆  ⬇️  keys.
=> feat(pick-list, value-list): add prop to enable changing selection via keyboard in single-selection mode

package-lock.json
This addresses the following message when running builds:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
=> chore: update browserslist

src/components/calcite-combobox/calcite-combobox.scss
Text input for single select combobox was using a pointer cursor. This is inconsistent with all the other inputs, comboboxes, etc. This was probably a mistake when I added this mode.
=> fix(combobox): use normal pointer for input of single select combobox

src/components/calcite-tree/calcite-tree.e2e.ts, src/components/calcite-tree/calcite-tree.tsx
**Related Issue:** #683 
This fixes an issue where tree would keep focusing on the first tabbable item when you tried focusing out of it. This updates the component to make the root only tabbable if focus has been moved outside.
This also has a test for this case, but it's weird to have a test for browser element tabbing. 
I looked at adding a `setFocus` method, but will create a separate issue for it instead since I'm not sure if we need special considerations for focusing based on the selection mode.
=> fix(tree): allow focusing out of tree via shift + tab

src/components/calcite-button/calcite-button.tsx, src/components/calcite-color-picker/calcite-color-picker.tsx, src/components/calcite-fab/calcite-fab.e2e.ts, src/components/calcite-fab/calcite-fab.tsx, src/components/calcite-inline-editable/calcite-inline-editable.tsx, src/components/calcite-split-button/calcite-split-button.e2e.ts, src/components/calcite-split-button/calcite-split-button.tsx
=> refactor(calcite-button)!: stop spreading attributes  BREAKING CHANGE: to set an aria-label on the button use the label attribute

src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree-item/interfaces.ts, src/components/calcite-tree/calcite-tree.e2e.ts
**Related Issue:** #2290 
This changes the `forceToggle` option in tree-item to be the same as when the item is clicked based on the premise that both of these events would trigger a selection event.
@paulcpederson Can you take a look at this? I'm not sure how to manually test for the ancestors-selection scenario.
=> fix(tree): allow selecting children with Enter/Space when selection-mode=children

src/components/calcite-color-picker/calcite-color-picker.scss
**Related Issue:** #2412 
The host was using the default `display` value, causing the component's box model to not match the component (visually).
=> fix(color-picker): ensure color picker dimensions match its content

src/components/calcite-block/calcite-block.e2e.ts, src/components/calcite-block/calcite-block.scss, src/components/calcite-block/calcite-block.tsx, src/components/calcite-block/resources.ts, src/demos/block/basic.html
**Related Issue:** #963 
This adds support for menu actions to the block header.
=> feat(block): add slot for header menu actions

src/components/calcite-tree-item/calcite-tree-item.scss, src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.e2e.ts
**Related Issue:** #2196 
This PR fixes an issue caused the default behavior from the tree item's checkbox label. Clicking it would cause a 2 clicks to be fired (from the host and checkbox+label). The internal label + checkbox are no longer interactive since the item itself handles this already.
=> fix(tree): prevent emitting selection event twice when a tree-item's checkbox label is clicked

src/components/calcite-popover/calcite-popover.e2e.ts, src/components/calcite-popover/calcite-popover.tsx, src/components/calcite-tooltip/calcite-tooltip.e2e.ts, src/components/calcite-tooltip/calcite-tooltip.tsx
**Related Issue:** #2446
fix(popover, tooltip): Query for referenceElement if needed when the tooltip/popover is opened or closed. #2446
=> fix(popover, tooltip): Query for referenceElement if needed when the tooltip/popover is opened or closed. #2446

src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.scss, src/components/calcite-slider/calcite-slider.tsx, src/demos/calcite-slider.html, src/utils/dom.ts
**Related Issue:** #720
This adds a `mirrored` property to `calcite-slider` (default false). When set to true, it will invert the slider unless there is a histogram associated. In this case, `mirrored` has no effect. This decision is based on https://material.io/design/usability/bidirectionality.html#mirroring-layout, talking to some teams that work w/ data visualization + sliders and some good ol' fashioned googling.
**Extras**
* sorts props alphabetically
* fixed casing of an internal type
* refactored method arguments/vars to make them value-agnostic - these are now left/right-based
* adds local vars to store bounding client rects to avoid duplicate computations
* adds another column for testing mirrored along with some edge-positioning cases
=> feat(slider): add support for mirroring slider

src/components/calcite-checkbox/calcite-checkbox.e2e.ts, src/components/calcite-label/calcite-label.tsx
=> refactor(calcite-label): stop spreading attributes to the label element

src/components/calcite-dropdown-group/calcite-dropdown-group.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.scss, src/components/calcite-dropdown-item/calcite-dropdown-item.tsx, src/demos/calcite-dropdown.html
**Related Issue:** #2041
- Updated scale L icon size to S
- Updated scale L font size to 1h
=> refactor(calcite-dropdown): updated scale l icon size and font size to match figma

package-lock.json
**Related Issue:** # (N/A)
Updates the version of calcite-ui-icons in package-lock.json (match package.json version)
=> chore(deps): update calicte-ui-icons in lock file

package-lock.json, src/components/calcite-radio-button-group/calcite-radio-button-group.tsx, src/components/calcite-radio-button/calcite-radio-button.tsx
**Related Issue:** #2542
Fixes an issue where `<code>` blocks  in JSDoc comments prevented the Storybook "Docs" from rendering.
=> docs(radio-button-group, radio-button): fix "Docs" render issue

src/components/calcite-action-menu/calcite-action-menu.scss
**Related Issue:** #2459
More accurately targets the 1px margin style to the actions in side the menu.
The 1px margin is to accommodate the focus ring.
=> fix(action-menu): target 1px margin more accurately to actions in menu

src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.e2e.ts
**Related Issue:** #2437 
This fixes an issue where clicking a tree-item's checkbox would not toggle the selection when a tree is in multi selection mode with input-enabled.
@paulcpederson Can you help test this one? I'm not clear if other selection modes + input-enabled need to work differently. The ancestor selection-mode + input-enabled from the demo page appear to work fine. I added an E2E test to start keeping track of this.
=> fix(tree): fix item selection when multi + input-enabled

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #2357 
This addresses an issue caused by the scope key-nudging logic never updating the current hue value when 0. Additionally includes some minor cleanup.
=> fix(color-picker): fix nudging hue slider with left/right arrows when color is #000 or #fff

src/components/calcite-button/calcite-button.e2e.ts, src/components/calcite-button/calcite-button.scss, src/components/calcite-button/calcite-button.tsx, src/components/calcite-button/resources.ts, src/demos/_assets/loadingButton.ts, src/demos/calcite-button.html
**Related Issue:** #2420
Adds a loading animation to calcite-button when `loading` changes (ensures 1 icon only buttons stay square when loading, per Figma spec).
(See "Toggle loading animation" in calcite-button.html for demo.)
=> feat(button): show animation when loading changes

src/components/calcite-button/calcite-button.e2e.ts
**Related Issue:** #2420 (follow-up test fix)
Updates the corresponding loading animation tests to just check for the classes instead. (Waiting for the loaders' animations seems brittle with Travis.)
=> test(button): fix unstable tests

src/components/calcite-inline-editable/calcite-inline-editable.e2e.ts, src/components/calcite-inline-editable/calcite-inline-editable.scss, src/components/calcite-inline-editable/calcite-inline-editable.tsx, src/components/calcite-inline-editable/resources.ts, src/components/calcite-input-date-picker/calcite-input-date-picker.scss, src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.resources.ts, src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.tsx, src/components/calcite-radio-button/calcite-radio-button.scss, src/components/calcite-radio-button/calcite-radio-button.tsx, src/components/calcite-radio-button/resources.ts
**Related Issue:** #2422
This PR namespaces classes (following [BEM](http://getbem.com/)) of currently scoped components since these are not transformed by the Stencil build and are available in the light DOM. 
This is a stopgap solution until all scoped components use shadow DOM.
=> fix(inline-editable, input, radio-button): namespace scoped CSS classes

src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2422 
This fixes a styling regression introduced by https://github.com/Esri/calcite-components/pull/2564. Issue was due to a few overlooked CSS class renames and not applying the class object correctly.
=> fix(input): fix layout of number input with horizontal button layout

src/components/calcite-tree/calcite-tree.e2e.ts
Fixes test warning reported in https://github.com/Esri/calcite-components/commit/44af3096adb6bbf5424c7aae83df054513c79016#r53757509.
=> test(tree): fix Jest warning

src/demos/calcite-icon.html
**Related Issue:** #2529 
- match the current calcite-icon demo page according to the Figma design
- _small_, _medium_, and _large_ variants included
=> test(icon): updated icon demo page

src/components/calcite-list-item/calcite-list-item.scss
**Related Issue:** #2587
Pre design spec, adds 2px spacing between label and description.
cc @bstifle
=> fix(calcite-list-item): adds bit of spacing between label and description

.github/workflows/update-deps.yml
Wires up [setup-git-user](https://github.com/marketplace/actions/setup-git-user) action to provide missing info for committing dependency updates.
=> chore(deps): set git user for dep-updater action

src/components/calcite-block/calcite-block.tsx, src/components/calcite-block/readme.md
**Related Issue:** #2531
Updated doc to leading, not trailing. This was likely caused by a typo.
=> docs(action-block): slot icon position is wrong

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.scss, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2582
fix(input): disabled calcite-input + type=number allows interaction with the up/down buttons. #2582
=> fix(input): disabled calcite-input + type=number allows interaction with the up/down buttons

src/components/calcite-notice/usage/basic.md
Fixes a slot typo I made and adds a calcite-link to demonstrate using the `link` slot.
=> docs(notice): fix typo in usage example

.github/workflows/update-deps.yml
Fixes `update-deps` error reported in some GH Action workflow runs (e.g., https://github.com/Esri/calcite-components/actions/runs/1057612143):
> Error : .github#L1
> a step cannot have both the `uses` and `run` keys
Thanks for reporting this, @caripizza!
=> chore(deps): fix git user setup for dep-updater

.huskyrc.json
Removes leftover file from Husky update: https://github.com/Esri/calcite-components/pull/2418#issuecomment-871695258
=> chore: remove unnecessary .huskyrc.json

src/demos/calcite-progress.html
**Related Issue:** #2636 
- fixed typo error from _intermediate_ to _indeterminate_
=> test(progress): fixed indeterminate typo

src/assets/styles/global.scss, src/components/calcite-inline-editable/calcite-inline-editable.stories.ts, src/components/calcite-input-message/calcite-input-message.e2e.ts, src/components/calcite-input-message/calcite-input-message.scss, src/components/calcite-input-message/calcite-input-message.tsx, src/components/calcite-input-message/interfaces.ts, src/components/calcite-input/calcite-input.stories.ts, src/demos/_assets/validateInput.ts
**Related Issue:** #2172 
Prunes the floating input-message variant.
=> refactor(calcite-input-message): remove floating messages

.github/workflows/update-browserslist-db.yml
Adds GH action to automate browserslist's database and submit a PR every week.
=> chore: automate browserslist db update

src/tests/utils.ts
These test util improvements came from #2303: 
* `dragAndDrop` – this can now be configured to place the pointer position horizontally and even specify an x,y offset.
* `visualizeMouseCursor` – this helps debug headful E2E tests by showing where the mouse cursor is during the test
**note**: this should only be used for debugging and not be included in a test (custom ESLint rule candidate)
=> test: enhance drag-and-drop util and add mouse cursor tracking util

src/components/calcite-color-picker/calcite-color-picker.e2e.ts, src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #2303
This introduces an input event that fires as the color field or hue slider thumb is dragged. The "minor" breaking change is that the change event will no longer fire when dragging and only when the thumb is released and final value is committed.
=> feat(color-picker)!: introduce input event and modify change event to no longer fire as hue slider/color field thumbs are dragged

src/components/calcite-color-picker/calcite-color-picker.tsx
**Related Issue:** #2335 
This revisits mouse tracking when the color field/hue slider thumb is dragged. The previous implementation could get out of sync in some cases (e.g, `MouseEvent#movement(X|Y)` would emit non-zero values when the cursor would move past the edge, Chrome and Firefox emit 0). This approach is simpler and slightly more efficient since it won't have to calculate the canvas region when the mouse is dragged outside of its bounds.
=> fix(color-picker): improve mouse tracking when dragging color field/hue slider thumb

src/components/calcite-slider/calcite-slider.tsx
**Related Issue:** #2309 
This fixes an issue where the the thumb elements moving over the track on mousedown would prevent Firefox from emitting a click event. 
**Notable changes**
* Simplifies mouse handling logic
* Manages event handlers properly (previously using `bind` on each add)
=> fix(slider): ensure change event is emitted consistently

src/components/calcite-color-picker/calcite-color-picker.e2e.ts
**Related Issue:** #2694
🚫 🧪 🚫
=> test(color-picker): skip unstable test

src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2675
fix(input): Internal buttons should not be able to submit forms. #2675
This sets all internal buttons to be a type of "button" so that they do not submit the form when an enter key is pressed on the search input element.
=> fix(input): Internal buttons should not be able to submit forms

src/components/calcite-graph/calcite-graph.e2e.ts, src/components/calcite-graph/calcite-graph.tsx, src/components/calcite-graph/interfaces.ts, src/components/calcite-slider/calcite-slider.e2e.ts, src/components/calcite-slider/calcite-slider.stories.ts, src/components/calcite-slider/calcite-slider.tsx, src/demos/calcite-graph.html, src/demos/calcite-slider.html, src/index.html
**Related Issue:** #834
Adds support for color stops for the `<calcite-graph>` component. A subsequent PR will add color stop support to the `<calcite-slider>` component.
```tsx
/**
* Array of values describing a single color stop ([offset, color, opacity])
* These color stops should be sorted by offset value
*/
@Prop() colorStops: [number, string, number][];
```
Color stops are added via a `<linearGradient>` element and apply along the x-axis.
This is pretty rudimentary support for adding a linear gradient with color stops. It solves the use case in the related issue, but are there other, more complex, use cases that we want to be prepared to support in the future?
=> feat(slider): Add support for histogram color stops

src/components/calcite-color-picker/calcite-color-picker.e2e.ts
**Related Issue:** #2694
Update test to allow variance in input event count during the simulated thumb drag portion.
=> test(color-picker): stabilize and unskip test

src/components/calcite-dropdown/calcite-dropdown.scss, src/demos/calcite-card.html
**Related Issue:** (#2625)
One line change to rule them all.
Reverts trigger width to 100%.
=> fix(dropdown): revert dropdown-trigger-container width 

src/components/calcite-switch/calcite-switch.scss
**Related Issue:** #2461 
Updates calcite-switch hover state on idle and active to grow inward as shown in Figma design.
- Changed `box-shadow` to use inset rather than the previous `shadow-outline-active`
=> refactor(Switch): match Figma and utilize Tailwind

src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.scss, src/components/calcite-date-picker-month/calcite-date-picker-month.scss
**Related Issue:** #2465
Adjusted spacing on `calcite-datepicker` header spaing Figma design.
=> refactor(Date Picker): match Figma and utilize Tailwind

src/components/calcite-list/calcite-list.e2e.ts, src/components/calcite-list/calcite-list.scss
**Related Issue:** (#2729)
Updates CalciteList :host display to be `block`.
=> fix(list): update display to block and updates related test

src/demos/calcite-color-picker.html
**Related Issue:** #2576 
- updated calcite-color-picker encompassing the Figma design
- this version includes _small_, _medium_, and _large_ scale, which the previous version failed to include
=> test(color-picker): updated calcite-color-picker demo page

stencil.config.ts
Splits up action components to main entry files. This also helps the build process generate the helper bundles included in the `custom-elements-bundle` output target.
Note: `calcite-action-group` is intentionally left out since it is a support component used by both `calcite-action-bar` and `calcite-action-pad`.
=> fix(custom-elements): add missing action component helper bundles

.github/workflows/update-browserslist-db.yml
Fixes copypasta error on the name. 😅
=> chore: fix browserslist-db-action-name

src/components/calcite-block/calcite-block.scss
**Related Issue:** #2735
Heading text adjusted from `ui-text-3` to `ui-text-1` by default.
=> refactor(Block heading): match Figma and utilize Tailwind

src/components/calcite-action/calcite-action.e2e.ts, src/components/calcite-action/calcite-action.tsx
Use onClick instead.
docs(action): Deprecate calciteActionClick.
=> docs(action): Deprecate calciteActionClick.

package-lock.json, package.json, src/6-custom-theme.stories.mdx
**Related Issue:** #2042
Bumps calcite-colors dependency to get the updated border-color values in its latest release:
```scss
.calcite-theme-light {
...
--calcite-ui-border-2: #d4d4d4; /* previous: #dfdfdf */
--calcite-ui-border-3: #dfdfdf; /* previous: #eaeaea */
...
}
.calcite-theme-dark {
...
--calcite-ui-border-1: #555555; /* previous: #4a4a4a */
--calcite-ui-border-2: #4a4a4a; /* previous: #404040 */
--calcite-ui-border-3: #404040; /* previous: #353535 */
...
}
```
=> chore(deps): bump calcite-colors, resolve border color conflicts w/ backgrounds

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2726
fix(input): Prevent keyboard events from changing values when readOnly is true. #2726
=> fix(input): Prevent keyboard events from changing values when readOnly is true

CONTRIBUTING.md
Adds some draft info on the commit messages convention.
=> docs(contributing): add commit message format section

src/components/calcite-block/calcite-block.e2e.ts, src/components/calcite-block/calcite-block.tsx
**Related Issue:** (#2740)
- adds logic to not render collapsibleIcon when `header-menu-actions` has content
- adds explicit test for this
- adds explicit test to not render collapsibleIcon when `control` has content
cc @caripizza @jcfranco
=> fix(block): stops rendering collapsibleIcon when there are header-menu-actions

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx, src/demos/calcite-input-number.html
**Related Issue:** #2764
This pr allows number inputs with `step="any"` to input decimal values akin to the native number input.
=> fix(calcite-input): number inputs with step="any" should allow decimals

package-lock.json, package.json, stencil.config.ts
The latest `color` package is on the bleeding-edge and may cause issues for clients that have a build process that does not target ES2021. This PR tweaks the build to transpile numeric separators from the package. 
cc @dasa
=> build: transpile numeric separators from color package

src/demos/calcite-flow.html, src/index.html
**Related Issue:** #2688 
- The previous merge #2755 had an incorrect filepath. 
- filepath corrected
=> test(flow-corrected): current merge error, corrected file path

stencil.config.ts
Setting value to `babelHelpers` to fix the following build warning (introduced by https://github.com/Esri/calcite-components/pull/2822):
```
babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
```
=> build: explicitly set babelHelpers to address warning

src/components/calcite-color-picker/readme.md, src/components/calcite-color-picker/usage/Basic.md, src/components/calcite-color-picker/usage/Minimal.md
- #2492 
Add usage examples for the calcite-color-picker documentation.
=> docs(color-picker): add usage examples

src/assets/styles/global.scss, src/components/calcite-loader/calcite-loader.scss, src/components/calcite-scrim/calcite-scrim.e2e.ts, src/components/calcite-scrim/calcite-scrim.scss, src/components/calcite-scrim/calcite-scrim.tsx, src/demos/calcite-scrim.html
**Related Issue:** #2801
* updates render to include default slot
* updates tests
* updates scrim bg color per @bstifle
=> feat(scrim): render default slot

src/components/calcite-flow/calcite-flow.scss, src/components/calcite-shell-panel/calcite-shell-panel.scss, src/demos/shell/nesting-testing-flow.html, src/demos/shell/nesting-testing.html
**Related Issue:** #2741 
* Adds `calcite-match-height` class and styles to Flow.
* updates demo to reveal match-height usage with custom elements.
@jcfranco @caripizza This should be extremely low-risk as the class is 100% opt-in.
=> feat(flow): add match-height class

screener.config.js
`screener-runner` has [an option](https://github.com/screener-io/screener-runner/#:~:text=alwaysAcceptBaseBranch) that sounds like it would help with some visual diff inconsistencies we've noticed between PRs:
> alwaysAcceptBaseBranch: Option to automatically accept new and changed states in base branch. Assumes base branch should always be correct.
This PR enables this option for testing. 
If this ends up working the way we need it, we can schedule a date to ensure all PRs have the latest version of `master` merged into them. In theory, the base for all screenshot diffs would be the same and the only visual diffs we get should be related to the PR.
@eriklharper @caripizza For us to test this, would we need to accept some invalid changes in master and see how …
=> ci(screener): enable alwaysAcceptBaseBranch

src/components/calcite-avatar/usage/basic.md, src/components/calcite-date-picker/usage/basic.md
**Related Issue:** ##2859
Custom Elements should not be self closing, so I added closing tags to the usage examples that are.
=> docs(avatar, date-picker): add closing tags

src/components/calcite-date-picker/calcite-date-picker.e2e.ts
=> test(date-picker): skip unstable test

src/components/calcite-combobox/calcite-combobox.e2e.ts
**Related Issue:** #1876
Stabilizes test by waiting for combobox to be open before typing.
=> test(combobox): stabilize test

src/components/calcite-modal/calcite-modal.e2e.ts
**Related Issue:** #1626 
Unskipped to troubleshoot, but the build passed for 10 runs w/o any changes.
=> test(modal): stabilize test

src/components/calcite-alert/calcite-alert.e2e.ts
**Related Issue:** #1608 
Unskipped to troubleshoot, but the build passed for 10 runs w/o any changes.
=> test(alert): stabilize test

.lintstagedrc.json, package.json
We still have a couple of config JS files in the codebase (e.g., `screener.config.js`, `tailwind.config.js`). This updates our linting config and scripts to process them.
=> chore(linting): enable JS linting for config files

src/components/calcite-input/calcite-input.e2e.ts
Skips unstable `calcite-input` test: 
```
FAIL src/components/calcite-input/calcite-input.e2e.ts (380.725 s)
● calcite-input › number type › allows decimals when step is any
expect(received).toBe(expected) // Object.is equality
Expected: "1.5"
Received: "15"
920 |       await page.waitForChanges();
921 | 
> 922 |       expect(await input.getProperty("value")).toBe("1.5");
|                                                ^
923 |     });
924 |   });
925 | 
```
Reported in https://github.com/Esri/calcite-components/pull/2943#issuecomment-907709749.
=> test(input): skip unstable test

src/components/calcite-input/calcite-input.e2e.ts, src/components/calcite-input/calcite-input.tsx
**Related Issue:** #2918
This fixes an issue where nudging number values when step is set to a decimal was setting the value to 1 and then further nudging wouldn't have any effect.
=> fix(calcite-input): number values properly nudge when step is set to a decimal or "any"

src/components/calcite-tile/calcite-tile.e2e.ts, src/components/calcite-tile/calcite-tile.scss, src/components/calcite-tile/calcite-tile.stories.ts, src/components/calcite-tile/calcite-tile.tsx, src/components/calcite-tile/resources.ts, src/demos/calcite-tile-select.html, src/tests/commonTests.ts
**Related Issue:** #2113 
This updates `calcite-tile` to start following the standardization of slots (content) per our [prop vs slot discussion](https://github.com/Esri/calcite-components/wiki/Property-vs-Slot) to support slotting icons.
@asangma Can you review the structure & spacing?
* Story or demo page update for slots? Both? 
* Do we need to update the doc on guidance on using the slots? E.g., The `icon` prop should not be used along with a slotted icon (per https://github.com/Esri/calcite-components/issues/2113#issuecomment-866047377).
=> feat(tile): add content-start/content-end slots

src/components/calcite-dropdown/calcite-dropdown.tsx, src/components/calcite-dropdown/resources.ts
**Related Issue:** #2851
Missed one hardcoded slot from calcite-dropdown.
=> refactor(dropdown): use resource file for slot

src/components/calcite-tree-item/calcite-tree-item.tsx, src/components/calcite-tree/calcite-tree.tsx
**Related Issue:** #2807
Fixed the tree and tree-item slot documentation pointed out by @jcfranco during verification.
=> docs(tree, tree-item): fix slot documentation

src/components/calcite-accordion-item/calcite-accordion-item.scss, src/components/calcite-accordion-item/calcite-accordion-item.tsx, src/demos/calcite-accordion.html
Related Issue: [#2597](https://github.com/Esri/calcite-components/issues/2597)
This fixes an issue in `calcite-accordion-item` where chevron and caret directions pointing opposite of `calcite-block` .
=> fix(accordion): match accordion icon directions with block

src/components/calcite-tip-manager/calcite-tip-manager.tsx
**Related Issue:** #2856
When using tip manager the close button should be medium and not small.
=> refactor (calcite tip manager) close button size

src/components/calcite-action/calcite-action.scss
**Related Issue:** #1082
Calcite action tap behavior updated on active state. Background now changes to `foreground-1` from `foreground-3` when the button is actively clicked.
=> refactor(action): action active tap behavior

src/components/calcite-block-section/calcite-block-section.scss, src/demos/shell/block-configurations.html
**Related Issue:** #2577
* cleans up styles that were causing misalignments with label+switch
* adds example in a demo
=> fix(block-section): style update to align better with label and switch combo.

package-lock.json, package.json
Updating calcite-ui-icons to v3.16.9 to get that nice thumbs-down icon.
=> chore: update calcite-ui-icons to latest

src/components/calcite-list/calcite-list.stories.ts, src/components/calcite-pick-list/calcite-pick-list.stories.ts, src/components/calcite-popover/calcite-popover.stories.ts, src/components/calcite-shell/calcite-shell.stories.ts, src/components/calcite-tip/calcite-tip.stories.ts, src/components/calcite-value-list/calcite-value-list.stories.ts
**Related Issue:** #2887
Some of the child components did not have their readmes on storybook, such as `calcite-value-list-item`. I added the missing readmes under the parent components, similar to how [calcite-stepper](https://esri.github.io/calcite-components/?path=/docs/components-stepper--simple) is [implemented](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-stepper/calcite-stepper.stories.ts#L12).
=> docs: add missing storybook readmes

screener.config.js
Disables the `alwaysAcceptBaseBranch` Screener setting (from pr #2843).
**Why?**
We don't want undesirable changes that inadvertently get merged into master to be assumed to be correct. These were leading to false positives on subsequent pr builds.
According to Screener, this is how the setting functions:
> Yes, the "alwaysAcceptBaseBranch" is making an assumption that everything in your base branch is correct, and will automatically accept all states - Loyal
For additional insight, see pr #2978 for screenshot examples with the diff behavior Screener failed to pick up with this setting enabled.
**What else did we learn?**
- removal of stories does not impact test results (ie., this won't fail Screener)
- Screener's default settings ignore small layout …
=> ci(screener): disables alwaysAcceptBaseBranch setting

src/assets/styles/readme.md
**Related Issue:** #2999
The link to the color assets was broken.
=> docs(assets): fix broken color link

src/components/calcite-block/calcite-block.tsx, src/components/calcite-block/readme.md
**Related Issue:** #2824 
Block doesn't work without a heading, so I required it in the doc.
=> docs(block): require heading

package-lock.json, package.json, src/components/calcite-action-bar/calcite-action-bar.tsx, src/components/calcite-action-menu/calcite-action-menu.tsx, src/components/calcite-action/calcite-action.tsx, src/components/calcite-button/calcite-button.tsx, src/components/calcite-combobox/calcite-combobox.tsx, src/components/calcite-flow/calcite-flow.tsx, src/components/calcite-icon/calcite-icon.tsx, src/components/calcite-modal/calcite-modal.tsx, src/components/calcite-option/calcite-option.tsx, src/components/calcite-pick-list/calcite-pick-list.tsx, src/components/calcite-pick-list/shared-list-logic.ts, src/components/calcite-radio-group-item/calcite-radio-group-item.tsx, src/components/calcite-select/calcite-select.tsx, src/components/calcite-sortable-list/calcite-sortable-list.tsx, src/components/calcite-tab-title/calcite-tab-title.tsx, src/components/calcite-tip-manager/calcite-tip-manager.tsx, src/components/calcite-value-list/calcite-value-list.tsx, src/utils/observers.ts
Introduces a utility to consistently create observers (mutation, intersection, resize) for browser contexts. This will help with prerendering.
=> refactor: add util to create observers consistently

support/prepReleaseCommit.ts
**Related Issue:** #2623
Fixes the CDN-URL-updating code:
* update regexps to handle formatted script/link tags – previously would not match after formatting
* use releaseAs version to generate CDN URLs – previously would use pre-bump/outdated version
=> chore: fix CDN-updating logic

.github/workflows/pr-bot.yml
the pr bot kept assigning the creator even when they tried to assign someone else. Only running the action when a PR is opened will fix that
=> chore(actions): only run on opened event

src/components/calcite-accordion-item/calcite-accordion-item.scss
**Related Issue:** [#2597
](https://github.com/Esri/calcite-components/issues/2597)
This fixes the issue in `calcite-accordion` where direction of icons are opposite  when `icon-position` is set to start
=> fix(accordion): match icon directions with block when positioned at start
