- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/scrim/scrim.e2e.ts
- packages/calcite-components/src/components/scrim/scrim.scss
> test(scrim): add component token E2E tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/tip-group/tip-group.e2e.ts
- packages/calcite-components/src/components/tip-manager/tip-manager.e2e.ts
- packages/calcite-components/src/components/tip-manager/tip-manager.scss
- packages/calcite-components/src/components/tip/tip.e2e.ts
- packages/calcite-components/src/components/tip/tip.scss
> test(tip, tip-group, tip-manager): add component token E2E tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts
- packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx
- packages/calcite-components/src/components/dropdown-group/resources.ts
- packages/calcite-components/src/components/dropdown-item/dropdown-item.e2e.ts
- packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
- packages/calcite-components/src/components/dropdown/dropdown.scss
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/dropdown/resources.ts
> test(dropdown, dropdown-group): add component token E2E tests

- packages/calcite-components/src/components/select/select.e2e.ts
- packages/calcite-components/src/components/select/select.scss
> test(select): add component token E2E tests

- .github/scripts/publishPrerelease.sh
**Related Issue:** #9578
Resolve [an error](https://github.com/Esri/calcite-design-system/actions/runs/9563619774/job/26362509309#step:4:16) in the prerelease deployment script where an npm package is used before it is installed.
> ci(next): install deps before release scripts execute

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/radio-button/radio-button.e2e.ts
- packages/calcite-components/src/components/radio-button/radio-button.scss
> test(radio-button): add component token E2E tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/combobox-item-group/combobox-item-group.e2e.ts
- packages/calcite-components/src/components/combobox-item/combobox-item.e2e.ts
- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.scss
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/combobox/resources.ts
- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
- packages/calcite-components/src/components/input-time-zone/input-time-zone.scss
> test(combobox, combobox-item-group, combobox-item): add component token E2E tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9617
- if no filtered items are displayed, the combobox should not be opened
- adds test
> fix(combobox): only open when text exists and filtered items are present

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/list-item-group/list-item-group.e2e.ts
- packages/calcite-components/src/components/list-item-group/list-item-group.scss
- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/list-item/list-item.scss
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.scss
Made sure components were UTD with /dev to reduce merge conflict churn
Updates component tokens
Update e2e themed tests
> fix(list, list-item, list-item-group): add e2e themed tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/handle/handle.tsx
Marks `t9n` internal props as mutable to avoid warning debug messages. Doc was also updated for consistency.
> chore(handle): avoid mutable warnings from t9n props

- .github/scripts/publishPrerelease.sh
- package-lock.json
- package.json
**Related Issue:** #9628
A [pre-release error](https://github.com/Esri/calcite-design-system/actions/runs/9602677524/job/26484030057#step:4:98) occurred because lerna uses conventional-changelog's commonjs modules, which were removed in v8. Additionally, the pre-release script wasn't exiting on error.
> build(deps): downgrade conventional commits to fix next

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/inline-editable/inline-editable.e2e.ts
- packages/calcite-components/src/components/inline-editable/inline-editable.scss
Adds token theme tests for `calcite-inline-editable`.
> test(inline-editable): add token theme tests

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/filter/filter.e2e.ts
- packages/calcite-components/src/components/filter/filter.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/utils/filter.ts
**Related Issue:** #9619
- add filterProps property to list
- changes `matchFields` to `filterProps` on the filter component.
- add tests
> feat(list): add filterProps property to specify which properties to filter against

- packages/calcite-components/src/components/flow-item/flow-item.stories.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/panel/panel.stories.ts
**Related Issue:** #8981
Fixes DOM order of flow-item footer start/end slots.
Note: `flow-item` and `panel` stories were updated to make footer slot content easier to review.
> fix(flow-item): fix inverted footer start/end slots

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/components/input/common/input.ts
- packages/calcite-components/src/demos/validation.html
**Related Issue:** #8065, #9282
- Add `min` and `mix` properties to `calcite-input-time-picker`
- Add form validation support for `min` and `max` constraints to `calcite-input-time-picker` and `calcite-input-date-picker`
> feat(input-date-picker, input-time-picker): support form validation for min/max constraints

- .github/workflows/deploy-latest.yml
- Switch from the deprecated release-please-action repo to the new one
- Bump to v4
> ci(release-please): bump to v4

- .github/workflows/deploy-latest.yml
Fix a bug in release-please-action v4 that changes how the `releases_created` [output](https://github.com/googleapis/release-please-action?tab=readme-ov-file#outputs) needs to be checked in conditionals.
ref: https://github.com/googleapis/release-please-action/issues/912
> ci(release-please): fix conditional that checks if releases were created

- release-please-config.json
Releasing the `2.8.x` hotfix patches after `2.9.0` has caused a lot of issues with release-please. This hardcodes the `2.9.0` release commit so release-please doesn't try to figure things out itself.
https://github.com/googleapis/release-please/blob/ace2bd5dc778f83c33ad5dee6807db5d0afdba36/docs/manifest-releaser.md?plain=1#L134-L147
> ci(release-please): fix hotfix weirdness by hardcoding sha

- .github/workflows/deploy-latest.yml
Maybe release-please thinks the target branch is `dev` since the commit is being rebased to `main`?
> ci(release-please): hardcode target branch

- packages/calcite-components-angular/projects/component-library/package.json
Unfortunately, the `2.10.0` release didn't fix the empty Angular dist. After some digging, it started in `2.9.0-next.24`. These are the suspicious commits:
```sh
git log @esri/calcite-components-angular@2.9.0-next.23...@esri/calcite-components-angular@2.9.0-next.24^ -- packages/calcite-components-angular
```
In #9428 I added the `files` field to the `package.json` so the dist files could be added to the GitHub releases. It seems like that broke the actual releases, because Angular has really strange workflow where they copy the `package.json` into the `dist` and release from there.
> fix(angular): resolve empty dist

- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
The latest Puppeteer version includes Chromium 119, so we no longer need to provide most of what the test polyfill included. We still override supported time zones for increased coverage and to ease some test configurations.
> test(input-time-zone): tidy up Intl API polyfill/override

- package-lock.json
Fix incorrect package versions in `package-lock.json` due to the manual release.
> chore: fix package-lock versioning

- packages/calcite-components/src/components/block/block.tsx
> refactor(block): use icon value as key instead of class for consistency

- packages/calcite-components/.eslintrc.cjs
- packages/calcite-components/src/utils/floating-ui.ts
- packages/calcite-components/src/utils/form.tsx
- packages/calcite-components/src/utils/observers.ts
- packages/calcite-components/src/utils/t9n.ts
Prevents method shorthand syntax to avoid potential pitfals described in https://www.totaltypescript.com/method-shorthand-syntax-considered-harmful
> chore(linting): enable @typescript-eslint/methd-signature-style for safer types

- .github/workflows/deploy-latest.yml
- .release-please-manifest.json
- package-lock.json
- packages/calcite-components/CHANGELOG.md
- packages/calcite-components/package.json
- packages/calcite-design-tokens/package.json
- packages/eslint-plugin-calcite-components/package.json
- release-please-config.json
- support/syncLinkedPackageVersions.ts
I ended up releasing manually in the hopes that a new version will fix release-please.
- Re-bump release-please to v4 since that wasn't the issue
- Remove the commit scanning limitations from release-please
- Bump the version in the release-please manifest, which wasn't done by lerna
- Make the `latest` release commit message used by lerna consistent with the one used by release-please
- Lerna bumped the minor version of the design tokens and eslint plugin even though there were no deployable changes. So I downgraded them from the `next` pre-release to their latest version before deploying, but that [broke the pre-release CI](https://github.com/Esri/calcite-design-system/actions/runs/9687123168/job/26731035404#step:4:147). This manually bumps them back to the `next` versions.
> ci: cleanup release troubleshooting changes

- release-please-config.json
This is the last release-please escape hatch I haven't tried yet.
> ci(release-please): try setting bootstrap-sha to 2.10

- release-please-config.json
I just realized the "label" field replaces the default `autorelease: pending` one release-please uses to identify their pull requests. I'm pretty sure that was causing the issues.
> ci(release-please): use default label to identify PRs

- packages/calcite-components/src/utils/interactive.tsx
**Related Issue:** #9565
This updates the Firefox-specific workaround to remove the parent interaction blocker when no other disabled sibling elements are present.
**Note**: test environment is Chromium-based, so no tests were updated.
> fix: fix issue in Firefox where disabled elements were incorrectly enabled when a sibling was enabled

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/button/button.e2e.ts
- packages/calcite-components/src/components/button/button.scss
- packages/calcite-components/src/components/button/button.tsx
- packages/calcite-components/src/components/button/resources.ts
- packages/calcite-components/src/components/fab/fab.e2e.ts
- packages/calcite-components/src/components/fab/fab.scss
> test(button, fab): add component token E2E tests

- packages/calcite-components/src/components/rating/rating.e2e.ts
- packages/calcite-components/src/components/rating/rating.scss
- packages/calcite-components/src/components/rating/rating.tsx
- packages/calcite-components/src/components/rating/resources.ts
Adds token tests for theming to `calcite-rating`.
> test(rating): add theme token tests

- packages/calcite-components/src/components/block-section/block-section.tsx
**Related Issue:** #9703
Updates icon rendering to use class instead of value for styling.
> fix(block-section): apply missing CSS class to start/end icon

- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/segmented-control/segmented-control.tsx
**Related Issue:** #6860 
Made the checked state of segmented control update when the clearing value is undefined.
> fix(segmented-control): Make check state update correctly

- packages/calcite-components/src/components/text-area/resources.ts
- packages/calcite-components/src/components/text-area/text-area.e2e.ts
- packages/calcite-components/src/components/text-area/text-area.scss
- packages/calcite-components/src/components/text-area/text-area.tsx
- packages/calcite-components/src/tests/commonTests/themed.ts
> test(text-area): add component token E2E tests

- packages/calcite-components/src/components/flow-item/flow-item.stories.ts
- packages/calcite-components/src/components/panel/panel.stories.ts
**Related Issue:** #6980 
Adding scale control to the simple stories on storybook
> test(panel, flow-item): add scale control to simple stories

- packages/calcite-components/src/components/input-number/input-number.e2e.ts
- packages/calcite-components/src/components/input-number/input-number.tsx
**Related Issue:** #9740
Restores `decimal` default for the internal input's `inputmode`, which was unintentionally removed in https://github.com/Esri/calcite-design-system/pull/9123.
> fix(input-number): restore decimal input mode default

- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #9749
Restores `--calcite-panel-footer-padding`, which was unintentionally removed in https://github.com/Esri/calcite-design-system/pull/9374.
> fix(panel, flow-item): fix footer-padding CSS prop regression

- packages/calcite-components/src/components/tree-item/tree-item.tsx
Marks `indeterminate` as mutable and suppresses `@stencil-eslint/strict-mutable` class until https://github.com/stencil-community/stencil-eslint/issues/111 is fixed.
> chore(tree-item): fix mutable warning `indeterminate` prop

- packages/calcite-components/src/components/tile/tile.scss
- packages/calcite-components/src/components/tile/tile.stories.ts
- packages/calcite-components/src/demos/tile.html
**Related Issue:** [#9540](https://github.com/Esri/calcite-design-system/issues/9540)
This updates the `tile` component to center align `content-top` and `content-bottom` slots when the `alignment` prop is equal to `"center"`
> fix(tile): center align contentTop and contentBottom slots when alignment prop equals "center"

- packages/calcite-components/src/components/shell/resources.ts
- packages/calcite-components/src/components/shell/shell.e2e.ts
- packages/calcite-components/src/components/shell/shell.scss
- packages/calcite-components/src/components/shell/shell.stories.ts
- packages/calcite-components/src/components/shell/shell.tsx
**Related Issue:** [#8269](https://github.com/Esri/calcite-design-system/issues/8269)
Update `calcite-shell` to correctly position `calcite-shell-panel` with `slot="panel-bottom"` at calcite-shell's bottom, when there is no `calcite-shell-panel` with `slot="panel-top"`.
> fix(shell): update shell to correctly position calcite shell panel at shell's bottom

- packages/calcite-components/src/components/tile/tile.scss
**Related Issue:** [#9540](https://github.com/Esri/calcite-design-system/issues/9540)
updates the `tile` component to center align the slot's text when the alignment prop is equal to "center"
> fix(tile): center align slot's text when alignment is equal to center

- packages/calcite-components/support/formatting.ts
Adds CSS counterpart to [`html` formatting helper](https://github.com/Esri/calcite-design-system/pull/1392).
> chore(formatting): add css tagged template function to leverage Prettier formatting

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/flow-item/flow-item.e2e.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.tsx
**Related Issue:** #9769
- adds `beforeClose` property to `panel` and `flow-item`
- allows close to be prevented via a function returning a promise that could be rejected
- adds tests
> feat(panel, flow-item): add beforeClose property

- packages/calcite-components/src/tests/setupTests.ts
- packages/calcite-components/src/utils/config.spec.ts
- packages/calcite-components/src/utils/config.ts
- packages/calcite-components/stencil.config.ts
**Related Issue:** #9721
This updates the message displayed when components load to show the version, build date and revision (similar to Maps SDK). It will log an info message instead of a warning as it could be misinterpreted and would also show up multiple times when a bundled `calcite-components` version would be overridden.
**Note**: `console.info` messages will be omitted by default across all tests to avoid noise
> feat: provide info message on stamped version instead of warning

- packages/calcite-components/src/components/block/block.scss
**Related Issue:** [#9753](https://github.com/Esri/calcite-design-system/issues/9753)
Updates component to have no top padding when `heading` is not defined.
> fix(block): remove top padding when no heading is defined

- packages/calcite-components/src/components/date-picker-day/date-picker-day.scss
- packages/calcite-components/src/components/menu-item/menu-item.scss
- packages/calcite-components/src/components/notice/notice.scss
- packages/calcite-components/src/components/pick-list-item/pick-list-item.scss
- packages/calcite-components/src/components/slider/slider.scss
- packages/calcite-components/src/components/tab-title/tab-title.scss
- packages/calcite-components/src/components/tree-item/tree-item.scss
> style: autofix lint issues

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox-item/resources.ts
- packages/calcite-components/src/components/combobox/combobox.stories.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/combobox/utils.ts
**Related Issue:** #3695
This adds the following enhancements to `combobox`/`combobox-item`:
* `description` prop - displays description below label
* `shortHeading` prop - displays short version of the heading (label) in selection
* `content-end` slot - enables slotting non-interactive elements after the item's content
**Note**: the new props are filterable and also participate in visual matching
> feat(combobox, combobox-item): add `description`, `shortHeading` props and `content-end` slot

- packages/calcite-components/src/components/loader/loader.tsx
- packages/calcite-components/src/components/loader/resources.ts
Consolidates loader part rendering.
> refactor(loader): simplify loader part rendering

- packages/calcite-components/src/components/tab-nav/resources.ts
- packages/calcite-components/src/components/tab-nav/tab-nav.e2e.ts
- packages/calcite-components/src/components/tab-nav/tab-nav.scss
- packages/calcite-components/src/components/tab-nav/tab-nav.tsx
- packages/calcite-components/src/components/tab-title/tab-title.e2e.ts
- packages/calcite-components/src/components/tab-title/tab-title.scss
- packages/calcite-components/src/components/tab/tab.e2e.ts
- packages/calcite-components/src/components/tab/tab.scss
- packages/calcite-components/src/components/tabs/resources.ts
- packages/calcite-components/src/components/tabs/tabs.e2e.ts
- packages/calcite-components/src/components/tabs/tabs.scss
- packages/calcite-components/src/components/tabs/tabs.tsx
> test(tabs, tab-nav, tab-title, tab): add component token E2E tests

- packages/calcite-components/src/components/tooltip/TooltipManager.ts
- packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #9273
- support tap/touch events for tooltip
- cleanup
- removed private vars for hoveredTooltip, clickedTooltip to simplify things
- add test
> feat(tooltip): support touch events

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9796 
This update allows additional data to be set per item to be included for filtering.
> feat(combobox, combobox-item): add `metadata` support for filtering

- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #3695 
This fixes spacing and font-weight to follow the updated spec.
* updates previous internal CSS prop to follow conventions (will follow suit for others in a separate PR)
* ensures selected font weight is only applied to the title/heading
* fixes trailing indent padding
* prevents wrapping of `short-heading`
> fix(combobox-item): tweak center content font-weight and spacing

- package-lock.json
- package.json
[`@types/prettier`](https://www.npmjs.com/package/@types/prettier) is deprecated and no longer needed as Prettier includes types.
> build(deps): drop unnecessary @types/prettier dep

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/input-time-picker/input-time-picker.stories.ts
- packages/calcite-components/src/components/time-picker/time-picker.e2e.ts
- packages/calcite-components/src/components/time-picker/time-picker.stories.ts
- packages/calcite-components/src/components/time-picker/time-picker.tsx
- packages/calcite-components/src/demos/input-time-picker.html
- packages/calcite-components/src/utils/time.spec.ts
- packages/calcite-components/src/utils/time.ts
**Related Issue:** #9720
This PR fixes an issue where a starting time value past noon was not displaying the meridiem first in the `calcite-time-picker`.
> fix(time-picker): render meridiem first for korean locale

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** [#7288](https://github.com/Esri/calcite-design-system/issues/7288)
Update `combobox` to append custom values to top of dropdown list.
> feat(combobox): append custom values to top of dropdown

- packages/calcite-components/src/components/shell/shell.scss
- packages/calcite-components/src/components/shell/shell.tsx
**Related Issue:** #9807
- fixes styles when resizing
- makes non interactive container not suddenly jump full height/width.
- cleanup
> fix(shell): fix resizing a slotted shell-panel when clicking to resize

- packages/calcite-components/src/components/flow-item/flow-item.stories.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/panel/panel.tsx
**Related Issue:** #9855
- prevent footer slots from conflicting
- modify stories
- add doc
> fix(panel, flow-item): prevent footer slots from conflicting with each other

- packages/calcite-components/src/components/tree/tree.e2e.ts
Try to stabilize the tree tests.
Example:
```
@esri/calcite-components:test:   ● calcite-tree › keyboard support › does prevent space/enter keyboard event on actions with selectionMode of none
@esri/calcite-components:test: 
@esri/calcite-components:test:     expected event "keydown" to have been called 1 times, but was called 0 time
@esri/calcite-components:test: 
@esri/calcite-components:test:       1065 |       await page.keyboard.press("Enter");
@esri/calcite-components:test:       1066 |
@esri/calcite-components:test:     > 1067 |       expect(keydownSpy).toHaveReceivedEventTimes(1);
@esri/calcite-components:test:            |                          ^
@esri/calcite-components:test:       1068 |       expect(keydownSpy.lastEvent.defaultPrevented).toBe(true); …
```
> test(tree): stabilize tests

- packages/calcite-components/src/components/pick-list-item/pick-list-item.tsx
- packages/calcite-components/src/components/pick-list/pick-list.tsx
- packages/calcite-components/src/components/value-list-item/value-list-item.tsx
**Related Issue:** #9295
Fixes mismatched component names in deprecation warning.
> chore(pick-list, pick-list-item, value-list-item): fix runtime deprecation messages

- package.json
Prevents `git clean` from removing untracked, non-generated files/dirs from `.gitignore` (e.g., `.idea` 😉)
> chore: avoid deleting untracked, non-generated files on npm run clean

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/action/action.e2e.ts
- packages/calcite-components/src/components/action/action.scss
- packages/calcite-components/src/components/action/action.stories.ts
- packages/calcite-components/src/components/action/action.tsx
**Related Issue:** #3859
- deprecates the compact property
> docs(action): deprecates the compact property

- .github/workflows/issue-notifications.yaml
- package-lock.json
**Related Issue:** #9851
Fixes the case of environment variables in the workflow files, which I made uppercase in the GitHub scripts.
> ci: fix env var case in workflows

- packages/calcite-components/src/components/dialog/dialog.scss
- packages/calcite-components/src/components/dialog/dialog.stories.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/dialog/resources.ts
**Related Issue:** #9869
- adds css var `--calcite-dialog-content-space`
- sets padding on dialog by default
- adds screenshot test
> feat(dialog): add padding to default slot

- packages/calcite-components/.storybook/preview-head.html
- packages/calcite-components/src/components/flow-item/flow-item.stories.ts
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/panel/panel.stories.ts
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/panel/resources.ts
- packages/calcite-components/src/demos/panel.html
**Related Issue:** #9858 #9857
- fixes footer-end slot alignment when its the only thing slotted
- refactor styles
- makes footer slot take precedence over the other footer slots (including deprecated footer-actions)
- add screenshot tests
- cleanup screenshot tests
> fix(panel): correct footer padding and layout

- package-lock.json
Resolve `next` release [CI errors](https://github.com/Esri/calcite-design-system/actions/runs/10149756639/job/28065362229#step:4:77) due to an outdated `package-lock.json`.
> build(deps): update package-lock

- packages/calcite-design-tokens/LICENSE.md
- packages/calcite-design-tokens/package.json
**Related Issue:** https://github.com/Esri/calcite-design-system/pull/9835#discussion_r1688646094
Add license to `@esri/calcite-design-tokens`.
> chore: add license to npm package

- packages/calcite-components/src/components/dialog/dialog.scss
**Related Issue:** #9876
- This corrects an issue with the transform animation on the dialog.  
- The issue is that having a transform animation with a floating-ui element inside of it can cause positioning issues.
- Some notes about it can be read here: https://floating-ui.com/docs/usefloating#transform
- In our case, a wrapper won't work because the floating ui element is inside of the transform animation.
- As a workaround, the transform animation is removed when menuOpen is true.
> fix(dialog): fix menu positioning when when overlayPositioning is 'fixed' and menuOpen is true

- .husky/pre-commit
- package.json
Resolve husky deprecation warnings following their [v9 release notes](https://github.com/typicode/husky/releases/tag/v9.0.1).
> build(deps): resolve husky deprecation warnings

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #9282
Ensure the initial value is within the min/max range. This is in line with the existing behavior, but it is not ideal.
The plan is to stop automatically changing the value to the min/max when it is out of range, and rely on form constraint validation instead. However, doing so would be a breaking change, so it's on hold until v3.
The behavior after this is installed will look the same as the [repro sample](https://codepen.io/benelan/pen/VwOGwZy). The key is to check the value of the component in the form submission callback:
```js
form.onsubmit = (event) => {
console.log(event.target.elements["date-picker"].value);
...
}
```
Here is an [updated repro sample](https://codepen.io/benelan/pen/dyBNVMx?editors=1111).
> fix(input-date-picker): ensure initial value is in range

- .release-please-manifest.json
- package-lock.json
- packages/calcite-components-angular/projects/component-library/CHANGELOG.md
- packages/calcite-components-angular/projects/component-library/package.json
- packages/calcite-components-react/CHANGELOG.md
- packages/calcite-components-react/package.json
- packages/calcite-components/CHANGELOG.md
- packages/calcite-components/package.json
- packages/calcite-components/readme.md
- packages/calcite-ui-icons/CHANGELOG.md
- packages/calcite-ui-icons/package.json
Cherry-pick the release commit from `main`.
---
<details><summary>@esri/calcite-ui-icons: 3.30.0</summary>
[3.30.0](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-ui-icons-v3.29.0...@esri/calcite-ui-icons@3.30.0)
(2024-07-31)
* Add calcite-ui-icons to monorepo
([#9835](https://github.com/Esri/calcite-design-system/issues/9835))
([05264ea](https://github.com/Esri/calcite-design-system/commit/05264ea84d1c0d88d2878c33434a4166f2f5f532))
</details>
<details><summary>@esri/calcite-components: 2.11.0</summary>
[2.11.0](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-components@2.10.1...@esri/calcite-components@2.11.0)
(2024-07-31)
* **chip:** Enhance multi-select group affordance
([#9286](https://github.com/Esri/calcite-design-system/issues/9286)) …
> chore: release main (#9716)

- packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #9731
`delegatesFocus` will only focus elements in the shadow DOM (see [example](https://codepen.io/jcfranco/pen/MWMpaOM)), so this ensures the slotted trigger gets focused.
`focusable` test was incorrectly passing with the pinned version of Puppeteer (21.5.0) for both headless and headful modes. Testing the previous implementation with `puppeteer@22.14.0` (latest) fails the test properly.
> fix(dropdown): ensure `setFocus` focuses the trigger

- CONTRIBUTING.md
- package.json
**Related Issue:** #9938
Running `npm start` from the root of the monorepo will run `npm start` for all of the packages that have a `start` script. Therefore, `npm start` will launch the icon browser in addition to the component demos, now that the `@esri/calcite-ui-components` lives in the monorepo.
This seems to cause timing issues on Windows where the icons are copied to the components before they are all built.
To only launch the component demos, use `npm run start:components`.
> chore: add 'start:components' npm script

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #9719
Ensures the combobox updates items internally when an item's `disabled` property is modified.
> fix(combobox): fix selection of items that were previously disabled

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/block/resources.ts
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/panel/panel.scss
Cherry-pick the following commits to `main` for the 2.11.1 patch.
- **docs(modal): update component deprecation message to v4 (#9925)**
- **fix(panel, flow-item): fix header padding regression (#9936)**
- **fix(block): display correct header spacing when heading or description are present (#9924)**
> chore: cherry-pick patch commits

- lerna.json
**Related Issue:** #9946
Use the exact version (no semver range) when releasing `next` via Lerna to prevent Renovate from creating PRs to pin the version.
> ci(lerna): pin versions

- .release-please-manifest.json
- packages/calcite-components-angular/projects/component-library/CHANGELOG.md
- packages/calcite-components-react/CHANGELOG.md
- packages/calcite-components/CHANGELOG.md
- packages/calcite-components/readme.md
**Related Issue:** #9952
Cherry-pick the release commit from `main`.
---
<details><summary>@esri/calcite-components: 2.11.1</summary>
[2.11.1](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-components@2.11.0...@esri/calcite-components@2.11.1)
(2024-08-02)
* **block:** Display correct header spacing when heading or description
are present
([#9924](https://github.com/Esri/calcite-design-system/issues/9924))
([d8f1077](https://github.com/Esri/calcite-design-system/commit/d8f1077c649f9f45f0db7e00a916a4261cd0adf2))
* **panel, flow-item:** Fix header padding regression
([#9936](https://github.com/Esri/calcite-design-system/issues/9936))
([90e9368](https://github.com/Esri/calcite-design-system/commit/90e93681c6926eec8480c4028f2797046ebd54f4))
</details> …
> chore: release main (#9952)

- .github/workflows/icons-diff-check.yml
Temporarily disable the "Icon Team Diff Check" workflow, which is currently broken. I will re-enable it once I have time to fix it in the next few days.
> chore: temporarily disable broken icon diff check

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
**Related Issue:** #8784
Update focus styles so that they target the focusable element instead of the host, which does not use tabindex currently.
> fix(accordion-item): align focus styles across browsers

- packages/calcite-components/src/components/stepper-item/stepper-item.scss
- packages/calcite-components/src/components/stepper/stepper.stories.ts
**Related Issue:** [#8930](https://github.com/Esri/calcite-design-system/issues/8930)
Update `stepper-item` to take full width when parent `stepper`'s layout is "vertical".
> fix(stepper-item): update component to take full width when parent's layout is "vertical"

- .husky/pre-commit
Husky adds `node_modules/.bin` to path starting in `v9`, so `npx` is no longer required in the hook scripts.
ref: https://github.com/typicode/husky/releases/tag/v9.0.1#how-to-migrate
> ci: new version of husky no longer need npx

- .github/CODEOWNERS
Code owners is requesting review from Franco and I to all pull requests. It might be because we are the first item on the list and there is no catch-all. Hopefully adding a catch-all that assigns no one will fix the issue
> chore: stop requesting review from ben/franco for all PRs

- .github/workflows/contributors.yml
- readme.md
**Related Issue:** #8010
Sets up [akhilmhdh/contributors-readme-action](https://github.com/akhilmhdh/contributors-readme-action) to display contributors in the readme.
> ci: add contributors action

- .github/workflows/icons-diff-check.yml
The Icon Diff Check action was failing on the `pull_request_review` event, because apparently `github.base_ref` isn't defined in its context. The icon team members will only be submitting PRs to `dev`, so I hardcoded the branch name.
> ci: fix icon diff check failures

- packages/calcite-ui-icons/docs/index.html
- release-please-config.json
Bump the version in the UI Icons reference doc via release-please.
> ci: bump version in icon docs

- packages/calcite-components/src/components/input-time-zone/utils.ts
> perf(input-time-zone): improve memory footprint by leveraging browser cache and releasing utils after their use

- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #10042
Fix regression where panel `heading` and `description` retain their line height.
> fix(panel): define heading and description line height

- packages/calcite-components/.storybook/resources.ts
- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/alert/alert.e2e.ts
- packages/calcite-components/src/components/alert/alert.stories.ts
- packages/calcite-components/src/components/alert/alert.tsx
- packages/calcite-components/src/components/alert/interfaces.ts
**Related Issue:** #8705 #8316
- add `queue` property to order an open alert `immediate`, `next` or `last` (default).
- When a `queue="immediate"` alert is opened it is displayed immediately.
- When a `queue="next"` alert is opened it will be displayed after the currently opened one is closed.
- By default, alerts are queued to be `last` when opened.
- When an alert is set to `queue="immediate"` after already being opened it will be presented first.
- Done by unregistering and registering the alert again
- All open alerts not at the top of the stack will be queued and auto close timeout reset
- All other alerts remain in their place.
- cleanup private var names
- add simple story
- add urgent story
- add e2e test
> feat(alert): add 'queue' property to prioritize the ordering of alerts when opened

- package-lock.json
- package.json
- packages/calcite-components/package.json
The `updtr` package is no longer used since we transitioned to a monorepo with renovate.
> build(deps): remove unused updtr package

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/loader/loader.scss
- packages/calcite-components/src/components/loader/loader.stories.ts
- packages/calcite-components/src/components/loader/loader.tsx
**Related Issue:** #8678
Adds new determinate type to allow users to opt-into displaying the progress (percent) label.
**Note:** the current `determinate` type will no longer display a label in a future release.
> feat(loader): add `determinate-value` type

- packages/calcite-components/src/components/accordion/accordion.stories.ts
- packages/calcite-components/src/components/avatar/avatar.stories.ts
- packages/calcite-components/src/components/block/block.stories.ts
- packages/calcite-components/src/components/card-group/card-group.stories.ts
- packages/calcite-components/src/components/card/card.stories.ts
- packages/calcite-components/src/components/carousel/carousel.stories.ts
- packages/calcite-components/src/components/chip/chip.stories.ts
- packages/calcite-components/src/components/list/list.stories.ts
- packages/calcite-components/src/components/navigation-logo/navigation-logo.stories.ts
- packages/calcite-components/src/components/navigation-user/navigation-user.stories.ts
- packages/calcite-components/src/components/shell/shell.stories.ts
- packages/calcite-components/src/components/stack/stack.stories.ts
- packages/calcite-components/src/components/tabs/tabs.stories.ts
- packages/calcite-components/src/components/tile-group/tile-group.stories.ts
- packages/calcite-components/src/components/tile/tile.stories.ts
- packages/calcite-components/src/components/tip-manager/tip-manager.stories.ts
- packages/calcite-components/src/components/tip/tip.stories.ts
- packages/calcite-components/src/components/tooltip/tooltip.stories.ts
Resolves references to placeholder-image after filename change.
> chore(placeholder-image): fix renamed module imports

- .github/scripts/addUnblockedComment.js
**Related Issue:** #10132 
Changes the regex to better match the "Blocked issue:" so that randomly mentioned issues don't get matched and attempted to be unblocked. 
Also, catches the issue not found error in case somehow a issue that doesn't actually exist gets listed as blocked. 
[Codepen to test regex](https://codepen.io/Ditwan-Price/pen/QWXmmRL?editors=0012)
> ci(actions): fix regex, and catch issue not found error on blocked issue action

- .github/workflows/deploy-latest.yml
Attempt to fix the release asset uploading script, which is having errors due to invalid json string syntax. Setting the output to an intermediary env var could be messing up the quotes.
> ci: fix json string escaping for release asset upload

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/flow-item/flow-item.e2e.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/panel/resources.ts
**Related Issue:** #10129
- updates `dialog` and `flow-item` to only listen to panel events for the internal panel. Excluding any other bubbling events.
- uses `IDS` for unique ids of elements instead of `data-test` attributes.
- stops propagation of internal panel events on dialog.
- adds tests
> fix(dialog, flow-item): slotted closable panels should not close the component

- packages/calcite-components/.stylelintrc.json
- packages/calcite-components/src/assets/styles/_animation.scss
- packages/calcite-components/src/assets/styles/_floating-ui.scss
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/alert/alert.scss
- packages/calcite-components/src/components/combobox/combobox.scss
- packages/calcite-components/src/components/dropdown-item/dropdown-item.scss
- packages/calcite-components/src/components/dropdown/dropdown.scss
- packages/calcite-components/src/components/input-date-picker/input-date-picker.scss
- packages/calcite-components/src/components/loader/loader.scss
- packages/calcite-components/src/components/notice/notice.scss
- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/components/progress/progress.scss
- packages/calcite-components/src/components/stepper/stepper.scss
- packages/calcite-components/src/components/tooltip/tooltip.scss
- packages/calcite-components/src/components/tree-item/tree-item.scss
**Related Issue:** #7365
Refactor sass names to kebab-case.
> refactor(stylelint): refactor to and enforce kebab-casing for Sass utilities

- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #9387
- creates `dateTimeFormat` on connectedCallback to prevent console error from occurring.
> fix(input-date-picker): prevent console error when using a lang

- packages/calcite-components/src/components/functional/ExpandToggle.tsx
- packages/calcite-components/src/components/functional/FloatingArrow.tsx
- packages/calcite-components/src/components/functional/Heading.tsx
- packages/calcite-components/src/components/functional/Validation.tsx
- packages/calcite-components/src/components/functional/XButton.tsx
- packages/calcite-components/src/components/rating/functional/star.tsx
- packages/calcite-components/src/components/stepper/functional/step-bar.tsx
- packages/calcite-components/src/utils/form.tsx
- packages/calcite-components/src/utils/interactive.tsx
Fixes functional component types and also renames corresponding prop interfaces. 
Thanks, @maxpatiiuk!
> refactor: fix `FunctionalComponent` return types

- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
`describe` block was unintentionally added in https://github.com/Esri/calcite-design-system/pull/7584.
> chore(segmented-control): remove empty and irrelevant `describe` block

- release-please-config.json
- Use absolute path instead of relative as recommended in <https://github.com/googleapis/release-please/issues/2064#issuecomment-1714211105>
- Fix a syntax issue in the `jsonpath` to the extra files. The library they use is [different than the original](https://github.com/dchester/jsonpath?tab=readme-ov-file#other-minor-differences) I've used in the past. Specifically:
> non-ascii non-word characters are no-longer valid in member identifier names; use quoted subscript strings instead (e.g., `$['$']` instead of `$.$`)
> ci(release): fix jsonpath syntax for updating extra files

- packages/calcite-components/src/components/list-item/list-item.scss
**Related Issue:** #9290
Decreases horizontal space in selection modes that affects users
migrating from pick/value-list.
> fix(list-item): decrease horizontal spacing between selection icon and content (#9304)

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/modal/modal.tsx
**Related Issue:** #10194
Restores modal's component JSDoc placement to fix generated doc. #9751 placed it above the logger call, which changed the documentation target.
> docs(modal): restore component-level doc

- packages/calcite-components/.stylelintrc.json
**Related Issue:** #10188 
The Sass compiler does not error on unknown functions, but we can use Stylelint's [`function-no-unknown`](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown) to ensure function names are properly referenced.
> chore(linting): enable `scss/function-no-unknown` rule

- patches/@types+jsdom+21.1.7.patch
This resolves the following warning:
```bash
> calcite-design-system@0.0.0 postinstall
> patch-package
patch-package 8.0.0
Applying patches...
@types/jsdom@21.1.6 ✔
Warning: patch-package detected a patch file version mismatch
Don't worry! This is probably fine. The patch was still applied
successfully. Here's the deets:
Patch file created for
@types/jsdom@21.1.6
applied to
@types/jsdom@21.1.7
At path
node_modules/@types/jsdom
This warning is just to give you a heads-up. There is a small chance of
breakage even though the patch was applied successfully. Make sure the package
still behaves like you expect (you wrote tests, right?) and then run
patch-package @types/jsdom
to update the version in the patch file name and make this warning go away.
---
patch-package …
```
> chore: update patch for jsdom@21.1.7

- packages/calcite-components/src/utils/floating-ui.spec.ts
- packages/calcite-components/src/utils/floating-ui.ts
- packages/calcite-components/stencil.config.ts
chore: only call getElementDir once when positioning floating-ui elements
> refactor: only call getElementDir once when positioning floating-ui elements

- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #10238
Fixes a regression caused by #10141 where clicks on scrollers would show the focus outline. 
* this behavior aligns with Chrome/Firefox's latest default focus on scrolling content behavior
* `:focus-visible` [isn’t supported in Safari 15.0 - 15.3](https://caniuse.com/?search=focus-visible), but given Safari 18 is expected this year, this is a minor visual inconsistency for unsupported versions.
* cleans up focus styles that should have been updated by #10141.
* no tests were added as we currently don't cover interactive focus-related styling
> fix(panel, flow-item): hide focus-outline when scrolling via mouse to align with browsers

- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
**Related Issue:** #10227
Re-skip unstable test (see #10226).
Unfortunately, https://github.com/Esri/calcite-design-system/pull/10228 didn't stabilize this test.
> test(input-time-picker): skip unstable test

- packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #8368 
`input-date-picker` no longer emits `calciteInputDatePickerChange` event when `valueAsDate` is set programmatically.
> fix(input-date-picker): no longer emits `calciteInputDatePickerChange` event when `valueAsDate` is set programmatically

- packages/calcite-components/src/tests/commonTests/openClose.ts
Removes `beforeToggle` option as it is not being used by any test.
**Note:** It appears this option has not been used since it was introduced by https://github.com/Esri/calcite-design-system/pull/7379.
> refactor(openClose): drop unused test helper options

- .github/scripts/addEsriProductLabel.js
**Related Issue:** #10011 
The original issue was for fixing the action not successfully adding the priority label to a newly created issue. It looks like the reason that wasn't working was because the action would fail before getting to that step. 
The failure was caused by the `addEsriProductLabel` step of the action expecting there to always be an "Esri team" line in the issue body but that's not the case for all issue types.
This is just a small change to stop the failure and instead log a message when the "Esri team" is not present on an issue and continue to the next steps.
> ci(actions): fix adding labels action failing on issues without "Esri team" line

- packages/calcite-components/src/components/input-date-picker/input-date-picker.stories.ts
Refactors `input-date-picker` stories to use `min/max` attributes instead of `start/end`.
> refactor(input-date-picker): update stories to use min/max attributes

- packages/calcite-components/src/components/action-menu/action-menu.tsx
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/split-button/split-button.tsx
**Related PR:** https://github.com/Esri/calcite-design-system/pull/10249#discussion_r1752547649
Update the `flipPlacements` property description across the design system for consistency and clarity. 
Includes the following components:
- action-menu
- combobox
- dropdown
- input-date-picker
- popover
- split-button
> docs(action-menu, combobox, dropdown, input-date-picker, popover, split-button): update flipPlacements description for consistency

- packages/calcite-components/.eslintrc.cjs
- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/color-picker-swatch/color-picker-swatch.tsx
- packages/calcite-components/src/components/functional/Heading.tsx
- packages/calcite-components/src/components/loader/loader.tsx
- packages/calcite-components/src/components/pick-list/shared-list-render.tsx
- packages/calcite-components/src/components/rating/functional/star.tsx
**Related Issue:** #10236
Moves away from JSX attribute spreading pattern.
This also enables [`react/jsx-props-no-spreading`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md) to prevent the spread of future spreading (🥁🐍)
> refactor: avoid and prevent spread attribute usage

- .husky/pre-commit
This updates our pre-commit hook to check SVG icons to make sure they follow the icon naming convention:
* `<iconName>-<size>.svg`.
* `<iconName>-<size>-f.svg`.
If an icon about to be committed does not match this format, the commit will fail and be canceled.
> chore(icons): ensure UI icons follow naming convention

- packages/calcite-components/stencil.config.ts
**Related Issue:** #10219
This reverts commit 2305cc80a1b3ea13f4033e0355813ac38e7c6596 as it did not help stabilize tests as expected (see https://github.com/Esri/calcite-design-system/pull/10232#issuecomment-2342596324).
> revert: "chore: set default page size for E2E tests (#10219)"

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/button/button.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/functional/FloatingArrow.tsx
- packages/calcite-components/src/components/handle/handle.e2e.ts
- packages/calcite-components/src/components/link/link.tsx
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/rating/rating.tsx
- packages/calcite-components/src/components/tooltip/tooltip.tsx
- packages/calcite-components/src/utils/floating-ui.ts
- packages/calcite-components/src/utils/form.tsx
- packages/calcite-components/src/utils/selectableComponent.ts
- packages/eslint-plugin-calcite-components/src/rules/require-event-emitter-type.ts
- packages/eslint-plugin-calcite-components/src/rules/strict-boolean-attributes.ts
With the changes in this PR, after running the codemod, there are only 60 TypeScript errors in the Calcite package - those should be best fixed manually after running the codemod.
Now that error count is down to negligible level, will work on migrating tests.
> refactor: fixup typescript errors

- packages/calcite-components/src/demos/_assets/head.ts
- packages/calcite-components/src/demos/input-time-picker.html
- packages/calcite-components/src/demos/menu.html
- packages/calcite-components/src/demos/navigation.html
Extracts demo page cleanup from https://github.com/Esri/calcite-design-system/pull/10295.
> chore: tidy up demo pages

- packages/calcite-components/src/components/popover/popover.tsx
**Related Issue:** #10353
- connect and disconnect mutation observer
> fix(popover): update focus trap elements on mutation observer

- packages/calcite-components/src/components/action/action.tsx
- packages/calcite-components/src/components/action/assets/action/t9n/messages.json
- packages/calcite-components/src/components/action/assets/action/t9n/messages_en.json
**Related Issue:** #9071
- check in new string
> chore(action): add new string for accessible indicator label

- .github/ISSUE_TEMPLATE/accessibility.yml
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/8724
Adds a reference to the foundational [accessibility page](https://developers.arcgis.com/calcite-design-system/foundations/accessibility) to the accessibility issue template, where additional a11y guidance, including new context to focus, visible focus and no keyboard trap will be provided to developers.
> docs(a11y): add reference to a11y guidance to issue template

- packages/calcite-components/src/components/action/action.tsx
**Related Issue:** #7775
- only set `disabled` on action, not `aria-disabled` since it is redundant.
> fix(action): prefer `disabled` in favor of `aria-disabled`

- .husky/pre-commit
- .husky/pre-push
- support/updateStylelintCustomSassFunctions.ts
Resolve a few errors in our `pre-commit` and `pre-push` hooks:
1. The `support/updateStylelintCustomSassFunctions.ts` script was trying to open scss files in the root directory.
```text
Error reading file: /home/jamin/dev/work/calcite-design-system/dev/ComponentWithSass.scss
Error: ENOENT: no such file or directory, open '/home/jamin/dev/work/calcite-design-system/dev/ComponentWithSass.scss'
at Object.readFileSync (node:fs:448:20)
at <anonymous> (/home/jamin/dev/work/calcite-design-system/dev/support/updateStylelintCustomSassFunctions.ts:37:24)
at Array.forEach (<anonymous>)
at sassFiles (/home/jamin/dev/work/calcite-design-system/dev/support/updateStylelintCustomSassFunctions.ts:35:11)
at Object.<anonymous> (/home/jamin/dev/work/calcite-design-system/dev/support/updateStylelintCustomSassF …
```
> ci: resolve husky pre-push and pre-commit errors

- packages/calcite-components/src/components/panel/panel.scss
- focus-base is defined twice on a class.
- showed up in VSCode lint
> refactor(panel): remove duplicate tailwind class

- packages/calcite-components/src/components/chip-group/chip-group.e2e.ts
- packages/calcite-components/src/components/chip/chip.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/functional/XButton.tsx
- packages/calcite-components/src/components/list-item-group/list-item-group.tsx
- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/loader/loader.tsx
- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/table/table.tsx
- packages/calcite-components/src/components/text-area/text-area.e2e.ts
- packages/calcite-components/src/components/time-picker/time-picker.tsx
- packages/calcite-components/src/tests/commonTests/t9n.ts
- packages/calcite-components/src/utils/dom.spec.ts
- packages/calcite-components/src/utils/interactive.tsx
Run the migration script on tests.
This PR includes some small fixups that affect TypeScript typings to reduce number of TypeScript errors after the codemod.
With these changes, there are only 57 TypeScript error in the entire calcite-components package after the codemod!
> refactor(tests): reduce TypeScript errors

- packages/calcite-components/src/components/pick-list/pick-list.tsx
- packages/calcite-components/src/components/pick-list/shared-list-render.tsx
- packages/calcite-components/src/components/value-list/value-list.tsx
Lumina does not have a `<Host>` element, but there is an equivalent syntax.
The codemod can take care of migrating to the alternative syntax, as long as the `<Host>` element appears in the `render()` methods.
This PR moves the `<Host>` element from the `<List>` functional component into the parent `render()` methods.
With this change, all `<Host>` elements in Calcite's codebase are migrated automatically.
> refactor: do not use Host in functional components

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #8720
- add fix for selecting items with the same value
- add e2e test
> fix(combobox): selection-mode="single-persist" correctly selects an item when items have same values

- packages/calcite-components/src/components/action-pad/action-pad.scss
- packages/calcite-components/src/components/action-pad/action-pad.stories.ts
**Related Issue:** #10307
Removes an extra border-block-end which was causing a layout bug
> fix(action-pad): fix horizontal action group alignment

- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/segmented-control/segmented-control.tsx
**Related Issue:** #9955
- Use slotchange event to get items and update them when necessary
- No need for the mutation observer
- add e2e test
> fix(segmented-control): honor appearance, layout and scale when items are added after initialization

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/popover/popover.e2e.ts
- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/utils/floating-ui.ts
Apply `popover` component tokens `--calcite-popover-background-color` and `--calcite-popover-border-color` to `floating arrow`.
> feat(popover): apply component tokens to arrow

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/alert/alert.e2e.ts
- packages/calcite-components/src/components/alert/alert.scss
- packages/calcite-components/src/custom-theme/alert.ts
**Related Issue:** [#7180](https://github.com/Esri/calcite-design-system/issues/7180)
-Apply `calcite-alert-corner-radius` to internal close button.
-Make queue count's container background-color transparent.
> feat(alert): apply --calcite-alert-corner-radius to internal close button

- packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json
- packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages_en.json
- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
- packages/calcite-components/src/components/input-time-zone/interfaces.d.ts
- packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #10289
This addresses some issues that came up from #10345.
* use combobox-item metadata for filtering
* fix Ho Chi Minh City label
* fix selection bug that would cause rendering quirks
* sort GMT locales numerically
* sort time zone group items
* there's a small delay after selection for the country label to be rendered, I'll create a follow-up PR to improve this (#10310 might help with this)
* we could also explore an option in combobox to make it easier to update the selected item's label between open/close states. cc @ashetland
> fix(input-time-zone): fix region mode quirks after update

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/tooltip/TooltipManager.ts
- packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #10416
- track clicked tooltip to stop hovering until the tooltip is hovered off of
- add e2e test
> fix(tooltip): closed tooltips should not reappear

- .github/workflows/pr-semantic.yml
Updates our semantic PR check to allow the new commit type added in https://github.com/Esri/calcite-design-system/pull/10346.
> chore(actions): add custom `deprecate` type to semantic-pr check

- packages/eslint-plugin-calcite-components/docs/enforce-ref-last-prop.md
- packages/eslint-plugin-calcite-components/src/rules/enforce-ref-last-prop.ts
**Related Issue:** #10398
Deprecates this rule for 3.x removal as it is no longer needed after Stencil 4.14.1 and will be even more obsolete after #10310.
> deprecate: deprecate `enforce-ref-last-prop` rule

- packages/calcite-components/src/assets/styles/_host.scss
- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/components/tip-manager/tip-manager.scss
**Related Issue:** #10347
Updates styles to avoid [mixed declaration](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) warnings that will show up after #10310.
> refactor: prevent mixed Sass mixed declaration warnings

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/components/action-bar/action-bar.scss
- packages/calcite-components/src/components/action-group/action-group.scss
- packages/calcite-components/src/components/action-pad/action-pad.scss
- packages/calcite-components/src/components/action/action.scss
- packages/calcite-components/src/components/avatar/avatar.scss
- packages/calcite-components/src/components/card-group/card-group.scss
- packages/calcite-components/src/components/card/card.scss
- packages/calcite-components/src/components/chip/chip.scss
- packages/calcite-components/src/components/icon/icon.scss
- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/components/progress/progress.scss
- packages/calcite-components/src/components/text-area/text-area.scss
Provide consistency and alignment in our docs across the design system for component design tokens, also in alignment with our [component token example PR](https://github.com/Esri/calcite-design-system/pull/10058). 📚
> docs: component token description consistency

- packages/calcite-components/src/tests/commonTests/themed.ts
**Related Issue:** #10389
We can restore this later if needed.
> refactor(themed): drop broken, unused, regexp arg support

- packages/calcite-components/src/components/functional/Heading.spec.tsx
**Related Issue:** #10349
Adds stopgap `VNode`/rendering assertion util to `Heading.spec.tsx`. Once #10310 lands, we can revisit this and use better test tooling.
> test(heading): avoid `newSpecPage` usage to ease Lumina migration

- packages/calcite-components/src/components/card/card.e2e.ts
> test(card): remove redundant spy and setup wrapper element

- packages/calcite-components/src/components/alert/alert.e2e.ts
- packages/calcite-components/src/components/button/button.e2e.ts
- packages/calcite-components/src/components/chip/chip.e2e.ts
**Related Issue:** #10369 
This updates `getComputedStyle` args to:
* use `::after` vs `:after`
* remove invalid pseudoclass args (only pseudo-elements are supported)
> test: fix `window.getComputedStyle` arguments

- packages/calcite-components/src/components/dialog/dialog.stories.ts
- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #10385
Slotted content will now adjust its size and position to allow more flexible layouts, similar to how content behaves in `modal`.
> feat(panel): improve panel header layout

- packages/calcite-components/src/components/alert/alert.tsx
- simplify setFocus method focusing
> refactor(alert): simplify setFocus method

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.tsx
> fix(block): fix rendering tied to named-slot content

- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
> fix(combobox-item): fix rendering tied to named-slot content

- packages/calcite-components/src/components/notice/notice.tsx
> fix(notice): fix rendering tied to named-slot content

- packages/calcite-components/src/components/accordion-item/accordion-item.tsx
> fix(accordion-item): fix rendering tied to named-slot content

- packages/calcite-components/src/components/action-bar/action-bar.tsx
- packages/calcite-components/src/components/action-group/action-group.tsx
- packages/calcite-components/src/components/action-pad/action-pad.tsx
- packages/calcite-components/src/components/shell-panel/shell-panel.tsx
- packages/calcite-components/src/components/shell/shell.tsx
- removes `ConditionalSlotComponent` and helpers on components that no longer need them.
- these components do not use getSlotted any longer so these should not be necessary
> refactor(action-bar, action-group, action-pad, shell, shell-panel): remove conditional slot component where not necessary

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/input-number/input-number.e2e.ts
- packages/calcite-components/src/components/input-number/input-number.tsx
- packages/calcite-components/src/components/input-text/input-text.e2e.ts
- packages/calcite-components/src/components/input-text/input-text.tsx
- packages/calcite-components/src/components/input/input.e2e.ts
- packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #6059 #10055
- removes getSlotted util usage
- removes setting slotted buttons to be disabled
- removed applicable tests
> fix(input, input-number, input-text): should not set slotted actions to be disabled

- packages/calcite-components/src/components/inline-editable/inline-editable.tsx
- replace with `slotchange` event 
> fix(inline-editable): fix rendering tied to default slot content

- packages/calcite-components/src/components/shell-center-row/shell-center-row.e2e.ts
- packages/calcite-components/src/components/shell-center-row/shell-center-row.tsx
> fix(shell-center-row): fix rendering tied to named-slot content

- packages/calcite-components/src/components/modal/modal.e2e.ts
- packages/calcite-components/src/components/modal/modal.tsx
> fix(modal): fix rendering tied to named-slot content

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/components/tip/resources.ts
- packages/calcite-components/src/components/tip/tip.scss
- packages/calcite-components/src/components/tip/tip.tsx
- packages/calcite-components/src/demos/tip-manager.html
- packages/calcite-components/src/demos/tip/basic.html
> fix(tip): fix rendering tied to named-slot content

- packages/calcite-components/src/components/stepper/stepper.tsx
- packages/calcite-components/src/components/tab-nav/tab-nav.tsx
- packages/calcite-components/src/utils/openCloseComponent.spec.ts
- packages/calcite-components/src/utils/openCloseComponent.ts
**Related Issue:** #10348
We've been using `readTask` in a few places to ensure proper timing for DOM reads w/o triggering layout thrashing. Looking at [the implementation](https://github.com/ionic-team/stencil/blob/7ede77a873486b5cf47f0b26571f852675f67dd6/src/client/client-task-queue.ts#L23), we might be able to get close or similar behavior by using `requestAnimationFrame`.
> refactor: use `requestAnimationFrame` to replace `readTask`

- packages/calcite-components/src/components/stepper-item/stepper-item.scss
**Related Issue:** [#10000](https://github.com/Esri/calcite-design-system/issues/10000)
-Add `bg-foreground-3` to the component's `active` state.
> feat(stepper-item): update component's active state background color.

- .vscode/extensions.json
Adds the [`cssrem`](https://marketplace.visualstudio.com/items?itemName=cipchk.cssrem) extension to display unit conversions within the editor. This will help avoid adding comments for unit conversions (see https://github.com/Esri/calcite-design-system/pull/10179#discussion_r1752943775).
> chore: add cssrem VSCode extension recommendation

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
**Related Issue:** #10500
- no longer apply transform styling unless dragEnabled or resizable
- add e2e test
> fix(dialog): no longer apply transform styling unless dragEnabled or resizable

- packages/calcite-components/src/components/shell-center-row/shell-center-row.tsx
**Related Issue:** #10506 
Adds deprecation context to `shell-center-row` with our logger messaging and a `@deprecated` reference in the component's .tsx file.
> docs(shell-center-row): add logger + component deprecation context

- packages/calcite-components/src/components/pagination/pagination.scss
**Related Issue:** [#9991](https://github.com/Esri/calcite-design-system/issues/9991)
- Add `2px` gap between all of the component's elements.
- Update chevron icon on `:hover` and `:pressed` to `text-color-1` (currently `brand`).
- Update `background-color` on `:pressed` to `bg-foreground-3`.
- Update inactive page `:pressed` to `text-color-1` and `bg-foreground-3`.
- Increase active state `:focus` `bottom-border` to `4px`.
> feat(pagination): enhance component's interactive states

- packages/calcite-components/src/components/stepper-item/stepper-item.scss
**Related Issue:** [#10000](https://github.com/Esri/calcite-design-system/issues/10000)
Add `bg-foreground-3` to the component's `active` state.
> feat(stepper-item): update component's active state background color

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/combobox/resources.ts
**Related Issue:** #10156
Restores `filterText` when filtered items are empty.
> fix(combobox): restores `filterText` when filtered items are empty

- packages/calcite-components/src/components/notice/notice.e2e.ts
- packages/calcite-components/src/components/notice/notice.scss
- packages/calcite-components/src/tests/commonTests/openClose.ts
- packages/calcite-components/src/tests/commonTests/themed.ts
- packages/calcite-components/src/tests/utils.ts
**Related Issue:** #10516
Fixes regression introduced by https://github.com/Esri/calcite-design-system/commit/7e2764f13a95cbf6488596a1f11a9964970883c2#diff-eef7cf73b4f6571be27053eba0e491f478a9569a26f5f2571a590a18bebfc591.
* updates `openClose` test helper with option to assert on collapsed layout
* adds util to get `ElementHandle` and updates applicable tests
> fix(notice): ensure closed notice does not affect layout

- packages/calcite-components/src/components/input-text/input-text.tsx
- packages/calcite-components/src/components/input/input.tsx
- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #9148 
Adds support for `spellcheck` property.
`spellcheck` property is a global attribute. Please refer the spec [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)
> feat(input,input-text,text-area): support `spellcheck` property

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/chip/chip.scss
**Related Issue:** #10428
Mitigates the --calcite-chip-close-icon-color token inconsistency.
> fix(chip): fix close icon color inconsistency

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/components/pagination/pagination.e2e.ts
- packages/calcite-components/src/components/pagination/pagination.scss
- packages/calcite-components/src/components/pagination/pagination.tsx
- packages/calcite-components/src/components/pagination/resources.ts
**Related Issue:** [#10513](https://github.com/Esri/calcite-design-system/issues/10513)
Remove the 2px gap at the start and end of component.
> feat(pagination): remove gap at start and end of component.

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/components/list-item-group/list-item-group.tsx
- packages/calcite-components/src/components/list-item/list-item.scss
- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/list-item/resources.ts
- packages/calcite-components/src/components/list/list.scss
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #10495
- use aria attributes and role instead of semantic elements
- This is because table elements need to have their child elements as direct children.
- Visual changes are due to not using `td` elements anymore which shifts `1px` padding. Seems ok to me 👍  Probably shouldn't have been there. Was coming from default browser td styles.
> refactor(list): use roles instead of table elements

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/components/chip/chip.scss
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/combobox/resources.ts
- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.stories.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/notice/notice.e2e.ts
- packages/calcite-components/src/components/notice/notice.scss
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/shell-center-row/shell-center-row.tsx
- packages/calcite-components/src/tests/commonTests/openClose.ts
- packages/calcite-components/src/tests/commonTests/themed.ts
- packages/calcite-components/src/tests/utils.ts
Cherry-pick the following patch commits to `main`:
- **docs(accordion-item): fix deprecation tag (#10479)**
- **fix(dialog): no longer apply transform styling unless dragEnabled or resizable (#10503)**
- **docs(shell-center-row): add logger + component deprecation context (#10507)**
- **fix(combobox): restores `filterText` when filtered items are empty (#10498)**
- **fix(notice): ensure closed notice does not affect layout (#10518)**
- **fix(chip): fix close icon color inconsistency (#10493)**
- **revert(panel): revert relative positioning on content (#10496)**
> [!IMPORTANT]
> This PR must be rebase-merged
> chore: cherry-pick patch commits to main

- packages/calcite-ui-icons/docs/app.js
Fixes [https://github.com/Esri/calcite-design-system/security/code-scanning/47](https://github.com/Esri/calcite-design-system/security/code-scanning/47)
To fix the problem, we need to ensure that any user-controlled data assigned to `innerHTML` is properly sanitized or escaped to prevent XSS attacks. The best way to fix this issue is to use `textContent` instead of `innerHTML` for setting plain text content. This will ensure that any special characters in the `key` variable are treated as text and not as HTML.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: fix code scanning alert no. 47: DOM text reinterpreted as HTML

- packages/calcite-ui-icons/docs/app.js
Fixes [https://github.com/Esri/calcite-design-system/security/code-scanning/48](https://github.com/Esri/calcite-design-system/security/code-scanning/48)
To fix the problem, we need to ensure that any data taken from the DOM and used in constructing URLs or setting `innerHTML` is properly sanitized or escaped. Specifically, we should:
1. Escape any special characters in the `data-icon` attribute value before using it.
2. Use textContent instead of innerHTML where possible to avoid interpreting the content as HTML.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: fix code scanning alert no. 48: DOM text reinterpreted as HTML

- packages/calcite-components/src/components/shell-center-row/shell-center-row.tsx
**Related Issue:** #10563
Moves deprecation warnings to show when `shell-center-row` is added to the DOM and initially loaded.
This warning was being shown due to [bundling](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/stencil.config.ts#L76).
> fix(shell-center-row): ensure deprecation warning doesn’t show when using standalone `shell` or `shell-panel`

- packages/calcite-components/src/components/inline-editable/assets/inline-editable/t9n/messages.json
- packages/calcite-components/src/components/inline-editable/assets/inline-editable/t9n/messages_en.json
- packages/calcite-components/src/components/inline-editable/inline-editable.e2e.ts
- packages/calcite-components/src/components/inline-editable/inline-editable.tsx
**Related Issue:** #10536
- add `title` attribute for controls
- change message text to remove "click to"
- add test
> fix(inline-editable): add tooltips for controls

- packages/eslint-plugin-calcite-components/docs/require-event-emitter-type.md
- packages/eslint-plugin-calcite-components/src/rules/require-event-emitter-type.ts
**Related Issue:** #10398
Deprecates this rule for 3.x removal as it is no longer needed after #10310.
> deprecate: deprecate `require-event-emitter-type` rule

- packages/eslint-plugin-calcite-components/docs/ban-props-on-host.md
- packages/eslint-plugin-calcite-components/src/rules/ban-props-on-host.ts
**Related Issue:** #10398
Deprecates this rule for 3.x removal as it is no longer needed after #10310.
> deprecate: deprecate `ban-props-on-host` rule

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/components/navigation/navigation.e2e.ts
- packages/calcite-components/src/components/navigation/navigation.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/navigation.ts
Add the following component-scoped CSS Variables to `calcite-navigation`:
`--calcite-navigation-background-color`: Specifies component's background color.
Deprecates following component-scoped CSS variables in `calcite-navigation`:
`--calcite-navigation-background`
> feat(navigation): add component tokens

- .github/workflows/contributors.yml
**Related Issue:** #8010 
Spent way too long hunting down a solution to a generic "Error: Not found" error message and found nothing, but it turned out to be just a case sensitive default path 🤦 so this should fix it. 🤞 
(Tested in my test repo)
> ci(actions): fix contributor list action failing

- packages/calcite-components/src/components/alert/alert.tsx
- packages/calcite-components/src/components/button/button.tsx
- packages/calcite-components/src/components/link/link.tsx
- packages/calcite-components/src/components/notice/notice.tsx
- packages/calcite-components/src/components/tab-title/tab-title.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/10658
Combines separate JSDoc blocks into one to improve parsing in VSCode and Lumina
> docs: fixup invalid JSDoc blocks

- packages/calcite-components/src/components.d.ts
- packages/calcite-components/src/demos/validation.html
- packages/calcite-components/src/tests/commonTests/formAssociated.ts
- packages/calcite-components/src/utils/dom.ts
- packages/calcite-components/src/utils/form.tsx
**Related Issue:** #10482
Resolve the `validationIcon` issue brought up in https://github.com/Esri/calcite-design-system/pull/10509#discussion_r1792823363
The only properties affected by the change in how boolean properties are reflected are `icon`, `validationIcon`, and `download`. This PR fixes the utils that caused issues with `icon` and `validationIcon`. The `download` property seems to already be correct, for example:
https://github.com/Esri/calcite-design-system/blob/25319998739c3af17a5438d285c5931ea656285d/packages/calcite-components/src/components/link/link.tsx#L178
> refactor: handle stencil vs lumina boolean reflection differences

- packages/calcite-components/src/components/sort-handle/sort-handle.scss
**Related Issue:** #7537
- adjust icon color to use border-input color.
> fix(sort-handle): adjust icon color

- packages/calcite-components/src/components/table-header/table-header.tsx
- packages/calcite-components/src/components/table-row/table-row.tsx
- packages/calcite-components/src/components/table/table.e2e.ts
- packages/calcite-components/src/components/table/table.tsx
- packages/calcite-components/src/tests/commonTests/accessible.ts
**Related Issue:** #10495
Split up table rendering to bypass HTML parser corrections that would break functionality and styling.
> refactor(table): refactor internals to work around HTML parser issue

- packages/calcite-components/src/components/action-group/action-group.tsx
- packages/calcite-components/src/components/input/input.tsx
- packages/calcite-components/src/components/menu/menu.tsx
**Related Issue:** #10394
This uses `focusFirstTabbable` to ensure focus works properly.
> fix(action-group, input, menu): fix `setFocus` issues in Chrome 128+

- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.e2e.ts
- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
Avoids imports from `components.d.ts`
> refactor(date-picker-month-header, sort-handle): fix imports

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/refactor.yml
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/10634#issuecomment-2458156607
Add the `@esri/calcite-ui-icons` package to our bug and refactor templates.
> docs: add calcite-ui-icons package to issue templates

- packages/calcite-components/src/components/popover/popover.scss
- No longer necessary since the internal element is hidden when closed now
> refactor(popover): remove unnecessary CSS

- packages/calcite-components/src/components/tooltip/TooltipManager.ts
**Related Issue:** #10715
- fixes closeOnClick for the Safari browser
> fix(tooltip): fix closeOnClick property in Safari

- packages/calcite-components/src/components/dialog/dialog.stories.ts
- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #10095 
Fixes layout issues in dialog and panel content area.
This reverts commit 239f4da406920fcb3c4019573ccf3605903f954a.
> fix(dialog, panel): restore relative positioning in content area

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
**Related Issue:** #4012 
Removes pt-0 from .content to allow spacing between the header-content and content.
> feat(accordion-item): custom header and content spacing tokens

- packages/calcite-components/vite.config.ts
**Related Issue:** #10761
Fixes build issues caused by non-ESM dependencies being externalized by default.
cc @dasa @maxpatiiuk
> fix: bundle-in non-ESM dependencies

- package-lock.json
- packages/calcite-components/package.json
Adds [`@floating-ui/utils`](https://www.npmjs.com/package/@floating-ui/utils) as a dep, which is required by [`composed-offset-position`](https://www.npmjs.com/package/composed-offset-position).
This should address Yarn install errors.
cc @ffaubry
> build(deps): add `@floating-ui/utils` dep

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.tsx
**Related Issue:** #8697 
- Adds `label` property as required to provide context for AT users.
- `heading` is no longer a required property.
BREAKING CHANGE: The component's `label` property is a required property and `heading` is an optional property.
> feat(block)!: add required label property and mark heading as optional

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/combobox/interfaces.ts
- packages/calcite-components/src/components/list-item/interfaces.d.ts
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #9615 
Updates components to only filter known-visibly-rendered properties. 
BREAKING CHANGE: Filtering will no longer include item values by default. If value-filtering is desired, developers will need to configure items' `metadata` property.
> fix(combobox, list)!: stop filtering on value by default

- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/components/split-button/split-button.tsx
**Related Issue:** #7547 
Updates components to no longer close a component when disabled.
BREAKING CHANGE: Components will no longer close automatically when disabled. Developers relying on this behavior will also need to update the `open` property as well.
> refactor(combobox, dropdown, input-date-picker, input-time-picker, split-button)!: avoid modifying `open` based on `disabled` prop

- packages/calcite-components/src/components/checkbox/checkbox.tsx
**Related Issue:** #9713
This property is no longer needed since the `connectForm` utility takes the place of the previous implementation that required rendering a native `input` element that needed a unique id set with the `guid` utility to enable native form submission.
BREAKING CHANGE: Removes the deprecated `guid` property from `calcite-checkbox`.
Migration plan: Developers may need to replace `calcite-checkbox`'s "guid" property with a unique "id" property.
> refactor(checkbox)!: remove deprecated guid property

- packages/calcite-components/src/components/table/table.stories.ts
- packages/calcite-components/src/components/table/table.tsx
**Related Issue:** #9713
BREAKING CHANGE: Removes the deprecated property `zebra` from `calcite-table`.
Developers will need to replace `calcite-table`'s "zebra" property with "striped".
> refactor(table)!: remove deprecated zebra property

- packages/calcite-components/src/components/color-picker-hex-input/color-picker-hex-input.tsx
- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.tsx
- packages/calcite-components/src/components/date-picker-month/date-picker-month.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #10803
Subtly change the JSON type imports to encourage TypeScript to inline these in the final .d.ts files, rather than preserve them as `.json` imports.
Opened an issue 2047 in AWC to add a build-time error if any .json import appears in the public .d.ts file. We can extend that as needed
> fix(t9n): make TypeScript inline .json type imports

- packages/calcite-components/src/components/flow-item/flow-item.tsx
**Related Issue:** #10801
Restores internal prop that was unintentionally made private by #10482.
> fix(flow-item): fix TS error caused by FlowItemLike type

- packages/calcite-components/.storybook/main.ts
#10482 caused a break in our GitHub deployment. This fix addresses it by:
* Adding a `.nojekyll` file to the pages folder to prevent files with leading underscores in their names from being excluded (see https://github.blog/news-insights/bypassing-jekyll-on-github-pages/).
* Moving the internal-testing notice to the preview head to leverage the lazy-loaded components in the preview.
* We can revisit restoring this in the manager head after https://github.com/storybookjs/builder-vite/issues/486 is resolved.
> chore: fix storybook GH pages deployment

- packages/calcite-components/src/components/action-group/action-group.tsx
**Related Issue:** #9173
BREAKING CHANGE: Removes the deprecated `layout` property by converting it to an internal property.
Developers will need to replace `calcite-action-group`'s `layout` property with it's parent's `layout` property (i.e., parent `action-pad` or `action-bar`).
> refactor(action-group)!: remove deprecated layout property

- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/segmented-control/segmented-control.tsx
**Related Issue:** #10810
Updates `calcite-segmented-control` to wait for the item and parent component to be updated before emitting the change event.
> fix(segmented-control): ensure change event emits after item update

- packages/calcite-design-tokens/src/core/font.json
- packages/calcite-design-tokens/src/semantic/font.json
- packages/calcite-design-tokens/support/tests/__snapshots__/index.spec.ts.snap
**Related Issue:** #9524
letter-spacing, paragraph-spacing, text-decoration, and text-case tokens are deprecated to align tokens with the Calcite UIKit
> deprecate(letter-spacing, paragraph-spacing, text-decoration, text-case): align with UIKit

- packages/calcite-components/src/components/checkbox/checkbox.scss
**Related Issue:** #10537 
Applies a border for high contrast mode in Firefox.
> fix(checkbox): ensure that border shows in high contrast mode

- packages/calcite-components/src/components/block/block.tsx
**Related Issue:** #8697
- No longer make label a required property
> fix(block): label property should not be required

- .husky/pre-commit
There have been instances where this script fails to update [`customFunctions`](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/.stylelintrc.cjs#L4) properly. At times, it either clears the list or adds unnecessary functions. To address this, we’ll remove the script for now until it can be stabilized and restored.
cc @anveshmekala @macandcheese
> chore: remove stylelint-updating pre-commit script

- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/link/link.scss
**Related Issue:** #7284
Restores the underline animation that was broken in v2.7.0 (https://github.com/Esri/calcite-design-system/pull/8797) and updates it to work consistently in both LTR/RTL directions.
This also adds a `transition-default` mixin to provide finer-grained control of transitions.
> fix(link): fix underline animation

- packages/calcite-components/calcite-preset.ts
**Related Issue:** #10837
Splits up props set by the `transition-default` Tailwind util, so they are all configured correctly.
This came up in https://github.com/Esri/calcite-design-system/pull/10835. It turns out https://github.com/Esri/calcite-design-system/pull/10835 wasn't set up properly and core transitions were not working.
**Note**: Removed `outline` and `outline-offset` as these were configured with defaults and are not animated by default.
> fix: fix core transitions across components

- packages/calcite-components/package.json
- packages/calcite-components/vite.config.ts
We need to set Vite's `ssr.noExternal` option to the same non-ESM dependencies we add to Lumina's `bundleIn` option.
This also removes calcite-component's `test:prerender` NPM script, which does a Vite SSR build and is no longer necessary after migrating to Lumina.
ref: <https://vite.dev/guide/ssr#ssr-externals>
> build: externalize non-esm deps in ssr build

- packages/calcite-components/.stylelintrc.cjs
Restores [`customFunctions`](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/.stylelintrc.cjs#L4) to prevent [`function-no-unknown`](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown) errors.
> chore: restore stylelint known custom functions

- packages/calcite-components/src/assets/styles/_animation.scss
- packages/calcite-components/src/components/loader/loader.scss
Removes remaining workaround no longer needed after https://github.com/Esri/calcite-design-system/issues/6604.
> refactor: drop unnecessary prefers-reduced-motion workaround

- packages/calcite-components/src/components/list-item/list-item.scss
- packages/calcite-components/src/components/list-item/resources.ts
**Related Issue:** #9174
Updates single-select icons according to the updated spec:
* `circle` for unselected (using `color.border.input`)
* `circle-inset-large` for selected
> feat(list-item): update single-select icons

- packages/calcite-components/.eslintrc.cjs
- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/utils/component.ts
**Related Issue:** #10321
Addressed usage issues caused by TypeScript-enforced required property that had been marked as deprecated.
* adds `warnIfMissingRequiredProp` util for cases where TS-enforced required props are not suitable
* enable [`jsdoc/no-restricted-syntax`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/no-restricted-syntax.md) rule to catch props tagged as both required and deprecated
> fix(combobox-item): replace type-enforced deprecated + required `textLabel` prop with runtime warning

- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/utils/component.spec.ts
- packages/calcite-components/src/utils/component.ts
- packages/calcite-components/src/utils/label.ts
Lumina provides `componentOnReady` for both lazy and non-lazy outputs, so this util is no longer necessary.
> refactor: drop obsolete `componentOnReady` util

- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/list/interfaces.ts
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.stories.ts
- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/demos/list.html
**Related Issue:** #9173
- add `displayMode` property to choose between flat and nested lists
- update demos
- update stories
- add tests
BREAKING CHANGE: Choose a `displayMode` of "nested" or "flat" according to space and nesting requirements.
> feat(list)!: add displayMode property to choose between flat and nested lists

- packages/calcite-components/src/components/input/input.scss
- packages/calcite-components/src/components/input/input.tsx
- packages/calcite-components/src/components/input/resources.ts
**Related Issue:** #10864 
Removes the custom grab handle icon for Input in type textarea. This defers to the browser and matches the design of the Text Area component, which is the recommended migration from this "deprecated" textarea type of Input (related: #9974)
> feat(input): Improve display of resize handle for type textarea

- packages/calcite-components/src/components/dialog/dialog.scss
**Related Issue:** #10809 
Updates `dialog`’s content background color to be consistent with `modal`, easing the team’s migration efforts.
> fix(dialog): update content background color to match modal

- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/combobox-item.ts
**Related Issue:** [#7854](https://github.com/Esri/calcite-design-system/issues/7854)
Update to allow `--calcite-ui-icon-color` to override the component's icon color.
> fix(combobox-item): fix icon color css override

- packages/calcite-components/src/components/alert/alert.scss
**Related Issue:** [#10520](https://github.com/Esri/calcite-design-system/issues/10520)
Rename internal `--calcite-internal-alert-edge-distance` css token to `--calcite-alert-offset-size` and make it public.
> fix(alert): add public --calcite-alert-offset-size css token

- packages/calcite-components/src/components/chip/chip.e2e.ts
- packages/calcite-components/src/components/chip/chip.tsx
**Related Issue:** #6825
This prop will allow developers to configure whether a chip will close on `Delete` when focused.
> feat(chip): add `closeOnDelete` prop

- .lintstagedrc.json
- package-lock.json
- package.json
- packages/calcite-components/.eslintrc.cjs
- packages/calcite-components/package.json
- packages/calcite-design-tokens/package.json
After https://github.com/Esri/calcite-design-system/pull/10884, we need a few more tweaks for linting to run properly. 
* The following rules have been set to warn or removed until they can be fixed separately:
* `ban-types` (removed) – [split into separate rules](https://typescript-eslint.io/rules/ban-types/).
* `@typescript-eslint/no-empty-object-type` (warns)
* `@typescript-eslint/no-unused-expressions` (warns)
* `@typescript-eslint/no-unused-vars` (warns)
*  `no-constant-binary-expression` (warns)
* `lines-between-class-members` [(removed))](https://typescript-eslint.io/rules/lines-between-class-members/) – moved to `@stylistic`
* Installs `cross-env` per [ESLint](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated) …
> chore(linting): update ESLint setup

- packages/calcite-components/src/components/chip/chip.e2e.ts
- packages/calcite-components/src/components/chip/chip.stories.ts
- packages/calcite-components/src/components/chip/chip.tsx
- packages/calcite-components/src/demos/chip.html
**Related Issue:** #8696 
Provides context to the component's `label` property for JAWS and NVDA users using the [`"img"` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role), conveying content is delivered in a visual manner and should be accompanied with the required `label` property.
> fix(chip): provide label context to assistive technologies

- packages/calcite-components/src/components/color-picker-hex-input/color-picker-hex-input.scss
- packages/calcite-components/src/components/color-picker/color-picker.e2e.ts
- packages/calcite-components/src/components/color-picker/color-picker.scss
- packages/calcite-components/src/components/color-picker/resources.ts
**Related Issue:** #9415 
This updates the `color-picker`'s default widths to be:
* 200 (s)
* 240 (m)
* 304 (l)
Additionally, the color-field will use an aspect ratio of 1.8.
BREAKING CHANGE: The default width and height of the `color-picker` have been updated. Developers should review and adjust their layouts to accommodate these changes.
> feat(color-picker)!: update color field dimensions

- packages/calcite-components/src/components/date-picker/date-picker.e2e.ts
Address test failure caused by temporal coupling, assuming next year and month wouldn't overflow (e.g., December ➡️ January).
> test(date-picker): fix test assumption for next year and month

- package-lock.json
- package.json
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/sheet/sheet.scss
- packages/calcite-components/src/components/stepper-item/stepper-item.scss
Updates Sass vars to use design tokens, removing a legacy dep.
> build(deps): drop `@esri/calcite-colors`

- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
- packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #8698, #8005
Updates time zone labels (name-mode) to display IANA identifiers per https://github.com/Esri/calcite-design-system/issues/8005#issuecomment-2379908947.
> fix(input-time-zone): ensure name-mode displays IANA time zone identifiers

- .github/workflows/track-milestone-estimates.yml
Adds a new run to the track-milestone-estimates when a milestone has been closed. The `trackMilestoneEstimates.js` script does not contain specific context to the issue, so the accompanying script shouldn't need any tweaks with the new run condition. 
The run will now execute when either:
- an issue is closed
- a milestone is closed, or
- manually via `workflow_dispatch`
> ci(milestone-estimates): add run when milestone is closed

- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #10897 
cascade `scale` from `combobox` onto `combobox-item-group`
> fix(combobox-item-group): cascade scale from combobox

- packages/calcite-components/src/components/button/button.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/notice/notice.tsx
- packages/calcite-components/src/components/select/select.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/components/shell-panel/shell-panel.tsx
- packages/calcite-components/src/components/split-button/split-button.tsx
**Related Issue:** #10934
Include `half` in the updated types. Fix `width` types.
> fix(button, dialog, dropdown, notice, select, sheet, shell-panel, split-button): fix width types

- packages/calcite-components/src/components/popover/popover.e2e.ts
**Related Issue:** #10867
Ensure `popover` doesn't reopen when the trigger is clicked and `autoClose` is true.
> test(popover): ensure popover doesn't reopen when trigger is clicked and autoClose is true

- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** [#9862](https://github.com/Esri/calcite-design-system/issues/9862)
Update `panel` to:
- Use `calcite-font-line-height-relative-snug` as `heading` and `description`'s line height.
- Vertically center the header's content when only `heading` or `description` are used.
> fix(panel): add correct heading and description line height and alignment

- packages/calcite-components/src/components/dropdown-item/dropdown-item.scss
**Related Issue:** #10335 
Updates styles to no longer lose focus outline when hovering a selected item.
> fix(dropdown-item): keep focus ring when selected dropdown item is hovered

- packages/calcite-components/src/components/menu-item/menu-item.scss
**Related Issue:** [#10001](https://github.com/Esri/calcite-design-system/issues/10001)
This:
- Removes the background color on `:hover` and `:focus`.
- Adds `border.2` `2px` bottom border on `:hover`.
- Increases `:active` state `bottom border` to `4px` on `:focus`.
> feat(menu-item): enhance component's interactive states

- packages/calcite-components/src/components/slider/slider.scss
- packages/calcite-components/src/components/slider/slider.stories.ts
- packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #9239
This improves label handling for long thumb labels.
> fix(slider): avoid breaking thumb label on edges

- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
**Related Issue:** #10723
This update passes `sort-handle`'s `scale` property down to the handle `action` component.  This corrects the appearance for large scale sort handles used in components like `list-item`.
> fix(sort-handle): pass scale to handle action

- packages/calcite-components/src/components/input-time-zone/utils.ts
**Related Issue:** #10895 
Add workaround for https://issues.chromium.org/issues/381620359.
**Note**: `timezone-groups` was [also updated](https://github.com/Esri/calcite-design-system/pull/10961) with this workaround.
> fix(input-time-zone): add workaround for `Factory` time zone error in Chrome

- packages/calcite-components/src/components/list/list.stories.ts
**Related Issue:** #7100
This PR fixes the simple story for `list` to correctly set the `scale` property.
> chore(list): fixing scale argument on list's simple story

- packages/calcite-components/src/components/filter/filter.scss
**Related Issue:** #10941
This update removes an inline margin applied to `calcite-filter`'s internal `label` element.  This spacing is now handled by `list`'s supported scales.
> fix(filter): remove unnecessary inline margin from internal label element

- packages/calcite-components/src/components/list/list.tsx
**Related PR:** https://github.com/Esri/calcite-design-system/pull/10702
It looks like the new Lumina language wasn't included in the [original PR](https://github.com/Esri/calcite-design-system/pull/10702). This PR updates so the documentation picks up `list`'s required `label` property.
> docs(list): use lumina ref for required label property

- packages/calcite-components/src/components/filter/filter.e2e.ts
- packages/calcite-components/src/components/filter/filter.tsx
**Related Issue:** #8076
- add label prop to filter
- add test
> feat(filter): add label property

- packages/calcite-components/src/components/icon/icon.e2e.ts
- packages/calcite-components/src/components/icon/icon.tsx
**Related Issue:** #8261
Adds new property that will allow icon data to be preloaded for eager rendering.
> feat(icon): add preload property

- packages/calcite-components/src/components/input/input.scss
The Chrome-specific selector fixed in [this PR](https://github.com/Esri/calcite-design-system/pull/10973) introduces cross-browser inconsistencies and prevents users from toggling the calendar via mouse. This change removes the selector to address these issues.
> revert: fix(input): fix broken selector

- packages/calcite-components/src/components/menu-item/interfaces.ts
- packages/calcite-components/src/components/menu-item/menu-item.tsx
- packages/calcite-components/src/components/menu/menu.stories.ts
- packages/calcite-components/src/components/menu/menu.tsx
- packages/calcite-components/src/components/navigation-logo/navigation-logo.tsx
- packages/calcite-components/src/components/navigation-user/navigation-user.tsx
- packages/calcite-components/src/components/navigation/navigation.tsx
**Related Issue:** #10845
Renames component classes starting with `Calcite`. 
**Note**: This is not a breaking change since directly importing class interfaces is undocumented. Developers are expected to use the corresponding HTML element type (e.g., `HTMLCalciteActionElement` instead of `Action`).
> refactor: ensure component class names are consistent

- packages/calcite-components/src/components/action/action.e2e.ts
- packages/calcite-components/src/components/action/action.scss
- packages/calcite-components/src/tests/commonTests/themed.ts
**Related Issue:** #10982
Resolves issue where transparent styles are not correctly applied when the action[active] state is set.
Adds optional "expectedValue" prop to themed test utility
Adds e2e test coverage
> fix(action): active styles present with transparent appearance

- packages/calcite-components/src/components/tree-item/tree-item.scss
- packages/calcite-components/src/components/tree-item/tree-item.tsx
- packages/calcite-components/src/components/tree/tree.stories.ts
**Related Issue:** #7096 
Updates padding indentation for `tree-item`'s in `tree`
> feat(tree,tree-item): update indentation

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
**Related Issue:** #10762
Splits header and content padding rules so the token doesn't apply to header
> fix(accordion-item): split header content padding

- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
This should help bundlers (e.g., Webpack) resolve dependencies due to ambiguous paths.
For context, Lumina doesn't bundle dependencies like Stencil did. `dayjs` imports were causing trouble because of this.
> fix: use explicit module imports for dayjs

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.tsx
`willUpdate` was invoking toggling logic that was meant to be called after initialization (compare with [Stencil version](https://github.com/Esri/calcite-design-system/blame/bcc19be314a45ff584793e473e5851e15cefa83f/packages/calcite-components/src/components/panel/panel.tsx#L92)).
> fix(dialog, panel): prevent `beforeClose` from being invoked during initialization

- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #10947 
Enhance the `list`'s `displayMode` prop to account for the `"flat"` and `"nested"` values, and consistency of the value when defined on the parent element for its children.
> docs(list): enhance displayMode prop

- packages/calcite-components/src/components/tree-item/tree-item.scss
**Related Issue:** #11035 
Fixed `lines` length of parent `tree-item` with slotted children.
> fix(tree): ensures `lines` length is accurate

- packages/calcite-components/src/components/inline-editable/inline-editable.e2e.ts
- packages/calcite-components/src/components/inline-editable/inline-editable.tsx
Fixes issue that prevented canceling an edit session and restoring the input.
> fix(inline-editable): fix cancel workflow

- packages/calcite-components/src/index.ts
**Related Issue:** #11013
Augments `csstype`'s module to allow all custom Calcite CSS properties (step 3 from https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors).
> fix: allow custom Calcite CSS properties in style object type

- packages/calcite-components/src/components/action/action.e2e.ts
- packages/calcite-components/src/components/action/action.scss
**Related Issue:** #10831
Deprecate --calcite-action-background-color-pressed in favor of --calcite-action-background-color-press
Deprecate --calcite-action-text-color-pressed in favor of --calcite-action-text-color-press
Deprecate --calcite-action-corner-radius-start-start, --calcite-action-corner-radius-start-end, --calcite-action-corner-radius-end-start, and --calcite-action-corner-radius-end-end in favor of --calcite-action-corner-radius.
> deprecate(action): deprecate tokens

- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
Adds internal flag to determine if filter should be performed. Similar to [`ad054fd` (#10482)](https://github.com/Esri/calcite-design-system/pull/10482/commits/ad054fd07e88b9cb304f02b7ec2006a146e10d08), this is needed because subsequent calls after `updateListItem({ performFilter: true })` would take precedence due to how [`lodash#debounce`](https://lodash.com/docs/4.17.15#debounce) works:
> The `func` is invoked with the last arguments provided to the debounced function.
> fix(list): fix issue where last call to debounced update filter logic would override args from previous calls

- packages/calcite-components/src/components/dialog/dialog.scss
- packages/calcite-components/src/components/dialog/dialog.stories.ts
**Related Issue:** #10809
- set slotted panel bg color to initial color
- add story test
> fix(dialog): no longer modifies slotted panels background color

- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.stories.ts
- packages/calcite-components/src/components/sort-handle/sort-handle.e2e.ts
- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
- disable drag handle when a single item is in the list and the list has nowhere else to move to
- add e2e
- add story
> fix(list, sort-handle): disable sort-handle when no move to items are present and item count is one

- packages/calcite-components/src/components/dialog/dialog.scss
- packages/calcite-components/src/components/dialog/dialog.stories.ts
**Related Issue:** #11052
- set slotted panel bg color to initial color
- add story test
> fix(dialog): no longer modify slotted panels background color

- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.tsx
Fixes a text width logic issue where [`font`](https://developer.mozilla.org/en-US/docs/Web/CSS/font) would be empty instead of the expected shorthand value.
This also moves the text-width calculation logic to a `requestAnimationFrame` callback to improve timing and performance.
> fix(date-picker): fix year-select width logic

- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/utils/focusTrapComponent.ts
This addresses an issue where focus-trapping components were unintentionally modified by https://github.com/Esri/calcite-design-system/pull/9231/ to block interaction/focusing via outside clicks.
> fix(dialog, modal, popover, sheet): restore deactivating focus traps on outside click

- packages/calcite-components/src/components/action/action.scss
**Related Issue:** #10982
Update the background color of the component when active=true and appearance=transparent to use the transparent-hover instead of transparent-press.
> fix(action): component in transparent active mode should use -hover

- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/list/list.tsx
Changes `calcite-list` and `calcite-list-item` to wait for their update to be complete before emitting the change and selection events.
> fix(list, list-item): ensure change and select events are emitted after state is updated

- packages/calcite-components/src/components/input/input.scss
- packages/calcite-components/src/components/list-item/list-item.scss
- packages/calcite-components/src/components/navigation-logo/navigation-logo.scss
- packages/calcite-components/src/components/navigation-user/navigation-user.scss
- packages/calcite-components/src/components/navigation/navigation.scss
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/tooltip/tooltip.scss
Provide consistency and alignment in our docs across the design system for component design tokens, also in alignment with our https://github.com/Esri/calcite-design-system/pull/10058 and https://github.com/Esri/calcite-design-system/pull/10430. 📚
Also of note, there was an extra `*` in the `navigation logo` [internal doc](https://next-preview.sites.afd.arcgis.com/calcite-design-system/components/navigation-logo/#styles).
> docs: update component token description for consistency

- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
✨🧹✨
**Note**: this isn't considered breaking since it's an internal component
> refactor(sort-handle): remove unused `maxItems` prop

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/components/accordion/accordion.stories.ts
This avoids unintentionally styling other actionable components and offers more flexibility.
**Note**: this changes styles to use explicit selectors instead of universal ones to improve maintainability.
> fix(accordion-item): stretch slotted actions only

- packages/calcite-components/src/components/input/input.scss
- packages/calcite-components/src/components/input/input.tsx
- packages/calcite-components/src/components/input/resources.ts
**Related Issue:** #10959 #10958
Adds classes to use for specific styling cases in Input. This only adjusts `suffix-text` and `prefix-text`. There are other styles set on attributes in the component, but those are reflected attributes. We could still improve that in the future if needed - and / or, in the newer `input-x` components.
> fix(input): Avoid styling on non-reflected attributes

- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/tile-select/tile-select.tsx
Adds guards for refs that may be nulled. Unlike Stencil, Lumina calls `ref` when the component is disconnected, so this addresses some issues caused by logic running after an element is no longer connected.
> fix(input-date-picker, modal, tile-select): avoid using refs that have been nulled

- packages/calcite-components/src/utils/number.ts
Referencing the class would cause incorrect JS output in certain vite builds:
**source ✅**
```ts
class i {
static {
this.DECIMALS = 100;
}
static {
this.SHIFT = BigInt("1" + "0".repeat(i.DECIMALS));
}
}
```
**transpiled ❌**
```ts
var b = class {
static{this.DECIMALS = 100;}
static{this.SHIFT = BigInt("1" + "0".repeat(b.DECIMALS));} // TypeError: Cannot read properties of undefined (reading 'DECIMALS')
}
```
> fix: prevent transpilation issues by using `this` to reference static props

- packages/calcite-components/src/assets/styles/_floating-ui.scss
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/popover/popover.stories.ts
- packages/calcite-components/src/components/tooltip/tooltip.stories.ts
- Follows [`floating-ui`'s initial layout recommendation](https://floating-ui.com/docs/computeposition#initial-layout).
- Combobox wasn't correctly handling the size when in fixed overlay positioning
- Example: https://codepen.io/Matt-Driscoll/pen/raByNmQ?editors=1010
- updated tooltip and popover stories where stories were being cut off due to sizing.
> fix: floating ui elements set max-content for inline-size

- packages/calcite-components/src/controllers/useT9n.ts
`@arcgis/lumina@4.32.0-next.52` uses `no` for Norwegian by default, so we can drop this argument.
> refactor(t9n): drop deprecated and obsolete `useNoForNorwegian` arg

- .github/scripts/omitPrFromChangelog.js
This adds context (ignored by changelog generation) to the commit override to clarify its intent.
> chore: add context to no-changelog commit override

- packages/calcite-components/src/components/autocomplete-item/autocomplete-item.tsx
- packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts
- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/demos/validation.html
- packages/calcite-components/src/utils/form.tsx
**Related Issue:** #10044
- opens autocomplete when input is clicked
- This is useful for when the input is already focused but the autocomplete is closed.
- Sets focus and sets `open=false` when `autocomplete-item` is clicked
- ensures that the input receives focus after an `autocomplete-item` is clicked
- use `enterKeyHint` property JSX
- update `onFormReset` to be called after form component logic
- This allows us to reset the `inputValue` to the `defaultInputValue` without overriding existing logic
- adds autocomplete to validation demo
cc @benelan 
> fix(autocomplete): handle focusing when item is clicked and reset inputValue on form reset

- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #6544
- fix to not require filterEnabled to use filterPredicate
- It was basically the `(changes.has("filterPredicate") && this.hasUpdated)` that was the culprit.
- add test
> fix(list): Don't require `filterEnabled` for `filterPredicate` usage

- packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #11115
This extends the bottom border of `list-item` content to include content in the `actions-start` slot.
> feat(list-item): extend bottom border to include actions-start slot

- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #6544
docs(list): make filterPredicate property optional.
> docs(list): make filterPredicate property optional.

- packages/calcite-components/src/components/input-number/input-number.tsx
- packages/calcite-components/src/components/input-text/input-text.tsx
- packages/calcite-components/src/components/input/common/tests.ts
- packages/calcite-components/src/components/input/input.tsx
Fixes an issue caused by #10310, where `autofocus` was no longer used within rendering.
> fix(input, input-text, input-number): restore handling of autofocus global attribute

- packages/calcite-components/src/components/list-item/list-item.scss
Updates `list-item` to use the default focus color token introduced in https://github.com/Esri/calcite-design-system/pull/10512.
> fix(list-item): ensure consistent focus border color by referencing updated tokens

- packages/calcite-components/src/components/popover/popover.e2e.ts
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
- packages/calcite-components/src/components/tooltip/tooltip.tsx
Adds a guard to `popover` and `tooltip` `ref` callbacks to avoid missing ref warnings on removal. After #10310, `ref` callbacks are invoked both when the component is added and removed (see https://github.com/Esri/calcite-design-system/issues/11093).
> fix(popover, tooltip): skip ref setup logic on component removal

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/custom-theme/accordion-item.ts
- packages/calcite-components/src/custom-theme/accordion.ts
**Related Issue:** #10894 
This PR adds two new tokens which align with the Calcite naming schema.
--calcite-accordion-item-icon-color-start
--calcite-accordion-item-icon-color-end
deprecate(accordion-item): deprecate `--calcite-accordion-item-start-icon-color` and `--calcite-accordion-item-end-icon-color` tokens
> feat(accordion-item): update token naming schema

- packages/calcite-components/src/components/action-menu/action-menu.e2e.ts
- packages/calcite-components/src/components/action-menu/action-menu.tsx
Fixes a regression caused by #10310 where the change to the internal popover to use `triggerDisabled` would no longer work when the component was reconnected.
> fix(action-menu): fix toggle logic when `action-menu` is reconnected

- packages/calcite-components/src/components/block-section/block-section.e2e.ts
- packages/calcite-components/src/components/block-section/block-section.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/block-section.ts
Adds the following subcomponent tokens (CSS props):
- `--calcite-block-section-background-color`
- `--calcite-block-section-border-color`
- `--calcite-block-section-header-text-color`
- `--calcite-block-section-text-color`
- `--calcite-block-section-text-color-hover`
> feat(block-section): add component tokens

- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #11138
Add a description to `input-time-zone`'s `setFocus` method.
> docs(input-time-zone): add setFocus method description

- packages/calcite-components/src/components/button/button.tsx
- packages/calcite-components/src/components/color-picker-swatch/color-picker-swatch.tsx
- packages/calcite-components/src/components/color-picker/color-picker.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/functional/FloatingArrow.tsx
- packages/calcite-components/src/components/icon/icon.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
- packages/calcite-components/src/components/link/link.tsx
- packages/calcite-components/src/components/select/select.tsx
- packages/calcite-components/src/components/slider/slider.tsx
- packages/calcite-components/src/components/tab-title/tab-title.tsx
- packages/calcite-components/src/tests/utils.ts
- packages/calcite-components/src/utils/config.ts
- packages/calcite-components/src/utils/globalScript.ts
- vitest.workspace.ts
**Related Issue:** #10083 
Add consistent use of the `@see` JSDoc references across the repo, where previously there was a mix of `see` and `@see` references.
This is phase 1 of 2 for the issue, where phase 2 will require documentation updates to accommodate the JSDoc references to display on the site.
> docs: add jsdoc `@see` tag consistency

- package-lock.json
- package.json
- packages/calcite-components/eslint.config.mjs
- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
- packages/calcite-components/src/components/input/common/input.spec.ts
- packages/calcite-components/src/components/input/common/tests.ts
- packages/calcite-components/src/utils/dom.spec.ts
This will replace `eslint-plugin-jest` rules that are no longer applicable after #10310.
> chore(linting): enable `eslint-plugin-vitest`

- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
**Related Issue:** #11128 
Fixes an issue caused by having selection-related logic run before items are updated.
* removes `async` from synchronous method
* moves internal value-setting logic earlier to ensure proper state
> fix(input-time-zone): keep selection in sync when item-related props are set along with value

- .github/ISSUE_TEMPLATE/accessibility.yml
Remove the default priority, `p - high`, from the accessibility issue template, where the team can assess the a11y issue's priority during regular bug triage meetings.
> chore(a11y): remove default priority label from a11y issue template

- .renovaterc.json
[`followTag`](https://docs.renovatebot.com/configuration-options/#followtag) should help bump prerelease versions in `package.json` instead of only updating the lock file, which could cause different versions to be installed (see https://github.com/Esri/calcite-design-system/pull/11174).
**Note**: we should remove this option once `@arcgis` packages are stable. cc @benelan
> ci(renovate): enable followTag for @arcgis prereleases

- packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts
- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/demos/autocomplete.html
**Related Issue:** #11152
- add `scrollContentTo` method
- add test
- automatically scroll to items when using keyboard
> feat(autocomplete): add scrollContentTo method and automatically scroll when navigating items via keyboard

- packages/calcite-components/package.json
- packages/calcite-components/support/generateSupportedBrowsersJSON.ts
**Related Issue:** #10217
Adds a script that generates supported browsers JSON file for our internal docs output on each build.
**`docs/supported-browsers.json`** (split into lines for readability)
```json
[
"chrome 131",
"chrome 130",
"edge 131",
"edge 130",
"firefox 133",
"firefox 132",
"firefox 128",
"ios_saf 18.2",
"ios_saf 18.1",
"ios_saf 18.0",
"ios_saf 17.6-17.7",
"ios_saf 17.5",
"ios_saf 17.4",
"ios_saf 17.3",
"ios_saf 17.2",
"ios_saf 17.1",
"ios_saf 17.0",
"safari 18.2",
"safari 18.1",
"safari 18.0",
"safari 17.6",
"safari 17.5",
"safari 17.4",
"safari 17.3",
"safari 17.2",
"safari 17.1",
"safari 17.0"
]
```
> chore: add script to generate supported browser info for docs

- .renovaterc.json
- package.json
- packages/calcite-components/package.json
Using `bump` [range strategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) along with minor `@arcgis` instead of [`followTag`](https://docs.renovatebot.com/configuration-options/#followtag), as the latter follows versions strictly, making minor versions no longer allowed. 
versions strictly, thus no longer allowing minor versions.
cc @maxpatiiuk
> ci(renovate): use bump range strategy instead of `followTag` for @arcgis prereleases

- LICENSE.md
- packages/calcite-components-react/LICENSE.md
- packages/calcite-components/LICENSE.md
- packages/calcite-components/readme.md
- packages/calcite-design-tokens/LICENSE.md
- packages/calcite-ui-icons/LICENSE.md
- packages/eslint-plugin-calcite-components/LICENSE.md
- packages/eslint-plugin-calcite-components/README.md
- readme.md
Updates Calcite's copyright year to 2️⃣0️⃣2️⃣5️⃣ 🎉
> docs: update copyright to 2025

- packages/calcite-components/src/tests/commonTests/themed.ts
This helps avoid test failures caused by animations/transitions.
> chore(themed): disable animations for consistent assertion results

- packages/calcite-components/src/components/time-picker/time-picker.e2e.ts
- packages/calcite-components/src/components/time-picker/time-picker.tsx
- packages/calcite-components/src/utils/time.ts
**Related Issue:** #11198 
This PR fixes an issue where if no valid time value is currently set, the `time-picker` component doesn't display the hour in the corresponding `hour-format`.
> fix(time-picker): display correct localized hour based on hour-format when no value is set

- packages/calcite-components/src/components/input/input.scss
**Related Issue:** #8967 
Breaks the placeholder styles into separate lines to avoid a browser specific selector erroring out the whole line. 
> fix(input): correctly apply placeholder styles

- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/notice/notice.scss
Updates component token descriptions for `block` and `notice` in alignment with our [documentation standard](https://github.com/Esri/calcite-design-system/wiki/tokens-documentation#component-tokens).
> docs(block, notice): update component token descriptions

- packages/calcite-components/src/components/notice/notice.scss
Deprecate `--calcite-notice-width token` token.
> deprecate(notice): deprecate --calcite-notice-width token

- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #11217 #10731
Removes unintentional `@readonly` on `readOnly` prop. 
For context, with #10310 any props with the `@readonly` tag will be made read-only.
> fix(text-area): make `readOnly` prop writable

- packages/calcite-components/support/generateT9nDocsJSON.ts
Updates `generateT9nDocsJSON.ts` to reference the updated translations bundle file name (see https://github.com/Esri/calcite-design-system/pull/11054).
> fix(docs): use updated translation bundle paths to generate `translations.json`

- packages/calcite-components/src/tests/commonTests/themed.ts
This fixes an issue in the `themed` test util where elements with multiple classes weren’t matched using strict equality.
**Note**: this also simplifies shadow DOM querying logic
> chore(themed): fix issue where class-based matching would not work due to resolved class value

- packages/calcite-components/package.json
Adds package export to support doc-related ESM imports.
> fix(docs): add docs package export

- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.tsx
- packages/calcite-components/src/components/handle/handle.tsx
- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
For consistency, removes `@readonly` JSDoc tags on internal `messages` props (t9n).
> refactor: remove unnecessary @readonly tags

- packages/calcite-components/src/components/tile/tile.scss
**Related Issue:** #11170 
This PR fixes an issue where overflowing content doesn't stay within the outer bounds of the Tile.
> fix(tile): wrap overflowing text content

- packages/calcite-components/src/components/input/input.scss
**Related Issue:** #8053
Fixes text clipping in Windows 10 when using Japanese locale.
> fix(input): fix clipping for type=file with Japanese locale

- packages/calcite-components/src/components/tile-group/tile-group.stories.ts
- packages/calcite-components/src/components/tile/tile.scss
**Related Issue:** #10931 
Fixes an issue where large tiles (w/o `description`) would cause the selection icon to be oversized and misaligned.
* refactors stories to use HTML-generating functions to improve maintainability
* adds internal CSS var to reuse and simplify internal space assignments
* applies icon styling separately
* applies relative positioning to content container
* replaces sticky z-index var in favor of default + bump to keep it within the same layer
> fix(tile-group): keep selection icon size consistent for large tiles

- packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts
- packages/calcite-components/src/components/autocomplete/autocomplete.stories.ts
- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/autocomplete/resources.ts
- packages/calcite-components/src/utils/dom.spec.ts
**Related Issue:** #11224
- allow icon to be set false
- add tests
> fix(autocomplete): allow hiding icon

- packages/calcite-components/eslint.config.mjs
- packages/calcite-design-tokens/eslint.config.mjs
Resolve a lint-staged error reported by @macandcheese:
```text
✖ eslint --fix:
/Users/adam9519/Documents/git-repositories/calcite-design-system/packages/calcite-components/src/components/combobox/combobox.stories.ts
0:0  error  Parsing error: /Users/adam9519/Documents/git-repositories/calcite-design-system/packages/calcite-components/src/components/combobox/combobox.stories.ts was not found by the project service. Consider either including it in the tsconfig.json or including it in allowDefaultProject
✖ 1 problem (1 error, 0 warnings)
husky - pre-commit script failed (code 1)
Hook process exited.
```
It seems like the projectService option is using `tsconfig.json` (which excludes stories) instead of `tsconfig-eslint.json`. Disabling the option for now.
ref: …
> ci(linting): fix typescript parser issue

- packages/calcite-components/eslint.config.mjs
- packages/calcite-components/src/components/input-number/input-number.tsx
- packages/calcite-components/src/components/input/input.tsx
This PR disables:
* false-positives from [`react/forbid-dom-props`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md) and [`react/forbid-component-props`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md) 
* `eslint-plugin-jsdoc` rules that create churn without added value (most already covered by TypeScript):
* [`jsdoc/check-param-names`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.README/rules/check-param-names.md)
* [`jsdoc/require-param-description`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.README/rules/require-param-description.md)
* [`jsdoc/require-returns`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.README/rules/require-returns. …
> chore(linting): clean up warnings

- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/navigation-logo/navigation-logo.e2e.ts
- packages/calcite-components/src/components/rating/rating.e2e.ts
- packages/calcite-components/src/tests/commonTests/themed.ts
This adds support for `find` string selectors for testing stateful interactions. 
* deprecates the `attribute`/`value` matching since `find` string selectors:
* accomplish the same
* align better with E2E tests
* simpler to wire up
* provide more precise matching
* changes the existing `attribute`/`value` matching to be scoped to the targeted element:
* improves reliability of matches
* encourages using `find` string selectors for more complex cases
> chore(themed): improve matching of interaction target elements

- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox-item/resources.ts
- packages/calcite-components/src/components/combobox/combobox.stories.ts
**Related Issue:** #9322 
Adds support for `content-start` slot. @SkyeSeitz @ashetland can you confirm the "kitchen sink" case spacing with icon prop, slotted content, etc.
> feat(combobox-item): Add support for `content-start` slot

- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/components/list/resources.ts
> refactor(list): use debounce value from common debounce module instead of local one

- packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #9581
Ensure the `files` property is updated before `calciteInputInput` is emitted for `type="file"` inputs.
> fix(input): update files property on input event when type="file"

- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox/combobox.tsx
**Related Issue:** #10731  
https://github.com/Esri/calcite-design-system/pull/10952 increased the frequency of `combobox`'s item-updating logic.  
This improves performance by:  
* reducing the number of initial item update calls  
* debouncing the item update function to the next tick
> perf(combobox): fix initialization performance regression

- packages/calcite-components/src/tests/commonTests/defaults.ts
- packages/calcite-components/src/tests/commonTests/disabled.ts
- packages/calcite-components/src/tests/commonTests/floatingUI.ts
- packages/calcite-components/src/tests/commonTests/focusable.ts
- packages/calcite-components/src/tests/commonTests/formAssociated.ts
- packages/calcite-components/src/tests/commonTests/hidden.ts
- packages/calcite-components/src/tests/commonTests/labelable.ts
- packages/calcite-components/src/tests/commonTests/openClose.ts
- packages/calcite-components/src/tests/commonTests/reflects.ts
- packages/calcite-components/src/tests/commonTests/renders.ts
- packages/calcite-components/src/tests/commonTests/slots.ts
- packages/calcite-components/src/tests/commonTests/t9n.ts
- packages/calcite-components/src/tests/commonTests/themed.ts
- packages/calcite-components/src/tests/commonTests/utils.ts
Removes `jest-axe`-related setup for non-`accessible` common test helpers.
> chore: remove unrelated jest-axe expect extensions

- packages/calcite-components/src/components/tile/tile.scss
- packages/calcite-components/src/components/tile/tile.stories.ts
**Related Issue:** [#11199 ](https://github.com/Esri/calcite-design-system/issues/11199#issuecomment-2587924216)
This update allows percentage `inline-size/width` styles set on slotted content to be based on the host `calcite-tile` element.
> fix(tile): allow percentage inline-size on slotted content to be based on host

- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/list-item/list-item.scss
- packages/calcite-components/src/components/list/list.stories.ts
Uses pseudo-element + CSS logical property placement to ensure the selection indicator is consistently positioned, regardless of page direction.
> fix(list-item): fix selection indicator placement in RTL

- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/input-text/input-text.tsx
- packages/calcite-components/src/components/input/input.tsx
**Related Issue:** #11148
Updates the `pattern` prop in `autocomplete`, `input`, and `input-text` that to use the prop the component must reside within a form element, re: https://github.com/Esri/calcite-design-system/issues/11148#issuecomment-2574036966.
> docs(autocomplete, input, input-text): update pattern context for residing in a parent form

- packages/calcite-components/src/components/alert/alert.tsx
- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/notice/notice.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/components/tooltip/tooltip.tsx
- packages/calcite-components/src/utils/openCloseComponent.spec.ts
- packages/calcite-components/src/utils/openCloseComponent.ts
Updates open/close components to use the correct transition property.
* this was working as expected because the property wasn't being used correctly
* makes `openProp` optional and defaults to `open` when not specified
* updates types to ensure CSS props are specified by `transitionProp`
* renames `openTransitionProp` to `openProp` to avoid confusion with CSS transitions
@Elijbet Thanks for spotting this one!
> refactor(openClose): use the correct property to specify open/close transition prop

- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/checkbox/checkbox.tsx
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/date-picker/date-picker.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
- packages/calcite-components/src/components/input-number/input-number.tsx
- packages/calcite-components/src/components/input-text/input-text.tsx
- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
- packages/calcite-components/src/components/input/input.tsx
- packages/calcite-components/src/components/radio-button-group/radio-button-group.tsx
- packages/calcite-components/src/components/radio-button/radio-button.tsx
- packages/calcite-components/src/components/rating/rating.tsx
- packages/calcite-components/src/components/segmented-control/segmented-control.tsx
- packages/calcite-components/src/components/select/select.tsx
- packages/calcite-components/src/components/slider/slider.tsx
- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** https://github.com/Esri/calcite-design-system/pull/11285#pullrequestreview-2551247008
Updates the `required`, `max`, `min`, `maxLength` and `minLength` props where a parent form element is needed.
> docs: update `required`, `max`, `min`, `maxLength` + `minLength` to include parent form

- .github/workflows/deploy-latest.yml
- .github/workflows/deploy-prerelease.yml
- .github/workflows/pr-e2e.yml
- .github/workflows/remove-prerelease-changelog-entries.yml
**Related Issue:** https://github.com/actions/runner-images/issues/10636
GitHub just updated the `ubuntu-latest` action runner to point to `v24.04`, which is causing a Puppeteer error:
```text
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Failed to launch the browser process!
[0115/215319.789774:FATAL:zygote_host_impl_linux.cc(128)] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise seehttps://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate …
```
> ci: resolve e2e errors due to updated actions runner

- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
**Related Issue:** #11078
- no longer focuses on cells when a cell is focused via click
- only a row or cell can be focusable via tabindex at a time
- update tests
> fix(list): only focus on row when clicking a list item

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/custom-theme/block.ts
Refactor block heading text color. `open/close` icon shares a hover state with the color of the heading text when the component is open.
Adds the following component token:
`--calcite-block-heading-text-color-press`
> refactor(block): heading text color

- packages/calcite-ui-icons/fantasticonrc.json
**Related Issue:** #11331 #11299
The changes to `fantasticonrc.json` were not committed in the PRs linked above. @arowles, can you please make sure the additions to `fantasticonrc.json` are included in your PR whenever you add icons? Otherwise the fonts will not have consistent codepoints.
Please see this comment for more context: https://github.com/Esri/calcite-design-system/pull/10996#pullrequestreview-2503379692
> chore(utility-network-layer, crosshair): add font codepoints

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
Adds async assertion to non-throwing test.
* https://vitest.dev/api/expect.html#tothrowerror
* https://vitest.dev/api/expect
* https://jestjs.io/docs/asynchronous#asyncawait
> test(combobox): use async expect for non-throwing test case

- CONTRIBUTING.md
- packages/calcite-components/src/utils/loadable.ts
**Related Issue:** #11243 #11312
Fix a linting error that was likely committed before the author's branch was synced with the rule changes linked above. The linting error caused issues committing during merge conflict resolution.
> ci: lint monorepo

- packages/calcite-components/src/components/color-picker/color-picker.e2e.ts
- packages/calcite-components/src/components/color-picker/color-picker.tsx
**Related Issue:** #10731  
Adds missing check to skip internal, equal values after transitioning to getters/setters in #10310.
> fix(color-picker): fix error caused by initial value with a different format

- packages/calcite-components/src/components/tree-item/tree-item.scss
- packages/calcite-components/src/components/tree/tree.stories.ts
**Related Issue:** #11334
- renders lines correctly in rtl
- adds story
> fix(tree): render lines correctly in RTL direction

- packages/calcite-components/src/components/action-pad/action-pad.scss
- removes overflow styling which is unnecessary
> refactor(action-pad): remove unnecessary overflow css styling.

- packages/calcite-components/src/components/flow/flow.tsx
This moves `flow-item` processing to `loaded`, so all items are guaranteed to be ready.
**Note**: `items` is no longer decorated with `@state`, as it is not used in rendering.
> fix(flow): process items on loaded

- packages/calcite-components/src/components/carousel/carousel.e2e.ts
- packages/calcite-components/src/components/carousel/carousel.tsx
**Related Issue:** #11317 
Ensures the animation is correctly applied when `autoplay` advances through Carousel Items.
Also updates the Progress component to adhere to the new `value` format / breaking change for 3.x: https://github.com/Esri/calcite-design-system/pull/10622 / logged in internal tracking discussion
> fix(carousel): Ensure correct `autoplay` display and animation

- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.scss
**Related Issue:** #11371 
Removes outline for header actions which is causing transition on focus shift. 
This is introduced with https://github.com/Esri/calcite-design-system/pull/10836/ where outline exclusion from transition is ignored in Tailwind util.
> fix(date-picker): remove outline for header actions

- packages/calcite-components/src/components/icon/utils.ts
This improves clarity by displaying the icon name and scale separately in the error message instead of an internal key used by icon utils:
```sh
"measure16" is not a valid calcite-ui-icon name
```
⬇️
```sh
measure (s) icon failed to load.
```
Also, this now uses the logger to display the `calcite` badge for additional context.
> chore(icon): improve icon load error message

- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.tsx
- packages/calcite-components/src/components/date-picker/date-picker.e2e.ts
**Related Issue:** #11321 
No longer disable min,max month's in select menu of date-picker.
> fix(date-picker): no longer disable min/max value month in select menu

- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/components/tooltip/tooltip.scss
Removes legacy `position: relative` to reduce chance of clipping (see https://floating-ui.com/docs/misc#clipping).
> fix(popover, tooltip): drop relative-positioning to reduce risk of clipping

- packages/calcite-components/src/components/graph/graph.e2e.ts
- packages/calcite-components/src/components/graph/graph.scss
- packages/calcite-components/src/components/graph/graph.tsx
- packages/calcite-components/src/components/graph/resources.ts
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/graph.ts
- packages/calcite-components/src/demos/graph.html
Add `graph` component tokens.
`--calcite-graph-highlight-fill-color`: Specifies the fill color of the `highlight` element, when present.
> feat(graph): add component tokens

- .github/workflows/issue-notifications.yaml
- packages/calcite-components-react/eslint.config.mjs
- packages/calcite-components/src/01-introduction.mdx
- packages/calcite-components/src/02-contributing.mdx
- packages/calcite-components/src/03-code-of-conduct.mdx
- packages/calcite-components/src/04-licensing.mdx
- packages/calcite-components/src/06-faq.mdx
- packages/calcite-components/src/07-conventions.mdx
- packages/calcite-components/src/15-internationalization.mdx
- packages/calcite-ui-icons/bin/build-fonts.js
- packages/calcite-ui-icons/docs/app.js
- packages/eslint-config-calcite/core.js
- packages/eslint-config-calcite/jsx.js
- packages/eslint-plugin-calcite-components/eslint.config.mjs
- packages/eslint-plugin-calcite-components/src/utils/rule-tester.ts
Format the monorepo using prettier.
> style: run prettier from monorepo root

- packages/calcite-components/src/components/combobox-item/combobox-item.tsx
- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
Fixes prop update delays introduced in #10310 by moving event emitting to Lit's [pre-update phase](https://lit.dev/docs/components/lifecycle/#reactive-update-cycle).
> fix(combobox): improve prop update times

- packages/calcite-components/src/components/meter/meter.scss
**Related Issue:** #10571 
Add `forced-colors` media query to the styles to define a solid color when in high-contrast accessibility mode.
> fix(meter): add fill style for high-contrast mode

- packages/calcite-components/src/components/tree-item/tree-item.tsx
- packages/calcite-components/src/components/tree/tree.e2e.ts
- packages/calcite-components/src/components/tree/tree.stories.ts
**Related Issue:** #10731  
✨🚸☑️🔨✨ 
@driskull Thanks for the patch!
> fix(tree): fix has-children logic

- packages/calcite-components/src/components/chip/chip.scss
- packages/calcite-components/src/components/chip/chip.stories.ts
**Related Issue:** #11353
Resolves issue where close button was not visible on a chip with `kind="inverse"`.
Updates the `withClosable` storybook test to include all versions of chip with `closable` to cover future use cases.
> fix(chip): fix inverse close color

- packages/calcite-components/src/components/segmented-control-item/segmented-control-item.e2e.ts
- packages/calcite-components/src/components/segmented-control-item/segmented-control-item.scss
- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/segmented-control/segmented-control.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/segmented-control.ts
- packages/calcite-components/src/demos/segmented-control.html
Add `segmented-control`, `segmented-control-item` component tokens.
`--calcite-segmented-control-color`: Specifies the component's color.
`--calcite-segmented-control-background-color`: Specifies the component's background color.
`--calcite-segmented-control-border-color`: Specifies the component's border color.
`--calcite-segmented-control-shadow`: Specifies the component's shadow.
`--calcite-segmented-control-icon-color`: Specifies the icons's color.
> feat(segmented-control, segmented-control-item): add component tokens

- packages/calcite-components/src/components/combobox/combobox.e2e.ts
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/tests/utils.ts
**Related Issue:** #10731, #11382
This updates the combobox internal state after an custom item is added.
**Note**: this also adds `createEventTimePropValuesAsserter` to help assert on event-emit time component state.
> fix(combobox): update internal state after custom value is added

- packages/calcite-components/src/components/list-item/utils.ts
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #11397
- use `oldDraggableIndex` and `newDraggableIndex` from https://github.com/SortableJS/Sortable?tab=readme-ov-file#event-object-demo in order to only track the relevant indexes of draggable items via mouse.
- updates keyboard logic for indexes to only consider applicable items.
- updates tests to add slotted content which should not affect event `newIndex/oldIndex`.
> fix(list): drag event properties `newIndex` and `oldIndex` should only reflect list item indexes

- packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts
- packages/calcite-components/src/tests/commonTests/formAssociated.ts
- packages/calcite-components/src/utils/form.tsx
**Related Issue:** #11419
- adds `ariaHidden = "true"` property to the hidden form input when it is created
- adds test in autocomplete
- add formAssociated test to make sure hidden inputs are setting ariaHidden properly
> fix(form): add ariaHidden property to the hidden form input

- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/controllers/useFocusTrap.ts
- packages/calcite-components/src/utils/focusTrapComponent.ts
Fixes an issue where a `focus-trap` instance might be left active after the dialog is removed.
* Adds `useFocusTrap` controller
* Extracts and exports function to create default `focus-trap` options
> fix(dialog): toggle focus-trap on DOM connect and disconnect

- packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts
Fixes the below test failure for `February` month.
https://github.com/Esri/calcite-design-system/blob/f208961506ebb5edc7a21ac40277b77b214ce883/packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts#L513
> test(input-date-picker): date selection is independent of days in month

- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/loader/loader.scss
- packages/calcite-components/src/components/progress/progress.scss
- Remove unnecessary import
- This import is already imported in the includes sass file
> refactor(block, loader, progress): remove unnecessary sass import

- packages/calcite-components/src/components/list-item/utils.ts
- packages/calcite-components/src/components/list/list.tsx
use constant for querySelector and remove unnecessary conditional
> refactor(list, list-item): use constant for querySelector and remove unnecessary conditional

- packages/calcite-components/src/components/text-area/text-area.e2e.ts
- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #10175 
Adds `limitText` prop to restrict input beyond the specified `max-length`, aligning with native behavior.
> feat(text-area): add `limitText` prop to prevent input beyond max-length

- packages/calcite-components/src/components/sheet/sheet.tsx
**Related Issue:** #11452
Adds the `sheet`'s default slot for inclusion in our documentation pages.
> docs(sheet): add default slot for docs

- packages/calcite-components/src/components/table-row/table-row.scss
- packages/calcite-components/src/components/table/table.scss
- packages/calcite-components/src/demos/table.html
**Related Issue:** #11464
Adds a set of styling rules to address a Firefox-specific styling bug with a "not best practice" disclaimer.
Also updates the Table "local demo" to use Dialog instead of Modal.
Note: in FF - the Table ends up being slightly taller because of this adjustment - however, prior to this change, there was a greater difference in height ...
| Before    | After |
| -------- | ------- |
| ![Screenshot 2025-02-05 at 3 11 36 PM](https://github.com/user-attachments/assets/86677e1e-2415-4244-886e-3671cbd01ee1)  | ![Screenshot 2025-02-05 at 3 10 24 PM](https://github.com/user-attachments/assets/159c5310-a8bc-4f94-a388-8ab52accef25)  |
> fix(table): Fix `bordered` styling in Firefox

- packages/calcite-components/src/components/time-picker/time-picker.tsx
Realized the `calciteTimePickerChange` event was missing a description, so this adds one.
> docs(time-picker): add description to time picker change event

- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #10175
Ensures `maxLength` is properly cleared in the internal `<textarea>` when `inputText` is set to `false`. Otherwise, it would be set to `-1`, which could interfere with external test utils.
> refactor(text-area): clear maxLength instead of directly setting it to the default

- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/controllers/useFocusTrap.ts
**Related Issue:** #11345 
Adds missing type to newly added `focusTrapOptions` props.
> fix(dialog, modal, popover): add type to `focusTrapOptions` prop

- packages/calcite-components/src/components/dropdown-group/dropdown-group.scss
- packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/dropdown/resources.ts
Fixes regression caused by https://github.com/Esri/calcite-design-system/pull/10971.
> fix(dropdown): avoid showing scroller when max-items equals items

- packages/calcite-components/src/components/stepper-item/stepper-item.tsx
- packages/calcite-components/src/components/stepper/stepper.e2e.ts
Applies `tabindex` on the host for vertical layout items only, as horizontal ones rely on an internal focusable container.
> fix(stepper-item): keep initial focus on newly selected item

- .github/scripts/iconTeamDiffCheck.js
- .github/workflows/icons-diff-check.yml
Remove the `pull_request_review` trigger event from the `Icon Team Diff Check` workflow. 
The `Icon Team Diff Check` workflow fails if members of the `calcite-icon-designers` team change files outside of the `packages/calcite-ui-icons` path. On failure, the `calcite-design-system-admins` team is assigned for review. 
Previously, the workflow ran on `pull_request_review` approvals and the check passed if the approver was a `calcite-design-system-admins` team member. However, the workflow ran on all PR approvals, which prevented merging for around 20 seconds.
Moving forward, when admins are automatically assigned to review an icon designer's PR, the new action items are:
1. Review the PR to make sure the changes outside of `packages/calcite-ui-icons` make sense. 
- For example, there could …
> ci: stop running icon diff check on pr review submit

- packages/calcite-components/src/components/modal/modal.tsx
Fixes an issue where the modal’s opening logic was invoked before the transition element was available. This adds a simple guard for now, but I’ll revisit later to ensure the method isn’t called until after the component updates.
> fix(modal): fix issue caused by early opening logic calls

- release-please-config.json
By default, release-please only checks 500 commits when searching for the previous release. That number can be increased with the `commit-search-depth` [manifest] option. Changing the value to 1000 will be more than enough according to my calculation:
```sh
git rev-list @esri/calcite-components@2.13.2...origin/main | wc -l # => 793
```
[manifest]: https://github.com/googleapis/release-please/blob/90058f543cd82858539fdc7d1b34eabd348edbee/docs/manifest-releaser.md?plain=1#L243-L249
> ci: increase release-please commit search depth

- packages/calcite-components/src/components/tab-title/tab-title.scss
**Related Issue:** [#10003](https://github.com/Esri/calcite-design-system/issues/10003)
- Increase `bottom-border` to `4px` on `focus` when `selected=true`.
- Change `text-color-3` to `text-color-1` on `hover` and `active` when `bordered=false` and `selected=false`.
- When `bordered=true`:
- Remove `hover` and `active` states when `selected=true`.
- Change `text-color-3` to `text-color-1` on `hover` and `active` when `selected=false`.
> feat(tab-title): enhance component's interactivity states

- packages/calcite-components/src/components/action/action.scss
**Related Issue:** [#10007](https://github.com/Esri/calcite-design-system/issues/10007)
- Remove `hover` styling from the `focus` state.
- Update `active` state `background-color` to `--calcite-color-transparent-press` when `appearance="transparent"`.
> feat(action): enhance component's interactivity states

- .github/workflows/contributors.yml
**Related Issue:** #11503 #11502 #11499 
The contributors action was running on `main` when it should run on `dev`.
> ci: ensure contributors workflow runs on dev

- examples/components/angular/README.md
- examples/components/angular/src/app/app.component.ts
- examples/components/react/README.md
- examples/components/react/src/App.tsx
Update the react and angular examples to fix module import errors due to changes in the v3 release.
> docs(examples): update module imports after 3x breaking change

- packages/calcite-components/src/components/accordion/accordion.e2e.ts
- packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
- packages/calcite-components/src/components/stepper/stepper.e2e.ts
**Related Issue:** #11407
Fix tests for inheritable props getting passed to items from parents.
> test(dropdown, accordion, stepper): fix tests for inheritable props

- packages/calcite-components/src/components/loader/loader.scss
- packages/calcite-components/src/components/loader/loader.tsx
**Related Issue:** #11518
Updates `loader`'s properties and css variables descriptions to reflect the updated use.
> docs(loader): update references to reflect component use

- packages/calcite-components/src/components/block-group/block-group.e2e.ts
- packages/calcite-components/src/components/block-group/block-group.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #11513
- Fix keyboard moving `MoveTo` object to always have unique identifiers
- Previously, it was using the incorrect id
- There's no reason to use the element id so just using a guid makes more sense here
- Add tests
> fix(list, block-group): drag menu 'Move to' actions broken when list elements have explicit ids

- packages/calcite-components/src/components/split-button/split-button.e2e.ts
- packages/calcite-components/src/components/split-button/split-button.stories.ts
- packages/calcite-components/src/components/split-button/split-button.tsx
- packages/calcite-components/src/demos/split-button.html
**Related Issue:** #9126 
Implemented ability to make the primary part of a split button into a downloadable link or an href link.
> feat(split-button): make downloadable and linkable

- packages/calcite-components/src/components/segmented-control-item/segmented-control-item.scss
**Related Issue:** [#10013](https://github.com/Esri/calcite-design-system/issues/10013)
Update focus ring `z-index` to sit on top of border container.
> feat(segmented-control-item): enhance component's interactivity states

- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/controllers/useFocusTrap.ts
**Related Issue:** #11523 
Internal calls to `updateFocusTrap` caused user-provided `extraContainers` to be lost. This updates `useFocusTrap` to maintain stateful focusable containers for subsequent updates.
> fix(dialog, modal, sheet): preserve focus-trap extra containers across internal trap updates

- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
**Related Issue:** #11523 
https://github.com/Esri/calcite-design-system/pull/11548 missed calling the internal update focus trap method, using the public method instead, which clears user-specified `extraContainers`.
> fix(dialog, modal, popover, sheet): fixes an issue that caused extra containers to be lost after internal trap updates

- packages/calcite-components/src/components/tooltip/TooltipManager.ts
- packages/calcite-components/src/components/tooltip/tooltip.e2e.ts
**Related Issue:** #11541
- Close tooltip even when `pointer-move` event is cancelled
- Add test
> fix(tooltip): close tooltips on prevented pointer move events

- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/components/sortable-list/sortable-list.tsx
> docs(list, sortable-list): remove consecutive spaces in documentation

- packages/calcite-components/src/controllers/useFocusTrap.ts
Removes unused `activate`/`deactivate` override options to ensure focus traps work consistently by using initial options.
> refactor(useFocusTrap): remove activate/deactivate override options for consistent behavior

- packages/calcite-components/src/components/segmented-control-item/segmented-control-item.scss
**Related Issue:** [#11578](https://github.com/Esri/calcite-design-system/issues/11578)
Use `--calcite-z-index` css token instead of hardcoded value to correctly display focus ring.
> refactor(segmented-control-item): use --calcite-z-index css token instead of hardcoded value

- packages/calcite-components/src/controllers/useFocusTrap.ts
**Related Issue:** #11527 
This updates `useFocusTrap` to toggle the trap accordingly if `focusTrapDisabled` is modified at runtime.
**Note**: Testing for this and other controllers will be addressed in https://github.com/Esri/calcite-design-system/issues/11305 and https://github.com/Esri/calcite-design-system/issues/11558.
> fix(dialog, modal, popover, sheet): restore `focusTrapDisabled` reactiveness

- packages/calcite-components/src/components/graph/graph.e2e.ts
- packages/calcite-components/src/components/graph/util.ts
- packages/calcite-components/src/components/slider/slider.stories.ts
**Related Issue:** #11583 
Fixes histogram clipping by ensuring the y range accounts for the dataset’s min value. Previously, the y-axis scaling didn’t account for non-zero min values, leading to incorrect positioning and clipping.
* Most histogram slider screenshot tests were merged into one as they are similar
* Added a histogram slider creator function for reuse between stories
* Removed E2E tests that relied on implementation details and were covered by screenshot tests
> fix(slider): ensure histograms with non-zero min are displayed correctly

- packages/calcite-components/src/components/rating/rating.e2e.ts
- packages/calcite-components/src/components/rating/rating.scss
- packages/calcite-components/src/components/rating/rating.tsx
- packages/calcite-components/src/custom-theme/rating.ts
**Related Issue:** [#10015](https://github.com/Esri/calcite-design-system/issues/10015)
- Update star icon to `fill` on `:hover`.
- Update star icon color to `--calcite-color-brand-hover` on `:hover`.
- Update star icon color to `--calcite-color-brand-press` on `:active`.
- Add `--calcite-rating-color-press` css token.
> feat(rating): enhance component's interactivity states

- packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts
- packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #10028
This fixes an error caused by `dropdown-group`s looking up their parent element. It updates `dropdown` to set the position directly on groups, avoiding parent lookups.
> fix(dropdown-group): fix error caused by early removal

- .lintstagedrc.js
- packages/calcite-components/.lintstagedrc.js
This came up in https://github.com/Esri/calcite-design-system/pull/11608 where committing CSS would cause the following error:
```
✔ Backed up original state in git stash (43c49791f)
⚠ Running tasks for staged files...
❯ .lintstagedrc.js — 12 files
✔ *.{json,html,yml} — 3 files
❯ *.css — 2 files
✖ stylelint --fix [FAILED]
◼ prettier --write
↓ *.md — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
✖ stylelint --fix:
Error: No configuration provided for /.../calcite-design-system/examples/components/preact/src/routes/home/style.module.css
at configurationError (/.../calcite-design-system/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
at getConfigForFile …
```
> chore(linting): move stylelint `lint-staged` command to `calcite-components` to prevent config errors

- .github/scripts/closeNeedMoreInfoIssues.js
- .github/scripts/support/resources.js
- .github/workflows/close-needs-more-info-issues.yml
**Related Issue:** #11235 
- Adds action to run daily at midnight UTC that will check for issues with the `need more info` and close them if it's been 2 weeks or more without any updates. 
- Tested in personal action testing repo.
> ci(actions): add action to close issues without enough information

- packages/calcite-components/src/components/card-group/card-group.scss
**Related Issue:** #11637 
Updates token to restore card group gap
> fix(card-group): Restore default gap spacing

- packages/calcite-components/src/components/block-section/block-section.e2e.ts
- packages/calcite-components/src/components/block-section/block-section.scss
- packages/calcite-components/src/components/block-section/block-section.tsx
- packages/calcite-components/src/components/block-section/resources.ts
- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/block/block.stories.ts
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/block/resources.ts
- packages/calcite-components/src/demos/block.html
**Related Issue:** #6473, #11225
Deprecate `open` prop in favor of `expanded`. Add logger warning for deprecation to help inform users about the deprecated property and guide them towards using the recommended alternatives.
> feat(block, block-section): add `expanded` property and deprecate `open` property

- packages/calcite-components/readme.md
Removes the extraneous, and no longer needed CDN stylesheet reference.
> docs: remove extraneous stylesheet reference

- packages/calcite-design-tokens/src/semantic/color.json
- packages/calcite-design-tokens/support/tests/__snapshots__/index.spec.ts.snap
**Related Issue:** #10510  
Removes the global focus color introduced in [#10512](https://github.com/Esri/calcite-design-system/pull/10512) to match the behavior of the deprecated `--calcite-ui-focus-color`. Previously, `--calcite-color-focus` was defined at `:root`, preventing it from inheriting updates to `--calcite-color-brand` (its fallback).  
This is **not** considered a breaking change because:  
* it only affects outputs that are not publicly documented
* the default color will still be applied as expected
* `--calcite-color-focus` remains available for overriding the focus color
**Note**: https://github.com/Esri/calcite-design-system/issues/11713 will restore `--calcite-color-focus` after #11391 lands.
> fix: allow global focus color token to inherit fallback value

- packages/calcite-components/src/components/text-area/resources.ts
- packages/calcite-components/src/components/text-area/text-area.e2e.ts
- packages/calcite-components/src/components/text-area/text-area.tsx
**Related Issue:** #11514
Updates internal measuring logic to check for references before calling `Element.getBoundingClientRect()` since `ref`s can be cleared when a ref is updated and the element is disconnected.
> fix(text-area): fix error caused by internal measuring on disconnect

- packages/calcite-components/src/components/tabs/resources.ts
- packages/calcite-components/src/components/tabs/tabs.e2e.ts
- packages/calcite-components/src/components/tabs/tabs.tsx
> refactor(tabs): use tag selector

- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/components/combobox/combobox.scss
Tweaks the token documentation descriptions for the `combobox` and `combobox-item` components.
> docs(combobox, combobox-item): update token descriptions

- packages/calcite-components/src/components/fab/fab.e2e.ts
- packages/calcite-components/src/components/fab/fab.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/fab.ts
Reverts the `fab` component tokens for release.
This reverts commit 5f97278d442dea0ddfbd7ebb0f1718eb7d5c25d1.
> revert(fab): add component tokens

- packages/calcite-ui-icons/docs/keywords.json
**updated tags**
updated tags for check icon
> fix: update tags

- packages/calcite-components/src/components/input-message/input-message.e2e.ts
- packages/calcite-components/src/components/input-message/input-message.scss
- packages/calcite-components/src/components/input-message/resources.ts
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/input-message.ts
Adds the following tokens to `input-message` component:
`--calcite-input-message-icon-color`: Specifies the component's icon color.
`--calcite-input-message-spacing`: Specifies the top margin space above the component.
Deprecates `--calcite-input-message-spacing-value`: Specifies the top margin space above the component.
> feat(input-message): add component tokens and deprecate --calcite-input-message-spacing-value

- package.json
- packages/calcite-design-tokens/package.json
- packages/calcite-ui-icons/package.json
- packages/eslint-plugin-calcite-components/package.json
> chore: include all node_modules dirs in clean script

- packages/calcite-components/src/components/list-item/list-item.scss
**Related Issue:** [#10018](https://github.com/Esri/calcite-design-system/issues/10018)
- Update `:active` background color to `--calcite-color-foreground-3`.
- Update icon-start | end to `--calcite-color-text-1` when `:hover` / `:active`.
- Remove `:hover` ghosted selection border in `selection-appearance=“border”`.
- Update chevron to change to `--calcite-color-text-1` only when hovering its hit area.
> feat(list-item): enhance component's interactivity states

- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/components/popover/resources.ts
Fix casing inconsistency to ensure the `header-container` class is consistently applied and styled across the `popover` component.
> refactor(popover): fix casing inconsistency

- .github/workflows/contributors.yml
**Related Issue:** #11853
I removed hardcoded tabs from the contributors action, which should fix the formatting related pull requests.
ref: https://github.com/benelan/contributors-readme-action/commit/c26b918f4f14ace216690e1d64daae255c00e70b
> ci: prevent contributors PRs due to formatting

- LICENSE.md
- README.md
- packages/calcite-components-react/LICENSE.md
- packages/calcite-components-react/README.md
- packages/calcite-components/LICENSE.md
- packages/calcite-components/README.md
- packages/calcite-design-tokens/LICENSE.md
- packages/calcite-design-tokens/README.md
- packages/calcite-ui-icons/LICENSE.md
- packages/calcite-ui-icons/README.md
- packages/eslint-config-calcite/LICENSE.md
- packages/eslint-plugin-calcite-components/LICENSE.md
- packages/eslint-plugin-calcite-components/README.md
**Related Issue:** #8950
Directs users to Calcite's [Licensing](https://developers.arcgis.com/calcite-design-system/resources/licensing/) page, and licensing requirements - which is Calcite's source of truth for licensing.
cc @juliepowell
> docs(licensing): refer users to the licensing documentation page

- packages/calcite-components/src/components/fab/fab.e2e.ts
- packages/calcite-components/src/components/fab/fab.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/fab.ts
Adds the following tokens for `fab` component.
`--calcite-fab-background-color`: Specifies the component's background color.
`--calcite-fab-border-color`: Specifies the component's border color.
`--calcite-fab-corner-radius`: Specifies the component's corner radius.
`--calcite-fab-text-color`: Specifies the component's text color.
`--calcite-fab-loader-color`: Specifies the component's loader color.
`--calcite-fab-shadow`: Specifies the component's shadow.
> feat(fab): add component tokens

- .github/workflows/pr-e2e.yml
- packages/calcite-design-tokens/package.json
- packages/calcite-design-tokens/src/build/format/docs.ts
- packages/calcite-design-tokens/tests/spec/index.spec.ts
- turbo.json
This ensures token snapshot tests run consistently by always replacing the timestamp field in JSON files, if present.  
The workflow introduced in https://github.com/Esri/calcite-design-system/pull/11831 requires a special test build before running tests, which isn't always applicable. This was causing failures in the `deploy-prerelease` action ([example](https://github.com/Esri/calcite-design-system/actions/runs/14274033634/job/40013441322)), which runs token tests after a production build.
> test: avoid timestamp comparison regardless of build or test context

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
**Related Issue:** [#10017](https://github.com/Esri/calcite-design-system/issues/10017)
- Update `:active` background color to `--calcite-color-foreground-3`.
- Update description to `--calcite-color-text-2` when `expanded`.
- Update icon-start | end to `--calcite-color-text-1` when `expanded`.
> feat(block): enhance component's interactivity states

- packages/calcite-components/src/assets/styles/_sortable.scss
**Related Issue:** #11871
- In FF, the `overflow:hidden` on the chosen class was causing the drag and drop to break
- In this PR, unnecessary styles are removed in order to prevent the breakage and any future breakage
- No tests are present because our testing is chromium based
> fix: remove unused dragging styles

- packages/calcite-components/src/assets/styles/_sortable.scss
**Related Issue:** #11871
- In FF, the `overflow:hidden` on the chosen class was causing the drag
and drop to break
- In this PR, unnecessary styles are removed in order to prevent the
breakage and any future breakage
- No tests are present because our testing is chromium based
> fix: remove unused dragging styles (#11883)

- .github/scripts/lint-staged.config.mjs
- lint-staged.config.mjs
- package-lock.json
- package.json
- packages/calcite-components/lint-staged.config.mjs
- packages/calcite-design-tokens/lint-staged.config.mjs
- packages/calcite-design-tokens/package.json
- packages/calcite-design-tokens/tsconfig-eslint.json
Fixes errors that came up after recent linting-related updates.
* Resolves `markdownlint-cli2` config path properly
* Ensures `.mjs` files are included in ESLint configs (TS-related)
* Prevents `markdownlint-cli2` from processing `node_modules` in packages by moving dev dependencies to the root
* Adds type annotations to `lint-staged.config.mjs` files
> chore(linting): fix `lint-staged` errors

- packages/calcite-components/src/components/shell/shell.e2e.ts
- packages/calcite-components/src/components/shell/shell.scss
Adds the following tokens for `shell` component.
- --calcite-shell-border-color: Specifies the component's border color.
- --calcite-shell-tip-spacing: [Deprecated] This component has been deprecated. The left and right spacing of the `calcite-tip-manager` when slotted in the component.
> feat(shell): add component tokens

- packages/calcite-design-tokens/.prettierignore
Source tokens are managed by the Tokens Studio plugin, which syncs directly with GitHub. This bypasses pre-commit hooks, so it's not able to lint the JSON as expected, leading to inconsistent diffs in design token PRs.
> chore: exclude token source from formatting

- packages/calcite-components/package.json
Adds passthrough arg support to `test` script missed in https://github.com/Esri/calcite-design-system/pull/11877.
> chore: allow passthrough-args to test script

- lint-staged.config.mjs
- packages/calcite-components/support/generateSupportedBrowsersJSON.ts
- packages/calcite-components/support/generateT9nDocsJSON.ts
- packages/calcite-design-tokens/src/build/utils/node.ts
- packages/calcite-design-tokens/tests/spec/index.spec.ts
Uses [`import.meta.dirname`](https://nodejs.org/api/esm.html#importmeta) to replace
```tsx
dirname(fileURLToPath(import.meta.url));
```
> refactor: tidy up

- packages/calcite-components/src/components/input-number/input-number.e2e.ts
- packages/calcite-components/src/components/input-number/input-number.tsx
**Related Issue:** #10271
- Cancel ArrowDown event using preventDefault()
- Add tests
> fix(input-number): cancel arrow down event

- packages/calcite-components/vite.config.ts
**Related Issue:** #11877
Make vitest default to the stable tests when the `EXPERIMENTAL_TESTS` environment variable is not set. Previously, `npx vitest` would not find any tests to run.
This change fixes the test runner integrations provided by some IDEs (including neovim and vscode).
> [!NOTE]
> We can probably get rid of the `STABLE_TESTS` environment variable with this change.
> ci: default to stable tests when experimental mode is not set

- packages/calcite-components/src/components/input-number/input-number.e2e.ts
- packages/calcite-components/src/components/input-number/input-number.tsx
**Related Issue:** #11324 
Resolve an issue where inputs in some locales would not fire the change event when clearing a value that was set programmatically via the property.
> fix(input-number): ensure change event correctly fires for all locales

- packages/calcite-components/src/components/tab/tab.e2e.ts
- packages/calcite-components/src/components/tab/tab.scss
**Related Issue:** #10419 
Fixes an issue where the focus outline would be included in the scrolled content.
> fix(tab): fix focus outline placement on scrolling tabs

- packages/calcite-components/src/components/button/button.e2e.ts
- packages/calcite-components/src/components/chip/chip.e2e.ts
- packages/calcite-design-tokens/src/tokens/core/opacity.json
- packages/calcite-design-tokens/src/tokens/semantic/color/dark.json
- packages/calcite-design-tokens/src/tokens/semantic/color/light.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #11565 
- Adds 2 core opacity tokens
- Updates opacities for semantic transparency hover/press dark theme tokens
- Adds semantic transparency-inverse hover/press tokens
> feat(tokens): add transparency-inverse tokens

- package-lock.json
- packages/calcite-tailwind-preset/package.json
Adding explicit `calcite-design-tokens` dev dependency to the Tailwind preset package so Lerna can detect changes and update local packages correctly (see https://github.com/lerna/lerna/issues/955#issuecomment-323260292).
This resolves `next` [deployment issues](https://github.com/Esri/calcite-design-system/actions/runs/14537811536/job/40789636366) caused by missing peer dependencies.
> chore: add design-tokens as dev dependency for Lerna updates

- packages/calcite-design-tokens/src/tokens/core/color.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #11725 
cc @trailtraveler
This updates 15 of the `core.color.neutral` token values. Calcite does currently reference most of these tokens in the `semantic` colors, but the changes are so subtle that no changes to components are anticipated.
Before/after comparisons:
> feat(tokens): update core neutral color values

- packages/calcite-design-tokens/src/build/preprocessors/store-same-value-theme-tokens.ts
- packages/calcite-design-tokens/src/build/transforms/value/merge-value.ts
- packages/calcite-design-tokens/src/tokens/semantic/color/dark.json
- packages/calcite-design-tokens/src/tokens/semantic/color/light.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** [#7798](https://github.com/Esri/calcite-design-system/issues/7798)
Update the following semantic tokens to resolve contrast issues:
LIGHT MODE
status/warning/default → `color/high-saturation/orange-yellow/h-oy-060`
status/warning/hover → `color/vibrant/orange-yellow/v-oy-180`
status/warning/press → `color/high-saturation/orange-yellow/h-oy-080`
DARK MODE
status/warning/default → `color/high-saturation/orange-yellow/h-oy-060`
status/warning/hover → `color/vibrant/orange-yellow/v-oy-120`
status/warning/press → `color/vibrant/orange-yellow/v-oy-140`
> fix(semantic-tokens): provide sufficient warning color contrast across components

- packages/calcite-components/src/components/list-item/list-item.scss
**Related Issue:** [#11031](https://github.com/Esri/calcite-design-system/issues/11031)
Add bottom spacing to fix misalignment of elements to the left of the item's content.
> fix(list-item): align elements to the left of the item's content

- packages/calcite-components/src/components/button/button.scss
**Related Issue:** [#11576](https://github.com/Esri/calcite-design-system/issues/11576)
For `appearance="transparent"` `kind="inverse"`:
- Update `:hover` to `--calcite-color-transparent-inverse-hover` background change instead of a stroke width change.
- Update `:press` to a `--calcite-color-transparent-inverse-press` background change instead of a stroke width change.
> feat(button): enhance component's interactivity states

- packages/calcite-components/src/components/time-picker/time-picker.e2e.ts
- packages/calcite-components/src/components/time-picker/time-picker.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/time-picker.ts
Adds the following tokens for `time-picker` component.
- --calcite-time-picker-background-color: The background color of the time picker.
- --calcite-time-picker-corner-radius: The border radius of the time picker.
- --calcite-time-picker-button-background-color-hover: Specifies the button's background color when hovered or focused.
- --calcite-time-picker-button-background-color-press: Specifies the button's background color when active.
- --calcite-time-picker-color: Specifies the component's background color.
- --calcite-time-picker-icon-color: Specifies the component's icon color.
- --calcite-time-picker-input-border-color-press: Specifies the input's border color when active.
- --calcite-time-picker-input-border-color-hover: Specifies the input's border color …
> feat(time-picker): add component tokens

- package-lock.json
- package.json
- packages/calcite-components/package.json
- packages/calcite-components/vite.config.ts
* properly separate Vitest browser-mode and Puppeteer tests
* explicitly set `playwright` as provider
* explicitly install Playwright before browser mode test runs (workaround)
* move `playwright` dev dependency close to `@vitest/browser`
> chore: tweak experimental test setup

- packages/calcite-components/vite.config.ts
Fixes issue with test configuration that was missed in https://github.com/Esri/calcite-design-system/pull/12017 that caused E2E tests to be skipped.
> chore: fix test include/exclude

- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
- packages/calcite-design-tokens/tests/spec/index.spec.ts
Updates snapshot identifier to distinguish internal output tests from public.
> chore: use internal label for internal token output snapshots

- packages/calcite-components/tailwind.config.ts
- packages/calcite-tailwind-preset/src/index.ts
Moves custom animation utils that depend on `calcite-components` internals into the package.
> refactor: keep internal animation Tailwind utils scoped to components

- packages/calcite-components/src/components/sheet/sheet.e2e.ts
- packages/calcite-components/src/components/sheet/sheet.scss
- packages/calcite-components/src/components/sheet/sheet.tsx
Adds the following tokens:
- --calcite-sheet-background-color: Specifies the background color of the sheet.
- --calcite-sheet-corner-radius: Specifies the corner radius of the component.
- --calcite-sheet-shadow: Specifies the shadow of the component.
- --calcite-sheet-text-color: Specifies the text color of the component.
- --calcite-sheet-resize-background-color: Specifies the background color of the resize handle.
- --calcite-sheet-resize-icon-color: Specifies the text color of the resize handle.
> feat(sheet): add component tokens

- packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
**Related Issue:** #11399 
Updates `input-date-picker` to use `Intl.DateTimeFormat` utils that normalize locales.
> fix(input-date-picker): ensure ar-fallback when the locale is ar-SA

- package-lock.json
- packages/calcite-components/package.json
**Related Issue:** #12044 
Restores dependency ranges (^) that were unintentionally removed by https://github.com/Esri/calcite-design-system/pull/11925 (see https://github.com/Esri/calcite-design-system/pull/11190/ for previous approach).
> build(deps): restore ^ range for @arcgis deps

- packages/calcite-design-tokens/src/tokens/semantic/corner.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #11906 
- Deprecates 2 semantic corner-radius tokens
- Adds 3 new semantic corner-radius tokens - 2 replacements and 1 new with a new value of 2px
deprecate(semantic-tokens): mark old corner-radius tokens as deprecated
> feat(semantic-tokens): update and add to corner-radius tokens

- packages/calcite-components/src/components/action-menu/action-menu.e2e.ts
- packages/calcite-components/src/components/action-menu/action-menu.tsx
**Related Issue:** #12048
- stop propagation of internal popover events
- add tests
> fix(action-menu): stop propagation of internal popover events

- packages/calcite-components/src/components/filter/filter.e2e.ts
- packages/calcite-components/src/components/filter/filter.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/filter.ts
Adds the following tokens for `filter` component.
- --calcite-filter-content-space: Specifies the padding of the component's content.
- --calcite-filter-input-background-color: Specifies the input's background color.
- --calcite-filter-input-border-color: Specifies the input's border color.
- --calcite-filter-input-corner-radius: Specifies the input's corner radius.
- --calcite-filter-input-shadow: Specifies the shadow around the input.
- --calcite-filter-input-icon-color: Specifies the input's icon color.
- --calcite-filter-input-text-color: Specifies the input's text color.
- --calcite-filter-input-placeholder-text-color: Specifies the input's placeholder text color.
- --calcite-filter-input-actions-background-color: Specifies the background color of the input's …
> feat(filter): add component tokens

- packages/calcite-design-tokens/src/tokens/semantic/color/dark.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #12067 
Replaces the value for `--calcite-color-foreground-current` (dark) from a hex code to our equivalent core token
> refactor(semantic-tokens): update `--calcite-color-foreground-current` (dark) reference

- packages/calcite-components/src/components/navigation/navigation.e2e.ts
- packages/calcite-components/src/components/navigation/navigation.scss
**Related Issue:** #11022
- Add missing CSS `display: block;` to host
- ~~could be considered a breaking change~~ considered a fix, not a breaking change. 
- add test
> fix(navigation): add missing css display

- packages/calcite-components/src/utils/locale.spec.ts
- packages/calcite-components/src/utils/locale.ts
**Related Issue:** #11978 
- Add support for `nn` locale which maps to `no`
- removes `t9n` context from locale util since it is handled by lumina controller.
> feat: support  `nn` locale

- packages/calcite-components/src/components/dropdown/dropdown.tsx
**Related Issue:** #11781
Removes explicit open event listeners in favor of open/close hooks.
> refactor(dropdown): tidy up `setFocus` calls

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/modal/modal.e2e.ts
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/sheet/sheet.e2e.ts
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/tests/commonTests/focusTrap.ts
**Related Issue:** #11781
Fixes an issue that caused focus-trapping components with `initialFocus` disabled to be ignored.
* to avoid a breaking change, components with `focusTrapDisabled` will still focus on opening
* this will likely change in a future version and require developers to call `setFocus` after opening
* adds starter `focusTrap` common test util to cover this behavior
* improves test coverage for `dialog`'s focus-trapping test group
> fix(dialog, modal, sheet): honor `initialFocus` when opening components

- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
**Related Issue:** #12078
- fixes setFocus method in safari by waiting for component to be focusable before proceeding to focus internal component
> fix(autocomplete): fix setFocus method in Safari

- packages/calcite-components/src/components/time-picker/time-picker.tsx
**Related Issue:** #12090
This PR addresses refactor review comments from #11712.
> refactor(input-time-picker): use private computed property for step precision

- packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #10648 
Addresses a memory leak where floating-ui cleanup was not invoked when the component had missing elements. Tear down should always occur if it was previously registered, regardless of component state.
Our test environment doesn't cover memory profiling, so no tests were added.
> fix: fix memory leak caused when disconnecting floating-ui

- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
**Related Issue:** #11712
This PR fixes a critical issue caused by changes added in #11712 that caused multiple instances of `calcite-input-time-picker` on a single page to get updated when only 1 instance's value changed.
> fix(input-time-picker): isolate calciteTimeChange event listener to just the component instance it was fired from

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/custom-theme/block.ts
**Related Issue:** [#11888](https://github.com/Esri/calcite-design-system/issues/11888)
Add specific css tokens:
`--calcite-block-description-text-color`: Specifies the component's `description` text color.
`--calcite-block-icon-color`: Specifies the component's `collapsible` icon, `iconStart` and `iconEnd` color.
`--calcite-block-icon-color-hover`: Specifies the component's `collapsible` icon color when hovered.
> feat(block): add specific component css tokens

- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/panel/resources.ts
**Related Issue:** #12104
Fixes typo preventing pressed action background color prop from applying.
**Note**: adds test coverage for other CSS props
> fix(panel): fix `--calcite-panel-header-action-text-color-press`

- packages/calcite-components/src/components/action-bar/action-bar.e2e.ts
- packages/calcite-components/src/components/action-bar/action-bar.scss
- packages/calcite-components/src/components/action-bar/action-bar.stories.ts
- packages/calcite-components/src/components/action-bar/action-bar.tsx
- packages/calcite-components/src/components/action-bar/resources.ts
- packages/calcite-components/src/components/action-bar/utils.ts
- packages/calcite-components/src/components/action-pad/action-pad.tsx
- packages/calcite-components/src/components/shell-panel/resources.ts
- packages/calcite-components/src/components/shell-panel/shell-panel.e2e.ts
- packages/calcite-components/src/components/shell-panel/shell-panel.scss
- packages/calcite-components/src/components/shell-panel/shell-panel.tsx
- packages/calcite-components/src/demos/action.html
**Related Issue:** #7507
- Adds `floating` property to `action-bar`
- Moves `pointer-events-auto` styling on action bar to `shell-panel` where it is needed.
- Deprecates `action-pad`
- Add tests
- Add stories
> feat(action-bar): add floating property and "grid" layout value

- packages/calcite-components/src/components/action-bar/action-bar.tsx
- packages/calcite-components/src/components/action-bar/utils.ts
- packages/calcite-components/src/utils/overflow.spec.ts
- packages/calcite-components/src/utils/overflow.ts
**Related Issue:** #7507
- Moves overflow logic to a utility for use by other components
- Adds spec tests for utility
- Updates utility to use the size of each item rather than an average size of all items. Falls back to largest item if item size is 0.
> refactor(action-bar): improve accuracy of overflow item count

- packages/calcite-tailwind-preset/tsconfig-base.json
Uses `node16` instead of `node18` (invalid) as the module resolution.
Preset build was working since the default is `node16` when module is `node18` (see https://www.typescriptlang.org/tsconfig/#moduleResolution).
> build(preset): use valid TS module resolution

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/components/action/action.scss
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/chip/chip.scss
- packages/calcite-components/src/components/color-picker-swatch/color-picker-swatch.scss
- packages/calcite-components/src/components/combobox-item/combobox-item.scss
- packages/calcite-components/src/components/date-picker-month-header/date-picker-month-header.scss
- packages/calcite-components/src/components/dropdown-item/dropdown-item.scss
- packages/calcite-components/src/components/meter/meter.scss
- packages/calcite-components/src/components/stepper-item/stepper-item.scss
- packages/calcite-components/src/components/switch/switch.scss
- packages/calcite-components/src/components/tile-select/tile-select.scss
- packages/calcite-components/src/tests/commonTests/themed.ts
- packages/calcite-components/tailwind.config.ts
- packages/calcite-tailwind-preset/src/index.ts
**Related Issue:** #12170
This ensures `--calcite-duration-factor` is honored in Tailwind transition utilities (e.g., `transition-color`).
Also, this improves test consistency in cases like the `themed` test helper, where animations are expected to be disabled via `--calcite-duration-factor` (required by https://github.com/Esri/calcite-design-system/issues/10433).
> fix: ensure transition-duration is used in Tailwind utils

- packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts
- packages/calcite-components/src/components/segmented-control/segmented-control.tsx
- packages/calcite-components/src/tests/utils/puppeteer.ts
**Related Issue:** #10595 
Updates `calcite-segmented-control` to apply focus only when selection changes result from user actions.
> fix(segmented-control): avoid changing focus from programmatic item selection

- packages/calcite-components/src/runtime.ts
- packages/calcite-components/src/utils/globalScript.ts
**Related Issue:** #10038
1. Don't log calcite version message in tests as it adds noise in tests and can even cause tests to fail (see #10038 for details)
2. Delay emission of a console message until a microtask to give users more time to disable the console message. This is the exact same change I implemented in Lit: https://github.com/lit/lit/pull/4901 - see that pr and associated issue for reasoning
- In case of calcite, the console message can be disabled by running `(globalThis as { calciteConfig?: { version?: string } }).calciteConfig ??= { version: " " };` before the microtask fires
> feat: make version console message easier to disable

- packages/calcite-components/src/components/popover/popover.tsx
- packages/calcite-components/src/components/tooltip/tooltip.tsx
**Related Issue:** #12200 
Update property description for `referenceElement` on `tooltip` and `popover` to include a not that those components should not be placed within their referenc eelements.
> docs(popover, tooltip): add note to not place components in their refernce elements

- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #12185
- fixes setting `setPosition` and `setSize` correctly on sort handle with nested lists
- adds test for list
> fix(list): reorder options not shown in nested list drag menus

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.scss
- packages/calcite-components/src/components/dialog/dialog.stories.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/flow-item/flow-item.e2e.ts
- packages/calcite-components/src/components/flow-item/flow-item.scss
- packages/calcite-components/src/components/flow-item/flow-item.stories.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/panel/panel.stories.ts
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/panel/resources.ts
- packages/calcite-components/src/demos/panel.html
**Related Issue:** #10265
- adds `icon` property to `panel`, `flow-item` and `dialog` components
- adds `iconFlipRtl` property to `panel`, `flow-item` and `dialog` components
- adds `--calcite-dialog-icon-color` css var to `dialog`
- adds `--calcite-flow-icon-color` css var to `flow-item`
- adds `--calcite-panel-icon-color` css var to `panel`
- adds tests
- adds stories
- add demo html
> feat(dialog, panel, flow-item): add `icon` and `iconFlipRtl` properties

- packages/calcite-components/src/components/dialog/dialog.e2e.ts
- packages/calcite-components/src/components/dialog/dialog.tsx
**Related Issue:** #10252
- restricts minimum sizing for width/height when resizing
- add tests
> fix(dialog): restrict resizing once minimum size has been reached

- package-lock.json
- package.json
- packages/calcite-components/src/assets/styles/_animation.scss
- packages/calcite-components/src/assets/styles/_floating-ui.scss
- packages/calcite-components/src/assets/styles/_spacing.scss
- packages/calcite-components/src/assets/styles/global.scss
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/modal/modal.scss
`calcite-base` is a legacy dependency that is used for a small set of Sass variables. This PR drops it as dependency by inlining some values within our style files. 📦✂️
- This will help with #10585 and #10583
- I'll create a follow-up issue to replace `$baseline`, `$easing-function` and `$floating-ui-shadow` with token or alternate styling (if applicable)
> refactor: drop calcite-base dep

- packages/calcite-components/src/components/link/link.e2e.ts
- packages/calcite-components/src/components/link/link.scss
- packages/calcite-components/src/components/link/link.tsx
**Related Issue:** #10728
- Changes the internal element from a `span` to a `button` to handle enter key events to trigger click event
- Removes setting role on `span` as a `link` since its a `button` now
- Updates tests
- Adds test for use case
- Updates styles
> fix(link): Emit click event on enter key when the component doesn't have href defined

- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/controllers/time/time.ts
**Related Issue:** #12090
This PR updates `input-time-picker` to use the functional `useTime` controller to match the pattern with other controllers.
> refactor(input-time-picker): add useTime functional controller

- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/controllers/time/time.ts
**Related Issue:** #12230
Sets the internal value whenever the `value` prop changes to keep the input in sync. This ensures the controller’s user-set value stays up to date since it could get out of sync if a user-driven time-picker update is followed by a programmatic one.
> fix(input-time-picker): ensure programmatic value setting updates input display

- packages/calcite-components/src/components/color-picker/color-picker.e2e.ts
- packages/calcite-components/src/components/color-picker/color-picker.tsx
**Related Issue:** #12227 
Updates the color-to-channels logic to use rounding instead of flooring each channel's value. 
**Note**: this behavior has been in place [since the component was introduced](https://github.com/Esri/calcite-design-system/pull/592/files#diff-406257c24372573bea6f61d161e358c1f9f33be0c23530546c53618a2342a0f2R927).
> fix(color-picker): ensure channel values are rounded

- CONTRIBUTING.md
Convention documents had been moved into the `packages/calcite-components/conventions` folder, breaking links in the main `CONTRIBUTING.md` file.
This PR updates the broken relative links to the new convention documents using absolute URLs. Unsure if they should be relative rather than absolute.
> docs(CONTRIBUTING): update broken links to Convention docs to use correct paths

- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/utils/label.ts
**Related Issue:** #12153
This fixes an issue with `calcite-input-time-picker` where setting a `label` attribute wouldn't apply correctly, resulting in an accessibility warning.
> fix(input-time-picker): add label property

- packages/calcite-components/src/components/button/button.tsx
**Related Issue:** #12294
To stay in line with the [Best Practices - Recommendations](https://developers.arcgis.com/calcite-design-system/components/button/#recommendations), updates the `loading` property JSDoc to communicate only the busy indicator behavior. The JSDoc previously stated that the `loading` prop disabled interaction, which is incorrect.
> docs(button): correct conflicting JSDoc for `loading` prop

- packages/calcite-components/src/components/block-section/block-section.e2e.ts
- packages/calcite-components/src/components/block-section/block-section.tsx
**Related Issue:** #11053 
Use appropriate class name for `icon-end` element which is using `icon--start` before.
> refactor(block-section): use appropriate class name for `icon-end` element

- packages/calcite-components/src/components/stepper-item/resources.ts
- packages/calcite-components/src/components/stepper-item/stepper-item.scss
- packages/calcite-components/src/components/stepper-item/stepper-item.tsx
- packages/calcite-components/src/components/stepper/stepper.stories.ts
**Related Issue:** #10717 
Removes extra margin space when slotted content is empty in stepper-item.
> fix(stepper-item): remove margin when slotted content is empty

- packages/calcite-components/src/04-licensing.mdx
- packages/calcite-components/src/06-faq.mdx
- packages/calcite-components/src/07-conventions.mdx
Fixes the imports of three (3) markdown pages that are broken in Storybook by adding the `raw` query parameter to the end of the import paths.
Currently, the pages display one long base64 encoded string instead of properly formatted Markdown.
1. [Licensing](https://esri.github.io/calcite-design-system/?path=/docs/overview-licensing--docs)
2. [FAQs](https://esri.github.io/calcite-design-system/?path=/docs/overview-faq--docs)
3. [Conventions](https://esri.github.io/calcite-design-system/?path=/docs/overview-conventions--docs)
> docs(storybook): fix markdown imports by adding `raw` query parameter

- package-lock.json
- packages/calcite-components-react/package.json
- packages/calcite-components/package.json
Automated next deployments were failing because the cherry-picked [release commit](https://github.com/Esri/calcite-design-system/pull/12247) reverted the version to an earlier patch, which caused a conflict when calculating the next version.
> ci: fix next deployments by restoring version

- packages/calcite-components/src/components/input-time-picker/input-time-picker.tsx
- packages/calcite-components/src/components/input-time-picker/resources.ts
**Related Issue:** #12153
This PR fixes an issue where NVDA and JAWS don't read out the `aria-label` set on `calcite-input-time-picker`.
> fix(input-time-picker): apply aria-label and aria-controls attributes correctly to support NVDA and JAWS

- package-lock.json
- packages/calcite-components/package.json
Similar to https://github.com/Esri/calcite-design-system/pull/12318, automated next deployments for the icons, tokens and ESLint plugin packages were stalled due to the cherry-picked [release commit](https://github.com/Esri/calcite-design-system/pull/12247) that ended up reverting them to earlier, non-next versions.
> build: restore usage of monorepo package dependencies

- packages/calcite-design-tokens/tsconfig-base.json
- packages/calcite-design-tokens/tsconfig.json
The design tokens package can now enable `strict` in its `tsconfig.json` and remove `typescript-strict-plugin`.
> chore(tokens): enable `strict` and drop `typescript-strict-plugin`

- packages/calcite-components/tailwind.config.ts
- packages/calcite-tailwind-preset/src/index.ts
Uses design-token CSS props for focus width and offset in custom Tailwind focus utils.
> refactor: wire up design tokens in custom Tailwind focus utils

- package-lock.json
- package.json
- packages/calcite-components/.storybook/manager.ts
This removes logic that stripped hydrated-related attributes for the HTML preview. Since our storybook setup is internal and meant for testing, this is no longer needed.
**Note**: this drops the [`cheerio`](https://npmjs.com/package/cheerio) package as well.
> chore(storybook): html preview attribute cleanup

- packages/calcite-components/src/components/input-time-zone/input-time-zone.e2e.ts
- packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx
- packages/calcite-components/src/utils/openCloseComponent.ts
**Related Issue:** #12375 
This fixes a regression caused by #10980 (label update flicker) and #11965 (scroll delay).
**Note**: `openCloseComponent` was updated to ensure the component state is in sync when the events are emitted.
> fix(input-time-zone): fix selected time zone label flicker and scroll delay for region mode

- packages/calcite-components/src/assets/styles/_floating-ui.scss
- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
- packages/calcite-components/src/tests/commonTests/openClose.ts
**Related Issue:** #12399, #10227
This fixes an issue where initial animations would be interrupted on DOM attachment.
* bumps `--calcite-duration-factor` to 3 for `openClose` test util animation-enabled tests
* simplifies `floating-ui.scss`
* uses [`@starting-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style) and [`transition-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior) to help with animation consistency
* baseline supported Safari version will go from 17.4 to 18 in our 2025.R3 release
> fix: ensure initial transitions are applied consistently

- packages/calcite-components/src/components/date-picker/date-picker.tsx
- packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
This drops a guard against `localeData` used in rendering. This prop is [initialized and awaited on during `load`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx#L457), so there's no need to check for its existence.
> refactor(date-picker, input-date-picker): drop checks for required localeData prop

- packages/calcite-components/.stylelintrc.cjs
- packages/calcite-components/src/assets/styles/includes.scss
- packages/calcite-components/src/components/modal/modal.scss
- packages/calcite-components/src/components/panel/panel.scss
- packages/calcite-components/src/components/shell-panel/shell-panel.scss
- packages/calcite-components/src/components/tip/tip.scss
The `base-component` mixin includes common hidden styles, so separate selectors aren’t needed.  
**Note**: this also enables stylelint’s `selector-attribute-name-disallowed-list` rule to help enforce it.
> refactor: drop redundant hidden styles

- packages/calcite-components/src/components/input-number/input-number.e2e.ts
- packages/calcite-components/src/components/input-number/input-number.scss
- packages/calcite-components/src/custom-theme/input-number.ts
- packages/calcite-components/src/demos/input-number.html
**Related Issue:** #12408 
No longer inherits `icon` color from `--calcite-input-actions-icon-color` & adds `--calcite-input-number-icon-color` token to customize `icon` color in `input-number`.
> fix(input-number): add token to customize icon color

- packages/calcite-design-tokens/src/build/transforms/attribute/platform-names.ts
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
Ensures consistent casing conversion by using `change-case`, which is more robust than `lodash-es`'s utils (see https://github.com/Esri/calcite-design-system/pull/12445).
**Note**: this also fixes generated ES6 token names for internal build outputs (`js` and `docs`). Compare https://app.unpkg.com/@esri/calcite-design-tokens@3.1.0/files/dist/es6/global.js#L300 (`calciteTypographyLightMinus3H`) ❌ with https://unpkg.com/@esri/calcite-design-tokens@3.1.0/dist/docs/global.json) (`calciteTypographyLightMinus3h`) ✅.
> chore: use change-case for all casing conversions

- packages/calcite-components/conventions/Internationalization.md
Fixes the following `markdownlint-cli2` error:
```
conventions/Internationalization.md:35:135 MD059/descriptive-link-text Link text should be descriptive [Context: "[here]"]
```
> chore: fix markdown linting error

- packages/calcite-components/src/components/autocomplete/autocomplete.e2e.ts
- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
**Related Issue:** #12433
- announce result to screen readers using aria-live attribute
> fix(autocomplete): announce result to screen readers using aria-live attribute

- packages/calcite-components/CHANGELOG_BETA.md
- packages/calcite-components/eslint.config.mjs
- packages/calcite-components/src/controllers/useCancelable.ts
- packages/calcite-components/src/utils/floating-ui.ts
**Related Issue:** #12431
Enforce usage of the `useCancelable` controller via linting.
> refactor: enforce usage of `useCancelable` controller via linting

- packages/calcite-design-tokens/src/tokens/semantic/color/dark.json
- packages/calcite-design-tokens/src/tokens/semantic/color/light.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #12390 
- "Renames" `--calcite-color-foreground-highlight` to `--calcite-color-surface-highlight`
Changelog updated in #12266
> refactor(semantic-tokens):  rename `--calcite-color-foreground-highlight` to `--calcite-color-surface-highlight`

- packages/calcite-components/src/utils/dom.browser.spec.ts
- packages/calcite-components/src/utils/dom.ts
Restores `currentTarget` usage in slot utils introduced in https://github.com/Esri/calcite-design-system/pull/9768, which was unintentionally removed by https://github.com/Esri/calcite-design-system/pull/9374/files#diff-289d1884a42555c239e4e403d4ea7d10b281307f0eeda6da7e9c573c9bcaffc7.
Depending on the slot structure, `target` will not be the expected slot (see https://codepen.io/jcfranco/pen/WbQegmz).
* converted `dom` util test suite to browser-mode spec test
* updated `getStylePixelValue` logic to avoid precision errors causing test failure
* update `slotChangeGetAssignedElements` and `slotChangeGetAssignedNodes` tests to use browser - other utils should follow suit
> refactor(dom): restore currentTarget in slot utils

- packages/calcite-components/src/components/slider/slider.tsx
**Related Issue:** #12132
This PR fixes an issue where the fill color of the last dragged handle in the slider doesn't reset after dragging and focus has moved away from the handle.
> fix(slider): remove fill color when dragged handle is released and no longer has focus

- packages/calcite-design-tokens/src/tokens/semantic/color/dark.json
- packages/calcite-design-tokens/src/tokens/semantic/color/light.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #12390
- updates the deprecation comment for `--calcite-color-foreground-current` to recommend using `--calcite-color-surface-highlight`
- "foreground" -> "surface"
> refactor(semantic-tokens): update deprecation comment for --calcite-color-foreground-current

- .prettierignore
- packages/calcite-components/.prettierignore
- packages/calcite-design-tokens/.prettierignore
Consolidates ignore files as Prettier will [honor `.gitignore` by default](https://prettier.io/blog/2023/07/05/3.0.0.html#cli) and needs its ignore file to be at the root since it [does not allow for hierarchical configuration](https://github.com/prettier/prettier/issues/4081).
> chore(linting): consolidate prettier ignore files

- packages/calcite-components/conventions/Accessibility.md
**Related Issue:** https://github.com/Esri/calcite-design-system/issues/12538
Fixes the a11y convention documentation page, which was previously showcasing the CSS in the markdown in GitHub's UI.
A preview can be viewed on the branch in [this markdown file](https://github.com/Esri/calcite-design-system/blob/geospatialem/docs-a11y-convention/packages/calcite-components/conventions/Accessibility.md).
| Before | After |
| ----------- | ----------- |
| <img width="1587" height="453" alt="image" src="https://github.com/user-attachments/assets/e5d5e03b-17bc-4083-9080-5100e138740f" />| <img width="1589" height="755" alt="image" src="https://github.com/user-attachments/assets/27752d57-1140-4a93-a2da-47fbc41a5a38" />|
> docs(conventions): fix a11y conventions styling

- packages/calcite-components/src/components/popover/popover.e2e.ts
- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/src/custom-theme/popover.ts
**Related Issue:** #12319
- add token for specifying the max width
- add test
> feat(popover): add token for specifying the max width

- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
This restores doc unintentionally removed in https://github.com/Esri/calcite-design-system/pull/12555.
> docs: restore unintentionally removed options param doc for `scrollContentTo`

- CONTRIBUTING.md
**Related Issue:** #12334
Updates contributing guidance and includes new roles and responsibilities for users and contributors to the calcite-design-system repo. Also includes minor language tweaks and updated links throughout the contribution file.
Explore a [preview of the markdown page](https://github.com/Esri/calcite-design-system/blob/geospatialem/docs-contributing-governance/CONTRIBUTING.md) available for viewing.
> docs(contributing): update roles and responsibilities

- examples/components/vue/vite.config.ts
**Related Issue:** #12522
Resolves "Failed to resolve component: xxx" console warnings by telling Vite to treat all tags that include `calcite-' as custom elements.
Utilizes [Vue's recommended approach](https://vuejs.org/guide/extras/web-components#example-vite-config) for using custom elements.
> docs(examples): treat tags including `calcite-` as custom elements

- package-lock.json
- packages/calcite-components-react/package.json
- packages/calcite-components/package.json
**Related Issue:** #12613
Unpins the `lit` dependency, which will allow more flexibility with downstream packages that are consuming both calcite and lumina
> chore(deps): unpin lit dependency

- packages/calcite-components/src/components/accordion-item/accordion-item.e2e.ts
- packages/calcite-components/src/components/accordion-item/accordion-item.tsx
- packages/calcite-components/src/components/action-bar/action-bar.e2e.ts
- packages/calcite-components/src/components/action-bar/action-bar.tsx
- packages/calcite-components/src/components/action-group/action-group.e2e.ts
- packages/calcite-components/src/components/action-group/action-group.tsx
- packages/calcite-components/src/components/action-menu/action-menu.e2e.ts
- packages/calcite-components/src/components/action-menu/action-menu.tsx
- packages/calcite-components/src/components/action-pad/action-pad.e2e.ts
- packages/calcite-components/src/components/action-pad/action-pad.tsx
- packages/calcite-components/src/components/block-section/block-section.e2e.ts
- packages/calcite-components/src/components/block-section/block-section.tsx
- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/flow-item/flow-item.e2e.ts
- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/components/shell-panel/shell-panel.e2e.ts
- packages/calcite-components/src/components/shell-panel/shell-panel.tsx
- packages/calcite-components/src/components/tree-item/tree-item.e2e.ts
- packages/calcite-components/src/components/tree-item/tree-item.tsx
**Related Issue:** #12565
Emit `expanded`/`collapsed` end-state events for expandable components.
`action-bar`
`action-group`
`action-menu`
`action-pad`
`panel`
`accordion-item`
`block`
`block-section`
`list-item`
`tree-item`
> feat: emit `expanded`/`collapsed` end-state events for expandable components

- packages/calcite-components/src/components/flow-item/flow-item.tsx
**Related Issue:** [#12551](https://github.com/Esri/calcite-design-system/issues/12551) 
Updated beforeBack() to be optional as per the description.
> docs(flow-item): `beforeBack` property should be optional

- packages/calcite-components/support/updateT9nManifest.ts
- t9nmanifest.txt
Fixes `updateT9nManifest` script which referenced `packages/calcite-components`  prior to https://github.com/Esri/calcite-design-system/pull/12529 . With https://github.com/Esri/calcite-design-system/pull/12529, reference directory is set to monorepo root.
> chore(t9n): fix `update-t9n-manifest` script

- packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #12583
prevent drag flickering while sorting
> fix(list): prevent drag flickering while sorting

- packages/calcite-components/src/assets/styles/_sortable.scss
**Related Issue:** #12204
- restores CSS we had removed to handle a firefox bug
- see https://github.com/Esri/calcite-design-system/pull/11883
> fix(list): fix visual artifacts when you initiate a drag operation with the drag handle menu open

- packages/calcite-components/src/components/popover/popover.scss
- packages/calcite-components/vite.config.ts
Restores deprecated warnings prematurely removed in https://github.com/Esri/calcite-design-system/pull/12465/files#diff-50e581eb0e72b23e2222ae7118aad3c0a006d398318cb468fef90c04be473012L77-L82. 
Also addresses a new `mixed-decls` warning introduced in https://github.com/Esri/calcite-design-system/pull/12516:
> @esri/calcite-components:build: Deprecation Warning [mixed-decls]: Sass's behavior for declarations that appear after nested
@esri/calcite-components:build: rules will be changing to match the behavior specified by CSS in an upcoming
@esri/calcite-components:build: version. To keep the existing behavior, move the declaration above the nested
@esri/calcite-components:build: rule. To opt into the new behavior, wrap the declaration in `& {}`. …
> chore: restore sass deprecation warning silencing

- packages/calcite-components/src/components/block-group/block-group.e2e.ts
- packages/calcite-components/src/components/block-group/block-group.tsx
- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/list-item/list-item.e2e.ts
- packages/calcite-components/src/components/list-item/list-item.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/components/sort-handle/sort-handle.e2e.ts
- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
- packages/calcite-components/src/components/tree/tree.e2e.ts
- packages/calcite-components/src/demos/sortable-list.html
- packages/calcite-components/src/utils/sortableComponent.ts
**Related Issue:** #11953
- add `sortDisabled` property to `list`, `block-group` and `sort-handle` components
- It is now possible to disable internal sorting in the above components
- When internal sorting is disabled, list items can still be dragged to other lists via menu or pointer device
- When internal sorting is disabled, the drag-handle-menu "Reorder" section is hidden
- If no reordering items or move to items are available the action/dropdown menu is disabled
- add tests
> feat(list, block-group, sort-handle): add sortDisabled property to prevent reordering

- packages/calcite-ui-icons/bin/server.js
Fixes missed import from https://github.com/Esri/calcite-design-system/pull/12639.
> chore(icons): update missed es-toolkit import

- packages/calcite-components/src/custom-theme/panel.ts
- packages/calcite-components/src/custom-theme/shell-panel.ts
Some custom theme components were referencing a `icon{1,3}` icon, which does not exist.
> test(custom-theme): fix non-existent icon names

- .husky/pre-commit
Improves DX by auto-committing auto-generated internal custom CSS prop doc updates.
> chore: ensure auto-generated internal custom CSS prop doc is committed by precommit hook

- packages/calcite-components/src/components/input-number/input-number.scss
- packages/calcite-components/src/components/input-number/input-number.stories.ts
- packages/calcite-components/src/components/input-number/input-number.tsx
- packages/calcite-components/src/components/input-text/input-text.scss
- packages/calcite-components/src/components/input-text/input-text.stories.ts
- packages/calcite-components/src/components/input-text/input-text.tsx
**Related Issue:** [#12419](https://github.com/Esri/calcite-design-system/issues/12419)
Allow `center` value in the `alignment` prop in `calcite-input-number` and `calcite-input-text`.
> feat(input-number, input-text): add center alignment

- packages/calcite-components/src/components/action/action.tsx
**Related Issue:** #12599
Updates `action`'s default slot description to fit more use cases for non-interactive content.
> docs(action): update unnamed slot description to fit more use cases

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/custom-theme/block.ts
**Related Issue:** [#12088](https://github.com/Esri/calcite-design-system/issues/12088)
Add `--calcite-block-content-space` css token to replace deprecated `--calcite-block-content-padding` token.
> feat(block): add --calcite-block-content-space css token

- packages/calcite-components/src/components/loader/loader.scss
Update the description of the `--calcite-loader-size` token to accurately reflect the actual behavior.
> docs: update loader size token description

- packages/calcite-components/src/components/card/card.e2e.ts
- packages/calcite-components/src/components/card/card.tsx
**Related Issue:** #12714 
Fixes issue where `setFocus` would target focusable children instead of the card itself.
> fix(card): ensure `setFocus` focuses card when it contains nested interactive children

- package-lock.json
- packages/calcite-components/package.json
After the latest updates to `input-time-picker`, [`dayjs`](https://www.npmjs.com/package/dayjs) is no longer needed.
> chore(deps): drop dayjs

- packages/calcite-components/src/components/color-picker-swatch/color-picker-swatch.tsx
- packages/calcite-components/src/components/swatch/swatch.tsx
**Related Issue:** #12734 
Deprecates Color Picker Swatch
> docs(color-picker-swatch): Deprecate component

- packages/calcite-components/src/components/date-picker/date-picker.e2e.ts
- packages/calcite-components/src/components/date-picker/date-picker.tsx
**Related Issue:** [#10329](https://github.com/Esri/calcite-design-system/issues/10329)
Ensure `minAsDate` and `maxAsDate` are used in date logic when provided.
* updates `DatePicker#willUpdate` to use `min`/`max` OR `minAsDate`/`maxAsDate` for internal state
* removes redundant prop update on `connectedCallback`/`load` (this is handled by `willUpdate`)
* ensures user local time is used in tests that depend on current date – fixes incorrect assertions using dates affected by UTC vs local time context
* adds local test helpers for common date handling
* moves test helpers to component `describe` block for consistency
* tidy up
> fix(date-picker): honor `minAsDate` & `maxAsDate` when set

- packages/calcite-components/src/components/autocomplete/autocomplete.tsx
- packages/calcite-components/src/components/combobox/combobox.tsx
- packages/calcite-components/src/components/dialog/dialog.tsx
- packages/calcite-components/src/components/list/list.tsx
- packages/calcite-components/src/components/modal/modal.tsx
- packages/calcite-components/src/components/sheet/sheet.tsx
- packages/calcite-components/src/components/sort-handle/sort-handle.tsx
Per the [Lit docs](https://lit.dev/docs/components/properties/#internal-reactive-state), `state` is meant for internal reactive state that the component manages itself. 
The [implementation](https://github.com/lit/lit/blob/main/packages/reactive-element/src/decorators/state.ts) and the [tests](https://github.com/lit/lit/blob/main/packages/reactive-element/src/test/decorators/state_test.ts) show that it only works when the value is set by the component.
> refactor: drop futile `state()` usage

- packages/calcite-components/src/components/combobox/combobox.scss
**Related Issue:** #10409
Adjust padding for no-matches context.
> fix(combobox): adjust padding for no-matches context

- packages/calcite-components/src/components/block-group/block-group.e2e.ts
- packages/calcite-components/src/components/block-group/block-group.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #12490
- Emit `calciteListOrderChange` on the destination list for move
- Emit `calciteListOrderChange` on the destination list for add
- adds tests
> fix(list, block-group): emit calciteListOrderChange on destination when adding or moving from the menu

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
**Related Issue:** #12633 
Customize heading text color when expanded using `--calcite-block-heading-text-color` token.
Example:
```
calcite-block[expanded] {
--calcite-heading-text-color:  blue;
}
```
Deprecates following tokens in block:
- --calcite-block-text-color
- --calcite-block-heading-text-color-press
> fix(block): allow customizing heading text color when expanded & deprecate tokens

- packages/calcite-components/src/components/panel/panel.scss
**Related Issue:** #12785
- alert slot should not take up any height
> fix(panel): alert slot should not take up any height

- packages/calcite-components/src/components/block/block.e2e.ts
- packages/calcite-components/src/components/block/block.scss
- packages/calcite-components/src/components/block/block.stories.ts
- packages/calcite-components/src/components/block/block.tsx
- packages/calcite-components/src/components/block/resources.ts
**Related Issue:** #12797 
No longer renders an empty header when below configurable options are empty or set to false.
- heading
- description
- icon-start
- content-start slot
- status
- loading
> fix(block): no longer renders an empty header

- packages/calcite-components/src/components/flow-item/flow-item.tsx
- packages/calcite-components/src/components/slider/slider.tsx
- packages/calcite-components/src/components/stepper-item/stepper-item.tsx
**Related Issue:** #12711
Cleans up some minor boolean property documentation for consistency, based on feedback from #12791.
- **docs(stepper-item): add period to property doc for consistency**
- **docs(slider, flow-item): use "component" instead of component's name for consistency**
> docs(slider, stepper-item, flow-item): feedback changes for boolean property consistency

- .github/ISSUE_TEMPLATE/new-component.yml
Adds the `design` label to the new component issue template, so design can be consulted as soon as the issue is created to decide if design expertise is needed in the request.
> chore: add design label to new component issue template

- .renovaterc.json
The version with `latest` dist tag for `@arcgis/toolkit` is marked as deprecated, which is preventing Renovate from grabbing updates.
ref: https://docs.renovatebot.com/configuration-options#ignoreunstable
> ci(renovate): allow prerelease bumps for arcgis deps

- packages/calcite-design-tokens/src/tokens/core/size.json
- packages/calcite-design-tokens/src/tokens/semantic/font.json
- packages/calcite-design-tokens/tests/spec/__snapshots__/index.spec.ts.snap
**Related Issue:** #12827
- add core token `--calcite-size-relative-normal` with the value `normal`
- update semantic token `--calcite-font-line-height-relative` to reference `--calcite-size-relative-normal`
> fix(tokens): update `--calcite-font-line-height-relative` to resolve as a valid value

- packages/calcite-components/src/components/carousel/carousel.tsx
- packages/calcite-components/src/components/color-picker/color-picker.tsx
- packages/calcite-components/src/components/sortable-list/sortable-list.tsx
- packages/calcite-components/src/components/tab-title/tab-title.tsx
- packages/calcite-components/src/components/table/table.tsx
**Related Issue:** #12711
Updates boolean attribute description for consistency that were identified during verification for `carousel`, `color-picker`, `sortable-list` (undoc'd), `tab-title` and `table`.
> docs: boolean property context consistency

- package-lock.json
- package.json
- packages/calcite-components/.storybook/main.ts
**Related Issue:** #12472 
Restores `@whitespace/storybook-addon-html` now that it [supports v9](https://github.com/whitespace-se/storybook-addon-html/issues/141#issuecomment-3234790740).
> chore(storybook): restore `@whitespace/storybook-addon-html`

- packages/calcite-components/conventions/Documentation.md
**Related Issue:** #12711
With the effort to clarify the usage of boolean attributes, updates the Documentation Style Guide to include a rule for the recommended "When present, ..." wording.
> docs(conventions): add boolean attribute rule to Documentation Style Guide

- packages/calcite-components/src/components/block-group/block-group.e2e.ts
- packages/calcite-components/src/components/block-group/block-group.tsx
- packages/calcite-components/src/components/list/list.e2e.ts
- packages/calcite-components/src/components/list/list.tsx
**Related Issue:** #12847
- Update menu items when menu is opened
- Add tests
> fix(list, block-group): sort handle menu should respond to new lists or label changes

- packages/calcite-components/src/components/accordion-item/accordion-item.scss
- packages/calcite-components/src/components/accordion-item/accordion-item.tsx
- packages/calcite-components/src/components/accordion-item/resources.ts
- packages/calcite-components/src/components/accordion/accordion.stories.ts
**Related Issue:** [#10444](https://github.com/Esri/calcite-design-system/issues/10444)
Add `content-start` and `content-end` slots.
> feat(accordion-item): add content-start and content-end slots

- packages/calcite-components/src/components/swatch/swatch.e2e.ts
- packages/calcite-components/src/components/swatch/swatch.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/swatch-group.ts
- packages/calcite-components/src/custom-theme/swatch.ts
- packages/calcite-components/src/demos/swatch-group.html
**Related Issue:** #12762 
Updates the component to ensure internally rendered svg adhere to user-set `--calcite-swatch-corner-radius`, which became noticeable with certain overrides. 
Adds Swatch Group / Swatch to custom theme story and adds tests.
Before: 
After:
> fix(swatch): Ensure corner radius css property is correctly applied

- packages/calcite-components/src/components/input-time-picker/input-time-picker.e2e.ts
- packages/calcite-components/src/components/input-time-picker/input-time-picker.scss
- packages/calcite-components/src/custom-theme.stories.ts
- packages/calcite-components/src/custom-theme/input-time-picker.ts
- packages/calcite-components/src/demos/input-time-picker.html
`--calcite-input-time-picker-background-color`: Specifies the background color of the component.
`--calcite-input-time-picker-border-color`: Specifies the component's border color.
`--calcite-input-time-picker-icon-color`: Specifies the component's icon color.
`--calcite-input-time-picker-icon-color-hover`: Specifies the component's icon color when hovered.
`--calcite-input-time-picker-shadow`: Specifies the component's shadow.
`--calcite-input-time-picker-corner-radius`: Specifies the border radius of the component.
`--calcite-input-time-picker-input-background-color`: Specifies the component's input background color.
`--calcite-input-time-picker-input-border-color`: Specifies the component's input border color.
`--calcite-input-time-picker-input-text-color`: …
> feat(input-time-picker): Add component tokens

- packages/calcite-components/src/components/date-picker-day/date-picker-day.scss
- packages/calcite-components/src/components/table-cell/table-cell.scss
**Related Issue:** [#12482](https://github.com/Esri/calcite-design-system/issues/12482)
Replaced deprecated `color-foreground-current` with `color-surface-highlight` token.
> feat(date-picker, table-cell): update to use color-surface-highlight token

- packages/calcite-components/src/components/inline-editable/inline-editable.e2e.ts
- packages/calcite-components/src/components/inline-editable/inline-editable.tsx
**Related Issue:** #12858 
This prevents tooltips from appearing when the start editing button is hidden during an active edit session.
> fix(inline-editable): prevent interaction with start-editing button when hidden

- .github/scripts/monday/handleReadyForDev.js
- .github/scripts/monday/updateAssignee.js
- .github/scripts/monday/updateLabels.js
- .github/scripts/monday/updateState.js
- .github/scripts/notifyWhenReadyForDev.js
- .github/scripts/support/monday.js
- .github/workflows/issue-monday-sync.yml
- .github/workflows/issue-notifications.yml
**Related Issue:** #12814
After #12820 was merged, a few bugs and logic flaws were discovered. This PR addresses:
- Triggering and handling the Monday.com sync for the "Ready for Dev" automation. Changes made in the automation do not automatically trigger the Monday workflow, so a custom trigger is required.
- Capitalizing "Dev" in the "Ready for Dev" status value to match the Monday board
- Correcting Abraham's Monday ID to properly assign tasks to him
- Properly skipping the "needs triage" label in the logic
- Skipping the "new" and "assigned" labels when syncing to Monday, as they are not needed. These skips will be removed once our labels change.
- Passing HTTP error information instead of the issue body for better error handling
- Abstracting state handling and including the …
> ci(actions): fix Monday sync bugs and trigger sync from `ready for dev` action

- packages/calcite-components/src/components/dropdown-group/dropdown-group.e2e.ts
- packages/calcite-components/src/components/dropdown-group/dropdown-group.scss
- packages/calcite-components/src/components/dropdown-group/dropdown-group.tsx
- packages/calcite-components/src/components/dropdown-group/resources.ts
- packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
**Related Issue:** [#10783](https://github.com/Esri/calcite-design-system/issues/10783)
Update group-title color to `--calcite-color-text-1`.
Update padding-block of group-title at each scale. padding-inline matches that of Dropdown Item at each scale.
Use a single divider between groups.
> feat(dropdown-group): update design for 4.0

- .github/scripts/monday/removeLabel.js
- .github/scripts/support/monday.js
- .github/scripts/support/resources.js
- .github/workflows/issue-monday-sync.yml
**Related Issue:** #12814
- Add `design-tokens` and `calcite-design-tokens` labels to `resources.js`
- Sync these tokens to the "Design Tokens" Monday column, allowing removal but only if neither of them are still present on the issue.
> ci(actions): sync design tokens labels to Monday

- packages/calcite-components/src/components/list-item/list-item.tsx
**Related Issue:** #12818 
This fixes a memory leak caused by `calcite-list-item`'s [`focusMap`](https://github.com/Esri/calcite-design-system/blob/8cc130d4bc496809d53ee4bd31da204ceb9a26b8/packages/calcite-components/src/components/list-item/list-item.tsx#L35) holding on to list elements and not being cleared when removed from the DOM.
Our test environment doesn't cover memory profiling, so no tests were added.
> fix(list-item): fix memory leak caused by focusing before disconnecting

- .github/scripts/support/monday.js
**Related Issue:** #12814
Fixes all Monday.com API queries by passing the query variables object in the `body` using the `variables` property/key.
> ci(actions): pass query variables explicitly as property named `variables`

- packages/calcite-components/src/components/panel/panel.e2e.ts
- packages/calcite-components/src/components/panel/panel.stories.ts
- packages/calcite-components/src/components/panel/panel.tsx
- packages/calcite-components/src/demos/panel.html
**Related Issue:** #12894 
Ensures `action-bar` and `content-top` slots display when populated.
> fix(panel): Ensure `content-top` and `action-bar` slots are visible

- packages/calcite-components/src/components/dropdown/dropdown.e2e.ts
- packages/calcite-components/src/components/dropdown/dropdown.tsx
- packages/calcite-components/src/components/interfaces.ts
**Related Issue:** #12947  
Cleans up code related to supporting multiple triggers.  
**Note:** The component now uses Lit’s [`queryAssignedElements`](https://lit.dev/docs/api/decorators/#queryAssignedElements) decorator. Since this API always returns an array, the property is typed as a single-element array to both simplify the code and help catch improper usage. The property name remains singular, but we can update it if a plural form feels more accurate.
> refactor(dropdown): drop multi-trigger handling logic

- packages/calcite-components/conventions/Documentation.md
**Related Issue:** #12711
Reverts the Style Guide recommendatations for boolean properties to use "When `true`, xxx" wording instead of "When present, xxx."
> docs(conventions): revert boolean guidelines to "When `true`, xxx"

- packages/calcite-components/src/components/color-picker/color-picker.scss
- packages/calcite-components/src/components/date-picker/date-picker.scss
**Related Issue:** [#10768](https://github.com/Esri/calcite-design-system/issues/10768)
Update `border-color` to `--calcite-color-border-3`.
> feat(color-picker, date-picker): adjust outline color for 4.0

- .github/workflows/deploy.yml
**Related Issue:** #12991
`next` releases are failing with the following error:
> Two-factor authentication is required to publish this package but an automation token was specified
I'm guessing this is because I didn't remove the token environment variables when setting up the repo as trusted publisher. 
If this doesn't fix the issue, I'll revert and do some testing in a different repo.
> ci(deploy): remove the npm token environment variables

- .github/workflows/deploy-latest.yml
- .github/workflows/deploy-prerelease.yml
- .github/workflows/deploy.yml
**Related Issue:** #12998 #12991
Revert the changes to the deployment workflows due to `next` failures. There is a new error:
> lerna WARN notice Package failed to publish: @esri/calcite-components
> lerna ERR! E404 Not found
> lerna ERR! errno "undefined" is not a valid exit code - exiting with code 1
> revert: use a granular npm token for deployment

- packages/calcite-components/src/components/table-row/table-row.scss
**Related Issue:** #13024
Adds back the deprecated `--calcite-table-row-background` token as a fallback until it is removed in a breaking change release.
> fix(table-row): add deprecated background token as fallback

- packages/calcite-components/src/components/button/button.scss
- packages/calcite-components/src/components/split-button/split-button.scss
**Related Issue:** #13039
Removes the `/or` wording from `button` and `split-button` `xxx-icon-color` token docs to avoid the Lumina API generator from cuttin the strings short.
> docs(button, split-button): reword `icon-color` token docs to avoid forward slash

- package-lock.json
- package.json
- packages/calcite-components-react/package.json
- packages/calcite-components/package.json
- packages/calcite-tailwind-preset/package.json
- release-please-config.json
* Keeps `@arcgis` dependencies within supported range
* Updates `@esri/calcite-tailwind-preset`'s peer dep
* Enables [`release-please` peer dep bumps](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#linking-peer-dependencies)
> build(deps): tweak dep ranges

- packages/calcite-components/src/components/button/button.e2e.ts
- packages/calcite-components/src/components/button/button.scss
**Related Issue:** #13038 
Add back support for `--calcite-ui-icon-color`.
Issue is resolved by this [update](https://devtopia.esri.com/WebGIS/arcgis-js-api/pull/74895#issuecomment-5829349) to use `--calcite-icon-color` instead of `--calcite-ui-icon-color`. This fix will help resolve similar use cases.
> fix(button): add backward compatibility for `--calcite-ui-icon-color` token
